/*
 Platform.js <https://mths.be/platform>
 Copyright 2014-2018 Benjamin Tan <https://bnjmnt4n.now.sh/>
 Copyright 2011-2013 John-David Dalton
 Available under MIT license <https://mths.be/mit>
*/
(function(){function a(m){m=String(m);return m.charAt(0).toUpperCase()+m.slice(1)}function c(m,N){var H=-1,D=m?m.length:0;if("number"==typeof D&&-1<D&&D<=y)for(;++H<D;)N(m[H],H,m);else d(m,N)}function b(m){m=String(m).replace(/^ +| +$/g,"");return/^(?:webOS|i(?:OS|P))/.test(m)?m:a(m)}function d(m,N){for(var H in m)F.call(m,H)&&N(m[H],H,m)}function e(m){return null==m?a(m):v.call(m).slice(8,-1)}function f(m,N){var H=null!=m?typeof m[N]:"number";return!/^(?:boolean|number|string|undefined)$/.test(H)&&
("object"==H?!!m[N]:!0)}function g(m){return String(m).replace(/([ -])(?!$)/g,"$1?")}function l(m,N){var H=null;c(m,function(D,C){H=N(H,D,C,m)});return H}function r(m){function N(S){return l(S,function(O,M){var U=M.pattern||g(M);!O&&(O=RegExp("\\b"+U+" *\\d+[.\\w_]*","i").exec(m)||RegExp("\\b"+U+" *\\w+-[\\w]*","i").exec(m)||RegExp("\\b"+U+"(?:; *(?:[a-z]+[_-])?[a-z]+\\d+|[^ ();-]*)","i").exec(m))&&((O=String(M.label&&!RegExp(U,"i").test(M.label)?M.label:O).split("/"))[1]&&!/[\d.]+/.test(O[0])&&(O[0]+=
" "+O[1]),M=M.label||M,O=b(O[0].replace(RegExp(U,"i"),M).replace(RegExp("; *(?:"+M+"[_-])?","i")," ").replace(RegExp("("+M+")[-_.]?(\\w)","i"),"$1 $2")));return O})}function H(S){return l(S,function(O,M){return O||(RegExp(M+"(?:-[\\d.]+/|(?: for [\\w-]+)?[ /-])([\\d.]+[^ ();/_-]*)","i").exec(m)||0)[1]||null})}var D=p,C=m&&"object"==typeof m&&"String"!=e(m);C&&(D=m,m=null);var R=D.navigator||{},w=R.userAgent||"";m||(m=w);var P=C?!!R.likeChrome:/\bChrome\b/.test(m)&&!/internal|\n/i.test(v.toString()),
Q=C?"Object":"ScriptBridgingProxyObject",K=C?"Object":"Environment",z=C&&D.java?"JavaPackage":e(D.java),L=C?"Object":"RuntimeObject";K=(z=/\bJava/.test(z)&&D.java)&&e(D.environment)==K;var T=z?"a":"\u03b1",Z=z?"b":"\u03b2",aa=D.document||{},I=D.operamini||D.opera,E=k.test(E=C&&I?I["[[Class]]"]:e(I))?E:I=null,h,Y=m;C=[];var V=null,x=m==w;w=x&&I&&"function"==typeof I.version&&I.version();var G=function(S){return l(S,function(O,M){return O||RegExp("\\b"+(M.pattern||g(M))+"\\b","i").exec(m)&&(M.label||
M)})}([{label:"EdgeHTML",pattern:"Edge"},"Trident",{label:"WebKit",pattern:"AppleWebKit"},"iCab","Presto","NetFront","Tasman","KHTML","Gecko"]),u=function(S){return l(S,function(O,M){return O||RegExp("\\b"+(M.pattern||g(M))+"\\b","i").exec(m)&&(M.label||M)})}(["Adobe AIR","Arora","Avant Browser","Breach","Camino","Electron","Epiphany","Fennec","Flock","Galeon","GreenBrowser","iCab","Iceweasel","K-Meleon","Konqueror","Lunascape","Maxthon",{label:"Microsoft Edge",pattern:"Edge"},"Midori","Nook Browser",
"PaleMoon","PhantomJS","Raven","Rekonq","RockMelt",{label:"Samsung Internet",pattern:"SamsungBrowser"},"SeaMonkey",{label:"Silk",pattern:"(?:Cloud9|Silk-Accelerated)"},"Sleipnir","SlimBrowser",{label:"SRWare Iron",pattern:"Iron"},"Sunrise","Swiftfox","Waterfox","WebPositive","Opera Mini",{label:"Opera Mini",pattern:"OPiOS"},"Opera",{label:"Opera",pattern:"OPR"},"Chrome",{label:"Chrome Mobile",pattern:"(?:CriOS|CrMo)"},{label:"Firefox",pattern:"(?:Firefox|Minefield)"},{label:"Firefox for iOS",pattern:"FxiOS"},
{label:"IE",pattern:"IEMobile"},{label:"IE",pattern:"MSIE"},"Safari"]),J=N([{label:"BlackBerry",pattern:"BB10"},"BlackBerry",{label:"Galaxy S",pattern:"GT-I9000"},{label:"Galaxy S2",pattern:"GT-I9100"},{label:"Galaxy S3",pattern:"GT-I9300"},{label:"Galaxy S4",pattern:"GT-I9500"},{label:"Galaxy S5",pattern:"SM-G900"},{label:"Galaxy S6",pattern:"SM-G920"},{label:"Galaxy S6 Edge",pattern:"SM-G925"},{label:"Galaxy S7",pattern:"SM-G930"},{label:"Galaxy S7 Edge",pattern:"SM-G935"},"Google TV","Lumia","iPad",
"iPod","iPhone","Kindle",{label:"Kindle Fire",pattern:"(?:Cloud9|Silk-Accelerated)"},"Nexus","Nook","PlayBook","PlayStation Vita","PlayStation","TouchPad","Transformer",{label:"Wii U",pattern:"WiiU"},"Wii","Xbox One",{label:"Xbox 360",pattern:"Xbox"},"Xoom"]),W=function(S){return l(S,function(O,M,U){return O||(M[J]||M[/^[a-z]+(?: +[a-z]+\b)*/i.exec(J)]||RegExp("\\b"+g(U)+"(?:\\b|\\w*\\d)","i").exec(m))&&U})}({Apple:{iPad:1,iPhone:1,iPod:1},Archos:{},Amazon:{Kindle:1,"Kindle Fire":1},Asus:{Transformer:1},
"Barnes & Noble":{Nook:1},BlackBerry:{PlayBook:1},Google:{"Google TV":1,Nexus:1},HP:{TouchPad:1},HTC:{},LG:{},Microsoft:{Xbox:1,"Xbox One":1},Motorola:{Xoom:1},Nintendo:{"Wii U":1,Wii:1},Nokia:{Lumia:1},Samsung:{"Galaxy S":1,"Galaxy S2":1,"Galaxy S3":1,"Galaxy S4":1},Sony:{PlayStation:1,"PlayStation Vita":1}}),A=function(S){return l(S,function(O,M){var U=M.pattern||g(M);if(!O&&(O=RegExp("\\b"+U+"(?:/[\\d.]+|[ \\w.]*)","i").exec(m))){var X=O,ba=M.label||M,ca={"10.0":"10","6.4":"10 Technical Preview",
"6.3":"8.1","6.2":"8","6.1":"Server 2008 R2 / 7","6.0":"Server 2008 / Vista","5.2":"Server 2003 / XP 64-bit","5.1":"XP","5.01":"2000 SP1","5.0":"2000","4.0":"NT","4.90":"ME"};U&&ba&&/^Win/i.test(X)&&!/^Windows Phone /i.test(X)&&(ca=ca[/[\d.]+$/.exec(X)])&&(X="Windows "+ca);X=String(X);U&&ba&&(X=X.replace(RegExp(U,"i"),ba));O=X=b(X.replace(/ ce$/i," CE").replace(/\bhpw/i,"web").replace(/\bMacintosh\b/,"Mac OS").replace(/_PowerPC\b/i," OS").replace(/\b(OS X) [^ \d]+/i,"$1").replace(/\bMac (OS X)\b/,
"$1").replace(/\/(\d)/," $1").replace(/_/g,".").replace(/(?: BePC|[ .]*fc[ \d.]+)$/i,"").replace(/\bx86\.64\b/gi,"x86_64").replace(/\b(Windows Phone) OS\b/,"$1").replace(/\b(Chrome OS \w+) [\d.]+\b/,"$1").split(" on ")[0])}return O})}(["Windows Phone","Android","CentOS",{label:"Chrome OS",pattern:"CrOS"},"Debian","Fedora","FreeBSD","Gentoo","Haiku","Kubuntu","Linux Mint","OpenBSD","Red Hat","SuSE","Ubuntu","Xubuntu","Cygwin","Symbian OS","hpwOS","webOS ","webOS","Tablet OS","Tizen","Linux","Mac OS X",
"Macintosh","Mac","Windows 98;","Windows "]);G&&(G=[G]);W&&!J&&(J=N([W]));if(h=/\bGoogle TV\b/.exec(J))J=h[0];/\bSimulator\b/i.test(m)&&(J=(J?J+" ":"")+"Simulator");"Opera Mini"==u&&/\bOPiOS\b/.test(m)&&C.push("running in Turbo/Uncompressed mode");"IE"==u&&/\blike iPhone OS\b/.test(m)?(h=r(m.replace(/like iPhone OS/,"")),W=h.manufacturer,J=h.product):/^iP/.test(J)?(u||(u="Safari"),A="iOS"+((h=/ OS ([\d_]+)/i.exec(m))?" "+h[1].replace(/_/g,"."):"")):"Konqueror"!=u||/buntu/i.test(A)?W&&"Google"!=W&&
(/Chrome/.test(u)&&!/\bMobile Safari\b/i.test(m)||/\bVita\b/.test(J))||/\bAndroid\b/.test(A)&&/^Chrome/.test(u)&&/\bVersion\//i.test(m)?(u="Android Browser",A=/\bAndroid\b/.test(A)?A:"Android"):"Silk"==u?(/\bMobi/i.test(m)||(A="Android",C.unshift("desktop mode")),/Accelerated *= *true/i.test(m)&&C.unshift("accelerated")):"PaleMoon"==u&&(h=/\bFirefox\/([\d.]+)\b/.exec(m))?C.push("identifying as Firefox "+h[1]):"Firefox"==u&&(h=/\b(Mobile|Tablet|TV)\b/i.exec(m))?(A||(A="Firefox OS"),J||(J=h[1])):!u||
(h=!/\bMinefield\b/i.test(m)&&/\b(?:Firefox|Safari)\b/.exec(u))?(u&&!J&&/[\/,]|^[^(]+?\)/.test(m.slice(m.indexOf(h+"/")+8))&&(u=null),(h=J||W||A)&&(J||W||/\b(?:Android|Symbian OS|Tablet OS|webOS)\b/.test(A))&&(u=/[a-z]+(?: Hat)?/i.exec(/\bAndroid\b/.test(A)?A:h)+" Browser")):"Electron"==u&&(h=(/\bChrome\/([\d.]+)\b/.exec(m)||0)[1])&&C.push("Chromium "+h):A="Kubuntu";w||(w=H(["(?:Cloud9|CriOS|CrMo|Edge|FxiOS|IEMobile|Iron|Opera ?Mini|OPiOS|OPR|Raven|SamsungBrowser|Silk(?!/[\\d.]+$))","Version",g(u),
"(?:Firefox|Minefield|NetFront)"]));if(h="iCab"==G&&3<parseFloat(w)&&"WebKit"||/\bOpera\b/.test(u)&&(/\bOPR\b/.test(m)?"Blink":"Presto")||/\b(?:Midori|Nook|Safari)\b/i.test(m)&&!/^(?:Trident|EdgeHTML)$/.test(G)&&"WebKit"||!G&&/\bMSIE\b/i.test(m)&&("Mac OS"==A?"Tasman":"Trident")||"WebKit"==G&&/\bPlayStation\b(?! Vita\b)/i.test(u)&&"NetFront")G=[h];"IE"==u&&(h=(/; *(?:XBLWP|ZuneWP)(\d+)/i.exec(m)||0)[1])?(u+=" Mobile",A="Windows Phone "+(/\+$/.test(h)?h:h+".x"),C.unshift("desktop mode")):/\bWPDesktop\b/i.test(m)?
(u="IE Mobile",A="Windows Phone 8.x",C.unshift("desktop mode"),w||(w=(/\brv:([\d.]+)/.exec(m)||0)[1])):"IE"!=u&&"Trident"==G&&(h=/\brv:([\d.]+)/.exec(m))&&(u&&C.push("identifying as "+u+(w?" "+w:"")),u="IE",w=h[1]);if(x){if(f(D,"global"))if(z&&(h=z.lang.System,Y=h.getProperty("os.arch"),A=A||h.getProperty("os.name")+" "+h.getProperty("os.version")),K){try{w=D.require("ringo/engine").version.join("."),u="RingoJS"}catch(S){(h=D.system)&&h.global.system==D.system&&(u="Narwhal",A||(A=h[0].os||null))}u||
(u="Rhino")}else"object"==typeof D.process&&!D.process.browser&&(h=D.process)&&("object"==typeof h.versions&&("string"==typeof h.versions.electron?(C.push("Node "+h.versions.node),u="Electron",w=h.versions.electron):"string"==typeof h.versions.nw&&(C.push("Chromium "+w,"Node "+h.versions.node),u="NW.js",w=h.versions.nw)),u||(u="Node.js",Y=h.arch,A=h.platform,w=(w=/[\d.]+/.exec(h.version))?w[0]:null));else e(h=D.runtime)==Q?(u="Adobe AIR",A=h.flash.system.Capabilities.os):e(h=D.phantom)==L?(u="PhantomJS",
w=(h=h.version||null)&&h.major+"."+h.minor+"."+h.patch):"number"==typeof aa.documentMode&&(h=/\bTrident\/(\d+)/i.exec(m))?(w=[w,aa.documentMode],(h=+h[1]+4)!=w[1]&&(C.push("IE "+w[1]+" mode"),G&&(G[1]=""),w[1]=h),w="IE"==u?String(w[1].toFixed(1)):w[0]):"number"==typeof aa.documentMode&&/^(?:Chrome|Firefox)\b/.test(u)&&(C.push("masking as "+u+" "+w),u="IE",w="11.0",G=["Trident"],A="Windows");A=A&&b(A)}w&&(h=/(?:[ab]|dp|pre|[ab]\d+pre)(?:\d+\+?)?$/i.exec(w)||/(?:alpha|beta)(?: ?\d)?/i.exec(m+";"+(x&&
R.appMinorVersion))||/\bMinefield\b/i.test(m)&&"a")&&(V=/b/i.test(h)?"beta":"alpha",w=w.replace(RegExp(h+"\\+?$"),"")+("beta"==V?Z:T)+(/\d+\+?/.exec(h)||""));if("Fennec"==u||"Firefox"==u&&/\b(?:Android|Firefox OS)\b/.test(A))u="Firefox Mobile";else if("Maxthon"==u&&w)w=w.replace(/\.[\d.]+/,".x");else if(/\bXbox\b/i.test(J))"Xbox 360"==J&&(A=null),"Xbox 360"==J&&/\bIEMobile\b/.test(m)&&C.unshift("mobile mode");else if(!/^(?:Chrome|IE|Opera)$/.test(u)&&(!u||J||/Browser|Mobi/.test(u))||"Windows CE"!=
A&&!/Mobi/i.test(m))if("IE"==u&&x)try{null===D.external&&C.unshift("platform preview")}catch(S){C.unshift("embedded")}else(/\bBlackBerry\b/.test(J)||/\bBB10\b/.test(m))&&(h=(RegExp(J.replace(/ +/g," *")+"/([.\\d]+)","i").exec(m)||0)[1]||w)?(h=[h,/BB10/.test(m)],A=(h[1]?(J=null,W="BlackBerry"):"Device Software")+" "+h[0],w=null):this!=d&&"Wii"!=J&&(x&&I||/Opera/.test(u)&&/\b(?:MSIE|Firefox)\b/i.test(m)||"Firefox"==u&&/\bOS X (?:\d+\.){2,}/.test(A)||"IE"==u&&(A&&!/^Win/.test(A)&&5.5<w||/\bWindows XP\b/.test(A)&&
8<w||8==w&&!/\bTrident\b/.test(m)))&&!k.test(h=r.call(d,m.replace(k,"")+";"))&&h.name&&(h="ing as "+h.name+((h=h.version)?" "+h:""),k.test(u)?(/\bIE\b/.test(h)&&"Mac OS"==A&&(A=null),h="identify"+h):(h="mask"+h,u=E?b(E.replace(/([a-z])([A-Z])/g,"$1 $2")):"Opera",/\bIE\b/.test(h)&&(A=null),x||(w=null)),G=["Presto"],C.push(h));else u+=" Mobile";if(h=(/\bAppleWebKit\/([\d.]+\+?)/i.exec(m)||0)[1]){h=[parseFloat(h.replace(/\.(\d)$/,".0$1")),h];if("Safari"==u&&"+"==h[1].slice(-1))u="WebKit Nightly",V="alpha",
w=h[1].slice(0,-1);else if(w==h[1]||w==(h[2]=(/\bSafari\/([\d.]+\+?)/i.exec(m)||0)[1]))w=null;h[1]=(/\bChrome\/([\d.]+)/i.exec(m)||0)[1];537.36==h[0]&&537.36==h[2]&&28<=parseFloat(h[1])&&"WebKit"==G&&(G=["Blink"]);x&&(P||h[1])?(G&&(G[1]="like Chrome"),h=h[1]||(h=h[0],530>h?1:532>h?2:532.05>h?3:533>h?4:534.03>h?5:534.07>h?6:534.1>h?7:534.13>h?8:534.16>h?9:534.24>h?10:534.3>h?11:535.01>h?12:535.02>h?"13+":535.07>h?15:535.11>h?16:535.19>h?17:536.05>h?18:536.1>h?19:537.01>h?20:537.11>h?"21+":537.13>h?
23:537.18>h?24:537.24>h?25:537.36>h?26:"Blink"!=G?"27":"28")):(G&&(G[1]="like Safari"),h=(h=h[0],400>h?1:500>h?2:526>h?3:533>h?4:534>h?"4+":535>h?5:537>h?6:538>h?7:601>h?8:"8"));G&&(G[1]+=" "+(h+="number"==typeof h?".x":/[.+]/.test(h)?"":"+"));"Safari"==u&&(!w||45<parseInt(w))&&(w=h)}"Opera"==u&&(h=/\bzbov|zvav$/.exec(A))?(u+=" ",C.unshift("desktop mode"),"zvav"==h?(u+="Mini",w=null):u+="Mobile",A=A.replace(RegExp(" *"+h+"$"),"")):"Safari"==u&&/\bChrome\b/.exec(G&&G[1])&&(C.unshift("desktop mode"),
u="Chrome Mobile",w=null,/\bOS X\b/.test(A)?(W="Apple",A="iOS 4.3+"):A=null);w&&0==w.indexOf(h=/[\d.]+$/.exec(A))&&-1<m.indexOf("/"+h+"-")&&(A=String(A.replace(h,"")).replace(/^ +| +$/g,""));G&&!/\b(?:Avant|Nook)\b/.test(u)&&(/Browser|Lunascape|Maxthon/.test(u)||"Safari"!=u&&/^iOS/.test(A)&&/\bSafari\b/.test(G[1])||/^(?:Adobe|Arora|Breach|Midori|Opera|Phantom|Rekonq|Rock|Samsung Internet|Sleipnir|Web)/.test(u)&&G[1])&&(h=G[G.length-1])&&C.push(h);C.length&&(C=["("+C.join("; ")+")"]);W&&J&&0>J.indexOf(W)&&
C.push("on "+W);J&&C.push((/^on /.test(C[C.length-1])?"":"on ")+J);if(A){var da=(h=/ ([\d.+]+)$/.exec(A))&&"/"==A.charAt(A.length-h[0].length-1);A={architecture:32,family:h&&!da?A.replace(h[0],""):A,version:h?h[1]:null,toString:function(){var S=this.version;return this.family+(S&&!da?" "+S:"")+(64==this.architecture?" 64-bit":"")}}}(h=/\b(?:AMD|IA|Win|WOW|x86_|x)64\b/i.exec(Y))&&!/\bi686\b/i.test(Y)?(A&&(A.architecture=64,A.family=A.family.replace(RegExp(" *"+h),"")),u&&(/\bWOW64\b/i.test(m)||x&&
/\w(?:86|32)$/.test(R.cpuClass||R.platform)&&!/\bWin64; x64\b/i.test(m))&&C.unshift("32-bit")):A&&/^OS X/.test(A.family)&&"Chrome"==u&&39<=parseFloat(w)&&(A.architecture=64);m||(m=null);D={};D.description=m;D.layout=G&&G[0];D.manufacturer=W;D.name=u;D.prerelease=V;D.product=J;D.ua=m;D.version=u&&w;D.os=A||{architecture:null,family:null,version:null,toString:function(){return"null"}};D.parse=r;D.toString=function(){return this.description||""};D.version&&C.unshift(w);D.name&&C.unshift(u);A&&u&&(A!=
String(A).split(" ")[0]||A!=u.split(" ")[0]&&!J)&&C.push(J?"("+A+")":"on "+A);C.length&&(D.description=C.join(" "));return D}var n={"function":!0,object:!0},p=n[typeof window]&&window||this,t=n[typeof exports]&&exports;n=n[typeof module]&&module&&!module.nodeType&&module;var q=t&&n&&"object"==typeof global&&global;!q||q.global!==q&&q.window!==q&&q.self!==q||(p=q);var y=Math.pow(2,53)-1,k=/\bOpera/;q=Object.prototype;var F=q.hasOwnProperty,v=q.toString,B=r();"function"==typeof define&&"object"==typeof define.amd&&
define.amd?(p.platform=B,define(function(){return B})):t&&n?d(B,function(m,N){t[N]=m}):p.platform=B}).call(this);
function buildIOSMeta(){for(var a=[{name:"viewport",content:"width=device-width, height=device-height, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no"},{name:"apple-mobile-web-app-capable",content:"yes"},{name:"apple-mobile-web-app-status-bar-style",content:"black"}],c=0;c<a.length;c++){var b=document.createElement("meta");b.name=a[c].name;b.content=a[c].content;var d=window.document.head.querySelector('meta[name="'+b.name+'"]');d&&d.parentNode.removeChild(d);window.document.head.appendChild(b)}}
function hideIOSFullscreenPanel(){document.querySelector(".xxx-ios-fullscreen-message").style.display="none";document.querySelector(".xxx-ios-fullscreen-scroll").style.display="none";document.querySelector(".xxx-game-iframe-full").classList.remove("xxx-game-iframe-iphone-se")}function buildIOSFullscreenPanel(){document.body.insertAdjacentHTML("beforeend",'<div class="xxx-ios-fullscreen-message"><div class="xxx-ios-fullscreen-swipe"></div></div><div class="xxx-ios-fullscreen-scroll"></div>')}
function showIOSFullscreenPanel(){document.querySelector(".xxx-ios-fullscreen-message").style.display="none";document.querySelector(".xxx-ios-fullscreen-scroll").style.display="none"}
function __iosResize(){window.scrollTo(0,0);console.log(window.devicePixelRatio);console.log(window.innerWidth);console.log(window.innerHeight);if("iPhone"===platform.product)switch(window.devicePixelRatio){case 2:switch(window.innerWidth){case 568:320!==window.innerHeight&&document.querySelector(".xxx-game-iframe-full").classList.add("xxx-game-iframe-iphone-se");break;case 667:375===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;case 808:414===window.innerHeight?hideIOSFullscreenPanel():
showIOSFullscreenPanel();break;default:hideIOSFullscreenPanel()}break;case 3:switch(window.innerWidth){case 736:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;case 724:375===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;case 808:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;default:hideIOSFullscreenPanel()}break;default:hideIOSFullscreenPanel()}}
function iosResize(){__iosResize();setTimeout(function(){__iosResize()},500)}function iosInIframe(){try{return window.self!==window.top}catch(a){return!0}}function isIOSLessThen13(){var a=platform.os,c=a.family.toLowerCase();a=parseFloat(a.version);return"ios"===c&&13>a?!0:!1}document.addEventListener("DOMContentLoaded",function(){platform&&"iPhone"===platform.product&&"safari"===platform.name.toLowerCase()&&isIOSLessThen13()&&!iosInIframe()&&(buildIOSFullscreenPanel(),buildIOSMeta())});
window.addEventListener("resize",function(a){platform&&"iPhone"===platform.product&&"safari"===platform.name.toLowerCase()&&isIOSLessThen13()&&!iosInIframe()&&iosResize()});var s_iOffsetX,s_iOffsetY,s_iScaleFactor=1,s_bIsIphone=!1,s_bFocus=!0;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}
function getSize(a){var c=a.toLowerCase(),b=window.document,d=b.documentElement;if(void 0===window["inner"+a])a=d["client"+a];else if(window["inner"+a]!=d["client"+a]){var e=b.createElement("body");e.id="vpw-test-b";e.style.cssText="overflow:scroll";var f=b.createElement("div");f.id="vpw-test-d";f.style.cssText="position:absolute;top:-1000px";f.innerHTML="<style>@media("+c+":"+d["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+c+":7px!important}}</style>";e.appendChild(f);d.insertBefore(e,b.head);
a=7==f["offset"+a]?d["client"+a]:window["inner"+a];d.removeChild(e)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}
function isIpad(){var a=-1!==navigator.userAgent.toLowerCase().indexOf("ipad");return!a&&navigator.userAgent.match(/Mac/)&&navigator.maxTouchPoints&&2<navigator.maxTouchPoints?!0:a}function isMobile(){return isIpad()?!0:navigator.userAgent.match(/Android/i)||navigator.userAgent.match(/webOS/i)||navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPad/i)||navigator.userAgent.match(/iPod/i)||navigator.userAgent.match(/BlackBerry/i)||navigator.userAgent.match(/Windows Phone/i)?!0:!1}
function isIOS(){if(isIpad())return!0;for(var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");a.length;)if(navigator.platform===a.pop())return s_bIsIphone=!0;return s_bIsIphone=!1}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a=null!==platform.name&&"safari"===platform.name.toLowerCase()?getIOSWindowHeight():getSize("Height");var c=getSize("Width");s_bFocus&&_checkOrientation(c,a);var b=Math.min(a/CANVAS_HEIGHT,c/CANVAS_WIDTH),d=Math.round(CANVAS_WIDTH*b);b=Math.round(CANVAS_HEIGHT*b);if(b<a){var e=a-b;b+=e;d+=CANVAS_WIDTH/CANVAS_HEIGHT*e}else d<c&&(e=c-d,d+=e,b+=CANVAS_HEIGHT/CANVAS_WIDTH*e);e=a/2-b/2;var f=c/2-d/2,g=CANVAS_WIDTH/d;if(f*g<-EDGEBOARD_X||
e*g<-EDGEBOARD_Y)b=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),c/(CANVAS_WIDTH-2*EDGEBOARD_X)),d=Math.round(CANVAS_WIDTH*b),b=Math.round(CANVAS_HEIGHT*b),e=(a-b)/2,f=(c-d)/2,g=CANVAS_WIDTH/d;s_iOffsetX=-1*f*g;s_iOffsetY=-1*e*g;0<=e&&(s_iOffsetY=0);0<=f&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_bIsIphone&&s_oStage?(canvas=document.getElementById("canvas"),s_oStage.canvas.width=2*d,s_oStage.canvas.height=
2*b,canvas.style.width=d+"px",canvas.style.height=b+"px",c=Math.min(d/CANVAS_WIDTH,b/CANVAS_HEIGHT),s_iScaleFactor=2*c,s_oStage.scaleX=s_oStage.scaleY=2*c):s_bMobile&&!1===isIOS()?($("#canvas").css("width",d+"px"),$("#canvas").css("height",b+"px")):s_oStage&&(s_oStage.canvas.width=d,s_oStage.canvas.height=b,s_iScaleFactor=Math.min(d/CANVAS_WIDTH,b/CANVAS_HEIGHT),s_oStage.scaleX=s_oStage.scaleY=s_iScaleFactor);0>e||(e=(a-b)/2);$("#canvas").css("top",e+"px");$("#canvas").css("left",f+"px");fullscreenHandler()}}
function _checkOrientation(a,c){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(a>c?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),
s_oMain.stopUpdate()))}function createBitmap(a,c,b){var d=new createjs.Bitmap(a),e=new createjs.Shape;c&&b?e.graphics.beginFill("#fff").drawRect(0,0,c,b):e.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);d.hitArea=e;return d}function createSprite(a,c,b,d,e,f){a=null!==c?new createjs.Sprite(a,c):new createjs.Sprite(a);c=new createjs.Shape;c.graphics.beginFill("#000000").drawRect(-b,-d,e,f);a.hitArea=c;return a}
(function(){function a(b){var d={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};b=b||window.event;b.type in d?document.body.className=d[b.type]:(document.body.className=this[c]?"hidden":"visible","hidden"===document.body.className?(s_oMain.stopUpdate(),s_bFocus=!1):(s_oMain.startUpdate(),s_bFocus=!0))}var c="hidden";c in document?document.addEventListener("visibilitychange",a):(c="mozHidden")in document?document.addEventListener("mozvisibilitychange",
a):(c="webkitHidden")in document?document.addEventListener("webkitvisibilitychange",a):(c="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();function randomFloatBetween(a,c,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(a+Math.random()*(c-a),c).toFixed(b))}
function shuffle(a){for(var c=a.length,b,d;0!==c;)d=Math.floor(Math.random()*c),--c,b=a[c],a[c]=a[d],a[d]=b;return a}function formatTime(a){a/=1E3;var c=Math.floor(a/60);a=parseFloat(a-60*c).toFixed(1);var b="";b=10>c?b+("0"+c+":"):b+(c+":");return 10>a?b+("0"+a):b+a}
Array.prototype.sortOn=function(){var a=this.slice();if(!arguments.length)return a.sort();var c=Array.prototype.slice.call(arguments);return a.sort(function(b,d){for(var e=c.slice(),f=e.shift();b[f]==d[f]&&e.length;)f=e.shift();return b[f]==d[f]?0:b[f]>d[f]?1:-1})};function roundDecimal(a,c){var b=Math.pow(10,c);return Math.round(b*a)/b}function tweenVectors(a,c,b,d){d.set(a.getX()+b*(c.getX()-a.getX()),a.getY()+b*(c.getY()-a.getY()));return d}
function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3===a.nodeType&&(a=a.parentNode);var c=document.createEvent("MouseEvents");c.initEvent("click",!0,!0);a.dispatchEvent(c)}}};function playSound(a,c,b){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(s_aSounds[a].play(),s_aSounds[a].volume(c),s_aSounds[a].loop(b),s_aSounds[a]):null}function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].stop()}
function setVolume(a,c){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].volume(c)}function setMute(a,c){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].mute(c)}function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}function getParamValue(a){for(var c=window.location.search.substring(1).split("&"),b=0;b<c.length;b++){var d=c[b].split("=");if(d[0]==a)return d[1]}}
function fullscreenHandler(){ENABLE_FULLSCREEN&&screenfull.isEnabled&&(s_bFullscreen=screenfull.isFullscreen,null!==s_oInterface&&s_oInterface.resetFullscreenBut(),null!==s_oMenu&&s_oMenu.resetFullscreenBut())}if(screenfull.isEnabled)screenfull.on("change",function(){s_bFullscreen=screenfull.isFullscreen;null!==s_oInterface&&s_oInterface.resetFullscreenBut();null!==s_oMenu&&s_oMenu.resetFullscreenBut()});
function CSpriteLibrary(){var a={},c,b,d,e,f,g;this.init=function(l,r,n){c={};d=b=0;e=l;f=r;g=n};this.addSprite=function(l,r){if(a.hasOwnProperty(l))return!1;var n=new Image;a[l]=c[l]={szPath:r,oSprite:n,bLoaded:!1};b++;return!0};this.getSprite=function(l){return a.hasOwnProperty(l)?a[l].oSprite:null};this._onSpritesLoaded=function(){b=0;f.call(g)};this._onSpriteLoaded=function(){e.call(g);++d===b&&this._onSpritesLoaded()};this.loadSprites=function(){for(var l in c)c[l].oSprite.oSpriteLibrary=this,
c[l].oSprite.szKey=l,c[l].oSprite.onload=function(){this.oSpriteLibrary.setLoaded(this.szKey);this.oSpriteLibrary._onSpriteLoaded(this.szKey)},c[l].oSprite.onerror=function(r){var n=r.currentTarget;setTimeout(function(){c[n.szKey].oSprite.src=c[n.szKey].szPath},500)},c[l].oSprite.src=c[l].szPath};this.setLoaded=function(l){a[l].bLoaded=!0};this.isLoaded=function(l){return a[l].bLoaded};this.getNumSprites=function(){return b}}
var CANVAS_WIDTH=1700,CANVAS_HEIGHT=768,EDGEBOARD_X=250,EDGEBOARD_Y=0,FPS_TIME=1E3/24,DISABLE_SOUND_MOBILE=!1,FONT_GAME_1="arialbold",FONT_GAME_2="Digital-7",STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,STATE_GAME_WAITING_FOR_BET=0,STATE_GAME_DEALING=1,STATE_GAME_PLAYER_TURN=2,STATE_GAME_SHOWDOWN=3,STATE_GAME_DISTRIBUTE_FICHES=4,STATE_GAME_SHOW_WINNER=5,STATE_CARD_DEALING=0,STATE_CARD_REMOVING=1,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,ASSIGN_FICHES=
"ASSIGN_FICHES",END_HAND="END_HAND",ON_CARD_SHOWN="ON_CARD_SHOWN",ON_CARD_ANIMATION_ENDING="ON_CARD_ANIMATION_ENDING",ON_CARD_TO_REMOVE="ON_CARD_TO_REMOVE",NUM_FICHES=6,CARD_WIDTH=66,CARD_HEIGHT=102,MIN_BET,MAX_BET,TOTAL_MONEY,FICHE_WIDTH,WIN_OCCURRENCE,BET_OCCURRENCE,TIME_FICHES_MOV=600,TIME_CARD_DEALING=250,TIME_CARD_REMOVE=1E3,TIME_SHOW_FINAL_CARDS=4E3,TIME_END_HAND,BET_TIME=1E4,AD_SHOW_COUNTER,NUM_DECKS=4,PAYOUT_MULT,ROYAL_FLUSH=0,STRAIGHT_FLUSH=1,FOUR_OF_A_KIND=2,FULL_HOUSE=3,FLUSH=4,STRAIGHT=
5,THREE_OF_A_KIND=6,TWO_PAIR=7,ONE_PAIR=8,HIGH_CARD=9,NO_HAND=10,CARD_TWO=2,CARD_THREE=3,CARD_FOUR=4,CARD_FIVE=5,CARD_SIX=6,CARD_SEVEN=7,CARD_EIGHT=8,CARD_NINE=9,CARD_TEN=10,CARD_JACK=11,CARD_QUEEN=12,CARD_KING=13,CARD_ACE=14,BET_ANTE=0,BET_RAISE=1,POS_BET=[],MULTIPLIERS=[],COLOR_FICHE_PER_VALUE="#fff #000 #000 #fff #fff #fff".split(" "),FICHES_VALUE,ENABLE_FULLSCREEN,ENABLE_CHECK_ORIENTATION,SHOW_CREDITS;
function CPreloader(){var a,c,b,d,e,f,g,l,r;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.addSprite("200x200","./sprites/200x200.jpg");s_oSpriteLibrary.loadSprites();r=new createjs.Container;s_oStage.addChild(r)};this.unload=function(){r.removeAllChildren()};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};
this.attachSprites=function(){var n=new createjs.Shape;n.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);r.addChild(n);n=s_oSpriteLibrary.getSprite("200x200");g=createBitmap(n);g.regX=.5*n.width;g.regY=.5*n.height;g.x=CANVAS_WIDTH/2;g.y=CANVAS_HEIGHT/2-180;r.addChild(g);l=new createjs.Shape;l.graphics.beginFill("rgba(0,0,0,0.01)").drawRoundRect(g.x-100,g.y-100,200,200,10);r.addChild(l);g.mask=l;n=s_oSpriteLibrary.getSprite("progress_bar");d=createBitmap(n);d.x=CANVAS_WIDTH/2-
n.width/2;d.y=CANVAS_HEIGHT/2+50;r.addChild(d);a=n.width;c=n.height;e=new createjs.Shape;e.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(d.x,d.y,1,c);r.addChild(e);d.mask=e;b=new createjs.Text("","30px "+FONT_GAME_1,"#fff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT/2+100;b.textBaseline="alphabetic";b.textAlign="center";r.addChild(b);f=new createjs.Shape;f.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);r.addChild(f);createjs.Tween.get(f).to({alpha:0},500).call(function(){createjs.Tween.removeTweens(f);
r.removeChild(f)})};this.refreshLoader=function(n){b.text=n+"%";100===n&&(s_oMain._onRemovePreloader(),b.visible=!1,d.visible=!1);e.graphics.clear();n=Math.floor(n*a/100);e.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(d.x,d.y,n,c)};this._init()}
function CMain(a){var c,b=0,d=0,e=STATE_LOADING,f,g;this.initContainer=function(){var r=document.getElementById("canvas");s_oStage=new createjs.Stage(r);s_bMobile=isMobile();!1===s_bMobile?s_oStage.enableMouseOver(20):createjs.Touch.enable(s_oStage,!0);s_iPrevTime=(new Date).getTime();createjs.Ticker.setFPS(30);createjs.Ticker.addEventListener("tick",this._update);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;seekAndDestroy()?f=new CPreloader:
window.location.href="https://www.codethislab.com/contact-us.html";s_oGameSettings=new CGameSettings;c=!0};this.preloaderReady=function(){this._loadImages();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds()};this.soundLoaded=function(){b++;f.refreshLoader(Math.floor(b/d*100))};this._initSounds=function(){Howler.mute(!s_bAudioActive);s_aSoundsInfo=[];s_aSoundsInfo.push({path:"./sounds/",filename:"card",loop:!1,volume:1,ingamename:"card"});s_aSoundsInfo.push({path:"./sounds/",filename:"chip",
loop:!1,volume:1,ingamename:"chip"});s_aSoundsInfo.push({path:"./sounds/",filename:"fiche_collect",loop:!1,volume:1,ingamename:"fiche_collect"});s_aSoundsInfo.push({path:"./sounds/",filename:"press_but",loop:!1,volume:1,ingamename:"press_but"});s_aSoundsInfo.push({path:"./sounds/",filename:"win",loop:!1,volume:1,ingamename:"win"});s_aSoundsInfo.push({path:"./sounds/",filename:"lose",loop:!1,volume:1,ingamename:"lose"});d+=s_aSoundsInfo.length;s_aSounds=[];for(var r=0;r<s_aSoundsInfo.length;r++)this.tryToLoadSound(s_aSoundsInfo[r],
!1)};this.tryToLoadSound=function(r,n){setTimeout(function(){s_aSounds[r.ingamename]=new Howl({src:[r.path+r.filename+".mp3"],autoplay:!1,preload:!0,loop:r.loop,volume:r.volume,onload:s_oMain.soundLoaded,onloaderror:function(p,t){for(var q=0;q<s_aSoundsInfo.length;q++)if(0<s_aSounds[s_aSoundsInfo[q].ingamename]._sounds.length&&p===s_aSounds[s_aSoundsInfo[q].ingamename]._sounds[0]._id){s_oMain.tryToLoadSound(s_aSoundsInfo[q],!0);break}else document.querySelector("#block_game").style.display="none"},
onplayerror:function(p){for(var t=0;t<s_aSoundsInfo.length;t++)if(p===s_aSounds[s_aSoundsInfo[t].ingamename]._sounds[0]._id){s_aSounds[s_aSoundsInfo[t].ingamename].once("unlock",function(){s_aSounds[s_aSoundsInfo[t].ingamename].play()});break}}})},n?200:0)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_menu_bg","./sprites/but_menu_bg.png");s_oSpriteLibrary.addSprite("but_game_bg","./sprites/but_game_bg.png");s_oSpriteLibrary.addSprite("but_exit",
"./sprites/but_exit.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("card_spritesheet","./sprites/card_spritesheet.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("display_bg","./sprites/display_bg.png");s_oSpriteLibrary.addSprite("fiche_highlight","./sprites/fiche_highlight.png");
s_oSpriteLibrary.addSprite("win_bg","./sprites/win_bg.png");s_oSpriteLibrary.addSprite("but_clear","./sprites/but_clear.png");s_oSpriteLibrary.addSprite("but_generic","./sprites/but_generic.png");s_oSpriteLibrary.addSprite("but_rebet","./sprites/but_rebet.png");s_oSpriteLibrary.addSprite("gui_bg","./sprites/gui_bg.png");s_oSpriteLibrary.addSprite("bet_ante","./sprites/bet_ante.png");s_oSpriteLibrary.addSprite("bet_raise","./sprites/bet_raise.png");s_oSpriteLibrary.addSprite("paytable_bg","./sprites/paytable_bg.png");
s_oSpriteLibrary.addSprite("help_cursor","./sprites/help_cursor.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");s_oSpriteLibrary.addSprite("but_credits","./sprites/but_credits.png");s_oSpriteLibrary.addSprite("logo_ctl","./sprites/logo_ctl.png");for(var r=0;r<NUM_FICHES;r++)s_oSpriteLibrary.addSprite("fiche_"+r,"./sprites/fiche_"+r+".png");d+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;f.refreshLoader(Math.floor(b/
d*100))};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this._onRemovePreloader=function(){f.unload();this.gotoMenu()};this.gotoMenu=function(){new CMenu;e=STATE_MENU};this.gotoGame=function(){g=new CGame(l);e=STATE_GAME};this.gotoHelp=function(){new CHelp;e=STATE_HELP};this.stopUpdate=function(){c=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||Howler.mute(!0)};this.startUpdate=function(){s_iPrevTime=
(new Date).getTime();c=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none");(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)&&s_bAudioActive&&Howler.mute(!1)};this._update=function(r){if(c){var n=(new Date).getTime();s_iTimeElaps=n-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=n;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);e===STATE_GAME&&g.update();s_oStage.update(r)}};s_oMain=this;var l=a;ENABLE_CHECK_ORIENTATION=l.check_orientation;ENABLE_FULLSCREEN=
l.fullscreen;SHOW_CREDITS=a.show_credits;FICHES_VALUE=a.fiche_values;s_bAudioActive=a.audio_enable_on_startup;this.initContainer()}var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_bFullscreen=!1,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oGameSettings,s_aSoundsInfo;
function CTextButton(a,c,b,d,e,f,g,l){var r,n,p,t,q,y,k,F,v,B,m,N;this._init=function(H,D,C,R,w,P,Q){r=!1;n=1;q=[];y=[];N=createBitmap(C);p=C.width;t=C.height;B=new createjs.Container;B.x=H;B.y=D;B.regX=C.width/2;B.regY=C.height/2;s_bMobile||(B.cursor="pointer");B.addChild(N,m);l.addChild(B);m=new CTLText(B,10,5,C.width-20,C.height-10,Q,"center",P,w,1,0,0,R,!0,!0,!1,!1);this._initListener()};this.unload=function(){B.off("mousedown",k);B.off("pressup",F);l.removeChild(B)};this.setVisible=function(H){B.visible=
H};this.setAlign=function(H){m.textAlign=H};this.setTextX=function(H){m.x=H};this.setScale=function(H){n=B.scaleX=B.scaleY=H};this.enable=function(){r=!1;B.filters=[];B.cache(0,0,p,t)};this.disable=function(){r=!0;var H=(new createjs.ColorMatrix).adjustSaturation(-100);B.filters=[new createjs.ColorMatrixFilter(H)];B.cache(0,0,p,t)};this._initListener=function(){k=B.on("mousedown",this.buttonDown);F=B.on("pressup",this.buttonRelease)};this.addEventListener=function(H,D,C){q[H]=D;y[H]=C};this.addEventListenerWithParams=
function(H,D,C,R){q[H]=D;y[H]=C;v=R};this.buttonRelease=function(){r||(playSound("press_but",1,!1),B.scaleX=n,B.scaleY=n,q[ON_MOUSE_UP]&&q[ON_MOUSE_UP].call(y[ON_MOUSE_UP],v))};this.buttonDown=function(){r||(B.scaleX=.9*n,B.scaleY=.9*n,q[ON_MOUSE_DOWN]&&q[ON_MOUSE_DOWN].call(y[ON_MOUSE_DOWN]))};this.setPosition=function(H,D){B.x=H;B.y=D};this.tweenPosition=function(H,D,C,R,w,P,Q){createjs.Tween.get(B).wait(R).to({x:H,y:D},C,w).call(function(){void 0!==P&&P.call(Q)})};this.changeText=function(H){m.refreshText(H)};
this.setX=function(H){B.x=H};this.setY=function(H){B.y=H};this.getButtonImage=function(){return B};this.getX=function(){return B.x};this.getY=function(){return B.y};this.getSprite=function(){return B};this.getScale=function(){return B.scaleX};this._init(a,c,b,d,e,f,g)}
function CGfxButton(a,c,b,d){var e,f,g,l,r,n=[],p,t,q;this._init=function(k,F,v){e=!1;l=[];r=[];f=v.width;g=v.height;q=createBitmap(v);q.x=k;q.y=F;q.regX=v.width/2;q.regY=v.height/2;q.cursor="pointer";y.addChild(q);this._initListener()};this.unload=function(){q.off("mousedown",p);q.off("pressup",t);y.removeChild(q)};this.setVisible=function(k){q.visible=k};this._initListener=function(){p=q.on("mousedown",this.buttonDown);t=q.on("pressup",this.buttonRelease)};this.addEventListener=function(k,F,v){l[k]=
F;r[k]=v};this.addEventListenerWithParams=function(k,F,v,B){l[k]=F;r[k]=v;n=B};this.buttonRelease=function(){e||(playSound("press_but",1,!1),q.scaleX=q.scaleY=1,l[ON_MOUSE_UP]&&l[ON_MOUSE_UP].call(r[ON_MOUSE_UP],n))};this.buttonDown=function(){e||(q.scaleX=q.scaleY=.9,l[ON_MOUSE_DOWN]&&l[ON_MOUSE_DOWN].call(r[ON_MOUSE_DOWN],n))};this.setPosition=function(k,F){q.x=k;q.y=F};this.setX=function(k){q.x=k};this.setY=function(k){q.y=k};this.enable=function(){e=!1;q.filters=[];q.cache(0,0,f,g)};this.disable=
function(){e=!0;var k=(new createjs.ColorMatrix).adjustSaturation(-100);q.filters=[new createjs.ColorMatrixFilter(k)];q.cache(0,0,f,g)};this.getButtonImage=function(){return q};this.getX=function(){return q.x};this.getY=function(){return q.y};var y=d;this._init(a,c,b);return this}
function CToggle(a,c,b,d,e){var f,g,l,r=[],n,p,t;this._init=function(q,y,k,F){g=[];l=[];var v=new createjs.SpriteSheet({images:[k],frames:{width:k.width/2,height:k.height,regX:k.width/2/2,regY:k.height/2},animations:{state_true:[0],state_false:[1]}});f=F;t=createSprite(v,"state_"+f,k.width/2/2,k.height/2,k.width/2,k.height);t.x=q;t.y=y;t.cursor="pointer";t.stop();e.addChild(t);this._initListener()};this.unload=function(){t.off("mousedown",n);t.off("pressup",p);e.removeChild(t)};this._initListener=
function(){n=t.on("mousedown",this.buttonDown);p=t.on("pressup",this.buttonRelease)};this.addEventListener=function(q,y,k){g[q]=y;l[q]=k};this.addEventListenerWithParams=function(q,y,k,F){g[q]=y;l[q]=k;r=F};this.setActive=function(q){f=q;t.gotoAndStop("state_"+f)};this.buttonRelease=function(){t.scaleX=1;t.scaleY=1;playSound("press_but",1,!1);f=!f;t.gotoAndStop("state_"+f);g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(l[ON_MOUSE_UP],r)};this.buttonDown=function(){t.scaleX=.9;t.scaleY=.9;g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN],
r)};this.setPosition=function(q,y){t.x=q;t.y=y};this.setVisible=function(q){t.visible=q};this.getY=function(){return t.y};this._init(a,c,b,d)}
function CMenu(){var a,c,b,d,e,f,g,l,r,n,p,t=null,q=null,y;this._init=function(){g=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(g);var k=s_oSpriteLibrary.getSprite("but_menu_bg");l=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-164,k,s_oStage);l.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)k=s_oSpriteLibrary.getSprite("audio_icon"),e=CANVAS_WIDTH-k.width/4-10,f=k.height/2+10,r=new CToggle(e,f,k,s_bAudioActive,s_oStage),
r.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);k=s_oSpriteLibrary.getSprite("but_credits");SHOW_CREDITS?(a=10+k.width/2,c=k.height/2+10,n=new CGfxButton(a,c,k,s_oStage),n.addEventListener(ON_MOUSE_UP,this._onCredits,this),b=a+k.width+10,d=c):(b=10+k.width/2,d=k.height/2+10);k=window.document;var F=k.documentElement;t=F.requestFullscreen||F.mozRequestFullScreen||F.webkitRequestFullScreen||F.msRequestFullscreen;q=k.exitFullscreen||k.mozCancelFullScreen||k.webkitExitFullscreen||k.msExitFullscreen;
!1===ENABLE_FULLSCREEN&&(t=!1);t&&screenfull.isEnabled&&(k=s_oSpriteLibrary.getSprite("but_fullscreen"),p=new CToggle(b,d,k,s_bFullscreen,s_oStage),p.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));y=new createjs.Shape;y.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(y);createjs.Tween.get(y).to({alpha:0},400).call(function(){y.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(k,F){!1!==DISABLE_SOUND_MOBILE&&
!1!==s_bMobile||r.setPosition(e-k,F+f);t&&screenfull.isEnabled&&p.setPosition(b+k,d+F);SHOW_CREDITS&&n.setPosition(a+k,c+F)};this.unload=function(){l.unload();l=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)r.unload(),r=null;SHOW_CREDITS&&n.unload();t&&screenfull.isEnabled&&p.unload();s_oStage.removeAllChildren();s_oMenu=null};this._onButPlayRelease=function(){this.unload();s_oMain.gotoGame();$(s_oMain).trigger("start_session")};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);
s_bAudioActive=!s_bAudioActive};this._onCredits=function(){_oCreditsPanel=new CCreditsPanel};this.resetFullscreenBut=function(){t&&screenfull.isEnabled&&p.setActive(s_bFullscreen)};this._onFullscreenRelease=function(){s_bFullscreen?q.call(window.document):t.call(window.document.documentElement);sizeHandler()};s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(a){var c=!1,b,d,e,f,g,l,r,n,p,t,q,y,k,F,v,B,m,N,H,D,C,R,w,P,Q,K,z,L,T,Z,aa,I,E,h,Y;this._init=function(){e=MAX_BET;f=-1;g=y=d=0;s_oTweenController=new CTweenController;aa=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(aa);I=new CInterface(TOTAL_MONEY);L=new createjs.Container;s_oStage.addChild(L);T=new CHandEvaluator;E=new CSeat;E.setCredit(TOTAL_MONEY);Z=new CHelpCursor(520,416,s_oSpriteLibrary.getSprite("help_cursor"),s_oStage);this.reset(!1);w=new CVector2;
w.set(1214,228);P=new CVector2;P.set(CANVAS_WIDTH/2-199,230);Q=new CVector2;Q.set(418,820);K=new CVector2;K.set(0,-CANVAS_HEIGHT);z=new CVector2(454,230);H=[E.getCardOffset(),P];Y=new CGameOver;E.getCredit()<FICHES_VALUE[0]?(this._gameOver(),this.changeState(-1)):c=!0;R=new CVector2(w.getX(),w.getY());h=new CMsgBox;this.changeState(STATE_GAME_WAITING_FOR_BET)};this.unload=function(){c=!1;for(var x=0;x<v.length;x++)v[x].unload();I.unload();Y.unload();h.unload();s_oStage.removeAllChildren()};this.reset=
function(x){l=g=d=0;E.reset();v=[];v.splice(0);B=[];N=[];I.reset();I.enableBetFiches(x);this.shuffleCard()};this.shuffleCard=function(){m=[];m=s_oGameSettings.getShuffledCardDeck()};this.changeState=function(x){f=x;switch(x){case STATE_GAME_WAITING_FOR_BET:I.displayMsg(TEXT_DISPLAY_MSG_WAITING_BET,TEXT_MIN_BET+": "+MIN_BET+"\n"+TEXT_MAX_BET+": "+MAX_BET);break;case STATE_GAME_DEALING:I.disableButtons(),I.displayMsg(TEXT_DISPLAY_MSG_DEALING,""),this._dealing()}};this.cardFromDealerArrived=function(x,
G,u){(!1===G||G&&9===u)&&x.showCard();10>u&&s_oGame._dealing()};this.setMoney=function(x){E.setCredit(x);I.refreshCredit(x)};this._showWin=function(){b?this._playerLose():t===NO_HAND&&"dealer"!==k?this._playerWin(TEXT_DISPLAY_MSG_NOT_QUALIFY):"player"===k?this._playerWin(TEXT_HAND_WON_PLAYER):"dealer"===k&&t!==NO_HAND?this._playerLose():this._standOff();"player"===k?playSound("win",1,!1):playSound("lose",1,!1);this.changeState(STATE_GAME_DISTRIBUTE_FICHES);I.refreshCredit(E.getCredit());setTimeout(function(){E.clearBet();
s_oGame.changeState(STATE_GAME_WAITING_FOR_BET);I.enableBetFiches(!0)},3*TIME_CARD_REMOVE)};this._playerWin=function(x){E.increaseCredit(n);V-=n;I.displayMsg(TEXT_DISPLAY_MSG_SHOWDOWN,TEXT_DISPLAY_MSG_PLAYER_WIN+" "+n+TEXT_CURRENCY);E.initMovement(0,Q.getX(),Q.getY());E.initMovement(1,Q.getX(),Q.getY());I.showResultText(x)};this._playerLose=function(x){I.displayMsg(TEXT_DISPLAY_MSG_SHOWDOWN,TEXT_DISPLAY_MSG_PLAYER_LOSE);E.initMovement(0,K.getX(),K.getY());x||E.initMovement(1,K.getX(),K.getY());I.showResultText(TEXT_HAND_WON_DEALER)};
this._standOff=function(){E.increaseCredit(n);V-=n;I.displayMsg(TEXT_DISPLAY_MSG_SHOWDOWN,TEXT_DISPLAY_MSG_STANDOFF);E.initMovement(0,Q.getX(),Q.getY());E.initMovement(1,Q.getX(),Q.getY());I.showResultText(TEXT_DISPLAY_MSG_STANDOFF)};this._dealing=function(){if(10>l){var x=new CCard(w.getX(),w.getY(),L);if(1===l%H.length){var G=new CVector2(P.getX()+(CARD_WIDTH/2+7)*l,P.getY());var u=C.splice(0,1),J=u[0].fotogram;u=u[0].rank;x.setInfo(R,G,J,u,!0,l);x.addEventListener(ON_CARD_SHOWN,this._onCardShown);
B.push(x)}else u=D.splice(0,1),J=u[0].fotogram,u=u[0].rank,x.setInfo(R,E.getAttachCardOffset(),J,u,!1,l),E.newCardDealed(),N.push(x);v.push(x);l++;x.addEventListener(ON_CARD_ANIMATION_ENDING,this.cardFromDealerArrived);playSound("card",1,!1)}else setTimeout(function(){s_oGame.changeState(STATE_GAME_PLAYER_TURN);I.displayMsg(TEXT_DISPLAY_MSG_USER_TURN,"");I.enable(!1,!0,!0)},1E3)};this._onEndHand=function(){for(var x=new CVector2(z.getX(),z.getY()),G=0;G<v.length;G++)v[G].initRemoving(x),v[G].hideCard();
I.clearCardValueText();d=0;s_oGame.changeState(STATE_GAME_SHOW_WINNER);playSound("fiche_collect",1,!1);y++;y===AD_SHOW_COUNTER&&(y=0,$(s_oMain).trigger("show_interlevel_ad"));$(s_oMain).trigger("save_score",[E.getCredit()])};this._onCardShown=function(){f===STATE_GAME_PLAYER_TURN&&(4===p?(I.showHandValue(t,q),f=STATE_GAME_SHOWDOWN,s_oGame._showWin()):s_oGame._showNextDealerCard())};this.setBet=function(x,G){if(I.isResultPanelvisible())I.disableBetFiches(),E.clearBet(),F=this.setBet,this._onEndHand();
else{var u=FICHES_VALUE[G];if(x===BET_ANTE){d=0;Z.hide();var J=E.getBetAnte()+u;if(2*J>E.getCredit()-u){I.displayMsg(TEXT_NO_MONEY_FOR_RAISE,"");return}if(J>e){h.show(TEXT_ERROR_MAX_BET);return}}else J=2*E.getBetAnte();$(s_oMain).trigger("bet_placed",J);x===BET_ANTE?(E.decreaseCredit(u),V+=u,E.betAnte(u),I.enable(!0,!1,!1)):(E.decreaseCredit(J),V+=J,E.betRaise());I.refreshCredit(E.getCredit())}};this._gameOver=function(){Y.show()};this._calculateTotalWin=function(){if(t===NO_HAND&&"dealer"!==k)n=
2*E.getBetAnte()+2*E.getBetAnte();else if("player"===k){var x=2*E.getBetAnte();n=x+x*PAYOUT_MULT[q]+x}else n="dealer"===k&&t!==NO_HAND?0:E.getBetAnte()+2*E.getBetAnte()};this.onRebet=function(){I.isResultPanelvisible()&&(F=this.rebet,this._onEndHand())};this.onDeal=function(){r=E.getBetAnte()*PAYOUT_MULT[PAYOUT_MULT.length-1];if(E.getBetAnte()<MIN_BET)h.show(TEXT_ERROR_MIN_BET),I.enableBetFiches(!1),I.enable(!1,!1,!1);else{L.removeAllChildren();if((V+2*E.getBetAnte()<r?WIN_OCCURRENCE+1:Math.floor(101*
Math.random()))>WIN_OCCURRENCE){do{D=this._generateRandPlayerCards();C=this._generateRandDealerCards();var x=T.evaluate(C,!0),G=T.evaluate(D,!1);t=x.ret;q=G.ret;k=T.getWinnerComparingHands(G.sort_hand,x.sort_hand,q,t);this._calculateTotalWin()}while(t===NO_HAND||"player"===k||"dealer_no_hand"===k)}else{do D=this._generateRandPlayerCards(),C=this._generateRandDealerCards(),x=T.evaluate(C,!0),G=T.evaluate(D,!1),t=x.ret,q=G.ret,k=T.getWinnerComparingHands(G.sort_hand,x.sort_hand,q,t),this._calculateTotalWin();
while("dealer"===k||n>V+2*E.getBetAnte())}E.setPrevBet();playSound("card",1,!1);b=!1;this.changeState(STATE_GAME_DEALING)}};this.onFold=function(){b=!0;k="dealer";p=0;this._showNextDealerCard()};this.onRaise=function(){f!==STATE_GAME_DISTRIBUTE_FICHES&&(this.setBet(BET_RAISE,I.getFicheSelected()),p=0,this._showNextDealerCard())};this._showNextDealerCard=function(){B[p].showCard();p++};this._generateRandDealerCards=function(){for(var x=[],G=0;5>G;G++)x.push({fotogram:m[g].fotogram,rank:m[g].rank,suit:m[g].suit}),
g++,this._checkDeckLength();return x};this._generateRandPlayerCards=function(){for(var x=[],G=0;5>G;G++)x.push({fotogram:m[g].fotogram,rank:m[g].rank,suit:m[g].suit}),g++,this._checkDeckLength();return x};this._checkDeckLength=function(){g>=m.length&&(m=s_oGameSettings.getShuffledCardDeck(),g=0)};this.clearBets=function(){if(f===STATE_GAME_WAITING_FOR_BET){I.enable(!1,!1,!1);var x=E.getStartingBet();0<x&&(E.clearBet(),E.increaseCredit(x),V-=x,I.refreshCredit(E.getCredit()),x=E.checkIfRebetIsPossible(),
I.enableBetFiches(x))}};this.rebet=function(){this.clearBets();var x=E.rebet();V+=x;I.enable(!0,!1,!1);I.refreshCredit(E.getCredit());d=BET_TIME};this.onExit=function(){this.unload();$(s_oMain).trigger("save_score",[E.getCredit()]);$(s_oMain).trigger("end_session");$(s_oMain).trigger("share_event",E.getCredit());s_oMain.gotoMenu()};this.getState=function(){return f};this._updateDealing=function(){for(var x=0;x<v.length;x++)v[x].update()};this._updateFiches=function(){E.updateFichesController()};this._updateShowWinner=
function(){for(var x=0;x<v.length;x++)v[x].update();d+=s_iTimeElaps;d>TIME_END_HAND&&(d=0,x=E.checkIfRebetIsPossible(),this.reset(x),I.reset(),E.getCredit()<FICHES_VALUE[0]?(this._gameOver(),this.changeState(-1)):E.getCredit()<FICHES_VALUE[0]?(this._gameOver(),this.changeState(-1)):(this.changeState(STATE_GAME_WAITING_FOR_BET),F.call(this,0,I.getFicheSelected())))};this.update=function(){if(!1!==c)switch(f){case STATE_GAME_WAITING_FOR_BET:d+=s_iTimeElaps;6E3<d&&(d=0,Z.isVisible()||0!==E.getBetAnte()||
Z.show(1));break;case STATE_GAME_DEALING:this._updateDealing();break;case STATE_GAME_DISTRIBUTE_FICHES:this._updateFiches();break;case STATE_GAME_SHOW_WINNER:this._updateShowWinner()}};s_oGame=this;TOTAL_MONEY=a.money;MIN_BET=a.min_bet;MAX_BET=a.max_bet;MULTIPLIERS=a.multiplier;BET_TIME=a.bet_time;BLACKJACK_PAYOUT=a.blackjack_payout;WIN_OCCURRENCE=a.win_occurrence;BET_OCCURRENCE=a.bet_occurrence;var V=a.game_cash;PAYOUT_MULT=a.payout;TIME_END_HAND=a.time_show_hand;AD_SHOW_COUNTER=a.ad_show_counter;
this._init()}var s_oGame,s_oTweenController;
function CInterface(a){var c,b,d,e,f,g,l,r,n,p,t,q,y,k,F,v=null,B,m,N,H,D,C,R,w,P=null,Q=null;this._init=function(K){var z=s_oSpriteLibrary.getSprite("but_exit");d=CANVAS_WIDTH-z.width/2-10;e=z.height/2+10;n=new CGfxButton(d,e,z,s_oStage);n.addEventListener(ON_MOUSE_UP,this._onExit,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)f=n.getX()-z.width-10,g=z.height/2+10,v=new CToggle(f,g,s_oSpriteLibrary.getSprite("audio_icon"),s_bAudioActive,s_oStage),v.addEventListener(ON_MOUSE_UP,this._onAudioToggle,
this);z=window.document;var L=z.documentElement;P=L.requestFullscreen||L.mozRequestFullScreen||L.webkitRequestFullScreen||L.msRequestFullscreen;Q=z.exitFullscreen||z.mozCancelFullScreen||z.webkitExitFullscreen||z.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(P=!1);P&&screenfull.isEnabled&&(z=s_oSpriteLibrary.getSprite("but_fullscreen"),c=null===v?n.getX()-z.width/2-10:f-z.width/2-10,b=z.height/2+10,w=new CToggle(c,b,z,s_bFullscreen,s_oStage),w.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));
z=createBitmap(s_oSpriteLibrary.getSprite("display_bg"));z.x=290;z.y=6;s_oStage.addChild(z);z=s_oSpriteLibrary.getSprite("gui_bg");L=createBitmap(z);L.y=CANVAS_HEIGHT-z.height;s_oStage.addChild(L);z=s_oSpriteLibrary.getSprite("but_clear");p=new CGfxButton(830,CANVAS_HEIGHT-z.height/2,z,s_oStage);p.disable();p.addEventListener(ON_MOUSE_UP,this._onButClearRelease,this);z=s_oSpriteLibrary.getSprite("but_rebet");t=new CGfxButton(890,CANVAS_HEIGHT-z.height/2,z,s_oStage);t.disable();t.addEventListener(ON_MOUSE_UP,
this._onButRebetRelease,this);z=s_oSpriteLibrary.getSprite("but_generic");y=new CTextButton(1012,CANVAS_HEIGHT-z.height/2,z,TEXT_DEAL,FONT_GAME_1,"#ffffff",30,s_oStage);y.addEventListener(ON_MOUSE_UP,this._onButDealRelease,this);z=s_oSpriteLibrary.getSprite("but_generic");k=new CTextButton(1196,CANVAS_HEIGHT-z.height/2,z,TEXT_RAISE,FONT_GAME_1,"#ffffff",30,s_oStage);k.addEventListener(ON_MOUSE_UP,this._onButRaiseRelease,this);z=s_oSpriteLibrary.getSprite("but_generic");F=new CTextButton(1380,CANVAS_HEIGHT-
z.height/2,z,TEXT_FOLD,FONT_GAME_1,"#ffffff",30,s_oStage);F.addEventListener(ON_MOUSE_UP,this._onButFoldRelease,this);POS_BET[BET_ANTE]={x:CANVAS_WIDTH/2-100,y:440};POS_BET[BET_RAISE]={x:CANVAS_WIDTH/2+100,y:440};q=new CGfxButton(POS_BET[BET_ANTE].x,POS_BET[BET_ANTE].y,s_oSpriteLibrary.getSprite("bet_ante"),s_oStage);q.addEventListener(ON_MOUSE_UP,this._onButAnteRelease,this);L=s_oSpriteLibrary.getSprite("bet_raise");var T=createBitmap(L);T.x=POS_BET[BET_RAISE].x;T.y=POS_BET[BET_RAISE].y;T.regX=L.width/
2;T.regY=L.height/2;s_oStage.addChild(T);H=new CTLText(s_oStage,408,16,192,48,24,"left","#ffde00",FONT_GAME_2,1,0,0," ",!0,!0,!0,!1);D=new CTLText(s_oStage,408,66,192,38,19,"left","#ffde00",FONT_GAME_2,1,0,0," ",!0,!0,!0,!1);m=new CTLText(s_oStage,CANVAS_WIDTH/2-180,290,360,21,21,"center","#fff",FONT_GAME_1,1,0,0," ",!0,!0,!1,!1);N=new CTLText(s_oStage,CANVAS_WIDTH/2-180,650,360,21,21,"center","#fff",FONT_GAME_1,1,0,0," ",!0,!0,!1,!1);new CTLText(s_oStage,300,CANVAS_HEIGHT-84,150,30,30,"right","#ffde00",
FONT_GAME_2,1,0,0,TEXT_MONEY+":",!0,!0,!1,!1);B=new CTLText(s_oStage,460,CANVAS_HEIGHT-84,150,30,30,"left","#ffde00",FONT_GAME_2,1,0,0,TEXT_CURRENCY+K.toFixed(2),!0,!0,!1,!1);K=[{x:337,y:CANVAS_HEIGHT-24},{x:417,y:CANVAS_HEIGHT-24},{x:497,y:CANVAS_HEIGHT-24},{x:577,y:CANVAS_HEIGHT-24},{x:657,y:CANVAS_HEIGHT-24},{x:737,y:CANVAS_HEIGHT-24}];r=[];for(L=0;L<NUM_FICHES;L++)r[L]=new CFiche(K[L].x,K[L].y,L,FICHES_VALUE[L],1,!0,s_oStage),r[L].addEventListenerWithParams(ON_MOUSE_UP,this._onFicheClicked,this,
[FICHES_VALUE[L],L]),0===L&&r[0].select(!0);l=0;FICHE_WIDTH=z.width;C=new CAnimText(CANVAS_WIDTH,CANVAS_HEIGHT,s_oStage);R=new CPaytablePanel(CANVAS_WIDTH-303,450,s_oStage);this.disableButtons();this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){n.unload();n=null;!1===DISABLE_SOUND_MOBILE&&(v.unload(),v=null);P&&screenfull.isEnabled&&w.unload();p.unload();y.unload();t.unload();s_oInterface=null};this.refreshButtonPos=function(K,z){n.setPosition(d-K,z+e);!1!==DISABLE_SOUND_MOBILE&&
!1!==s_bMobile||v.setPosition(f-K,z+g);P&&screenfull.isEnabled&&w.setPosition(c-K,b+z);R.refreshButtonPos(K,z)};this.reset=function(){this.disableButtons()};this.enableBetFiches=function(K){for(var z=0;z<NUM_FICHES;z++)r[z].enable();p.enable();q.enable();K&&t.enable()};this.disableBetFiches=function(){for(var K=0;K<NUM_FICHES;K++)r[K].disable();p.disable();t.disable();q.disable()};this.disableButtons=function(){y.disable();F.disable();k.disable()};this.enable=function(K,z,L){K?y.enable():y.disable();
z?k.enable():k.disable();L?F.enable():F.disable()};this.refreshCredit=function(K){B.refreshText(TEXT_CURRENCY+K.toFixed(2))};this.refreshCardValue=function(K,z){m.refreshText(""+K);N.refreshText(""+z)};this.displayMsg=function(K,z){H.refreshText(K);D.refreshText(z)};this.clearCardValueText=function(){m.refreshText("");N.refreshText("");C.hide()};this._onFicheClicked=function(K){for(var z=0;z<r.length;z++)r[z].select(!1);r[K[1]].select(!0);l=K[1]};this.showResultText=function(K){C.show({x:-200,y:CANVAS_HEIGHT/
2+160},{x:CANVAS_WIDTH/2-450,y:CANVAS_HEIGHT/2+160},K)};this.showHandValue=function(K,z){m.refreshText(TEXT_EVALUATOR[K]);N.refreshText(TEXT_EVALUATOR[z])};this._onButClearRelease=function(){s_oGame.clearBets()};this._onButRebetRelease=function(){t.disable();s_oGame.onRebet()};this._onButAnteRelease=function(){s_oGame.setBet(BET_ANTE,l)};this._onButDealRelease=function(){this.disableBetFiches();this.disableButtons();s_oGame.onDeal()};this._onButRaiseRelease=function(){this.disableBetFiches();this.disableButtons();
s_oGame.onRaise()};this._onButFoldRelease=function(){this.disableBetFiches();this.disableButtons();s_oGame.onFold()};this._onExit=function(){s_oGame.onExit()};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this.resetFullscreenBut=function(){P&&screenfull.isEnabled&&w.setActive(s_bFullscreen)};this._onFullscreenRelease=function(){s_bFullscreen?Q.call(window.document):P.call(window.document.documentElement);sizeHandler()};this.getFicheSelected=function(){return l};
this.isResultPanelvisible=function(){return C.isVisible()};s_oInterface=this;this._init(a);return this}var s_oInterface=null;
function CTweenController(){this.tweenValue=function(a,c,b){return a+b*(c-a)};this.easeLinear=function(a,c,b,d){return b*a/d+c};this.easeInCubic=function(a,c,b,d){d=(a/=d)*a*a;return c+b*d};this.easeBackInQuart=function(a,c,b,d){d=(a/=d)*a;return c+b*(2*d*d+2*d*a+-3*d)};this.easeInBack=function(a,c,b,d){return b*(a/=d)*a*(2.70158*a-1.70158)+c};this.easeOutCubic=function(a,c,b,d){return b*((a=a/d-1)*a*a+1)+c}}
function CSeat(){var a,c,b,d,e,f,g,l,r,n;this._init=function(){l=new createjs.Container;l.x=CANVAS_WIDTH/2-160;l.y=586;s_oStage.addChild(l);n=[];for(var p=0;2>p;p++)n[p]=new CFichesController;c=a=e=0;this.reset();r=new CVector2;r.set(0,0);g=new CVector2(r.getX(),r.getY())};this.unload=function(){s_oStage.removeChild(l)};this.addEventListener=function(p,t,q){};this.reset=function(){for(var p=d=0;p<n.length;p++)n[p].reset();f=[];for(p=0;3>p;p++)f[p]=[]};this.clearBet=function(){c=a=0;f=[];for(var p=
0;p<n.length;p++)n[p].reset(),f[p]=[]};this.resetBet=function(){c=a=0};this.setCredit=function(p){e=p};this.increaseCredit=function(p){e+=p};this.betAnte=function(p){a+=p;n[0].createFichesPile(a,POS_BET[0].x,POS_BET[0].y)};this.betRaise=function(){c=2*a;n[1].createFichesPile(c,POS_BET[1].x,POS_BET[1].y)};this.setPrevBet=function(){b=a};this.decreaseCredit=function(p){e-=p;e=parseFloat(e.toFixed(2))};this.refreshFiches=function(p,t,q,y,k){f[k].push({value:p,index:t});n[k].refreshFiches(f[k],q,y)};
this.initMovement=function(p,t,q){n[p].initMovement(t,q)};this.newCardDealed=function(){d++};this.rebet=function(){c=0;a=b;this.decreaseCredit(b);n[BET_ANTE].createFichesPile(b,POS_BET[BET_ANTE].x,POS_BET[BET_ANTE].y);return b};this.checkIfRebetIsPossible=function(){for(var p=0,t=0;t<n.length;t++){var q=parseFloat(n[t].getPrevBet().toFixed(2));p+=q}return p>e?!1:!0};this.updateFichesController=function(){for(var p=0;p<n.length;p++)n[p].update()};this.getAttachCardOffset=function(){g.set(l.x+r.getX()+
(CARD_WIDTH+14)*d,l.y+r.getY());return g};this.getBetAnte=function(){return a};this.getBetRaise=function(){return c};this.getCredit=function(){return e};this.getCardOffset=function(){return r};this.getPotentialWin=function(p){return(void 0)[p]};this.getStartingBet=function(){for(var p=0,t=0;t<n.length;t++)p+=n[t].getValue();return p};this._init()}
function CFichesController(){var a,c,b,d,e,f,g,l,r,n;this._init=function(){l=new createjs.Container;s_oStage.addChild(l);e=new CVector2;e.set(l.x,l.y);r=new createjs.Container;s_oStage.addChild(r);n=new createjs.Text("","28px "+FONT_GAME_1,"#fff");n.textAlign="center";r.addChild(n);b=d=c=0;a=!1};this.addEventListener=function(p,t,q){};this.reset=function(){a=!1;b=0;l.removeAllChildren();l.x=e.getX();l.y=e.getY();n.text=""};this.setPrevValue=function(p){d=p};this.refreshFiches=function(p,t,q){p=p.sortOn("value",
"index");for(var y=t,k=q+10,F=b=0,v=0;v<p.length;v++)new CFiche(y,k,p[v].index,FICHES_VALUE[p[v].index],.85,!1,l),k-=5,F++,9<F&&(F=0,y+=FICHE_WIDTH,k=q),b+=p[v].value;playSound("chip",1,!1);n.x=t;n.y=q+35;n.text=b.toFixed(2)+TEXT_CURRENCY};this.createFichesPile=function(p,t,q){this.reset();var y=[];do{for(var k=FICHES_VALUE[FICHES_VALUE.length-1],F=FICHES_VALUE.length-1;k>p;)F--,k=FICHES_VALUE[F];F=Math.floor(p/k);for(var v=0;v<F;v++)y.push({value:k,index:s_oGameSettings.getIndexForFiches(k)});k=
Math.floor(p/k)===p/k?0:p%k;p=k.toFixed(2)}while(0<k);this.refreshFiches(y,t,q)};this.initMovement=function(p,t){d=b;f=new CVector2(l.x,l.y);g=new CVector2(p,t);n.text="";a=!0};this.getValue=function(){return b};this.getPrevBet=function(){return d};this.update=function(){if(a)if(c+=s_iTimeElaps,c>TIME_FICHES_MOV)c=0,a=!1;else{var p=easeInOutCubic(c,0,1,TIME_FICHES_MOV),t=new CVector2;t=tweenVectors(f,g,p,t);l.x=t.getX();l.y=t.getY()}};this._init()}
function CVector2(a,c){var b,d;this._init=function(e,f){b=e;d=f};this.add=function(e,f){b+=e;d+=f};this.addV=function(e){b+=e.getX();d+=e.getY()};this.scalarDivision=function(e){b/=e;d/=e};this.subV=function(e){b-=e.getX();d-=e.getY()};this.scalarProduct=function(e){b*=e;d*=e};this.invert=function(){b*=-1;d*=-1};this.dotProduct=function(e){return b*e.getX()+d*e.getY()};this.set=function(e,f){b=e;d=f};this.setV=function(e){b=e.getX();d=e.getY()};this.length=function(){return Math.sqrt(b*b+d*d)};this.length2=
function(){return b*b+d*d};this.normalize=function(){var e=this.length();0<e&&(b/=e,d/=e)};this.getNormalize=function(e){this.length();e.set(b,d);e.normalize()};this.rot90CCW=function(){var e=b;b=-d;d=e};this.rot90CW=function(){var e=b;b=d;d=-e};this.getRotCCW=function(e){e.set(b,d);e.rot90CCW()};this.getRotCW=function(e){e.set(b,d);e.rot90CW()};this.ceil=function(){b=Math.ceil(b);d=Math.ceil(d)};this.round=function(){b=Math.round(b);d=Math.round(d)};this.toString=function(){return"Vector2: "+b+", "+
d};this.print=function(){trace("Vector2: "+b+", "+d)};this.getX=function(){return b};this.getY=function(){return d};this._init(a,c)}
function CGameSettings(){var a,c;this._init=function(){var b=-1;a=[];for(var d=0;52>d;d++){var e=(d+1)%13;1===e?(e=14,b++):0===e&&(e=13);a.push({fotogram:d,rank:e,suit:b})}};this.getIndexForFiches=function(b){for(var d=0,e=0;e<FICHES_VALUE.length;e++)FICHES_VALUE[e]===b&&(d=e);return d};this.generateFichesPile=function(b){var d=[],e=FICHES_VALUE.length-1,f=FICHES_VALUE[e];do{var g=b%f;g=CMath.roundDecimal(g,1);b=Math.floor(b/f);for(var l=0;l<b;l++)d.push(f);e--;f=FICHES_VALUE[e];b=g}while(0<g&&-1<
e);return d};this.timeToString=function(b){b=Math.round(b/1E3);var d=Math.floor(b/60);b-=60*d;var e="";e=10>d?e+("0"+d+":"):e+(d+":");return 10>b?e+("0"+b):e+b};this.getShuffledCardDeck=function(){for(var b=[],d=0;d<a.length;d++)b[d]=a[d];for(c=[];0<b.length;)c.push(b.splice(Math.round(Math.random()*(b.length-1)),1)[0]);return c};this.getCardDeck=function(){return a};this._init()}var TYPE_LINEAR=0,TYPE_OUT_CUBIC=1,TYPE_IN_CUBIC=2,TYPE_OUT_BACK=3,TYPE_IN_BACK=4;
function ease(a,c,b,d,e,f){switch(a){case TYPE_LINEAR:var g=easeLinear(c,b,d,e,f);break;case TYPE_IN_CUBIC:g=easeInCubic(c,b,d,e,f);break;case TYPE_OUT_CUBIC:g=easeOutCubic(c,b,d,e,f);break;case TYPE_IN_BACK:g=easeInBack(c,b,d,e,f);break;case TYPE_OUT_BACK:g=easeInBack(c,b,d,e,f)}return g}function easeOutBounce(a,c,b,d){return(a/=d)<1/2.75?7.5625*b*a*a+c:a<2/2.75?b*(7.5625*(a-=1.5/2.75)*a+.75)+c:a<2.5/2.75?b*(7.5625*(a-=2.25/2.75)*a+.9375)+c:b*(7.5625*(a-=2.625/2.75)*a+.984375)+c}
function easeInBounce(a,c,b,d){return b-easeOutBounce(d-a,0,b,d)+c}function easeInOutBounce(a,c,b,d){return a<d/2?.5*easeInBounce(2*a,0,b,d)+c:.5*easeOutBounce(2*a-d,0,b,d)+.5*b+c}function easeInCirc(a,c,b,d){return-b*(Math.sqrt(1-(a/=d)*a)-1)+c}function easeOutCirc(a,c,b,d){return b*Math.sqrt(1-(a=a/d-1)*a)+c}function easeInOutCirc(a,c,b,d){return 1>(a/=d/2)?-b/2*(Math.sqrt(1-a*a)-1)+c:b/2*(Math.sqrt(1-(a-=2)*a)+1)+c}function easeInCubic(a,c,b,d,e){return b*(a/=d)*a*a+c}
function easeOutCubic(a,c,b,d,e){return b*((a=a/d-1)*a*a+1)+c}function easeInOutCubic(a,c,b,d,e){return 1>(a/=d/2)?b/2*a*a*a+c:b/2*((a-=2)*a*a+2)+c}function easeInElastic(a,c,b,d,e,f,g){if(0==a)return c;if(1==(a/=d))return c+b;g||(g=.3*d);!f||f<Math.abs(b)?(f=b,e=g/4):e=g/(2*Math.PI)*Math.asin(b/f);return-(f*Math.pow(2,10*--a)*Math.sin(2*(a*d-e)*Math.PI/g))+c}
function easeOutElastic(a,c,b,d,e,f,g){if(0==a)return c;if(1==(a/=d))return c+b;g||(g=.3*d);!f||f<Math.abs(b)?(f=b,e=g/4):e=g/(2*Math.PI)*Math.asin(b/f);return f*Math.pow(2,-10*a)*Math.sin(2*(a*d-e)*Math.PI/g)+b+c}function easeInOutElastic(a,c,b,d,e,f,g){if(0==a)return c;if(1==(a/=d))return c+b;g||(g=.3*d);!f||f<Math.abs(b)?(f=b,e=g/4):e=g/(2*Math.PI)*Math.asin(b/f);return 1>a?-.5*f*Math.pow(2,10*--a)*Math.sin(2*(a*d-e)*Math.PI/g)+c:f*Math.pow(2,-10*--a)*Math.sin(2*(a*d-e)*Math.PI/g)*.5+b+c}
function easeInExpo(a,c,b,d){return 0==a?c:b*Math.pow(2,10*(a/d-1))+c}function easeOutExpo(a,c,b,d){return a==d?c+b:b*(-Math.pow(2,-10*a/d)+1)+c}function easeInOutExpo(a,c,b,d){return 0==a?c:a==d?c+b:1>(a/=d/2)?b/2*Math.pow(2,10*(a-1))+c:b/2*(-Math.pow(2,-10*--a)+2)+c}function easeLinear(a,c,b,d){return b*a/d+c}function easeInQuad(a,c,b,d){return b*(a/=d)*a+c}function easeOutQuad(a,c,b,d){return-b*(a/=d)*(a-2)+c}function easeInOutQuad(a,c,b,d){return 1>(a/=d/2)?b/2*a*a+c:-b/2*(--a*(a-2)-1)+c}
function easeInQuart(a,c,b,d){return b*(a/=d)*a*a*a+c}function easeOutQuart(a,c,b,d){return-b*((a=a/d-1)*a*a*a-1)+c}function easeInOutQuart(a,c,b,d){return 1>(a/=d/2)?b/2*a*a*a*a+c:-b/2*((a-=2)*a*a*a-2)+c}function easeInQuint(a,c,b,d){return b*(a/=d)*a*a*a*a+c}function easeOutQuint(a,c,b,d){return b*((a=a/d-1)*a*a*a*a+1)+c}function easeInOutQuint(a,c,b,d){return 1>(a/=d/2)?b/2*a*a*a*a*a+c:b/2*((a-=2)*a*a*a*a+2)+c}function easeInSine(a,c,b,d){return-b*Math.cos(a/d*(Math.PI/2))+b+c}
function easeOutSine(a,c,b,d){return b*Math.sin(a/d*(Math.PI/2))+c}function easeInOutSine(a,c,b,d){return-b/2*(Math.cos(Math.PI*a/d)-1)+c}function easeInBack(a,c,b,d){return b*(a/=d)*a*(2.70158*a-1.70158)+c}function easeOutBack(a,c,b,d){return b*((a=a/d-1)*a*(2.70158*a+1.70158)+1)+c}
function CCard(a,c,b){var d,e,f=-1,g,l,r,n,p,t,q,y,k,F;this._init=function(v,B,m){F=m;m={images:[s_oSpriteLibrary.getSprite("card_spritesheet")],frames:{width:CARD_WIDTH,height:CARD_HEIGHT,regX:CARD_WIDTH/2,regY:CARD_HEIGHT/2},animations:{card_1_1:[0],card_1_2:[1],card_1_3:[2],card_1_4:[3],card_1_5:[4],card_1_6:[5],card_1_7:[6],card_1_8:[7],card_1_9:[8],card_1_10:[9],card_1_J:[10],card_1_Q:[11],card_1_K:[12],card_2_1:[13],card_2_2:[14],card_2_3:[15],card_2_4:[16],card_2_5:[17],card_2_6:[18],card_2_7:[19],
card_2_8:[20],card_2_9:[21],card_2_10:[22],card_2_J:[23],card_2_Q:[24],card_2_K:[25],card_3_1:[26],card_3_2:[27],card_3_3:[28],card_3_4:[29],card_3_5:[30],card_3_6:[31],card_3_7:[32],card_3_8:[33],card_3_9:[34],card_3_10:[35],card_3_J:[36],card_3_Q:[37],card_3_K:[38],card_4_1:[39],card_4_2:[40],card_4_3:[41],card_4_4:[42],card_4_5:[43],card_4_6:[44],card_4_7:[45],card_4_8:[46],card_4_9:[47],card_4_10:[48],card_4_J:[49],card_4_Q:[50],card_4_K:[51],back:[52]}};m=new createjs.SpriteSheet(m);k=createSprite(m,
"back",CARD_WIDTH/2,CARD_HEIGHT/2,CARD_WIDTH,CARD_HEIGHT);k.x=v;k.y=B;k.rotation=120;k.stop();F.addChild(k);q=[];y=[]};this.unload=function(){t=p=null;F.removeChild(k)};this.addEventListener=function(v,B,m){q[v]=B;y[v]=m};this.setInfo=function(v,B,m,N,H,D){e=!1;n=0;g=m;l=N;p=v;t=B;r=D;d=H;f=STATE_CARD_DEALING};this.initRemoving=function(v){p=new CVector2(k.x,k.y);t=v;n=0;f=STATE_CARD_REMOVING};this.setValue=function(){k.gotoAndStop(g);var v=this;createjs.Tween.get(k).to({scaleX:1},100).call(function(){v.cardShown()})};
this.showCard=function(){var v=this;createjs.Tween.get(k).to({scaleX:.1},100).call(function(){v.setValue()})};this.hideCard=function(){var v=this;createjs.Tween.get(k).to({scaleX:.1},100).call(function(){v.setBack()})};this.setBack=function(){k.gotoAndStop("back");var v=this;createjs.Tween.get(k).to({scaleX:1},100).call(function(){v.cardHidden()})};this.cardShown=function(){q[ON_CARD_SHOWN]&&q[ON_CARD_SHOWN].call(y[ON_CARD_SHOWN])};this.cardHidden=function(){e=!0};this.getValue=function(){return l};
this.getFotogram=function(){return g};this._updateDealing=function(){n+=s_iTimeElaps;if(n>TIME_CARD_DEALING)f=-1,n=0,k.x=t.getX(),k.y=t.getY(),k.rotation=360,q[ON_CARD_ANIMATION_ENDING]&&q[ON_CARD_ANIMATION_ENDING].call(y[ON_CARD_ANIMATION_ENDING],this,d,r);else{this.visible=!0;var v=easeInOutCubic(n,0,1,TIME_CARD_DEALING),B=new CVector2;B=tweenVectors(p,t,v,B);k.x=B.getX();k.y=B.getY();k.rotation=120+24E3*v/100}};this._updateRemoving=function(){n+=s_iTimeElaps;if(n>TIME_CARD_REMOVE)n=0,e=!1,f=-1,
this.unload();else{var v=easeInOutCubic(n,0,1,TIME_CARD_REMOVE),B=new CVector2;B=tweenVectors(p,t,v,B);k.x=B.getX();k.y=B.getY();k.rotation=4500*v/100}};this.update=function(){switch(f){case STATE_CARD_DEALING:this._updateDealing();break;case STATE_CARD_REMOVING:!0===e&&this._updateRemoving()}};s_oCard=this;this._init(a,c,b)}var s_oCard;
function CGameOver(){var a,c,b;this._init=function(){b=new createjs.Container;s_oStage.addChild(b);b.on("click",function(){});var d=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));b.addChild(d);new CTLText(b,CANVAS_WIDTH/2-180,275,360,140,32,"center","#fff",FONT_GAME_1,1,0,0,TEXT_NO_MONEY,!0,!0,!0,!1);a=new CTextButton(CANVAS_WIDTH/2-100,450,s_oSpriteLibrary.getSprite("but_game_bg"),TEXT_RECHARGE,FONT_GAME_1,"#fff",14,b);a.addEventListener(ON_MOUSE_UP,this._onRecharge,this);c=new CTextButton(CANVAS_WIDTH/
2+100,450,s_oSpriteLibrary.getSprite("but_game_bg"),TEXT_EXIT,FONT_GAME_1,"#fff",14,b);c.addEventListener(ON_MOUSE_UP,this._onExit,this);this.hide()};this.unload=function(){a.unload();c.unload();b.off("click",function(){})};this.show=function(){b.visible=!0;$(s_oMain).trigger("end_session")};this.hide=function(){b.visible=!1};this._onRecharge=function(){b.visible=!1;$(s_oMain).trigger("recharge")};this._onExit=function(){s_oGame.onExit()};this._init()}
function CMsgBox(){var a,c,b;this._init=function(){b=new createjs.Container;b.alpha=0;b.visible=!1;s_oStage.addChild(b);a=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));b.addChild(a);c=new CTLText(b,CANVAS_WIDTH/2-180,CANVAS_HEIGHT/2-90,360,166,34,"center","#fff",FONT_GAME_1,1,0,0," ",!0,!0,!0,!1);c.setShadow("#000",2,2,2)};this.unload=function(){b.off("mousedown",this._onExit)};this._initListener=function(){b.on("mousedown",this._onExit)};this.show=function(d){c.refreshText(d);b.visible=!0;
var e=this;createjs.Tween.get(b).to({alpha:1},500).call(function(){e._initListener()})};this._onExit=function(){b.visible&&(b.off("mousedown"),b.visible=!1)};this._init();return this}
function CHandEvaluator(){var a,c,b;this.evaluate=function(d,e){c=[];a=[];for(var f=0;f<d.length;f++)c[f]={rank:d[f].rank,suit:d[f].suit},a[f]={rank:d[f].rank,suit:d[f].suit};c.sort(this.compareRank);a.sort(this.compareRank);b=[0,1,2,3,4];return{ret:this.rankHand(e),sort_hand:a}};this.rankHand=function(d){return this._checkForRoyalFlush()?ROYAL_FLUSH:this._checkForStraightFlush()?STRAIGHT_FLUSH:this._checkForFourOfAKind()?FOUR_OF_A_KIND:this._checkForFullHouse()?FULL_HOUSE:this._checkForFlush()?FLUSH:
this._checkForStraight()?STRAIGHT:this._checkForThreeOfAKind()?THREE_OF_A_KIND:this._checkForTwoPair()?TWO_PAIR:this._checkForOnePair()?ONE_PAIR:this._checkHighCard(d)?HIGH_CARD:NO_HAND};this._checkForRoyalFlush=function(){return this._isRoyalStraight()&&this._isFlush()?!0:!1};this._checkForStraightFlush=function(){return this._isStraight()&&this._isFlush()?!0:!1};this._checkForFourOfAKind=function(){return c[0].rank===c[3].rank?(c.splice(4,1),b.splice(4,1),!0):c[1].rank===c[4].rank?(c.splice(0,1),
b.splice(0,1),!0):!1};this._checkForFullHouse=function(){return c[0].rank===c[1].rank&&c[2].rank===c[4].rank||c[0].rank===c[2].rank&&c[3].rank===c[4].rank?!0:!1};this._checkForFlush=function(){return this._isFlush()?!0:!1};this._checkForStraight=function(){return this._isStraight()?!0:!1};this._checkForThreeOfAKind=function(){return c[0].rank===c[1].rank&&c[0].rank===c[2].rank?(c.splice(3,1),c.splice(3,1),b.splice(3,1),b.splice(3,1),!0):c[1].rank===c[2].rank&&c[1].rank===c[3].rank?(c.splice(0,1),
c.splice(3,1),b.splice(0,1),b.splice(3,1),!0):c[2].rank===c[3].rank&&c[2].rank===c[4].rank?(c.splice(0,1),c.splice(0,1),b.splice(0,1),b.splice(0,1),!0):!1};this._checkForTwoPair=function(){return c[0].rank===c[1].rank&&c[2].rank===c[3].rank?(c.splice(4,1),b.splice(4,1),!0):c[1].rank===c[2].rank&&c[3].rank===c[4].rank?(c.splice(0,1),b.splice(0,1),!0):c[0].rank===c[1].rank&&c[3].rank===c[4].rank?(c.splice(2,1),b.splice(2,1),!0):!1};this._checkForOnePair=function(){for(var d=0;4>d;d++)if(c[d].rank===
c[d+1].rank){var e=c[d],f=c[d+1];c=[];c.push(e);c.push(f);b=[d,d+1];return!0}return!1};this._checkHighCard=function(d){for(var e=!1,f=!1,g=0;5>g;g++)c[g].rank===CARD_ACE&&(e=!0),c[g].rank===CARD_KING&&(f=!0);return d?e&&f?!0:!1:e||f?!0:!1};this._isFlush=function(){return c[0].suit===c[1].suit&&c[0].suit===c[2].suit&&c[0].suit===c[3].suit&&c[0].suit===c[4].suit?!0:!1};this._isRoyalStraight=function(){return c[0].rank===CARD_TEN&&c[1].rank===CARD_JACK&&c[2].rank===CARD_QUEEN&&c[3].rank===CARD_KING&&
c[4].rank===CARD_ACE?!0:!1};this._isStraight=function(){var d=c[0].rank+1===c[1].rank&&c[1].rank+1===c[2].rank&&c[2].rank+1===c[3].rank;return d&&c[0].rank===CARD_TWO&&c[4].rank===CARD_ACE?!0:d&&c[3].rank+1===c[4].rank?!0:!1};this.compareRank=function(d,e){return d.rank<e.rank?-1:d.rank>e.rank?1:0};this.getWinnerComparingHands=function(d,e,f,g){if(f===g)switch(f){case STRAIGHT_FLUSH:return d[0].suit>e[0].suit?"dealer":d[0].suit<e[0].suit?"player":"standoff";case FOUR_OF_A_KIND:return d[1].rank>e[1].rank?
"player":d[1].rank<e[1].rank?"dealer":"standoff";case FULL_HOUSE:return d[4].rank>e[4].rank?"player":d[4].rank<e[4].rank?"dealer":"standoff";case FLUSH:return d[0].suit>e[0].suit?"dealer":d[0].suit<e[0].suit?"player":"standoff";case STRAIGHT:return d[4].rank>e[4].rank?"player":d[4].rank<e[4].rank?"dealer":"standoff";case THREE_OF_A_KIND:return d[2].rank>e[2].rank?"player":d[2].rank<e[2].rank?"dealer":"standoff";case TWO_PAIR:f=0;for(g=d.length-1;0<g;g--)if(d[g].rank===d[g-1].rank){f=d[g].rank;break}d=
0;for(g=e.length-1;0<g;g--)if(e[g].rank===e[g-1].rank){d=e[g].rank;break}return f>d?"player":f<d?"dealer":"standoff";case ONE_PAIR:for(g=f=0;g<d.length-1;g++)if(d[g].rank===d[g+1].rank){f=d[g].rank;break}for(g=d=0;g<e.length-1;g++)if(e[g].rank===e[g+1].rank){d=e[g].rank;break}return f>d?"player":f<d?"dealer":"standoff";case NO_HAND:break;default:return"standoff"}else return g===NO_HAND?"dealer_no_hand":f>g?"dealer":"player"}}
function CAnimText(a,c,b){var d,e,f;this._init=function(l,r){f=new createjs.Container;f.visible=!1;f.x=l;f.y=r;g.addChild(f);var n=s_oSpriteLibrary.getSprite("win_bg"),p=createBitmap(n);f.addChild(p);e=new CTLText(f,5,5,n.width-10,n.height-10,28,"center","#fff",FONT_GAME_1,1,0,0," ",!0,!0,!0,!1)};this.show=function(l,r,n){d=l;e.refreshText(n);f.x=l.x;f.y=l.y;f.visible=!0;createjs.Tween.get(f).to({x:r.x,y:r.y},1E3,createjs.Ease.elasticOut)};this.hide=function(){f.visible=!1;f.x=d.x;f.y=d.y};this.isVisible=
function(){return f.visible};var g=b;this._init(a,c)}
function CPaytablePanel(a,c,b){var d,e,f;this._init=function(l,r){d=l;e=r;f=new createjs.Container;f.x=d;f.y=e;g.addChild(f);var n=s_oSpriteLibrary.getSprite("paytable_bg"),p=createBitmap(n);f.addChild(p);for(var t=p="",q=0;q<PAYOUT_MULT.length;q++)p+=TEXT_EVALUATOR[q],t+=PAYOUT_MULT[q]+":1",q<PAYOUT_MULT.length-1&&(p+="\n",t+="\n");new CTLText(f,10,10,200,180,20,"left","#ffde00",FONT_GAME_1,1,0,0,p,!0,!0,!0,!1);new CTLText(f,n.width-90,10,85,180,20,"right","#ffde00",FONT_GAME_1,1,0,0,t,!0,!0,!0,
!1)};this.refreshButtonPos=function(l,r){f.x=d-l};var g=b;this._init(a,c)}
function CHelpCursor(a,c,b,d){var e,f;this._init=function(l,r,n){e=l;f=createBitmap(n);f.visible=!1;f.x=l;f.y=r;d.addChild(f)};this.show=function(l){0>l&&(f.scaleX*=-1);this._move(l,e+30*l,600);f.visible=!0};this.hide=function(){createjs.Tween.removeTweens(f);f.x=e;f.visible=!1};this._move=function(l,r,n){var p=0<l?createjs.Ease.cubicIn:createjs.Ease.cubicOut;createjs.Tween.get(f).to({x:r},n,p).call(function(){l*=-1;g._move(l,r+15*l,400)})};this.isVisible=function(){return f.visible};var g=this;this._init(a,
c,b)}
function CCreditsPanel(){var a,c,b,d,e,f,g;this._init=function(){g=new createjs.Container;s_oStage.addChild(g);a=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));g.addChild(a);d=new createjs.Shape;d.graphics.beginFill("#0f0f0f").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);d.alpha=.01;f=d.on("click",this._onLogoButRelease);g.addChild(d);var l=s_oSpriteLibrary.getSprite("but_exit");b=new CGfxButton(615,270,l,g);b.addEventListener(ON_MOUSE_UP,this.unload,this);l=s_oSpriteLibrary.getSprite("logo_ctl");c=
createBitmap(l);c.regX=l.width/2;c.regY=l.height/2;c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT/2;g.addChild(c);e=new createjs.Text("www.codethislab.com","36px "+FONT_GAME_1,"#fff");e.textAlign="center";e.textBaseline="alphabetic";e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT/2+100;g.addChild(e)};this.unload=function(){d.off("click",f);b.unload();b=null;s_oStage.removeChild(g)};this._onLogoButRelease=function(){window.open("https://www.codethislab.com/","_blank")};this._init()}
CTLText.prototype={constructor:CTLText,__autofit:function(){if(this._bFitText){for(var a=this._iStartingFontSize;(this._oText.getBounds().height>this._iHeight-2*this._iPaddingV||this._oText.getBounds().width>this._iWidth-2*this._iPaddingH)&&!(a--,this._oText.font=a+"px "+this._szFont,this._oText.lineHeight=Math.round(a*this._fLineHeightFactor),this.__updateY(),this.__verticalAlign(),8>a););this._iFontSize=a}},__verticalAlign:function(){if(this._bVerticalAlign){var a=this._oText.getBounds().height;
this._oText.y-=(a-this._iHeight)/2+this._iPaddingV}},__updateY:function(){this._oText.y=this._y+this._iPaddingV;switch(this._oText.textBaseline){case "middle":this._oText.y+=this._oText.lineHeight/2+(this._iFontSize*this._fLineHeightFactor-this._iFontSize)}},__createText:function(a){this._bDebug&&(this._oDebugShape=new createjs.Shape,this._oDebugShape.graphics.beginFill("rgba(255,0,0,0.5)").drawRect(this._x,this._y,this._iWidth,this._iHeight),this._oContainer.addChild(this._oDebugShape));this._oText=
new createjs.Text(a,this._iFontSize+"px "+this._szFont,this._szColor);this._oText.textBaseline="middle";this._oText.lineHeight=Math.round(this._iFontSize*this._fLineHeightFactor);this._oText.textAlign=this._szAlign;this._oText.lineWidth=this._bMultiline?this._iWidth-2*this._iPaddingH:null;switch(this._szAlign){case "center":this._oText.x=this._x+this._iWidth/2;break;case "left":this._oText.x=this._x+this._iPaddingH;break;case "right":this._oText.x=this._x+this._iWidth-this._iPaddingH}this._oContainer.addChild(this._oText);
this.refreshText(a)},setX:function(a){this._x=this._oText.x=a},setY:function(a){this._y=this._oText.y=a},setVerticalAlign:function(a){this._bVerticalAlign=a},setOutline:function(a){null!==this._oText&&(this._oText.outline=a)},setShadow:function(a,c,b,d){null!==this._oText&&(this._oText.shadow=new createjs.Shadow(a,c,b,d))},setColor:function(a){this._oText.color=a},setAlpha:function(a){this._oText.alpha=a},removeTweens:function(){createjs.Tween.removeTweens(this._oText)},getText:function(){return this._oText},
getY:function(){return this._y},getFontSize:function(){return this._iFontSize},getBounds:function(){return this._oText.getBounds()},refreshText:function(a){""===a&&(a=" ");null===this._oText&&this.__createText(a);this._oText.text=a;this._oText.font=this._iStartingFontSize+"px "+this._szFont;this._oText.lineHeight=Math.round(this._iStartingFontSize*this._fLineHeightFactor);this.__autofit();this.__updateY();this.__verticalAlign()}};
function CTLText(a,c,b,d,e,f,g,l,r,n,p,t,q,y,k,F,v){this._oContainer=a;this._x=c;this._y=b;this._iWidth=d;this._iHeight=e;this._bMultiline=F;this._iFontSize=this._iStartingFontSize=f;this._szAlign=g;this._szColor=l;this._szFont=r;this._iPaddingH=p;this._iPaddingV=t;this._bVerticalAlign=k;this._bFitText=y;this._bDebug=v;this._oDebugShape=null;this._fLineHeightFactor=n;this._oText=null;q&&this.__createText(q)}
function CFiche(a,c,b,d,e,f,g){var l,r,n,p,t,q,y;this._init=function(k,F,v,B,m){y=new createjs.Container;y.x=k;y.y=F;y.scaleX=y.scaleY=e;g.addChild(y);k=s_oSpriteLibrary.getSprite("fiche_highlight");t=createBitmap(k);t.x=-9;t.y=-9;t.visible=!1;y.addChild(t);k=s_oSpriteLibrary.getSprite("fiche_"+v);q=createBitmap(k);y.addChild(q);new CTLText(y,8,8,k.width-21,20,20,"center",COLOR_FICHE_PER_VALUE[v],FONT_GAME_1,1,0,0,B,!0,!0,!1,!1);m&&(l=!1,r=[],n=[],y.on("mousedown",this.buttonDown),y.on("pressup",
this.buttonRelease));y.regX=k.width/2;y.regY=k.height/2};this.addEventListener=function(k,F,v){r[k]=F;n[k]=v};this.addEventListenerWithParams=function(k,F,v,B){r[k]=F;n[k]=v;p=B};this.select=function(k){t.visible=k};this.enable=function(){l=!1};this.disable=function(){l=!0};this.buttonRelease=function(){l||(y.scaleX=e,y.scaleY=e,r[ON_MOUSE_UP]&&r[ON_MOUSE_UP].call(n[ON_MOUSE_UP],p))};this.buttonDown=function(){l||(y.scaleX=.9*e,y.scaleY=.9*e,r[ON_MOUSE_DOWN]&&r[ON_MOUSE_DOWN].call(n[ON_MOUSE_DOWN],
p))};this.getX=function(){return y.x};this.getY=function(){return y.x};this._init(a,c,b,d,f)}function extractHostname(a){a=-1<a.indexOf("://")?a.split("/")[2]:a.split("/")[0];a=a.split(":")[0];return a=a.split("?")[0]}function extractRootDomain(a){a=extractHostname(a);var c=a.split("."),b=c.length;2<b&&(a=c[b-2]+"."+c[b-1]);return a}
var getClosestTop=function(){var a=window,c=!1;try{for(;a.parent.document!==a.document;)if(a.parent.document)a=a.parent;else{c=!0;break}}catch(b){c=!0}return{topFrame:a,err:c}},getBestPageUrl=function(a){var c=a.topFrame,b="";if(a.err)try{try{b=window.top.location.href}catch(e){var d=window.location.ancestorOrigins;b=d[d.length-1]}}catch(e){b=c.document.referrer}else b=c.location.href;return b},TOPFRAMEOBJ=getClosestTop(),PAGE_URL=getBestPageUrl(TOPFRAMEOBJ);
function seekAndDestroy(){for(var a=extractRootDomain(PAGE_URL),c=[String.fromCharCode(99,111,100,101,116,104,105,115,108,97,98,46,99,111,109),String.fromCharCode(101,110,118,97,116,111,46,99,111,109),String.fromCharCode(99,111,100,101,99,97,110,121,111,110,46,99,111,109),String.fromCharCode(99,111,100,101,99,97,110,121,111,110,46,110,101,116)],b=0;b<c.length;b++)if(c[b]===a)return!0;return!0};