/*
 Platform.js <https://mths.be/platform>
 Copyright 2014-2018 Benjamin Tan <https://bnjmnt4n.now.sh/>
 Copyright 2011-2013 John-David Dalton
 Available under MIT license <https://mths.be/mit>
*/
(function(){function a(a){a=String(a);return a.charAt(0).toUpperCase()+a.slice(1)}function b(a,b){var d=-1,f=a?a.length:0;if("number"==typeof f&&-1<f&&f<=y)for(;++d<f;)b(a[d],d,a);else c(a,b)}function d(b){b=String(b).replace(/^ +| +$/g,"");return/^(?:webOS|i(?:OS|P))/.test(b)?b:a(b)}function c(a,b){for(var d in a)k.call(a,d)&&b(a[d],d,a)}function f(b){return null==b?a(b):w.call(b).slice(8,-1)}function g(a,b){var d=null!=a?typeof a[b]:"number";return!/^(?:boolean|number|string|undefined)$/.test(d)&&
("object"==d?!!a[b]:!0)}function m(a){return String(a).replace(/([ -])(?!$)/g,"$1?")}function p(a,d){var c=null;b(a,function(b,f){c=d(c,b,f,a)});return c}function l(a){function b(b){return p(b,function(b,c){var f=c.pattern||m(c);!b&&(b=RegExp("\\b"+f+" *\\d+[.\\w_]*","i").exec(a)||RegExp("\\b"+f+" *\\w+-[\\w]*","i").exec(a)||RegExp("\\b"+f+"(?:; *(?:[a-z]+[_-])?[a-z]+\\d+|[^ ();-]*)","i").exec(a))&&((b=String(c.label&&!RegExp(f,"i").test(c.label)?c.label:b).split("/"))[1]&&!/[\d.]+/.test(b[0])&&(b[0]+=
" "+b[1]),c=c.label||c,b=d(b[0].replace(RegExp(f,"i"),c).replace(RegExp("; *(?:"+c+"[_-])?","i")," ").replace(RegExp("("+c+")[-_.]?(\\w)","i"),"$1 $2")));return b})}function q(b){return p(b,function(b,c){return b||(RegExp(c+"(?:-[\\d.]+/|(?: for [\\w-]+)?[ /-])([\\d.]+[^ ();/_-]*)","i").exec(a)||0)[1]||null})}var h=t,k=a&&"object"==typeof a&&"String"!=f(a);k&&(h=a,a=null);var x=h.navigator||{},n=x.userAgent||"";a||(a=n);var y=k?!!x.likeChrome:/\bChrome\b/.test(a)&&!/internal|\n/i.test(w.toString()),
S=k?"Object":"ScriptBridgingProxyObject",z=k?"Object":"Environment",B=k&&h.java?"JavaPackage":f(h.java),T=k?"Object":"RuntimeObject";z=(B=/\bJava/.test(B)&&h.java)&&f(h.environment)==z;var U=B?"a":"\u03b1",V=B?"b":"\u03b2",P=h.document||{},J=h.operamini||h.opera,M=u.test(M=k&&J?J["[[Class]]"]:f(J))?M:J=null,e,N=a;k=[];var O=null,K=a==n;n=K&&J&&"function"==typeof J.version&&J.version();var C=function(b){return p(b,function(b,c){return b||RegExp("\\b"+(c.pattern||m(c))+"\\b","i").exec(a)&&(c.label||
c)})}([{label:"EdgeHTML",pattern:"Edge"},"Trident",{label:"WebKit",pattern:"AppleWebKit"},"iCab","Presto","NetFront","Tasman","KHTML","Gecko"]),r=function(b){return p(b,function(b,c){return b||RegExp("\\b"+(c.pattern||m(c))+"\\b","i").exec(a)&&(c.label||c)})}(["Adobe AIR","Arora","Avant Browser","Breach","Camino","Electron","Epiphany","Fennec","Flock","Galeon","GreenBrowser","iCab","Iceweasel","K-Meleon","Konqueror","Lunascape","Maxthon",{label:"Microsoft Edge",pattern:"Edge"},"Midori","Nook Browser",
"PaleMoon","PhantomJS","Raven","Rekonq","RockMelt",{label:"Samsung Internet",pattern:"SamsungBrowser"},"SeaMonkey",{label:"Silk",pattern:"(?:Cloud9|Silk-Accelerated)"},"Sleipnir","SlimBrowser",{label:"SRWare Iron",pattern:"Iron"},"Sunrise","Swiftfox","Waterfox","WebPositive","Opera Mini",{label:"Opera Mini",pattern:"OPiOS"},"Opera",{label:"Opera",pattern:"OPR"},"Chrome",{label:"Chrome Mobile",pattern:"(?:CriOS|CrMo)"},{label:"Firefox",pattern:"(?:Firefox|Minefield)"},{label:"Firefox for iOS",pattern:"FxiOS"},
{label:"IE",pattern:"IEMobile"},{label:"IE",pattern:"MSIE"},"Safari"]),D=b([{label:"BlackBerry",pattern:"BB10"},"BlackBerry",{label:"Galaxy S",pattern:"GT-I9000"},{label:"Galaxy S2",pattern:"GT-I9100"},{label:"Galaxy S3",pattern:"GT-I9300"},{label:"Galaxy S4",pattern:"GT-I9500"},{label:"Galaxy S5",pattern:"SM-G900"},{label:"Galaxy S6",pattern:"SM-G920"},{label:"Galaxy S6 Edge",pattern:"SM-G925"},{label:"Galaxy S7",pattern:"SM-G930"},{label:"Galaxy S7 Edge",pattern:"SM-G935"},"Google TV","Lumia","iPad",
"iPod","iPhone","Kindle",{label:"Kindle Fire",pattern:"(?:Cloud9|Silk-Accelerated)"},"Nexus","Nook","PlayBook","PlayStation Vita","PlayStation","TouchPad","Transformer",{label:"Wii U",pattern:"WiiU"},"Wii","Xbox One",{label:"Xbox 360",pattern:"Xbox"},"Xoom"]),F=function(b){return p(b,function(b,c,d){return b||(c[D]||c[/^[a-z]+(?: +[a-z]+\b)*/i.exec(D)]||RegExp("\\b"+m(d)+"(?:\\b|\\w*\\d)","i").exec(a))&&d})}({Apple:{iPad:1,iPhone:1,iPod:1},Archos:{},Amazon:{Kindle:1,"Kindle Fire":1},Asus:{Transformer:1},
"Barnes & Noble":{Nook:1},BlackBerry:{PlayBook:1},Google:{"Google TV":1,Nexus:1},HP:{TouchPad:1},HTC:{},LG:{},Microsoft:{Xbox:1,"Xbox One":1},Motorola:{Xoom:1},Nintendo:{"Wii U":1,Wii:1},Nokia:{Lumia:1},Samsung:{"Galaxy S":1,"Galaxy S2":1,"Galaxy S3":1,"Galaxy S4":1},Sony:{PlayStation:1,"PlayStation Vita":1}}),v=function(b){return p(b,function(b,c){var f=c.pattern||m(c);if(!b&&(b=RegExp("\\b"+f+"(?:/[\\d.]+|[ \\w.]*)","i").exec(a))){var e=b,h=c.label||c,g={"10.0":"10","6.4":"10 Technical Preview",
"6.3":"8.1","6.2":"8","6.1":"Server 2008 R2 / 7","6.0":"Server 2008 / Vista","5.2":"Server 2003 / XP 64-bit","5.1":"XP","5.01":"2000 SP1","5.0":"2000","4.0":"NT","4.90":"ME"};f&&h&&/^Win/i.test(e)&&!/^Windows Phone /i.test(e)&&(g=g[/[\d.]+$/.exec(e)])&&(e="Windows "+g);e=String(e);f&&h&&(e=e.replace(RegExp(f,"i"),h));b=e=d(e.replace(/ ce$/i," CE").replace(/\bhpw/i,"web").replace(/\bMacintosh\b/,"Mac OS").replace(/_PowerPC\b/i," OS").replace(/\b(OS X) [^ \d]+/i,"$1").replace(/\bMac (OS X)\b/,"$1").replace(/\/(\d)/,
" $1").replace(/_/g,".").replace(/(?: BePC|[ .]*fc[ \d.]+)$/i,"").replace(/\bx86\.64\b/gi,"x86_64").replace(/\b(Windows Phone) OS\b/,"$1").replace(/\b(Chrome OS \w+) [\d.]+\b/,"$1").split(" on ")[0])}return b})}(["Windows Phone","Android","CentOS",{label:"Chrome OS",pattern:"CrOS"},"Debian","Fedora","FreeBSD","Gentoo","Haiku","Kubuntu","Linux Mint","OpenBSD","Red Hat","SuSE","Ubuntu","Xubuntu","Cygwin","Symbian OS","hpwOS","webOS ","webOS","Tablet OS","Tizen","Linux","Mac OS X","Macintosh","Mac",
"Windows 98;","Windows "]);C&&(C=[C]);F&&!D&&(D=b([F]));if(e=/\bGoogle TV\b/.exec(D))D=e[0];/\bSimulator\b/i.test(a)&&(D=(D?D+" ":"")+"Simulator");"Opera Mini"==r&&/\bOPiOS\b/.test(a)&&k.push("running in Turbo/Uncompressed mode");"IE"==r&&/\blike iPhone OS\b/.test(a)?(e=l(a.replace(/like iPhone OS/,"")),F=e.manufacturer,D=e.product):/^iP/.test(D)?(r||(r="Safari"),v="iOS"+((e=/ OS ([\d_]+)/i.exec(a))?" "+e[1].replace(/_/g,"."):"")):"Konqueror"!=r||/buntu/i.test(v)?F&&"Google"!=F&&(/Chrome/.test(r)&&
!/\bMobile Safari\b/i.test(a)||/\bVita\b/.test(D))||/\bAndroid\b/.test(v)&&/^Chrome/.test(r)&&/\bVersion\//i.test(a)?(r="Android Browser",v=/\bAndroid\b/.test(v)?v:"Android"):"Silk"==r?(/\bMobi/i.test(a)||(v="Android",k.unshift("desktop mode")),/Accelerated *= *true/i.test(a)&&k.unshift("accelerated")):"PaleMoon"==r&&(e=/\bFirefox\/([\d.]+)\b/.exec(a))?k.push("identifying as Firefox "+e[1]):"Firefox"==r&&(e=/\b(Mobile|Tablet|TV)\b/i.exec(a))?(v||(v="Firefox OS"),D||(D=e[1])):!r||(e=!/\bMinefield\b/i.test(a)&&
/\b(?:Firefox|Safari)\b/.exec(r))?(r&&!D&&/[\/,]|^[^(]+?\)/.test(a.slice(a.indexOf(e+"/")+8))&&(r=null),(e=D||F||v)&&(D||F||/\b(?:Android|Symbian OS|Tablet OS|webOS)\b/.test(v))&&(r=/[a-z]+(?: Hat)?/i.exec(/\bAndroid\b/.test(v)?v:e)+" Browser")):"Electron"==r&&(e=(/\bChrome\/([\d.]+)\b/.exec(a)||0)[1])&&k.push("Chromium "+e):v="Kubuntu";n||(n=q(["(?:Cloud9|CriOS|CrMo|Edge|FxiOS|IEMobile|Iron|Opera ?Mini|OPiOS|OPR|Raven|SamsungBrowser|Silk(?!/[\\d.]+$))","Version",m(r),"(?:Firefox|Minefield|NetFront)"]));
if(e="iCab"==C&&3<parseFloat(n)&&"WebKit"||/\bOpera\b/.test(r)&&(/\bOPR\b/.test(a)?"Blink":"Presto")||/\b(?:Midori|Nook|Safari)\b/i.test(a)&&!/^(?:Trident|EdgeHTML)$/.test(C)&&"WebKit"||!C&&/\bMSIE\b/i.test(a)&&("Mac OS"==v?"Tasman":"Trident")||"WebKit"==C&&/\bPlayStation\b(?! Vita\b)/i.test(r)&&"NetFront")C=[e];"IE"==r&&(e=(/; *(?:XBLWP|ZuneWP)(\d+)/i.exec(a)||0)[1])?(r+=" Mobile",v="Windows Phone "+(/\+$/.test(e)?e:e+".x"),k.unshift("desktop mode")):/\bWPDesktop\b/i.test(a)?(r="IE Mobile",v="Windows Phone 8.x",
k.unshift("desktop mode"),n||(n=(/\brv:([\d.]+)/.exec(a)||0)[1])):"IE"!=r&&"Trident"==C&&(e=/\brv:([\d.]+)/.exec(a))&&(r&&k.push("identifying as "+r+(n?" "+n:"")),r="IE",n=e[1]);if(K){if(g(h,"global"))if(B&&(e=B.lang.System,N=e.getProperty("os.arch"),v=v||e.getProperty("os.name")+" "+e.getProperty("os.version")),z){try{n=h.require("ringo/engine").version.join("."),r="RingoJS"}catch(R){(e=h.system)&&e.global.system==h.system&&(r="Narwhal",v||(v=e[0].os||null))}r||(r="Rhino")}else"object"==typeof h.process&&
!h.process.browser&&(e=h.process)&&("object"==typeof e.versions&&("string"==typeof e.versions.electron?(k.push("Node "+e.versions.node),r="Electron",n=e.versions.electron):"string"==typeof e.versions.nw&&(k.push("Chromium "+n,"Node "+e.versions.node),r="NW.js",n=e.versions.nw)),r||(r="Node.js",N=e.arch,v=e.platform,n=(n=/[\d.]+/.exec(e.version))?n[0]:null));else f(e=h.runtime)==S?(r="Adobe AIR",v=e.flash.system.Capabilities.os):f(e=h.phantom)==T?(r="PhantomJS",n=(e=e.version||null)&&e.major+"."+e.minor+
"."+e.patch):"number"==typeof P.documentMode&&(e=/\bTrident\/(\d+)/i.exec(a))?(n=[n,P.documentMode],(e=+e[1]+4)!=n[1]&&(k.push("IE "+n[1]+" mode"),C&&(C[1]=""),n[1]=e),n="IE"==r?String(n[1].toFixed(1)):n[0]):"number"==typeof P.documentMode&&/^(?:Chrome|Firefox)\b/.test(r)&&(k.push("masking as "+r+" "+n),r="IE",n="11.0",C=["Trident"],v="Windows");v=v&&d(v)}n&&(e=/(?:[ab]|dp|pre|[ab]\d+pre)(?:\d+\+?)?$/i.exec(n)||/(?:alpha|beta)(?: ?\d)?/i.exec(a+";"+(K&&x.appMinorVersion))||/\bMinefield\b/i.test(a)&&
"a")&&(O=/b/i.test(e)?"beta":"alpha",n=n.replace(RegExp(e+"\\+?$"),"")+("beta"==O?V:U)+(/\d+\+?/.exec(e)||""));if("Fennec"==r||"Firefox"==r&&/\b(?:Android|Firefox OS)\b/.test(v))r="Firefox Mobile";else if("Maxthon"==r&&n)n=n.replace(/\.[\d.]+/,".x");else if(/\bXbox\b/i.test(D))"Xbox 360"==D&&(v=null),"Xbox 360"==D&&/\bIEMobile\b/.test(a)&&k.unshift("mobile mode");else if(!/^(?:Chrome|IE|Opera)$/.test(r)&&(!r||D||/Browser|Mobi/.test(r))||"Windows CE"!=v&&!/Mobi/i.test(a))if("IE"==r&&K)try{null===h.external&&
k.unshift("platform preview")}catch(R){k.unshift("embedded")}else(/\bBlackBerry\b/.test(D)||/\bBB10\b/.test(a))&&(e=(RegExp(D.replace(/ +/g," *")+"/([.\\d]+)","i").exec(a)||0)[1]||n)?(e=[e,/BB10/.test(a)],v=(e[1]?(D=null,F="BlackBerry"):"Device Software")+" "+e[0],n=null):this!=c&&"Wii"!=D&&(K&&J||/Opera/.test(r)&&/\b(?:MSIE|Firefox)\b/i.test(a)||"Firefox"==r&&/\bOS X (?:\d+\.){2,}/.test(v)||"IE"==r&&(v&&!/^Win/.test(v)&&5.5<n||/\bWindows XP\b/.test(v)&&8<n||8==n&&!/\bTrident\b/.test(a)))&&!u.test(e=
l.call(c,a.replace(u,"")+";"))&&e.name&&(e="ing as "+e.name+((e=e.version)?" "+e:""),u.test(r)?(/\bIE\b/.test(e)&&"Mac OS"==v&&(v=null),e="identify"+e):(e="mask"+e,r=M?d(M.replace(/([a-z])([A-Z])/g,"$1 $2")):"Opera",/\bIE\b/.test(e)&&(v=null),K||(n=null)),C=["Presto"],k.push(e));else r+=" Mobile";if(e=(/\bAppleWebKit\/([\d.]+\+?)/i.exec(a)||0)[1]){e=[parseFloat(e.replace(/\.(\d)$/,".0$1")),e];if("Safari"==r&&"+"==e[1].slice(-1))r="WebKit Nightly",O="alpha",n=e[1].slice(0,-1);else if(n==e[1]||n==(e[2]=
(/\bSafari\/([\d.]+\+?)/i.exec(a)||0)[1]))n=null;e[1]=(/\bChrome\/([\d.]+)/i.exec(a)||0)[1];537.36==e[0]&&537.36==e[2]&&28<=parseFloat(e[1])&&"WebKit"==C&&(C=["Blink"]);K&&(y||e[1])?(C&&(C[1]="like Chrome"),e=e[1]||(e=e[0],530>e?1:532>e?2:532.05>e?3:533>e?4:534.03>e?5:534.07>e?6:534.1>e?7:534.13>e?8:534.16>e?9:534.24>e?10:534.3>e?11:535.01>e?12:535.02>e?"13+":535.07>e?15:535.11>e?16:535.19>e?17:536.05>e?18:536.1>e?19:537.01>e?20:537.11>e?"21+":537.13>e?23:537.18>e?24:537.24>e?25:537.36>e?26:"Blink"!=
C?"27":"28")):(C&&(C[1]="like Safari"),e=(e=e[0],400>e?1:500>e?2:526>e?3:533>e?4:534>e?"4+":535>e?5:537>e?6:538>e?7:601>e?8:"8"));C&&(C[1]+=" "+(e+="number"==typeof e?".x":/[.+]/.test(e)?"":"+"));"Safari"==r&&(!n||45<parseInt(n))&&(n=e)}"Opera"==r&&(e=/\bzbov|zvav$/.exec(v))?(r+=" ",k.unshift("desktop mode"),"zvav"==e?(r+="Mini",n=null):r+="Mobile",v=v.replace(RegExp(" *"+e+"$"),"")):"Safari"==r&&/\bChrome\b/.exec(C&&C[1])&&(k.unshift("desktop mode"),r="Chrome Mobile",n=null,/\bOS X\b/.test(v)?(F=
"Apple",v="iOS 4.3+"):v=null);n&&0==n.indexOf(e=/[\d.]+$/.exec(v))&&-1<a.indexOf("/"+e+"-")&&(v=String(v.replace(e,"")).replace(/^ +| +$/g,""));C&&!/\b(?:Avant|Nook)\b/.test(r)&&(/Browser|Lunascape|Maxthon/.test(r)||"Safari"!=r&&/^iOS/.test(v)&&/\bSafari\b/.test(C[1])||/^(?:Adobe|Arora|Breach|Midori|Opera|Phantom|Rekonq|Rock|Samsung Internet|Sleipnir|Web)/.test(r)&&C[1])&&(e=C[C.length-1])&&k.push(e);k.length&&(k=["("+k.join("; ")+")"]);F&&D&&0>D.indexOf(F)&&k.push("on "+F);D&&k.push((/^on /.test(k[k.length-
1])?"":"on ")+D);if(v){var Q=(e=/ ([\d.+]+)$/.exec(v))&&"/"==v.charAt(v.length-e[0].length-1);v={architecture:32,family:e&&!Q?v.replace(e[0],""):v,version:e?e[1]:null,toString:function(){var a=this.version;return this.family+(a&&!Q?" "+a:"")+(64==this.architecture?" 64-bit":"")}}}(e=/\b(?:AMD|IA|Win|WOW|x86_|x)64\b/i.exec(N))&&!/\bi686\b/i.test(N)?(v&&(v.architecture=64,v.family=v.family.replace(RegExp(" *"+e),"")),r&&(/\bWOW64\b/i.test(a)||K&&/\w(?:86|32)$/.test(x.cpuClass||x.platform)&&!/\bWin64; x64\b/i.test(a))&&
k.unshift("32-bit")):v&&/^OS X/.test(v.family)&&"Chrome"==r&&39<=parseFloat(n)&&(v.architecture=64);a||(a=null);h={};h.description=a;h.layout=C&&C[0];h.manufacturer=F;h.name=r;h.prerelease=O;h.product=D;h.ua=a;h.version=r&&n;h.os=v||{architecture:null,family:null,version:null,toString:function(){return"null"}};h.parse=l;h.toString=function(){return this.description||""};h.version&&k.unshift(n);h.name&&k.unshift(r);v&&r&&(v!=String(v).split(" ")[0]||v!=r.split(" ")[0]&&!D)&&k.push(D?"("+v+")":"on "+
v);k.length&&(h.description=k.join(" "));return h}var q={"function":!0,object:!0},t=q[typeof window]&&window||this,h=q[typeof exports]&&exports;q=q[typeof module]&&module&&!module.nodeType&&module;var x=h&&q&&"object"==typeof global&&global;!x||x.global!==x&&x.window!==x&&x.self!==x||(t=x);var y=Math.pow(2,53)-1,u=/\bOpera/;x=Object.prototype;var k=x.hasOwnProperty,w=x.toString,z=l();"function"==typeof define&&"object"==typeof define.amd&&define.amd?(t.platform=z,define(function(){return z})):h&&
q?c(z,function(a,b){h[b]=a}):t.platform=z}).call(this);
function buildIOSMeta(){for(var a=[{name:"viewport",content:"width=device-width, height=device-height, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no"},{name:"apple-mobile-web-app-capable",content:"yes"},{name:"apple-mobile-web-app-status-bar-style",content:"black"}],b=0;b<a.length;b++){var d=document.createElement("meta");d.name=a[b].name;d.content=a[b].content;var c=window.document.head.querySelector('meta[name="'+d.name+'"]');c&&c.parentNode.removeChild(c);window.document.head.appendChild(d)}}
function hideIOSFullscreenPanel(){jQuery(".xxx-ios-fullscreen-message").css("display","none");jQuery(".xxx-ios-fullscreen-scroll").css("display","none");jQuery(".xxx-game-iframe-full").removeClass("xxx-game-iframe-iphone-se")}function buildIOSFullscreenPanel(){jQuery("body").append('<div class="xxx-ios-fullscreen-message"><div class="xxx-ios-fullscreen-swipe"></div></div><div class="xxx-ios-fullscreen-scroll"></div>')}
function showIOSFullscreenPanel(){jQuery(".xxx-ios-fullscreen-message").css("display","block");jQuery(".xxx-ios-fullscreen-scroll").css("display","block")}
function __iosResize(){window.scrollTo(0,0);console.log(window.devicePixelRatio);console.log(window.innerWidth);console.log(window.innerHeight);if("iPhone"===platform.product)switch(window.devicePixelRatio){case 2:switch(window.innerWidth){case 568:320!==window.innerHeight&&jQuery(".xxx-game-iframe-full").addClass("xxx-game-iframe-iphone-se");break;case 667:375===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;case 808:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();
break;default:hideIOSFullscreenPanel()}break;case 3:switch(window.innerWidth){case 736:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;case 724:375===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;case 808:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;default:hideIOSFullscreenPanel()}break;default:hideIOSFullscreenPanel()}}function iosResize(){__iosResize();setTimeout(function(){__iosResize()},500)}
function iosInIframe(){try{return window.self!==window.top}catch(a){return!0}}function isIOSLessThen13(){var a=platform.os,b=a.family.toLowerCase();a=parseFloat(a.version);return"ios"===b&&13>a?!0:!1}$(document).ready(function(){platform&&"iPhone"===platform.product&&"safari"===platform.name.toLowerCase()&&isIOSLessThen13()&&!iosInIframe()&&(buildIOSFullscreenPanel(),buildIOSMeta())});
jQuery(window).resize(function(){platform&&"iPhone"===platform.product&&"safari"===platform.name.toLowerCase()&&isIOSLessThen13()&&!iosInIframe()&&iosResize()});var s_iOffsetX,s_iOffsetY,s_bIsRetina;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}function isIOS(){var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");if(-1!==navigator.userAgent.toLowerCase().indexOf("iphone"))return s_bIsIphone=!0;for(;a.length;)if(navigator.platform===a.pop())return!0;return s_bIsIphone=!1}
function isIpad(){var a=-1!==navigator.userAgent.toLowerCase().indexOf("ipad");return!a&&navigator.userAgent.match(/Mac/)&&navigator.maxTouchPoints&&2<navigator.maxTouchPoints?!0:a}function isMobile(){return isIpad()?!0:jQuery.browser.mobile}function isRetina(){s_bIsRetina=matchMedia("(-webkit-min-device-pixel-ratio: 2), (min-device-pixel-ratio: 2), (min-resolution: 192dpi)").matches?!0:!1}
function getSize(a){var b=a.toLowerCase(),d=window.document,c=d.documentElement;if(void 0===window["inner"+a])a=c["client"+a];else if(window["inner"+a]!=c["client"+a]){var f=d.createElement("body");f.id="vpw-test-b";f.style.cssText="overflow:scroll";var g=d.createElement("div");g.id="vpw-test-d";g.style.cssText="position:absolute;top:-1000px";g.innerHTML="<style>@media("+b+":"+c["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+b+":7px!important}}</style>";f.appendChild(g);c.insertBefore(f,d.head);
a=7==g["offset"+a]?c["client"+a]:window["inner"+a];c.removeChild(f)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a="safari"===platform.name.toLowerCase()?getIOSWindowHeight():getSize("Height");var b=getSize("Width");_checkOrientation(b,a);var d=Math.min(a/CANVAS_HEIGHT,b/CANVAS_WIDTH),c=Math.round(CANVAS_WIDTH*d);d=Math.round(CANVAS_HEIGHT*d);if(d<a){var f=a-d;d+=f;c+=CANVAS_WIDTH/CANVAS_HEIGHT*f}else c<b&&(f=b-c,c+=f,d+=CANVAS_HEIGHT/CANVAS_WIDTH*f);f=a/2-d/2;var g=b/2-c/2,m=CANVAS_WIDTH/c;if(g*m<-EDGEBOARD_X||f*m<-EDGEBOARD_Y)d=Math.min(a/(CANVAS_HEIGHT-
2*EDGEBOARD_Y),b/(CANVAS_WIDTH-2*EDGEBOARD_X)),c=Math.round(CANVAS_WIDTH*d),d=Math.round(CANVAS_HEIGHT*d),f=(a-d)/2,g=(b-c)/2,m=CANVAS_WIDTH/c;s_iOffsetX=-1*g*m;s_iOffsetY=-1*f*m;0<=f&&(s_iOffsetY=0);0<=g&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_bIsRetina?(canvas=document.getElementById("canvas"),s_oStage.canvas.width=2*c,s_oStage.canvas.height=2*d,canvas.style.width=c+"px",canvas.style.height=
d+"px",b=Math.min(c/CANVAS_WIDTH,d/CANVAS_HEIGHT),s_oStage.scaleX=s_oStage.scaleY=2*b):s_bMobile?($("#canvas").css("width",c+"px"),$("#canvas").css("height",d+"px")):(s_oStage.canvas.width=c,s_oStage.canvas.height=d,b=Math.min(c/CANVAS_WIDTH,d/CANVAS_HEIGHT),s_oStage.scaleX=s_oStage.scaleY=b);0>f||(f=(a-d)/2);$("#canvas").css("top",f+"px");$("#canvas").css("left",g+"px");fullscreenHandler()}}
function _checkOrientation(a,b){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(a>b?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),
s_oMain.stopUpdate()))}function createBitmap(a,b,d){var c=new createjs.Bitmap(a),f=new createjs.Shape;b&&d?f.graphics.beginFill("#fff").drawRect(0,0,b,d):f.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);c.hitArea=f;return c}function createSprite(a,b,d,c,f,g){a=null!==b?new createjs.Sprite(a,b):new createjs.Sprite(a);b=new createjs.Shape;b.graphics.beginFill("#000000").drawRect(-d,-c,f,g);a.hitArea=b;return a}
function randomFloatBetween(a,b,d){"undefined"===typeof d&&(d=2);return parseFloat(Math.min(a+Math.random()*(b-a),b).toFixed(d))}function shuffle(a){for(var b=a.length,d,c;0!==b;)c=Math.floor(Math.random()*b),--b,d=a[b],a[b]=a[c],a[c]=d;return a}function formatTime(a){a/=1E3;var b=Math.floor(a/60);a=parseFloat(a-60*b).toFixed(1);var d="";d=10>b?d+("0"+b+":"):d+(b+":");return 10>a?d+("0"+a):d+a}
Array.prototype.sortOn=function(){var a=this.slice();if(!arguments.length)return a.sort();var b=Array.prototype.slice.call(arguments);return a.sort(function(a,c){for(var d=b.slice(),g=d.shift();a[g]==c[g]&&d.length;)g=d.shift();return a[g]==c[g]?0:a[g]>c[g]?1:-1})};function roundDecimal(a,b){var d=Math.pow(10,b);return Math.round(d*a)/d}function tweenVectors(a,b,d,c){c.set(a.getX()+d*(b.getX()-a.getX()),a.getY()+d*(b.getY()-a.getY()));return c}
function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3===a.nodeType&&(a=a.parentNode);var b=document.createEvent("MouseEvents");b.initEvent("click",!0,!0);a.dispatchEvent(b)}}};function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(a){for(var b=window.location.search.substring(1).split("&"),d=0;d<b.length;d++){var c=b[d].split("=");if(c[0]==a)return c[1]}}function playSound(a,b,d){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(s_aSounds[a].play(),s_aSounds[a].volume(b),s_aSounds[a].loop(d),s_aSounds[a]):null}function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].stop()}function setVolume(a,b){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].volume(b)}
function setMute(a,b){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].mute(b)}
(function(){function a(a){var c={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in c?document.body.className=c[a.type]:(document.body.className=this[b]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var b="hidden";b in document?document.addEventListener("visibilitychange",a):(b="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(b="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(b="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();function fullscreenHandler(){ENABLE_FULLSCREEN&&!1!==screenfull.isEnabled&&(s_bFullscreen=screenfull.isFullscreen,null!==s_oInterface&&s_oInterface.resetFullscreenBut(),null!==s_oMenu&&s_oMenu.resetFullscreenBut())}
if(screenfull.isEnabled)screenfull.on("change",function(){s_bFullscreen=screenfull.isFullscreen;null!==s_oInterface&&s_oInterface.resetFullscreenBut();null!==s_oMenu&&s_oMenu.resetFullscreenBut()});
function CSpriteLibrary(){var a={},b,d,c,f,g,m;this.init=function(a,l,q){b={};c=d=0;f=a;g=l;m=q};this.addSprite=function(c,f){if(a.hasOwnProperty(c))return!1;var g=new Image;a[c]=b[c]={szPath:f,oSprite:g,bLoaded:!1};d++;return!0};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){d=0;g.call(m)};this._onSpriteLoaded=function(){f.call(m);++c===d&&this._onSpritesLoaded()};this.loadSprites=function(){for(var a in b)b[a].oSprite.oSpriteLibrary=this,
b[a].oSprite.szKey=a,b[a].oSprite.onload=function(){this.oSpriteLibrary.setLoaded(this.szKey);this.oSpriteLibrary._onSpriteLoaded(this.szKey)},b[a].oSprite.onerror=function(a){var c=a.currentTarget;setTimeout(function(){b[c.szKey].oSprite.src=b[c.szKey].szPath},500)},b[a].oSprite.src=b[a].szPath};this.setLoaded=function(b){a[b].bLoaded=!0};this.isLoaded=function(b){return a[b].bLoaded};this.getNumSprites=function(){return d}}
var CANVAS_WIDTH=1920,CANVAS_HEIGHT=768,EDGEBOARD_X=400,EDGEBOARD_Y=0,FONT1="OpenSans-BoldItalic",FONT2="Digital-7",FPS_TIME=1E3/24,DISABLE_SOUND_MOBILE=!1,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,STATE_GAME_WAITING_FOR_BET=0,STATE_GAME_DEAL=1,STATE_GAME_CHOOSE_HOLD=2,STATE_GAME_DRAW=3,STATE_GAME_EVALUATE=4,ON_CARD_SHOWN="ON_CARD_SHOWN",ON_CARD_HIDE="ON_CARD_HIDE",ON_CARD_SELECTED="ON_CARD_SELECTED",ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=
5,NATURAL_ROYAL_FLUSH=0,FIVE_OF_A_KIND=1,ROYAL_FLUSH=2,STRAIGHT_FLUSH=3,FOUR_OF_A_KIND=4,FULL_HOUSE=5,FLUSH=6,STRAIGHT=7,THREE_OF_A_KIND=8,TWO_PAIR=9,KINGS_OR_BETTER=10,HIGH_CARD=11,CARD_TWO=2,CARD_THREE=3,CARD_FOUR=4,CARD_FIVE=5,CARD_SIX=6,CARD_SEVEN=7,CARD_EIGHT=8,CARD_NINE=9,CARD_TEN=10,CARD_JACK=11,CARD_QUEEN=12,CARD_KING=13,CARD_ACE=14,CARD_JOKER=15,SUIT_HEARTS=0,SUIT_DIAMONDS=1,SUIT_CLUBS=2,SUIT_SPADES=3,CARD_WIDTH=154,CARD_HEIGHT=240,BET_TYPE,TOTAL_MONEY,NUM_BETS=5,WIN_COMBINATIONS=11,COMBO_PRIZES,
AUTOMATIC_RECHARGE,WIN_OCCURRENCE,DOUBLE_OCCURRENCE,DOUBLE_HALF_OCCURRENCE,GAME_CASH,MIN_WIN,NUM_HAND_FOR_ADS,ENABLE_FULLSCREEN,ENABLE_CHECK_ORIENTATION,SHOW_CREDITS,SOUNDTRACK_VOLUME_IN_GAME=.5;TEXT_NO_MONEY="沒有足夠的籌碼";TEXT_PLAY="開始";TEXT_BET="押注";TEXT_WIN="贏了";TEXT_MONEY="籌碼";TEXT_DEAL="發牌";TEXT_BET_ONE="押注一";TEXT_MAX_BET="押注最大";TEXT_RECHARGE="儲值";TEXT_EXIT="退出";TEXT_DRAW="棄牌";TEXT_NO_WIN="沒贏";TEXT_CURRENCY="$";TEXT_DOUBLE_UP="比倍 2x";TEXT_DOUBLE="比倍";
TEXT_DOUBLE_HALF="半比倍 1.5x";TEXT_YOU_WON="您贏了";TEXT_YOU_LOSE="您輸了";TEXT_DOUBLEUP_TO="比倍到";TEXT_DOUBLE_HALF_TO="半比倍到";TEXT_COLLECT="收下，不比了";TEXT_DEALER_CARD="發牌員的牌";TEXT_CHOOSE_CARD="選擇一張牌!";TEXT_CREDITS_DEVELOPED="DEVELOPED BY";var TEXT_PRELOADER_CONTINUE="開始";TEXT_COMBO="正同花大順;五條;同花大順;同花順;鐵支;葫蘆;同花;順;三條;兩對;K對或更大".split(";");TEXT_CONGRATULATIONS="恭喜!";
TEXT_SHARE_1="您獲得 <strong>";TEXT_SHARE_2=" 分</strong>!<br><br>與您的好友分享獲得的分數!";TEXT_SHARE_3="我的分數是 ";TEXT_SHARE_4=" 分! 您能獲得更好的分數嗎?";
function CPreloader(){var a,b,d,c,f,g,m,p,l;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.addSprite("200x200","./sprites/200x200.jpg");s_oSpriteLibrary.loadSprites();l=new createjs.Container;s_oStage.addChild(l)};this.unload=function(){l.removeAllChildren()};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};
this.attachSprites=function(){var q=new createjs.Shape;q.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);l.addChild(q);q=s_oSpriteLibrary.getSprite("200x200");m=createBitmap(q);m.regX=.5*q.width;m.regY=.5*q.height;m.x=CANVAS_WIDTH/2;m.y=CANVAS_HEIGHT/2-180;l.addChild(m);p=new createjs.Shape;p.graphics.beginFill("rgba(0,0,0,0.01)").drawRoundRect(m.x-100,m.y-100,200,200,10);l.addChild(p);m.mask=p;q=s_oSpriteLibrary.getSprite("progress_bar");c=createBitmap(q);c.x=CANVAS_WIDTH/2-
q.width/2;c.y=CANVAS_HEIGHT/2+50;l.addChild(c);a=q.width;b=q.height;f=new createjs.Shape;f.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(c.x,c.y,1,b);l.addChild(f);c.mask=f;d=new createjs.Text("","30px "+FONT1,"#fff");d.x=CANVAS_WIDTH/2;d.y=CANVAS_HEIGHT/2+100;d.textBaseline="alphabetic";d.textAlign="center";l.addChild(d);g=new createjs.Shape;g.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);l.addChild(g);createjs.Tween.get(g).to({alpha:0},500).call(function(){createjs.Tween.removeTweens(g);
l.removeChild(g)})};this.refreshLoader=function(g){d.text=g+"%";100===g&&(s_oMain._onRemovePreloader(),d.visible=!1,c.visible=!1);f.graphics.clear();g=Math.floor(g*a/100);f.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(c.x,c.y,g,b)};this._init()}
function CMain(a){var b,d=0,c=0,f=STATE_LOADING,g,m;this.initContainer=function(){var a=document.getElementById("canvas");s_oStage=new createjs.Stage(a);createjs.Touch.enable(s_oStage,!0);s_bMobile=isMobile();!1===s_bMobile&&s_oStage.enableMouseOver(20);s_iPrevTime=(new Date).getTime();createjs.Ticker.setFPS(30);createjs.Ticker.addEventListener("tick",this._update);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;seekAndDestroy()?g=new CPreloader:
window.location.href="http://www.codethislab.com/contact-us.html"};this.soundLoaded=function(){d++;g.refreshLoader(Math.floor(d/c*100))};this._initSounds=function(){Howler.mute(!s_bAudioActive);s_aSoundsInfo=[];s_aSoundsInfo.push({path:"./sounds/",filename:"card",loop:!1,volume:1,ingamename:"card"});s_aSoundsInfo.push({path:"./sounds/",filename:"press_but",loop:!1,volume:1,ingamename:"press_but"});s_aSoundsInfo.push({path:"./sounds/",filename:"win",loop:!0,volume:1,ingamename:"win"});s_aSoundsInfo.push({path:"./sounds/",
filename:"lose",loop:!1,volume:1,ingamename:"lose"});s_aSoundsInfo.push({path:"./sounds/",filename:"press_hold",loop:!1,volume:1,ingamename:"press_hold"});s_aSoundsInfo.push({path:"./sounds/",filename:"soundtrack",loop:!0,volume:1,ingamename:"soundtrack"});c+=s_aSoundsInfo.length;s_aSounds=[];for(var a=0;a<s_aSoundsInfo.length;a++)this.tryToLoadSound(s_aSoundsInfo[a],!1)};this.tryToLoadSound=function(a,b){setTimeout(function(){s_aSounds[a.ingamename]=new Howl({src:[a.path+a.filename+".mp3"],autoplay:!1,
preload:!0,loop:a.loop,volume:a.volume,onload:s_oMain.soundLoaded,onloaderror:function(a,b){for(var c=0;c<s_aSoundsInfo.length;c++)if(a===s_aSounds[s_aSoundsInfo[c].ingamename]._sounds[0]._id){s_oMain.tryToLoadSound(s_aSoundsInfo[c],!0);break}},onplayerror:function(a){for(var b=0;b<s_aSoundsInfo.length;b++)if(a===s_aSounds[s_aSoundsInfo[b].ingamename]._sounds[0]._id){s_aSounds[s_aSoundsInfo[b].ingamename].once("unlock",function(){s_aSounds[s_aSoundsInfo[b].ingamename].play();"soundtrack"===s_aSoundsInfo[b].ingamename&&
null!==s_oGame&&setVolume("soundtrack",SOUNDTRACK_VOLUME_IN_GAME)});break}}})},b?200:0)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("but_menu_bg","./sprites/but_menu_bg.png");s_oSpriteLibrary.addSprite("but_game_bg","./sprites/but_game_bg.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");
s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("card_spritesheet","./sprites/card_spritesheet.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("but_left","./sprites/but_left.png");s_oSpriteLibrary.addSprite("but_right","./sprites/but_right.png");s_oSpriteLibrary.addSprite("hold","./sprites/hold.png");s_oSpriteLibrary.addSprite("logo_game","./sprites/logo_game.png");s_oSpriteLibrary.addSprite("paytable","./sprites/paytable.png");
s_oSpriteLibrary.addSprite("display_bg","./sprites/display_bg.png");s_oSpriteLibrary.addSprite("big_display","./sprites/big_display.png");s_oSpriteLibrary.addSprite("selection","./sprites/selection.png");s_oSpriteLibrary.addSprite("card_selection","./sprites/card_selection.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");s_oSpriteLibrary.addSprite("bg_doubleup","./sprites/bg_doubleup.jpg");s_oSpriteLibrary.addSprite("but_credits","./sprites/but_credits.png");s_oSpriteLibrary.addSprite("ctl_logo",
"./sprites/ctl_logo.png");c+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){d++;g.refreshLoader(Math.floor(d/c*100))};this.preloaderReady=function(){this._loadImages();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();b=!0};this._onRemovePreloader=function(){g.unload();s_oSoundTrack=playSound("soundtrack",1,!0);this.gotoMenu()};this._onAllImagesLoaded=function(){};this.gotoMenu=function(){new CMenu;f=STATE_MENU};this.gotoGame=function(){m=
new CGame(p);f=STATE_GAME;$(s_oMain).trigger("game_start")};this.gotoHelp=function(){new CHelp;f=STATE_HELP};this.stopUpdate=function(){b=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||Howler.mute(!0)};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();b=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none");(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)&&s_bAudioActive&&Howler.mute(!1)};this._update=function(a){if(!1!==
b){var c=(new Date).getTime();s_iTimeElaps=c-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=c;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);f===STATE_GAME&&m.update();s_oStage.update(a)}};s_oMain=this;var p=a;ENABLE_FULLSCREEN=p.fullscreen;ENABLE_CHECK_ORIENTATION=p.check_orientation;SHOW_CREDITS=p.show_credits;s_bAudioActive=a.audio_enable_on_startup;this.initContainer()}
var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain=null,s_oSpriteLibrary,s_oSoundTrack=null,s_bFullscreen=!1,s_aSounds,s_aSoundsInfo;
function CTextButton(a,b,d,c,f,g,m,p,l){var q,t,h,x,y,u,k,w,z,B;this._init=function(a,b,c,d,f,g,k,m){q=!1;t=1;h=[];x=[];B=createBitmap(c);w=new createjs.Container;w.x=a;w.y=b;w.regX=c.width/2;w.regY=c.height/2;s_bMobile||(w.cursor="pointer");w.addChild(B,z);l.addChild(w);z=new CTLText(w,10,5,c.width-20,c.height-10,k,"center",g,f,1,m,0,d,!0,!0,!0,!1);this._initListener()};this.unload=function(){w.off("mousedown",y);w.off("pressup",u);l.removeChild(w)};this.setVisible=function(a){w.visible=a};this.setAlign=
function(a){z.textAlign=a};this.setTextX=function(a){z.x=a};this.setScale=function(a){t=w.scaleX=w.scaleY=a};this.enable=function(){q=!1};this.disable=function(){q=!0};this._initListener=function(){y=w.on("mousedown",this.buttonDown);u=w.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){h[a]=b;x[a]=c};this.addEventListenerWithParams=function(a,b,c,d){h[a]=b;x[a]=c;k=d};this.buttonRelease=function(){q||(playSound("press_but",1,!1),w.scaleX=t,w.scaleY=t,h[ON_MOUSE_UP]&&h[ON_MOUSE_UP].call(x[ON_MOUSE_UP],
k))};this.buttonDown=function(){q||(w.scaleX=.9*t,w.scaleY=.9*t,h[ON_MOUSE_DOWN]&&h[ON_MOUSE_DOWN].call(x[ON_MOUSE_DOWN]))};this.setPosition=function(a,b){w.x=a;w.y=b};this.tweenPosition=function(a,b,c,d,f,g,h){createjs.Tween.get(w).wait(d).to({x:a,y:b},c,f).call(function(){void 0!==g&&g.call(h)})};this.changeText=function(a){z.refreshText(a)};this.setX=function(a){w.x=a};this.setY=function(a){w.y=a};this.getButtonImage=function(){return w};this.getX=function(){return w.x};this.getY=function(){return w.y};
this.getSprite=function(){return w};this.getScale=function(){return w.scaleX};this._init(a,b,d,c,f,g,m,p)}
function CGfxButton(a,b,d,c){var f,g,m,p,l,q,t=[],h;this._init=function(a,b,c){f=!1;l=[];q=[];g=c.width;m=c.height;h=createBitmap(c);h.x=a;h.y=b;h.regX=c.width/2;h.regY=c.height/2;h.cursor="pointer";x.addChild(h);this._initListener()};this.unload=function(){h.off("mousedown",p[0]);h.off("pressup",p[1]);x.removeChild(h)};this.setVisible=function(a){h.visible=a};this._initListener=function(){p=[];p[0]=h.on("mousedown",this.buttonDown);p[1]=h.on("pressup",this.buttonRelease)};this.addEventListener=function(a,
b,c){l[a]=b;q[a]=c};this.addEventListenerWithParams=function(a,b,c,d){l[a]=b;q[a]=c;t=d};this.buttonRelease=function(){f||(playSound("press_but",1,!1),h.scaleX=1,h.scaleY=1,l[ON_MOUSE_UP]&&l[ON_MOUSE_UP].call(q[ON_MOUSE_UP],t))};this.buttonDown=function(){f||(h.scaleX=.9,h.scaleY=.9,l[ON_MOUSE_DOWN]&&l[ON_MOUSE_DOWN].call(q[ON_MOUSE_DOWN],t))};this.setPosition=function(a,b){h.x=a;h.y=b};this.setX=function(a){h.x=a};this.setY=function(a){h.y=a};this.enable=function(){f=!1;h.filters=[];h.cache(0,0,
g,m)};this.disable=function(){f=!0;var a=(new createjs.ColorMatrix).adjustSaturation(-100).adjustBrightness(40);h.filters=[new createjs.ColorMatrixFilter(a)];h.cache(0,0,g,m)};this.getButtonImage=function(){return h};this.getX=function(){return h.x};this.getY=function(){return h.y};var x=c;this._init(a,b,d);return this}
function CToggle(a,b,d,c){var f,g,m,p,l;this._init=function(a,b,c,d){m=[];p=[];var g=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});f=d;l=createSprite(g,"state_"+f,c.width/2/2,c.height/2,c.width/2,c.height);l.x=a;l.y=b;l.stop();l.cursor="pointer";s_oStage.addChild(l);this._initListener()};this.unload=function(){l.off("mousedown",g[0]);l.off("pressup",g[1]);s_oStage.removeChild(l)};this._initListener=
function(){g=[];g[0]=l.on("mousedown",this.buttonDown);g[1]=l.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){m[a]=b;p[a]=c};this.setActive=function(a){f=a;l.gotoAndStop("state_"+f)};this.buttonRelease=function(){l.scaleX=1;l.scaleY=1;playSound("press_but",1,!1);f=!f;l.gotoAndStop("state_"+f);m[ON_MOUSE_UP]&&m[ON_MOUSE_UP].call(p[ON_MOUSE_UP],f)};this.buttonDown=function(){l.scaleX=.9;l.scaleY=.9;m[ON_MOUSE_DOWN]&&m[ON_MOUSE_DOWN].call(p[ON_MOUSE_DOWN])};this.setPosition=function(a,
b){l.x=a;l.y=b};this._init(a,b,d,c)}
function CMenu(){var a,b,d,c,f,g,m,p,l,q,t,h=null,x=null,y;this._init=function(){m=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(m);var u=s_oSpriteLibrary.getSprite("but_menu_bg");p=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-164,u,TEXT_PLAY,FONT1,"#ffffff",40,0,s_oStage);p.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)u=s_oSpriteLibrary.getSprite("audio_icon"),f=CANVAS_WIDTH-u.width/4-10,g=u.height/2+10,l=new CToggle(CANVAS_WIDTH-
u.width/2+20,u.height/2+20,u,s_bAudioActive),l.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);SHOW_CREDITS?(u=s_oSpriteLibrary.getSprite("but_credits"),a=u.height/2+10,b=u.height/2+10,q=new CGfxButton(a,b,u,s_oStage),q.addEventListener(ON_MOUSE_UP,this._onButCreditsRelease,this),d=a+u.width+10,c=b):(d=u.height/2+10,c=u.height/2+10);u=window.document;var k=u.documentElement;h=k.requestFullscreen||k.mozRequestFullScreen||k.webkitRequestFullScreen||k.msRequestFullscreen;x=u.exitFullscreen||u.mozCancelFullScreen||
u.webkitExitFullscreen||u.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(h=!1);h&&screenfull.isEnabled&&(u=s_oSpriteLibrary.getSprite("but_fullscreen"),t=new CToggle(d,c,u,s_bFullscreen,!0),t.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));y=new createjs.Shape;y.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(y);createjs.Tween.get(y).to({alpha:0},500).call(function(){y.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){p.unload();
p=null;SHOW_CREDITS&&q.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)l.unload(),l=null;h&&screenfull.isEnabled&&t.unload();s_oStage.removeChild(m);m=null;s_oStage.removeChild(y);s_oMenu=y=null};this.refreshButtonPos=function(m,k){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||l.setPosition(f-m,k+g);h&&screenfull.isEnabled&&t.setPosition(d+m,c+k);SHOW_CREDITS&&q.setPosition(a+m,b+k)};this._onButCreditsRelease=function(){new CCreditsPanel};this._onButPlayRelease=function(){this.unload();$(s_oMain).trigger("start_session");
s_oMain.gotoGame()};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this.resetFullscreenBut=function(){h&&screenfull.isEnabled&&t.setActive(s_bFullscreen)};this._onFullscreenRelease=function(){s_bFullscreen?x.call(window.document):h.call(window.document.documentElement);sizeHandler()};s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(a){var b,d,c,f,g,m,p,l,q,t,h,x,y,u,k=[],w,z,B,E,H,A,I,G,n,L;this._init=function(){s_oPayTableSettings=new CPayTableSettings;c=TOTAL_MONEY;f=GAME_CASH;E=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(E);L=new createjs.Container;L.x=600;L.y=530;s_oStage.addChild(L);I=new CPayTable(550,140);b=!1;h=l=p=0;g=parseFloat(BET_TYPE[p]*(l+1));I.setCreditColumn(l);t=STATE_GAME_WAITING_FOR_BET;A=new CInterface(c,BET_TYPE[p]);n=new CAlertPanel;z=new CGameSettings;B=new CHandEvaluator;
q=0;w=[];w=z.getShuffledCardDeck();y=0;u=z.getShuffledDeckForDouble();MIN_WIN=COMBO_PRIZES[COMBO_PRIZES.length-1]*g*(l+1);this.placeFakeCardForStarting();G=new CDoubleUpPanel(H);setVolume("soundtrack",SOUNDTRACK_VOLUME_IN_GAME)};this.unload=function(){A.unload();n.unload();s_oStage.removeAllChildren()};this.resetHand=function(){q=m=0;w=[];w=z.getShuffledCardDeck();for(var a=0;a<k.length;a++)k[a].reset();A.resetHand();I.resetHand();this.checkMoney();b=!1;t=STATE_GAME_WAITING_FOR_BET};this.checkMoney=
function(){c<g&&(l=p=0,g=parseFloat(BET_TYPE[p]*(l+1)),c<g?this._showAlertPanel(TEXT_NO_MONEY):(A.refreshMoney(c,g),A.refreshBet(BET_TYPE[p])))};this.changeState=function(a){};this.placeFakeCardForStarting=function(){var a={images:[s_oSpriteLibrary.getSprite("card_spritesheet")],frames:{width:CARD_WIDTH,height:CARD_HEIGHT,regX:CARD_WIDTH/2,regY:CARD_HEIGHT/2},animations:{card_1_1:[0],card_1_2:[1],card_1_3:[2],card_1_4:[3],card_1_5:[4],card_1_6:[5],card_1_7:[6],card_1_8:[7],card_1_9:[8],card_1_10:[9],
card_1_J:[10],card_1_Q:[11],card_1_K:[12],card_2_1:[13],card_2_2:[14],card_2_3:[15],card_2_4:[16],card_2_5:[17],card_2_6:[18],card_2_7:[19],card_2_8:[20],card_2_9:[21],card_2_10:[22],card_2_J:[23],card_2_Q:[24],card_2_K:[25],card_3_1:[26],card_3_2:[27],card_3_3:[28],card_3_4:[29],card_3_5:[30],card_3_6:[31],card_3_7:[32],card_3_8:[33],card_3_9:[34],card_3_10:[35],card_3_J:[36],card_3_Q:[37],card_3_K:[38],card_4_1:[39],card_4_2:[40],card_4_3:[41],card_4_4:[42],card_4_5:[43],card_4_6:[44],card_4_7:[45],
card_4_8:[46],card_4_9:[47],card_4_10:[48],card_4_J:[49],card_4_Q:[50],card_4_K:[51],joker:[52],back:[53]}};H=new createjs.SpriteSheet(a);for(var b=a=0;5>b;b++){var c=createSprite(H,"back",CARD_WIDTH/2,CARD_HEIGHT/2,CARD_WIDTH,CARD_HEIGHT);c.x=a;c.y=0;c.shadow=new createjs.Shadow("#000000",5,5,5);L.addChild(c);a+=180}};this.dealCards=function(){if(!(b||0>=c)){b=!0;$(s_oMain).trigger("bet_placed",g);L.removeAllChildren();m=0;if((f<MIN_WIN?WIN_OCCURRENCE+1:Math.floor(100*Math.random()))>WIN_OCCURRENCE){do this._createCard();
while(B.evaluate(k)<HIGH_CARD);d=!1}else{var a=0;do{this._createCard();var h=B.evaluate(k),p=0;h<HIGH_CARD&&(p=s_oPayTableSettings.getWin(l,h)*g);a++}while(f<p&&5E3>a);if(5E3<=a){do this._createCard();while(B.evaluate(k)<HIGH_CARD);d=!1}else d=!0}c-=g;c=parseFloat(c.toFixed(2));f+=g;f=parseFloat(f.toFixed(2));A.refreshMoney(c,g);playSound("card",1,!1);t=STATE_GAME_DEAL}};this._createCard=function(){for(var a=0;a<k.length;a++)k[a].unload();a=0;k=[];for(var b=0;5>b;b++){var c=new CCard(a,0,H,L,w[q].fotogram,
w[q].rank,w[q].suit);c.addEventListener(ON_CARD_SHOWN,this._onCardShown,this);c.addEventListener(ON_CARD_HIDE,this._onCardHide,this);c.addEventListener(ON_CARD_SELECTED,this._onCardSelected,this);k.push(c);q++;this._checkDeckLength();a+=180;c.showCard()}};this.drawCards=function(){if(!b){b=!0;playSound("card",1,!1);for(var a=k.length,c=0;c<k.length;c++)!1===k[c].isHold()&&(k[c].hideCard(),a--);a===k.length&&(t=STATE_GAME_DRAW,this._onCardShown())}};this._checkDeckLength=function(){q>=w.length&&(w=
z.getShuffledCardDeck(),q=0)};this.setDoubleBet=function(){var a;y+5>=u.length&&(y=0,u=z.getShuffledDeckForDouble());var b=[];for(a=0;5>a;a++)b[a]=u[y],y++;b.sort(B.compareRank);var c=Math.floor(Math.random()*(b.length-3))+1;(f<2*m?DOUBLE_OCCURRENCE+1:Math.floor(100*Math.random()))<DOUBLE_OCCURRENCE?(a=!0,m*=2,m=parseFloat(m.toFixed(2))):(m=0,a=!1);return{win:a,cards:b,dealer_index:c}};this.setDoubleHalfBet=function(){y+5>=u.length&&(y=0,u=z.getShuffledDeckForDouble());for(var a=[],b=0;5>b;b++)a[b]=
u[y],y++;a.sort(B.compareRank);b=Math.floor(Math.random()*(a.length-3))+1;var d=m/2;c+=d;c=parseFloat(c.toFixed(2));f-=d;f=parseFloat(f.toFixed(2));(f<1.5*m?DOUBLE_HALF_OCCURRENCE+1:Math.floor(100*Math.random()))<DOUBLE_HALF_OCCURRENCE?d=!0:(d=!1,m=0);return{win:d,cards:a,dealer_index:b}};this.assignWin=function(){playSound("win",1,!1);for(var a=B.getSortedHand(),b=0;b<k.length;b++)for(var c=0;c<a.length;c++)if(a[c].rank===k[b].getRank()&&a[c].suit===k[b].getSuit()){k[b].highlight();break}I.showWinAnim(l,
x);m=s_oPayTableSettings.getWin(l,x)*BET_TYPE[p]};this.recharge=function(){n.hide()};this.setMoney=function(a){c=a;I.setCreditColumn(l);this.checkMoney();A.refreshMoney(c,g);A.refreshBet(BET_TYPE[p]);A.enableGUI()};this._showAlertPanel=function(a){n.show(a)};this._onCardSelected=function(a,b){t===STATE_GAME_CHOOSE_HOLD&&a.toggleHold()};this._onCardShown=function(){if(t!==STATE_GAME_CHOOSE_HOLD){switch(t){case STATE_GAME_DEAL:t=STATE_GAME_CHOOSE_HOLD;A.setState(t);A.enableDeal();break;case STATE_GAME_DRAW:x=
B.evaluate(k);A.setState(t);x!==HIGH_CARD?(s_oGame.assignWin(),setTimeout(function(){G.show(m,2*m,1.5*m)},3E3)):(playSound("lose",1,!1),A.showLosePanel(),A.enableGUI());t=STATE_GAME_EVALUATE;d||$(s_oMain).trigger("save_score",[c]);h++;h===NUM_HAND_FOR_ADS&&(h=0,$(s_oMain).trigger("show_interlevel_ad"));break;case STATE_GAME_EVALUATE:A.setState(t)}b=!1}};this.exitFromDoublePanel=function(){c+=m;c=parseFloat(c.toFixed(2));f-=m;f=parseFloat(f.toFixed(2));A.refreshWin(m);A.refreshMoney(c,g);t=STATE_GAME_EVALUATE;
A.setState(t);A.enableGUI();$(s_oMain).trigger("save_score",[c])};this.exitFromAlertPanel=function(){b=!1};this._onCardHide=function(){if(t!==STATE_GAME_DRAW){t=STATE_GAME_DRAW;if(d){var a=0;do{s_oGame._changeCardValue();var b=B.evaluate(k);var c=b===HIGH_CARD?0:s_oPayTableSettings.getWin(l,b)*g;a++}while((b===HIGH_CARD||f<c)&&1E3>a);if(1E3<=a){do s_oGame._changeCardValue(),b=B.evaluate(k);while(b<HIGH_CARD);d=!1}}else{do s_oGame._changeCardValue(),b=B.evaluate(k);while(b<HIGH_CARD)}for(a=0;5>a;a++)k[a].setHold(!1)}};
this._changeCardValue=function(){for(var a=0;5>a;a++)!1===k[a].isHold()&&(k[a].changeInfo(w[q].fotogram,w[q].rank,w[q].suit),k[a].showCard(),q++,this._checkDeckLength())};this._onButDealRelease=function(){switch(t){case STATE_GAME_WAITING_FOR_BET:this.dealCards();break;case STATE_GAME_CHOOSE_HOLD:this.drawCards();break;case STATE_GAME_EVALUATE:this.resetHand(),this.dealCards()}};this._onButLeftRelease=function(){if(!(0===p||b||t!==STATE_GAME_WAITING_FOR_BET&&t!==STATE_GAME_EVALUATE)){p--;var a=parseFloat(BET_TYPE[p]*
(l+1));c<a?p++:(g=a,A.refreshMoney(c,g),A.refreshBet(BET_TYPE[p]),MIN_WIN=COMBO_PRIZES[COMBO_PRIZES.length-1]*g*(l+1))}};this._onButRightRelease=function(){if(!(p===BET_TYPE.length-1||b||t!==STATE_GAME_WAITING_FOR_BET&&t!==STATE_GAME_EVALUATE)){p++;var a=parseFloat(BET_TYPE[p]*(l+1));c<a?p--:(g=a,A.refreshMoney(c,g),A.refreshBet(BET_TYPE[p]),MIN_WIN=COMBO_PRIZES[COMBO_PRIZES.length-1]*g*(l+1))}};this._onButBetOneRelease=function(){if(!(b||t!==STATE_GAME_WAITING_FOR_BET&&t!==STATE_GAME_EVALUATE)){l++;
l===NUM_BETS&&(l=0);var a=parseFloat(BET_TYPE[p]*(l+1));c<a&&(l=0,a=parseFloat(BET_TYPE[p]*(l+1)));g=a;A.refreshMoney(c,g);I.setCreditColumn(l);MIN_WIN=COMBO_PRIZES[COMBO_PRIZES.length-1]*g*(l+1)}};this._onButBetMaxRelease=function(){if(!(b||t!==STATE_GAME_WAITING_FOR_BET&&t!==STATE_GAME_EVALUATE)){b=!0;l=NUM_BETS-1;var a=parseFloat(BET_TYPE[p]*(l+1));c<a?this._showAlertPanel(TEXT_NO_MONEY):(g=a,A.refreshMoney(c,g),I.setCreditColumn(l),MIN_WIN=COMBO_PRIZES[COMBO_PRIZES.length-1]*g*(l+1),this.resetHand(),
this.dealCards())}};this.onExit=function(){this.unload();s_oMain.gotoMenu();$(s_oMain).trigger("end_session");$(s_oMain).trigger("share_event",[c])};this.getCurWin=function(){return m};this.update=function(){};s_oGame=this;WIN_OCCURRENCE=a.win_occurrence;DOUBLE_OCCURRENCE=a.double_occurrence;DOUBLE_HALF_OCCURRENCE=a.double_half_occurrence;GAME_CASH=a.game_cash;BET_TYPE=a.bets;COMBO_PRIZES=a.combo_prizes;TOTAL_MONEY=a.money;AUTOMATIC_RECHARGE=a.recharge;NUM_HAND_FOR_ADS=a.num_hand_before_ads;this._init()}
var s_oGame,s_oPayTableSettings;
function CInterface(a,b){var d,c,f,g,m,p,l,q,t,h,x,y,u,k,w,z,B,E,H,A=null,I=null;this._init=function(a,b){var n=s_oSpriteLibrary.getSprite("but_exit");f=CANVAS_WIDTH-n.width/2-10;g=n.height/2+10;l=new CGfxButton(f,g,n,s_oStage);l.addEventListener(ON_MOUSE_UP,this._onExit,this);!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(m=l.getX()-n.width-10,p=n.height/2+10,u=new CToggle(m,p,s_oSpriteLibrary.getSprite("audio_icon"),s_bAudioActive),u.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this),d=m-n.width-
10,c=p):(d=l.getX()-n.width-10,c=n.height/2+10);n=window.document;var G=n.documentElement;A=G.requestFullscreen||G.mozRequestFullScreen||G.webkitRequestFullScreen||G.msRequestFullscreen;I=n.exitFullscreen||n.mozCancelFullScreen||n.webkitExitFullscreen||n.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(A=!1);A&&screenfull.isEnabled&&(n=s_oSpriteLibrary.getSprite("but_fullscreen"),H=new CToggle(d,c,n,s_bFullscreen,!0),H.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));n=createBitmap(s_oSpriteLibrary.getSprite("display_bg"));
n.x=480;n.y=17;s_oStage.addChild(n);new CTLText(s_oStage,470,12,100,22,22,"left","#fff",FONT1,1,0,0,TEXT_WIN,!0,!0,!1,!1);n=createBitmap(s_oSpriteLibrary.getSprite("display_bg"));n.x=480;n.y=81;s_oStage.addChild(n);new CTLText(s_oStage,470,75,100,22,22,"left","#fff",FONT1,1,0,0,TEXT_BET,!0,!0,!1,!1);z=new CTLText(s_oStage,490,96,200,30,30,"center","#ffde00",FONT2,1,0,0,b.toFixed(2)+TEXT_CURRENCY,!0,!0,!1,!1);w=new CTLText(s_oStage,490,30,200,30,30,"center","#ffde00",FONT2,1,0,0,"0"+TEXT_CURRENCY,
!0,!0,!1,!1);n=createBitmap(s_oSpriteLibrary.getSprite("display_bg"));n.x=472;n.y=694;s_oStage.addChild(n);new CTLText(s_oStage,460,685,100,22,22,"left","#fff",FONT1,1,0,0,TEXT_MONEY,!0,!0,!1,!1);k=new CTLText(s_oStage,480,CANVAS_HEIGHT-60,200,30,30,"center","#ffde00",FONT2,1,0,0,a.toFixed(2)+TEXT_CURRENCY,!0,!0,!1,!1);n=createBitmap(s_oSpriteLibrary.getSprite("big_display"));n.x=779;n.y=693;s_oStage.addChild(n);B=new CTLText(s_oStage,786,700,100,40,40,"center","#ffde00",FONT2,1,0,0,b.toFixed(2)+
TEXT_CURRENCY,!0,!0,!1,!1);n=s_oSpriteLibrary.getSprite("logo_game");G=createBitmap(n);G.x=CANVAS_WIDTH/2;G.y=17;G.regX=n.width/2;s_oStage.addChild(G);n=s_oSpriteLibrary.getSprite("but_left");q=new CGfxButton(744,722,n,s_oStage);q.addEventListener(ON_MOUSE_UP,this._onButLeftRelease,this);n=s_oSpriteLibrary.getSprite("but_right");t=new CGfxButton(930,722,n,s_oStage);t.addEventListener(ON_MOUSE_UP,this._onButRightRelease,this);n=s_oSpriteLibrary.getSprite("but_game_bg");h=new CTextButton(1040,720,n,
TEXT_BET_ONE,FONT1,"#ffffff",23,0,s_oStage);h.addEventListener(ON_MOUSE_UP,this._onButBetOneRelease,this);x=new CTextButton(1190,720,n,TEXT_MAX_BET,FONT1,"#ffffff",23,0,s_oStage);x.addEventListener(ON_MOUSE_UP,this._onButBetMaxRelease,this);y=new CTextButton(1340,720,n,TEXT_DEAL,FONT1,"#ffffff",30,0,s_oStage);y.addEventListener(ON_MOUSE_UP,this._onButDealRelease,this);E=new createjs.Container;E.visible=!1;E.x=710;E.y=500;s_oStage.addChild(E);n=new createjs.Shape;n.graphics.beginFill("rgba(0,0,0,0.7)").drawRect(0,
0,500,100);E.addChild(n);new CTLText(E,0,0,500,100,50,"center","#fff",FONT1,1,10,5,TEXT_NO_WIN,!0,!0,!1,!1);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){l.unload();q.unload();t.unload();h.unload();x.unload();y.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)u.unload(),u=null;A&&screenfull.isEnabled&&H.unload();s_oInterface=null};this.refreshButtonPos=function(a,b){l.setPosition(f-a,b+g);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||u.setPosition(m-a,b+p);A&&screenfull.isEnabled&&
H.setPosition(d-a,c+b)};this.setState=function(a){switch(a){case STATE_GAME_CHOOSE_HOLD:y.changeText(TEXT_DRAW);break;case STATE_GAME_EVALUATE:y.changeText(TEXT_DEAL)}};this.enableDeal=function(){y.enable()};this.enableGUI=function(){q.enable();t.enable();h.enable();x.enable();y.enable()};this.disableGUI=function(){q.disable();t.disable();h.disable();x.disable();y.disable()};this.resetHand=function(){this.refreshWin(0);E.visible=!1};this.refreshMoney=function(a,b){k.refreshText(a.toFixed(2)+TEXT_CURRENCY);
z.refreshText(b.toFixed(2)+TEXT_CURRENCY)};this.refreshWin=function(a){w.refreshText(a.toFixed(2)+TEXT_CURRENCY)};this.refreshBet=function(a){B.refreshText(a.toFixed(2)+TEXT_CURRENCY)};this.showLosePanel=function(){E.visible=!0};this._onButLeftRelease=function(){s_oGame._onButLeftRelease()};this._onButRightRelease=function(){s_oGame._onButRightRelease()};this._onButBetOneRelease=function(){s_oGame._onButBetOneRelease()};this._onButBetMaxRelease=function(){s_oInterface.disableGUI();s_oGame._onButBetMaxRelease()};
this._onButDealRelease=function(){s_oInterface.disableGUI();s_oGame._onButDealRelease()};this._onExit=function(){s_oGame.onExit()};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this.resetFullscreenBut=function(){A&&screenfull.isEnabled&&H.setActive(s_bFullscreen)};this._onFullscreenRelease=function(){s_bFullscreen?I.call(window.document):A.call(window.document.documentElement);sizeHandler()};s_oInterface=this;this._init(a,b);return this}
var s_oInterface=null;
function CGameSettings(){var a,b,d;this._init=function(){var c=-1;b=[];a=[];for(var d=0;52>d;d++){var g=(d+1)%13;1===g?(g=14,c++):0===g&&(g=13);b.push({fotogram:d,rank:g,suit:c});a.push({fotogram:d,rank:g,suit:c})}b.push({fotogram:d,rank:15,suit:0})};this.timeToString=function(a){a=Math.round(a/1E3);var b=Math.floor(a/60);a-=60*b;var c="";c=10>b?c+("0"+b+":"):c+(b+":");return 10>a?c+("0"+a):c+a};this.getShuffledCardDeck=function(){for(var a=[],f=0;f<b.length;f++)a[f]=b[f];for(d=[];0<a.length;)d.push(a.splice(Math.round(Math.random()*
(a.length-1)),1)[0]);return d};this.getShuffledDeckForDouble=function(){for(var b=[],d=0;d<a.length;d++)b[d]=a[d];for(a=[];0<b.length;)a.push(b.splice(Math.round(Math.random()*(b.length-1)),1)[0]);return a};this.getCardValue=function(a){return(void 0)[a]};this._init()}
function CCard(a,b,d,c,f,g,m){var p,l,q,t,h,x,y,u,k,w,z,B;this._init=function(a,b,c,d,f,g,m){p=!1;B=d;l=f;q=g;t=m;u=createSprite(c,"back",CARD_WIDTH/2,CARD_HEIGHT/2,CARD_WIDTH,CARD_HEIGHT);u.x=a;u.y=b;u.stop();u.shadow=new createjs.Shadow("#000000",5,5,5);B.addChild(u);c=s_oSpriteLibrary.getSprite("card_selection");z=createBitmap(c);z.x=a;z.y=b;z.regX=c.width/2;z.regY=c.height/2;z.visible=!1;B.addChild(z);c=s_oSpriteLibrary.getSprite("hold");k=createBitmap(c);k.regX=c.width/2;k.x=a;k.y=b+66;k.visible=
!1;B.addChild(k);w=new createjs.Shape;w.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(a-CARD_WIDTH/2,b-CARD_HEIGHT/2,CARD_WIDTH,CARD_HEIGHT);w.on("click",this._onSelected);w.cursor="pointer";B.addChild(w);h=[];x=[]};this.unload=function(){w.off("click",this._onSelected);B.removeChild(u)};this.reset=function(){p=!1;z.visible=!1;u.shadow=new createjs.Shadow("#000000",5,5,5)};this.disable=function(){B.removeChild(w)};this.addEventListener=function(a,b,c){h[a]=b;x[a]=c};this.addEventListenerWithParams=
function(a,b,c,d){h[a]=b;x[a]=c;y=d};this.changeInfo=function(a,b,c){l=a;q=b;t=c};this.setValue=function(){u.gotoAndStop(l);var a=this;createjs.Tween.get(u).to({scaleX:1},200).call(function(){a.cardShown()})};this.setHold=function(a){p=a;k.visible=p};this.toggleHold=function(){p=!p;k.visible=p;playSound("press_hold",1,!1)};this.showCard=function(){var a=this;createjs.Tween.get(u).to({scaleX:.1},200).call(function(){a.setValue()})};this.hideCard=function(){var a=this;createjs.Tween.get(u).to({scaleX:.1},
200).call(function(){a.setBack()})};this.setBack=function(){u.gotoAndStop("back");var a=this;createjs.Tween.get(u).to({scaleX:1},200).call(function(){a.cardHidden()})};this.cardShown=function(){h[ON_CARD_SHOWN]&&h[ON_CARD_SHOWN].call(x[ON_CARD_SHOWN])};this.cardHidden=function(){h[ON_CARD_HIDE]&&h[ON_CARD_HIDE].call(x[ON_CARD_HIDE],this)};this.highlight=function(){u.shadow=new createjs.Shadow("#fff000",0,0,15);z.visible=!0};this._onSelected=function(){h[ON_CARD_SELECTED]&&h[ON_CARD_SELECTED].call(x[ON_CARD_SELECTED],
E,y)};this.getRank=function(){return q};this.getSuit=function(){return t};this.getFotogram=function(){return l};this.isHold=function(){return p};var E=this;this._init(a,b,d,c,f,g,m)}
function CAlertPanel(){var a,b,d,c,f;this._init=function(){f=new createjs.Container;s_oStage.addChild(f);var g=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));f.addChild(g);b=new CTLText(f,CANVAS_WIDTH/2-248,CANVAS_HEIGHT/2-98,500,50,50,"center","#000",FONT1,1,0,0," ",!0,!0,!1,!1);a=new CTLText(f,CANVAS_WIDTH/2-250,CANVAS_HEIGHT/2-100,500,50,50,"center","#fff",FONT1,1,0,0," ",!0,!0,!1,!1);d=new CTextButton(CANVAS_WIDTH/2-100,450,s_oSpriteLibrary.getSprite("but_game_bg"),TEXT_RECHARGE,FONT1,"#fff",
20,0,f);d.addEventListener(ON_MOUSE_UP,this._onRecharge,this);c=new CTextButton(CANVAS_WIDTH/2+100,450,s_oSpriteLibrary.getSprite("but_game_bg"),TEXT_EXIT,FONT1,"#fff",20,0,f);c.addEventListener(ON_MOUSE_UP,this._onExit,this);this.hide()};this.unload=function(){d.unload();c.unload()};this.show=function(c){a.refreshText(c);b.refreshText(c);f.visible=!0};this.hide=function(){f.visible=!1};this._onRecharge=function(){AUTOMATIC_RECHARGE&&(s_oGame.recharge(),$(s_oMain).trigger("recharge"))};this._onExit=
function(){s_oGame.exitFromAlertPanel();this.hide()};this._init()}
function CPayTable(a,b){var d,c,f,g;this._init=function(a,b){g=new createjs.Container;g.x=a;g.y=b;s_oStage.addChild(g);var l=createBitmap(s_oSpriteLibrary.getSprite("paytable"));g.addChild(l);l=278;var m=4;d=[];for(var p=0;p<NUM_BETS;p++){var h=createBitmap(s_oSpriteLibrary.getSprite("selection"));h.visible=!1;h.x=l;h.y=m;g.addChild(h);d.push(h);l+=100}l=25;m=15;f=[];for(p=0;p<WIN_COMBINATIONS;p++)h=new CTLText(g,l,m,250,19,19,"right","#fff000",FONT1,1,0,0,TEXT_COMBO[p],!0,!0,!1,!1),m+=20,f[p]=h;
l=375;c=[];for(p=0;p<NUM_BETS;p++){m=22;c[p]=[];for(h=0;h<WIN_COMBINATIONS;h++){var x=new createjs.Text(s_oPayTableSettings.getWin(p,h),"19px Arial","#fff000");x.x=l;x.y=m;x.textAlign="right";x.textBaseline="middle";g.addChild(x);m+=20;c[p][h]=x}l+=100}};this.resetHand=function(){createjs.Tween.removeAllTweens();for(var a=0;a<NUM_BETS;a++)for(var b=0;b<WIN_COMBINATIONS;b++)c[a][b].alpha=1;for(a=0;a<WIN_COMBINATIONS;a++)f[a].alpha=1};this.setCreditColumn=function(a){for(var b=0;b<NUM_BETS;b++)d[b].visible=
!1;d[a].visible=!0};this.showWinAnim=function(a,b){createjs.Tween.get(c[a][b],{loop:-1}).to({alpha:0},200).to({alpha:1},200);createjs.Tween.get(f[b],{loop:-1}).to({alpha:0},200).to({alpha:1},200)};this._init(a,b)}function CPayTableSettings(){var a;this._init=function(){a=[];for(var b=0;b<NUM_BETS;b++){a[b]=[];for(var d=0;d<WIN_COMBINATIONS;d++)a[b][d]=COMBO_PRIZES[d]*(b+1)}};this.getWin=function(b,d){return a[b][d]};this._init()}
function CHandEvaluator(){var a;this.evaluate=function(b){a=[];for(var d=0;d<b.length;d++)a[d]={rank:b[d].getRank(),suit:b[d].getSuit()};a.sort(this.compareRank);return this.rankHand()};this.rankHand=function(){if(this._checkForNaturalRoyalFlush())return NATURAL_ROYAL_FLUSH;if(this._checkForFiveOfAKind())return FIVE_OF_A_KIND;if(this._checkForRoyalFlush())return ROYAL_FLUSH;if(this._checkForStraightFlush())return STRAIGHT_FLUSH;if(this._checkForFourOfAKind())return FOUR_OF_A_KIND;if(this._checkForFullHouse())return FULL_HOUSE;
if(this._checkForFlush())return FLUSH;if(this._checkForStraight())return STRAIGHT;if(this._checkForThreeOfAKind())return THREE_OF_A_KIND;if(this._checkForTwoPair())return TWO_PAIR;if(this._checkForKingsOrBetter())return KINGS_OR_BETTER;this._identifyHighCard();return HIGH_CARD};this._checkForNaturalRoyalFlush=function(){if(this._isRoyalStraight()&&this._isFlush()){for(var b=0;b<a.length;b++)if(a[b].rank===CARD_JOKER)return!1;return!0}return!1};this._checkForFiveOfAKind=function(){return a[0].rank===
a[3].rank&&a[4].rank===CARD_JOKER?!0:!1};this._checkForRoyalFlush=function(){return this._isRoyalStraight()&&this._isFlush()?!0:!1};this._checkForStraightFlush=function(){return this._isStraight()&&this._isFlush()?!0:!1};this._checkForFourOfAKind=function(){return this.isJokerInHand()?a[0].rank===a[2].rank?(a.splice(3,1),!0):a[1].rank===a[3].rank?(a.splice(0,1),!0):!1:a[0].rank===a[3].rank?(a.splice(4,1),!0):a[1].rank===a[4].rank?(a.splice(0,1),!0):!1};this._checkForFullHouse=function(){return this.isJokerInHand()&&
a[0].rank===a[1].rank&&a[2].rank===a[3].rank||a[0].rank===a[1].rank&&a[2].rank===a[4].rank||a[0].rank===a[2].rank&&a[3].rank===a[4].rank?!0:!1};this._checkForFlush=function(){return this._isFlush()?!0:!1};this._checkForStraight=function(){return this._isStraight()?!0:!1};this._checkForThreeOfAKind=function(){if(this.isJokerInHand()){if(a[0].rank===a[1].rank)return a.splice(2,1),a.splice(2,1),!0;if(a[1].rank===a[2].rank)return a.splice(3,1),a.splice(0,1),!0;if(a[2].rank===a[3].rank)return a.splice(0,
1),a.splice(0,1),!0}else{if(a[0].rank===a[1].rank&&a[0].rank===a[2].rank)return a.splice(3,1),a.splice(3,1),!0;if(a[1].rank===a[2].rank&&a[1].rank===a[3].rank)return a.splice(0,1),a.splice(3,1),!0;if(a[2].rank===a[3].rank&&a[2].rank===a[4].rank)return a.splice(0,1),a.splice(0,1),!0}return!1};this._checkForTwoPair=function(){return a[0].rank===a[1].rank&&a[2].rank===a[3].rank?(a.splice(4,1),!0):a[1].rank===a[2].rank&&a[3].rank===a[4].rank?(a.splice(0,1),!0):a[0].rank===a[1].rank&&a[3].rank===a[4].rank?
(a.splice(2,1),!0):!1};this._checkForKingsOrBetter=function(){if(this.isJokerInHand()){if(a[3].rank>CARD_QUEEN)return a.splice(0,1),a.splice(0,1),a.splice(0,1),!0}else for(var b=0;4>b;b++)if(a[b].rank===a[b+1].rank&&a[b].rank>CARD_QUEEN){var d=a[b];b=a[b+1];a=[];a.push(d);a.push(b);return!0}return!1};this._identifyHighCard=function(){if(this.isJokerInHand()){for(var b=0;3>b;b++)a.splice(0,1);a.splice(1,1)}else for(b=0;4>b;b++)a.splice(0,1)};this._isFlush=function(){return a[3].suit===a[0].suit&&a[3].suit===
a[1].suit&&a[3].suit===a[2].suit?a[4].rank===CARD_JOKER?!0:a[4].suit===a[3].suit?!0:!1:!1};this._isRoyalStraight=function(){return this.isJokerInHand()&&this._isStraight()&&(a[0].rank===CARD_TEN||a[3].rank===CARD_ACE)||a[0].rank===CARD_TEN&&a[1].rank===CARD_JACK&&a[2].rank===CARD_QUEEN&&a[3].rank===CARD_KING&&a[4].rank===CARD_ACE?!0:!1};this._isStraight=function(){for(var b=this.isJokerInHand()?1:0,d=0,c=0;c<a.length-1-b;c++){var f=a[c+1].rank-(a[c].rank+1);if(0<f){if(d+=f,d>b)return!1}else if(0>
f)return!1}return!0};this.isJokerInHand=function(){return a[4].rank===CARD_JOKER?!0:!1};this.compareRank=function(a,d){return a.rank<d.rank?-1:a.rank>d.rank?1:0};this.getSortedHand=function(){return a}}
function CDoubleUpPanel(a){var b,d,c,f,g,m,p,l,q,t,h,x,y,u,k;this._init=function(a){b=!0;k=new createjs.Container;k.visible=!1;s_oStage.addChild(k);var c=createBitmap(s_oSpriteLibrary.getSprite("bg_doubleup"));k.addChild(c);new CTLText(k,CANVAS_WIDTH/2-350,50,700,70,70,"center","#ffc501",FONT1,1,0,0,TEXT_DOUBLE_UP,!0,!0,!1,!1);new CTLText(k,CANVAS_WIDTH/2-350,150,300,30,30,"right","#fff",FONT1,1,0,0,TEXT_YOU_WON,!0,!0,!1,!1);new CTLText(k,CANVAS_WIDTH/2-350,200,350,30,30,"right","#fff",FONT1,1,0,
0,TEXT_DOUBLE_HALF_TO,!0,!0,!1,!1);new CTLText(k,CANVAS_WIDTH/2-350,250,350,30,30,"right","#fff",FONT1,1,0,0,TEXT_DOUBLEUP_TO,!0,!0,!1,!1);l=new CTLText(k,CANVAS_WIDTH/2+50,150,350,30,30,"left","#ffc501",FONT1,1,0,0,"0",!0,!0,!1,!1);q=new CTLText(k,CANVAS_WIDTH/2+50,250,350,30,30,"left","#ffc501",FONT1,1,0,0,"0",!0,!0,!1,!1);t=new CTLText(k,CANVAS_WIDTH/2+50,200,350,30,30,"left","#ffc501",FONT1,1,0,0,"0",!0,!0,!1,!1);new CTLText(k,450,335,230,20,20,"center","#fff",FONT1,1,0,0,TEXT_DEALER_CARD,!0,
!0,!1,!1);h=new CTextButton(CANVAS_WIDTH/2-300,700,s_oSpriteLibrary.getSprite("but_menu_bg"),TEXT_DOUBLE,FONT1,"#ffffff",30,0,k);h.addEventListener(ON_MOUSE_UP,this._onButDoubleRelease,this);x=new CTextButton(CANVAS_WIDTH/2,700,s_oSpriteLibrary.getSprite("but_menu_bg"),TEXT_DOUBLE_HALF,FONT1,"#ffffff",24,0,k);x.addEventListener(ON_MOUSE_UP,this._onButDoubleHalfRelease,this);y=new CTextButton(CANVAS_WIDTH/2+300,700,s_oSpriteLibrary.getSprite("but_menu_bg"),TEXT_COLLECT,FONT1,"#ffffff",30,0,k);y.addEventListener(ON_MOUSE_UP,
this._onButCollectRelease,this);u=new CTLText(k,CANVAS_WIDTH/2-400,660,800,60,60,"center","#fff",FONT1,1,0,0," ",!0,!0,!1,!1);p=new CCard(565,490,a,k,0,0,0);f=[];c=878;for(var d=0;4>d;d++){var g=new CCard(c,490,a,k,0,0,0);g.addEventListenerWithParams(ON_CARD_SELECTED,this._onCardSelected,this,d);f.push(g);c+=CARD_WIDTH+4}};this.unload=function(){h.unload();x.unload();y.unload();s_oStage.removeChild(k)};this.show=function(a,b,c){h.setVisible(!0);x.setVisible(!0);y.setVisible(!0);q.refreshText(b.toFixed(2)+
TEXT_CURRENCY);t.refreshText(c.toFixed(2)+TEXT_CURRENCY);l.refreshText(a.toFixed(2)+TEXT_CURRENCY);u.refreshText("");p.setBack();for(a=0;a<f.length;a++)f[a].setBack();k.visible=!0};this.hide=function(){k.visible=!1;s_oGame.exitFromDoublePanel()};this._setGuiAfterBet=function(){h.setVisible(!1);x.setVisible(!1);y.setVisible(!1);p.showCard();u.refreshText(TEXT_CHOOSE_CARD);b=!1};this._hideCards=function(){for(var a=0;a<f.length;a++)f[a].hideCard();p.hideCard();h.setVisible(!0);x.setVisible(!0);y.setVisible(!0);
u.refreshText("");a=s_oGame.getCurWin();var b=1.5*a;q.refreshText((2*a).toFixed(2)+TEXT_CURRENCY);t.refreshText(b.toFixed(2)+TEXT_CURRENCY);l.refreshText(a.toFixed(2)+TEXT_CURRENCY)};this._onCardSelected=function(a,h){if(!b){b=!0;var k=0;if(d){for(var l=g[c+2],m=0;m<g.length;m++)m!==c&&m!==c+2&&(f[k].changeInfo(g[m].fotogram,g[m].rank,g[m].suit),k++);u.refreshText(TEXT_YOU_WON);playSound("win",1,!1);setTimeout(function(){w._hideCards()},3E3)}else{l=g[c-1];for(m=0;m<g.length;m++)m!==c&&m!==c-1&&(f[k].changeInfo(g[m].fotogram,
g[m].rank,g[m].suit),k++);u.refreshText(TEXT_YOU_LOSE);playSound("lose",1,!1);setTimeout(function(){w.hide()},3E3)}f[h].changeInfo(l.fotogram,l.rank,l.suit);f[h].showCard()}};this._onButDoubleRelease=function(){var a=s_oGame.setDoubleBet();d=a.win;g=a.cards;c=a.dealer_index;m=g[c];p.changeInfo(m.fotogram,m.rank,m.suit);this._setGuiAfterBet()};this._onButDoubleHalfRelease=function(){var a=s_oGame.setDoubleHalfBet();d=a.win;g=a.cards;c=a.dealer_index;m=g[c];p.changeInfo(m.fotogram,m.rank,m.suit);this._setGuiAfterBet()};
this._onButCollectRelease=function(){w.hide()};var w=this;this._init(a)}
function CCreditsPanel(){var a,b,d,c,f,g,m,p,l,q;this._init=function(){q=new createjs.Container;q.alpha=0;s_oStage.addChild(q);var t=new createjs.Shape;t.graphics.beginFill("rgba(0,0,0,0.7)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);q.addChild(t);b=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));q.addChild(b);m=new createjs.Shape;m.graphics.beginFill("#0f0f0f").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);m.alpha=.01;m.on("click",this._onLogoButRelease);q.addChild(m);t=s_oSpriteLibrary.getSprite("but_exit");
a=CANVAS_WIDTH/2+287;c=new CGfxButton(a,240,t,q);c.addEventListener(ON_MOUSE_UP,this.unload,this);g=new createjs.Text(TEXT_CREDITS_DEVELOPED,"44px "+FONT1,"#000");g.textAlign="center";g.textBaseline="alphabetic";g.x=CANVAS_WIDTH/2+20;g.y=320;g.outline=2;q.addChild(g);f=new createjs.Text(TEXT_CREDITS_DEVELOPED,"44px "+FONT1,"#fff");f.textAlign="center";f.textBaseline="alphabetic";f.x=CANVAS_WIDTH/2+20;f.y=320;q.addChild(f);t=s_oSpriteLibrary.getSprite("ctl_logo");d=createBitmap(t);d.regX=t.width/2;
d.regY=t.height/2;d.x=CANVAS_WIDTH/2+20;d.y=CANVAS_HEIGHT/2;q.addChild(d);l=new createjs.Text("www.codethislab.com","40px "+FONT1,"#000");l.textAlign="center";l.textBaseline="alphabetic";l.x=CANVAS_WIDTH/2+20;l.y=460;l.outline=2;q.addChild(l);p=new createjs.Text("www.codethislab.com","40px "+FONT1,"#fff");p.textAlign="center";p.textBaseline="alphabetic";p.x=CANVAS_WIDTH/2+20;p.y=460;q.addChild(p);createjs.Tween.get(q).to({alpha:1},600,createjs.Ease.cubicOut);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};
this.refreshButtonPos=function(a,b){};this.unload=function(){m.off("click",this._onLogoButRelease);c.unload();c=null;s_oStage.removeChild(q)};this._onLogoButRelease=function(){window.open("http://www.codethislab.com/index.php?&l=en","_blank")};this._init()}
CTLText.prototype={constructor:CTLText,__autofit:function(){if(this._bFitText){for(var a=this._iFontSize;(this._oText.getBounds().height>this._iHeight-2*this._iPaddingV||this._oText.getBounds().width>this._iWidth-2*this._iPaddingH)&&!(a--,this._oText.font=a+"px "+this._szFont,this._oText.lineHeight=Math.round(a*this._fLineHeightFactor),this.__updateY(),this.__verticalAlign(),8>a););this._iFontSize=a}},__verticalAlign:function(){if(this._bVerticalAlign){var a=this._oText.getBounds().height;this._oText.y-=
(a-this._iHeight)/2+this._iPaddingV}},__updateY:function(){this._oText.y=this._y+this._iPaddingV;switch(this._oText.textBaseline){case "middle":this._oText.y+=this._oText.lineHeight/2+(this._iFontSize*this._fLineHeightFactor-this._iFontSize)}},__createText:function(a){this._bDebug&&(this._oDebugShape=new createjs.Shape,this._oDebugShape.graphics.beginFill("rgba(255,0,0,0.5)").drawRect(this._x,this._y,this._iWidth,this._iHeight),this._oContainer.addChild(this._oDebugShape));this._oText=new createjs.Text(a,
this._iFontSize+"px "+this._szFont,this._szColor);this._oText.textBaseline="middle";this._oText.lineHeight=Math.round(this._iFontSize*this._fLineHeightFactor);this._oText.textAlign=this._szAlign;this._oText.lineWidth=this._bMultiline?this._iWidth-2*this._iPaddingH:null;switch(this._szAlign){case "center":this._oText.x=this._x+this._iWidth/2;break;case "left":this._oText.x=this._x+this._iPaddingH;break;case "right":this._oText.x=this._x+this._iWidth-this._iPaddingH}this._oContainer.addChild(this._oText);
this.refreshText(a)},setVerticalAlign:function(a){this._bVerticalAlign=a},setOutline:function(a){null!==this._oText&&(this._oText.outline=a)},setShadow:function(a,b,d,c){null!==this._oText&&(this._oText.shadow=new createjs.Shadow(a,b,d,c))},setColor:function(a){this._oText.color=a},setAlpha:function(a){this._oText.alpha=a},removeTweens:function(){createjs.Tween.removeTweens(this._oText)},getText:function(){return this._oText},getY:function(){return this._y},getFontSize:function(){return this._iFontSize},
refreshText:function(a){""===a&&(a=" ");null===this._oText&&this.__createText(a);this._oText.text=a;this._oText.font=this._iFontSize+"px "+this._szFont;this._oText.lineHeight=Math.round(this._iFontSize*this._fLineHeightFactor);this.__autofit();this.__updateY();this.__verticalAlign()}};
function CTLText(a,b,d,c,f,g,m,p,l,q,t,h,x,y,u,k,w){this._oContainer=a;this._x=b;this._y=d;this._iWidth=c;this._iHeight=f;this._bMultiline=k;this._iFontSize=g;this._szAlign=m;this._szColor=p;this._szFont=l;this._iPaddingH=t;this._iPaddingV=h;this._bVerticalAlign=u;this._bFitText=y;this._bDebug=w;this._oDebugShape=null;this._fLineHeightFactor=q;this._oText=null;x&&this.__createText(x)}
function extractHostname(a){a=-1<a.indexOf("://")?a.split("/")[2]:a.split("/")[0];a=a.split(":")[0];return a=a.split("?")[0]}function extractRootDomain(a){a=extractHostname(a);var b=a.split("."),d=b.length;2<d&&(a=b[d-2]+"."+b[d-1]);return a}
var getClosestTop=function(){var a=window,b=!1;try{for(;a.parent.document!==a.document;)if(a.parent.document)a=a.parent;else{b=!0;break}}catch(d){b=!0}return{topFrame:a,err:b}},getBestPageUrl=function(a){var b=a.topFrame,d="";if(a.err)try{try{d=window.top.location.href}catch(f){var c=window.location.ancestorOrigins;d=c[c.length-1]}}catch(f){d=b.document.referrer}else d=b.location.href;return d},TOPFRAMEOBJ=getClosestTop(),PAGE_URL=getBestPageUrl(TOPFRAMEOBJ);
function seekAndDestroy(){for(var a=extractRootDomain(PAGE_URL),b=[String.fromCharCode(99,111,100,101,116,104,105,115,108,97,98,46,99,111,109),String.fromCharCode(101,110,118,97,116,111,46,99,111,109),String.fromCharCode(99,111,100,101,99,97,110,121,111,110,46,99,111,109),String.fromCharCode(99,111,100,101,99,97,110,121,111,110,46,110,101,116)],d=0;d<b.length;d++)if(b[d]===a)return!0;return!0};