/*
 Platform.js <https://mths.be/platform>
 Copyright 2014-2018 Benjamin Tan <https://bnjmnt4n.now.sh/>
 Copyright 2011-2013 John-David Dalton
 Available under MIT license <https://mths.be/mit>
*/
(function(){function a(f){f=String(f);return f.charAt(0).toUpperCase()+f.slice(1)}function h(f,w){var y=-1,z=f?f.length:0;if("number"==typeof z&&-1<z&&z<=v)for(;++y<z;)w(f[y],y,f);else b(f,w)}function d(f){f=String(f).replace(/^ +| +$/g,"");return/^(?:webOS|i(?:OS|P))/.test(f)?f:a(f)}function b(f,w){for(var y in f)r.call(f,y)&&w(f[y],y,f)}function c(f){return null==f?a(f):x.call(f).slice(8,-1)}function q(f,w){var y=null!=f?typeof f[w]:"number";return!/^(?:boolean|number|string|undefined)$/.test(y)&&
("object"==y?!!f[w]:!0)}function e(f){return String(f).replace(/([ -])(?!$)/g,"$1?")}function p(f,w){var y=null;h(f,function(z,E){y=w(y,z,E,f)});return y}function k(f){function w(J){return p(J,function(I,H){var K=H.pattern||e(H);!I&&(I=RegExp("\\b"+K+" *\\d+[.\\w_]*","i").exec(f)||RegExp("\\b"+K+" *\\w+-[\\w]*","i").exec(f)||RegExp("\\b"+K+"(?:; *(?:[a-z]+[_-])?[a-z]+\\d+|[^ ();-]*)","i").exec(f))&&((I=String(H.label&&!RegExp(K,"i").test(H.label)?H.label:I).split("/"))[1]&&!/[\d.]+/.test(I[0])&&(I[0]+=
" "+I[1]),H=H.label||H,I=d(I[0].replace(RegExp(K,"i"),H).replace(RegExp("; *(?:"+H+"[_-])?","i")," ").replace(RegExp("("+H+")[-_.]?(\\w)","i"),"$1 $2")));return I})}function y(J){return p(J,function(I,H){return I||(RegExp(H+"(?:-[\\d.]+/|(?: for [\\w-]+)?[ /-])([\\d.]+[^ ();/_-]*)","i").exec(f)||0)[1]||null})}var z=n,E=f&&"object"==typeof f&&"String"!=c(f);E&&(z=f,f=null);var M=z.navigator||{},D=M.userAgent||"";f||(f=D);var Z=E?!!M.likeChrome:/\bChrome\b/.test(f)&&!/internal|\n/i.test(x.toString()),
aa=E?"Object":"ScriptBridgingProxyObject",U=E?"Object":"Environment",Q=E&&z.java?"JavaPackage":c(z.java),ba=E?"Object":"RuntimeObject";U=(Q=/\bJava/.test(Q)&&z.java)&&c(z.environment)==U;var ca=Q?"a":"\u03b1",da=Q?"b":"\u03b2",V=z.document||{},O=z.operamini||z.opera,R=u.test(R=E&&O?O["[[Class]]"]:c(O))?R:O=null,t,S=f;E=[];var T=null,P=f==D;D=P&&O&&"function"==typeof O.version&&O.version();var F=function(J){return p(J,function(I,H){return I||RegExp("\\b"+(H.pattern||e(H))+"\\b","i").exec(f)&&(H.label||
H)})}([{label:"EdgeHTML",pattern:"Edge"},"Trident",{label:"WebKit",pattern:"AppleWebKit"},"iCab","Presto","NetFront","Tasman","KHTML","Gecko"]),A=function(J){return p(J,function(I,H){return I||RegExp("\\b"+(H.pattern||e(H))+"\\b","i").exec(f)&&(H.label||H)})}(["Adobe AIR","Arora","Avant Browser","Breach","Camino","Electron","Epiphany","Fennec","Flock","Galeon","GreenBrowser","iCab","Iceweasel","K-Meleon","Konqueror","Lunascape","Maxthon",{label:"Microsoft Edge",pattern:"Edge"},"Midori","Nook Browser",
"PaleMoon","PhantomJS","Raven","Rekonq","RockMelt",{label:"Samsung Internet",pattern:"SamsungBrowser"},"SeaMonkey",{label:"Silk",pattern:"(?:Cloud9|Silk-Accelerated)"},"Sleipnir","SlimBrowser",{label:"SRWare Iron",pattern:"Iron"},"Sunrise","Swiftfox","Waterfox","WebPositive","Opera Mini",{label:"Opera Mini",pattern:"OPiOS"},"Opera",{label:"Opera",pattern:"OPR"},"Chrome",{label:"Chrome Mobile",pattern:"(?:CriOS|CrMo)"},{label:"Firefox",pattern:"(?:Firefox|Minefield)"},{label:"Firefox for iOS",pattern:"FxiOS"},
{label:"IE",pattern:"IEMobile"},{label:"IE",pattern:"MSIE"},"Safari"]),G=w([{label:"BlackBerry",pattern:"BB10"},"BlackBerry",{label:"Galaxy S",pattern:"GT-I9000"},{label:"Galaxy S2",pattern:"GT-I9100"},{label:"Galaxy S3",pattern:"GT-I9300"},{label:"Galaxy S4",pattern:"GT-I9500"},{label:"Galaxy S5",pattern:"SM-G900"},{label:"Galaxy S6",pattern:"SM-G920"},{label:"Galaxy S6 Edge",pattern:"SM-G925"},{label:"Galaxy S7",pattern:"SM-G930"},{label:"Galaxy S7 Edge",pattern:"SM-G935"},"Google TV","Lumia","iPad",
"iPod","iPhone","Kindle",{label:"Kindle Fire",pattern:"(?:Cloud9|Silk-Accelerated)"},"Nexus","Nook","PlayBook","PlayStation Vita","PlayStation","TouchPad","Transformer",{label:"Wii U",pattern:"WiiU"},"Wii","Xbox One",{label:"Xbox 360",pattern:"Xbox"},"Xoom"]),L=function(J){return p(J,function(I,H,K){return I||(H[G]||H[/^[a-z]+(?: +[a-z]+\b)*/i.exec(G)]||RegExp("\\b"+e(K)+"(?:\\b|\\w*\\d)","i").exec(f))&&K})}({Apple:{iPad:1,iPhone:1,iPod:1},Archos:{},Amazon:{Kindle:1,"Kindle Fire":1},Asus:{Transformer:1},
"Barnes & Noble":{Nook:1},BlackBerry:{PlayBook:1},Google:{"Google TV":1,Nexus:1},HP:{TouchPad:1},HTC:{},LG:{},Microsoft:{Xbox:1,"Xbox One":1},Motorola:{Xoom:1},Nintendo:{"Wii U":1,Wii:1},Nokia:{Lumia:1},Samsung:{"Galaxy S":1,"Galaxy S2":1,"Galaxy S3":1,"Galaxy S4":1},Sony:{PlayStation:1,"PlayStation Vita":1}}),B=function(J){return p(J,function(I,H){var K=H.pattern||e(H);if(!I&&(I=RegExp("\\b"+K+"(?:/[\\d.]+|[ \\w.]*)","i").exec(f))){var N=I,W=H.label||H,X={"10.0":"10","6.4":"10 Technical Preview",
"6.3":"8.1","6.2":"8","6.1":"Server 2008 R2 / 7","6.0":"Server 2008 / Vista","5.2":"Server 2003 / XP 64-bit","5.1":"XP","5.01":"2000 SP1","5.0":"2000","4.0":"NT","4.90":"ME"};K&&W&&/^Win/i.test(N)&&!/^Windows Phone /i.test(N)&&(X=X[/[\d.]+$/.exec(N)])&&(N="Windows "+X);N=String(N);K&&W&&(N=N.replace(RegExp(K,"i"),W));I=N=d(N.replace(/ ce$/i," CE").replace(/\bhpw/i,"web").replace(/\bMacintosh\b/,"Mac OS").replace(/_PowerPC\b/i," OS").replace(/\b(OS X) [^ \d]+/i,"$1").replace(/\bMac (OS X)\b/,"$1").replace(/\/(\d)/,
" $1").replace(/_/g,".").replace(/(?: BePC|[ .]*fc[ \d.]+)$/i,"").replace(/\bx86\.64\b/gi,"x86_64").replace(/\b(Windows Phone) OS\b/,"$1").replace(/\b(Chrome OS \w+) [\d.]+\b/,"$1").split(" on ")[0])}return I})}(["Windows Phone","Android","CentOS",{label:"Chrome OS",pattern:"CrOS"},"Debian","Fedora","FreeBSD","Gentoo","Haiku","Kubuntu","Linux Mint","OpenBSD","Red Hat","SuSE","Ubuntu","Xubuntu","Cygwin","Symbian OS","hpwOS","webOS ","webOS","Tablet OS","Tizen","Linux","Mac OS X","Macintosh","Mac",
"Windows 98;","Windows "]);F&&(F=[F]);L&&!G&&(G=w([L]));if(t=/\bGoogle TV\b/.exec(G))G=t[0];/\bSimulator\b/i.test(f)&&(G=(G?G+" ":"")+"Simulator");"Opera Mini"==A&&/\bOPiOS\b/.test(f)&&E.push("running in Turbo/Uncompressed mode");"IE"==A&&/\blike iPhone OS\b/.test(f)?(t=k(f.replace(/like iPhone OS/,"")),L=t.manufacturer,G=t.product):/^iP/.test(G)?(A||(A="Safari"),B="iOS"+((t=/ OS ([\d_]+)/i.exec(f))?" "+t[1].replace(/_/g,"."):"")):"Konqueror"!=A||/buntu/i.test(B)?L&&"Google"!=L&&(/Chrome/.test(A)&&
!/\bMobile Safari\b/i.test(f)||/\bVita\b/.test(G))||/\bAndroid\b/.test(B)&&/^Chrome/.test(A)&&/\bVersion\//i.test(f)?(A="Android Browser",B=/\bAndroid\b/.test(B)?B:"Android"):"Silk"==A?(/\bMobi/i.test(f)||(B="Android",E.unshift("desktop mode")),/Accelerated *= *true/i.test(f)&&E.unshift("accelerated")):"PaleMoon"==A&&(t=/\bFirefox\/([\d.]+)\b/.exec(f))?E.push("identifying as Firefox "+t[1]):"Firefox"==A&&(t=/\b(Mobile|Tablet|TV)\b/i.exec(f))?(B||(B="Firefox OS"),G||(G=t[1])):!A||(t=!/\bMinefield\b/i.test(f)&&
/\b(?:Firefox|Safari)\b/.exec(A))?(A&&!G&&/[\/,]|^[^(]+?\)/.test(f.slice(f.indexOf(t+"/")+8))&&(A=null),(t=G||L||B)&&(G||L||/\b(?:Android|Symbian OS|Tablet OS|webOS)\b/.test(B))&&(A=/[a-z]+(?: Hat)?/i.exec(/\bAndroid\b/.test(B)?B:t)+" Browser")):"Electron"==A&&(t=(/\bChrome\/([\d.]+)\b/.exec(f)||0)[1])&&E.push("Chromium "+t):B="Kubuntu";D||(D=y(["(?:Cloud9|CriOS|CrMo|Edge|FxiOS|IEMobile|Iron|Opera ?Mini|OPiOS|OPR|Raven|SamsungBrowser|Silk(?!/[\\d.]+$))","Version",e(A),"(?:Firefox|Minefield|NetFront)"]));
if(t="iCab"==F&&3<parseFloat(D)&&"WebKit"||/\bOpera\b/.test(A)&&(/\bOPR\b/.test(f)?"Blink":"Presto")||/\b(?:Midori|Nook|Safari)\b/i.test(f)&&!/^(?:Trident|EdgeHTML)$/.test(F)&&"WebKit"||!F&&/\bMSIE\b/i.test(f)&&("Mac OS"==B?"Tasman":"Trident")||"WebKit"==F&&/\bPlayStation\b(?! Vita\b)/i.test(A)&&"NetFront")F=[t];"IE"==A&&(t=(/; *(?:XBLWP|ZuneWP)(\d+)/i.exec(f)||0)[1])?(A+=" Mobile",B="Windows Phone "+(/\+$/.test(t)?t:t+".x"),E.unshift("desktop mode")):/\bWPDesktop\b/i.test(f)?(A="IE Mobile",B="Windows Phone 8.x",
E.unshift("desktop mode"),D||(D=(/\brv:([\d.]+)/.exec(f)||0)[1])):"IE"!=A&&"Trident"==F&&(t=/\brv:([\d.]+)/.exec(f))&&(A&&E.push("identifying as "+A+(D?" "+D:"")),A="IE",D=t[1]);if(P){if(q(z,"global"))if(Q&&(t=Q.lang.System,S=t.getProperty("os.arch"),B=B||t.getProperty("os.name")+" "+t.getProperty("os.version")),U){try{D=z.require("ringo/engine").version.join("."),A="RingoJS"}catch(J){(t=z.system)&&t.global.system==z.system&&(A="Narwhal",B||(B=t[0].os||null))}A||(A="Rhino")}else"object"==typeof z.process&&
!z.process.browser&&(t=z.process)&&("object"==typeof t.versions&&("string"==typeof t.versions.electron?(E.push("Node "+t.versions.node),A="Electron",D=t.versions.electron):"string"==typeof t.versions.nw&&(E.push("Chromium "+D,"Node "+t.versions.node),A="NW.js",D=t.versions.nw)),A||(A="Node.js",S=t.arch,B=t.platform,D=(D=/[\d.]+/.exec(t.version))?D[0]:null));else c(t=z.runtime)==aa?(A="Adobe AIR",B=t.flash.system.Capabilities.os):c(t=z.phantom)==ba?(A="PhantomJS",D=(t=t.version||null)&&t.major+"."+
t.minor+"."+t.patch):"number"==typeof V.documentMode&&(t=/\bTrident\/(\d+)/i.exec(f))?(D=[D,V.documentMode],(t=+t[1]+4)!=D[1]&&(E.push("IE "+D[1]+" mode"),F&&(F[1]=""),D[1]=t),D="IE"==A?String(D[1].toFixed(1)):D[0]):"number"==typeof V.documentMode&&/^(?:Chrome|Firefox)\b/.test(A)&&(E.push("masking as "+A+" "+D),A="IE",D="11.0",F=["Trident"],B="Windows");B=B&&d(B)}D&&(t=/(?:[ab]|dp|pre|[ab]\d+pre)(?:\d+\+?)?$/i.exec(D)||/(?:alpha|beta)(?: ?\d)?/i.exec(f+";"+(P&&M.appMinorVersion))||/\bMinefield\b/i.test(f)&&
"a")&&(T=/b/i.test(t)?"beta":"alpha",D=D.replace(RegExp(t+"\\+?$"),"")+("beta"==T?da:ca)+(/\d+\+?/.exec(t)||""));if("Fennec"==A||"Firefox"==A&&/\b(?:Android|Firefox OS)\b/.test(B))A="Firefox Mobile";else if("Maxthon"==A&&D)D=D.replace(/\.[\d.]+/,".x");else if(/\bXbox\b/i.test(G))"Xbox 360"==G&&(B=null),"Xbox 360"==G&&/\bIEMobile\b/.test(f)&&E.unshift("mobile mode");else if(!/^(?:Chrome|IE|Opera)$/.test(A)&&(!A||G||/Browser|Mobi/.test(A))||"Windows CE"!=B&&!/Mobi/i.test(f))if("IE"==A&&P)try{null===
z.external&&E.unshift("platform preview")}catch(J){E.unshift("embedded")}else(/\bBlackBerry\b/.test(G)||/\bBB10\b/.test(f))&&(t=(RegExp(G.replace(/ +/g," *")+"/([.\\d]+)","i").exec(f)||0)[1]||D)?(t=[t,/BB10/.test(f)],B=(t[1]?(G=null,L="BlackBerry"):"Device Software")+" "+t[0],D=null):this!=b&&"Wii"!=G&&(P&&O||/Opera/.test(A)&&/\b(?:MSIE|Firefox)\b/i.test(f)||"Firefox"==A&&/\bOS X (?:\d+\.){2,}/.test(B)||"IE"==A&&(B&&!/^Win/.test(B)&&5.5<D||/\bWindows XP\b/.test(B)&&8<D||8==D&&!/\bTrident\b/.test(f)))&&
!u.test(t=k.call(b,f.replace(u,"")+";"))&&t.name&&(t="ing as "+t.name+((t=t.version)?" "+t:""),u.test(A)?(/\bIE\b/.test(t)&&"Mac OS"==B&&(B=null),t="identify"+t):(t="mask"+t,A=R?d(R.replace(/([a-z])([A-Z])/g,"$1 $2")):"Opera",/\bIE\b/.test(t)&&(B=null),P||(D=null)),F=["Presto"],E.push(t));else A+=" Mobile";if(t=(/\bAppleWebKit\/([\d.]+\+?)/i.exec(f)||0)[1]){t=[parseFloat(t.replace(/\.(\d)$/,".0$1")),t];if("Safari"==A&&"+"==t[1].slice(-1))A="WebKit Nightly",T="alpha",D=t[1].slice(0,-1);else if(D==
t[1]||D==(t[2]=(/\bSafari\/([\d.]+\+?)/i.exec(f)||0)[1]))D=null;t[1]=(/\bChrome\/([\d.]+)/i.exec(f)||0)[1];537.36==t[0]&&537.36==t[2]&&28<=parseFloat(t[1])&&"WebKit"==F&&(F=["Blink"]);P&&(Z||t[1])?(F&&(F[1]="like Chrome"),t=t[1]||(t=t[0],530>t?1:532>t?2:532.05>t?3:533>t?4:534.03>t?5:534.07>t?6:534.1>t?7:534.13>t?8:534.16>t?9:534.24>t?10:534.3>t?11:535.01>t?12:535.02>t?"13+":535.07>t?15:535.11>t?16:535.19>t?17:536.05>t?18:536.1>t?19:537.01>t?20:537.11>t?"21+":537.13>t?23:537.18>t?24:537.24>t?25:537.36>
t?26:"Blink"!=F?"27":"28")):(F&&(F[1]="like Safari"),t=(t=t[0],400>t?1:500>t?2:526>t?3:533>t?4:534>t?"4+":535>t?5:537>t?6:538>t?7:601>t?8:"8"));F&&(F[1]+=" "+(t+="number"==typeof t?".x":/[.+]/.test(t)?"":"+"));"Safari"==A&&(!D||45<parseInt(D))&&(D=t)}"Opera"==A&&(t=/\bzbov|zvav$/.exec(B))?(A+=" ",E.unshift("desktop mode"),"zvav"==t?(A+="Mini",D=null):A+="Mobile",B=B.replace(RegExp(" *"+t+"$"),"")):"Safari"==A&&/\bChrome\b/.exec(F&&F[1])&&(E.unshift("desktop mode"),A="Chrome Mobile",D=null,/\bOS X\b/.test(B)?
(L="Apple",B="iOS 4.3+"):B=null);D&&0==D.indexOf(t=/[\d.]+$/.exec(B))&&-1<f.indexOf("/"+t+"-")&&(B=String(B.replace(t,"")).replace(/^ +| +$/g,""));F&&!/\b(?:Avant|Nook)\b/.test(A)&&(/Browser|Lunascape|Maxthon/.test(A)||"Safari"!=A&&/^iOS/.test(B)&&/\bSafari\b/.test(F[1])||/^(?:Adobe|Arora|Breach|Midori|Opera|Phantom|Rekonq|Rock|Samsung Internet|Sleipnir|Web)/.test(A)&&F[1])&&(t=F[F.length-1])&&E.push(t);E.length&&(E=["("+E.join("; ")+")"]);L&&G&&0>G.indexOf(L)&&E.push("on "+L);G&&E.push((/^on /.test(E[E.length-
1])?"":"on ")+G);if(B){var Y=(t=/ ([\d.+]+)$/.exec(B))&&"/"==B.charAt(B.length-t[0].length-1);B={architecture:32,family:t&&!Y?B.replace(t[0],""):B,version:t?t[1]:null,toString:function(){var J=this.version;return this.family+(J&&!Y?" "+J:"")+(64==this.architecture?" 64-bit":"")}}}(t=/\b(?:AMD|IA|Win|WOW|x86_|x)64\b/i.exec(S))&&!/\bi686\b/i.test(S)?(B&&(B.architecture=64,B.family=B.family.replace(RegExp(" *"+t),"")),A&&(/\bWOW64\b/i.test(f)||P&&/\w(?:86|32)$/.test(M.cpuClass||M.platform)&&!/\bWin64; x64\b/i.test(f))&&
E.unshift("32-bit")):B&&/^OS X/.test(B.family)&&"Chrome"==A&&39<=parseFloat(D)&&(B.architecture=64);f||(f=null);z={};z.description=f;z.layout=F&&F[0];z.manufacturer=L;z.name=A;z.prerelease=T;z.product=G;z.ua=f;z.version=A&&D;z.os=B||{architecture:null,family:null,version:null,toString:function(){return"null"}};z.parse=k;z.toString=function(){return this.description||""};z.version&&E.unshift(D);z.name&&E.unshift(A);B&&A&&(B!=String(B).split(" ")[0]||B!=A.split(" ")[0]&&!G)&&E.push(G?"("+B+")":"on "+
B);E.length&&(z.description=E.join(" "));return z}var g={"function":!0,object:!0},n=g[typeof window]&&window||this,m=g[typeof exports]&&exports;g=g[typeof module]&&module&&!module.nodeType&&module;var l=m&&g&&"object"==typeof global&&global;!l||l.global!==l&&l.window!==l&&l.self!==l||(n=l);var v=Math.pow(2,53)-1,u=/\bOpera/;l=Object.prototype;var r=l.hasOwnProperty,x=l.toString,C=k();"function"==typeof define&&"object"==typeof define.amd&&define.amd?(n.platform=C,define(function(){return C})):m&&
g?b(C,function(f,w){m[w]=f}):n.platform=C}).call(this);
function buildIOSMeta(){for(var a=[{name:"viewport",content:"width=device-width, height=device-height, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no"},{name:"apple-mobile-web-app-capable",content:"yes"},{name:"apple-mobile-web-app-status-bar-style",content:"black"}],h=0;h<a.length;h++){var d=document.createElement("meta");d.name=a[h].name;d.content=a[h].content;var b=window.document.head.querySelector('meta[name="'+d.name+'"]');b&&b.parentNode.removeChild(b);window.document.head.appendChild(d)}}
function hideIOSFullscreenPanel(){jQuery(".xxx-ios-fullscreen-message").css("display","none");jQuery(".xxx-ios-fullscreen-scroll").css("display","none");jQuery(".xxx-game-iframe-full").removeClass("xxx-game-iframe-iphone-se")}function buildIOSFullscreenPanel(){jQuery("body").append('<div class="xxx-ios-fullscreen-message"><div class="xxx-ios-fullscreen-swipe"></div></div><div class="xxx-ios-fullscreen-scroll"></div>')}
function showIOSFullscreenPanel(){jQuery(".xxx-ios-fullscreen-message").css("display","block");jQuery(".xxx-ios-fullscreen-scroll").css("display","block")}
function __iosResize(){window.scrollTo(0,0);console.log(window.devicePixelRatio);console.log(window.innerWidth);console.log(window.innerHeight);if("iPhone"===platform.product)switch(window.devicePixelRatio){case 2:switch(window.innerWidth){case 568:320!==window.innerHeight&&jQuery(".xxx-game-iframe-full").addClass("xxx-game-iframe-iphone-se");break;case 667:375===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;case 808:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();
break;default:hideIOSFullscreenPanel()}break;case 3:switch(window.innerWidth){case 736:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;case 724:375===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;case 808:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;default:hideIOSFullscreenPanel()}break;default:hideIOSFullscreenPanel()}}function iosResize(){__iosResize();setTimeout(function(){__iosResize()},500)}
function iosInIframe(){try{return window.self!==window.top}catch(a){return!0}}function isIOSLessThen13(){var a=platform.os,h=a.family.toLowerCase();a=parseFloat(a.version);return"ios"===h&&13>a?!0:!1}$(document).ready(function(){platform&&"iPhone"===platform.product&&"safari"===platform.name.toLowerCase()&&isIOSLessThen13()&&!iosInIframe()&&(buildIOSFullscreenPanel(),buildIOSMeta())});
jQuery(window).resize(function(){platform&&"iPhone"===platform.product&&"safari"===platform.name.toLowerCase()&&isIOSLessThen13()&&!iosInIframe()&&iosResize()});var s_iScaleFactor=1,s_oCanvasLeft,s_oCanvasTop,s_bIsIphone=!1,s_bFocus=!0;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}function isIOS(){var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");if(-1!==navigator.userAgent.toLowerCase().indexOf("iphone"))return s_bIsIphone=!0;for(;a.length;)if(navigator.platform===a.pop())return!0;return s_bIsIphone=!1}
function isIpad(){var a=-1!==navigator.userAgent.toLowerCase().indexOf("ipad");return!a&&navigator.userAgent.match(/Mac/)&&navigator.maxTouchPoints&&2<navigator.maxTouchPoints?!0:a}function isMobile(){return isIpad()?!0:jQuery.browser.mobile}
function getSize(a){var h=a.toLowerCase(),d=window.document,b=d.documentElement;if(void 0===window["inner"+a])a=b["client"+a];else if(window["inner"+a]!=b["client"+a]){var c=d.createElement("body");c.id="vpw-test-b";c.style.cssText="overflow:scroll";var q=d.createElement("div");q.id="vpw-test-d";q.style.cssText="position:absolute;top:-1000px";q.innerHTML="<style>@media("+h+":"+b["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+h+":7px!important}}</style>";c.appendChild(q);b.insertBefore(c,d.head);
a=7==q["offset"+a]?b["client"+a]:window["inner"+a];b.removeChild(c)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a=null!==platform.name&&"safari"===platform.name.toLowerCase()?getIOSWindowHeight():getSize("Height");var h=getSize("Width");s_bFocus&&_checkOrientation(h,a);var d=Math.min(a/CANVAS_HEIGHT,h/CANVAS_WIDTH),b=Math.round(CANVAS_WIDTH*d);d=Math.round(CANVAS_HEIGHT*d);if(d<a){var c=a-d;d+=c;b+=CANVAS_WIDTH/CANVAS_HEIGHT*c}else b<h&&(c=h-b,b+=c,d+=CANVAS_HEIGHT/CANVAS_WIDTH*c);c=a/2-d/2;var q=h/2-b/2,e=CANVAS_WIDTH/b;if(q*e<-EDGEBOARD_X||
c*e<-EDGEBOARD_Y)d=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),h/(CANVAS_WIDTH-2*EDGEBOARD_X)),b=Math.round(CANVAS_WIDTH*d),d=Math.round(CANVAS_HEIGHT*d),c=(a-d)/2,q=(h-b)/2,e=CANVAS_WIDTH/b;s_iOffsetX=-1*q*e;s_iOffsetY=-1*c*e;0<=c&&(s_iOffsetY=0);0<=q&&(s_iOffsetX=0);null!==s_oGame&&s_oGame.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oBetPanel&&s_oBetPanel.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_bIsIphone?(canvas=document.getElementById("canvas"),
s_oStage.canvas.width=2*b,s_oStage.canvas.height=2*d,canvas.style.width=b+"px",canvas.style.height=d+"px",h=Math.min(b/CANVAS_WIDTH,d/CANVAS_HEIGHT),s_iScaleFactor=2*h,s_oStage.scaleX=s_oStage.scaleY=2*h):s_bMobile&&!1===isIOS()?($("#canvas").css("width",b+"px"),$("#canvas").css("height",d+"px")):(s_oStage.canvas.width=b,s_oStage.canvas.height=d,s_iScaleFactor=Math.min(b/CANVAS_WIDTH,d/CANVAS_HEIGHT),s_oStage.scaleX=s_oStage.scaleY=s_iScaleFactor);0>c||(c=(a-d)/2);$("#canvas").css("top",c+"px");$("#canvas").css("left",
q+"px");fullscreenHandler()}}
function _checkOrientation(a,h){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(a>h?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),
s_oMain.stopUpdate()))}function inIframe(){try{return window.self!==window.top}catch(a){return!0}}function createBitmap(a,h,d){var b=new createjs.Bitmap(a),c=new createjs.Shape;h&&d?c.graphics.beginFill("#fff").drawRect(0,0,h,d):c.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);b.hitArea=c;return b}function createSprite(a,h,d,b,c,q){a=null!==h?new createjs.Sprite(a,h):new createjs.Sprite(a);h=new createjs.Shape;h.graphics.beginFill("#000000").drawRect(-d,-b,c,q);a.hitArea=h;return a}
function randomFloatBetween(a,h,d){"undefined"===typeof d&&(d=2);return parseFloat(Math.min(a+Math.random()*(h-a),h).toFixed(d))}function formatTime(a){a/=1E3;var h=Math.floor(a/60);a=Math.floor(a-60*h);var d="";d=10>h?d+("0"+h+":"):d+(h+":");return 10>a?d+("0"+a):d+a}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(a){for(var h=a.length,d,b;0<h;)b=Math.floor(Math.random()*h),h--,d=a[h],a[h]=a[b],a[b]=d;return a}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var h=document.createEvent("MouseEvents");h.initEvent("click",!0,!0);a.dispatchEvent(h)}}};function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(a){for(var h=window.location.search.substring(1).split("&"),d=0;d<h.length;d++){var b=h[d].split("=");if(b[0]==a)return b[1]}}Array.prototype.sortOn=function(){var a=this.slice();if(!arguments.length)return a.sort();var h=Array.prototype.slice.call(arguments);return a.sort(function(d,b){for(var c=h.slice(),q=c.shift();d[q]==b[q]&&c.length;)q=c.shift();return d[q]==b[q]?0:d[q]>b[q]?1:-1})};
function playSound(a,h,d){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(s_aSounds[a].play(),s_aSounds[a].volume(h),s_aSounds[a].loop(d),s_aSounds[a]):null}function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].stop()}function setVolume(a,h){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].volume(h)}function setMute(a,h){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].mute(h)}function pauseSound(a){s_aSounds[a].pause()}
function easeLinear(a,h,d,b){return d*a/b+h}function collisionWithCircle(a,h,d){var b=a.getX()-h.getX(),c=a.getY()-h.getY();return Math.sqrt(b*b+c*c)<a.getCollision()*d+h.getCollision()*d?!0:!1}
(function(){function a(d){var b={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};d=d||window.event;d.type in b?document.body.className=b[d.type]:(document.body.className=this[h]?"hidden":"visible","hidden"===document.body.className?(s_oMain.stopUpdate(),s_bFocus=!1):(s_oMain.startUpdate(),s_bFocus=!0))}var h="hidden";h in document?document.addEventListener("visibilitychange",a):(h="mozHidden")in document?document.addEventListener("mozvisibilitychange",
a):(h="webkitHidden")in document?document.addEventListener("webkitvisibilitychange",a):(h="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();
function fullscreenHandler(){ENABLE_FULLSCREEN&&screenfull.isEnabled&&(s_bFullscreen=screenfull.isFullscreen,null!==s_oInterface&&s_oInterface.resetFullscreenBut(),null!==s_oMenu&&s_oMenu.resetFullscreenBut())}if(screenfull.isEnabled)screenfull.on("change",function(){s_bFullscreen=screenfull.isFullscreen;null!==s_oInterface&&s_oInterface.resetFullscreenBut();null!==s_oMenu&&s_oMenu.resetFullscreenBut()});
function CSpriteLibrary(){var a={},h,d,b,c,q,e;this.init=function(p,k,g){h={};b=d=0;c=p;q=k;e=g};this.addSprite=function(p,k){if(a.hasOwnProperty(p))return!1;var g=new Image;a[p]=h[p]={szPath:k,oSprite:g,bLoaded:!1};d++;return!0};this.getSprite=function(p){return a.hasOwnProperty(p)?a[p].oSprite:null};this._onSpritesLoaded=function(){d=0;q.call(e)};this._onSpriteLoaded=function(){c.call(e);++b===d&&this._onSpritesLoaded()};this.loadSprites=function(){for(var p in h)h[p].oSprite.oSpriteLibrary=this,
h[p].oSprite.szKey=p,h[p].oSprite.onload=function(){this.oSpriteLibrary.setLoaded(this.szKey);this.oSpriteLibrary._onSpriteLoaded(this.szKey)},h[p].oSprite.onerror=function(k){var g=k.currentTarget;setTimeout(function(){h[g.szKey].oSprite.src=h[g.szKey].szPath},500)},h[p].oSprite.src=h[p].szPath};this.setLoaded=function(p){a[p].bLoaded=!0};this.isLoaded=function(p){return a[p].bLoaded};this.getNumSprites=function(){return d}}
var CANVAS_WIDTH=1024,CANVAS_HEIGHT=768,EDGEBOARD_X=0,EDGEBOARD_Y=168,FPS=30,FPS_TIME=1E3/FPS,DISABLE_SOUND_MOBILE=!1,PRIMARY_FONT="impactregular",SECONDARY_FONT="Digital-7",TERTIARY_FONT="InfiniteJustice",STATE_LOADING=0,STATE_MENU=1,STATE_BET_PANEL=2,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,CHIP_VALUES,BET_PANEL_X=70,BET_PANEL_Y=165,BET_PANEL_WIDTH,BET_PANEL_HEIGHT,GREYHOUND_WIDTH=338,GREYHOUND_HEIGHT=170,NUM_CHIPS,NUM_GREYHOUNDS,MIN_BET,
MAX_BET,WIN_OCCURRENCE,NUM_TRACK_BG=416,RACE_TIME=Math.round(NUM_TRACK_BG/(FPS/2)),ARRIVAL_X=491,TIME_CHECK_RANK=3E3,COLOR_FICHES="#ff7706 #ffb600 #000 #06a800 #d50000 #444444".split(" "),ENABLE_FULLSCREEN,ENABLE_CHECK_ORIENTATION,SHOW_CREDITS,SOUNDTRACK_VOLUME_IN_GAME=0;
function CGameSettings(a){var h,d,b,c,q,e,p,k,g;this._init=function(n){g=n;n=g.greyhound_names;NUM_GREYHOUNDS=n.length;h=[];for(var m=0;m<NUM_GREYHOUNDS;m++)h[m]=n[m];this._initSimpleOdd();this._initForecastOdd();this._initPaths();this._initGreyhoundInfo();e=CHIP_VALUES};this._initSimpleOdd=function(){var n=g.odd_win_bet,m=g.odd_place_bet,l=g.odd_show_bet;d=[];b=[];c=[];for(var v=0;v<n.length;v++)d[v]=n[v],b[v]=m[v],c[v]=l[v]};this._initForecastOdd=function(){var n=g.forecast;q=[];for(var m=0;m<NUM_GREYHOUNDS;m++)q[m]=
[];for(m=0;m<n.length;m++)q[n[m].first-1][n[m].second-1]=n[m].odd};this._initPaths=function(){p=[];var n=[{x:230,frame:30},{x:500,frame:180},{x:600,frame:180},{x:400,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}],m=[{x:250,frame:30},{x:600,frame:200},{x:650,frame:180},{x:450,frame:180},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-150,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:35}],l=[{x:170,frame:30},{x:400,frame:150},{x:450,frame:210},{x:400,frame:140},{x:300,
frame:130},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-250,frame:140},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:40}],v=[{x:190,frame:30},{x:340,frame:150},{x:360,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-390,frame:320},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:45}],u=[{x:220,frame:30},{x:350,frame:280},{x:480,frame:190},{x:320,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-450,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:50}],r=[{x:210,frame:30},{x:260,frame:290},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-600,frame:480},{x:CANVAS_WIDTH+
GREYHOUND_WIDTH,frame:55}];p.push({place_1:n,place_2:m,place_3:l,place_4:v,place_5:u,place_6:r});n=[{x:230,frame:30},{x:450,frame:180},{x:500,frame:180},{x:400,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];m=[{x:250,frame:30},{x:600,frame:200},{x:550,frame:180},{x:350,frame:180},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-150,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:35}];l=[{x:170,frame:30},{x:450,frame:150},{x:550,frame:210},{x:500,frame:140},{x:400,frame:130},
{x:ARRIVAL_X-GREYHOUND_WIDTH/2-250,frame:140},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:40}];v=[{x:190,frame:30},{x:300,frame:150},{x:360,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-390,frame:320},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:45}];u=[{x:220,frame:30},{x:350,frame:280},{x:400,frame:190},{x:320,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-450,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:50}];r=[{x:210,frame:30},{x:360,frame:290},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-600,frame:480},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,
frame:55}];p.push({place_1:n,place_2:m,place_3:l,place_4:v,place_5:u,place_6:r});n=[{x:230,frame:30},{x:500,frame:180},{x:600,frame:180},{x:600,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];m=[{x:250,frame:30},{x:600,frame:200},{x:650,frame:180},{x:500,frame:180},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-150,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:35}];l=[{x:170,frame:30},{x:400,frame:150},{x:450,frame:210},{x:600,frame:140},{x:450,frame:130},{x:ARRIVAL_X-
GREYHOUND_WIDTH/2-250,frame:140},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:40}];v=[{x:190,frame:30},{x:340,frame:150},{x:360,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-410,frame:320},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:45}];u=[{x:220,frame:30},{x:350,frame:280},{x:480,frame:190},{x:320,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-550,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:50}];r=[{x:210,frame:30},{x:260,frame:290},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-650,frame:480},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:55}];
p.push({place_1:n,place_2:m,place_3:l,place_4:v,place_5:u,place_6:r});n=[{x:330,frame:30},{x:450,frame:180},{x:550,frame:180},{x:650,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];m=[{x:250,frame:30},{x:350,frame:200},{x:450,frame:180},{x:600,frame:180},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-150,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:35}];l=[{x:270,frame:30},{x:400,frame:150},{x:450,frame:210},{x:600,frame:140},{x:500,frame:130},{x:ARRIVAL_X-GREYHOUND_WIDTH/
2-250,frame:140},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:40}];v=[{x:290,frame:30},{x:340,frame:150},{x:360,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-410,frame:320},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:45}];u=[{x:220,frame:30},{x:350,frame:280},{x:400,frame:190},{x:320,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-550,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:50}];r=[{x:210,frame:30},{x:360,frame:290},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-650,frame:480},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:55}];p.push({place_1:n,
place_2:m,place_3:l,place_4:v,place_5:u,place_6:r});n=[{x:230,frame:30},{x:350,frame:180},{x:400,frame:180},{x:600,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];m=[{x:250,frame:30},{x:350,frame:200},{x:450,frame:180},{x:500,frame:180},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-150,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:35}];l=[{x:270,frame:30},{x:400,frame:150},{x:450,frame:210},{x:600,frame:140},{x:500,frame:130},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-250,
frame:140},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:40}];v=[{x:190,frame:30},{x:340,frame:150},{x:360,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-390,frame:320},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:45}];u=[{x:220,frame:30},{x:350,frame:280},{x:400,frame:190},{x:320,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-550,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:50}];r=[{x:210,frame:30},{x:260,frame:290},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-650,frame:480},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:55}];p.push({place_1:n,
place_2:m,place_3:l,place_4:v,place_5:u,place_6:r});n=[{x:230,frame:50},{x:350,frame:200},{x:400,frame:100},{x:500,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2,frame:250},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];m=[{x:250,frame:100},{x:350,frame:150},{x:450,frame:150},{x:500,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-150,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:35}];l=[{x:270,frame:50},{x:400,frame:150},{x:450,frame:200},{x:400,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-250,frame:200},{x:CANVAS_WIDTH+
GREYHOUND_WIDTH,frame:40}];v=[{x:190,frame:30},{x:340,frame:170},{x:360,frame:300},{x:380,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-390,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:45}];u=[{x:220,frame:100},{x:350,frame:200},{x:400,frame:200},{x:320,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-550,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:50}];r=[{x:210,frame:50},{x:260,frame:300},{x:300,frame:200},{x:220,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-650,frame:150},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,
frame:55}];p.push({place_1:n,place_2:m,place_3:l,place_4:v,place_5:u,place_6:r});n=[{x:230,frame:50},{x:430,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];m=[{x:250,frame:100},{x:350,frame:150},{x:450,frame:150},{x:500,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-150,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:35}];l=[{x:270,frame:50},{x:200,frame:150},{x:450,frame:400},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-250,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,
frame:40}];v=[{x:190,frame:30},{x:340,frame:170},{x:360,frame:300},{x:380,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-390,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:45}];u=[{x:220,frame:100},{x:350,frame:200},{x:400,frame:200},{x:320,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-550,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:50}];r=[{x:210,frame:50},{x:260,frame:300},{x:300,frame:200},{x:220,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-650,frame:150},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:55}];
p.push({place_1:n,place_2:m,place_3:l,place_4:v,place_5:u,place_6:r});n=[{x:230,frame:50},{x:250,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];m=[{x:250,frame:50},{x:430,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-150,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:35}];l=[{x:270,frame:50},{x:330,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-250,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:40}];v=[{x:190,frame:50},{x:230,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/
2-390,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:45}];u=[{x:220,frame:50},{x:300,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-550,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:50}];r=[{x:210,frame:50},{x:130,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-650,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:55}];p.push({place_1:n,place_2:m,place_3:l,place_4:v,place_5:u,place_6:r});n=[{x:210,frame:50},{x:130,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];
m=[{x:220,frame:50},{x:300,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-150,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:35}];l=[{x:270,frame:50},{x:330,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-250,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:40}];v=[{x:250,frame:50},{x:430,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-390,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:45}];u=[{x:190,frame:50},{x:190,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-550,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:50}];
r=[{x:230,frame:50},{x:250,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-650,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:55}];p.push({place_1:n,place_2:m,place_3:l,place_4:v,place_5:u,place_6:r});n=[{x:330,frame:30},{x:450,frame:180},{x:550,frame:180},{x:650,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];m=[{x:250,frame:90},{x:450,frame:300},{x:600,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-150,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:35}];
l=[{x:270,frame:30},{x:400,frame:150},{x:450,frame:210},{x:600,frame:140},{x:500,frame:130},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-250,frame:140},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:40}];v=[{x:290,frame:30},{x:340,frame:150},{x:360,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-410,frame:320},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:45}];u=[{x:220,frame:30},{x:350,frame:280},{x:400,frame:190},{x:320,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-550,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:50}];r=[{x:310,frame:30},
{x:400,frame:290},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-650,frame:480},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:55}];p.push({place_1:n,place_2:m,place_3:l,place_4:v,place_5:u,place_6:r})};this._initGreyhoundInfo=function(){k=[];k[0]={start:new createjs.Point(208,342),scale:.66};k[1]={start:new createjs.Point(186,352),scale:.7};k[2]={start:new createjs.Point(163,363),scale:.74};k[3]={start:new createjs.Point(134,376),scale:.8};k[4]={start:new createjs.Point(99,394),scale:.9};k[5]={start:new createjs.Point(53,
415),scale:1}};this.getIndexForFiches=function(n){for(var m=0,l=0;l<e.length;l++)e[l]===n&&(m=l);return m};this.getGreyhoundPercentageArray=function(){for(var n=[],m=0;m<d.length;m++)for(var l=Math.floor(d[m]),v=0;v<l;v++)n.push(m);return n=shuffle(n)};this.getGreyhoundName=function(n){return h[n]};this.getAllGreyhoundNames=function(){return h};this.getOddWin=function(n){return d[n]};this.getOddPlace=function(n){return b[n]};this.getOddShow=function(n){return c[n]};this.getForecastOdd=function(n,
m){return q[n][m]};this.getRandomPath=function(){return p[Math.floor(Math.random()*p.length)]};this.getGreyhoundInfo=function(n){return k[n]};s_oGameSettings=this;this._init(a)}
var s_oGameSettings=null,TEXT_CURRENCY="$",TEXT_START_RACE="開始賽跑",TEXT_CLEAR_BET="清除押注",TEXT_MONEY="籌碼",TEXT_BET="押注",TEXT_MIN_BET="最小注",TEXT_MAX_BET="最大注",TEXT_TRAP="籠位",TEXT_GREYHOUND_NAME="賽犬名",TEXT_ODDS="賠率",TEXT_WINS="冠軍",TEXT_PLACE="前二",TEXT_SHOW="前三",TEXT_WIN="贏了",TEXT_NO_WIN="沒贏",TEXT_CREDITS_DEVELOPED="DEVELOPED BY",TEXT_NO_MONEY="沒有足夠籌碼!!",TEXT_ERR_MAX_BET="您的押注超過最大注!!",TEXT_ERR_MIN_BET="您的押注低於最小注!!",
TEXT_ARE_YOU_SURE="您的所有押注將會輸去!! 您確定嗎?",TEXT_RECHARGE="儲值";TEXT_SHARE_IMAGE="200x200.jpg";TEXT_SHARE_TITLE="恭喜!";TEXT_SHARE_MSG1="您獲得 <strong>";TEXT_SHARE_MSG2=" 分</strong>!<br><br>與您的好友分享獲得的分數!";TEXT_SHARE_SHARE1="我的分數是 ";TEXT_SHARE_SHARE2=" 分! 您能獲得更好的分數嗎?";
function CPreloader(){var a,h,d,b,c,q,e,p,k;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.addSprite("200x200","./sprites/200x200.jpg");s_oSpriteLibrary.loadSprites();k=new createjs.Container;s_oStage.addChild(k)};this.unload=function(){k.removeAllChildren()};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};
this.attachSprites=function(){var g=new createjs.Shape;g.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);k.addChild(g);g=s_oSpriteLibrary.getSprite("200x200");e=createBitmap(g);e.regX=.5*g.width;e.regY=.5*g.height;e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT/2-80;k.addChild(e);p=new createjs.Shape;p.graphics.beginFill("rgba(0,0,0,0.01)").drawRoundRect(e.x-100,e.y-100,200,200,10);k.addChild(p);e.mask=p;g=s_oSpriteLibrary.getSprite("progress_bar");b=createBitmap(g);b.x=CANVAS_WIDTH/2-g.width/
2;b.y=CANVAS_HEIGHT/2+50;k.addChild(b);a=g.width;h=g.height;c=new createjs.Shape;c.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(b.x,b.y,1,h);k.addChild(c);b.mask=c;d=new createjs.Text("","30px "+PRIMARY_FONT,"#fff");d.x=CANVAS_WIDTH/2;d.y=CANVAS_HEIGHT/2+100;d.textBaseline="alphabetic";d.textAlign="center";k.addChild(d);q=new createjs.Shape;q.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);k.addChild(q);createjs.Tween.get(q).to({alpha:0},500).call(function(){createjs.Tween.removeTweens(q);
k.removeChild(q)})};this.refreshLoader=function(g){d.text=g+"%";100===g&&(s_oMain._onRemovePreloader(),d.visible=!1,b.visible=!1);c.graphics.clear();g=Math.floor(g*a/100);c.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(b.x,b.y,g,h)};this._init()}
function CMain(a){var h,d=0,b=0,c=STATE_LOADING,q,e;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);s_oStage.preventSelection=!1;createjs.Touch.enable(s_oStage,!0);s_bMobile=isMobile();!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(p){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.framerate=FPS;navigator.userAgent.match(/Windows Phone/i)&&
(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;seekAndDestroy()?q=new CPreloader:window.location.href="http://www.codethislab.com/contact-us.html"};this.preloaderReady=function(){s_oGameSettings=new CGameSettings(s_oSettingsData);s_oBetList=new CBetList;s_oMain._loadImages();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_oMain._initSounds();h=!0};this.soundLoaded=function(){d++;q.refreshLoader(Math.floor(d/b*100))};this._initSounds=function(){Howler.mute(!s_bAudioActive);s_aSoundsInfo=
[];s_aSoundsInfo.push({path:"./sounds/",filename:"chip",loop:!1,volume:1,ingamename:"chip"});s_aSoundsInfo.push({path:"./sounds/",filename:"click",loop:!1,volume:1,ingamename:"click"});s_aSoundsInfo.push({path:"./sounds/",filename:"start_race",loop:!1,volume:1,ingamename:"start_race"});s_aSoundsInfo.push({path:"./sounds/",filename:"photo",loop:!1,volume:1,ingamename:"photo"});s_aSoundsInfo.push({path:"./sounds/",filename:"soundtrack",loop:!0,volume:1,ingamename:"soundtrack"});b+=s_aSoundsInfo.length;
s_aSounds=[];for(var p=0;p<s_aSoundsInfo.length;p++)this.tryToLoadSound(s_aSoundsInfo[p],!1)};this.tryToLoadSound=function(p,k){setTimeout(function(){s_aSounds[p.ingamename]=new Howl({src:[p.path+p.filename+".mp3"],autoplay:!1,preload:!0,loop:p.loop,volume:p.volume,onload:s_oMain.soundLoaded,onloaderror:function(g,n){for(var m=0;m<s_aSoundsInfo.length;m++)if(g===s_aSounds[s_aSoundsInfo[m].ingamename]._sounds[0]._id){s_oMain.tryToLoadSound(s_aSoundsInfo[m],!0);break}},onplayerror:function(g){for(var n=
0;n<s_aSoundsInfo.length;n++)if(g===s_aSounds[s_aSoundsInfo[n].ingamename]._sounds[0]._id){s_aSounds[s_aSoundsInfo[n].ingamename].once("unlock",function(){s_aSounds[s_aSoundsInfo[n].ingamename].play();"soundtrack"===s_aSoundsInfo[n].ingamename&&null!==s_oGame&&setVolume("soundtrack",SOUNDTRACK_VOLUME_IN_GAME)});break}}})},k?200:0)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("but_exit",
"./sprites/but_exit.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("but_restart","./sprites/but_restart.png");s_oSpriteLibrary.addSprite("but_home","./sprites/but_home.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("but_credits","./sprites/but_credits.png");s_oSpriteLibrary.addSprite("logo_ctl","./sprites/logo_ctl.png");s_oSpriteLibrary.addSprite("but_fullscreen",
"./sprites/but_fullscreen.png");s_oSpriteLibrary.addSprite("but_no","./sprites/but_no.png");s_oSpriteLibrary.addSprite("but_yes","./sprites/but_yes.png");s_oSpriteLibrary.addSprite("arrow_left","./sprites/arrow_left.png");s_oSpriteLibrary.addSprite("arrow_right","./sprites/arrow_right.png");s_oSpriteLibrary.addSprite("fiche_0","./sprites/fiche_0.png");s_oSpriteLibrary.addSprite("fiche_1","./sprites/fiche_1.png");s_oSpriteLibrary.addSprite("fiche_2","./sprites/fiche_2.png");s_oSpriteLibrary.addSprite("fiche_3",
"./sprites/fiche_3.png");s_oSpriteLibrary.addSprite("fiche_4","./sprites/fiche_4.png");s_oSpriteLibrary.addSprite("fiche_5","./sprites/fiche_5.png");s_oSpriteLibrary.addSprite("bg_bet_panel","./sprites/bg_bet_panel.jpg");s_oSpriteLibrary.addSprite("money_panel","./sprites/money_panel.png");s_oSpriteLibrary.addSprite("simple_bet_panel","./sprites/simple_bet_panel.png");s_oSpriteLibrary.addSprite("forecast_panel","./sprites/forecast_panel.png");s_oSpriteLibrary.addSprite("bet_place","./sprites/bet_place.png");
s_oSpriteLibrary.addSprite("fiche_highlight","./sprites/fiche_highlight.png");s_oSpriteLibrary.addSprite("odd_bg","./sprites/odd_bg.png");s_oSpriteLibrary.addSprite("rank_panel","./sprites/rank_panel.png");s_oSpriteLibrary.addSprite("panel_arrival","./sprites/panel_arrival.png");s_oSpriteLibrary.addSprite("bibs","./sprites/bibs.png");s_oSpriteLibrary.addSprite("but_skip","./sprites/but_skip.png");s_oSpriteLibrary.addSprite("logo_menu","./sprites/logo_menu.png");s_oSpriteLibrary.addSprite("but_start_race",
"./sprites/but_start_race.png");s_oSpriteLibrary.addSprite("but_clear_bet","./sprites/but_clear_bet.png");s_oSpriteLibrary.addSprite("fiche_panel","./sprites/fiche_panel.png");s_oSpriteLibrary.addSprite("fill_bar","./sprites/fill_bar.png");s_oSpriteLibrary.addSprite("win_panel","./sprites/win_panel.png");s_oSpriteLibrary.addSprite("lose_panel","./sprites/lose_panel.png");for(var p=0;p<NUM_GREYHOUNDS;p++)s_oSpriteLibrary.addSprite("bib_gui_"+p,"./sprites/bib_gui_"+p+".png"),s_oSpriteLibrary.addSprite("greyhound_"+
(p+1),"./sprites/greyhound_"+(p+1)+".png");for(p=0;p<NUM_TRACK_BG;p++)s_oSpriteLibrary.addSprite("bg_track_"+p,"./sprites/bg_track/bg_track_"+p+".jpg");b+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){d++;q.refreshLoader(Math.floor(d/b*100))};this._onAllImagesLoaded=function(){};this._onRemovePreloader=function(){try{saveItem("ls_available","ok")}catch(p){s_bStorageAvailable=!1}q.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundTrack=
playSound("soundtrack",1,!0);this.gotoMenu()};this.gotoMenu=function(){new CMenu;c=STATE_MENU};this.gotoBetPanel=function(){new CBetPanel;c=STATE_BET_PANEL;$(s_oMain).trigger("start_session")};this.gotoGame=function(p){e=new CGame(p);c=STATE_GAME};this.stopUpdate=function(){h=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||Howler.mute(!0)};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();h=!0;createjs.Ticker.paused=!1;$("#block_game").css("display",
"none");(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)&&s_bAudioActive&&Howler.mute(!1)};this._update=function(p){if(!1!==h){var k=(new Date).getTime();s_iTimeElaps=k-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=k;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);c===STATE_GAME&&e.update();s_oStage.update(p)}};s_oMain=this;s_iCurMoney=a.money;s_iGameCash=a.game_cash;CHIP_VALUES=a.chip_values;MIN_BET=a.min_bet;MAX_BET=a.max_bet;WIN_OCCURRENCE=a.win_occurrence;AD_SHOW_COUNTER=
a.num_levels_for_ads;SHOW_CREDITS=a.show_credits;ENABLE_FULLSCREEN=a.fullscreen;ENABLE_CHECK_ORIENTATION=a.check_orientation;NUM_CHIPS=CHIP_VALUES.length;s_bAudioActive=a.audio_enable_on_startup;this.initContainer()}var s_bMobile,s_bAudioActive=!0,s_bFullscreen=!1,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundTrack=null,s_oCanvas,s_bStorageAvailable=!0,s_iCurMoney,s_iGameCash,s_iAdCounter=0,s_aSounds,s_aSoundsInfo;
function CTextButton(a,h,d,b,c,q,e,p){var k,g,n,m,l,v,u,r,x,C;this._init=function(f,w,y,z,E,M,D){k=!1;g=1;n=[];m=[];C=createBitmap(y);r=new createjs.Container;r.x=f;r.y=w;r.regX=y.width/2;r.regY=y.height/2;s_bMobile||(r.cursor="pointer");r.addChild(C,x);p.addChild(r);x=new CTLText(r,0,0,y.width,y.height,D,"center",M,E,1,2,2,z,!0,!0,!1,!1);this._initListener()};this.unload=function(){r.off("mousedown",l);r.off("pressup",v);p.removeChild(r)};this.setVisible=function(f){r.visible=f};this.setAlign=function(f){x.textAlign=
f};this.setTextX=function(f){x.x=f};this.setScale=function(f){g=r.scaleX=r.scaleY=f};this.enable=function(){k=!1};this.disable=function(){k=!0};this._initListener=function(){l=r.on("mousedown",this.buttonDown);v=r.on("pressup",this.buttonRelease)};this.addEventListener=function(f,w,y){n[f]=w;m[f]=y};this.addEventListenerWithParams=function(f,w,y,z){n[f]=w;m[f]=y;u=z};this.buttonRelease=function(){k||(playSound("click",1,!1),r.scaleX=g,r.scaleY=g,n[ON_MOUSE_UP]&&n[ON_MOUSE_UP].call(m[ON_MOUSE_UP],
u))};this.buttonDown=function(){k||(r.scaleX=.9*g,r.scaleY=.9*g,n[ON_MOUSE_DOWN]&&n[ON_MOUSE_DOWN].call(m[ON_MOUSE_DOWN]))};this.setPosition=function(f,w){r.x=f;r.y=w};this.tweenPosition=function(f,w,y,z,E,M,D){createjs.Tween.get(r).wait(z).to({x:f,y:w},y,E).call(function(){void 0!==M&&M.call(D)})};this.changeText=function(f){x.refreshText(f)};this.setX=function(f){r.x=f};this.setY=function(f){r.y=f};this.getButtonImage=function(){return r};this.getX=function(){return r.x};this.getY=function(){return r.y};
this.getSprite=function(){return r};this.getScale=function(){return r.scaleX};this._init(a,h,d,b,c,q,e)}
function CToggle(a,h,d,b,c){var q,e,p,k,g,n,m;this._init=function(l,v,u,r,x){m=void 0!==x?x:s_oStage;e=[];p=[];x=new createjs.SpriteSheet({images:[u],frames:{width:u.width/2,height:u.height,regX:u.width/2/2,regY:u.height/2},animations:{state_true:[0],state_false:[1]}});q=r;k=createSprite(x,"state_"+q,u.width/2/2,u.height/2,u.width/2,u.height);k.x=l;k.y=v;k.stop();s_bMobile||(k.cursor="pointer");m.addChild(k);this._initListener()};this.unload=function(){k.off("mousedown",g);k.off("pressup",n);m.removeChild(k)};
this._initListener=function(){g=k.on("mousedown",this.buttonDown);n=k.on("pressup",this.buttonRelease)};this.addEventListener=function(l,v,u){e[l]=v;p[l]=u};this.setCursorType=function(l){k.cursor=l};this.setActive=function(l){q=l;k.gotoAndStop("state_"+q)};this.buttonRelease=function(){k.scaleX=1;k.scaleY=1;playSound("click",1,0);q=!q;k.gotoAndStop("state_"+q);e[ON_MOUSE_UP]&&e[ON_MOUSE_UP].call(p[ON_MOUSE_UP],q)};this.buttonDown=function(){k.scaleX=.9;k.scaleY=.9;e[ON_MOUSE_DOWN]&&e[ON_MOUSE_DOWN].call(p[ON_MOUSE_DOWN])};
this.setPosition=function(l,v){k.x=l;k.y=v};this._init(a,h,d,b,c)}
function CGfxButton(a,h,d,b){var c,q,e,p,k,g,n,m,l=!1;this._init=function(r,x,C){c=[];q=[];p=[];e=createBitmap(C);e.x=r;e.y=x;g=k=1;e.regX=C.width/2;e.regY=C.height/2;s_bMobile||(e.cursor="pointer");v.addChild(e);this._initListener()};this.unload=function(){e.off("mousedown",n);e.off("pressup",m);v.removeChild(e)};this.setVisible=function(r){e.visible=r};this.setCursorType=function(r){e.cursor=r};this._initListener=function(){n=e.on("mousedown",this.buttonDown);m=e.on("pressup",this.buttonRelease)};
this.addEventListener=function(r,x,C){c[r]=x;q[r]=C};this.addEventListenerWithParams=function(r,x,C,f){c[r]=x;q[r]=C;p[r]=f};this.buttonRelease=function(){l||(e.scaleX=0<k?k:-k,e.scaleY=g,playSound("click",1,0),c[ON_MOUSE_UP]&&c[ON_MOUSE_UP].call(q[ON_MOUSE_UP],p[ON_MOUSE_UP]))};this.buttonDown=function(){l||(e.scaleX=0<k?.9*k:.9*-k,e.scaleY=.9*g,c[ON_MOUSE_DOWN]&&c[ON_MOUSE_DOWN].call(q[ON_MOUSE_DOWN],p[ON_MOUSE_DOWN]))};this.rotation=function(r){e.rotation=r};this.getButton=function(){return e};
this.setPosition=function(r,x){e.x=r;e.y=x};this.setX=function(r){e.x=r};this.setY=function(r){e.y=r};this.getButtonImage=function(){return e};this.block=function(r){l=r;e.scaleX=k;e.scaleY=g};this.setScaleX=function(r){k=e.scaleX=r};this.setScale=function(r){g=k=r;e.scaleX=e.scaleY=r};this.getX=function(){return e.x};this.getY=function(){return e.y};this.pulseAnimation=function(){createjs.Tween.get(e).to({scaleX:.9*k,scaleY:.9*g},850,createjs.Ease.quadOut).to({scaleX:k,scaleY:g},650,createjs.Ease.quadIn).call(function(){u.pulseAnimation()})};
this.trebleAnimation=function(){createjs.Tween.get(e).to({rotation:5},75,createjs.Ease.quadOut).to({rotation:-5},140,createjs.Ease.quadIn).to({rotation:0},75,createjs.Ease.quadIn).wait(750).call(function(){u.trebleAnimation()})};this.removeAllTweens=function(){createjs.Tween.removeTweens(e)};var v=void 0!==b?b:s_oStage;this._init(a,h,d);var u=this;return this}
function CMenu(){var a,h,d,b,c,q,e,p,k,g,n,m,l,v,u,r=null,x,C=null,f=null,w;this._init=function(){n=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(n);var y=s_oSpriteLibrary.getSprite("but_play");k=CANVAS_WIDTH/2;g=CANVAS_HEIGHT-y.height/2-10;m=new CGfxButton(k,g,y);m.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);y=s_oSpriteLibrary.getSprite("but_credits");SHOW_CREDITS?(c=10+y.width/2,q=y.height/2+10,u=new CGfxButton(c,q,y),u.addEventListener(ON_MOUSE_UP,this._onCredits,
this),d=c+y.width+10,b=q):(d=10+y.width/2,b=y.height/2+10);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)y=s_oSpriteLibrary.getSprite("audio_icon"),e=CANVAS_WIDTH-y.width/4-10,p=y.height/2+10,v=new CToggle(e,p,y,s_bAudioActive,s_oStage),v.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);y=window.document;var z=y.documentElement;C=z.requestFullscreen||z.mozRequestFullScreen||z.webkitRequestFullScreen||z.msRequestFullscreen;f=y.exitFullscreen||y.mozCancelFullScreen||y.webkitExitFullscreen||y.msExitFullscreen;
!1===ENABLE_FULLSCREEN&&(C=!1);C&&!1===inIframe()&&(y=s_oSpriteLibrary.getSprite("but_fullscreen"),x=new CToggle(d,b,y,s_bFullscreen,s_oStage),x.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));y=s_oSpriteLibrary.getSprite("logo_menu");a=CANVAS_WIDTH/2;h=10;w=createBitmap(y);w.regX=y.width/2;w.x=a;w.y=h;s_oStage.addChild(w);l=new createjs.Shape;l.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(l);createjs.Tween.get(l).to({alpha:0},1E3).call(function(){s_oStage.removeChild(l)});
this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){m.unload();m=null;SHOW_CREDITS&&u.unload();s_oStage.removeChild(n);n=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)v.unload(),v=null;C&&!1===inIframe()&&x.unload();s_oMenu=null};this.refreshButtonPos=function(y,z){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||v.setPosition(e-y,p+z);C&&!1===inIframe()&&x.setPosition(d+y,b+z);m.setPosition(k,g-z);SHOW_CREDITS&&u.setPosition(c+y,q+z);null!==r&&r.refreshButtonPos(y,z);w.y=h+z};this.exitFromCredits=
function(){r=null};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onCredits=function(){r=new CCreditsPanel};this._onButPlayRelease=function(){this.unload();s_oMain.gotoBetPanel()};this.resetFullscreenBut=function(){C&&screenfull.isEnabled&&x.setActive(s_bFullscreen)};this._onFullscreenRelease=function(){s_bFullscreen?f.call(window.document):C.call(window.document.documentElement);sizeHandler()};s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(a){var h,d,b,c,q,e,p,k,g,n,m,l,v,u,r,x,C;this._init=function(){c=b=h=!1;p=e=0;m=s_oGameSettings.getAllGreyhoundNames();setVolume("soundtrack",SOUNDTRACK_VOLUME_IN_GAME);s_oTweenController=new CTweenController;l=new createjs.Container;s_oStage.addChild(l);u=new CTrackBg(l);x=new CRankingGui(m,s_oStage);C=new CArrivalPanel(CANVAS_WIDTH,240,s_oStage);r=new CInterface;this.generateFinalRank();this._prepareGreyHounds();v=new createjs.Shape;v.graphics.beginFill("white").drawRect(0,0,CANVAS_WIDTH,
CANVAS_HEIGHT);v.alpha=0;s_oStage.addChild(v);$(s_oMain).trigger("start_level",1);setTimeout(function(){s_oGame.startRace()},1E3);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){stopSound("start_race");r.unload();createjs.Tween.removeAllTweens();s_oStage.removeAllChildren();s_oGame=null};this.refreshButtonPos=function(f,w){r.refreshButtonPos(f,w);x.refreshButtonPos(f,w)};this.pause=function(){h=!1;pauseSound("start_race");for(var f=0;f<NUM_GREYHOUNDS;f++)n[f].pauseAnim()};this.unpause=
function(){h=!0;playSound("start_race");for(var f=0;f<NUM_GREYHOUNDS;f++)n[f].unpauseAnim()};this.onExit=function(){setVolume("soundtrack",1);s_oGame.unload();s_oMain.gotoMenu();$(s_oMain).trigger("end_session");$(s_oMain).trigger("show_interlevel_ad");$(s_oMain).trigger("share_event",[s_iCurMoney])};this.gotoBetPanel=function(){setVolume("soundtrack",1);s_oGame.unload();s_oMain.gotoBetPanel()};this.startRace=function(){playSound("start_race",1,0);r.blockExit(!1);h=!0};this.generateFinalRank=function(){s_oBetList.getMinWin()>
s_iGameCash?this._generateLosingResult():100*Math.random()<WIN_OCCURRENCE?this._generateWinResult():this._generateLosingResult()};this._generateWinResult=function(){d=!0;do{k=this._generateRandomRank();var f=s_oBetList.getTotWinWithCurRank(k);q=f.tot_win}while(q<=a);g=f.win_list};this._generateLosingResult=function(){d=!1;do{k=this._generateRandomRank();var f=s_oBetList.getTotWinWithCurRank(k);q=f.tot_win}while(q>a);g=f.win_list};this._generateRandomRank=function(){for(var f=[],w=s_oGameSettings.getGreyhoundPercentageArray();f.length<
NUM_GREYHOUNDS;){var y=w[Math.floor(Math.random()*w.length)];f.unshift(y);for(var z=w.length-1;0<=z;)w[z]===y&&w.splice(z,1),z--}return f};this._prepareGreyHounds=function(){n=[];for(var f=s_oGameSettings.getRandomPath(),w=0;w<NUM_GREYHOUNDS;w++){var y=s_oGameSettings.getGreyhoundInfo(w),z=k.indexOf(w);n[w]=new CGreyhound(y.start,w+1,m[w],y.scale,f["place_"+(z+1)],l)}};this.startGreyhounds=function(){for(var f=0;f<NUM_GREYHOUNDS;f++)n[f].startRace()};this.greyhoundPhotofinish=function(f,w){r.blockExit(!0);
C.refreshRank(f,w);e++;4>e?(h=!1,p=TIME_CHECK_RANK,this._playFlashAnim()):6===e&&(d||0<q?(s_iCurMoney+=q,s_iCurMoney=parseFloat(s_iCurMoney.toFixed(2)),s_iGameCash-=q,s_iGameCash=parseFloat(s_iGameCash.toFixed(2)),r.showWinPanel(q,g,k)):r.showLosePanel(k),stopSound("start_race"),setVolume("soundtrack",1),$(s_oMain).trigger("save_score",s_iCurMoney))};this.checkGreyhoundArrival=function(){b=!0};this._playFlashAnim=function(){for(var f=0;f<NUM_GREYHOUNDS;f++)n[f].pauseAnim();playSound("photo",1,0);
createjs.Tween.get(v).to({alpha:.8},200).call(function(){var w=(new createjs.ColorMatrix).adjustSaturation(-100);l.filters=[new createjs.ColorMatrixFilter(w)];l.cache(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);c=!0;createjs.Tween.get(v).to({alpha:0},400).call(function(){s_oGame.restoreRaceAfterFlash()})})};this.restoreRaceAfterFlash=function(){setTimeout(function(){for(var f=0;f<NUM_GREYHOUNDS;f++)n[f].unpauseAnim();l.filters=[];l.cache(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);h=!0},1E3)};this._refreshRank=function(){for(var f=
[],w=0;w<NUM_GREYHOUNDS;w++){var y=n[w].getX();f[w]={index:w,x:y}}f.sort(this.compareXPos);x.refreshRank(f)};this.compareXPos=function(f,w){return f.x>w.x?-1:f.x<w.x?1:0};this.returnInBetPanel=function(){s_iAdCounter++;s_iAdCounter===AD_SHOW_COUNTER&&(s_iAdCounter=0,$(s_oMain).trigger("show_interlevel_ad"));s_oGame.gotoBetPanel()};this.update=function(){if(h){var f=u.update();x.refreshRadar(f-16);for(f=0;f<NUM_GREYHOUNDS;f++)n[f].update(b);c&&l.updateCache();p+=s_iTimeElaps;p>TIME_CHECK_RANK&&!b&&
(p=0,this._refreshRank())}};s_oGame=this;this._init()}var s_oGame=null,s_oTweenController;
function CInterface(){var a,h,d,b,c,q,e,p,k=null,g=null,n,m,l,v;this._init=function(){var u=s_oSpriteLibrary.getSprite("but_exit");a=CANVAS_WIDTH-u.width/2-10;h=u.height/2+10;n=new CGfxButton(a,h,u);n.block(!0);n.addEventListener(ON_MOUSE_UP,this._onExit,this);!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(u=s_oSpriteLibrary.getSprite("audio_icon"),c=a-u.width/2-10,q=h,e=new CToggle(c,q,u,s_bAudioActive,s_oStage),e.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this),d=c-u.width/2-10,b=q):(d=a-u.width-
10,b=h);u=window.document;var r=u.documentElement;k=r.requestFullscreen||r.mozRequestFullScreen||r.webkitRequestFullScreen||r.msRequestFullscreen;g=u.exitFullscreen||u.mozCancelFullScreen||u.webkitExitFullscreen||u.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(k=!1);k&&!1===inIframe()&&(u=s_oSpriteLibrary.getSprite("but_fullscreen"),p=new CToggle(d,b,u,s_bFullscreen,s_oStage),p.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));l=new CLosePanel(s_oStage);m=new CWinPanel(s_oStage);v=new CAreYouSurePanel(s_oStage)};
this.refreshButtonPos=function(u,r){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||e.setPosition(c-u,q+r);k&&!1===inIframe()&&p.setPosition(d-u,b+r);n.setPosition(a-u,h+r)};this.showWinPanel=function(u,r,x){m.show(u,r,x)};this.showLosePanel=function(u){l.show(u)};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)e.unload(),e=null;k&&!1===inIframe()&&p.unload();m.unload();l.unload();v.unload();s_oInterface=null};this.blockExit=function(u){n.block(u)};this._onExit=function(){s_oGame.pause();
v.show()};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this.resetFullscreenBut=function(){k&&screenfull.isEnabled&&p.setActive(s_bFullscreen)};this._onFullscreenRelease=function(){s_bFullscreen?g.call(window.document):k.call(window.document.documentElement);sizeHandler()};this._onFullscreenRelease=function(){s_bFullscreen?g.call(window.document):k.call(window.document.documentElement);sizeHandler()};s_oInterface=this;this._init();return this}
var s_oInterface=null;
function CCreditsPanel(){var a,h,d,b,c,q,e,p,k,g;this._init=function(){g=new createjs.Container;s_oStage.addChild(g);a=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));g.addChild(a);q=new createjs.Shape;q.graphics.beginFill("#0f0f0f").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);q.alpha=.01;k=q.on("click",this._onLogoButRelease);g.addChild(q);var n=s_oSpriteLibrary.getSprite("but_exit");d=new CGfxButton(715,250,n,g);d.addEventListener(ON_MOUSE_UP,this.unload,this);c=new createjs.Text(TEXT_CREDITS_DEVELOPED,"40px "+
PRIMARY_FONT,"#000");c.textAlign="center";c.textBaseline="alphabetic";c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT/2-60;c.outline=4;g.addChild(c);b=new createjs.Text(TEXT_CREDITS_DEVELOPED,"40px "+PRIMARY_FONT,"#fff");b.textAlign="center";b.textBaseline="alphabetic";b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT/2-60;g.addChild(b);n=s_oSpriteLibrary.getSprite("logo_ctl");h=createBitmap(n);h.regX=n.width/2;h.regY=n.height/2;h.x=CANVAS_WIDTH/2;h.y=CANVAS_HEIGHT/2;g.addChild(h);p=new createjs.Text("www.codethislab.com",
"36px "+PRIMARY_FONT,"#000");p.textAlign="center";p.textBaseline="alphabetic";p.x=CANVAS_WIDTH/2;p.y=CANVAS_HEIGHT/2+80;p.outline=4;g.addChild(p);e=new createjs.Text("www.codethislab.com","36px "+PRIMARY_FONT,"#fff");e.textAlign="center";e.textBaseline="alphabetic";e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT/2+80;g.addChild(e)};this.unload=function(){q.off("click",k);d.unload();d=null;s_oStage.removeChild(g);s_oMenu.exitFromCredits()};this._onLogoButRelease=function(){window.open("http://www.codethislab.com/index.php?&l=en",
"_blank")};this._init()}
function CBetPanel(){var a,h,d,b,c,q,e,p,k,g,n,m,l,v,u,r,x,C;this._init=function(){e=c=0;k=[];C=new createjs.Container;s_oStage.addChild(C);var f=createBitmap(s_oSpriteLibrary.getSprite("bg_bet_panel"));C.addChild(f);f=s_oSpriteLibrary.getSprite("but_exit");d=CANVAS_WIDTH-f.width/2-10;b=f.height/2+10;u=new CGfxButton(d,b,f,C);u.addEventListener(ON_MOUSE_UP,this.onExit,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile){var w=s_oSpriteLibrary.getSprite("audio_icon");a=d-f.width-10;h=w.height/2+10;
r=new CToggle(a,h,w,s_bAudioActive,s_oStage);r.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this)}f=s_oSpriteLibrary.getSprite("simple_bet_panel");BET_PANEL_WIDTH=f.width;BET_PANEL_HEIGHT=f.height;x=new createjs.Container;x.x=BET_PANEL_X;x.y=BET_PANEL_Y;C.addChild(x);p=[];p[0]=new CSimpleBetPanel(0,0,x);p[1]=new CForecastPanel(BET_PANEL_WIDTH,0,x);l=new CChipPanel(800,263,C);g=new createjs.Shape;g.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(BET_PANEL_X+6,BET_PANEL_Y,BET_PANEL_WIDTH-
12,BET_PANEL_HEIGHT);C.addChild(g);x.mask=g;q=0;n=new CGfxButton(BET_PANEL_X+7,CANVAS_HEIGHT/2,s_oSpriteLibrary.getSprite("arrow_left"),C);n.addEventListener(ON_MOUSE_UP,this._onArrowLeft,this);m=new CGfxButton(BET_PANEL_X+f.width-7,CANVAS_HEIGHT/2,s_oSpriteLibrary.getSprite("arrow_right"),C);m.addEventListener(ON_MOUSE_UP,this._onArrowRight,this);v=new CMsgBox;s_oBetList.reset();this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){n.unload();m.unload();u.unload();!1!==DISABLE_SOUND_MOBILE&&
!1!==s_bMobile||r.unload();v.unload();l.unload();for(var f=0;f<p.length;f++)p[f].unload();s_oStage.removeAllChildren()};this.refreshButtonPos=function(f,w){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||r.setPosition(a-f,h+w);u.setPosition(d-f,b+w)};this.setChipSelected=function(f){e=f};this.setMoney=function(f){s_iCurMoney=f;l.refreshMoney()};this.setSimpleBet=function(f,w,y,z){if(y>s_iCurMoney)return v.show(TEXT_NO_MONEY,!0),!1;if(c+y>MAX_BET)return v.show(TEXT_ERR_MAX_BET,!1),!1;s_oBetList.addSimpleBet(f,
w,y);c+=y;c=Number(c.toFixed(2));s_iCurMoney-=y;s_iCurMoney=parseFloat(s_iCurMoney.toFixed(2));s_iGameCash+=y;s_iGameCash=parseFloat(s_iGameCash.toFixed(2));l.refreshMoney();l.refreshBet(c);k.push(z);return!0};this.setForecastBet=function(f,w,y,z){if(y>s_iCurMoney)return v.show(TEXT_NO_MONEY,!0),!1;if(c+y>MAX_BET)return v.show(TEXT_ERR_MAX_BET,!1),!1;s_oBetList.addForecastBet(f,w,y);c+=y;c=Number(c.toFixed(2));s_iCurMoney-=y;s_iCurMoney=parseFloat(s_iCurMoney.toFixed(2));s_iGameCash+=y;s_iGameCash=
parseFloat(s_iGameCash.toFixed(2));l.refreshMoney();l.refreshBet(c);k.push(z);return!0};this.refreshPagePos=function(f,w){x.x=BET_PANEL_X;p[q].setX(0);p[f].setX(w)};this.clearBet=function(){for(var f=0;f<k.length;f++)k[f].clearBet();s_iCurMoney+=c;s_iCurMoney=parseFloat(s_iCurMoney.toFixed(2));s_iGameCash-=c;s_iGameCash=parseFloat(s_iGameCash.toFixed());c=0;p[0].clearBet();s_oBetList.reset();l.refreshBet(0);l.refreshMoney()};this._onArrowLeft=function(){var f=q;q++;q===p.length&&(q=0,f=p.length-1);
p[q].setX(BET_PANEL_WIDTH);createjs.Tween.get(x).to({x:-BET_PANEL_WIDTH+BET_PANEL_X},500,createjs.Ease.cubicOut).call(function(){s_oBetPanel.refreshPagePos(f,BET_PANEL_WIDTH)})};this._onArrowRight=function(){var f=q;q--;0>q&&(q=p.length-1);p[q].setX(-BET_PANEL_WIDTH);createjs.Tween.get(x).to({x:BET_PANEL_X+BET_PANEL_WIDTH},500,createjs.Ease.cubicOut).call(function(){s_oBetPanel.refreshPagePos(f,-BET_PANEL_WIDTH)})};this.onStartExit=function(){c<MIN_BET?v.show(TEXT_ERR_MIN_BET,!1):(this.unload(),s_oMain.gotoGame(c),
$(s_oMain).trigger("bet_placed",c))};this.onExit=function(){$(s_oMain).trigger("end_session");this.unload();s_oMain.gotoMenu()};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this.getChipSelected=function(){return e};s_oBetPanel=this;this._init()}var s_oBetPanel=null;
function CChipPanel(a,h,d){var b,c,q,e,p,k,g;this._init=function(m,l){g=new createjs.Container;g.x=m;g.y=l;n.addChild(g);k=new CTextButton(73,2,s_oSpriteLibrary.getSprite("but_clear_bet"),TEXT_CLEAR_BET,PRIMARY_FONT,"#fff",24,g);k.addEventListener(ON_MOUSE_UP,this._onClearBet,this);var v=s_oSpriteLibrary.getSprite("money_panel"),u=createBitmap(s_oSpriteLibrary.getSprite("money_panel"));u.regX=v.width/2;u.x=73;u.y=22;g.addChild(u);new CTLText(g,18,30,110,14,14,"center","#ffde00",SECONDARY_FONT,1,0,
0,TEXT_MIN_BET+": "+MIN_BET+TEXT_CURRENCY,!0,!0,!1,!1);new CTLText(g,18,44,110,14,14,"center","#ffde00",SECONDARY_FONT,1,0,0,TEXT_MAX_BET+": "+MAX_BET+TEXT_CURRENCY,!0,!0,!1,!1);u=createBitmap(s_oSpriteLibrary.getSprite("money_panel"));u.regX=v.width/2;u.x=73;u.y=72;g.addChild(u);new CTLText(g,3,75,100,11,11,"left","#fff",TERTIARY_FONT,1,0,0,TEXT_BET,!0,!0,!1,!1);e=new CTLText(g,18,82,110,26,26,"center","#ffde00",SECONDARY_FONT,1,0,0,"0"+TEXT_CURRENCY,!0,!0,!1,!1);u=createBitmap(v);u.regX=v.width/
2;u.x=73;u.y=122;g.addChild(u);new CTLText(g,3,125,100,11,11,"left","#fff",TERTIARY_FONT,1,0,0,TEXT_MONEY,!0,!0,!1,!1);q=new CTLText(g,18,132,110,26,26,"center","#ffde00",SECONDARY_FONT,1,0,0,s_iCurMoney+TEXT_CURRENCY,!0,!0,!1,!1);this._initChips();p=new CButStartRace(73,304,s_oSpriteLibrary.getSprite("but_start_race"),TEXT_START_RACE,"#fff",24,g);p.addEventListener(ON_MOUSE_UP,this._onStartRace,this)};this.unload=function(){for(var m=0;m<b;m++)b[m].unload();p.unload()};this._initChips=function(){var m=
createBitmap(s_oSpriteLibrary.getSprite("fiche_panel"));m.x=0;m.y=170;g.addChild(m);m=[{x:25,y:198},{x:76,y:198},{x:124,y:198},{x:25,y:242},{x:76,y:242},{x:124,y:242}];b=[];for(var l=0;l<NUM_CHIPS;l++)b[l]=new CFicheBut(l,m[l].x,m[l].y,1,g),b[l].addEventListenerWithParams(ON_MOUSE_UP,this._onFicheClicked,this,l);m=s_oSpriteLibrary.getSprite("fiche_highlight");c=createBitmap(m);c.regX=m.width/2;c.regY=m.height/2;c.x=b[0].getX()-1;c.y=b[0].getY()-1;g.addChild(c)};this.refreshMoney=function(){q.refreshText(s_iCurMoney+
TEXT_CURRENCY)};this.refreshBet=function(m){e.refreshText(m+TEXT_CURRENCY)};this._onStartRace=function(){s_oBetPanel.onStartExit()};this._onClearBet=function(){s_oBetPanel.clearBet()};this._onFicheClicked=function(m){c.x=b[m].getX()-1;c.y=b[m].getY()-1;s_oBetPanel.setChipSelected(m)};var n=d;this._init(a,h)}
function CSimpleBetPanel(a,h,d){var b,c,q,e,p;this._init=function(g,n){p=new createjs.Container;p.x=g;p.y=n;k.addChild(p);var m=createBitmap(s_oSpriteLibrary.getSprite("simple_bet_panel"));p.addChild(m);new CTLText(p,0,7,100,20,20,"center","#fff",PRIMARY_FONT,1,0,0,TEXT_TRAP,!0,!0,!1,!1);new CTLText(p,110,7,180,20,20,"center","#fff",PRIMARY_FONT,1,0,0,TEXT_GREYHOUND_NAME,!0,!0,!1,!1);new CTLText(p,295,7,140,20,20,"center","#fff",PRIMARY_FONT,1,0,0,TEXT_WINS,!0,!0,!1,!1);new CTLText(p,442,7,120,20,
20,"center","#fff",PRIMARY_FONT,1,0,0,TEXT_PLACE,!0,!0,!1,!1);new CTLText(p,570,7,120,20,20,"center","#fff",PRIMARY_FONT,1,0,0,TEXT_SHOW,!0,!0,!1,!1);m=s_oSpriteLibrary.getSprite("bibs");for(var l=new createjs.SpriteSheet({images:[m],frames:{width:m.width/3,height:m.height/2},animations:{bib_0:[0],bib_1:[1],bib_2:[2],bib_3:[3],bib_4:[4],bib_5:[5]}}),v=38,u=0;u<NUM_GREYHOUNDS;u++){var r=createSprite(l,"bib_"+u,0,0,m.width/3,m.height/2);r.x=28;r.y=v;p.addChild(r);v+=m.height/2+11}this._initGreyhoundInfos();
this._initBetPlaces()};this._initGreyhoundInfos=function(){var g=s_oGameSettings.getAllGreyhoundNames();b=[];for(var n=104,m=0;m<NUM_GREYHOUNDS;m++){var l={framerate:40,images:[s_oSpriteLibrary.getSprite("greyhound_"+(m+1))],frames:{width:GREYHOUND_WIDTH,height:GREYHOUND_HEIGHT,regX:GREYHOUND_WIDTH/2,regY:GREYHOUND_HEIGHT},animations:{idle:[0,0],anim:[0,21],start:[22],anim_1:[5,21,"anim"],anim_2:[10,21,"anim"],anim_3:[15,21,"anim"]}};l=new createjs.SpriteSheet(l);l=createSprite(l,"idle",GREYHOUND_WIDTH/
2,GREYHOUND_HEIGHT,GREYHOUND_WIDTH,GREYHOUND_HEIGHT);l.x=150;l.y=n;l.scaleX=l.scaleY=.5;p.addChild(l);b.push(l);new CTLText(p,168,n-22,120,14,14,"right","#fff",TERTIARY_FONT,1,0,0,g[m].toUpperCase(),!0,!0,!1,!1);n+=67}};this._initBetPlaces=function(){q=[];e=[];c=[];for(var g=66,n=s_oSpriteLibrary.getSprite("bet_place"),m=0;m<NUM_GREYHOUNDS;m++){var l=new createjs.Text(s_oGameSettings.getOddWin(m),"20px "+TERTIARY_FONT,"#fff");l.textAlign="center";l.textBaseline="middle";l.x=325;l.y=g;p.addChild(l);
l=new CButBet(l.x+60,g,n,.7,p);l.addEventListenerWithParams(ON_MOUSE_UP,this._onWinClicked,this,m);c.push(l);l=new createjs.Text(s_oGameSettings.getOddPlace(m),"20px "+TERTIARY_FONT,"#fff");l.textAlign="center";l.textBaseline="middle";l.x=465;l.y=g;p.addChild(l);l=new CButBet(l.x+60,g,n,.7,p);l.addEventListenerWithParams(ON_MOUSE_UP,this._onPlaceClicked,this,m);q.push(l);l=new createjs.Text(s_oGameSettings.getOddShow(m),"20px "+TERTIARY_FONT,"#fff");l.textAlign="center";l.textBaseline="middle";l.x=
593;l.y=g;p.addChild(l);l=new CButBet(l.x+60,g,n,.7,p);l.addEventListenerWithParams(ON_MOUSE_UP,this._onShowClicked,this,m);e.push(l);g+=67}};this.unload=function(){for(var g=0;g<q.length;g++)c[g].unload(),e[g].unload(),q[g].unload()};this.setX=function(g){p.x=g};this.clearBet=function(){for(var g=0;g<b.length;g++)b[g].gotoAndStop("idle")};this._onWinClicked=function(g){var n=CHIP_VALUES[s_oBetPanel.getChipSelected()];s_oBetPanel.setSimpleBet(g,1,n,c[g])&&(0===c[g].getTotBet()&&b[g].gotoAndPlay("anim"),
c[g].increaseBet(n))};this._onPlaceClicked=function(g){var n=CHIP_VALUES[s_oBetPanel.getChipSelected()];s_oBetPanel.setSimpleBet(g,2,n,q[g])&&(0===q[g].getTotBet()&&b[g].gotoAndPlay("anim"),q[g].increaseBet(n))};this._onShowClicked=function(g){var n=CHIP_VALUES[s_oBetPanel.getChipSelected()];s_oBetPanel.setSimpleBet(g,3,n,e[g])&&(0===e[g].getTotBet()&&b[g].gotoAndPlay("anim"),e[g].increaseBet(n))};this.getContainer=function(){return p};var k=d;this._init(a,h)}
function CForecastPanel(a,h,d){var b,c;this._init=function(){c=new createjs.Container;c.x=a;c.y=h;q.addChild(c);var e=createBitmap(s_oSpriteLibrary.getSprite("forecast_panel"));c.addChild(e);this._initForecastBets()};this.unload=function(){for(var e in b)-1<e.indexOf("forecast_")&&b[e].unload()};this._initForecastBets=function(){b=[];for(var e=[{x:26,y:10},{x:256,y:10},{x:486,y:10},{x:26,y:225},{x:256,y:225},{x:486,y:225}],p=0;p<NUM_GREYHOUNDS;p++)this._placeForecastBetForGreyhound(p,e[p].x,e[p].y)};
this._placeForecastBetForGreyhound=function(e,p,k){var g=s_oSpriteLibrary.getSprite("odd_bg"),n=s_oSpriteLibrary.getSprite("bet_place"),m=s_oSpriteLibrary.getSprite("bibs"),l=m.width/3,v=m.height/2;m=new createjs.SpriteSheet({images:[m],frames:{width:l,height:v},animations:{bib_0:[0],bib_1:[1],bib_2:[2],bib_3:[3],bib_4:[4],bib_5:[5]}});for(var u=0;u<NUM_GREYHOUNDS;u++)if(u!==e){var r=createSprite(m,"bib_"+e,0,0,l,v);r.x=p;r.y=k;r.scaleX=r.scaleY=.65;c.addChild(r);var x=new createjs.Text("X","12px "+
PRIMARY_FONT,"#fff");x.textAlign="center";x.textBaseline="middle";x.x=p+.65*l+10;x.y=k+.65*v/2;c.addChild(x);var C=createSprite(m,"bib_"+u,0,0,l/3,v/2);C.x=x.x+10;C.y=r.y;C.scaleX=C.scaleY=.65;c.addChild(C);x=createBitmap(g);x.x=C.x+.65*l+10;x.y=r.y+2;c.addChild(x);r=new createjs.Text(s_oGameSettings.getForecastOdd(e,u),"18px "+PRIMARY_FONT,"#fff");r.textAlign="center";r.textBaseline="alphabetic";r.x=x.x+g.width/2;r.y=x.y+g.height/2+6;c.addChild(r);r=new CButBet(x.x+g.width+.72*n.width/2+5,x.y+.72*
n.height/2,n,.45,c);r.setScale(.72);r.addEventListenerWithParams(ON_MOUSE_UP,this._onForecastClicked,this,{first:e,second:u});b["forecast_"+e+"_"+u]=r;k+=.65*v+5}};this.setX=function(e){c.x=e};this._onForecastClicked=function(e){var p=CHIP_VALUES[s_oBetPanel.getChipSelected()];s_oBetPanel.setForecastBet(e.first,e.second,p,b["forecast_"+e.first+"_"+e.second])&&b["forecast_"+e.first+"_"+e.second].increaseBet(p)};var q=d;this._init(a,h)}
function CBetList(){var a,h,d;this._init=function(){this.reset()};this.reset=function(){a=[];for(var b=0;b<NUM_GREYHOUNDS;b++)a[b]=[],a[b].place_1=0,a[b].place_2=0,a[b].place_3=0;h=[];for(b=0;b<NUM_GREYHOUNDS;b++){h[b]=[];for(var c=0;c<NUM_GREYHOUNDS;c++)h[b][c]=0}d=[]};this.addSimpleBet=function(b,c,q){a[b]["place_"+c]+=q;var e=0;switch(c){case 1:e=q*s_oGameSettings.getOddWin(b);break;case 2:e=q*s_oGameSettings.getOddPlace(b);break;case 3:e=q*s_oGameSettings.getOddShow(b)}d.push({type_bet:"simple",
greyhounds:[{index:b,place:c}],bet:q,win:e})};this.addForecastBet=function(b,c,q){h[b][c]+=q;d.push({type_bet:"forecast",greyhounds:[{index:b,place:1},{index:c,place:2}],bet:q,win:q*s_oGameSettings.getForecastOdd(b,c)})};this.getMinWin=function(){if(0<d.length){for(var b=d[0].win,c=1;c<d.length;c++)b>d[c].win&&(b=d[c].win);return b}return 0};this.getTotWinWithCurRank=function(b){var c=0,q=[];if(0<a[b[0]].place_1){var e=a[b[0]].place_1*s_oGameSettings.getOddWin(b[0]);e=parseFloat(e.toFixed(2));c+=
e;q.push({win:e,greyhounds:b[0],bet:a[b[0]].place_1,type:"win"})}0<a[b[0]].place_2&&(e=a[b[0]].place_2*s_oGameSettings.getOddPlace(b[0]),e=parseFloat(e.toFixed(2)),c+=e,q.push({win:e,greyhounds:b[0],bet:a[b[0]].place_2,type:"place"}));0<a[b[1]].place_2&&(e=a[b[1]].place_2*s_oGameSettings.getOddPlace(b[1]),e=parseFloat(e.toFixed(2)),c+=e,q.push({win:e,greyhounds:b[1],bet:a[b[1]].place_2,type:"place"}));0<a[b[0]].place_3&&(e=a[b[0]].place_3*parseFloat(s_oGameSettings.getOddShow(b[0])),e=parseFloat(e.toFixed(2)),
c+=e,q.push({win:e,greyhounds:b[0],bet:a[b[0]].place_3,type:"show"}));0<a[b[1]].place_3&&(e=a[b[1]].place_3*s_oGameSettings.getOddShow(b[1]),e=parseFloat(e.toFixed(2)),c+=e,q.push({win:e,greyhounds:b[1],bet:a[b[1]].place_3,type:"show"}));0<a[b[2]].place_3&&(e=a[b[2]].place_3*s_oGameSettings.getOddShow(b[2]),e=parseFloat(e.toFixed(2)),c+=e,q.push({win:e,greyhounds:b[2],bet:a[b[2]].place_3,type:"show"}));0<h[b[0]][b[1]]&&(e=h[b[0]][b[1]]*s_oGameSettings.getForecastOdd(b[0],b[1]),e=parseFloat(e.toFixed(2)),
c+=e,q.push({win:e,greyhounds:[b[0],b[1]],bet:h[b[0]][b[1]],type:"forecast"}));return{tot_win:c,win_list:q}};s_oBetList=this;this._init()}var s_oBetList=null;
function CFichesController(a,h){var d,b,c,q,e,p,k,g,n,m,l,v;this._init=function(r){q=r;n=new createjs.Container;u.addChild(n);p=new CVector2;p.set(n.x,n.y);m=new createjs.Container;u.addChild(m);r*=18;v=new createjs.Text("",r+"px "+TERTIARY_FONT,"#000");v.textAlign="center";m.addChild(v);l=new createjs.Text("",r+"px "+TERTIARY_FONT,"#fff");l.textAlign="center";m.addChild(l);c=e=b=0;d=!1};this.addEventListener=function(r,x,C){};this.reset=function(){d=!1;c=0;n.removeAllChildren();n.x=p.getX();n.y=
p.getY();v.text="";l.text=""};this.setPrevValue=function(r){e=r};this.refreshFiches=function(r,x,C){r=r.sortOn("value","index");for(var f=x,w=C,y=c=0,z=0;z<r.length;z++)(new CFicheBut(r[z].index,f,w,a,n)).disable(),w-=5,y++,9<y&&(y=0,f+=FICHE_WIDTH,w=C),c+=r[z].value;playSound("chip",1,0);l.x=x;l.y=C+25*q;l.text=c.toFixed(2)+TEXT_CURRENCY;v.x=x+2;v.y=C+27*q;v.text=c.toFixed(2)+TEXT_CURRENCY};this.createFichesPile=function(r,x,C){this.reset();var f=CHIP_VALUES,w=[];do{for(var y=f[f.length-1],z=f.length-
1;y>r;)z--,y=f[z];z=Math.floor(r/y);for(var E=0;E<z;E++)w.push({value:y,index:s_oGameSettings.getIndexForFiches(y)});y=Math.floor(r/y)===r/y?0:r%y;r=y.toFixed(2)}while(0<y);this.refreshFiches(w,x,C*q)};this.initMovement=function(r,x){e=c;k=new CVector2(n.x,n.y);g=new CVector2(r,x);l.text="";v.text="";d=!0};this.getValue=function(){return c};this.getPrevBet=function(){return e};this.update=function(r){if(d)if(b+=r,b>TIME_FICHES_MOV)b=0,d=!1;else{r=easeInOutCubic(b,0,1,TIME_FICHES_MOV);var x=new CVector2;
x=tweenVectors(k,g,r,x);n.x=x.getX();n.y=x.getY()}};var u=h;this._init(a)}
function CButBet(a,h,d,b,c){var q,e,p,k,g,n,m,l,v,u=!1,r,x;this._init=function(w,y,z,E){q=0;e=[];p=[];g=[];x=new createjs.Container;x.x=w;x.y=y;C.addChild(x);k=createBitmap(z);m=n=1;k.regX=z.width/2;k.regY=z.height/2;s_bMobile||(k.cursor="pointer");x.addChild(k);this._initListener();r=new CFichesController(E,x)};this.unload=function(){k.off("mousedown",l);k.off("pressup",v);C.removeChild(x)};this.setVisible=function(w){k.visible=w};this.setCursorType=function(w){k.cursor=w};this._initListener=function(){l=
k.on("mousedown",this.buttonDown);v=k.on("pressup",this.buttonRelease)};this.addEventListener=function(w,y,z){e[w]=y;p[w]=z};this.addEventListenerWithParams=function(w,y,z,E){e[w]=y;p[w]=z;g[w]=E};this.buttonRelease=function(){u||(k.scaleX=0<n?n:-n,k.scaleY=m,playSound("chip",1,0),e[ON_MOUSE_UP]&&e[ON_MOUSE_UP].call(p[ON_MOUSE_UP],g[ON_MOUSE_UP]))};this.buttonDown=function(){u||(k.scaleX=0<n?.9*n:.9*-n,k.scaleY=.9*m,e[ON_MOUSE_DOWN]&&e[ON_MOUSE_DOWN].call(p[ON_MOUSE_DOWN],g[ON_MOUSE_DOWN]))};this.rotation=
function(w){k.rotation=w};this.getButton=function(){return k};this.setPosition=function(w,y){k.x=w;k.y=y};this.setX=function(w){k.x=w};this.setY=function(w){k.y=w};this.getButtonImage=function(){return k};this.block=function(w){u=w;k.scaleX=n;k.scaleY=m};this.setScaleX=function(w){n=k.scaleX=w};this.setScale=function(w){m=n=w;k.scaleX=k.scaleY=w};this.increaseBet=function(w){q+=w;r.createFichesPile(q.toFixed(2),0,-4)};this.clearBet=function(){q=0;r.reset()};this.getX=function(){return k.x};this.getY=
function(){return k.y};this.pulseAnimation=function(){createjs.Tween.get(k).to({scaleX:.9*n,scaleY:.9*m},850,createjs.Ease.quadOut).to({scaleX:n,scaleY:m},650,createjs.Ease.quadIn).call(function(){f.pulseAnimation()})};this.trebleAnimation=function(){createjs.Tween.get(k).to({rotation:5},75,createjs.Ease.quadOut).to({rotation:-5},140,createjs.Ease.quadIn).to({rotation:0},75,createjs.Ease.quadIn).wait(750).call(function(){f.trebleAnimation()})};this.removeAllTweens=function(){createjs.Tween.removeTweens(k)};
this.getTotBet=function(){return q};var C=void 0!==c?c:s_oStage;this._init(a,h,d,b);var f=this;return this}
function CVector2(a,h){var d,b;this._init=function(c,q){d=c;b=q};this.add=function(c,q){d+=c;b+=q};this.addV=function(c){d+=c.getX();b+=c.getY()};this.scalarDivision=function(c){d/=c;b/=c};this.subV=function(c){d-=c.getX();b-=c.getY()};this.scalarProduct=function(c){d*=c;b*=c};this.invert=function(){d*=-1;b*=-1};this.dotProduct=function(c){return d*c.getX()+b*c.getY()};this.set=function(c,q){d=c;b=q};this.setV=function(c){d=c.getX();b=c.getY()};this.length=function(){return Math.sqrt(d*d+b*b)};this.length2=
function(){return d*d+b*b};this.normalize=function(){var c=this.length();0<c&&(d/=c,b/=c)};this.getNormalize=function(c){this.length();c.set(d,b);c.normalize()};this.rot90CCW=function(){var c=d;d=-b;b=c};this.rot90CW=function(){var c=d;d=b;b=-c};this.getRotCCW=function(c){c.set(d,b);c.rot90CCW()};this.getRotCW=function(c){c.set(d,b);c.rot90CW()};this.ceil=function(){d=Math.ceil(d);b=Math.ceil(b)};this.round=function(){d=Math.round(d);b=Math.round(b)};this.toString=function(){return"Vector2: "+d+", "+
b};this.print=function(){trace("Vector2: "+d+", "+b)};this.getX=function(){return d};this.getY=function(){return b};this._init(a,h)}
function CMsgBox(){var a,h,d,b,c;this._init=function(){d=new createjs.Container;d.alpha=0;d.visible=!1;s_oStage.addChild(d);a=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));d.addChild(a);h=new CTLText(d,CANVAS_WIDTH/2-200,CANVAS_HEIGHT/2-100,400,130,34,"center","#fff",PRIMARY_FONT,1,0,0," ",!0,!0,!0,!1);b=new CTextButton(CANVAS_WIDTH/2,460,s_oSpriteLibrary.getSprite("fiche_panel"),TEXT_RECHARGE,PRIMARY_FONT,"#fff",30,d);b.setVisible(!1);b.addEventListener(ON_MOUSE_UP,this._onRecharge,this);c=
new CGfxButton(CANVAS_WIDTH/2+205,CANVAS_HEIGHT/2-130,s_oSpriteLibrary.getSprite("but_exit"),d);c.addEventListener(ON_MOUSE_UP,this._onExit,this)};this.unload=function(){b.unload();c.unload()};this.show=function(q,e){h.refreshText(q);d.visible=!0;createjs.Tween.get(d).to({alpha:1},500);e?b.setVisible(!0):b.setVisible(!1)};this._onExit=function(){d.visible=!1};this._onRecharge=function(){$(s_oMain).trigger("recharge");d.visible=!1};this._init();return this}
function CTrackBg(a){var h,d,b,c,q,e;this._init=function(){e=new createjs.Container;p.addChild(e);d=0;b=2;c=0;q=[];for(var k=0;k<NUM_TRACK_BG;k++){var g=createBitmap(s_oSpriteLibrary.getSprite("bg_track_"+k));0<k&&(g.visible=!1);e.addChild(g);q[k]=g}h=!0};this.update=function(){if(!h)return d;c++;c===b&&(c=0,d++,q[d].visible=!0,q[d-1].visible=!1,d===q.length-1?(h=!1,s_oGame.checkGreyhoundArrival()):17===d&&s_oGame.startGreyhounds());return d};var p=a;this._init()}
function CGreyhound(a,h,d,b,c,q){var e,p,k,g,n,m,l,v,u,r,x;this._init=function(f,w,y,z,E){p=!1;k=w;l=0;v=ARRIVAL_X-GREYHOUND_WIDTH/2*z+30;u=y;r=E;w={framerate:40,images:[s_oSpriteLibrary.getSprite("greyhound_"+w)],frames:{width:GREYHOUND_WIDTH,height:GREYHOUND_HEIGHT,regX:GREYHOUND_WIDTH/2,regY:GREYHOUND_HEIGHT},animations:{idle:[0,0],anim:[0,21],start:[22],anim_1:[5,21,"anim"],anim_2:[10,21,"anim"],anim_3:[15,21,"anim"]}};w=new createjs.SpriteSheet(w);x=createSprite(w,"start",GREYHOUND_WIDTH/2,GREYHOUND_HEIGHT,
GREYHOUND_WIDTH,GREYHOUND_HEIGHT);x.x=f.x;x.y=f.y;x.scaleX=x.scaleY=z;x.alpha=0;C.addChild(x)};this.startRace=function(){var f="anim_"+(Math.floor(3*Math.random())+1);createjs.Tween.get(x).to({alpha:1},150).call(function(){x.gotoAndPlay(f)});m=x.x;g=0;n=r[l].frame;e=!0};this.pauseAnim=function(){x.paused=!0};this.unpauseAnim=function(){x.paused=!1};this.getX=function(){return x.x};this.update=function(f){if(e){g++;if(g>=n)l++,l<r.length?(g=0,n=r[l].frame,m=x.x):e=!1;else{var w=s_oTweenController.easeLinear(g,
0,1,n);w=s_oTweenController.tweenValue(m,r[l].x,w);x.x=w}f&&!p&&x.x>=v&&(p=!0,s_oGame.greyhoundPhotofinish(k-1,u))}};var C=q;this._init(a,h,d,b,c)}
function CTweenController(){this.tweenValue=function(a,h,d){return a+d*(h-a)};this.easeLinear=function(a,h,d,b){return d*a/b+h};this.easeInCubic=function(a,h,d,b){b=(a/=b)*a*a;return h+d*b};this.easeBackInQuart=function(a,h,d,b){b=(a/=b)*a;return h+d*(2*b*b+2*b*a+-3*b)};this.easeInBack=function(a,h,d,b){return d*(a/=b)*a*(2.70158*a-1.70158)+h};this.easeOutCubic=function(a,h,d,b){return d*((a=a/b-1)*a*a+1)+h};this.getTrajectoryPoint=function(a,h){var d=new createjs.Point,b=(1-a)*(1-a),c=a*a;d.x=b*
h.start.x+2*(1-a)*a*h.traj.x+c*h.end.x;d.y=b*h.start.y+2*(1-a)*a*h.traj.y+c*h.end.y;return d}}
function CRankingGui(a,h){var d,b,c,q,e,p,k;this._init=function(n){var m=s_oSpriteLibrary.getSprite("rank_panel");d=CANVAS_HEIGHT-m.height+6;k=new createjs.Container;k.x=0;k.y=d;g.addChild(k);m=createBitmap(m);k.addChild(m);q=[];q[0]=new createjs.Point(780,48);q[1]=new createjs.Point(642,48);q[2]=new createjs.Point(504,48);q[3]=new createjs.Point(366,48);q[4]=new createjs.Point(228,48);q[5]=new createjs.Point(90,48);this._initBibs(n);b=2;e=createBitmap(s_oSpriteLibrary.getSprite("fill_bar"));e.x=
107;e.y=116;k.addChild(e);p=new createjs.Shape;p.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(e.x,e.y-2,.01,10);k.addChild(p);e.mask=p;this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(n,m){k.y=d-m};this._initBibs=function(n){c=[];for(var m=0;m<NUM_GREYHOUNDS;m++){var l=new createjs.Container;l.x=q[m].x;l.y=q[m].y;k.addChild(l);var v=createBitmap(s_oSpriteLibrary.getSprite("bib_gui_"+m));l.addChild(v);new CTLText(l,-28,0,80,12,12,"right","#fff",PRIMARY_FONT,1,0,
0,n[m].toUpperCase(),!0,!0,!1,!1);c.push(l)}};this.refreshRank=function(n){for(var m=0;m<n.length;m++)createjs.Tween.get(c[n[m].index]).to({x:q[m].x},1E3,createjs.Ease.cubicOut)};this.refreshRadar=function(n){p.graphics.clear();p.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(e.x,e.y-2,b*n,10)};var g=h;this._init(a)}
function CArrivalPanel(a,h,d){var b,c,q,e,p,k,g;this._init=function(m,l){e=0;c=m;q=l;g=new createjs.Container;g.x=c;g.y=q;n.addChild(g);var v=s_oSpriteLibrary.getSprite("panel_arrival");v=createBitmap(v);g.addChild(v);v=s_oSpriteLibrary.getSprite("bibs");var u=v.width/3,r=v.height/2,x=new createjs.SpriteSheet({images:[v],frames:{width:u,height:r},animations:{bib_0:[0],bib_1:[1],bib_2:[2],bib_3:[3],bib_4:[4],bib_5:[5]}});p=[];k=[];for(var C=6,f=0;f<NUM_GREYHOUNDS;f++){var w=createSprite(x,"bib_0",
0,0,u,r);w.x=10;w.y=C;w.visible=!1;w.scaleX=w.scaleY=.5;g.addChild(w);k.push(w);w=new CTLText(g,w.x+.5*u+5,w.y+12,120,15,15,"left","#fff",TERTIARY_FONT,1,0,0," ",!0,!0,!1,!1);p.push(w);C+=.5*r+4}b=CANVAS_WIDTH-v.width};this.show=function(){createjs.Tween.get(g).to({x:b},500,createjs.Ease.cubicOut)};this.hide=function(){createjs.Tween.get(g).to({x:c},500,createjs.Ease.cubicOut)};this.refreshRank=function(m,l){p[e].refreshText(l);k[e].gotoAndStop("bib_"+m);k[e].visible=!0;0===e&&this.show();e++};var n=
d;this._init(a,h)}
function CWinPanel(a){var h,d,b,c,q,e;this._init=function(){e=new createjs.Container;e.visible=!1;p.addChild(e);var k=createBitmap(s_oSpriteLibrary.getSprite("win_panel"));e.addChild(k);k=s_oSpriteLibrary.getSprite("bibs");h=k.width/3;d=k.height/2;b=new createjs.SpriteSheet({images:[k],frames:{width:h,height:d},animations:{bib_0:[0],bib_1:[1],bib_2:[2],bib_3:[3],bib_4:[4],bib_5:[5]}});q=new CTLText(e,CANVAS_WIDTH/2+15,450,120,80,30,"center","#ffde00",SECONDARY_FONT,1,0,0,TEXT_WIN,!0,!0,!0,!1);c=new CGfxButton(700,
491,s_oSpriteLibrary.getSprite("but_skip"),e);c.addEventListener(ON_MOUSE_UP,this.onSkip,this)};this.unload=function(){c.unload()};this.show=function(k,g,n){q.refreshText(TEXT_WIN+"\n"+k+TEXT_CURRENCY);k=310;for(var m=0;3>m;m++){var l={images:[s_oSpriteLibrary.getSprite("greyhound_"+(n[m]+1))],frames:{width:GREYHOUND_WIDTH,height:GREYHOUND_HEIGHT,regX:GREYHOUND_WIDTH/2,regY:GREYHOUND_HEIGHT},animations:{idle:[18,18],anim:[0,21],start:[22],anim_1:[5,21,"anim"],anim_2:[10,21,"anim"],anim_3:[15,21,"anim"]}};
l=new createjs.SpriteSheet(l);l=createSprite(l,"idle",GREYHOUND_WIDTH/2,GREYHOUND_HEIGHT,GREYHOUND_WIDTH,GREYHOUND_HEIGHT);l.scaleX=l.scaleY=.5;l.x=CANVAS_WIDTH/2+150;l.y=k;e.addChild(l);k+=68}k=CANVAS_HEIGHT/2-150;for(n=0;n<g.length;n++){if("forecast"===g[n].type){l=g[n].greyhounds;var v=createSprite(b,"bib_"+l[0],0,0,h,d);v.x=280;v.y=k;v.scaleX=v.scaleY=.5;e.addChild(v);m=new createjs.Text("X","20px "+PRIMARY_FONT,"#fff");m.textAlign="center";m.textBaseline="middle";m.x=v.x+.5*h+10;m.y=k+15;e.addChild(m);
l=createSprite(b,"bib_"+l[1],0,0,h,d);l.x=m.x+10;l.y=k;l.scaleX=l.scaleY=.5;e.addChild(l);l=l.x+35}else v=createSprite(b,"bib_"+g[n].greyhounds,0,0,h,d),v.x=280,v.y=k,v.scaleX=v.scaleY=.5,e.addChild(v),l=v.x+35;m=new createjs.Text(g[n].type.toUpperCase(),"16px "+PRIMARY_FONT,"#ffb400");m.textAlign="left";m.textBaseline="alphabetic";m.x=l;m.y=k+22;e.addChild(m);l=new createjs.Text(TEXT_WIN+": "+g[n].win+TEXT_CURRENCY,"16px "+PRIMARY_FONT,"#fff");l.textAlign="left";l.textBaseline="alphabetic";l.x=m.x+
m.getBounds().width+10;l.y=k+22;e.addChild(l);k+=35}e.visible=!0;e.alpha=0;createjs.Tween.get(e).wait(1E3).to({alpha:1},500,createjs.Ease.cubicOut)};this.onSkip=function(){s_oGame.returnInBetPanel()};var p=a;this._init()}
function CLosePanel(a){var h,d,b,c,q,e;this._init=function(){e=new createjs.Container;e.visible=!1;p.addChild(e);var k=createBitmap(s_oSpriteLibrary.getSprite("lose_panel"));e.addChild(k);new CTLText(e,CANVAS_WIDTH/2-200,250,400,50,50,"center","#fff",PRIMARY_FONT,1,0,0,TEXT_NO_WIN,!0,!0,!0,!1);k=s_oSpriteLibrary.getSprite("bibs");h=k.width/3;d=k.height/2;c=new createjs.SpriteSheet({images:[k],frames:{width:h,height:d},animations:{bib_0:[0],bib_1:[1],bib_2:[2],bib_3:[3],bib_4:[4],bib_5:[5]}});b=[];
k=createSprite(c,"bib_0",0,0,h,d);k.x=CANVAS_WIDTH/2-100-h/2;k.y=350;e.addChild(k);b.push(k);k=createSprite(c,"bib_0",0,0,h,d);k.x=CANVAS_WIDTH/2-h/2;k.y=350;e.addChild(k);b.push(k);k=createSprite(c,"bib_0",0,0,h,d);k.x=CANVAS_WIDTH/2+100-h/2;k.y=350;e.addChild(k);b.push(k);new CTLText(e,CANVAS_WIDTH/2-200,500,400,30,30,"center","#fff",PRIMARY_FONT,1,0,0,TEXT_WIN+": 0.00 "+TEXT_CURRENCY,!0,!0,!0,!1);q=new CGfxButton(700,480,s_oSpriteLibrary.getSprite("but_skip"),e);q.addEventListener(ON_MOUSE_UP,
this.onSkip,this)};this.unload=function(){q.unload()};this.show=function(k){for(var g=0;3>g;g++)b[g].gotoAndStop("bib_"+k[g]);e.visible=!0;e.alpha=0;createjs.Tween.get(e).wait(1E3).to({alpha:1},500,createjs.Ease.cubicOut)};this.onSkip=function(){s_oGame.returnInBetPanel()};var p=a;this._init()}
function CButStartRace(a,h,d,b,c,q,e){var p,k,g,n,m,l;this._init=function(u,r,x,C,f,w){p=[];k=[];g=new createjs.Container;g.x=u;g.y=r;g.regX=x.width/2;g.regY=x.height/2;v.addChild(g);u=createBitmap(x);g.addChild(u);n=new CTLText(g,0,6,x.width,w,w,"center",f,PRIMARY_FONT,1,0,0,C,!0,!0,!0,!1);s_bMobile||(g.cursor="pointer");this._initListener()};this.unload=function(){g.off("mousedown",m);g.off("pressup",l);v.removeChild(g)};this.setVisible=function(u){g.visible=u};this._initListener=function(){m=g.on("mousedown",
this.buttonDown);l=g.on("pressup",this.buttonRelease)};this.addEventListener=function(u,r,x){p[u]=r;k[u]=x};this.buttonRelease=function(){g.scaleX=1;g.scaleY=1;playSound("click",1,0);p[ON_MOUSE_UP]&&p[ON_MOUSE_UP].call(k[ON_MOUSE_UP])};this.buttonDown=function(){g.scaleX=.9;g.scaleY=.9;p[ON_MOUSE_DOWN]&&p[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN])};this.setTextPosition=function(u){n.setY(u)};this.setPosition=function(u,r){g.x=u;g.y=r};this.setX=function(u){g.x=u};this.setY=function(u){g.y=u};this.getButtonImage=
function(){return g};this.getX=function(){return g.x};this.getY=function(){return g.y};var v=e;this._init(a,h,d,b,c,q);return this}
function CAreYouSurePanel(a){var h,d,b,c;this._init=function(){c=new createjs.Container;c.visible=!1;h=c.on("click",function(){});q.addChild(c);var e=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));c.addChild(e);new CTLText(c,CANVAS_WIDTH/2-200,250,400,100,50,"center","#fff",PRIMARY_FONT,1,0,0,TEXT_ARE_YOU_SURE,!0,!0,!0,!1);d=new CGfxButton(CANVAS_WIDTH/2+170,460,s_oSpriteLibrary.getSprite("but_yes"),c);d.addEventListener(ON_MOUSE_UP,this._onReleaseYes,this);b=new CGfxButton(CANVAS_WIDTH/2-170,
460,s_oSpriteLibrary.getSprite("but_no"),c);b.addEventListener(ON_MOUSE_UP,this._onReleaseNo,this)};this.unload=function(){c.off("click",h);b.unload();d.unload()};this.show=function(){c.visible=!0;c.alpha=0;createjs.Tween.get(c).to({alpha:1},500,createjs.Ease.cubicOut)};this._onReleaseYes=function(){s_oGame.onExit()};this._onReleaseNo=function(){c.visible=!1;s_oGame.unpause()};var q=a;this._init(a)}
CTLText.prototype={constructor:CTLText,__autofit:function(){if(this._bFitText){for(var a=this._iFontSize;(this._oText.getBounds().height>this._iHeight-2*this._iPaddingV||this._oText.getBounds().width>this._iWidth-2*this._iPaddingH)&&!(a--,this._oText.font=a+"px "+this._szFont,this._oText.lineHeight=Math.round(a*this._fLineHeightFactor),this.__updateY(),this.__verticalAlign(),8>a););this._iFontSize=a}},__verticalAlign:function(){if(this._bVerticalAlign){var a=this._oText.getBounds().height;this._oText.y-=
(a-this._iHeight)/2+this._iPaddingV}},__updateY:function(){this._oText.y=this._y+this._iPaddingV;switch(this._oText.textBaseline){case "middle":this._oText.y+=this._oText.lineHeight/2+(this._iFontSize*this._fLineHeightFactor-this._iFontSize)}},__createText:function(a){this._bDebug&&(this._oDebugShape=new createjs.Shape,this._oDebugShape.graphics.beginFill("rgba(255,0,0,0.5)").drawRect(this._x,this._y,this._iWidth,this._iHeight),this._oContainer.addChild(this._oDebugShape));this._oText=new createjs.Text(a,
this._iFontSize+"px "+this._szFont,this._szColor);this._oText.textBaseline="middle";this._oText.lineHeight=Math.round(this._iFontSize*this._fLineHeightFactor);this._oText.textAlign=this._szAlign;this._oText.lineWidth=this._bMultiline?this._iWidth-2*this._iPaddingH:null;switch(this._szAlign){case "center":this._oText.x=this._x+this._iWidth/2;break;case "left":this._oText.x=this._x+this._iPaddingH;break;case "right":this._oText.x=this._x+this._iWidth-this._iPaddingH}this._oContainer.addChild(this._oText);
this.refreshText(a)},setVerticalAlign:function(a){this._bVerticalAlign=a},setOutline:function(a){null!==this._oText&&(this._oText.outline=a)},setVisible:function(a){this._oContainer.visible=a},setShadow:function(a,h,d,b){null!==this._oText&&(this._oText.shadow=new createjs.Shadow(a,h,d,b))},setColor:function(a){this._oText.color=a},setAlpha:function(a){this._oText.alpha=a},setY:function(a){this._oText.y=a},removeTweens:function(){createjs.Tween.removeTweens(this._oText)},getText:function(){return this._oText},
getY:function(){return this._y},getFontSize:function(){return this._iFontSize},refreshText:function(a){""===a&&(a=" ");null===this._oText&&this.__createText(a);this._oText.text=a;this._oText.font=this._iFontSize+"px "+this._szFont;this._oText.lineHeight=Math.round(this._iFontSize*this._fLineHeightFactor);this.__autofit();this.__updateY();this.__verticalAlign()}};
function CTLText(a,h,d,b,c,q,e,p,k,g,n,m,l,v,u,r,x){this._oContainer=a;this._x=h;this._y=d;this._iWidth=b;this._iHeight=c;this._bMultiline=r;this._iFontSize=q;this._szAlign=e;this._szColor=p;this._szFont=k;this._iPaddingH=n;this._iPaddingV=m;this._bVerticalAlign=u;this._bFitText=v;this._bDebug=x;this._oDebugShape=null;this._fLineHeightFactor=g;this._oText=null;l&&this.__createText(l)}
function CFicheBut(a,h,d,b,c){var q,e,p,k=[],g,n;this._init=function(m,l){var v=s_oSpriteLibrary.getSprite("fiche_"+a);q=!1;n=new createjs.Container;n.x=m;n.y=l;n.regX=v.width/2;n.regY=v.height/2;c.addChild(n);e=[];p=[];g=createBitmap(v);g.cursor="pointer";n.addChild(g);n.scaleX=n.scaleY=b;new CTLText(n,11,11,18,18,20,"center",COLOR_FICHES[a],PRIMARY_FONT,1.1,0,0,CHIP_VALUES[a],!0,!0,!1,!1);this._initListener()};this.unload=function(){n.off("mousedown",this.buttonDown);n.off("pressup",this.buttonRelease);
c.removeChild(n)};this.select=function(){};this.deselect=function(){};this.enable=function(){q=!1};this.disable=function(){q=!0};this.setVisible=function(m){n.visible=m};this._initListener=function(){n.on("mousedown",this.buttonDown);n.on("pressup",this.buttonRelease)};this.addEventListener=function(m,l,v){e[m]=l;p[m]=v};this.addEventListenerWithParams=function(m,l,v,u){e[m]=l;p[m]=v;k=u};this.buttonRelease=function(){q||(playSound("click",1,!1),n.scaleX=b,n.scaleY=b,e[ON_MOUSE_UP]&&e[ON_MOUSE_UP].call(p[ON_MOUSE_UP],
k))};this.buttonDown=function(){q||(n.scaleX=.9*b,n.scaleY=.9*b,e[ON_MOUSE_DOWN]&&e[ON_MOUSE_DOWN].call(p[ON_MOUSE_DOWN],k))};this.setPosition=function(m,l){n.x=m;n.y=l};this.setX=function(m){n.x=m};this.setY=function(m){n.y=m};this.getX=function(){return n.x};this.getY=function(){return n.y};this._init(h,d)}function extractHostname(a){a=-1<a.indexOf("://")?a.split("/")[2]:a.split("/")[0];a=a.split(":")[0];return a=a.split("?")[0]}
function extractRootDomain(a){a=extractHostname(a);var h=a.split("."),d=h.length;2<d&&(a=h[d-2]+"."+h[d-1]);return a}
var getClosestTop=function(){var a=window,h=!1;try{for(;a.parent.document!==a.document;)if(a.parent.document)a=a.parent;else{h=!0;break}}catch(d){h=!0}return{topFrame:a,err:h}},getBestPageUrl=function(a){var h=a.topFrame,d="";if(a.err)try{try{d=window.top.location.href}catch(c){var b=window.location.ancestorOrigins;d=b[b.length-1]}}catch(c){d=h.document.referrer}else d=h.location.href;return d},TOPFRAMEOBJ=getClosestTop(),PAGE_URL=getBestPageUrl(TOPFRAMEOBJ);
function seekAndDestroy(){for(var a=extractRootDomain(PAGE_URL),h=[String.fromCharCode(99,111,100,101,116,104,105,115,108,97,98,46,99,111,109),String.fromCharCode(101,110,118,97,116,111,46,99,111,109),String.fromCharCode(99,111,100,101,99,97,110,121,111,110,46,99,111,109),String.fromCharCode(99,111,100,101,99,97,110,121,111,110,46,110,101,116)],d=0;d<h.length;d++)if(h[d]===a)return!0;return!0};