/*
 Platform.js
 Copyright 2014-2020 Benjamin Tan
 Copyright 2011-2013 John-David Dalton
 Available under MIT license
*/
(function(){var a="undefined"!==typeof window&&"undefined"!==typeof window.document?window.document:{},e="undefined"!==typeof module&&module.exports,c=function(){for(var h,k=["requestFullscreen exitFullscreen fullscreenElement fullscreenEnabled fullscreenchange fullscreenerror".split(" "),"webkitRequestFullscreen webkitExitFullscreen webkitFullscreenElement webkitFullscreenEnabled webkitfullscreenchange webkitfullscreenerror".split(" "),"webkitRequestFullScreen webkitCancelFullScreen webkitCurrentFullScreenElement webkitCancelFullScreen webkitfullscreenchange webkitfullscreenerror".split(" "),
"mozRequestFullScreen mozCancelFullScreen mozFullScreenElement mozFullScreenEnabled mozfullscreenchange mozfullscreenerror".split(" "),"msRequestFullscreen msExitFullscreen msFullscreenElement msFullscreenEnabled MSFullscreenChange MSFullscreenError".split(" ")],f=0,t=k.length,b={};f<t;f++)if((h=k[f])&&h[1]in a){for(f=0;f<h.length;f++)b[k[0][f]]=h[f];return b}return!1}(),g={change:c.fullscreenchange,error:c.fullscreenerror},l={request:function(h){return new Promise(function(k,f){var t=function(){this.off("change",
t);k()}.bind(this);this.on("change",t);h=h||a.documentElement;Promise.resolve(h[c.requestFullscreen]())["catch"](f)}.bind(this))},exit:function(){return new Promise(function(h,k){if(this.isFullscreen){var f=function(){this.off("change",f);h()}.bind(this);this.on("change",f);Promise.resolve(a[c.exitFullscreen]())["catch"](k)}else h()}.bind(this))},toggle:function(h){return this.isFullscreen?this.exit():this.request(h)},onchange:function(h){this.on("change",h)},onerror:function(h){this.on("error",h)},
on:function(h,k){var f=g[h];f&&a.addEventListener(f,k,!1)},off:function(h,k){var f=g[h];f&&a.removeEventListener(f,k,!1)},raw:c};c?(Object.defineProperties(l,{isFullscreen:{get:function(){return!!a[c.fullscreenElement]}},element:{enumerable:!0,get:function(){return a[c.fullscreenElement]}},isEnabled:{enumerable:!0,get:function(){return!!a[c.fullscreenEnabled]}}}),e?module.exports=l:window.screenfull=l):e?module.exports={isEnabled:!1}:window.screenfull={isEnabled:!1}})();
(function(){function a(d){d=String(d);return d.charAt(0).toUpperCase()+d.slice(1)}function e(d,A){var C=-1,w=d?d.length:0;if("number"==typeof w&&-1<w&&w<=v)for(;++C<w;)A(d[C],C,d);else g(d,A)}function c(d){d=t(d);return/^(?:webOS|i(?:OS|P))/.test(d)?d:a(d)}function g(d,A){for(var C in d)u.call(d,C)&&A(d[C],C,d)}function l(d){return null==d?a(d):y.call(d).slice(8,-1)}function h(d,A){var C=null!=d?typeof d[A]:"number";return!/^(?:boolean|number|string|undefined)$/.test(C)&&("object"==C?!!d[A]:!0)}function k(d){return String(d).replace(/([ -])(?!$)/g,
"$1?")}function f(d,A){var C=null;e(d,function(w,B){C=A(C,w,B,d)});return C}function t(d){return String(d).replace(/^ +| +$/g,"")}function b(d){function A(T){return f(T,function(P,M){var V=M.pattern||k(M);!P&&(P=RegExp("\\b"+V+" *\\d+[.\\w_]*","i").exec(d)||RegExp("\\b"+V+" *\\w+-[\\w]*","i").exec(d)||RegExp("\\b"+V+"(?:; *(?:[a-z]+[_-])?[a-z]+\\d+|[^ ();-]*)","i").exec(d))&&((P=String(M.label&&!RegExp(V,"i").test(M.label)?M.label:P).split("/"))[1]&&!/[\d.]+/.test(P[0])&&(P[0]+=" "+P[1]),M=M.label||
M,P=c(P[0].replace(RegExp(V,"i"),M).replace(RegExp("; *(?:"+M+"[_-])?","i")," ").replace(RegExp("("+M+")[-_.]?(\\w)","i"),"$1 $2")));return P})}function C(T){return f(T,function(P,M){return P||(RegExp(M+"(?:-[\\d.]+/|(?: for [\\w-]+)?[ /-])([\\d.]+[^ ();/_-]*)","i").exec(d)||0)[1]||null})}var w=r,B=d&&"object"==typeof d&&"String"!=l(d);B&&(w=d,d=null);var D=w.navigator||{},z=D.userAgent||"";d||(d=z);var I=B?!!D.likeChrome:/\bChrome\b/.test(d)&&!/internal|\n/i.test(y.toString()),Q=B?"Object":"ScriptBridgingProxyObject",
H=B?"Object":"Environment",N=B&&w.java?"JavaPackage":l(w.java),O=B?"Object":"RuntimeObject";H=(N=/\bJava/.test(N)&&w.java)&&l(w.environment)==H;var U=N?"a":"\u03b1",R=N?"b":"\u03b2",X=w.document||{},J=w.operamini||w.opera,W=x.test(W=B&&J?J["[[Class]]"]:l(J))?W:J=null,m,aa=d;B=[];var ba=null,Z=d==z;z=Z&&J&&"function"==typeof J.version&&J.version();var L=function(T){return f(T,function(P,M){return P||RegExp("\\b"+(M.pattern||k(M))+"\\b","i").exec(d)&&(M.label||M)})}([{label:"EdgeHTML",pattern:"Edge"},
"Trident",{label:"WebKit",pattern:"AppleWebKit"},"iCab","Presto","NetFront","Tasman","KHTML","Gecko"]),E=function(T){return f(T,function(P,M){return P||RegExp("\\b"+(M.pattern||k(M))+"\\b","i").exec(d)&&(M.label||M)})}(["Adobe AIR","Arora","Avant Browser","Breach","Camino","Electron","Epiphany","Fennec","Flock","Galeon","GreenBrowser","iCab","Iceweasel","K-Meleon","Konqueror","Lunascape","Maxthon",{label:"Microsoft Edge",pattern:"(?:Edge|Edg|EdgA|EdgiOS)"},"Midori","Nook Browser","PaleMoon","PhantomJS",
"Raven","Rekonq","RockMelt",{label:"Samsung Internet",pattern:"SamsungBrowser"},"SeaMonkey",{label:"Silk",pattern:"(?:Cloud9|Silk-Accelerated)"},"Sleipnir","SlimBrowser",{label:"SRWare Iron",pattern:"Iron"},"Sunrise","Swiftfox","Vivaldi","Waterfox","WebPositive",{label:"Yandex Browser",pattern:"YaBrowser"},{label:"UC Browser",pattern:"UCBrowser"},"Opera Mini",{label:"Opera Mini",pattern:"OPiOS"},"Opera",{label:"Opera",pattern:"OPR"},"Chromium","Chrome",{label:"Chrome",pattern:"(?:HeadlessChrome)"},
{label:"Chrome Mobile",pattern:"(?:CriOS|CrMo)"},{label:"Firefox",pattern:"(?:Firefox|Minefield)"},{label:"Firefox for iOS",pattern:"FxiOS"},{label:"IE",pattern:"IEMobile"},{label:"IE",pattern:"MSIE"},"Safari"]),K=A([{label:"BlackBerry",pattern:"BB10"},"BlackBerry",{label:"Galaxy S",pattern:"GT-I9000"},{label:"Galaxy S2",pattern:"GT-I9100"},{label:"Galaxy S3",pattern:"GT-I9300"},{label:"Galaxy S4",pattern:"GT-I9500"},{label:"Galaxy S5",pattern:"SM-G900"},{label:"Galaxy S6",pattern:"SM-G920"},{label:"Galaxy S6 Edge",
pattern:"SM-G925"},{label:"Galaxy S7",pattern:"SM-G930"},{label:"Galaxy S7 Edge",pattern:"SM-G935"},"Google TV","Lumia","iPad","iPod","iPhone","Kindle",{label:"Kindle Fire",pattern:"(?:Cloud9|Silk-Accelerated)"},"Nexus","Nook","PlayBook","PlayStation Vita","PlayStation","TouchPad","Transformer",{label:"Wii U",pattern:"WiiU"},"Wii","Xbox One",{label:"Xbox 360",pattern:"Xbox"},"Xoom"]),S=function(T){return f(T,function(P,M,V){return P||(M[K]||M[/^[a-z]+(?: +[a-z]+\b)*/i.exec(K)]||RegExp("\\b"+k(V)+
"(?:\\b|\\w*\\d)","i").exec(d))&&V})}({Apple:{iPad:1,iPhone:1,iPod:1},Alcatel:{},Archos:{},Amazon:{Kindle:1,"Kindle Fire":1},Asus:{Transformer:1},"Barnes & Noble":{Nook:1},BlackBerry:{PlayBook:1},Google:{"Google TV":1,Nexus:1},HP:{TouchPad:1},HTC:{},Huawei:{},Lenovo:{},LG:{},Microsoft:{Xbox:1,"Xbox One":1},Motorola:{Xoom:1},Nintendo:{"Wii U":1,Wii:1},Nokia:{Lumia:1},Oppo:{},Samsung:{"Galaxy S":1,"Galaxy S2":1,"Galaxy S3":1,"Galaxy S4":1},Sony:{PlayStation:1,"PlayStation Vita":1},Xiaomi:{Mi:1,Redmi:1}}),
G=function(T){return f(T,function(P,M){var V=M.pattern||k(M);if(!P&&(P=RegExp("\\b"+V+"(?:/[\\d.]+|[ \\w.]*)","i").exec(d))){var Y=P,ca=M.label||M,da={"10.0":"10","6.4":"10 Technical Preview","6.3":"8.1","6.2":"8","6.1":"Server 2008 R2 / 7","6.0":"Server 2008 / Vista","5.2":"Server 2003 / XP 64-bit","5.1":"XP","5.01":"2000 SP1","5.0":"2000","4.0":"NT","4.90":"ME"};V&&ca&&/^Win/i.test(Y)&&!/^Windows Phone /i.test(Y)&&(da=da[/[\d.]+$/.exec(Y)])&&(Y="Windows "+da);Y=String(Y);V&&ca&&(Y=Y.replace(RegExp(V,
"i"),ca));P=Y=c(Y.replace(/ ce$/i," CE").replace(/\bhpw/i,"web").replace(/\bMacintosh\b/,"Mac OS").replace(/_PowerPC\b/i," OS").replace(/\b(OS X) [^ \d]+/i,"$1").replace(/\bMac (OS X)\b/,"$1").replace(/\/(\d)/," $1").replace(/_/g,".").replace(/(?: BePC|[ .]*fc[ \d.]+)$/i,"").replace(/\bx86\.64\b/gi,"x86_64").replace(/\b(Windows Phone) OS\b/,"$1").replace(/\b(Chrome OS \w+) [\d.]+\b/,"$1").split(" on ")[0])}return P})}(["Windows Phone","KaiOS","Android","CentOS",{label:"Chrome OS",pattern:"CrOS"},
"Debian",{label:"DragonFly BSD",pattern:"DragonFly"},"Fedora","FreeBSD","Gentoo","Haiku","Kubuntu","Linux Mint","OpenBSD","Red Hat","SuSE","Ubuntu","Xubuntu","Cygwin","Symbian OS","hpwOS","webOS ","webOS","Tablet OS","Tizen","Linux","Mac OS X","Macintosh","Mac","Windows 98;","Windows "]);L&&(L=[L]);/\bAndroid\b/.test(G)&&!K&&(m=/\bAndroid[^;]*;(.*?)(?:Build|\) AppleWebKit)\b/i.exec(d))&&(K=t(m[1]).replace(/^[a-z]{2}-[a-z]{2};\s*/i,"")||null);S&&!K?K=A([S]):S&&K&&(K=K.replace(RegExp("^("+k(S)+")[-_.\\s]",
"i"),S+" ").replace(RegExp("^("+k(S)+")[-_.]?(\\w)","i"),S+" $2"));if(m=/\bGoogle TV\b/.exec(K))K=m[0];/\bSimulator\b/i.test(d)&&(K=(K?K+" ":"")+"Simulator");"Opera Mini"==E&&/\bOPiOS\b/.test(d)&&B.push("running in Turbo/Uncompressed mode");"IE"==E&&/\blike iPhone OS\b/.test(d)?(m=b(d.replace(/like iPhone OS/,"")),S=m.manufacturer,K=m.product):/^iP/.test(K)?(E||(E="Safari"),G="iOS"+((m=/ OS ([\d_]+)/i.exec(d))?" "+m[1].replace(/_/g,"."):"")):"Konqueror"==E&&/^Linux\b/i.test(G)?G="Kubuntu":S&&"Google"!=
S&&(/Chrome/.test(E)&&!/\bMobile Safari\b/i.test(d)||/\bVita\b/.test(K))||/\bAndroid\b/.test(G)&&/^Chrome/.test(E)&&/\bVersion\//i.test(d)?(E="Android Browser",G=/\bAndroid\b/.test(G)?G:"Android"):"Silk"==E?(/\bMobi/i.test(d)||(G="Android",B.unshift("desktop mode")),/Accelerated *= *true/i.test(d)&&B.unshift("accelerated")):"UC Browser"==E&&/\bUCWEB\b/.test(d)?B.push("speed mode"):"PaleMoon"==E&&(m=/\bFirefox\/([\d.]+)\b/.exec(d))?B.push("identifying as Firefox "+m[1]):"Firefox"==E&&(m=/\b(Mobile|Tablet|TV)\b/i.exec(d))?
(G||(G="Firefox OS"),K||(K=m[1])):!E||(m=!/\bMinefield\b/i.test(d)&&/\b(?:Firefox|Safari)\b/.exec(E))?(E&&!K&&/[\/,]|^[^(]+?\)/.test(d.slice(d.indexOf(m+"/")+8))&&(E=null),(m=K||S||G)&&(K||S||/\b(?:Android|Symbian OS|Tablet OS|webOS)\b/.test(G))&&(E=/[a-z]+(?: Hat)?/i.exec(/\bAndroid\b/.test(G)?G:m)+" Browser")):"Electron"==E&&(m=(/\bChrome\/([\d.]+)\b/.exec(d)||0)[1])&&B.push("Chromium "+m);z||(z=C(["(?:Cloud9|CriOS|CrMo|Edge|Edg|EdgA|EdgiOS|FxiOS|HeadlessChrome|IEMobile|Iron|Opera ?Mini|OPiOS|OPR|Raven|SamsungBrowser|Silk(?!/[\\d.]+$)|UCBrowser|YaBrowser)",
"Version",k(E),"(?:Firefox|Minefield|NetFront)"]));if(m="iCab"==L&&3<parseFloat(z)&&"WebKit"||/\bOpera\b/.test(E)&&(/\bOPR\b/.test(d)?"Blink":"Presto")||/\b(?:Midori|Nook|Safari)\b/i.test(d)&&!/^(?:Trident|EdgeHTML)$/.test(L)&&"WebKit"||!L&&/\bMSIE\b/i.test(d)&&("Mac OS"==G?"Tasman":"Trident")||"WebKit"==L&&/\bPlayStation\b(?! Vita\b)/i.test(E)&&"NetFront")L=[m];"IE"==E&&(m=(/; *(?:XBLWP|ZuneWP)(\d+)/i.exec(d)||0)[1])?(E+=" Mobile",G="Windows Phone "+(/\+$/.test(m)?m:m+".x"),B.unshift("desktop mode")):
/\bWPDesktop\b/i.test(d)?(E="IE Mobile",G="Windows Phone 8.x",B.unshift("desktop mode"),z||(z=(/\brv:([\d.]+)/.exec(d)||0)[1])):"IE"!=E&&"Trident"==L&&(m=/\brv:([\d.]+)/.exec(d))&&(E&&B.push("identifying as "+E+(z?" "+z:"")),E="IE",z=m[1]);if(Z){if(h(w,"global"))if(N&&(m=N.lang.System,aa=m.getProperty("os.arch"),G=G||m.getProperty("os.name")+" "+m.getProperty("os.version")),H){try{z=w.require("ringo/engine").version.join("."),E="RingoJS"}catch(T){(m=w.system)&&m.global.system==w.system&&(E="Narwhal",
G||(G=m[0].os||null))}E||(E="Rhino")}else"object"==typeof w.process&&!w.process.browser&&(m=w.process)&&("object"==typeof m.versions&&("string"==typeof m.versions.electron?(B.push("Node "+m.versions.node),E="Electron",z=m.versions.electron):"string"==typeof m.versions.nw&&(B.push("Chromium "+z,"Node "+m.versions.node),E="NW.js",z=m.versions.nw)),E||(E="Node.js",aa=m.arch,G=m.platform,z=(z=/[\d.]+/.exec(m.version))?z[0]:null));else l(m=w.runtime)==Q?(E="Adobe AIR",G=m.flash.system.Capabilities.os):
l(m=w.phantom)==O?(E="PhantomJS",z=(m=m.version||null)&&m.major+"."+m.minor+"."+m.patch):"number"==typeof X.documentMode&&(m=/\bTrident\/(\d+)/i.exec(d))?(z=[z,X.documentMode],(m=+m[1]+4)!=z[1]&&(B.push("IE "+z[1]+" mode"),L&&(L[1]=""),z[1]=m),z="IE"==E?String(z[1].toFixed(1)):z[0]):"number"==typeof X.documentMode&&/^(?:Chrome|Firefox)\b/.test(E)&&(B.push("masking as "+E+" "+z),E="IE",z="11.0",L=["Trident"],G="Windows");G=G&&c(G)}z&&(m=/(?:[ab]|dp|pre|[ab]\d+pre)(?:\d+\+?)?$/i.exec(z)||/(?:alpha|beta)(?: ?\d)?/i.exec(d+
";"+(Z&&D.appMinorVersion))||/\bMinefield\b/i.test(d)&&"a")&&(ba=/b/i.test(m)?"beta":"alpha",z=z.replace(RegExp(m+"\\+?$"),"")+("beta"==ba?R:U)+(/\d+\+?/.exec(m)||""));if("Fennec"==E||"Firefox"==E&&/\b(?:Android|Firefox OS|KaiOS)\b/.test(G))E="Firefox Mobile";else if("Maxthon"==E&&z)z=z.replace(/\.[\d.]+/,".x");else if(/\bXbox\b/i.test(K))"Xbox 360"==K&&(G=null),"Xbox 360"==K&&/\bIEMobile\b/.test(d)&&B.unshift("mobile mode");else if(!/^(?:Chrome|IE|Opera)$/.test(E)&&(!E||K||/Browser|Mobi/.test(E))||
"Windows CE"!=G&&!/Mobi/i.test(d))if("IE"==E&&Z)try{null===w.external&&B.unshift("platform preview")}catch(T){B.unshift("embedded")}else(/\bBlackBerry\b/.test(K)||/\bBB10\b/.test(d))&&(m=(RegExp(K.replace(/ +/g," *")+"/([.\\d]+)","i").exec(d)||0)[1]||z)?(m=[m,/BB10/.test(d)],G=(m[1]?(K=null,S="BlackBerry"):"Device Software")+" "+m[0],z=null):this!=g&&"Wii"!=K&&(Z&&J||/Opera/.test(E)&&/\b(?:MSIE|Firefox)\b/i.test(d)||"Firefox"==E&&/\bOS X (?:\d+\.){2,}/.test(G)||"IE"==E&&(G&&!/^Win/.test(G)&&5.5<z||
/\bWindows XP\b/.test(G)&&8<z||8==z&&!/\bTrident\b/.test(d)))&&!x.test(m=b.call(g,d.replace(x,"")+";"))&&m.name&&(m="ing as "+m.name+((m=m.version)?" "+m:""),x.test(E)?(/\bIE\b/.test(m)&&"Mac OS"==G&&(G=null),m="identify"+m):(m="mask"+m,E=W?c(W.replace(/([a-z])([A-Z])/g,"$1 $2")):"Opera",/\bIE\b/.test(m)&&(G=null),Z||(z=null)),L=["Presto"],B.push(m));else E+=" Mobile";if(m=(/\bAppleWebKit\/([\d.]+\+?)/i.exec(d)||0)[1]){m=[parseFloat(m.replace(/\.(\d)$/,".0$1")),m];if("Safari"==E&&"+"==m[1].slice(-1))E=
"WebKit Nightly",ba="alpha",z=m[1].slice(0,-1);else if(z==m[1]||z==(m[2]=(/\bSafari\/([\d.]+\+?)/i.exec(d)||0)[1]))z=null;m[1]=(/\b(?:Headless)?Chrome\/([\d.]+)/i.exec(d)||0)[1];537.36==m[0]&&537.36==m[2]&&28<=parseFloat(m[1])&&"WebKit"==L&&(L=["Blink"]);Z&&(I||m[1])?(L&&(L[1]="like Chrome"),m=m[1]||(m=m[0],530>m?1:532>m?2:532.05>m?3:533>m?4:534.03>m?5:534.07>m?6:534.1>m?7:534.13>m?8:534.16>m?9:534.24>m?10:534.3>m?11:535.01>m?12:535.02>m?"13+":535.07>m?15:535.11>m?16:535.19>m?17:536.05>m?18:536.1>
m?19:537.01>m?20:537.11>m?"21+":537.13>m?23:537.18>m?24:537.24>m?25:537.36>m?26:"Blink"!=L?"27":"28")):(L&&(L[1]="like Safari"),m=(m=m[0],400>m?1:500>m?2:526>m?3:533>m?4:534>m?"4+":535>m?5:537>m?6:538>m?7:601>m?8:602>m?9:604>m?10:606>m?11:608>m?12:"12"));L&&(L[1]+=" "+(m+="number"==typeof m?".x":/[.+]/.test(m)?"":"+"));"Safari"==E&&(!z||45<parseInt(z))?z=m:"Chrome"==E&&/\bHeadlessChrome/i.test(d)&&B.unshift("headless")}"Opera"==E&&(m=/\bzbov|zvav$/.exec(G))?(E+=" ",B.unshift("desktop mode"),"zvav"==
m?(E+="Mini",z=null):E+="Mobile",G=G.replace(RegExp(" *"+m+"$"),"")):"Safari"==E&&/\bChrome\b/.exec(L&&L[1])?(B.unshift("desktop mode"),E="Chrome Mobile",z=null,/\bOS X\b/.test(G)?(S="Apple",G="iOS 4.3+"):G=null):/\bSRWare Iron\b/.test(E)&&!z&&(z=C("Chrome"));z&&0==z.indexOf(m=/[\d.]+$/.exec(G))&&-1<d.indexOf("/"+m+"-")&&(G=t(G.replace(m,"")));G&&-1!=G.indexOf(E)&&!RegExp(E+" OS").test(G)&&(G=G.replace(RegExp(" *"+k(E)+" *"),""));L&&!/\b(?:Avant|Nook)\b/.test(E)&&(/Browser|Lunascape|Maxthon/.test(E)||
"Safari"!=E&&/^iOS/.test(G)&&/\bSafari\b/.test(L[1])||/^(?:Adobe|Arora|Breach|Midori|Opera|Phantom|Rekonq|Rock|Samsung Internet|Sleipnir|SRWare Iron|Vivaldi|Web)/.test(E)&&L[1])&&(m=L[L.length-1])&&B.push(m);B.length&&(B=["("+B.join("; ")+")"]);S&&K&&0>K.indexOf(S)&&B.push("on "+S);K&&B.push((/^on /.test(B[B.length-1])?"":"on ")+K);if(G){var ea=(m=/ ([\d.+]+)$/.exec(G))&&"/"==G.charAt(G.length-m[0].length-1);G={architecture:32,family:m&&!ea?G.replace(m[0],""):G,version:m?m[1]:null,toString:function(){var T=
this.version;return this.family+(T&&!ea?" "+T:"")+(64==this.architecture?" 64-bit":"")}}}(m=/\b(?:AMD|IA|Win|WOW|x86_|x)64\b/i.exec(aa))&&!/\bi686\b/i.test(aa)?(G&&(G.architecture=64,G.family=G.family.replace(RegExp(" *"+m),"")),E&&(/\bWOW64\b/i.test(d)||Z&&/\w(?:86|32)$/.test(D.cpuClass||D.platform)&&!/\bWin64; x64\b/i.test(d))&&B.unshift("32-bit")):G&&/^OS X/.test(G.family)&&"Chrome"==E&&39<=parseFloat(z)&&(G.architecture=64);d||(d=null);w={};w.description=d;w.layout=L&&L[0];w.manufacturer=S;w.name=
E;w.prerelease=ba;w.product=K;w.ua=d;w.version=E&&z;w.os=G||{architecture:null,family:null,version:null,toString:function(){return"null"}};w.parse=b;w.toString=function(){return this.description||""};w.version&&B.unshift(z);w.name&&B.unshift(E);G&&E&&(G!=String(G).split(" ")[0]||G!=E.split(" ")[0]&&!K)&&B.push(K?"("+G+")":"on "+G);B.length&&(w.description=B.join(" "));return w}var p={"function":!0,object:!0},r=p[typeof window]&&window||this,n=p[typeof exports]&&exports;p=p[typeof module]&&module&&
!module.nodeType&&module;var q=n&&p&&"object"==typeof global&&global;!q||q.global!==q&&q.window!==q&&q.self!==q||(r=q);var v=Math.pow(2,53)-1,x=/\bOpera/;q=Object.prototype;var u=q.hasOwnProperty,y=q.toString,F=b();"function"==typeof define&&"object"==typeof define.amd&&define.amd?(r.platform=F,define(function(){return F})):n&&p?g(F,function(d,A){n[A]=d}):r.platform=F}).call(this);
function buildIOSMeta(){for(var a=[{name:"viewport",content:"width=device-width, height=device-height, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no"},{name:"apple-mobile-web-app-capable",content:"yes"},{name:"apple-mobile-web-app-status-bar-style",content:"black"}],e=0;e<a.length;e++){var c=document.createElement("meta");c.name=a[e].name;c.content=a[e].content;var g=window.document.head.querySelector('meta[name="'+c.name+'"]');g&&g.parentNode.removeChild(g);window.document.head.appendChild(c)}}
function hideIOSFullscreenPanel(){jQuery(".xxx-ios-fullscreen-message").css("display","none");jQuery(".xxx-ios-fullscreen-scroll").css("display","none");jQuery(".xxx-game-iframe-full").removeClass("xxx-game-iframe-iphone-se")}function buildIOSFullscreenPanel(){jQuery("body").append('<div class="xxx-ios-fullscreen-message"><div class="xxx-ios-fullscreen-swipe"></div></div><div class="xxx-ios-fullscreen-scroll"></div>')}
function showIOSFullscreenPanel(){jQuery(".xxx-ios-fullscreen-message").css("display","block");jQuery(".xxx-ios-fullscreen-scroll").css("display","block")}
function __iosResize(){window.scrollTo(0,0);console.log(window.devicePixelRatio);console.log(window.innerWidth);console.log(window.innerHeight);if("iPhone"===platform.product)switch(window.devicePixelRatio){case 2:switch(window.innerWidth){case 568:320!==window.innerHeight&&jQuery(".xxx-game-iframe-full").addClass("xxx-game-iframe-iphone-se");break;case 667:375===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;case 808:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();
break;default:hideIOSFullscreenPanel()}break;case 3:switch(window.innerWidth){case 736:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;case 724:375===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;case 808:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;default:hideIOSFullscreenPanel()}break;default:hideIOSFullscreenPanel()}}function iosResize(){__iosResize();setTimeout(function(){__iosResize()},500)}
function iosInIframe(){try{return window.self!==window.top}catch(a){return!0}}$(document).ready(function(){platform&&"iPhone"===platform.product&&"safari"!==platform.name.toLowerCase()&&!iosInIframe()&&(buildIOSFullscreenPanel(),buildIOSMeta())});jQuery(window).resize(function(){platform&&"iPhone"===platform.product&&"safari"!==platform.name.toLowerCase()&&!iosInIframe()&&iosResize()});var s_iScaleFactor=1,s_oCanvasLeft,s_oCanvasTop,s_bIsIphone,s_bFocus=!0;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}function isIpad(){var a=-1!==navigator.userAgent.toLowerCase().indexOf("ipad");return!a&&navigator.userAgent.match(/Mac/)&&navigator.maxTouchPoints&&2<navigator.maxTouchPoints?!0:a}function isMobile(){return isIpad()?!0:jQuery.browser.mobile}
function isIOS(){for(var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");a.length;)if(navigator.platform===a.pop())return s_bIsIphone=!0;return s_bIsIphone=!1}
function getSize(a){var e=a.toLowerCase(),c=window.document,g=c.documentElement;if(void 0===window["inner"+a])a=g["client"+a];else if(window["inner"+a]!=g["client"+a]){var l=c.createElement("body");l.id="vpw-test-b";l.style.cssText="overflow:scroll";var h=c.createElement("div");h.id="vpw-test-d";h.style.cssText="position:absolute;top:-1000px";h.innerHTML="<style>@media("+e+":"+g["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+e+":7px!important}}</style>";l.appendChild(h);g.insertBefore(l,c.head);
a=7==h["offset"+a]?g["client"+a]:window["inner"+a];g.removeChild(l)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a=null!==platform.name&&"safari"===platform.name.toLowerCase()?getIOSWindowHeight():getSize("Height");var e=getSize("Width");s_bFocus&&_checkOrientation(e,a);var c=Math.min(a/CANVAS_HEIGHT,e/CANVAS_WIDTH),g=Math.round(CANVAS_WIDTH*c);c=Math.round(CANVAS_HEIGHT*c);if(c<a){var l=a-c;c+=l;g+=CANVAS_WIDTH/CANVAS_HEIGHT*l}else g<e&&(l=e-g,g+=l,c+=CANVAS_HEIGHT/CANVAS_WIDTH*l);l=a/2-c/2;var h=e/2-g/2,k=CANVAS_WIDTH/g;if(h*k<-EDGEBOARD_X||
l*k<-EDGEBOARD_Y)c=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),e/(CANVAS_WIDTH-2*EDGEBOARD_X)),g=Math.round(CANVAS_WIDTH*c),c=Math.round(CANVAS_HEIGHT*c),l=(a-c)/2,h=(e-g)/2,k=CANVAS_WIDTH/g;s_iOffsetX=-1*h*k;s_iOffsetY=-1*l*k;0<=l&&(s_iOffsetY=0);0<=h&&(s_iOffsetX=0);null!==s_oGame&&s_oGame.refreshButtonPos();null!==s_oMenu&&s_oMenu.refreshButtonPos();null!==s_oLevelMenu&&s_oLevelMenu.refreshButtonPos();s_bMobile?($("#canvas").css("width",g+"px"),$("#canvas").css("height",c+"px")):void 0!==s_oStage&&
(s_oStage.canvas.width=g,s_oStage.canvas.height=c,s_iScaleFactor=Math.min(g/CANVAS_WIDTH,c/CANVAS_HEIGHT),s_oStage.scaleX=s_oStage.scaleY=s_iScaleFactor);0>l||(l=(a-c)/2);$("#canvas").css("top",l+"px");$("#canvas").css("left",h+"px");fullscreenHandler()}}
function _checkOrientation(a,e){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(a>e?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),
s_oMain.stopUpdate()))}function createBitmap(a,e,c){var g=new createjs.Bitmap(a),l=new createjs.Shape;e&&c?l.graphics.beginFill("#fff").drawRect(0,0,e,c):l.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);g.hitArea=l;return g}function createSprite(a,e,c,g,l,h){a=null!==e?new createjs.Sprite(a,e):new createjs.Sprite(a);e=new createjs.Shape;e.graphics.beginFill("#000000").drawRect(-c,-g,l,h);a.hitArea=e;return a}
function randomFloatBetween(a,e,c){"undefined"===typeof c&&(c=2);return parseFloat(Math.min(a+Math.random()*(e-a),e).toFixed(c))}function shuffle(a){for(var e=a.length,c,g;0!==e;)g=Math.floor(Math.random()*e),--e,c=a[e],a[e]=a[g],a[g]=c;return a}function formatTime(a){a/=1E3;var e=Math.floor(a/60);a=parseFloat(a-60*e).toFixed(1);var c="";c=10>e?c+("0"+e+":"):c+(e+":");return 10>a?c+("0"+a):c+a}
function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(a){for(var e=a.length,c,g;0<e;)g=Math.floor(Math.random()*e),e--,c=a[e],a[e]=a[g],a[g]=c;return a}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var e=document.createEvent("MouseEvents");e.initEvent("click",!0,!0);a.dispatchEvent(e)}}};
(function(){function a(c){var g={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};c=c||window.event;c.type in g?document.body.className=g[c.type]:(document.body.className=this[e]?"hidden":"visible","hidden"===document.body.className?(s_oMain.stopUpdate(),s_bFocus=!1):(s_oMain.startUpdate(),s_bFocus=!0))}var e="hidden";e in document?document.addEventListener("visibilitychange",a):(e="mozHidden")in document?document.addEventListener("mozvisibilitychange",
a):(e="webkitHidden")in document?document.addEventListener("webkitvisibilitychange",a):(e="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(a){for(var e=window.location.search.substring(1).split("&"),c=0;c<e.length;c++){var g=e[c].split("=");if(g[0]==a)return g[1]}}function playSound(a,e,c){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(s_aSounds[a].play(),s_aSounds[a].volume(e),s_aSounds[a].loop(c),s_aSounds[a]):null}function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].stop()}function setVolume(a,e){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].volume(e)}
function setMute(a,e){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].mute(e)}function isSoundPlaying(a){return s_aSounds[a].playing()}function saveItem(a,e){s_bStorageAvailable&&localStorage.setItem(a,e)}function getItem(a){return s_bStorageAvailable?localStorage.getItem(a):null}
function fullscreenHandler(){ENABLE_FULLSCREEN&&!1!==screenfull.isEnabled&&(s_bFullscreen=screenfull.isFullscreen,null!==s_oInterface&&s_oInterface.resetFullscreenBut(),null!==s_oMenu&&s_oMenu.resetFullscreenBut(),null!==s_oLevelMenu&&s_oLevelMenu.resetFullscreenBut())}if(screenfull.isEnabled)screenfull.on("change",function(){s_bFullscreen=screenfull.isFullscreen;null!==s_oInterface&&s_oInterface.resetFullscreenBut();null!==s_oMenu&&s_oMenu.resetFullscreenBut();null!==s_oLevelMenu&&s_oLevelMenu.resetFullscreenBut()});
function CSpriteLibrary(){var a={},e,c,g,l,h,k;this.init=function(f,t,b){e={};g=c=0;l=f;h=t;k=b};this.addSprite=function(f,t){if(!a.hasOwnProperty(f)){var b=new Image;a[f]=e[f]={szPath:t,oSprite:b,bLoaded:!1};c++}};this.getSprite=function(f){return a.hasOwnProperty(f)?a[f].oSprite:null};this._onSpritesLoaded=function(){c=0;h.call(k)};this._onSpriteLoaded=function(){l.call(k);++g===c&&this._onSpritesLoaded()};this.loadSprites=function(){for(var f in e)e[f].oSprite.oSpriteLibrary=this,e[f].oSprite.szKey=
f,e[f].oSprite.onload=function(){this.oSpriteLibrary.setLoaded(this.szKey);this.oSpriteLibrary._onSpriteLoaded(this.szKey)},e[f].oSprite.onerror=function(t){var b=t.currentTarget;setTimeout(function(){e[b.szKey].oSprite.src=e[b.szKey].szPath},500)},e[f].oSprite.src=e[f].szPath};this.setLoaded=function(f){a[f].bLoaded=!0};this.isLoaded=function(f){return a[f].bLoaded};this.getNumSprites=function(){return c}}
var CANVAS_WIDTH=1500,CANVAS_HEIGHT=768,EDGEBOARD_X=180,EDGEBOARD_Y=20,FPS=30,FPS_TIME=1E3/FPS,DISABLE_SOUND_MOBILE=!1,FONT_GAME="TradeGothic",STATE_LOADING=0,STATE_MENU=1,STATE_MENU_LEVEL=2,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,ON_BUT_YES_DOWN=6,ON_PLAYER_ARRIVAL=7,ON_PLAYER_FALL=8,ON_OPPONENT_HIDE=9,ON_OPPONENT_CHECK_COLLISION=10,ON_READY_FOR_PLAYER_ARRIVAL=11,ON_BACK_MENU=12,ON_RESTART=13,ON_NEXT_LEVEL=14,ON_BUT_END_TWEEN_X=15,ON_END_COUNTDOWN=
16,PLAYER_ANIM_RUN=0,PLAYER_ANIM_FALL=1,PLAYER_ANIM_ARRIVAL=2,PLAYER_ANIM_LEFT=3,PLAYER_ANIM_LEFT_OUT=4,PLAYER_ANIM_RIGHT=5,PLAYER_ANIM_RIGHT_OUT=6,STARTING_STANDS_SCALE_BONUS=.74,NUM_LEVELS,OPPONENT_FINAL_Y=1200,TIME_OPPONENT_RUN_0=2600,TIME_OPPONENT_RUN_1=800,TIME_OPPONENT_RUN=3E3,HERO_ACCELERATION,HERO_FRICTION,MAX_HERO_SPEED,MIN_START_X=CANVAS_WIDTH/2-50,MAX_START_X=CANVAS_WIDTH/2+50,MIN_ARRIVAL_X=-300,START_X_INTERVAL=MAX_START_X-MIN_START_X,MAX_ARRIVAL_X=CANVAS_WIDTH+300,ARRIVAL_X_INTERVAL=
MAX_ARRIVAL_X-MIN_ARRIVAL_X,MIN_PLAYER_X=180,MAX_PLAYER_X=CANVAS_WIDTH-180,NUM_COLS_PAGE_LEVEL=6,NUM_ROWS_PAGE_LEVEL=2,GAME_NAME="downhill_ski",SOUNDTRACK_VOLUME_IN_GAME=.4,ENABLE_FULLSCREEN,ENABLE_CHECK_ORIENTATION;
function CPreloader(){var a,e,c,g,l,h,k,f,t,b;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.addSprite("200x200","./sprites/200x200.jpg");s_oSpriteLibrary.addSprite("but_start","./sprites/but_start.png");s_oSpriteLibrary.loadSprites();b=new createjs.Container;s_oStage.addChild(b)};this.unload=function(){t.unload();b.removeAllChildren()};this._onImagesLoaded=function(){};
this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var p=new createjs.Shape;p.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);b.addChild(p);p=s_oSpriteLibrary.getSprite("200x200");k=createBitmap(p);k.regX=.5*p.width;k.regY=.5*p.height;k.x=CANVAS_WIDTH/2;k.y=CANVAS_HEIGHT/2-80;b.addChild(k);f=new createjs.Shape;f.graphics.beginFill("rgba(0,0,0,0.01)").drawRoundRect(k.x-100,k.y-100,200,200,10);b.addChild(f);k.mask=f;p=
s_oSpriteLibrary.getSprite("progress_bar");g=createBitmap(p);g.x=CANVAS_WIDTH/2-p.width/2;g.y=CANVAS_HEIGHT/2+70;b.addChild(g);a=p.width;e=p.height;l=new createjs.Shape;l.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(g.x,g.y,1,e);b.addChild(l);g.mask=l;c=new createjs.Text("","30px "+FONT_GAME,"#fff");c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT/2+120;c.textBaseline="alphabetic";c.textAlign="center";b.addChild(c);p=s_oSpriteLibrary.getSprite("but_start");t=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2+
100,p,TEXT_PRELOADER_CONTINUE,"Arial","#000",36,b);t.addEventListener(ON_MOUSE_UP,this._onButStartRelease,this);t.setVisible(!1);h=new createjs.Shape;h.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);b.addChild(h);createjs.Tween.get(h).to({alpha:0},500).call(function(){createjs.Tween.removeTweens(h);b.removeChild(h)})};this._onButStartRelease=function(){s_oMain._allResourcesLoaded()};this.refreshLoader=function(p){c.text=p+"%";100===p&&(s_oMain._allResourcesLoaded(),c.visible=
!1,g.visible=!1);l.graphics.clear();p=Math.floor(p*a/100);l.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(g.x,g.y,p,e)};this._init()}
function CMain(a){var e,c,g=0,l=0,h=STATE_LOADING,k,f,t;this.initContainer=function(){var b=document.getElementById("canvas");s_oStage=new createjs.Stage(b);s_oStage.preventSelection=!1;createjs.Touch.enable(s_oStage,!0);s_bMobile=isMobile();!1===s_bMobile&&s_oStage.enableMouseOver(20);s_iPrevTime=(new Date).getTime();createjs.Ticker.framerate=FPS;createjs.Ticker.on("tick",this._update);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;s_oLevelSettings=
new CLevelSettings;seekAndDestroy()?k=new CPreloader:window.location.href="http://www.codethislab.com/contact-us.html"};this.setLocalStorageLevel=function(b){var p=getItem(GAME_NAME+"_level");if(null===p||p<b)s_iLastLevel=b,saveItem(GAME_NAME+"_level",s_iLastLevel)};this.setLocalStorageScore=function(b,p){saveItem(GAME_NAME+"_score_level_"+p,b)};this.clearLocalStorage=function(){s_iLastLevel=1;if(s_bStorageAvailable)for(var b=0;b<localStorage.length;){var p=localStorage.key(b);-1!==p.indexOf(GAME_NAME)?
localStorage.removeItem(p):b++}};this.getScoreTillLevel=function(b){if(!s_bStorageAvailable)return 0;for(var p=0,r=0;r<b-1;r++)p+=parseInt(getItem(GAME_NAME+"_score_level_"+(r+1)));return p};this.getScoreLevel=function(b){return getItem(GAME_NAME+"_score_level_"+(b+1))};this.getSavedLevel=function(){if(!s_bStorageAvailable)return 1;var b=getItem(GAME_NAME+"_level");return null===b?1:b};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();
e=c=!0};this.soundLoaded=function(){g++;k.refreshLoader(Math.floor(g/l*100))};this._initSounds=function(){Howler.mute(!s_bAudioActive);s_aSoundsInfo=[];s_aSoundsInfo.push({path:"./sounds/",filename:"click",loop:!1,volume:1,ingamename:"click"});s_aSoundsInfo.push({path:"./sounds/",filename:"level_win",loop:!1,volume:1,ingamename:"level_win"});s_aSoundsInfo.push({path:"./sounds/",filename:"game_over",loop:!1,volume:1,ingamename:"game_over"});s_aSoundsInfo.push({path:"./sounds/",filename:"crowd_idle",
loop:!1,volume:1,ingamename:"crowd_idle"});s_aSoundsInfo.push({path:"./sounds/",filename:"skiing_direction",loop:!1,volume:1,ingamename:"skiing_direction"});s_aSoundsInfo.push({path:"./sounds/",filename:"falling",loop:!1,volume:1,ingamename:"falling"});s_aSoundsInfo.push({path:"./sounds/",filename:"countdown",loop:!1,volume:1,ingamename:"countdown"});s_aSoundsInfo.push({path:"./sounds/",filename:"go",loop:!1,volume:1,ingamename:"go"});s_aSoundsInfo.push({path:"./sounds/",filename:"arrival",loop:!1,
volume:1,ingamename:"arrival"});s_aSoundsInfo.push({path:"./sounds/",filename:"soundtrack",loop:!0,volume:1,ingamename:"soundtrack"});l+=s_aSoundsInfo.length;s_aSounds=[];for(var b=0;b<s_aSoundsInfo.length;b++)this.tryToLoadSound(s_aSoundsInfo[b],!1)};this.tryToLoadSound=function(b,p){setTimeout(function(){s_aSounds[b.ingamename]=new Howl({src:[b.path+b.filename+".mp3"],autoplay:!1,preload:!0,loop:b.loop,volume:b.volume,onload:s_oMain.soundLoaded,onloaderror:function(r,n){for(var q=0;q<s_aSoundsInfo.length;q++)if(r===
s_aSounds[s_aSoundsInfo[q].ingamename]._sounds[0]._id){s_oMain.tryToLoadSound(s_aSoundsInfo[q],!0);break}},onplayerror:function(r){for(var n=0;n<s_aSoundsInfo.length;n++)if(r===s_aSounds[s_aSoundsInfo[n].ingamename]._sounds[0]._id){s_aSounds[s_aSoundsInfo[n].ingamename].once("unlock",function(){s_aSounds[s_aSoundsInfo[n].ingamename].play();"soundtrack"===s_aSoundsInfo[n].ingamename&&null!==s_oGame&&setVolume("soundtrack",SOUNDTRACK_VOLUME_IN_GAME)});break}}})},p?200:0)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,
this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("but_next","./sprites/but_next.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("msg_box_wide","./sprites/msg_box_wide.png");s_oSpriteLibrary.addSprite("msg_box_small","./sprites/msg_box_small.png");s_oSpriteLibrary.addSprite("bg_game",
"./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("logo_ctl","./sprites/logo_ctl.png");s_oSpriteLibrary.addSprite("but_credits","./sprites/but_credits.png");s_oSpriteLibrary.addSprite("but_yes","./sprites/but_yes.png");s_oSpriteLibrary.addSprite("but_no","./sprites/but_no.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");s_oSpriteLibrary.addSprite("but_settings","./sprites/but_settings.png");s_oSpriteLibrary.addSprite("but_home","./sprites/but_home.png");s_oSpriteLibrary.addSprite("but_restart",
"./sprites/but_restart.png");s_oSpriteLibrary.addSprite("but_pause","./sprites/but_pause.png");s_oSpriteLibrary.addSprite("key_0","./sprites/key_0.png");s_oSpriteLibrary.addSprite("key_1","./sprites/key_1.png");s_oSpriteLibrary.addSprite("but_left","./sprites/but_left.png");s_oSpriteLibrary.addSprite("but_right","./sprites/but_right.png");s_oSpriteLibrary.addSprite("but_level","./sprites/but_level.png");s_oSpriteLibrary.addSprite("logo_menu","./sprites/logo_menu.png");s_oSpriteLibrary.addSprite("item_0",
"./sprites/item_0.png");s_oSpriteLibrary.addSprite("item_1","./sprites/item_1.png");s_oSpriteLibrary.addSprite("item_2","./sprites/item_2.png");s_oSpriteLibrary.addSprite("score_panel","./sprites/score_panel.png");s_oSpriteLibrary.addSprite("sponsor","./sprites/sponsor.png");s_oSpriteLibrary.addSprite("countdown_0","./sprites/countdown_0.png");s_oSpriteLibrary.addSprite("countdown_1","./sprites/countdown_1.png");s_oSpriteLibrary.addSprite("countdown_2","./sprites/countdown_2.png");s_oSpriteLibrary.addSprite("countdown_3",
"./sprites/countdown_3.png");s_oSpriteLibrary.addSprite("icon_score","./sprites/icon_score.png");s_oSpriteLibrary.addSprite("but_clear_save","./sprites/but_clear_save.png");for(var b=0;87>b;b++)s_oSpriteLibrary.addSprite("field_loop_"+b,"./sprites/field_loop/field_loop_"+b+".png");for(b=0;42>b;b++)s_oSpriteLibrary.addSprite("arrive_"+b,"./sprites/arrive/arrive_"+b+".png");for(b=0;30>b;b++)s_oSpriteLibrary.addSprite("player_falling_"+b,"./sprites/player/falling/player_falling_"+b+".png");for(b=0;70>
b;b++)s_oSpriteLibrary.addSprite("player_arrival_"+b,"./sprites/player/arrival/player_arrival_"+b+".png");for(b=0;19>b;b++)s_oSpriteLibrary.addSprite("player_running_"+b,"./sprites/player/running/player_running_"+b+".png");for(b=0;8>b;b++)s_oSpriteLibrary.addSprite("player_left_"+b,"./sprites/player/turn_left/player_left_"+b+".png"),s_oSpriteLibrary.addSprite("player_right_"+b,"./sprites/player/turn_right/player_right_"+b+".png");for(b=0;7>b;b++)s_oSpriteLibrary.addSprite("player_left_out_"+b,"./sprites/player/turn_left_out/player_left_out_"+
b+".png"),s_oSpriteLibrary.addSprite("player_right_out_"+b,"./sprites/player/turn_right_out/player_right_out_"+b+".png");for(b=0;45>b;b++)s_oSpriteLibrary.addSprite("tutorial_"+b,"./sprites/help/tutorial_"+b+".jpg");l+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){g++;k.refreshLoader(Math.floor(g/l*100))};this._onAllImagesLoaded=function(){};this._allResourcesLoaded=function(){k.unload();try{saveItem("ls_available","ok"),s_iLastLevel=this.getSavedLevel()}catch(b){s_bStorageAvailable=
!1}s_oSoundTrack=playSound("soundtrack",1,!0);s_oMain.gotoMenu()};this.gotoMenu=function(){new CMenu;h=STATE_MENU};this.gotoLevelMenu=function(){f=new CLevelMenu;h=STATE_MENU_LEVEL};this.gotoSelectCar=function(){new CMenuSelectCar;h=STATE_MENU_SELECT_CAR};this.gotoGame=function(){t=new CGame;h=STATE_GAME};this.levelSelected=function(b){s_iLevelSelected=b;f.unload();b>=s_iLastLevel&&(s_iLastLevel=b);s_oMain.gotoGame()};this.stopUpdateNoBlockAndTick=function(){c=!1};this.startUpdateNoBlockAndTick=function(){c=
!0};this.stopUpdateNoBlock=function(){e=!1;createjs.Ticker.paused=!0};this.startUpdateNoBlock=function(){s_iPrevTime=(new Date).getTime();e=!0;createjs.Ticker.paused=!1};this.stopUpdate=function(){e=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||Howler.mute(!0)};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();e=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none");(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)&&
s_bAudioActive&&Howler.mute(!1)};this.isUpdating=function(){return e};this._update=function(b){if(!1!==e){var p=(new Date).getTime();s_iTimeElaps=p-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=p;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);h===STATE_GAME&&c&&t.update();void 0!==s_oStage&&s_oStage.update(b)}};s_oMain=this;HERO_ACCELERATION=a.hero_acceleration;HERO_FRICTION=a.hero_friction;MAX_HERO_SPEED=a.max_hero_speed;ENABLE_FULLSCREEN=a.fullscreen;ENABLE_CHECK_ORIENTATION=
a.check_orientation;this.initContainer()}var s_bMobile,s_bAudioActive=!1,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oSoundTrack=null,s_oDrawLayer,s_oStage,s_oMain=null,s_oSpriteLibrary,s_oLevelSettings,s_iLastLevel,s_iLevelSelected=1,s_bFullscreen=!1,s_bStorageAvailable=!0,s_aSoundsInfo;
function CTextButton(a,e,c,g,l,h,k,f){var t,b,p,r,n,q,v,x,u,y,F;this._init=function(d,A,C,w,B,D,z,I){t=!1;r=[];n=[];F=createBitmap(C);b=C.width;p=C.height;y=new createjs.Text(w,z+"px "+B,D);y.textAlign="center";y.textBaseline="alphabetic";y.lineWidth=.9*b;y.x=C.width/2;y.y=Math.floor(C.height/2)+15;u=new createjs.Container;u.x=d;u.y=A;u.regX=C.width/2;u.regY=C.height/2;s_bMobile||(u.cursor="pointer");u.addChild(F,y);!1!==I&&s_oStage.addChild(u);this._initListener()};this.unload=function(){u.off("mousedown",
q);u.off("pressup",v);s_oStage.removeChild(u)};this.setVisible=function(d){u.visible=d};this.setAlign=function(d){y.textAlign=d};this.enable=function(){t=!1;F.filters=[];F.cache(0,0,b,p)};this.disable=function(){t=!0;var d=(new createjs.ColorMatrix).adjustSaturation(-100).adjustBrightness(40);F.filters=[new createjs.ColorMatrixFilter(d)];F.cache(0,0,b,p)};this._initListener=function(){q=u.on("mousedown",this.buttonDown);v=u.on("pressup",this.buttonRelease)};this.addEventListener=function(d,A,C){r[d]=
A;n[d]=C};this.addEventListenerWithParams=function(d,A,C,w){r[d]=A;n[d]=C;x=w};this.buttonRelease=function(){t||(playSound("click",1,!1),u.scaleX=1,u.scaleY=1,r[ON_MOUSE_UP]&&r[ON_MOUSE_UP].call(n[ON_MOUSE_UP],x))};this.buttonDown=function(){t||(u.scaleX=.9,u.scaleY=.9,r[ON_MOUSE_DOWN]&&r[ON_MOUSE_DOWN].call(n[ON_MOUSE_DOWN]))};this.setPosition=function(d,A){u.x=d;u.y=A};this.changeText=function(d){y.text=d};this.setX=function(d){u.x=d};this.setY=function(d){u.y=d};this.getButtonImage=function(){return u};
this.getX=function(){return u.x};this.getY=function(){return u.y};this.getSprite=function(){return u};this._init(a,e,c,g,l,h,k,f);return this}
function CGfxButton(a,e,c,g){var l,h,k,f,t=[],b,p,r;this._init=function(n,q,v){l=!1;h=1;k=[];f=[];r=createBitmap(v);r.x=n;r.y=q;r.regX=v.width/2;r.regY=v.height/2;r.cursor="pointer";g.addChild(r);this._initListener()};this.unload=function(){r.off("mousedown",b);r.off("pressup",p);g.removeChild(r)};this.setVisible=function(n){r.visible=n};this._initListener=function(){b=r.on("mousedown",this.buttonDown);p=r.on("pressup",this.buttonRelease)};this.addEventListener=function(n,q,v){k[n]=q;f[n]=v};this.addEventListenerWithParams=
function(n,q,v,x){k[n]=q;f[n]=v;t=x};this.enable=function(){l=!1};this.disable=function(){l=!0};this.buttonRelease=function(){l||(playSound("click",1,!1),r.scaleX=h,r.scaleY=h,k[ON_MOUSE_UP]&&k[ON_MOUSE_UP].call(f[ON_MOUSE_UP],t))};this.buttonDown=function(){l||(r.scaleX=.9*h,r.scaleY=.9*h,k[ON_MOUSE_DOWN]&&k[ON_MOUSE_DOWN].call(f[ON_MOUSE_DOWN],t))};this.setPosition=function(n,q){r.x=n;r.y=q};this.setX=function(n){r.x=n};this.setY=function(n){r.y=n};this.setScale=function(n){h=n;r.scaleX=r.scaleY=
n};this.getButtonImage=function(){return r};this.getX=function(){return r.x};this.getY=function(){return r.y};this._init(a,e,c)}
function CSideGfxButton(a,e,c,g,l){var h,k=e,f,t,b,p,r=[],n,q,v;this._init=function(x,u,y,F){h=!1;b=[];p=[];v=createBitmap(F);v.y=y;t=F.width;x?(v.x=-F.width,v.regX=0):(v.x=CANVAS_WIDTH+F.width,v.regX=F.width);f=v.x;v.regY=F.height/2;v.cursor="pointer";l.addChild(v);this._initListener()};this.unload=function(){v.off("mousedown",n);v.off("pressup",q);l.removeChild(v)};this.setVisible=function(x){v.visible=x};this._initListener=function(){n=v.on("mousedown",this.buttonDown);q=v.on("pressup",this.buttonRelease)};
this.addEventListener=function(x,u,y){b[x]=u;p[x]=y};this.addEventListenerWithParams=function(x,u,y,F){b[x]=u;p[x]=y;r=F};this.enable=function(){h=!1};this.disable=function(){h=!0};this.buttonRelease=function(){h||(playSound("click",1,!1),v.scaleX=1,v.scaleY=1,b[ON_MOUSE_UP]&&b[ON_MOUSE_UP].call(p[ON_MOUSE_UP],r))};this.buttonDown=function(){h||(v.scaleX=.9,v.scaleY=.9,b[ON_MOUSE_DOWN]&&b[ON_MOUSE_DOWN].call(p[ON_MOUSE_DOWN],r))};this.setPosition=function(x,u){v.x=x;v.y=u};this.setX=function(x){v.x=
x};this.setY=function(x){v.y=x};this.resetX=function(){v.x=a?-t:CANVAS_WIDTH+t};this.setFinalX=function(x){k=x;f=a?k-t:k+t};this.tweenFinalX=function(){createjs.Tween.get(v).to({x:k},300,createjs.Ease.quartOut).call(function(){b[ON_BUT_END_TWEEN_X]&&b[ON_BUT_END_TWEEN_X].call(p[ON_BUT_END_TWEEN_X])})};this.tweenStartX=function(x){createjs.Tween.get(v).wait(x).to({x:f},300,createjs.Ease.quartOut)};this.getButtonImage=function(){return v};this.getX=function(){return v.x};this.getY=function(){return v.y};
this._init(a,e,c,g);return this}
function CSideToggle(a,e,c,g,l,h,k){var f,t=c,b,p,r,n;this._init=function(q,v,x,u,y){p=[];r=[];v=0;!1===q&&(v=u.width/2);var F=new createjs.SpriteSheet({images:[u],frames:{width:u.width/2,height:u.height,regX:v,regY:u.height/2},animations:{state_true:[0],state_false:[1]}});f=y;n=createSprite(F,"state_"+f,v,u.height/2,u.width/2,u.height);n.x=q?-u.width/2:CANVAS_WIDTH+u.width/2;b=n.x;n.y=x;n.stop();n.cursor="pointer";k.addChild(n);this._initListener()};this.unload=function(){n.off("mousedown",this.buttonDown);
n.off("pressup",this.buttonRelease);k.removeChild(n)};this._initListener=function(){n.on("mousedown",this.buttonDown);n.on("pressup",this.buttonRelease)};this.addEventListener=function(q,v,x){p[q]=v;r[q]=x};this.setActive=function(q){f=q;n.gotoAndStop("state_"+f)};this.buttonRelease=function(){n.scaleX=1;n.scaleY=1;playSound("click",1,!1);f=!f;n.gotoAndStop("state_"+f);p[ON_MOUSE_UP]&&p[ON_MOUSE_UP].call(r[ON_MOUSE_UP],f)};this.buttonDown=function(){n.scaleX=.9;n.scaleY=.9;p[ON_MOUSE_DOWN]&&p[ON_MOUSE_DOWN].call(r[ON_MOUSE_DOWN])};
this.setPosition=function(q,v){n.x=q;n.y=v};this.setY=function(q){n.y=q};this.setFinalX=function(q){t=q};this.tweenFinalX=function(){createjs.Tween.get(n).wait(e).to({x:t},300,createjs.Ease.quartOut).call(function(){p[ON_BUT_END_TWEEN_X]&&p[ON_BUT_END_TWEEN_X].call(r[ON_BUT_END_TWEEN_X])})};this.tweenStartX=function(q){createjs.Tween.get(n).wait(q).to({x:b},300,createjs.Ease.quartOut)};this.getButtonImage=function(){return n};this._init(a,c,g,l,h)}
function CMenu(){var a,e,c,g,l,h,k,f,t,b,p,r,n,q,v,x,u,y=null,F=null;this._init=function(){t=!0;b=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(b);p=new CGfxButton(CANVAS_WIDTH/2+250,CANVAS_HEIGHT/2+90,s_oSpriteLibrary.getSprite("but_play"),s_oStage);p.addEventListener(ON_MOUSE_UP,this._onButPlaySingle,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile){var d=s_oSpriteLibrary.getSprite("audio_icon");k=CANVAS_WIDTH;f=d.height/2+10;r=new CSideToggle(!1,0,k-s_iOffsetX,f+s_iOffsetY,
d,s_bAudioActive,s_oStage);r.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);c=CANVAS_WIDTH;g=f+d.height+10;r.tweenFinalX()}else c=CANVAS_WIDTH,g=d.height/2+10;d=s_oSpriteLibrary.getSprite("but_credits");l=0;h=d.height/2+10;n=new CSideGfxButton(!0,l+s_iOffsetX,h+s_iOffsetY,d,s_oStage);n.addEventListener(ON_MOUSE_UP,this._onButCreditsRelease,this);n.addEventListener(ON_BUT_END_TWEEN_X,this._onButEndTween,this);a=0;e=CANVAS_HEIGHT-d.height/2-10;q=new CSideGfxButton(!0,a+s_iOffsetX,e-s_iOffsetY,
s_oSpriteLibrary.getSprite("but_clear_save"),s_oStage);q.addEventListener(ON_MOUSE_UP,this._onButClearRelease,this);d=window.document;var A=d.documentElement;y=A.requestFullscreen||A.mozRequestFullScreen||A.webkitRequestFullScreen||A.msRequestFullscreen;F=d.exitFullscreen||d.mozCancelFullScreen||d.webkitExitFullscreen||d.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(y=!1);y&&screenfull.isEnabled&&(d=s_oSpriteLibrary.getSprite("but_fullscreen"),x=new CSideToggle(!1,200,c-s_iOffsetX,g+s_iOffsetY,d,s_bFullscreen,
s_oStage),x.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this),x.tweenFinalX());d=createBitmap(s_oSpriteLibrary.getSprite("logo_menu"));d.x=450;d.y=60;s_oStage.addChild(d);u=new CAreYouSurePanel;u.addEventListener(ON_BUT_YES_DOWN,this._onConfirmClear,this);s_bStorageAvailable||new CAlertSavingBox(TEXT_ERR_LS,s_oStage);v=new createjs.Shape;v.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(v);createjs.Tween.get(v).to({alpha:0},400).call(function(){v.visible=
!1});n.tweenFinalX();q.tweenFinalX();setVolume("soundtrack",1)};this.unload=function(){p.unload();n.unload();q.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)r.unload(),r=null;y&&screenfull.isEnabled&&x.unload();s_oStage.removeAllChildren();s_oMenu=null};this.refreshButtonPos=function(){t||(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||r.setPosition(k-s_iOffsetX,s_iOffsetY+f),y&&screenfull.isEnabled&&x.setPosition(c-s_iOffsetX,g+s_iOffsetY),n.setPosition(l+s_iOffsetX,h+s_iOffsetY),q.setPosition(a+
s_iOffsetX,e-s_iOffsetY))};this._onButPlaySingle=function(){s_oMenu.unload();s_oMain.gotoLevelMenu();$(s_oMain).trigger("start_session")};/*this._onButCreditsRelease=function(){new CCreditsPanel};*/this._onButClearRelease=function(){u.show(TEXT_CONFIRM_CLEAR_SAVINGS)};this._onButEndTween=function(){t=!1};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this.resetFullscreenBut=function(){y&&screenfull.isEnabled&&x.setActive(s_bFullscreen)};this._onFullscreenRelease=
function(){s_bFullscreen?F.call(window.document):y.call(window.document.documentElement);sizeHandler()};this._onConfirmClear=function(){s_oMain.clearLocalStorage()};s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(){var a=!1,e,c,g,l,h,k,f,t,b,p,r,n,q,v,x,u,y,F,d,A,C,w,B,D,z,I,Q;this._init=function(){t=s_iLevelSelected;k=s_oMain.getScoreTillLevel(t);y=[{x:10,y:0},{x:-20,y:0},{x:10,y:-10},{x:0,y:20},{x:10,y:-10},{x:-10,y:0},{x:10,y:0},{x:-20,y:0},{x:10,y:-10},{x:0,y:20},{x:10,y:-10},{x:-10,y:0}];var H=s_oSpriteLibrary.getSprite("bg_game");C=new createjs.Container;C.x=H.width/2;C.y=CANVAS_HEIGHT/2;C.regX=H.width/2;C.regY=424;s_oStage.addChild(C);F=createBitmap(H);F.x=-50;C.addChild(F);d=new CField(-50,
220,C);d.addEventListener(ON_READY_FOR_PLAYER_ARRIVAL,this.playArrival,this);w=new createjs.Container;C.addChild(w);D=new CPlayer(CANVAS_WIDTH/2,850,w);D.addEventListener(ON_PLAYER_ARRIVAL,this._onWinLevel,this);D.addEventListener(ON_PLAYER_FALL,this._onEndLevel,this);B=new CCountdownController(CANVAS_WIDTH/2,CANVAS_HEIGHT/2-150,s_oStage);B.addEventListener(ON_END_COUNTDOWN,this.startRace,this);A=new CInterface(k);this.reset();z=new CHelpPanel;z.show();I=new CEndPanel;I.addEventListener(ON_RESTART,
this.restart,this);I.addEventListener(ON_BACK_MENU,this.onExit,this);Q=new CNextLevelPanel;Q.addEventListener(ON_RESTART,this.restart,this);Q.addEventListener(ON_BACK_MENU,this.onExit,this);Q.addEventListener(ON_NEXT_LEVEL,this._onNextLevel,this)};this.unload=function(){a=!1;A.unload();s_oStage.removeAllChildren();s_oGame=null};this.reset=function(){e=h=g=c=l=!1;b=f=0;x=[];p=s_oLevelSettings.getEnemiesSpawn(t);r=s_oLevelSettings.getStartingEnemySpawn(t);s_oLevelSettings.getEnemySpawnNumber(t);k=s_oMain.getScoreTillLevel(t);
n=parseFloat((-334/p).toFixed(2));F.y=0;D.reset();A.reset(k,t);B.reset();d.reset();setVolume("soundtrack",SOUNDTRACK_VOLUME_IN_GAME);$(s_oMain).trigger("start_level",t)};this.restart=function(){$(s_oMain).trigger("restart_level",t);for(var H=0;H<x.length;H++)x[H].unload();this.reset();this.startCountdown()};this.refreshButtonPos=function(){A.refreshButtonPos()};this.onKeyDown=function(H){if(!a||h||D.getCurAnim()===PLAYER_ANIM_ARRIVAL)return H.preventDefault(),!1;H||(H=window.event);switch(H.keyCode){case 37:c=
!0;D.moveLeft(!0);break;case 39:g=!0,D.moveRight(!0)}H.preventDefault();return!1};this.onKeyUp=function(H){if(!a||h||D.getCurAnim()===PLAYER_ANIM_ARRIVAL)return H.preventDefault(),!1;H||(H=window.event);g=c=!1;switch(H.keyCode){case 37:D.moveLeft(!1);break;case 39:D.moveRight(!1)}H.preventDefault();return!1};this.moveLeft=function(H){!a||H&&c||h||D.getCurAnim()===PLAYER_ANIM_ARRIVAL||(c=H,D.moveLeft(H))};this.moveRight=function(H){!a||H&&g||h||D.getCurAnim()===PLAYER_ANIM_ARRIVAL||(g=H,D.moveRight(H))};
this.startCountdown=function(){D.show();d.show();B.start();a=!0};this.startRace=function(){this._spawnEnemy()};this._createSpawnArray=function(){u=[];for(var H=ARRIVAL_X_INTERVAL/5,N=MIN_ARRIVAL_X,O=0;6>O;O++)u.push(N),N+=H;u=shuffle(u)};this.onExitFromHelp=function(){this.startCountdown()};this._spawnEnemy=function(){e=!0;if(0!==p){p--;var H=!1;0===p?l=H=!0:2===p&&d.prepareSponsorsForStop();var N=Math.floor(3*Math.random());if(.3<Math.random())var O=D.getX()-CANVAS_WIDTH/2+D.getX();else this._createSpawnArray(),
O=u.pop();H=new COpponent(H,(O-MIN_ARRIVAL_X)/ARRIVAL_X_INTERVAL*START_X_INTERVAL+MIN_START_X,500,O,N,w);H.addEventListener(ON_OPPONENT_HIDE,this.checkArrival,this);H.addEventListener(ON_OPPONENT_CHECK_COLLISION,this.checkCollision,this);x.push(H);H=F.y+n;(new createjs.Tween.get(F)).to({y:H},r)}};this.checkArrival=function(H){H&&!h&&(d.readyForArrival(),playSound("crowd_idle",1,!1))};this.checkCollision=function(H,N){if(!h){var O=D.getRect(),U=Math.abs(H.x-O.x);if(O.intersects(H)){h=!0;q=0;var R=
this;v=setInterval(function(){R.tremble()},20);D.changeAnim(PLAYER_ANIM_FALL)}else this.refreshScore(Math.floor(U/200));w.swapChildren(N,D.getContainer())}};this.tremble=function(){var H=y[q];C.x+=H.x;C.y+=H.y;q++;q===y.length&&(q=0,clearInterval(v))};this.refreshScore=function(H){f+=H;k+=H;A.refreshScore(k)};this.playArrival=function(){g=c=!1;D.changeAnim(PLAYER_ANIM_ARRIVAL)};this._manageOpponentDepth=function(){w.sortChildren(function(H,N,O){return H.y>N.y?1:H.y<N.y?-1:0})};this._onEndLevel=function(){$(s_oMain).trigger("end_level",
t);d.stopAnim();for(var H=0;H<x.length;H++)x[H].stopUpdate();setTimeout(function(){I.show(0,TEXT_GAME_OVER)},500)};this._onWinLevel=function(){$(s_oMain).trigger("end_level",t);$(s_oMain).trigger("save_score",k);t===NUM_LEVELS?setTimeout(function(){I.show(k,TEXT_CONGRATS)},500):(s_oMain.setLocalStorageLevel(t+1),setTimeout(function(){Q.show(f,k,t)},500));s_oMain.setLocalStorageScore(f,t)};this._onNextLevel=function(){t++;this.reset();this.startCountdown()};this.onExit=function(){this.unload();s_oMain.gotoMenu();
$(s_oMain).trigger("show_interlevel_ad");$(s_oMain).trigger("end_session");$(s_oMain).trigger("share_event",k)};this.getPlayerX=function(){return D.getX()};this.update=function(){z.isVisible()&&z.update();if(!1!==a){c&&-4<C.rotation?C.rotation-=.5:g&&4>C.rotation?C.rotation+=.5:!1===c&&!1===g&&(0<C.rotation?C.rotation-=.5:0>C.rotation&&(C.rotation+=.5));D.update();d.update();this._manageOpponentDepth();for(var H=0;H<x.length;H++)x[H].update();!h&&e&&(b+=s_iTimeElaps,!l&&b>r&&(b=0,this._spawnEnemy()))}};
s_oGame=this;this._init()}var s_oGame=null;
function CInterface(a){var e,c,g,l,h,k,f,t,b,p,r,n,q,v,x,u,y,F,d,A,C,w,B,D,z,I,Q=null,H=null,N,O,U,R;this._init=function(X){if(s_bMobile){var J=s_oSpriteLibrary.getSprite("but_left");h=J.width/2+150;k=CANVAS_HEIGHT-J.height/2-50;z=new CGfxButton(h,k,J,s_oStage);z.addEventListener(ON_MOUSE_DOWN,this._onLeftDown,this);z.addEventListener(ON_MOUSE_UP,this._onLeftUp,this);J=s_oSpriteLibrary.getSprite("but_right");g=CANVAS_WIDTH-J.width/2-150;l=CANVAS_HEIGHT-J.height/2-50;I=new CGfxButton(g,l,J,s_oStage);
I.addEventListener(ON_MOUSE_DOWN,this._onRightDown,this);I.addEventListener(ON_MOUSE_UP,this._onRightUp,this)}else document.onkeydown=s_oGame.onKeyDown,document.onkeyup=s_oGame.onKeyUp;J=s_oSpriteLibrary.getSprite("but_settings");var W=CANVAS_WIDTH,m=J.height/2+10;N=new CGUIExpandible(W,m,J,s_oStage);J=s_oSpriteLibrary.getSprite("but_exit");q=W;v=m+J.height+10;C=new CSideGfxButton(!1,q-s_iOffsetX,v,J,s_oStage);C.addEventListener(ON_MOUSE_UP,this._onExit,this);J=s_oSpriteLibrary.getSprite("but_pause");
e=CANVAS_WIDTH;c=v+J.height+10;D=new CSideGfxButton(!1,e-s_iOffsetX,c,J,s_oStage);D.addEventListener(ON_MOUSE_UP,this._onPause,this);W=100;!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(J=s_oSpriteLibrary.getSprite("audio_icon"),x=CANVAS_WIDTH,u=c+J.height+10,w=new CSideToggle(!1,W,x-s_iOffsetX,u,J,s_bAudioActive,s_oStage),w.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this),f=CANVAS_WIDTH,t=u+J.height+10,W+=100):(f=CANVAS_WIDTH,t=c+J.height+10);J=window.document;m=J.documentElement;Q=m.requestFullscreen||
m.mozRequestFullScreen||m.webkitRequestFullScreen||m.msRequestFullscreen;H=J.exitFullscreen||J.mozCancelFullScreen||J.webkitExitFullscreen||J.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(Q=!1);Q&&screenfull.isEnabled&&(J=s_oSpriteLibrary.getSprite("but_fullscreen"),B=new CSideToggle(!1,W,f-s_iOffsetX,t+s_iOffsetY,J,s_bFullscreen,s_oStage),B.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));N.addButton(C);N.addButton(D);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||N.addButton(w);Q&&screenfull.isEnabled&&
N.addButton(B);J=s_oSpriteLibrary.getSprite("score_panel");r=0;n=10;U=new createjs.Container;U.x=r;U.y=n;s_oStage.addChild(U);W=createBitmap(J);U.addChild(W);d=new CTLText(U,10,0,J.width-10,J.height,40,"left","#ffffff",FONT_GAME,1.1,0,0,TEXT_SCORE,!0,!0,!0,!1);F=new CTLText(U,d.getX()+d.getBounds().width+20,d.getY(),140,J.height,40,"left","#ffffff",FONT_GAME,1.1,0,0,X,!0,!0,!0,!1);b=0;p=CANVAS_HEIGHT-J.height-10;R=new createjs.Container;R.x=b;R.y=p;s_oStage.addChild(R);X=createBitmap(J);R.addChild(X);
A=new CTLText(R,10,0,J.width-10,J.height,40,"left","#ffffff",FONT_GAME,1.1,0,0,TEXT_LEVEL+" "+s_iLevelSelected,!0,!0,!0,!1);O=new CAreYouSurePanel;O.addEventListener(ON_BUT_YES_DOWN,this._onExitYes,this);y=new CRollingScore;this.refreshButtonPos()};this.unload=function(){C.unload();C=null;N.unload();O.unload();!1===DISABLE_SOUND_MOBILE&&(w.unload(),w=null);Q&&screenfull.isEnabled&&B.unload();s_bMobile?(z.unload(),I.unload()):(document.onkeydown=null,document.onkeyup=null);s_oStage.removeAllChildren();
s_oInterface=null};this.reset=function(X,J){F.refreshText(X);A.refreshText(TEXT_LEVEL+" "+J)};this.refreshButtonPos=function(){U.x=r+s_iOffsetX;U.y=n+s_iOffsetY;R.x=b+s_iOffsetX;R.y=p-s_iOffsetY;N.refreshPos();N.isExpanded()?(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||w.setPosition(x-s_iOffsetX,s_iOffsetY+u),Q&&screenfull.isEnabled&&B.setPosition(f-s_iOffsetX,t+s_iOffsetY),C.setPosition(q-s_iOffsetX,v+s_iOffsetY),D.setPosition(e-s_iOffsetX,c+s_iOffsetY)):(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||
w.setY(s_iOffsetY+u),Q&&screenfull.isEnabled&&B.setY(t+s_iOffsetY),C.setY(v+s_iOffsetY),D.setY(c+s_iOffsetY),C.resetX(),D.resetX());s_bMobile&&(z.setPosition(h+s_iOffsetX,k-s_iOffsetY),I.setPosition(g-s_iOffsetX,l-s_iOffsetY))};this.refreshScore=function(X){y.rolling(F,null,X)};this._onLeftDown=function(){s_oGame.moveLeft(!0)};this._onRightDown=function(){s_oGame.moveRight(!0)};this._onLeftUp=function(){s_oGame.moveLeft(!1)};this._onRightUp=function(){s_oGame.moveRight(!1)};this._onExit=function(){O.show(TEXT_ARE_SURE)};
this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onPause=function(){s_oMain.isUpdating()?s_oMain.stopUpdateNoBlock():s_oMain.startUpdateNoBlock()};this.resetFullscreenBut=function(){Q&&screenfull.isEnabled&&B.setActive(s_bFullscreen)};this._onFullscreenRelease=function(){!1===s_oMain.isUpdating()&&s_oMain.startUpdateNoBlock();s_bFullscreen?H.call(window.document):Q.call(window.document.documentElement);sizeHandler()};this._onExitYes=function(){s_oGame.onExit()};
s_oInterface=this;this._init(a);return this}var s_oInterface=null;
function CHelpPanel(){var a,e,c,g,l,h,k,f,t,b=this;this._init=function(){t=new createjs.Container;t.visible=!1;s_oStage.addChild(t);g=new createjs.Shape;g.graphics.beginFill("rgba(0,0,0,0.7)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);c=g.on("click",function(){});t.addChild(g);var p=s_oSpriteLibrary.getSprite("msg_box_wide"),r=createBitmap(p);r.regX=p.width/2;r.regY=p.height/2;r.x=CANVAS_WIDTH/2;r.y=CANVAS_HEIGHT/2;t.addChild(r);p=[];for(r=0;45>r;r++)p.push(s_oSpriteLibrary.getSprite("tutorial_"+r));
r=p[0].width;var n=p[0].height;p=new createjs.SpriteSheet({images:p,framerate:15,frames:{width:r,height:n,regX:r/2},animations:{start:0,anim:[0,p.length-1]}});k=createSprite(p,"start",r/2,0,r,n);k.x=CANVAS_WIDTH/2;k.y=130;t.addChild(k);e=[];s_bMobile?(p=s_oSpriteLibrary.getSprite("but_left"),r=s_oSpriteLibrary.getSprite("but_right")):(p=s_oSpriteLibrary.getSprite("key_0"),r=s_oSpriteLibrary.getSprite("key_1"));l=createBitmap(p);l.regX=p.width/2;l.regY=p.height/2;l.x=CANVAS_WIDTH/2-240;l.y=CANVAS_HEIGHT/
2+40;t.addChild(l);e.push(l);h=createBitmap(r);h.regX=r.width/2;h.regY=r.height/2;h.x=CANVAS_WIDTH/2+240;h.y=CANVAS_HEIGHT/2+40;t.addChild(h);e.push(h);f=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2+180,s_oSpriteLibrary.getSprite("but_next"),t);f.addEventListener(ON_MOUSE_UP,this._onStart,this)};this.unload=function(){g.off("click",c)};this.show=function(){a=0;h.scaleX=h.scaleY=.9;k.gotoAndPlay("anim");t.alpha=0;t.visible=!0;createjs.Tween.get(t).to({alpha:1},500)};this.hide=function(){createjs.Tween.get(t).to({alpha:0},
500,createjs.Ease.cubicOut).call(function(){t.visible=!1})};this._attachPlayer=function(p,r,n,q){n=[];for(var v=0;18>v;v++)n.push(s_oSpriteLibrary.getSprite("player_running_"+v));v=n[0].width;var x=n[0].height;n=new createjs.SpriteSheet({images:n,frames:{width:v,height:x,regX:v/2,regY:x},animations:{start:0,anim:[0,n.length-1,q]}});n=createSprite(n,"start",v/2,x,v,x);n.scaleX=n.scaleY=.7;n.x=p;n.y=r;t.addChild(n);return n};this._toggleKeyAnims=function(){.9===h.scaleX?(h.scaleX=h.scaleY=1,l.scaleX=
l.scaleY=.9):(l.scaleX=l.scaleY=1,h.scaleX=h.scaleY=.9)};this._onStart=function(){f.disable();b.hide();s_oGame.onExitFromHelp()};this.isVisible=function(){return t.visible};this.update=function(){a+=s_iTimeElaps;1500<a&&(a=0,this._toggleKeyAnims())};this._init()}
function CLevelSettings(){var a,e,c;this._init=function(){a=[20,30,40,50,60,70,80,80,90,90,100,100];e=[1300,1100,900,800,800,700,700,600,600,500,500,400];c=[1,1,1,2,2,2,2,3,3,2,2,2];NUM_LEVELS=a.length};this.getEnemiesSpawn=function(g){return a[g-1]};this.getStartingEnemySpawn=function(g){return e[g-1]};this.getEnemySpawnNumber=function(g){return c[g-1]};this._init()}
function CLevelMenu(){var a,e,c,g,l,h,k,f,t,b,p,r,n,q,v,x,u,y,F,d,A=null,C=null;this._init=function(){k=!0;f=0;F=new createjs.Container;s_oStage.addChild(F);var w=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));F.addChild(w);v=new createjs.Shape;v.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);v.alpha=.5;F.addChild(v);x=new createjs.Container;x.x=CANVAS_WIDTH/2;F.addChild(x);q=s_oSpriteLibrary.getSprite("msg_box_wide");w=createBitmap(q);x.addChild(w);new CTLText(x,0,40,q.width,
90,80,"center","#ffffff",FONT_GAME,1,20,5,TEXT_SELECT_LEVEL,!0,!0,!0,!1);var B=s_oSpriteLibrary.getSprite("but_exit");l=CANVAS_WIDTH;h=B.height/2+10;u=new CSideGfxButton(!1,l-s_iOffsetX,h+s_iOffsetY,B,s_oStage);u.addEventListener(ON_MOUSE_UP,this._onExit,this);u.addEventListener(ON_BUT_END_TWEEN_X,this._onButEndTween,this);x.regX=q.width/2;x.regY=q.height/2;t=-q.height/2;b=B.height;w=100;!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(B=s_oSpriteLibrary.getSprite("audio_icon"),c=CANVAS_WIDTH,g=h+B.height+
10,y=new CSideToggle(!1,w,c-s_iOffsetX,g+s_iOffsetY,B,s_bAudioActive,s_oStage),y.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this),a=CANVAS_WIDTH,e=g+B.height+10,w+=100,y.tweenFinalX()):(a=CANVAS_WIDTH,e=h+B.height+10);B=window.document;var D=B.documentElement;A=D.requestFullscreen||D.mozRequestFullScreen||D.webkitRequestFullScreen||D.msRequestFullscreen;C=B.exitFullscreen||B.mozCancelFullScreen||B.webkitExitFullscreen||B.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(A=!1);A&&screenfull.isEnabled&&
(B=s_oSpriteLibrary.getSprite("but_fullscreen"),d=new CSideToggle(!1,w,a-s_iOffsetX,e+s_iOffsetY,B,s_bFullscreen,s_oStage),d.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this),d.tweenFinalX());this._checkBoundLimits();r=[];w=Math.floor((q.width-100)/NUM_COLS_PAGE_LEVEL)/2;for(D=B=0;D<NUM_COLS_PAGE_LEVEL;D++)r.push(B),B+=2*w;n=[];this._createNewLevelPage(0,NUM_LEVELS);this.refreshButtonPos();v.alpha=0;x.y=t;F.visible=!0;u.tweenFinalX();createjs.Tween.get(v).to({alpha:.7},500);createjs.Tween.get(x).to({y:CANVAS_HEIGHT/
2},500,createjs.Ease.quartOut)};this.unload=function(){for(var w=0;w<p.length;w++)p[w].unload();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||y.unload();A&&screenfull.isEnabled&&d.unload();u.unload();s_oStage.removeAllChildren();s_oLevelMenu=null};this.refreshButtonPos=function(){k||(u.setPosition(l-s_iOffsetX,h+s_iOffsetY),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||y.setPosition(c-s_iOffsetX,s_iOffsetY+g),A&&screenfull.isEnabled&&d.setPosition(a-s_iOffsetX,e+s_iOffsetY))};this._checkBoundLimits=function(){for(var w=
s_oSpriteLibrary.getSprite("but_level"),B=0,D=CANVAS_HEIGHT-2*EDGEBOARD_Y-2*b,z=0;B<D;)B+=w.height+20,z++;NUM_ROWS_PAGE_LEVEL>z&&(NUM_ROWS_PAGE_LEVEL=z);D=B=0;z=CANVAS_WIDTH-2*EDGEBOARD_X;for(w=s_oSpriteLibrary.getSprite("but_level");D<z;)D+=w.width/2+5,B++;NUM_COLS_PAGE_LEVEL>B&&(NUM_COLS_PAGE_LEVEL=B)};this._createNewLevelPage=function(w,B){var D=new createjs.Container;x.addChild(D);n.push(D);p=[];for(var z=0,I=0,Q=1,H=!1,N=s_oSpriteLibrary.getSprite("but_level"),O=w;O<B;O++){var U=null;if(O+1>
s_iLastLevel)var R=!1;else R=!0,U=s_oMain.getScoreLevel(O);R=new CLevelBut(r[z]+N.width/4,I+N.height/2,O+1,U,N,R,D);R.addEventListenerWithParams(ON_MOUSE_UP,this._onButLevelRelease,this,O);p.push(R);z++;if(z===r.length&&(z=0,I+=N.height+70,Q++,Q>NUM_ROWS_PAGE_LEVEL&&O!==B-1)){H=!0;break}}D.x=q.width/2;D.y=q.height/2;D.regX=D.getBounds().width/2;D.regY=D.getBounds().height/2;H&&this._createNewLevelPage(O+1,B)};this._onRight=function(){n[f].visible=!1;f++;f>=n.length&&(f=0);n[f].visible=!0};this._onLeft=
function(){n[f].visible=!1;f--;0>f&&(f=n.length-1);n[f].visible=!0};this._onButLevelRelease=function(w){s_oLevelMenu.unload();s_oMain.levelSelected(w+1)};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this.resetFullscreenBut=function(){A&&screenfull.isEnabled&&d.setActive(s_bFullscreen)};this._onFullscreenRelease=function(){s_bFullscreen?C.call(window.document):A.call(window.document.documentElement);sizeHandler()};this._onButEndTween=function(){k=!1};this._onExit=
function(){s_oLevelMenu.unload();s_oMain.gotoMenu()};s_oLevelMenu=this;this._init()}var s_oLevelMenu=null;
function CLevelBut(a,e,c,g,l,h,k){var f,t,b,p=[],r=[],n,q,v,x;this._init=function(y,F,d,A,C,w){t=[];b=[];x=new createjs.Container;u.addChild(x);var B=new createjs.SpriteSheet({images:[C],frames:{width:C.width/2,height:C.height,regX:C.width/2/2,regY:C.height/2},animations:{state_true:[0],state_false:[1]}});f=w;v=createSprite(B,"state_"+f,C.width/2/2,C.height/2,C.width/2,C.height);v.mouseEnabled=w;v.x=y;v.y=F;v.stop();s_bMobile||(x.cursor="pointer");x.addChild(v);p.push(v);n=new createjs.Text(d,"50px "+
FONT_GAME,"#fff");n.x=y;n.y=F+2;n.textAlign="center";n.textBaseline="alphabetic";x.addChild(n);d=s_oSpriteLibrary.getSprite("icon_score");d=createBitmap(d);d.x=y-40;d.y=F+22;x.addChild(d);null===A&&(A=0);q=new createjs.Text(A,"20px "+FONT_GAME,"#fff");q.x=y+40;q.y=F+37;q.textAlign="right";q.textBaseline="alphabetic";x.addChild(q);w||(n.color="#b4b4b4");this._initListener()};this.unload=function(){x.off("mousedown",this.buttonDown);x.off("pressup",this.buttonRelease);x.removeChild(v)};this._initListener=
function(){x.on("mousedown",this.buttonDown);x.on("pressup",this.buttonRelease)};this.viewBut=function(y){x.addChild(y)};this.addEventListener=function(y,F,d){t[y]=F;b[y]=d};this.addEventListenerWithParams=function(y,F,d,A){t[y]=F;b[y]=d;r=A};this.ifClickable=function(){return!0===x.mouseEnabled?1:0};this.setActive=function(y,F){f=F;p[y].gotoAndStop("state_"+f);p[y].mouseEnabled=!0;n.color=f?"#00397a":"#b4b4b4"};this.buttonRelease=function(){f&&(playSound("click",1,!1),t[ON_MOUSE_UP]&&t[ON_MOUSE_UP].call(b[ON_MOUSE_UP],
r))};this.buttonDown=function(){t[ON_MOUSE_DOWN]&&t[ON_MOUSE_DOWN].call(b[ON_MOUSE_DOWN],r)};this.setPosition=function(y,F){x.x=y;x.y=F};this.setVisible=function(y){x.visible=y};var u=k;this._init(a,e,c,g,l,h,k)}
function CCreditsPanel(){var a,e,c,g,l,h,k;this._init=function(){k=new createjs.Container;s_oStage.addChild(k);var f=new createjs.Shape;f.graphics.beginFill("rgba(0,0,0,0.7)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);k.addChild(f);f=s_oSpriteLibrary.getSprite("msg_box_small");a=createBitmap(f);a.regX=f.width/2;a.regY=f.height/2;a.x=CANVAS_WIDTH/2;a.y=CANVAS_HEIGHT/2;k.addChild(a);l=new createjs.Shape;l.graphics.beginFill("#0f0f0f").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);l.alpha=.01;l.on("click",
this._onLogoButRelease);k.addChild(l);f=s_oSpriteLibrary.getSprite("but_no");c=new CGfxButton(980,246,f,k);c.setScale(.6);c.addEventListener(ON_MOUSE_UP,this.unload,this);g=new createjs.Text(TEXT_CREDITS_DEVELOPED,"26px "+FONT_GAME,"#fff");g.textAlign="center";g.textBaseline="alphabetic";g.x=CANVAS_WIDTH/2;g.y=330;k.addChild(g);f=s_oSpriteLibrary.getSprite("logo_ctl");e=createBitmap(f);e.regX=f.width/2;e.regY=f.height/2;e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT/2;k.addChild(e);h=new createjs.Text("www.codethislab.com",
"26px "+FONT_GAME,"#fff");h.textAlign="center";h.textBaseline="alphabetic";h.x=CANVAS_WIDTH/2;h.y=450;k.addChild(h)};this.unload=function(){l.off("click",this._onLogoButRelease);c.unload();c=null;s_oStage.removeChild(k)};this._onLogoButRelease=function(){window.open("http://www.codethislab.com/index.php?&l=en","_blank")};this._init()}
function CAlertSavingBox(a,e){var c,g;this._init=function(k){g=new createjs.Container;h.addChild(g);var f=new createjs.Shape;f.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);f.alpha=.5;f.on("click",function(){});g.addChild(f);f=s_oSpriteLibrary.getSprite("msg_box_small");var t=createBitmap(f);t.x=.5*CANVAS_WIDTH;t.y=.5*CANVAS_HEIGHT;t.regX=.5*f.width;t.regY=.5*f.height;g.addChild(t);new CTLText(g,CANVAS_WIDTH/2-f.width/2,CANVAS_HEIGHT/2-90,f.width,200,40,"center","#ffffff",FONT_GAME,
1,20,10,k,!0,!0,!0,!1);c=new CSideGfxButton(!1,1024,250,s_oSpriteLibrary.getSprite("but_exit"),g);c.addEventListener(ON_MOUSE_UP,this._onButOk,this);c.setX(1024)};this._onButOk=function(){l.unload()};this.unload=function(){c.unload();h.removeChild(g)};var l=this;var h=e;this._init(a)}
function CAreYouSurePanel(){var a,e,c,g,l,h,k,f,t=this;this._init=function(){a=[];e=[];k=new createjs.Container;k.visible=!1;s_oStage.addChild(k);f=new createjs.Shape;f.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);f.alpha=.5;f.on("click",function(){});k.addChild(f);var b=s_oSpriteLibrary.getSprite("msg_box_small");c=createBitmap(b);c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT/2;c.regX=.5*b.width;c.regY=.5*b.height;k.addChild(c);g=new CTLText(k,CANVAS_WIDTH/2-b.width/2,CANVAS_HEIGHT/
2-b.height/2,b.width,200,70,"center","#ffffff",FONT_GAME,1,40,10,TEXT_ARE_SURE,!0,!0,!0,!1);l=new CGfxButton(CANVAS_WIDTH/2+150,.5*CANVAS_HEIGHT+70,s_oSpriteLibrary.getSprite("but_yes"),k);l.addEventListener(ON_MOUSE_UP,this._onButYes,this);h=new CGfxButton(CANVAS_WIDTH/2-150,.5*CANVAS_HEIGHT+70,s_oSpriteLibrary.getSprite("but_no"),k);h.addEventListener(ON_MOUSE_UP,this._onButNo,this)};this.addEventListener=function(b,p,r){a[b]=p;e[b]=r};this.show=function(b){g.refreshText(b);k.alpha=0;k.visible=
!0;createjs.Tween.get(k).to({alpha:1},300,createjs.Ease.quartOut).call(function(){s_oMain.stopUpdateNoBlock()})};this.hide=function(){s_oMain.startUpdateNoBlock();createjs.Tween.get(k).to({alpha:0},500,createjs.Ease.quartOut).call(function(){k.visible=!1})};this.unload=function(){h.unload();l.unload()};this._onButYes=function(){t.hide();a[ON_BUT_YES_DOWN]&&a[ON_BUT_YES_DOWN].call(e[ON_BUT_YES_DOWN])};this._onButNo=function(){t.hide()};this._init()}
function CGUIExpandible(a,e,c,g){var l,h,k,f,t;this._init=function(p,r,n,q){h=[];f=new createjs.Container;f.x=p;f.y=r;q.addChild(f);t=new createjs.Container;f.addChild(t);l=!1;k=new CSideGfxButton(!1,0,0,n,t);k.addEventListener(ON_MOUSE_UP,this._onMenu,this);k.tweenFinalX()};this.unload=function(){k.unload();g.removeChild(f)};this.refreshPos=function(){f.x=a-s_iOffsetX;f.y=e+s_iOffsetY;for(var p=0;p<h.length;p++)h[p].setFinalX(f.x)};this.addButton=function(p){h.push(p)};this._onMenu=function(){(l=
!l)?b._expand():b._collapse()};this._expand=function(){for(var p=0;p<h.length;p++)h[p].tweenFinalX()};this._collapse=function(){for(var p=100*h.length,r=0;r<h.length;r++)h[r].tweenStartX(p),p-=100};this.isExpanded=function(){return l};var b=this;this._init(a,e,c,g)}
function CField(a,e,c){var g,l,h,k,f,t,b,p,r,n,q,v,x=this;this._init=function(y,F){p=[];r=[];n=new createjs.Container;n.x=y;n.y=F;u.addChild(n);for(var d=[],A=0;87>A;A++){var C=s_oSpriteLibrary.getSprite("field_loop_"+A);d.push(C)}C={images:d,framerate:20,frames:{width:1600,height:631},animations:{start:0,anim:[0,29,"anim"],arrival:[30,86,"end"],end:86}};C=new createjs.SpriteSheet(C);v=createSprite(C,"start",0,0,1600,631);v.on("animationend",this._onAnimEnd,this);v.on("change",this._onAnimChange,
this);n.addChild(v);d=[];for(A=0;42>A;A++)C=s_oSpriteLibrary.getSprite("arrive_"+A),d.push(C);t=[];b=[];for(A=0;2>A;A++)C=new CSponsor(510,256,!0,n),t.push(C),C=new CSponsor(1070,256,!1,n),b.push(C);C={images:d,framerate:15,frames:{width:1600,height:539},animations:{start:0,anim:[0,41,"end"],end:42}};C=new createjs.SpriteSheet(C);q=createSprite(C,"start",0,0,1600,539);q.visible=!1;q.y=-F-18;n.addChild(q)};this.reset=function(){l=!1;for(var y=0;y<t.length;y++)t[y].reset(),b[y].reset();h=q.visible=
!1;f=k=0};this.show=function(){g=!1;v.gotoAndPlay("anim");h=!0};this.hide=function(){v.gotoAndStop("start");n.visible=!1};this.addEventListener=function(y,F,d){p[y]=F;r[y]=d};this.readyForArrival=function(){g=!0};this._playArrival=function(){v.framerate=15;v.gotoAndPlay("arrival")};this.stopAnim=function(){v.stop();this.stopSponsors()};this.prepareSponsorsForStop=function(){for(var y=0;y<t.length;y++)t[y].readyForRemoval(),b[y].readyForRemoval()};this.stopSponsors=function(){for(var y=0;y<t.length;y++)t[y].stopTween(),
b[y].stopTween()};this._onAnimEnd=function(y){"anim"===y.currentTarget.currentAnimation&&g&&(g=!1,x._playArrival())};this._onAnimChange=function(y){"arrival"===y.currentTarget.currentAnimation&&(75<=y.currentTarget.currentFrame&&!l?(l=!0,p[ON_READY_FOR_PLAYER_ARRIVAL]&&p[ON_READY_FOR_PLAYER_ARRIVAL].call(r[ON_READY_FOR_PLAYER_ARRIVAL])):31<=y.currentTarget.currentFrame&&!1===q.visible&&(q.gotoAndPlay("anim"),q.visible=!0))};this.update=function(){h&&(k+=s_iTimeElaps,2E3<k&&(k=0,t[f].startAnim(),b[f].startAnim(),
f++,f===t.length&&(h=!1)))};var u=c;this._init(a,e)}
function CPlayer(a,e,c){var g=!1,l=!1,h=!1,k,f,t,b,p,r,n,q,v,x,u,y,F,d,A;this._init=function(w,B){b=w;p=B;q=0;r=HERO_ACCELERATION;n=MAX_HERO_SPEED;F=[];d=[];A=new createjs.Container;A.x=w;A.y=B;C.addChild(A);y=[];y[PLAYER_ANIM_RUN]=19;y[PLAYER_ANIM_FALL]=30;y[PLAYER_ANIM_ARRIVAL]=70;y[PLAYER_ANIM_LEFT]=8;y[PLAYER_ANIM_RIGHT]=8;y[PLAYER_ANIM_LEFT_OUT]=7;y[PLAYER_ANIM_RIGHT_OUT]=7;u=[];u[PLAYER_ANIM_RUN]=[];for(var D=0;D<y[PLAYER_ANIM_RUN];D++){var z=s_oSpriteLibrary.getSprite("player_running_"+D),
I=createBitmap(z);I.visible=!1;I.regX=z.width/2;I.regY=z.height;A.addChild(I);u[PLAYER_ANIM_RUN].push(I)}u[PLAYER_ANIM_FALL]=[];for(D=0;D<y[PLAYER_ANIM_FALL];D++)z=s_oSpriteLibrary.getSprite("player_falling_"+D),I=createBitmap(z),I.visible=!1,I.regX=z.width/2,I.regY=z.height,A.addChild(I),u[PLAYER_ANIM_FALL].push(I);u[PLAYER_ANIM_ARRIVAL]=[];for(D=0;D<y[PLAYER_ANIM_ARRIVAL];D++)z=s_oSpriteLibrary.getSprite("player_arrival_"+D),I=createBitmap(z),I.visible=!1,I.regX=z.width/2,I.regY=z.height,A.addChild(I),
u[PLAYER_ANIM_ARRIVAL].push(I);u[PLAYER_ANIM_LEFT]=[];for(D=0;D<y[PLAYER_ANIM_LEFT];D++)z=s_oSpriteLibrary.getSprite("player_left_"+D),I=createBitmap(z),I.visible=!1,I.regX=z.width/2,I.regY=z.height,A.addChild(I),u[PLAYER_ANIM_LEFT].push(I);u[PLAYER_ANIM_RIGHT]=[];for(D=0;D<y[PLAYER_ANIM_RIGHT];D++)z=s_oSpriteLibrary.getSprite("player_right_"+D),I=createBitmap(z),I.visible=!1,I.regX=z.width/2,I.regY=z.height,A.addChild(I),u[PLAYER_ANIM_RIGHT].push(I);u[PLAYER_ANIM_LEFT_OUT]=[];for(D=0;D<y[PLAYER_ANIM_LEFT_OUT];D++)z=
s_oSpriteLibrary.getSprite("player_left_out_"+D),I=createBitmap(z),I.visible=!1,I.regX=z.width/2,I.regY=z.height,A.addChild(I),u[PLAYER_ANIM_LEFT_OUT].push(I);u[PLAYER_ANIM_RIGHT_OUT]=[];for(D=0;D<y[PLAYER_ANIM_RIGHT_OUT];D++)z=s_oSpriteLibrary.getSprite("player_right_out_"+D),I=createBitmap(z),I.visible=!1,I.regX=z.width/2,I.regY=z.height,A.addChild(I),u[PLAYER_ANIM_RIGHT_OUT].push(I);k=PLAYER_ANIM_RUN};this.addEventListener=function(w,B,D){F[w]=B;d[w]=D};this.show=function(){f=y[k];u[k][0].visible=
!0;t=0;A.visible=!0;v=A.getBounds().width-400;x=A.getBounds().height-200;g=!0};this.hide=function(){g=!1;A.visible=!1};this.reset=function(){h=l=g=!1;q=0;r=HERO_ACCELERATION;n=MAX_HERO_SPEED;A.alpha=1;A.x=b;A.y=p;for(var w=0;w<y[PLAYER_ANIM_RUN];w++)u[PLAYER_ANIM_RUN][w].visible=!1;for(w=0;w<y[PLAYER_ANIM_FALL];w++)u[PLAYER_ANIM_FALL][w].visible=!1;for(w=0;w<y[PLAYER_ANIM_ARRIVAL];w++)u[PLAYER_ANIM_ARRIVAL][w].visible=!1;for(w=0;w<y[PLAYER_ANIM_LEFT];w++)u[PLAYER_ANIM_LEFT][w].visible=!1;for(w=0;w<
y[PLAYER_ANIM_RIGHT];w++)u[PLAYER_ANIM_RIGHT][w].visible=!1;k=PLAYER_ANIM_RUN};this.changeAnim=function(w){w!==k&&(g=!1,u[k][t].visible=!1,k=w,u[k][0].visible=!0,t=0,f=y[k],g=!0,w===PLAYER_ANIM_LEFT||w===PLAYER_ANIM_RIGHT?playSound("skiing_direction",1,!1):w===PLAYER_ANIM_FALL?playSound("falling",1,!1):w===PLAYER_ANIM_ARRIVAL&&playSound("arrival",1,!1))};this.playToFrame=function(w){u[k][t].visible=!1;t=w;u[k][t].visible=!0};this.nextFrame=function(){u[k][t].visible=!1;t++;u[k][t].visible=!0};this.moveLeft=
function(w){A.x===MIN_PLAYER_X?(l=!1,q=0):(w?this.changeAnim(PLAYER_ANIM_LEFT):this.changeAnim(PLAYER_ANIM_LEFT_OUT),l=w)};this.moveRight=function(w){A.x===MAX_PLAYER_X?(h=!1,q=0):(w?this.changeAnim(PLAYER_ANIM_RIGHT):this.changeAnim(PLAYER_ANIM_RIGHT_OUT),h=w)};this.setAcceleration=function(w,B){r=w;n=B};this.setY=function(w){A.y=w};this.getRect=function(){return new createjs.Rectangle(A.x-v/2,A.y-x,v,x)};this.getCurAnim=function(){return k};this.getX=function(){return A.x};this.getContainer=function(){return A};
this._updateMove=function(){k!==PLAYER_ANIM_FALL&&k!==PLAYER_ANIM_ARRIVAL&&(l&&(q-=r),h&&(q+=r),A.x+=q,q*=HERO_FRICTION,q>n&&(q=n),q<-n&&(q=-n),.1>Math.abs(q)&&(q=0),A.x+q>=MAX_PLAYER_X?(A.x=MAX_PLAYER_X,k===PLAYER_ANIM_RIGHT&&this.changeAnim(PLAYER_ANIM_RIGHT_OUT)):A.x-q<=MIN_PLAYER_X&&(A.x=MIN_PLAYER_X,k===PLAYER_ANIM_LEFT&&this.changeAnim(PLAYER_ANIM_LEFT_OUT)),A.y=p-Math.abs((A.x-CANVAS_WIDTH/2)/10),A.setTransform(A.x,A.y,1,1,0,-(A.x-CANVAS_WIDTH/2)/50))};this.update=function(){if(!1!==g)if(this._updateMove(),
t===f-1)switch(k){case PLAYER_ANIM_RUN:this.playToFrame(0);break;case PLAYER_ANIM_FALL:this.hide();F[ON_PLAYER_FALL]&&F[ON_PLAYER_FALL].call(d[ON_PLAYER_FALL]);break;case PLAYER_ANIM_ARRIVAL:g=!1;F[ON_PLAYER_ARRIVAL]&&F[ON_PLAYER_ARRIVAL].call(d[ON_PLAYER_ARRIVAL]);break;case PLAYER_ANIM_LEFT_OUT:case PLAYER_ANIM_RIGHT_OUT:this.changeAnim(PLAYER_ANIM_RUN)}else this.nextFrame()};var C=c;this._init(a,e)}
function COpponent(a,e,c,g,l,h){var k,f,t=!1,b,p,r,n,q,v,x=this,u;x=this;this._init=function(F,d,A){r=[];n=[];k=F;f=d;u=new createjs.Container;u.x=F;u.y=d;u.scaleX=u.scaleY=.05;y.addChild(u);F=s_oSpriteLibrary.getSprite("item_"+A);b=F.width;p=F.height;v=createBitmap(F);u.addChild(v);u.regX=b/2;u.regY=p;this.show()};this.addEventListener=function(F,d,A){r[F]=d;n[F]=A};this.reset=function(){u.x=k;u.y=f;u.scaleX=u.scaleY=.05;v.visible=!1};this.unload=function(){y.removeChild(u)};this.show=function(){t=
!1;this.reset();x._startRun()};this._startRun=function(){v.visible=!0;u.alpha=0;u.visible=!0;(new createjs.Tween.get(u)).to({alpha:1},1200);q=(new createjs.Tween.get(u)).to({x:g},TIME_OPPONENT_RUN,createjs.Ease.quintIn);(new createjs.Tween.get(u)).to({y:OPPONENT_FINAL_Y},TIME_OPPONENT_RUN,createjs.Ease.quintIn);(new createjs.Tween.get(u)).to({scaleX:1.2,scaleY:1.2},TIME_OPPONENT_RUN,createjs.Ease.quartIn).call(function(){x.hide()});t=!0};this.hide=function(){t=!1;u.visible=!1;r[ON_OPPONENT_HIDE]&&
r[ON_OPPONENT_HIDE].call(n[ON_OPPONENT_HIDE],a)};this.stopUpdate=function(){createjs.Tween.removeTweens(u);t=!1};this.update=function(){if(t&&q.position>.8*TIME_OPPONENT_RUN&&(t=!1,r[ON_OPPONENT_CHECK_COLLISION])){var F=new createjs.Rectangle(u.x-b*u.scaleX/2,u.y-p*u.scaleY,b*u.scaleX,p*u.scaleY);r[ON_OPPONENT_CHECK_COLLISION].call(n[ON_OPPONENT_CHECK_COLLISION],F,u)}};var y=h;this._init(e,c,l)}
function CEndPanel(){var a,e,c,g,l,h,k,f,t,b,p,r,n=this;this._init=function(){c=[];g=[];p=new createjs.Container;p.visible=!1;s_oStage.addChild(p);h=new createjs.Shape;h.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);h.alpha=0;l=h.on("click",function(){});p.addChild(h);r=new createjs.Container;r.x=CANVAS_WIDTH/2;p.addChild(r);var q=s_oSpriteLibrary.getSprite("msg_box_small"),v=createBitmap(q);r.addChild(v);k=new CTLText(r,0,0,q.width,120,80,"center","#ffffff",FONT_GAME,1,40,
10,"",!0,!0,!0,!1);f=new CTLText(r,0,q.height/2-60,q.width,80,80,"center","#ffffff",FONT_GAME,1,40,10,"",!0,!0,!0,!1);t=new CGfxButton(q.width/2-200,q.height/2+110,s_oSpriteLibrary.getSprite("but_home"),r);t.addEventListener(ON_MOUSE_UP,this._onHome,this);b=new CGfxButton(q.width/2+200,q.height/2+110,s_oSpriteLibrary.getSprite("but_restart"),r);b.addEventListener(ON_MOUSE_UP,this._onRestart,this);a=-q.height/2;r.regX=q.width/2;r.regY=q.height/2};this.unload=function(){t.unload();b.unload();h.off("click",
l)};this.addEventListener=function(q,v,x){c[q]=v;g[q]=x};this.show=function(q,v){setVolume("soundtrack",0);(v===TEXT_CONGRATS?playSound("level_win",1,!1):playSound("game_over",1,!1)).on("end",function(){setVolume("soundtrack",1)});k.refreshText(v);0<q?f.refreshText(TEXT_SCORE+": "+q):f.refreshText("");h.alpha=0;r.y=a;p.visible=!0;createjs.Tween.get(h).to({alpha:.7},500);createjs.Tween.get(r).wait(400).to({y:CANVAS_HEIGHT/2},500,createjs.Ease.quartOut).call(function(){n.enableButtons()})};this.hide=
function(){createjs.Tween.get(r).to({y:a},500,createjs.Ease.quartOut).call(function(){p.visible=!1;c[e]&&c[e].call(g[e])})};this.enableButtons=function(){t.enable();b.enable()};this.disableButtons=function(){t.disable();b.disable()};this._onHome=function(){n.disableButtons();e=ON_BACK_MENU;n.hide()};this._onRestart=function(){n.disableButtons();$(s_oMain).trigger("show_interlevel_ad");e=ON_RESTART;n.hide()};this._init()}
function CNextLevelPanel(){var a,e,c,g,l,h,k,f,t,b,p,r,n,q,v=this;this._init=function(){c=[];g=[];n=new createjs.Container;n.visible=!1;s_oStage.addChild(n);h=new createjs.Shape;h.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);h.alpha=0;l=h.on("click",function(){});n.addChild(h);q=new createjs.Container;q.x=CANVAS_WIDTH/2;n.addChild(q);var x=s_oSpriteLibrary.getSprite("msg_box_small"),u=createBitmap(x);q.addChild(u);f=new CTLText(q,0,0,x.width,120,80,"center","#ffffff",FONT_GAME,
1,40,10,"",!0,!0,!0,!1);k=new CTLText(q,0,x.height/2-70,x.width,60,80,"center","#ffffff",FONT_GAME,1,40,10,"",!0,!0,!0,!1);t=new CTLText(q,0,x.height/2,x.width,60,80,"center","#ffffff",FONT_GAME,1,40,10,"",!0,!0,!0,!1);b=new CGfxButton(x.width/2-200,x.height/2+110,s_oSpriteLibrary.getSprite("but_home"),q);b.addEventListener(ON_MOUSE_UP,this._onHome,this);p=new CGfxButton(x.width/2,x.height/2+110,s_oSpriteLibrary.getSprite("but_restart"),q);p.addEventListener(ON_MOUSE_UP,this._onRestart,this);r=new CGfxButton(x.width/
2+200,x.height/2+110,s_oSpriteLibrary.getSprite("but_next"),q);r.addEventListener(ON_MOUSE_UP,this._onNext,this);a=-x.height/2;q.regX=x.width/2;q.regY=x.height/2};this.unload=function(){b.unload();p.unload();h.off("click",l)};this.addEventListener=function(x,u,y){c[x]=u;g[x]=y};this.show=function(x,u,y){setVolume("soundtrack",0);playSound("level_win",1,!1).on("end",function(){setVolume("soundtrack",1)});f.refreshText(TEXT_LEVEL+" "+y+" "+TEXT_CLEARED);k.refreshText(TEXT_LEVEL_SCORE+": "+x);t.refreshText(TEXT_SCORE+
": "+u);h.alpha=0;q.y=a;n.visible=!0;createjs.Tween.get(h).to({alpha:.7},500);createjs.Tween.get(q).wait(400).to({y:CANVAS_HEIGHT/2},500,createjs.Ease.quartOut).call(function(){v.enableButtons()})};this.hide=function(){createjs.Tween.get(q).to({y:a},500,createjs.Ease.quartOut).call(function(){n.visible=!1;c[e]&&c[e].call(g[e])})};this.enableButtons=function(){b.enable();r.enable();p.enable()};this.disableButtons=function(){b.disable();r.disable();p.disable()};this._onHome=function(){v.disableButtons();
e=ON_BACK_MENU;v.hide()};this._onRestart=function(){v.disableButtons();$(s_oMain).trigger("show_interlevel_ad");e=ON_RESTART;v.hide()};this._onNext=function(){v.disableButtons();$(s_oMain).trigger("show_interlevel_ad");e=ON_NEXT_LEVEL;v.hide()};this._init()}var MS_ROLLING_SCORE=400;
function CRollingScore(){var a=null,e=null;this.rolling=function(c,g,l){a=createjs.Tween.get(c.getText()).to({text:l},MS_ROLLING_SCORE,createjs.Ease.cubicOut).call(function(){createjs.Tween.removeTweens(a);c.setColor("#fff")}).addEventListener("change",function(){c.refreshText(Math.floor(c.getString()))});null!==g&&(e=createjs.Tween.get(g.getText()).to({text:l},MS_ROLLING_SCORE,createjs.Ease.cubicOut).call(function(){createjs.Tween.removeTweens(e)}).addEventListener("change",function(){g.refreshText(Math.floor(g.getString()))}))};
return this}
function CScoreText(a,e,c,g){var l;this._init=function(h,k,f){l=new createjs.Text("+"+h," 80px "+FONT_GAME,"#fff");l.textAlign="center";l.x=k;l.y=f;l.alpha=0;l.shadow=new createjs.Shadow("#000",1,1,1);g.addChild(l);var t=this;createjs.Tween.get(l).to({alpha:1},200,createjs.Ease.quadIn).call(function(){t.moveUp()})};this.moveUp=function(){var h=l.y-400,k=this;createjs.Tween.get(l).to({y:h},1500,createjs.Ease.sineIn).call(function(){k.unload()});createjs.Tween.get(l).wait(800).to({alpha:0},500)};this.unload=
function(){g.removeChild(l)};this._init(a,e,c)}
function CCountdownController(a,e,c){var g,l,h,k,f,t=this;this._init=function(b,p){h=[];k=[];f=new createjs.Container;f.x=b;f.y=p;c.addChild(f);l=[];for(var r=0;4>r;r++){var n=s_oSpriteLibrary.getSprite("countdown_"+(4-r-1)),q=createBitmap(n);q.regX=n.width/2;q.regY=n.height/2;f.addChild(q);l.push(q)}};this.addEventListener=function(b,p,r){h[b]=p;k[b]=r};this.reset=function(){for(var b=0;b<l.length;b++)l[b].scaleX=l[b].scaleY=.1,l[b].alpha=0};this.start=function(){g=0;this._playAnim()};this._playAnim=
function(){0<g&&createjs.Tween.get(l[g-1]).to({alpha:0},300,createjs.Ease.cubicOut);g===l.length?h[ON_END_COUNTDOWN]&&h[ON_END_COUNTDOWN].call(k[ON_END_COUNTDOWN]):(createjs.Tween.get(l[g]).to({alpha:1},300,createjs.Ease.cubicOut).call(function(){g===l.length-1?playSound("go",1,!1):playSound("countdown",1,!1)}),createjs.Tween.get(l[g]).to({scaleX:1,scaleY:1},1E3,createjs.Ease.quartOut).call(function(){g++;t._playAnim()}))};this._init(a,e)}
function CSponsor(a,e,c,g){var l,h,k,f,t,b,p=this;this._init=function(r,n){l=!1;h=r;k=n;b=new createjs.Container;b.visible=!1;b.x=r;b.y=n;b.scaleX=b.scaleY=.1;g.addChild(b);var q=s_oSpriteLibrary.getSprite("sponsor"),v=createBitmap(q);v.regX=q.width/2;v.regY=q.height/2;b.addChild(v);c?(v.rotation=5,f=-q.width/2):(v.rotation=-5,f=CANVAS_WIDTH+q.width/2);t=n-40};this.reset=function(){b.visible=!1;this._resetAnim()};this.startAnim=function(){b.visible=!0;b.alpha=0;(new createjs.Tween.get(b)).to({alpha:1},
1E3);(new createjs.Tween.get(b)).to({x:f,y:t},TIME_OPPONENT_RUN,createjs.Ease.quintIn).call(function(){l?b.visible=!1:(p._resetAnim(),p.startAnim())});(new createjs.Tween.get(b)).to({scaleX:1,scaleY:1},TIME_OPPONENT_RUN,createjs.Ease.quartIn)};this._resetAnim=function(){l=!1;b.x=h;b.y=k;b.scaleX=b.scaleY=.1};this.readyForRemoval=function(){l=!0};this.stopTween=function(){createjs.Tween.removeTweens(b)};this._init(a,e)}
CTLText.prototype={constructor:CTLText,__autofit:function(){if(this._bFitText){for(var a=this._iFontSize;(this._oText.getBounds().height>this._iHeight-2*this._iPaddingV||this._oText.getBounds().width>this._iWidth-2*this._iPaddingH)&&!(a--,this._oText.font=a+"px "+this._szFont,this._oText.lineHeight=Math.round(a*this._fLineHeightFactor),this.__updateY(),this.__verticalAlign(),8>a););this._iFontSize=a}},__verticalAlign:function(){if(this._bVerticalAlign){var a=this._oText.getBounds().height;this._oText.y-=
(a-this._iHeight)/2+this._iPaddingV}},__updateY:function(){this._oText.y=this._y+this._iPaddingV;switch(this._oText.textBaseline){case "middle":this._oText.y+=this._oText.lineHeight/2+(this._iFontSize*this._fLineHeightFactor-this._iFontSize)}},__createText:function(a){this._bDebug&&(this._oDebugShape=new createjs.Shape,this._oDebugShape.graphics.beginFill("rgba(255,0,0,0.5)").drawRect(this._x,this._y,this._iWidth,this._iHeight),this._oContainer.addChild(this._oDebugShape));this._oText=new createjs.Text(a,
this._iFontSize+"px "+this._szFont,this._szColor);this._oText.textBaseline="middle";this._oText.lineHeight=Math.round(this._iFontSize*this._fLineHeightFactor);this._oText.textAlign=this._szAlign;this._oText.lineWidth=this._bMultiline?this._iWidth-2*this._iPaddingH:null;switch(this._szAlign){case "center":this._oText.x=this._x+this._iWidth/2;break;case "left":this._oText.x=this._x+this._iPaddingH;break;case "right":this._oText.x=this._x+this._iWidth-this._iPaddingH}this._oContainer.addChild(this._oText);
this.refreshText(a)},setVerticalAlign:function(a){this._bVerticalAlign=a},setOutline:function(a){null!==this._oText&&(this._oText.outline=a)},setShadow:function(a,e,c,g){null!==this._oText&&(this._oText.shadow=new createjs.Shadow(a,e,c,g))},setColor:function(a){this._oText.color=a},setAlpha:function(a){this._oText.alpha=a},removeTweens:function(){createjs.Tween.removeTweens(this._oText)},getText:function(){return this._oText},getString:function(){return this._oText.text},getX:function(){return this._x},
getY:function(){return this._y},getBounds:function(){return this._oText.getBounds()},getFontSize:function(){return this._iFontSize},refreshText:function(a){""===a&&(a=" ");null===this._oText&&this.__createText(a);this._oText.text=a;this._oText.font=this._iFontSize+"px "+this._szFont;this._oText.lineHeight=Math.round(this._iFontSize*this._fLineHeightFactor);this.__autofit();this.__updateY();this.__verticalAlign()}};
function CTLText(a,e,c,g,l,h,k,f,t,b,p,r,n,q,v,x,u){this._oContainer=a;this._x=e;this._y=c;this._iWidth=g;this._iHeight=l;this._bMultiline=x;this._iFontSize=h;this._szAlign=k;this._szColor=f;this._szFont=t;this._iPaddingH=p;this._iPaddingV=r;this._bVerticalAlign=v;this._bFitText=q;this._bDebug=u;this._oDebugShape=null;this._fLineHeightFactor=b;this._oText=null;n&&this.__createText(n)}
function extractHostname(a){a=-1<a.indexOf("://")?a.split("/")[2]:a.split("/")[0];a=a.split(":")[0];return a=a.split("?")[0]}function extractRootDomain(a){a=extractHostname(a);var e=a.split("."),c=e.length;2<c&&(a=e[c-2]+"."+e[c-1]);return a}
var getClosestTop=function(){var a=window,e=!1;try{for(;a.parent.document!==a.document;)if(a.parent.document)a=a.parent;else{e=!0;break}}catch(c){e=!0}return{topFrame:a,err:e}},getBestPageUrl=function(a){var e=a.topFrame,c="";if(a.err)try{try{c=window.top.location.href}catch(l){var g=window.location.ancestorOrigins;c=g[g.length-1]}}catch(l){c=e.document.referrer}else c=e.location.href;return c},TOPFRAMEOBJ=getClosestTop(),PAGE_URL=getBestPageUrl(TOPFRAMEOBJ);
function seekAndDestroy(){for(var a=extractRootDomain(PAGE_URL),e=[String.fromCharCode(99,111,100,101,116,104,105,115,108,97,98,46,99,111,109),String.fromCharCode(101,110,118,97,116,111,46,99,111,109),String.fromCharCode(99,111,100,101,99,97,110,121,111,110,46,99,111,109),String.fromCharCode(99,111,100,101,99,97,110,121,111,110,46,110,101,116)],c=0;c<e.length;c++)if(e[c]===a)return!0;return!0};