/*
 Platform.js <https://mths.be/platform>
 Copyright 2014-2018 Benjamin Tan <https://bnjmnt4n.now.sh/>
 Copyright 2011-2013 John-David Dalton
 Available under MIT license <https://mths.be/mit>
*/
(function(){function a(f){f=String(f);return f.charAt(0).toUpperCase()+f.slice(1)}function c(f,x){var B=-1,h=f?f.length:0;if("number"==typeof h&&-1<h&&h<=A)for(;++B<h;)x(f[B],B,f);else d(f,x)}function b(f){f=String(f).replace(/^ +| +$/g,"");return/^(?:webOS|i(?:OS|P))/.test(f)?f:a(f)}function d(f,x){for(var B in f)E.call(f,B)&&x(f[B],B,f)}function l(f){return null==f?a(f):D.call(f).slice(8,-1)}function p(f,x){var B=null!=f?typeof f[x]:"number";return!/^(?:boolean|number|string|undefined)$/.test(B)&&
("object"==B?!!f[x]:!0)}function r(f){return String(f).replace(/([ -])(?!$)/g,"$1?")}function g(f,x){var B=null;c(f,function(h,u){B=x(B,h,u,f)});return B}function m(f){function x(L){return g(L,function(K,J){var M=J.pattern||r(J);!K&&(K=RegExp("\\b"+M+" *\\d+[.\\w_]*","i").exec(f)||RegExp("\\b"+M+" *\\w+-[\\w]*","i").exec(f)||RegExp("\\b"+M+"(?:; *(?:[a-z]+[_-])?[a-z]+\\d+|[^ ();-]*)","i").exec(f))&&((K=String(J.label&&!RegExp(M,"i").test(J.label)?J.label:K).split("/"))[1]&&!/[\d.]+/.test(K[0])&&(K[0]+=
" "+K[1]),J=J.label||J,K=b(K[0].replace(RegExp(M,"i"),J).replace(RegExp("; *(?:"+J+"[_-])?","i")," ").replace(RegExp("("+J+")[-_.]?(\\w)","i"),"$1 $2")));return K})}function B(L){return g(L,function(K,J){return K||(RegExp(J+"(?:-[\\d.]+/|(?: for [\\w-]+)?[ /-])([\\d.]+[^ ();/_-]*)","i").exec(f)||0)[1]||null})}var h=k,u=f&&"object"==typeof f&&"String"!=l(f);u&&(h=f,f=null);var F=h.navigator||{},t=F.userAgent||"";f||(f=t);var C=u?!!F.likeChrome:/\bChrome\b/.test(f)&&!/internal|\n/i.test(D.toString()),
N=u?"Object":"ScriptBridgingProxyObject",W=u?"Object":"Environment",S=u&&h.java?"JavaPackage":l(h.java),ba=u?"Object":"RuntimeObject";W=(S=/\bJava/.test(S)&&h.java)&&l(h.environment)==W;var ca=S?"a":"\u03b1",da=S?"b":"\u03b2",X=h.document||{},Q=h.operamini||h.opera,T=z.test(T=u&&Q?Q["[[Class]]"]:l(Q))?T:Q=null,e,U=f;u=[];var V=null,R=f==t;t=R&&Q&&"function"==typeof Q.version&&Q.version();var H=function(L){return g(L,function(K,J){return K||RegExp("\\b"+(J.pattern||r(J))+"\\b","i").exec(f)&&(J.label||
J)})}([{label:"EdgeHTML",pattern:"Edge"},"Trident",{label:"WebKit",pattern:"AppleWebKit"},"iCab","Presto","NetFront","Tasman","KHTML","Gecko"]),v=function(L){return g(L,function(K,J){return K||RegExp("\\b"+(J.pattern||r(J))+"\\b","i").exec(f)&&(J.label||J)})}(["Adobe AIR","Arora","Avant Browser","Breach","Camino","Electron","Epiphany","Fennec","Flock","Galeon","GreenBrowser","iCab","Iceweasel","K-Meleon","Konqueror","Lunascape","Maxthon",{label:"Microsoft Edge",pattern:"Edge"},"Midori","Nook Browser",
"PaleMoon","PhantomJS","Raven","Rekonq","RockMelt",{label:"Samsung Internet",pattern:"SamsungBrowser"},"SeaMonkey",{label:"Silk",pattern:"(?:Cloud9|Silk-Accelerated)"},"Sleipnir","SlimBrowser",{label:"SRWare Iron",pattern:"Iron"},"Sunrise","Swiftfox","Waterfox","WebPositive","Opera Mini",{label:"Opera Mini",pattern:"OPiOS"},"Opera",{label:"Opera",pattern:"OPR"},"Chrome",{label:"Chrome Mobile",pattern:"(?:CriOS|CrMo)"},{label:"Firefox",pattern:"(?:Firefox|Minefield)"},{label:"Firefox for iOS",pattern:"FxiOS"},
{label:"IE",pattern:"IEMobile"},{label:"IE",pattern:"MSIE"},"Safari"]),I=x([{label:"BlackBerry",pattern:"BB10"},"BlackBerry",{label:"Galaxy S",pattern:"GT-I9000"},{label:"Galaxy S2",pattern:"GT-I9100"},{label:"Galaxy S3",pattern:"GT-I9300"},{label:"Galaxy S4",pattern:"GT-I9500"},{label:"Galaxy S5",pattern:"SM-G900"},{label:"Galaxy S6",pattern:"SM-G920"},{label:"Galaxy S6 Edge",pattern:"SM-G925"},{label:"Galaxy S7",pattern:"SM-G930"},{label:"Galaxy S7 Edge",pattern:"SM-G935"},"Google TV","Lumia","iPad",
"iPod","iPhone","Kindle",{label:"Kindle Fire",pattern:"(?:Cloud9|Silk-Accelerated)"},"Nexus","Nook","PlayBook","PlayStation Vita","PlayStation","TouchPad","Transformer",{label:"Wii U",pattern:"WiiU"},"Wii","Xbox One",{label:"Xbox 360",pattern:"Xbox"},"Xoom"]),O=function(L){return g(L,function(K,J,M){return K||(J[I]||J[/^[a-z]+(?: +[a-z]+\b)*/i.exec(I)]||RegExp("\\b"+r(M)+"(?:\\b|\\w*\\d)","i").exec(f))&&M})}({Apple:{iPad:1,iPhone:1,iPod:1},Archos:{},Amazon:{Kindle:1,"Kindle Fire":1},Asus:{Transformer:1},
"Barnes & Noble":{Nook:1},BlackBerry:{PlayBook:1},Google:{"Google TV":1,Nexus:1},HP:{TouchPad:1},HTC:{},LG:{},Microsoft:{Xbox:1,"Xbox One":1},Motorola:{Xoom:1},Nintendo:{"Wii U":1,Wii:1},Nokia:{Lumia:1},Samsung:{"Galaxy S":1,"Galaxy S2":1,"Galaxy S3":1,"Galaxy S4":1},Sony:{PlayStation:1,"PlayStation Vita":1}}),w=function(L){return g(L,function(K,J){var M=J.pattern||r(J);if(!K&&(K=RegExp("\\b"+M+"(?:/[\\d.]+|[ \\w.]*)","i").exec(f))){var P=K,Y=J.label||J,Z={"10.0":"10","6.4":"10 Technical Preview",
"6.3":"8.1","6.2":"8","6.1":"Server 2008 R2 / 7","6.0":"Server 2008 / Vista","5.2":"Server 2003 / XP 64-bit","5.1":"XP","5.01":"2000 SP1","5.0":"2000","4.0":"NT","4.90":"ME"};M&&Y&&/^Win/i.test(P)&&!/^Windows Phone /i.test(P)&&(Z=Z[/[\d.]+$/.exec(P)])&&(P="Windows "+Z);P=String(P);M&&Y&&(P=P.replace(RegExp(M,"i"),Y));K=P=b(P.replace(/ ce$/i," CE").replace(/\bhpw/i,"web").replace(/\bMacintosh\b/,"Mac OS").replace(/_PowerPC\b/i," OS").replace(/\b(OS X) [^ \d]+/i,"$1").replace(/\bMac (OS X)\b/,"$1").replace(/\/(\d)/,
" $1").replace(/_/g,".").replace(/(?: BePC|[ .]*fc[ \d.]+)$/i,"").replace(/\bx86\.64\b/gi,"x86_64").replace(/\b(Windows Phone) OS\b/,"$1").replace(/\b(Chrome OS \w+) [\d.]+\b/,"$1").split(" on ")[0])}return K})}(["Windows Phone","Android","CentOS",{label:"Chrome OS",pattern:"CrOS"},"Debian","Fedora","FreeBSD","Gentoo","Haiku","Kubuntu","Linux Mint","OpenBSD","Red Hat","SuSE","Ubuntu","Xubuntu","Cygwin","Symbian OS","hpwOS","webOS ","webOS","Tablet OS","Tizen","Linux","Mac OS X","Macintosh","Mac",
"Windows 98;","Windows "]);H&&(H=[H]);O&&!I&&(I=x([O]));if(e=/\bGoogle TV\b/.exec(I))I=e[0];/\bSimulator\b/i.test(f)&&(I=(I?I+" ":"")+"Simulator");"Opera Mini"==v&&/\bOPiOS\b/.test(f)&&u.push("running in Turbo/Uncompressed mode");"IE"==v&&/\blike iPhone OS\b/.test(f)?(e=m(f.replace(/like iPhone OS/,"")),O=e.manufacturer,I=e.product):/^iP/.test(I)?(v||(v="Safari"),w="iOS"+((e=/ OS ([\d_]+)/i.exec(f))?" "+e[1].replace(/_/g,"."):"")):"Konqueror"!=v||/buntu/i.test(w)?O&&"Google"!=O&&(/Chrome/.test(v)&&
!/\bMobile Safari\b/i.test(f)||/\bVita\b/.test(I))||/\bAndroid\b/.test(w)&&/^Chrome/.test(v)&&/\bVersion\//i.test(f)?(v="Android Browser",w=/\bAndroid\b/.test(w)?w:"Android"):"Silk"==v?(/\bMobi/i.test(f)||(w="Android",u.unshift("desktop mode")),/Accelerated *= *true/i.test(f)&&u.unshift("accelerated")):"PaleMoon"==v&&(e=/\bFirefox\/([\d.]+)\b/.exec(f))?u.push("identifying as Firefox "+e[1]):"Firefox"==v&&(e=/\b(Mobile|Tablet|TV)\b/i.exec(f))?(w||(w="Firefox OS"),I||(I=e[1])):!v||(e=!/\bMinefield\b/i.test(f)&&
/\b(?:Firefox|Safari)\b/.exec(v))?(v&&!I&&/[\/,]|^[^(]+?\)/.test(f.slice(f.indexOf(e+"/")+8))&&(v=null),(e=I||O||w)&&(I||O||/\b(?:Android|Symbian OS|Tablet OS|webOS)\b/.test(w))&&(v=/[a-z]+(?: Hat)?/i.exec(/\bAndroid\b/.test(w)?w:e)+" Browser")):"Electron"==v&&(e=(/\bChrome\/([\d.]+)\b/.exec(f)||0)[1])&&u.push("Chromium "+e):w="Kubuntu";t||(t=B(["(?:Cloud9|CriOS|CrMo|Edge|FxiOS|IEMobile|Iron|Opera ?Mini|OPiOS|OPR|Raven|SamsungBrowser|Silk(?!/[\\d.]+$))","Version",r(v),"(?:Firefox|Minefield|NetFront)"]));
if(e="iCab"==H&&3<parseFloat(t)&&"WebKit"||/\bOpera\b/.test(v)&&(/\bOPR\b/.test(f)?"Blink":"Presto")||/\b(?:Midori|Nook|Safari)\b/i.test(f)&&!/^(?:Trident|EdgeHTML)$/.test(H)&&"WebKit"||!H&&/\bMSIE\b/i.test(f)&&("Mac OS"==w?"Tasman":"Trident")||"WebKit"==H&&/\bPlayStation\b(?! Vita\b)/i.test(v)&&"NetFront")H=[e];"IE"==v&&(e=(/; *(?:XBLWP|ZuneWP)(\d+)/i.exec(f)||0)[1])?(v+=" Mobile",w="Windows Phone "+(/\+$/.test(e)?e:e+".x"),u.unshift("desktop mode")):/\bWPDesktop\b/i.test(f)?(v="IE Mobile",w="Windows Phone 8.x",
u.unshift("desktop mode"),t||(t=(/\brv:([\d.]+)/.exec(f)||0)[1])):"IE"!=v&&"Trident"==H&&(e=/\brv:([\d.]+)/.exec(f))&&(v&&u.push("identifying as "+v+(t?" "+t:"")),v="IE",t=e[1]);if(R){if(p(h,"global"))if(S&&(e=S.lang.System,U=e.getProperty("os.arch"),w=w||e.getProperty("os.name")+" "+e.getProperty("os.version")),W){try{t=h.require("ringo/engine").version.join("."),v="RingoJS"}catch(L){(e=h.system)&&e.global.system==h.system&&(v="Narwhal",w||(w=e[0].os||null))}v||(v="Rhino")}else"object"==typeof h.process&&
!h.process.browser&&(e=h.process)&&("object"==typeof e.versions&&("string"==typeof e.versions.electron?(u.push("Node "+e.versions.node),v="Electron",t=e.versions.electron):"string"==typeof e.versions.nw&&(u.push("Chromium "+t,"Node "+e.versions.node),v="NW.js",t=e.versions.nw)),v||(v="Node.js",U=e.arch,w=e.platform,t=(t=/[\d.]+/.exec(e.version))?t[0]:null));else l(e=h.runtime)==N?(v="Adobe AIR",w=e.flash.system.Capabilities.os):l(e=h.phantom)==ba?(v="PhantomJS",t=(e=e.version||null)&&e.major+"."+
e.minor+"."+e.patch):"number"==typeof X.documentMode&&(e=/\bTrident\/(\d+)/i.exec(f))?(t=[t,X.documentMode],(e=+e[1]+4)!=t[1]&&(u.push("IE "+t[1]+" mode"),H&&(H[1]=""),t[1]=e),t="IE"==v?String(t[1].toFixed(1)):t[0]):"number"==typeof X.documentMode&&/^(?:Chrome|Firefox)\b/.test(v)&&(u.push("masking as "+v+" "+t),v="IE",t="11.0",H=["Trident"],w="Windows");w=w&&b(w)}t&&(e=/(?:[ab]|dp|pre|[ab]\d+pre)(?:\d+\+?)?$/i.exec(t)||/(?:alpha|beta)(?: ?\d)?/i.exec(f+";"+(R&&F.appMinorVersion))||/\bMinefield\b/i.test(f)&&
"a")&&(V=/b/i.test(e)?"beta":"alpha",t=t.replace(RegExp(e+"\\+?$"),"")+("beta"==V?da:ca)+(/\d+\+?/.exec(e)||""));if("Fennec"==v||"Firefox"==v&&/\b(?:Android|Firefox OS)\b/.test(w))v="Firefox Mobile";else if("Maxthon"==v&&t)t=t.replace(/\.[\d.]+/,".x");else if(/\bXbox\b/i.test(I))"Xbox 360"==I&&(w=null),"Xbox 360"==I&&/\bIEMobile\b/.test(f)&&u.unshift("mobile mode");else if(!/^(?:Chrome|IE|Opera)$/.test(v)&&(!v||I||/Browser|Mobi/.test(v))||"Windows CE"!=w&&!/Mobi/i.test(f))if("IE"==v&&R)try{null===
h.external&&u.unshift("platform preview")}catch(L){u.unshift("embedded")}else(/\bBlackBerry\b/.test(I)||/\bBB10\b/.test(f))&&(e=(RegExp(I.replace(/ +/g," *")+"/([.\\d]+)","i").exec(f)||0)[1]||t)?(e=[e,/BB10/.test(f)],w=(e[1]?(I=null,O="BlackBerry"):"Device Software")+" "+e[0],t=null):this!=d&&"Wii"!=I&&(R&&Q||/Opera/.test(v)&&/\b(?:MSIE|Firefox)\b/i.test(f)||"Firefox"==v&&/\bOS X (?:\d+\.){2,}/.test(w)||"IE"==v&&(w&&!/^Win/.test(w)&&5.5<t||/\bWindows XP\b/.test(w)&&8<t||8==t&&!/\bTrident\b/.test(f)))&&
!z.test(e=m.call(d,f.replace(z,"")+";"))&&e.name&&(e="ing as "+e.name+((e=e.version)?" "+e:""),z.test(v)?(/\bIE\b/.test(e)&&"Mac OS"==w&&(w=null),e="identify"+e):(e="mask"+e,v=T?b(T.replace(/([a-z])([A-Z])/g,"$1 $2")):"Opera",/\bIE\b/.test(e)&&(w=null),R||(t=null)),H=["Presto"],u.push(e));else v+=" Mobile";if(e=(/\bAppleWebKit\/([\d.]+\+?)/i.exec(f)||0)[1]){e=[parseFloat(e.replace(/\.(\d)$/,".0$1")),e];if("Safari"==v&&"+"==e[1].slice(-1))v="WebKit Nightly",V="alpha",t=e[1].slice(0,-1);else if(t==
e[1]||t==(e[2]=(/\bSafari\/([\d.]+\+?)/i.exec(f)||0)[1]))t=null;e[1]=(/\bChrome\/([\d.]+)/i.exec(f)||0)[1];537.36==e[0]&&537.36==e[2]&&28<=parseFloat(e[1])&&"WebKit"==H&&(H=["Blink"]);R&&(C||e[1])?(H&&(H[1]="like Chrome"),e=e[1]||(e=e[0],530>e?1:532>e?2:532.05>e?3:533>e?4:534.03>e?5:534.07>e?6:534.1>e?7:534.13>e?8:534.16>e?9:534.24>e?10:534.3>e?11:535.01>e?12:535.02>e?"13+":535.07>e?15:535.11>e?16:535.19>e?17:536.05>e?18:536.1>e?19:537.01>e?20:537.11>e?"21+":537.13>e?23:537.18>e?24:537.24>e?25:537.36>
e?26:"Blink"!=H?"27":"28")):(H&&(H[1]="like Safari"),e=(e=e[0],400>e?1:500>e?2:526>e?3:533>e?4:534>e?"4+":535>e?5:537>e?6:538>e?7:601>e?8:"8"));H&&(H[1]+=" "+(e+="number"==typeof e?".x":/[.+]/.test(e)?"":"+"));"Safari"==v&&(!t||45<parseInt(t))&&(t=e)}"Opera"==v&&(e=/\bzbov|zvav$/.exec(w))?(v+=" ",u.unshift("desktop mode"),"zvav"==e?(v+="Mini",t=null):v+="Mobile",w=w.replace(RegExp(" *"+e+"$"),"")):"Safari"==v&&/\bChrome\b/.exec(H&&H[1])&&(u.unshift("desktop mode"),v="Chrome Mobile",t=null,/\bOS X\b/.test(w)?
(O="Apple",w="iOS 4.3+"):w=null);t&&0==t.indexOf(e=/[\d.]+$/.exec(w))&&-1<f.indexOf("/"+e+"-")&&(w=String(w.replace(e,"")).replace(/^ +| +$/g,""));H&&!/\b(?:Avant|Nook)\b/.test(v)&&(/Browser|Lunascape|Maxthon/.test(v)||"Safari"!=v&&/^iOS/.test(w)&&/\bSafari\b/.test(H[1])||/^(?:Adobe|Arora|Breach|Midori|Opera|Phantom|Rekonq|Rock|Samsung Internet|Sleipnir|Web)/.test(v)&&H[1])&&(e=H[H.length-1])&&u.push(e);u.length&&(u=["("+u.join("; ")+")"]);O&&I&&0>I.indexOf(O)&&u.push("on "+O);I&&u.push((/^on /.test(u[u.length-
1])?"":"on ")+I);if(w){var aa=(e=/ ([\d.+]+)$/.exec(w))&&"/"==w.charAt(w.length-e[0].length-1);w={architecture:32,family:e&&!aa?w.replace(e[0],""):w,version:e?e[1]:null,toString:function(){var L=this.version;return this.family+(L&&!aa?" "+L:"")+(64==this.architecture?" 64-bit":"")}}}(e=/\b(?:AMD|IA|Win|WOW|x86_|x)64\b/i.exec(U))&&!/\bi686\b/i.test(U)?(w&&(w.architecture=64,w.family=w.family.replace(RegExp(" *"+e),"")),v&&(/\bWOW64\b/i.test(f)||R&&/\w(?:86|32)$/.test(F.cpuClass||F.platform)&&!/\bWin64; x64\b/i.test(f))&&
u.unshift("32-bit")):w&&/^OS X/.test(w.family)&&"Chrome"==v&&39<=parseFloat(t)&&(w.architecture=64);f||(f=null);h={};h.description=f;h.layout=H&&H[0];h.manufacturer=O;h.name=v;h.prerelease=V;h.product=I;h.ua=f;h.version=v&&t;h.os=w||{architecture:null,family:null,version:null,toString:function(){return"null"}};h.parse=m;h.toString=function(){return this.description||""};h.version&&u.unshift(t);h.name&&u.unshift(v);w&&v&&(w!=String(w).split(" ")[0]||w!=v.split(" ")[0]&&!I)&&u.push(I?"("+w+")":"on "+
w);u.length&&(h.description=u.join(" "));return h}var q={"function":!0,object:!0},k=q[typeof window]&&window||this,y=q[typeof exports]&&exports;q=q[typeof module]&&module&&!module.nodeType&&module;var n=y&&q&&"object"==typeof global&&global;!n||n.global!==n&&n.window!==n&&n.self!==n||(k=n);var A=Math.pow(2,53)-1,z=/\bOpera/;n=Object.prototype;var E=n.hasOwnProperty,D=n.toString,G=m();"function"==typeof define&&"object"==typeof define.amd&&define.amd?(k.platform=G,define(function(){return G})):y&&
q?d(G,function(f,x){y[x]=f}):k.platform=G}).call(this);
function buildIOSMeta(){for(var a=[{name:"viewport",content:"width=device-width, height=device-height, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no"},{name:"apple-mobile-web-app-capable",content:"yes"},{name:"apple-mobile-web-app-status-bar-style",content:"black"}],c=0;c<a.length;c++){var b=document.createElement("meta");b.name=a[c].name;b.content=a[c].content;var d=window.document.head.querySelector('meta[name="'+b.name+'"]');d&&d.parentNode.removeChild(d);window.document.head.appendChild(b)}}
function hideIOSFullscreenPanel(){jQuery(".xxx-ios-fullscreen-message").css("display","none");jQuery(".xxx-ios-fullscreen-scroll").css("display","none");jQuery(".xxx-game-iframe-full").removeClass("xxx-game-iframe-iphone-se")}function buildIOSFullscreenPanel(){jQuery("body").append('<div class="xxx-ios-fullscreen-message"><div class="xxx-ios-fullscreen-swipe"></div></div><div class="xxx-ios-fullscreen-scroll"></div>')}
function showIOSFullscreenPanel(){jQuery(".xxx-ios-fullscreen-message").css("display","block");jQuery(".xxx-ios-fullscreen-scroll").css("display","block")}
function __iosResize(){window.scrollTo(0,0);console.log(window.devicePixelRatio);console.log(window.innerWidth);console.log(window.innerHeight);if("iPhone"===platform.product)switch(window.devicePixelRatio){case 2:switch(window.innerWidth){case 568:320!==window.innerHeight&&jQuery(".xxx-game-iframe-full").addClass("xxx-game-iframe-iphone-se");break;case 667:375===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;case 808:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();
break;default:hideIOSFullscreenPanel()}break;case 3:switch(window.innerWidth){case 736:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;case 724:375===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;case 808:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;default:hideIOSFullscreenPanel()}break;default:hideIOSFullscreenPanel()}}function iosResize(){__iosResize();setTimeout(function(){__iosResize()},500)}
function iosInIframe(){try{return window.self!==window.top}catch(a){return!0}}function isIOSLessThen13(){var a=platform.os,c=a.family.toLowerCase();a=parseFloat(a.version);return"ios"===c&&13>a?!0:!1}$(document).ready(function(){platform&&"iPhone"===platform.product&&"safari"===platform.name.toLowerCase()&&isIOSLessThen13()&&!iosInIframe()&&(buildIOSFullscreenPanel(),buildIOSMeta())});
jQuery(window).resize(function(){platform&&"iPhone"===platform.product&&"safari"===platform.name.toLowerCase()&&isIOSLessThen13()&&!iosInIframe()&&iosResize()});var s_iScaleFactor=1,s_bIsIphone=!1,s_iOffsetX,s_iOffsetY,s_bFocus=!0;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}function isChrome(){return/Chrome/.test(navigator.userAgent)&&/Google Inc/.test(navigator.vendor)}function isIpad(){var a=-1!==navigator.userAgent.toLowerCase().indexOf("ipad");return!a&&navigator.userAgent.match(/Mac/)&&navigator.maxTouchPoints&&2<navigator.maxTouchPoints?!0:a}function isMobile(){return isIpad()?!0:jQuery.browser.mobile}
function isIOS(){var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");if(-1!==navigator.userAgent.toLowerCase().indexOf("iphone"))return s_bIsIphone=!0;for(;a.length;)if(navigator.platform===a.pop())return!0;return s_bIsIphone=!1}
function getSize(a){var c=a.toLowerCase(),b=window.document,d=b.documentElement;if(void 0===window["inner"+a])a=d["client"+a];else if(window["inner"+a]!=d["client"+a]){var l=b.createElement("body");l.id="vpw-test-b";l.style.cssText="overflow:scroll";var p=b.createElement("div");p.id="vpw-test-d";p.style.cssText="position:absolute;top:-1000px";p.innerHTML="<style>@media("+c+":"+d["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+c+":7px!important}}</style>";l.appendChild(p);d.insertBefore(l,b.head);
a=7==p["offset"+a]?d["client"+a]:window["inner"+a];d.removeChild(l)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a=null!==platform.name&&"safari"===platform.name.toLowerCase()?getIOSWindowHeight():getSize("Height");var c=getSize("Width");s_bFocus&&_checkOrientation(c,a);var b=Math.min(a/CANVAS_HEIGHT,c/CANVAS_WIDTH),d=Math.round(CANVAS_WIDTH*b);b=Math.round(CANVAS_HEIGHT*b);if(b<a){var l=a-b;b+=l;d+=CANVAS_WIDTH/CANVAS_HEIGHT*l}else d<c&&(l=c-d,d+=l,b+=CANVAS_HEIGHT/CANVAS_WIDTH*l);l=a/2-b/2;var p=c/2-d/2,r=CANVAS_WIDTH/d;if(p*r<-EDGEBOARD_X||
l*r<-EDGEBOARD_Y)b=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),c/(CANVAS_WIDTH-2*EDGEBOARD_X)),d=Math.round(CANVAS_WIDTH*b),b=Math.round(CANVAS_HEIGHT*b),l=(a-b)/2,p=(c-d)/2,r=CANVAS_WIDTH/d;s_iOffsetX=-1*p*r;s_iOffsetY=-1*l*r;0<=l&&(s_iOffsetY=0);0<=p&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_bIsIphone?(canvas=document.getElementById("canvas"),s_oStage.canvas.width=2*d,s_oStage.canvas.height=
2*b,canvas.style.width=d+"px",canvas.style.height=b+"px",s_iScaleFactor=2*Math.min(d/CANVAS_WIDTH,b/CANVAS_HEIGHT),s_oStage.scaleX=s_oStage.scaleY=s_iScaleFactor):s_bMobile||isChrome()?($("#canvas").css("width",d+"px"),$("#canvas").css("height",b+"px")):(s_oStage.canvas.width=d,s_oStage.canvas.height=b,s_iScaleFactor=Math.min(d/CANVAS_WIDTH,b/CANVAS_HEIGHT),s_oStage.scaleX=s_oStage.scaleY=s_iScaleFactor);0>l||(l=(a-b)/2);$("#canvas").css("top",l+"px");$("#canvas").css("left",p+"px");fullscreenHandler()}}
function _checkOrientation(a,c){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(a>c?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),
s_oMain.stopUpdate()))}function playSound(a,c,b){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(s_aSounds[a].play(),s_aSounds[a].volume(c),s_aSounds[a].loop(b),s_aSounds[a]):null}function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].stop()}function setVolume(a,c){}function setMute(a,c){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].mute(c)}
function createBitmap(a,c,b){var d=new createjs.Bitmap(a),l=new createjs.Shape;c&&b?l.graphics.beginFill("#fff").drawRect(0,0,c,b):l.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);d.hitArea=l;return d}function createSprite(a,c,b,d,l,p){a=null!==c?new createjs.Sprite(a,c):new createjs.Sprite(a);c=new createjs.Shape;c.graphics.beginFill("#000000").drawRect(-b,-d,l,p);a.hitArea=c;return a}
function randomFloatBetween(a,c,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(a+Math.random()*(c-a),c).toFixed(b))}function shuffle(a){for(var c=a.length,b,d;0!==c;)d=Math.floor(Math.random()*c),--c,b=a[c],a[c]=a[d],a[d]=b;return a}function formatTime(a){a/=1E3;var c=Math.floor(a/60);a=parseFloat(a-60*c).toFixed(1);var b="";b=10>c?b+("0"+c+":"):b+(c+":");return 10>a?b+("0"+a):b+a}
Array.prototype.sortOn=function(){var a=this.slice();if(!arguments.length)return a.sort();var c=Array.prototype.slice.call(arguments);return a.sort(function(b,d){for(var l=c.slice(),p=l.shift();b[p]==d[p]&&l.length;)p=l.shift();return b[p]==d[p]?0:b[p]>d[p]?1:-1})};function roundDecimal(a,c){var b=Math.pow(10,c);return Math.round(b*a)/b}function tweenVectors(a,c,b,d){d.set(a.getX()+b*(c.getX()-a.getX()),a.getY()+b*(c.getY()-a.getY()));return d}
function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3===a.nodeType&&(a=a.parentNode);var c=document.createEvent("MouseEvents");c.initEvent("click",!0,!0);a.dispatchEvent(c)}}};function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(a){for(var c=window.location.search.substring(1).split("&"),b=0;b<c.length;b++){var d=c[b].split("=");if(d[0]==a)return d[1]}}
(function(){function a(b){var d={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};b=b||window.event;b.type in d?document.body.className=d[b.type]:(document.body.className=this[c]?"hidden":"visible","hidden"===document.body.className?(s_oMain.stopUpdate(),s_bFocus=!1):(s_oMain.startUpdate(),s_bFocus=!0))}var c="hidden";c in document?document.addEventListener("visibilitychange",a):(c="mozHidden")in document?document.addEventListener("mozvisibilitychange",
a):(c="webkitHidden")in document?document.addEventListener("webkitvisibilitychange",a):(c="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();
function fullscreenHandler(){ENABLE_FULLSCREEN&&!1!==screenfull.isEnabled&&(s_bFullscreen=screenfull.isFullscreen,null!==s_oInterface&&s_oInterface.resetFullscreenBut(),null!==s_oMenu&&s_oMenu.resetFullscreenBut())}if(screenfull.isEnabled)screenfull.on("change",function(){s_bFullscreen=screenfull.isFullscreen;null!==s_oInterface&&s_oInterface.resetFullscreenBut();null!==s_oMenu&&s_oMenu.resetFullscreenBut()});
function CSpriteLibrary(){var a={},c,b,d,l,p,r;this.init=function(g,m,q){c={};d=b=0;l=g;p=m;r=q};this.addSprite=function(g,m){if(a.hasOwnProperty(g))return!1;var q=new Image;a[g]=c[g]={szPath:m,oSprite:q,bLoaded:!1};b++;return!0};this.getSprite=function(g){return a.hasOwnProperty(g)?a[g].oSprite:null};this._onSpritesLoaded=function(){b=0;p.call(r)};this._onSpriteLoaded=function(){l.call(r);++d===b&&this._onSpritesLoaded()};this.loadSprites=function(){for(var g in c)c[g].oSprite.oSpriteLibrary=this,
c[g].oSprite.szKey=g,c[g].oSprite.onload=function(){this.oSpriteLibrary.setLoaded(this.szKey);this.oSpriteLibrary._onSpriteLoaded(this.szKey)},c[g].oSprite.onerror=function(m){var q=m.currentTarget;setTimeout(function(){c[q.szKey].oSprite.src=c[q.szKey].szPath},500)},c[g].oSprite.src=c[g].szPath};this.setLoaded=function(g){a[g].bLoaded=!0};this.isLoaded=function(g){return a[g].bLoaded};this.getNumSprites=function(){return b}}
var CANVAS_WIDTH=1920,CANVAS_HEIGHT=768,EDGEBOARD_X=450,EDGEBOARD_Y=0,FONT1="OpenSans-BoldItalic",FONT2="Digital-7",FPS_TIME=1E3/30,DISABLE_SOUND_MOBILE=!1,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,STATE_GAME_WAITING_FOR_BET=0,STATE_GAME_DEAL=1,STATE_GAME_CHOOSE_HOLD=2,STATE_GAME_DRAW=3,STATE_GAME_EVALUATE=4,ON_CARD_SHOWN="ON_CARD_SHOWN",ON_CARD_HIDE="ON_CARD_HIDE",ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,ROYAL_FLUSH=0,STRAIGHT_FLUSH=
1,FOUR_OF_A_KIND=2,FULL_HOUSE=3,FLUSH=4,STRAIGHT=5,THREE_OF_A_KIND=6,TWO_PAIR=7,JACKS_OR_BETTER=8,HIGH_CARD=9,CARD_TWO=2,CARD_THREE=3,CARD_FOUR=4,CARD_FIVE=5,CARD_SIX=6,CARD_SEVEN=7,CARD_EIGHT=8,CARD_NINE=9,CARD_TEN=10,CARD_JACK=11,CARD_QUEEN=12,CARD_KING=13,CARD_ACE=14,SUIT_HEARTS=0,SUIT_DIAMONDS=1,SUIT_CLUBS=2,SUIT_SPADES=3,CARD_WIDTH=154,CARD_HEIGHT=240,BET_TYPE,TOTAL_MONEY,NUM_BETS=5,WIN_COMBINATIONS=9,COMBO_PRIZES,AUTOMATIC_RECHARGE,WIN_OCCURRENCE,GAME_CASH,MIN_WIN,NUM_HAND_FOR_ADS,ENABLE_FULLSCREEN,
ENABLE_CHECK_ORIENTATION,SOUNDTRACK_VOLUME_IN_GAME=.5;TEXT_GAMEOVER="GAME OVER";TEXT_PLAY="PLAY";TEXT_BET="BET";TEXT_WIN="WIN";TEXT_MONEY="MONEY";TEXT_DEAL="DEAL";TEXT_BET_ONE="BET ONE";TEXT_MAX_BET="BET MAX";TEXT_RECHARGE="RECHARGE";TEXT_EXIT="EXIT";TEXT_DRAW="DRAW";TEXT_NO_WIN="NO WIN";TEXT_CURRENCY="$";TEXT_CREDITS_DEVELOPED="DEVELOPED BY";var TEXT_PRELOADER_CONTINUE="START";TEXT_COMBO="Royal Flush;Straight Flush;Four of a Kind;Full House;Flush;Straight;Three of a Kind;Two Pairs;Jacks or Better".split(";");
TEXT_CONGRATULATIONS="Congratulations!";TEXT_SHARE_1="You collected <strong>";TEXT_SHARE_2=" points</strong>!<br><br>Share your score with your friends!";TEXT_SHARE_3="My score is ";TEXT_SHARE_4=" points! Can you do better?";
function CPreloader(){var a,c,b,d,l,p,r,g,m,q;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.addSprite("200x200","./sprites/200x200.jpg");s_oSpriteLibrary.addSprite("but_start","./sprites/but_start.png");s_oSpriteLibrary.loadSprites();q=new createjs.Container;s_oStage.addChild(q)};this.unload=function(){m.unload();q.removeAllChildren()};this._onImagesLoaded=function(){};
this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var k=new createjs.Shape;k.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);q.addChild(k);k=s_oSpriteLibrary.getSprite("200x200");r=createBitmap(k);r.regX=.5*k.width;r.regY=.5*k.height;r.x=CANVAS_WIDTH/2;r.y=CANVAS_HEIGHT/2-80;q.addChild(r);g=new createjs.Shape;g.graphics.beginFill("rgba(0,0,0,0.01)").drawRoundRect(r.x-100,r.y-100,200,200,10);q.addChild(g);r.mask=g;k=
s_oSpriteLibrary.getSprite("progress_bar");d=createBitmap(k);d.x=CANVAS_WIDTH/2-k.width/2;d.y=CANVAS_HEIGHT/2+70;q.addChild(d);a=k.width;c=k.height;l=new createjs.Shape;l.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(d.x,d.y,1,c);q.addChild(l);d.mask=l;b=new createjs.Text("","30px "+FONT1,"#fff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT/2+120;b.textBaseline="alphabetic";b.textAlign="center";q.addChild(b);k=s_oSpriteLibrary.getSprite("but_start");m=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2+100,
k,TEXT_PRELOADER_CONTINUE,"Arial","#000",36,0,q);m.addEventListener(ON_MOUSE_UP,this._onButStartRelease,this);m.setVisible(!1);p=new createjs.Shape;p.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);q.addChild(p);createjs.Tween.get(p).to({alpha:0},500).call(function(){createjs.Tween.removeTweens(p);q.removeChild(p)})};this._onButStartRelease=function(){s_oMain._onRemovePreloader()};this.refreshLoader=function(k){b.text=k+"%";100===k&&(s_oMain._onRemovePreloader(),b.visible=!1,
d.visible=!1);l.graphics.clear();k=Math.floor(k*a/100);l.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(d.x,d.y,k,c)};this._init()}
function CMain(a){var c,b=0,d=0,l=STATE_LOADING,p,r;this.initContainer=function(){var m=document.getElementById("canvas");s_oStage=new createjs.Stage(m);createjs.Touch.enable(s_oStage,!0);s_bMobile=isMobile();!1===s_bMobile&&s_oStage.enableMouseOver(20);s_iPrevTime=(new Date).getTime();createjs.Ticker.framerate=30;createjs.Ticker.addEventListener("tick",this._update);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;seekAndDestroy()?p=new CPreloader:
window.location.href="http://www.codethislab.com/contact-us.html"};this.soundLoaded=function(){b++;p.refreshLoader(Math.floor(b/d*100))};this._initSounds=function(){Howler.mute(!s_bAudioActive);s_aSoundsInfo=[];s_aSoundsInfo.push({path:"./sounds/",filename:"card",loop:!1,volume:1,ingamename:"card"});s_aSoundsInfo.push({path:"./sounds/",filename:"press_but",loop:!1,volume:1,ingamename:"press_but"});s_aSoundsInfo.push({path:"./sounds/",filename:"win",loop:!1,volume:1,ingamename:"win"});s_aSoundsInfo.push({path:"./sounds/",
filename:"lose",loop:!1,volume:1,ingamename:"lose"});s_aSoundsInfo.push({path:"./sounds/",filename:"press_hold",loop:!1,volume:1,ingamename:"press_hold"});s_aSoundsInfo.push({path:"./sounds/",filename:"soundtrack",loop:!0,volume:1,ingamename:"soundtrack"});d+=s_aSoundsInfo.length;s_aSounds=[];for(var m=0;m<s_aSoundsInfo.length;m++)this.tryToLoadSound(s_aSoundsInfo[m],!1)};this.tryToLoadSound=function(m,q){setTimeout(function(){s_aSounds[m.ingamename]=new Howl({src:[m.path+m.filename+".mp3"],autoplay:!1,
preload:!0,loop:m.loop,volume:m.volume,onload:s_oMain.soundLoaded,onloaderror:function(k,y){for(var n=0;n<s_aSoundsInfo.length;n++)if(k===s_aSounds[s_aSoundsInfo[n].ingamename]._sounds[0]._id){s_oMain.tryToLoadSound(s_aSoundsInfo[n],!0);break}},onplayerror:function(k){for(var y=0;y<s_aSoundsInfo.length;y++)if(k===s_aSounds[s_aSoundsInfo[y].ingamename]._sounds[0]._id){s_aSounds[s_aSoundsInfo[y].ingamename].once("unlock",function(){s_aSounds[s_aSoundsInfo[y].ingamename].play();"soundtrack"===s_aSoundsInfo[y].ingamename&&
null!==s_oGame&&setVolume("soundtrack",SOUNDTRACK_VOLUME_IN_GAME)});break}}})},q?200:0)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("but_menu_bg","./sprites/but_menu_bg.png");s_oSpriteLibrary.addSprite("but_game_bg","./sprites/but_game_bg.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");
s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("card_spritesheet","./sprites/card_spritesheet.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("but_left","./sprites/but_left.png");s_oSpriteLibrary.addSprite("but_right","./sprites/but_right.png");s_oSpriteLibrary.addSprite("hold","./sprites/hold.png");s_oSpriteLibrary.addSprite("logo_game","./sprites/logo_game.png");s_oSpriteLibrary.addSprite("paytable","./sprites/paytable.png");
s_oSpriteLibrary.addSprite("display_bg","./sprites/display_bg.png");s_oSpriteLibrary.addSprite("big_display","./sprites/big_display.png");s_oSpriteLibrary.addSprite("selection","./sprites/selection.png");s_oSpriteLibrary.addSprite("card_selection","./sprites/card_selection.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");s_oSpriteLibrary.addSprite("but_info","./sprites/but_info.png");s_oSpriteLibrary.addSprite("logo_ctl","./sprites/logo_ctl.png");d+=s_oSpriteLibrary.getNumSprites();
s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;p.refreshLoader(Math.floor(b/d*100))};this.preloaderReady=function(){this._loadImages();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();c=!0};this._onRemovePreloader=function(){p.unload();s_oSoundTrack=playSound("soundtrack",1,!0);this.gotoMenu()};this._onAllImagesLoaded=function(){};this.gotoMenu=function(){new CMenu;l=STATE_MENU};this.gotoGame=function(){r=new CGame(g);l=STATE_GAME;$(s_oMain).trigger("game_start")};
this.gotoHelp=function(){new CHelp;l=STATE_HELP};this.stopUpdate=function(){c=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||Howler.mute(!0)};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();c=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none");(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)&&s_bAudioActive&&Howler.mute(!1)};this._update=function(m){if(!1!==c){var q=(new Date).getTime();s_iTimeElaps=q-s_iPrevTime;
s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=q;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);l===STATE_GAME&&r.update();s_oStage.update(m)}};s_oMain=this;var g=a;ENABLE_FULLSCREEN=g.fullscreen;ENABLE_CHECK_ORIENTATION=g.check_orientation;SHOW_CREDITS=g.show_credits;s_bAudioActive=a.audio_enable_on_startup;this.initContainer()}
var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain=null,s_oSpriteLibrary,s_oSoundTrack=null,s_bFullscreen=!1,s_aSounds;
function CTextButton(a,c,b,d,l,p,r,g,m){var q,k,y,n,A,z,E,D,G,f;this._init=function(x,B,h,u,F,t,C,N){q=!1;k=1;y=[];n=[];f=createBitmap(h);D=new createjs.Container;D.x=x;D.y=B;D.regX=h.width/2;D.regY=h.height/2;s_bMobile||(D.cursor="pointer");D.addChild(f,G);m.addChild(D);G=new CTLText(D,10,5,h.width-20,h.height-10,C,"center",t,F,1,N,0,u,!0,!0,!0,!1);this._initListener()};this.unload=function(){D.off("mousedown",A);D.off("pressup",z);m.removeChild(D)};this.setVisible=function(x){D.visible=x};this.setAlign=
function(x){G.textAlign=x};this.setTextX=function(x){G.x=x};this.setScale=function(x){k=D.scaleX=D.scaleY=x};this.enable=function(){q=!1};this.disable=function(){q=!0};this._initListener=function(){A=D.on("mousedown",this.buttonDown);z=D.on("pressup",this.buttonRelease)};this.addEventListener=function(x,B,h){y[x]=B;n[x]=h};this.addEventListenerWithParams=function(x,B,h,u){y[x]=B;n[x]=h;E=u};this.buttonRelease=function(){q||(playSound("press_but",1,!1),D.scaleX=k,D.scaleY=k,y[ON_MOUSE_UP]&&y[ON_MOUSE_UP].call(n[ON_MOUSE_UP],
E))};this.buttonDown=function(){q||(D.scaleX=.9*k,D.scaleY=.9*k,y[ON_MOUSE_DOWN]&&y[ON_MOUSE_DOWN].call(n[ON_MOUSE_DOWN]))};this.setPosition=function(x,B){D.x=x;D.y=B};this.tweenPosition=function(x,B,h,u,F,t,C){createjs.Tween.get(D).wait(u).to({x:x,y:B},h,F).call(function(){void 0!==t&&t.call(C)})};this.changeText=function(x){G.refreshText(x)};this.setX=function(x){D.x=x};this.setY=function(x){D.y=x};this.getButtonImage=function(){return D};this.getX=function(){return D.x};this.getY=function(){return D.y};
this.getSprite=function(){return D};this.getScale=function(){return D.scaleX};this._init(a,c,b,d,l,p,r,g)}
function CGfxButton(a,c,b,d){var l,p,r,g,m,q=[],k,y,n;this._init=function(A,z,E){l=!1;g=[];m=[];p=E.width;r=E.height;n=createBitmap(E);n.x=A;n.y=z;n.regX=E.width/2;n.regY=E.height/2;n.cursor="pointer";d.addChild(n);this._initListener()};this.unload=function(){n.off("mousedown",k);n.off("pressup",y);d.removeChild(n)};this.setVisible=function(A){n.visible=A};this._initListener=function(){k=n.on("mousedown",this.buttonDown);y=n.on("pressup",this.buttonRelease)};this.addEventListener=function(A,z,E){g[A]=
z;m[A]=E};this.addEventListenerWithParams=function(A,z,E,D){g[A]=z;m[A]=E;q=D};this.buttonRelease=function(){l||(playSound("press_but",1,!1),n.scaleX=1,n.scaleY=1,g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(m[ON_MOUSE_UP],q))};this.buttonDown=function(){l||(n.scaleX=.9,n.scaleY=.9,g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(m[ON_MOUSE_DOWN],q))};this.setPosition=function(A,z){n.x=A;n.y=z};this.setX=function(A){n.x=A};this.setY=function(A){n.y=A};this.enable=function(){l=!1;n.filters=[];n.cache(0,0,p,r)};this.disable=
function(){l=!0;var A=(new createjs.ColorMatrix).adjustSaturation(-100).adjustBrightness(40);n.filters=[new createjs.ColorMatrixFilter(A)];n.cache(0,0,p,r)};this.getButtonImage=function(){return n};this.getX=function(){return n.x};this.getY=function(){return n.y};this._init(a,c,b);return this}
function CToggle(a,c,b,d){var l,p,r,g;this._init=function(m,q,k,y){p=[];r=[];var n=new createjs.SpriteSheet({images:[k],frames:{width:k.width/2,height:k.height,regX:k.width/2/2,regY:k.height/2},animations:{state_true:[0],state_false:[1]}});l=y;g=createSprite(n,"state_"+l,k.width/2/2,k.height/2,k.width/2,k.height);g.x=m;g.y=q;g.stop();g.cursor="pointer";s_oStage.addChild(g);this._initListener()};this.unload=function(){g.off("mousedown",this.buttonDown);g.off("pressup",this.buttonRelease);s_oStage.removeChild(g)};
this._initListener=function(){g.on("mousedown",this.buttonDown);g.on("pressup",this.buttonRelease)};this.addEventListener=function(m,q,k){p[m]=q;r[m]=k};this.setActive=function(m){l=m;g.gotoAndStop("state_"+l)};this.buttonRelease=function(){g.scaleX=1;g.scaleY=1;playSound("press_but",1,!1);l=!l;g.gotoAndStop("state_"+l);p[ON_MOUSE_UP]&&p[ON_MOUSE_UP].call(r[ON_MOUSE_UP],l)};this.buttonDown=function(){g.scaleX=.9;g.scaleY=.9;p[ON_MOUSE_DOWN]&&p[ON_MOUSE_DOWN].call(r[ON_MOUSE_DOWN])};this.setPosition=
function(m,q){g.x=m;g.y=q};this._init(a,c,b,d)}
function CMenu(){var a,c,b,d,l,p,r,g,m,q,k,y=null,n=null,A;this._init=function(){r=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(r);var z=s_oSpriteLibrary.getSprite("but_menu_bg");g=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-164,z,TEXT_PLAY,FONT1,"#ffffff",40,0,s_oStage);g.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)z=s_oSpriteLibrary.getSprite("audio_icon"),l=CANVAS_WIDTH-z.width/4-10,p=z.height/2+10,q=new CToggle(CANVAS_WIDTH-
z.width/2+20,z.height/2+20,z,s_bAudioActive),q.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this),setVolume("soundtrack",1);SHOW_CREDITS?(z=s_oSpriteLibrary.getSprite("but_info"),a=z.height/2+10,c=z.height/2+10,m=new CGfxButton(a,c,z,s_oStage),m.addEventListener(ON_MOUSE_UP,this._onButCreditsRelease,this),b=a+z.width+10,d=c):(b=z.height/2+10,d=z.height/2+10);z=window.document;var E=z.documentElement;y=E.requestFullscreen||E.mozRequestFullScreen||E.webkitRequestFullScreen||E.msRequestFullscreen;
n=z.exitFullscreen||z.mozCancelFullScreen||z.webkitExitFullscreen||z.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(y=!1);y&&screenfull.isEnabled&&(z=s_oSpriteLibrary.getSprite("but_fullscreen"),k=new CToggle(b,d,z,s_bFullscreen,!0),k.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));A=new createjs.Shape;A.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(A);createjs.Tween.get(A).to({alpha:0},500).call(function(){A.visible=!1});this.refreshButtonPos(s_iOffsetX,
s_iOffsetY)};this.unload=function(){g.unload();g=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)q.unload(),q=null;y&&screenfull.isEnabled&&k.unload();SHOW_CREDITS&&m.unload();s_oStage.removeChild(r);r=null;s_oStage.removeChild(A);s_oMenu=A=null};this.refreshButtonPos=function(z,E){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||q.setPosition(l-z,E+p);y&&screenfull.isEnabled&&k.setPosition(b+z,d+E);SHOW_CREDITS&&m.setPosition(a+z,c+E)};this._onButPlayRelease=function(){this.unload();$(s_oMain).trigger("start_session");
s_oMain.gotoGame()};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButCreditsRelease=function(){new CCreditsPanel};this.resetFullscreenBut=function(){y&&screenfull.isEnabled&&k.setActive(s_bFullscreen)};this._onFullscreenRelease=function(){s_bFullscreen?n.call(window.document):y.call(window.document.documentElement);sizeHandler()};s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(a){var c,b,d,l,p,r,g,m,q,k,y,n=[],A,z,E,D,G,f,x,B;this._init=function(){s_oPayTableSettings=new CPayTableSettings;d=TOTAL_MONEY;l=GAME_CASH;D=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(D);B=new createjs.Container;B.x=600;B.y=530;s_oStage.addChild(B);f=new CPayTable(550,149);c=!1;y=r=m=g=0;p=parseFloat(BET_TYPE[g]*(m+1));f.setCreditColumn(m);k=STATE_GAME_WAITING_FOR_BET;G=new CInterface(d,BET_TYPE[g]);x=new CGameOver;z=new CGameSettings;E=new CHandEvaluator;
q=0;A=[];A=z.getShuffledCardDeck();MIN_WIN=COMBO_PRIZES[COMBO_PRIZES.length-1]*BET_TYPE[g]*(m+1);this.placeFakeCardForStarting();setVolume("soundtrack",SOUNDTRACK_VOLUME_IN_GAME)};this.unload=function(){G.unload();x.unload();s_oStage.removeAllChildren()};this.resetHand=function(){q=r=0;A=[];A=z.getShuffledCardDeck();for(var h=0;h<n.length;h++)n[h].reset();G.resetHand();f.resetHand();this.checkMoney();c=!1;k=STATE_GAME_WAITING_FOR_BET};this.checkMoney=function(){d<p&&(m=g=0,p=parseFloat(BET_TYPE[g]*
(m+1)),f.setCreditColumn(m),d<p?this._gameOver():(G.refreshMoney(d,p),G.refreshBet(BET_TYPE[g])))};this.changeState=function(h){};this.placeFakeCardForStarting=function(){for(var h={images:[s_oSpriteLibrary.getSprite("card_spritesheet")],frames:{width:CARD_WIDTH,height:CARD_HEIGHT,regX:CARD_WIDTH/2,regY:CARD_HEIGHT/2},animations:{card_1_1:[0],card_1_2:[1],card_1_3:[2],card_1_4:[3],card_1_5:[4],card_1_6:[5],card_1_7:[6],card_1_8:[7],card_1_9:[8],card_1_10:[9],card_1_J:[10],card_1_Q:[11],card_1_K:[12],
card_2_1:[13],card_2_2:[14],card_2_3:[15],card_2_4:[16],card_2_5:[17],card_2_6:[18],card_2_7:[19],card_2_8:[20],card_2_9:[21],card_2_10:[22],card_2_J:[23],card_2_Q:[24],card_2_K:[25],card_3_1:[26],card_3_2:[27],card_3_3:[28],card_3_4:[29],card_3_5:[30],card_3_6:[31],card_3_7:[32],card_3_8:[33],card_3_9:[34],card_3_10:[35],card_3_J:[36],card_3_Q:[37],card_3_K:[38],card_4_1:[39],card_4_2:[40],card_4_3:[41],card_4_4:[42],card_4_5:[43],card_4_6:[44],card_4_7:[45],card_4_8:[46],card_4_9:[47],card_4_10:[48],
card_4_J:[49],card_4_Q:[50],card_4_K:[51],back:[52]}},u=0,F=0;5>F;F++){var t=new createjs.SpriteSheet(h);t=createSprite(t,"back",CARD_WIDTH/2,CARD_HEIGHT/2,CARD_WIDTH,CARD_HEIGHT);t.x=u;t.y=0;t.shadow=new createjs.Shadow("#000000",5,5,5);B.addChild(t);u+=180}};this.dealCards=function(){if(!(c||0>=d)){c=!0;B.removeAllChildren();if((l<MIN_WIN?WIN_OCCURRENCE+1:Math.floor(101*Math.random()))>WIN_OCCURRENCE){do this._createCard();while(E.evaluate(n)<HIGH_CARD);b=!1}else this._createCard(),b=!0;d-=p;d=
parseFloat(d.toFixed(2));l+=p;G.refreshMoney(d,p);playSound("card",1,!1);$(s_oMain).trigger("bet_placed",p);k=STATE_GAME_DEAL}};this._createCard=function(){for(var h=0;h<n.length;h++)n[h].unload();h=0;n=[];for(var u=0;5>u;u++){var F=new CCard(h,0,B,A[q].fotogram,A[q].rank,A[q].suit);F.addEventListener(ON_CARD_SHOWN,this._onCardShown);F.addEventListener(ON_CARD_HIDE,this._onCardHide);n.push(F);q++;this._checkDeckLength();h+=180;F.showCard()}};this.drawCards=function(){if(!c){c=!0;playSound("card",
1,!1);for(var h=n.length,u=0;u<n.length;u++)!1===n[u].isHold()&&(n[u].hideCard(),h--);h===n.length&&(k=STATE_GAME_DRAW,this._onCardShown())}};this._checkDeckLength=function(){q>=A.length&&(A=z.getShuffledCardDeck(),q=0)};this.assignWin=function(h){playSound("win",1,!1);for(var u=E.getSortedHand(),F=0;F<n.length;F++)for(var t=0;t<u.length;t++)if(u[t].rank===n[F].getRank()&&u[t].suit===n[F].getSuit()){n[F].highlight();break}f.showWinAnim(m,h);r=s_oPayTableSettings.getWin(m,h)*BET_TYPE[g];d+=r;d=parseFloat(d.toFixed(2));
l-=r;G.refreshWin(r);G.refreshMoney(d,p)};this.recharge=function(h){d=h;f.setCreditColumn(m);this.checkMoney();G.refreshMoney(d,p);G.refreshBet(BET_TYPE[g]);x.hide()};this._gameOver=function(){x.show()};this.setMoney=function(h){d=parseFloat(h);G.refreshMoney(d,p)};this.onCardSelected=function(h){k===STATE_GAME_CHOOSE_HOLD&&h.toggleHold()};this._onCardShown=function(){if(k!==STATE_GAME_CHOOSE_HOLD){switch(k){case STATE_GAME_DEAL:k=STATE_GAME_CHOOSE_HOLD;G.setState(k);break;case STATE_GAME_DRAW:var h=
E.evaluate(n);G.setState(k);h!==HIGH_CARD?s_oGame.assignWin(h):(playSound("lose",1,!1),G.showLosePanel());$(s_oMain).trigger("save_score",[d]);y++;y===NUM_HAND_FOR_ADS?(y=0,$(s_oMain).trigger("show_interlevel_ad")):y===NUM_HAND_FOR_ADS-1&&$(s_oMain).trigger("share_event",[d]);k=STATE_GAME_EVALUATE;break;case STATE_GAME_EVALUATE:G.setState(k)}c=!1}};this._onCardHide=function(){if(k!==STATE_GAME_DRAW){k=STATE_GAME_DRAW;if(b){var h=0;do{s_oGame._changeCardValue();var u=E.evaluate(n);var F=u===HIGH_CARD?
0:s_oPayTableSettings.getWin(m,u)*BET_TYPE[g];h++}while((u===HIGH_CARD||l<F)&&5E3>h);if(5E3<=h){do s_oGame._changeCardValue(),u=E.evaluate(n);while(u<HIGH_CARD);b=!1}}else{do s_oGame._changeCardValue(),u=E.evaluate(n);while(u<HIGH_CARD)}for(h=0;5>h;h++)n[h].setHold(!1)}};this._changeCardValue=function(){for(var h=0;5>h;h++)!1===n[h].isHold()&&(n[h].changeInfo(A[q].fotogram,A[q].rank,A[q].suit),n[h].showCard(),q++,this._checkDeckLength())};this._onButDealRelease=function(){switch(k){case STATE_GAME_WAITING_FOR_BET:this.dealCards();
break;case STATE_GAME_CHOOSE_HOLD:this.drawCards();break;case STATE_GAME_EVALUATE:this.resetHand(),this.dealCards()}};this._onButLeftRelease=function(){if(!(0===g||c||k!==STATE_GAME_WAITING_FOR_BET&&k!==STATE_GAME_EVALUATE)){MIN_WIN=COMBO_PRIZES[COMBO_PRIZES.length-1];g--;var h=parseFloat(BET_TYPE[g]*(m+1));d<h?g++:(p=h,G.refreshMoney(d,p),G.refreshBet(BET_TYPE[g]),MIN_WIN=COMBO_PRIZES[COMBO_PRIZES.length-1]*BET_TYPE[g]*(m+1))}};this._onButRightRelease=function(){if(!(g===BET_TYPE.length-1||c||k!==
STATE_GAME_WAITING_FOR_BET&&k!==STATE_GAME_EVALUATE)){g++;var h=parseFloat(BET_TYPE[g]*(m+1));d<h?g--:(p=h,G.refreshMoney(d,p),G.refreshBet(BET_TYPE[g]),MIN_WIN=COMBO_PRIZES[COMBO_PRIZES.length-1]*BET_TYPE[g]*(m+1))}};this._onButBetOneRelease=function(){if(!(c||k!==STATE_GAME_WAITING_FOR_BET&&k!==STATE_GAME_EVALUATE)){m++;m===NUM_BETS&&(m=0);var h=parseFloat(BET_TYPE[g]*(m+1));d<h?0===m?m=NUM_BETS-1:m--:(p=h,G.refreshMoney(d,p),f.setCreditColumn(m),MIN_WIN=COMBO_PRIZES[COMBO_PRIZES.length-1]*BET_TYPE[g]*
(m+1))}};this._onButBetMaxRelease=function(){if(!(c||k!==STATE_GAME_WAITING_FOR_BET&&k!==STATE_GAME_EVALUATE)){c=!0;m=NUM_BETS-1;var h=parseFloat(BET_TYPE[g]*(m+1));d<h?this._gameOver():(p=h,G.refreshMoney(d,p),f.setCreditColumn(m),MIN_WIN=COMBO_PRIZES[COMBO_PRIZES.length-1]*BET_TYPE[g]*(m+1),this.resetHand(),this.dealCards())}};this.onExit=function(){this.unload();s_oMain.gotoMenu();$(s_oMain).trigger("end_session")};this.update=function(){};s_oGame=this;WIN_OCCURRENCE=a.win_occurrence;GAME_CASH=
a.game_cash;BET_TYPE=a.bets;COMBO_PRIZES=a.combo_prizes;TOTAL_MONEY=a.money;AUTOMATIC_RECHARGE=a.recharge;NUM_HAND_FOR_ADS=a.num_hand_before_ads;this._init()}var s_oGame,s_oPayTableSettings;
function CInterface(a,c){var b,d,l,p,r,g,m,q,k,y,n,A,z,E,D,G,f,x,B,h=null,u=null;this._init=function(F,t){var C=s_oSpriteLibrary.getSprite("but_exit");l=CANVAS_WIDTH-C.width/2-2;p=C.height/2+2;m=new CGfxButton(l,p,C,s_oStage);m.addEventListener(ON_MOUSE_UP,this._onExit,this);!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(r=m.getX()-C.width,g=C.height/2+2,z=new CToggle(r,g,s_oSpriteLibrary.getSprite("audio_icon"),s_bAudioActive),z.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this),b=r-C.width-10,d=
g):(b=m.getX()-C.width-10,d=C.height/2+2);C=window.document;var N=C.documentElement;h=N.requestFullscreen||N.mozRequestFullScreen||N.webkitRequestFullScreen||N.msRequestFullscreen;u=C.exitFullscreen||C.mozCancelFullScreen||C.webkitExitFullscreen||C.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(h=!1);h&&screenfull.isEnabled&&(C=s_oSpriteLibrary.getSprite("but_fullscreen"),B=new CToggle(b,d,C,s_bFullscreen,!0),B.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));C=createBitmap(s_oSpriteLibrary.getSprite("display_bg"));
C.x=480;C.y=25;s_oStage.addChild(C);new CTLText(s_oStage,470,20,100,22,22,"left","#fff",FONT1,1,0,0,TEXT_WIN,!0,!0,!1,!1);C=createBitmap(s_oSpriteLibrary.getSprite("display_bg"));C.x=480;C.y=93;s_oStage.addChild(C);new CTLText(s_oStage,470,90,100,22,22,"left","#fff",FONT1,1,0,0,TEXT_BET,!0,!0,!1,!1);C=createBitmap(s_oSpriteLibrary.getSprite("display_bg"));C.x=470;C.y=687;s_oStage.addChild(C);new CTLText(s_oStage,460,685,100,22,22,"left","#fff",FONT1,1,0,0,TEXT_MONEY,!0,!0,!1,!1);E=new CTLText(s_oStage,
480,CANVAS_HEIGHT-66,210,30,30,"center","#ffde00",FONT2,1,0,0,F.toFixed(2)+TEXT_CURRENCY,!0,!0,!1,!1);G=new CTLText(s_oStage,490,110,210,30,30,"center","#ffde00",FONT2,1,0,0,t.toFixed(2)+TEXT_CURRENCY,!0,!0,!1,!1);D=new CTLText(s_oStage,490,40,210,30,30,"center","#ffde00",FONT2,1,0,0,"0"+TEXT_CURRENCY,!0,!0,!1,!1);C=createBitmap(s_oSpriteLibrary.getSprite("big_display"));C.x=770;C.y=686;s_oStage.addChild(C);f=new CTLText(s_oStage,780,700,108,40,40,"center","#ffde00",FONT2,1,0,0,t.toFixed(2)+TEXT_CURRENCY,
!0,!0,!1,!1);C=s_oSpriteLibrary.getSprite("logo_game");N=createBitmap(C);N.x=CANVAS_WIDTH/2;N.y=17;N.regX=C.width/2;s_oStage.addChild(N);C=s_oSpriteLibrary.getSprite("but_left");q=new CGfxButton(744,722,C,s_oStage);q.addEventListener(ON_MOUSE_UP,this._onButLeftRelease,this);C=s_oSpriteLibrary.getSprite("but_right");k=new CGfxButton(930,722,C,s_oStage);k.addEventListener(ON_MOUSE_UP,this._onButRightRelease,this);C=s_oSpriteLibrary.getSprite("but_game_bg");y=new CTextButton(1040,716,C,TEXT_BET_ONE,
FONT1,"#ffffff",23,0,s_oStage);y.addEventListener(ON_MOUSE_UP,this._onButBetOneRelease,this);n=new CTextButton(1190,716,C,TEXT_MAX_BET,FONT1,"#ffffff",23,0,s_oStage);n.addEventListener(ON_MOUSE_UP,this._onButBetMaxRelease,this);A=new CTextButton(1340,716,C,TEXT_DEAL,FONT1,"#ffffff",30,0,s_oStage);A.addEventListener(ON_MOUSE_UP,this._onButDealRelease,this);x=new createjs.Container;x.visible=!1;x.x=710;x.y=500;s_oStage.addChild(x);C=new createjs.Shape;C.graphics.beginFill("rgba(0,0,0,0.7)").drawRect(0,
0,500,100);x.addChild(C);new CTLText(x,0,0,500,100,50,"center","#fff",FONT1,1,10,5,TEXT_NO_WIN,!0,!0,!1,!1);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){m.unload();q.unload();k.unload();y.unload();n.unload();A.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)z.unload(),z=null;h&&screenfull.isEnabled&&B.unload();s_oInterface=null};this.refreshButtonPos=function(F,t){m.setPosition(l-F,t+p);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||z.setPosition(r-F,t+g);h&&screenfull.isEnabled&&
B.setPosition(b-F,d+t)};this.setState=function(F){switch(F){case STATE_GAME_CHOOSE_HOLD:A.changeText(TEXT_DRAW);break;case STATE_GAME_DRAW:case STATE_GAME_EVALUATE:A.changeText(TEXT_DEAL)}};this.resetHand=function(){this.refreshWin(0);x.visible=!1};this.refreshMoney=function(F,t){E.refreshText(F.toFixed(2)+TEXT_CURRENCY);G.refreshText(t.toFixed(2)+TEXT_CURRENCY)};this.refreshWin=function(F){D.refreshText(F.toFixed(2)+TEXT_CURRENCY)};this.refreshBet=function(F){f.refreshText(F.toFixed(2)+TEXT_CURRENCY)};
this.showLosePanel=function(){x.visible=!0};this._onButLeftRelease=function(){s_oGame._onButLeftRelease()};this._onButRightRelease=function(){s_oGame._onButRightRelease()};this._onButBetOneRelease=function(){s_oGame._onButBetOneRelease()};this._onButBetMaxRelease=function(){s_oGame._onButBetMaxRelease()};this._onButDealRelease=function(){s_oGame._onButDealRelease()};this._onExit=function(){s_oGame.onExit()};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};
this.resetFullscreenBut=function(){h&&screenfull.isEnabled&&B.setActive(s_bFullscreen)};this._onFullscreenRelease=function(){s_bFullscreen?u.call(window.document):h.call(window.document.documentElement);sizeHandler()};s_oInterface=this;this._init(a,c);return this}var s_oInterface=null;
function CGameSettings(){var a,c;this._init=function(){var b=-1;a=[];for(var d=0;52>d;d++){var l=(d+1)%13;1===l?(l=14,b++):0===l&&(l=13);a.push({fotogram:d,rank:l,suit:b})}};this.timeToString=function(b){b=Math.round(b/1E3);var d=Math.floor(b/60);b-=60*d;var l="";l=10>d?l+("0"+d+":"):l+(d+":");return 10>b?l+("0"+b):l+b};this.getShuffledCardDeck=function(){for(var b=[],d=0;d<a.length;d++)b[d]=a[d];for(c=[];0<b.length;)c.push(b.splice(Math.round(Math.random()*(b.length-1)),1)[0]);return c};this.getCardValue=
function(b){return(void 0)[b]};this._init()}
function CCard(a,c,b,d,l,p){var r,g,m,q,k,y,n,A,z,E,D;this._init=function(f,x,B,h,u,F){r=!1;D=B;g=h;m=u;q=F;B=s_oSpriteLibrary.getSprite("card_spritesheet");B=new createjs.SpriteSheet({images:[B],frames:{width:CARD_WIDTH,height:CARD_HEIGHT,regX:CARD_WIDTH/2,regY:CARD_HEIGHT/2},animations:{card_1_1:[0],card_1_2:[1],card_1_3:[2],card_1_4:[3],card_1_5:[4],card_1_6:[5],card_1_7:[6],card_1_8:[7],card_1_9:[8],card_1_10:[9],card_1_J:[10],card_1_Q:[11],card_1_K:[12],card_2_1:[13],card_2_2:[14],card_2_3:[15],
card_2_4:[16],card_2_5:[17],card_2_6:[18],card_2_7:[19],card_2_8:[20],card_2_9:[21],card_2_10:[22],card_2_J:[23],card_2_Q:[24],card_2_K:[25],card_3_1:[26],card_3_2:[27],card_3_3:[28],card_3_4:[29],card_3_5:[30],card_3_6:[31],card_3_7:[32],card_3_8:[33],card_3_9:[34],card_3_10:[35],card_3_J:[36],card_3_Q:[37],card_3_K:[38],card_4_1:[39],card_4_2:[40],card_4_3:[41],card_4_4:[42],card_4_5:[43],card_4_6:[44],card_4_7:[45],card_4_8:[46],card_4_9:[47],card_4_10:[48],card_4_J:[49],card_4_Q:[50],card_4_K:[51],
back:[52]}});n=createSprite(B,"back",CARD_WIDTH/2,CARD_HEIGHT/2,CARD_WIDTH,CARD_HEIGHT);n.x=f;n.y=x;n.stop();n.shadow=new createjs.Shadow("#000000",5,5,5);D.addChild(n);B=s_oSpriteLibrary.getSprite("hold");A=createBitmap(B);A.regX=B.width/2;A.x=f;A.y=x+76;A.visible=!1;D.addChild(A);B=s_oSpriteLibrary.getSprite("card_selection");E=createBitmap(B);E.x=f;E.y=x;E.regX=B.width/2;E.regY=B.height/2;E.visible=!1;D.addChild(E);z=new createjs.Shape;z.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(f-
CARD_WIDTH/2,x-CARD_HEIGHT/2,CARD_WIDTH,CARD_HEIGHT);z.on("click",this._onSelected);z.cursor="pointer";D.addChild(z);k=[];y=[]};this.unload=function(){z.off("click",this._onSelected);D.removeChild(n)};this.reset=function(){r=!1;E.visible=!1;n.shadow=new createjs.Shadow("#000000",5,5,5)};this.addEventListener=function(f,x,B){k[f]=x;y[f]=B};this.changeInfo=function(f,x,B){g=f;m=x;q=B};this.setValue=function(){n.gotoAndStop(g);var f=this;createjs.Tween.get(n).to({scaleX:1},200).call(function(){f.cardShown()})};
this.setHold=function(f){r=f;A.visible=r};this.toggleHold=function(){createjs.Tween.hasActiveTweens(n)||(r=!r,A.visible=r,playSound("press_hold",1,!1))};this.showCard=function(){var f=this;createjs.Tween.get(n).to({scaleX:.1},200).call(function(){f.setValue()})};this.hideCard=function(){var f=this;createjs.Tween.get(n).to({scaleX:.1},200).call(function(){f.setBack()})};this.setBack=function(){n.gotoAndStop("back");var f=this;createjs.Tween.get(n).to({scaleX:1},200).call(function(){f.cardHidden()})};
this.cardShown=function(){k[ON_CARD_SHOWN]&&k[ON_CARD_SHOWN].call(y[ON_CARD_SHOWN])};this.cardHidden=function(){k[ON_CARD_HIDE]&&k[ON_CARD_HIDE].call(y[ON_CARD_HIDE],this)};this.highlight=function(){n.shadow=new createjs.Shadow("#fff000",0,0,15);E.visible=!0};this._onSelected=function(){s_oGame.onCardSelected(G)};this.getRank=function(){return m};this.getSuit=function(){return q};this.getFotogram=function(){return g};this.isHold=function(){return r};var G=this;this._init(a,c,b,d,l,p)}
function CGameOver(){var a,c,b;this._init=function(){b=new createjs.Container;s_oStage.addChild(b);var d=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));b.addChild(d);new CTLText(b,CANVAS_WIDTH/2-198,CANVAS_HEIGHT/2-98,400,50,50,"center","#000",FONT1,1,0,0,TEXT_GAMEOVER,!0,!0,!1,!1);new CTLText(b,CANVAS_WIDTH/2-200,CANVAS_HEIGHT/2-100,400,50,50,"center","#fff",FONT1,1,0,0,TEXT_GAMEOVER,!0,!0,!1,!1);a=new CTextButton(CANVAS_WIDTH/2-100,450,s_oSpriteLibrary.getSprite("but_game_bg"),TEXT_RECHARGE,
FONT1,"#fff",14,0,b);a.addEventListener(ON_MOUSE_UP,this._onRecharge,this);c=new CTextButton(CANVAS_WIDTH/2+100,450,s_oSpriteLibrary.getSprite("but_game_bg"),TEXT_EXIT,FONT1,"#fff",14,0,b);c.addEventListener(ON_MOUSE_UP,this._onExit,this);this.hide()};this.unload=function(){a.unload();c.unload()};this.show=function(){b.visible=!0};this.hide=function(){b.visible=!1};this._onRecharge=function(){b.visible=!1;AUTOMATIC_RECHARGE&&s_oGame.recharge(TOTAL_MONEY);$(s_oMain).trigger("recharge")};this._onExit=
function(){$(s_oMain).trigger("end_session");s_oGame.onExit()};this._init()}
function CPayTable(a,c){var b,d,l,p;this._init=function(r,g){p=new createjs.Container;p.x=r;p.y=g;s_oStage.addChild(p);var m=createBitmap(s_oSpriteLibrary.getSprite("paytable"));p.addChild(m);m=278;var q=4;b=[];for(var k=0;k<NUM_BETS;k++){var y=createBitmap(s_oSpriteLibrary.getSprite("selection"));y.visible=!1;y.x=m;y.y=q;p.addChild(y);b.push(y);m+=100}m=25;q=15;l=[];for(k=0;k<WIN_COMBINATIONS;k++)y=new CTLText(p,m,q,250,19,19,"right","#fff000",FONT1,1,0,0,TEXT_COMBO[k],!0,!0,!1,!1),q+=22,l[k]=y;
m=375;d=[];for(k=0;k<NUM_BETS;k++){q=27;d[k]=[];for(y=0;y<WIN_COMBINATIONS;y++){var n=new createjs.Text(s_oPayTableSettings.getWin(k,y),"22px "+FONT1,"#fff000");n.x=m;n.y=q;n.textAlign="right";n.textBaseline="middle";p.addChild(n);q+=22;d[k][y]=n}m+=100}};this.resetHand=function(){createjs.Tween.removeAllTweens();for(var r=0;r<NUM_BETS;r++)for(var g=0;g<WIN_COMBINATIONS;g++)d[r][g].alpha=1;for(r=0;r<WIN_COMBINATIONS;r++)l[r].alpha=1};this.setCreditColumn=function(r){for(var g=0;g<NUM_BETS;g++)b[g].visible=
!1;b[r].visible=!0};this.showWinAnim=function(r,g){createjs.Tween.get(d[r][g],{loop:-1}).to({alpha:1},100).to({alpha:0},100);createjs.Tween.get(l[g]).to({alpha:1},100).to({alpha:0},100)};this._init(a,c)}function CPayTableSettings(){var a;this._init=function(){a=[];for(var c=0;c<NUM_BETS;c++){a[c]=[];for(var b=0;b<WIN_COMBINATIONS;b++)a[c][b]=COMBO_PRIZES[b]*(c+1)}};this.getWin=function(c,b){return a[c][b]};this._init()}
function CHandEvaluator(){var a,c;this.evaluate=function(b){a=[];for(var d=0;d<b.length;d++)a[d]={rank:b[d].getRank(),suit:b[d].getSuit()};a.sort(this.compareRank);c=[0,1,2,3,4];return this.rankHand()};this.rankHand=function(){if(this._checkForRoyalFlush())return ROYAL_FLUSH;if(this._checkForStraightFlush())return STRAIGHT_FLUSH;if(this._checkForFourOfAKind())return FOUR_OF_A_KIND;if(this._checkForFullHouse())return FULL_HOUSE;if(this._checkForFlush())return FLUSH;if(this._checkForStraight())return STRAIGHT;
if(this._checkForThreeOfAKind())return THREE_OF_A_KIND;if(this._checkForTwoPair())return TWO_PAIR;if(this._checkForOnePair())return JACKS_OR_BETTER;this._identifyHighCard();return HIGH_CARD};this._checkForRoyalFlush=function(){return this._isRoyalStraight()&&this._isFlush()?!0:!1};this._checkForStraightFlush=function(){return this._isStraight()&&this._isFlush()?!0:!1};this._checkForFourOfAKind=function(){return a[0].rank===a[3].rank?(a.splice(4,1),c.splice(4,1),!0):a[1].rank===a[4].rank?(a.splice(0,
1),c.splice(0,1),!0):!1};this._checkForFullHouse=function(){return a[0].rank===a[1].rank&&a[2].rank===a[4].rank||a[0].rank===a[2].rank&&a[3].rank===a[4].rank?!0:!1};this._checkForFlush=function(){return this._isFlush()?!0:!1};this._checkForStraight=function(){return this._isStraight()?!0:!1};this._checkForThreeOfAKind=function(){return a[0].rank===a[1].rank&&a[0].rank===a[2].rank?(a.splice(3,1),a.splice(3,1),c.splice(3,1),c.splice(3,1),!0):a[1].rank===a[2].rank&&a[1].rank===a[3].rank?(a.splice(0,
1),a.splice(3,1),c.splice(0,1),c.splice(3,1),!0):a[2].rank===a[3].rank&&a[2].rank===a[4].rank?(a.splice(0,1),a.splice(0,1),c.splice(0,1),c.splice(0,1),!0):!1};this._checkForTwoPair=function(){return a[0].rank===a[1].rank&&a[2].rank===a[3].rank?(a.splice(4,1),c.splice(4,1),!0):a[1].rank===a[2].rank&&a[3].rank===a[4].rank?(a.splice(0,1),c.splice(0,1),!0):a[0].rank===a[1].rank&&a[3].rank===a[4].rank?(a.splice(2,1),c.splice(2,1),!0):!1};this._checkForOnePair=function(){for(var b=0;4>b;b++)if(a[b].rank===
a[b+1].rank&&a[b].rank>CARD_TEN){var d=a[b],l=a[b+1];a=[];a.push(d);a.push(l);c=[b,b+1];return!0}return!1};this._identifyHighCard=function(){for(var b=0;4>b;b++)a.splice(0,1)};this._isFlush=function(){return a[0].suit===a[1].suit&&a[0].suit===a[2].suit&&a[0].suit===a[3].suit&&a[0].suit===a[4].suit?!0:!1};this._isRoyalStraight=function(){return a[0].rank===CARD_TEN&&a[1].rank===CARD_JACK&&a[2].rank===CARD_QUEEN&&a[3].rank===CARD_KING&&a[4].rank===CARD_ACE?!0:!1};this._isStraight=function(){var b=a[0].rank+
1===a[1].rank&&a[1].rank+1===a[2].rank&&a[2].rank+1===a[3].rank;return b&&a[0].rank===CARD_TWO&&a[4].rank===CARD_ACE?!0:b&&a[3].rank+1===a[4].rank?!0:!1};this.compareRank=function(b,d){return b.rank<d.rank?-1:b.rank>d.rank?1:0};this.getSortedHand=function(){return a};this.getCardIndexInCombo=function(){return c}}
function CCreditsPanel(){var a,c,b,d,l,p,r,g,m,q;this._init=function(){q=new createjs.Container;q.alpha=0;s_oStage.addChild(q);c=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));q.addChild(c);r=new createjs.Shape;r.graphics.beginFill("#0f0f0f").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);r.alpha=.01;r.on("click",this._onLogoButRelease);q.addChild(r);var k=s_oSpriteLibrary.getSprite("but_exit");a=CANVAS_WIDTH/2+240;d=new CGfxButton(a,270,k,q);d.addEventListener(ON_MOUSE_UP,this.unload,this);p=new createjs.Text(TEXT_CREDITS_DEVELOPED,
"34px "+FONT1,"#000");p.textAlign="center";p.textBaseline="alphabetic";p.x=CANVAS_WIDTH/2;p.y=340;p.outline=2;q.addChild(p);l=new createjs.Text(TEXT_CREDITS_DEVELOPED,"34px "+FONT1,"#fff");l.textAlign="center";l.textBaseline="alphabetic";l.x=CANVAS_WIDTH/2;l.y=340;q.addChild(l);k=s_oSpriteLibrary.getSprite("logo_ctl");b=createBitmap(k);b.regX=k.width/2;b.regY=k.height/2;b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT/2;q.addChild(b);m=new createjs.Text("www.codethislab.com","30px "+FONT1,"#000");m.textAlign=
"center";m.textBaseline="alphabetic";m.x=CANVAS_WIDTH/2;m.y=450;m.outline=2;q.addChild(m);g=new createjs.Text("www.codethislab.com","30px "+FONT1,"#fff");g.textAlign="center";g.textBaseline="alphabetic";g.x=CANVAS_WIDTH/2;g.y=450;q.addChild(g);createjs.Tween.get(q).to({alpha:1},600,createjs.Ease.cubicOut);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(k,y){};this.unload=function(){r.off("click",this._onLogoButRelease);d.unload();d=null;s_oStage.removeChild(q)};this._onLogoButRelease=
function(){window.open("http://www.codethislab.com/index.php?&l=en","_blank")};this._init()}
CTLText.prototype={constructor:CTLText,__autofit:function(){if(this._bFitText){for(var a=this._iFontSize;(this._oText.getBounds().height>this._iHeight-2*this._iPaddingV||this._oText.getBounds().width>this._iWidth-2*this._iPaddingH)&&!(a--,this._oText.font=a+"px "+this._szFont,this._oText.lineHeight=Math.round(a*this._fLineHeightFactor),this.__updateY(),this.__verticalAlign(),8>a););this._iFontSize=a}},__verticalAlign:function(){if(this._bVerticalAlign){var a=this._oText.getBounds().height;this._oText.y-=
(a-this._iHeight)/2+this._iPaddingV}},__updateY:function(){this._oText.y=this._y+this._iPaddingV;switch(this._oText.textBaseline){case "middle":this._oText.y+=this._oText.lineHeight/2+(this._iFontSize*this._fLineHeightFactor-this._iFontSize)}},__createText:function(a){this._bDebug&&(this._oDebugShape=new createjs.Shape,this._oDebugShape.graphics.beginFill("rgba(255,0,0,0.5)").drawRect(this._x,this._y,this._iWidth,this._iHeight),this._oContainer.addChild(this._oDebugShape));this._oText=new createjs.Text(a,
this._iFontSize+"px "+this._szFont,this._szColor);this._oText.textBaseline="middle";this._oText.lineHeight=Math.round(this._iFontSize*this._fLineHeightFactor);this._oText.textAlign=this._szAlign;this._oText.lineWidth=this._bMultiline?this._iWidth-2*this._iPaddingH:null;switch(this._szAlign){case "center":this._oText.x=this._x+this._iWidth/2;break;case "left":this._oText.x=this._x+this._iPaddingH;break;case "right":this._oText.x=this._x+this._iWidth-this._iPaddingH}this._oContainer.addChild(this._oText);
this.refreshText(a)},setVerticalAlign:function(a){this._bVerticalAlign=a},setOutline:function(a){null!==this._oText&&(this._oText.outline=a)},setShadow:function(a,c,b,d){null!==this._oText&&(this._oText.shadow=new createjs.Shadow(a,c,b,d))},setColor:function(a){this._oText.color=a},setAlpha:function(a){this._oText.alpha=a},removeTweens:function(){createjs.Tween.removeTweens(this._oText)},getText:function(){return this._oText},getY:function(){return this._y},getFontSize:function(){return this._iFontSize},
refreshText:function(a){""===a&&(a=" ");null===this._oText&&this.__createText(a);this._oText.text=a;this._oText.font=this._iFontSize+"px "+this._szFont;this._oText.lineHeight=Math.round(this._iFontSize*this._fLineHeightFactor);this.__autofit();this.__updateY();this.__verticalAlign()}};
function CTLText(a,c,b,d,l,p,r,g,m,q,k,y,n,A,z,E,D){this._oContainer=a;this._x=c;this._y=b;this._iWidth=d;this._iHeight=l;this._bMultiline=E;this._iFontSize=p;this._szAlign=r;this._szColor=g;this._szFont=m;this._iPaddingH=k;this._iPaddingV=y;this._bVerticalAlign=z;this._bFitText=A;this._bDebug=D;this._oDebugShape=null;this._fLineHeightFactor=q;this._oText=null;n&&this.__createText(n)}
function extractHostname(a){a=-1<a.indexOf("://")?a.split("/")[2]:a.split("/")[0];a=a.split(":")[0];return a=a.split("?")[0]}function extractRootDomain(a){a=extractHostname(a);var c=a.split("."),b=c.length;2<b&&(a=c[b-2]+"."+c[b-1]);return a}
var getClosestTop=function(){var a=window,c=!1;try{for(;a.parent.document!==a.document;)if(a.parent.document)a=a.parent;else{c=!0;break}}catch(b){c=!0}return{topFrame:a,err:c}},getBestPageUrl=function(a){var c=a.topFrame,b="";if(a.err)try{try{b=window.top.location.href}catch(l){var d=window.location.ancestorOrigins;b=d[d.length-1]}}catch(l){b=c.document.referrer}else b=c.location.href;return b},TOPFRAMEOBJ=getClosestTop(),PAGE_URL=getBestPageUrl(TOPFRAMEOBJ);
function seekAndDestroy(){for(var a=extractRootDomain(PAGE_URL),c=[String.fromCharCode(99,111,100,101,116,104,105,115,108,97,98,46,99,111,109),String.fromCharCode(101,110,118,97,116,111,46,99,111,109),String.fromCharCode(99,111,100,101,99,97,110,121,111,110,46,99,111,109),String.fromCharCode(99,111,100,101,99,97,110,121,111,110,46,110,101,116)],b=0;b<c.length;b++)if(c[b]===a)return!0;return!0};