/*
 screenfull
 v5.0.0 - 2019-09-09
 (c) Sindre Sorhus; MIT License
 Platform.js <https://mths.be/platform>
 Copyright 2014-2018 Benjamin Tan <https://bnjmnt4n.now.sh/>
 Copyright 2011-2013 John-David Dalton
 Available under MIT license <https://mths.be/mit>
*/
!function(){var a="undefined"!=typeof window&&void 0!==window.document?window.document:{},b="undefined"!=typeof module&&module.exports,c=function(){for(var f,m=["requestFullscreen exitFullscreen fullscreenElement fullscreenEnabled fullscreenchange fullscreenerror".split(" "),"webkitRequestFullscreen webkitExitFullscreen webkitFullscreenElement webkitFullscreenEnabled webkitfullscreenchange webkitfullscreenerror".split(" "),"webkitRequestFullScreen webkitCancelFullScreen webkitCurrentFullScreenElement webkitCancelFullScreen webkitfullscreenchange webkitfullscreenerror".split(" "),
"mozRequestFullScreen mozCancelFullScreen mozFullScreenElement mozFullScreenEnabled mozfullscreenchange mozfullscreenerror".split(" "),"msRequestFullscreen msExitFullscreen msFullscreenElement msFullscreenEnabled MSFullscreenChange MSFullscreenError".split(" ")],n=0,t=m.length,r={};n<t;n++)if((f=m[n])&&f[1]in a){for(n=0;n<f.length;n++)r[m[0][n]]=f[n];return r}return!1}(),d={change:c.fullscreenchange,error:c.fullscreenerror},e={request:function(f){return new Promise(function(m,n){var t=function(){this.off("change",
t);m()}.bind(this);this.on("change",t);f=f||a.documentElement;Promise.resolve(f[c.requestFullscreen]())["catch"](n)}.bind(this))},exit:function(){return new Promise(function(f,m){if(this.isFullscreen){var n=function(){this.off("change",n);f()}.bind(this);this.on("change",n);Promise.resolve(a[c.exitFullscreen]())["catch"](m)}else f()}.bind(this))},toggle:function(f){return this.isFullscreen?this.exit():this.request(f)},onchange:function(f){this.on("change",f)},onerror:function(f){this.on("error",f)},
on:function(f,m){var n=d[f];n&&a.addEventListener(n,m,!1)},off:function(f,m){var n=d[f];n&&a.removeEventListener(n,m,!1)},raw:c};c?(Object.defineProperties(e,{isFullscreen:{get:function(){return!!a[c.fullscreenElement]}},element:{enumerable:!0,get:function(){return a[c.fullscreenElement]}},isEnabled:{enumerable:!0,get:function(){return!!a[c.fullscreenEnabled]}}}),b?module.exports=e:window.screenfull=e):b?module.exports={isEnabled:!1}:window.screenfull={isEnabled:!1}}();
(function(){function a(p){p=String(p);return p.charAt(0).toUpperCase()+p.slice(1)}function b(p,N){var y=-1,z=p?p.length:0;if("number"==typeof z&&-1<z&&z<=F)for(;++y<z;)N(p[y],y,p);else d(p,N)}function c(p){p=String(p).replace(/^ +| +$/g,"");return/^(?:webOS|i(?:OS|P))/.test(p)?p:a(p)}function d(p,N){for(var y in p)H.call(p,y)&&N(p[y],y,p)}function e(p){return null==p?a(p):A.call(p).slice(8,-1)}function f(p,N){var y=null!=p?typeof p[N]:"number";return!/^(?:boolean|number|string|undefined)$/.test(y)&&
("object"==y?!!p[N]:!0)}function m(p){return String(p).replace(/([ -])(?!$)/g,"$1?")}function n(p,N){var y=null;b(p,function(z,B){y=N(y,z,B,p)});return y}function t(p){function N(K){return n(K,function(D,P){var X=P.pattern||m(P);!D&&(D=RegExp("\\b"+X+" *\\d+[.\\w_]*","i").exec(p)||RegExp("\\b"+X+" *\\w+-[\\w]*","i").exec(p)||RegExp("\\b"+X+"(?:; *(?:[a-z]+[_-])?[a-z]+\\d+|[^ ();-]*)","i").exec(p))&&((D=String(P.label&&!RegExp(X,"i").test(P.label)?P.label:D).split("/"))[1]&&!/[\d.]+/.test(D[0])&&(D[0]+=
" "+D[1]),P=P.label||P,D=c(D[0].replace(RegExp(X,"i"),P).replace(RegExp("; *(?:"+P+"[_-])?","i")," ").replace(RegExp("("+P+")[-_.]?(\\w)","i"),"$1 $2")));return D})}function y(K){return n(K,function(D,P){return D||(RegExp(P+"(?:-[\\d.]+/|(?: for [\\w-]+)?[ /-])([\\d.]+[^ ();/_-]*)","i").exec(p)||0)[1]||null})}var z=k,B=p&&"object"==typeof p&&"String"!=e(p);B&&(z=p,p=null);var S=z.navigator||{},G=S.userAgent||"";p||(p=G);var da=B?!!S.likeChrome:/\bChrome\b/.test(p)&&!/internal|\n/i.test(A.toString()),
ba=B?"Object":"ScriptBridgingProxyObject",W=B?"Object":"Environment",Z=B&&z.java?"JavaPackage":e(z.java),O=B?"Object":"RuntimeObject";W=(Z=/\bJava/.test(Z)&&z.java)&&e(z.environment)==W;var L=Z?"a":"\u03b1",Y=Z?"b":"\u03b2",V=z.document||{},ea=z.operamini||z.opera,ha=x.test(ha=B&&ea?ea["[[Class]]"]:e(ea))?ha:ea=null,l,ca=p;B=[];var ia=null,fa=p==G;G=fa&&ea&&"function"==typeof ea.version&&ea.version();var R=function(K){return n(K,function(D,P){return D||RegExp("\\b"+(P.pattern||m(P))+"\\b","i").exec(p)&&
(P.label||P)})}([{label:"EdgeHTML",pattern:"Edge"},"Trident",{label:"WebKit",pattern:"AppleWebKit"},"iCab","Presto","NetFront","Tasman","KHTML","Gecko"]),C=function(K){return n(K,function(D,P){return D||RegExp("\\b"+(P.pattern||m(P))+"\\b","i").exec(p)&&(P.label||P)})}(["Adobe AIR","Arora","Avant Browser","Breach","Camino","Electron","Epiphany","Fennec","Flock","Galeon","GreenBrowser","iCab","Iceweasel","K-Meleon","Konqueror","Lunascape","Maxthon",{label:"Microsoft Edge",pattern:"Edge"},"Midori",
"Nook Browser","PaleMoon","PhantomJS","Raven","Rekonq","RockMelt",{label:"Samsung Internet",pattern:"SamsungBrowser"},"SeaMonkey",{label:"Silk",pattern:"(?:Cloud9|Silk-Accelerated)"},"Sleipnir","SlimBrowser",{label:"SRWare Iron",pattern:"Iron"},"Sunrise","Swiftfox","Waterfox","WebPositive","Opera Mini",{label:"Opera Mini",pattern:"OPiOS"},"Opera",{label:"Opera",pattern:"OPR"},"Chrome",{label:"Chrome Mobile",pattern:"(?:CriOS|CrMo)"},{label:"Firefox",pattern:"(?:Firefox|Minefield)"},{label:"Firefox for iOS",
pattern:"FxiOS"},{label:"IE",pattern:"IEMobile"},{label:"IE",pattern:"MSIE"},"Safari"]),Q=N([{label:"BlackBerry",pattern:"BB10"},"BlackBerry",{label:"Galaxy S",pattern:"GT-I9000"},{label:"Galaxy S2",pattern:"GT-I9100"},{label:"Galaxy S3",pattern:"GT-I9300"},{label:"Galaxy S4",pattern:"GT-I9500"},{label:"Galaxy S5",pattern:"SM-G900"},{label:"Galaxy S6",pattern:"SM-G920"},{label:"Galaxy S6 Edge",pattern:"SM-G925"},{label:"Galaxy S7",pattern:"SM-G930"},{label:"Galaxy S7 Edge",pattern:"SM-G935"},"Google TV",
"Lumia","iPad","iPod","iPhone","Kindle",{label:"Kindle Fire",pattern:"(?:Cloud9|Silk-Accelerated)"},"Nexus","Nook","PlayBook","PlayStation Vita","PlayStation","TouchPad","Transformer",{label:"Wii U",pattern:"WiiU"},"Wii","Xbox One",{label:"Xbox 360",pattern:"Xbox"},"Xoom"]),T=function(K){return n(K,function(D,P,X){return D||(P[Q]||P[/^[a-z]+(?: +[a-z]+\b)*/i.exec(Q)]||RegExp("\\b"+m(X)+"(?:\\b|\\w*\\d)","i").exec(p))&&X})}({Apple:{iPad:1,iPhone:1,iPod:1},Archos:{},Amazon:{Kindle:1,"Kindle Fire":1},
Asus:{Transformer:1},"Barnes & Noble":{Nook:1},BlackBerry:{PlayBook:1},Google:{"Google TV":1,Nexus:1},HP:{TouchPad:1},HTC:{},LG:{},Microsoft:{Xbox:1,"Xbox One":1},Motorola:{Xoom:1},Nintendo:{"Wii U":1,Wii:1},Nokia:{Lumia:1},Samsung:{"Galaxy S":1,"Galaxy S2":1,"Galaxy S3":1,"Galaxy S4":1},Sony:{PlayStation:1,"PlayStation Vita":1}}),E=function(K){return n(K,function(D,P){var X=P.pattern||m(P);if(!D&&(D=RegExp("\\b"+X+"(?:/[\\d.]+|[ \\w.]*)","i").exec(p))){var aa=D,h=P.label||P,g={"10.0":"10","6.4":"10 Technical Preview",
"6.3":"8.1","6.2":"8","6.1":"Server 2008 R2 / 7","6.0":"Server 2008 / Vista","5.2":"Server 2003 / XP 64-bit","5.1":"XP","5.01":"2000 SP1","5.0":"2000","4.0":"NT","4.90":"ME"};X&&h&&/^Win/i.test(aa)&&!/^Windows Phone /i.test(aa)&&(g=g[/[\d.]+$/.exec(aa)])&&(aa="Windows "+g);aa=String(aa);X&&h&&(aa=aa.replace(RegExp(X,"i"),h));D=aa=c(aa.replace(/ ce$/i," CE").replace(/\bhpw/i,"web").replace(/\bMacintosh\b/,"Mac OS").replace(/_PowerPC\b/i," OS").replace(/\b(OS X) [^ \d]+/i,"$1").replace(/\bMac (OS X)\b/,
"$1").replace(/\/(\d)/," $1").replace(/_/g,".").replace(/(?: BePC|[ .]*fc[ \d.]+)$/i,"").replace(/\bx86\.64\b/gi,"x86_64").replace(/\b(Windows Phone) OS\b/,"$1").replace(/\b(Chrome OS \w+) [\d.]+\b/,"$1").split(" on ")[0])}return D})}(["Windows Phone","Android","CentOS",{label:"Chrome OS",pattern:"CrOS"},"Debian","Fedora","FreeBSD","Gentoo","Haiku","Kubuntu","Linux Mint","OpenBSD","Red Hat","SuSE","Ubuntu","Xubuntu","Cygwin","Symbian OS","hpwOS","webOS ","webOS","Tablet OS","Tizen","Linux","Mac OS X",
"Macintosh","Mac","Windows 98;","Windows "]);R&&(R=[R]);T&&!Q&&(Q=N([T]));if(l=/\bGoogle TV\b/.exec(Q))Q=l[0];/\bSimulator\b/i.test(p)&&(Q=(Q?Q+" ":"")+"Simulator");"Opera Mini"==C&&/\bOPiOS\b/.test(p)&&B.push("running in Turbo/Uncompressed mode");"IE"==C&&/\blike iPhone OS\b/.test(p)?(l=t(p.replace(/like iPhone OS/,"")),T=l.manufacturer,Q=l.product):/^iP/.test(Q)?(C||(C="Safari"),E="iOS"+((l=/ OS ([\d_]+)/i.exec(p))?" "+l[1].replace(/_/g,"."):"")):"Konqueror"!=C||/buntu/i.test(E)?T&&"Google"!=T&&
(/Chrome/.test(C)&&!/\bMobile Safari\b/i.test(p)||/\bVita\b/.test(Q))||/\bAndroid\b/.test(E)&&/^Chrome/.test(C)&&/\bVersion\//i.test(p)?(C="Android Browser",E=/\bAndroid\b/.test(E)?E:"Android"):"Silk"==C?(/\bMobi/i.test(p)||(E="Android",B.unshift("desktop mode")),/Accelerated *= *true/i.test(p)&&B.unshift("accelerated")):"PaleMoon"==C&&(l=/\bFirefox\/([\d.]+)\b/.exec(p))?B.push("identifying as Firefox "+l[1]):"Firefox"==C&&(l=/\b(Mobile|Tablet|TV)\b/i.exec(p))?(E||(E="Firefox OS"),Q||(Q=l[1])):!C||
(l=!/\bMinefield\b/i.test(p)&&/\b(?:Firefox|Safari)\b/.exec(C))?(C&&!Q&&/[\/,]|^[^(]+?\)/.test(p.slice(p.indexOf(l+"/")+8))&&(C=null),(l=Q||T||E)&&(Q||T||/\b(?:Android|Symbian OS|Tablet OS|webOS)\b/.test(E))&&(C=/[a-z]+(?: Hat)?/i.exec(/\bAndroid\b/.test(E)?E:l)+" Browser")):"Electron"==C&&(l=(/\bChrome\/([\d.]+)\b/.exec(p)||0)[1])&&B.push("Chromium "+l):E="Kubuntu";G||(G=y(["(?:Cloud9|CriOS|CrMo|Edge|FxiOS|IEMobile|Iron|Opera ?Mini|OPiOS|OPR|Raven|SamsungBrowser|Silk(?!/[\\d.]+$))","Version",m(C),
"(?:Firefox|Minefield|NetFront)"]));if(l="iCab"==R&&3<parseFloat(G)&&"WebKit"||/\bOpera\b/.test(C)&&(/\bOPR\b/.test(p)?"Blink":"Presto")||/\b(?:Midori|Nook|Safari)\b/i.test(p)&&!/^(?:Trident|EdgeHTML)$/.test(R)&&"WebKit"||!R&&/\bMSIE\b/i.test(p)&&("Mac OS"==E?"Tasman":"Trident")||"WebKit"==R&&/\bPlayStation\b(?! Vita\b)/i.test(C)&&"NetFront")R=[l];"IE"==C&&(l=(/; *(?:XBLWP|ZuneWP)(\d+)/i.exec(p)||0)[1])?(C+=" Mobile",E="Windows Phone "+(/\+$/.test(l)?l:l+".x"),B.unshift("desktop mode")):/\bWPDesktop\b/i.test(p)?
(C="IE Mobile",E="Windows Phone 8.x",B.unshift("desktop mode"),G||(G=(/\brv:([\d.]+)/.exec(p)||0)[1])):"IE"!=C&&"Trident"==R&&(l=/\brv:([\d.]+)/.exec(p))&&(C&&B.push("identifying as "+C+(G?" "+G:"")),C="IE",G=l[1]);if(fa){if(f(z,"global"))if(Z&&(l=Z.lang.System,ca=l.getProperty("os.arch"),E=E||l.getProperty("os.name")+" "+l.getProperty("os.version")),W){try{G=z.require("ringo/engine").version.join("."),C="RingoJS"}catch(K){(l=z.system)&&l.global.system==z.system&&(C="Narwhal",E||(E=l[0].os||null))}C||
(C="Rhino")}else"object"==typeof z.process&&!z.process.browser&&(l=z.process)&&("object"==typeof l.versions&&("string"==typeof l.versions.electron?(B.push("Node "+l.versions.node),C="Electron",G=l.versions.electron):"string"==typeof l.versions.nw&&(B.push("Chromium "+G,"Node "+l.versions.node),C="NW.js",G=l.versions.nw)),C||(C="Node.js",ca=l.arch,E=l.platform,G=(G=/[\d.]+/.exec(l.version))?G[0]:null));else e(l=z.runtime)==ba?(C="Adobe AIR",E=l.flash.system.Capabilities.os):e(l=z.phantom)==O?(C="PhantomJS",
G=(l=l.version||null)&&l.major+"."+l.minor+"."+l.patch):"number"==typeof V.documentMode&&(l=/\bTrident\/(\d+)/i.exec(p))?(G=[G,V.documentMode],(l=+l[1]+4)!=G[1]&&(B.push("IE "+G[1]+" mode"),R&&(R[1]=""),G[1]=l),G="IE"==C?String(G[1].toFixed(1)):G[0]):"number"==typeof V.documentMode&&/^(?:Chrome|Firefox)\b/.test(C)&&(B.push("masking as "+C+" "+G),C="IE",G="11.0",R=["Trident"],E="Windows");E=E&&c(E)}G&&(l=/(?:[ab]|dp|pre|[ab]\d+pre)(?:\d+\+?)?$/i.exec(G)||/(?:alpha|beta)(?: ?\d)?/i.exec(p+";"+(fa&&
S.appMinorVersion))||/\bMinefield\b/i.test(p)&&"a")&&(ia=/b/i.test(l)?"beta":"alpha",G=G.replace(RegExp(l+"\\+?$"),"")+("beta"==ia?Y:L)+(/\d+\+?/.exec(l)||""));if("Fennec"==C||"Firefox"==C&&/\b(?:Android|Firefox OS)\b/.test(E))C="Firefox Mobile";else if("Maxthon"==C&&G)G=G.replace(/\.[\d.]+/,".x");else if(/\bXbox\b/i.test(Q))"Xbox 360"==Q&&(E=null),"Xbox 360"==Q&&/\bIEMobile\b/.test(p)&&B.unshift("mobile mode");else if(!/^(?:Chrome|IE|Opera)$/.test(C)&&(!C||Q||/Browser|Mobi/.test(C))||"Windows CE"!=
E&&!/Mobi/i.test(p))if("IE"==C&&fa)try{null===z.external&&B.unshift("platform preview")}catch(K){B.unshift("embedded")}else(/\bBlackBerry\b/.test(Q)||/\bBB10\b/.test(p))&&(l=(RegExp(Q.replace(/ +/g," *")+"/([.\\d]+)","i").exec(p)||0)[1]||G)?(l=[l,/BB10/.test(p)],E=(l[1]?(Q=null,T="BlackBerry"):"Device Software")+" "+l[0],G=null):this!=d&&"Wii"!=Q&&(fa&&ea||/Opera/.test(C)&&/\b(?:MSIE|Firefox)\b/i.test(p)||"Firefox"==C&&/\bOS X (?:\d+\.){2,}/.test(E)||"IE"==C&&(E&&!/^Win/.test(E)&&5.5<G||/\bWindows XP\b/.test(E)&&
8<G||8==G&&!/\bTrident\b/.test(p)))&&!x.test(l=t.call(d,p.replace(x,"")+";"))&&l.name&&(l="ing as "+l.name+((l=l.version)?" "+l:""),x.test(C)?(/\bIE\b/.test(l)&&"Mac OS"==E&&(E=null),l="identify"+l):(l="mask"+l,C=ha?c(ha.replace(/([a-z])([A-Z])/g,"$1 $2")):"Opera",/\bIE\b/.test(l)&&(E=null),fa||(G=null)),R=["Presto"],B.push(l));else C+=" Mobile";if(l=(/\bAppleWebKit\/([\d.]+\+?)/i.exec(p)||0)[1]){l=[parseFloat(l.replace(/\.(\d)$/,".0$1")),l];if("Safari"==C&&"+"==l[1].slice(-1))C="WebKit Nightly",
ia="alpha",G=l[1].slice(0,-1);else if(G==l[1]||G==(l[2]=(/\bSafari\/([\d.]+\+?)/i.exec(p)||0)[1]))G=null;l[1]=(/\bChrome\/([\d.]+)/i.exec(p)||0)[1];537.36==l[0]&&537.36==l[2]&&28<=parseFloat(l[1])&&"WebKit"==R&&(R=["Blink"]);fa&&(da||l[1])?(R&&(R[1]="like Chrome"),l=l[1]||(l=l[0],530>l?1:532>l?2:532.05>l?3:533>l?4:534.03>l?5:534.07>l?6:534.1>l?7:534.13>l?8:534.16>l?9:534.24>l?10:534.3>l?11:535.01>l?12:535.02>l?"13+":535.07>l?15:535.11>l?16:535.19>l?17:536.05>l?18:536.1>l?19:537.01>l?20:537.11>l?"21+":
537.13>l?23:537.18>l?24:537.24>l?25:537.36>l?26:"Blink"!=R?"27":"28")):(R&&(R[1]="like Safari"),l=(l=l[0],400>l?1:500>l?2:526>l?3:533>l?4:534>l?"4+":535>l?5:537>l?6:538>l?7:601>l?8:"8"));R&&(R[1]+=" "+(l+="number"==typeof l?".x":/[.+]/.test(l)?"":"+"));"Safari"==C&&(!G||45<parseInt(G))&&(G=l)}"Opera"==C&&(l=/\bzbov|zvav$/.exec(E))?(C+=" ",B.unshift("desktop mode"),"zvav"==l?(C+="Mini",G=null):C+="Mobile",E=E.replace(RegExp(" *"+l+"$"),"")):"Safari"==C&&/\bChrome\b/.exec(R&&R[1])&&(B.unshift("desktop mode"),
C="Chrome Mobile",G=null,/\bOS X\b/.test(E)?(T="Apple",E="iOS 4.3+"):E=null);G&&0==G.indexOf(l=/[\d.]+$/.exec(E))&&-1<p.indexOf("/"+l+"-")&&(E=String(E.replace(l,"")).replace(/^ +| +$/g,""));R&&!/\b(?:Avant|Nook)\b/.test(C)&&(/Browser|Lunascape|Maxthon/.test(C)||"Safari"!=C&&/^iOS/.test(E)&&/\bSafari\b/.test(R[1])||/^(?:Adobe|Arora|Breach|Midori|Opera|Phantom|Rekonq|Rock|Samsung Internet|Sleipnir|Web)/.test(C)&&R[1])&&(l=R[R.length-1])&&B.push(l);B.length&&(B=["("+B.join("; ")+")"]);T&&Q&&0>Q.indexOf(T)&&
B.push("on "+T);Q&&B.push((/^on /.test(B[B.length-1])?"":"on ")+Q);if(E){var ka=(l=/ ([\d.+]+)$/.exec(E))&&"/"==E.charAt(E.length-l[0].length-1);E={architecture:32,family:l&&!ka?E.replace(l[0],""):E,version:l?l[1]:null,toString:function(){var K=this.version;return this.family+(K&&!ka?" "+K:"")+(64==this.architecture?" 64-bit":"")}}}(l=/\b(?:AMD|IA|Win|WOW|x86_|x)64\b/i.exec(ca))&&!/\bi686\b/i.test(ca)?(E&&(E.architecture=64,E.family=E.family.replace(RegExp(" *"+l),"")),C&&(/\bWOW64\b/i.test(p)||fa&&
/\w(?:86|32)$/.test(S.cpuClass||S.platform)&&!/\bWin64; x64\b/i.test(p))&&B.unshift("32-bit")):E&&/^OS X/.test(E.family)&&"Chrome"==C&&39<=parseFloat(G)&&(E.architecture=64);p||(p=null);z={};z.description=p;z.layout=R&&R[0];z.manufacturer=T;z.name=C;z.prerelease=ia;z.product=Q;z.ua=p;z.version=C&&G;z.os=E||{architecture:null,family:null,version:null,toString:function(){return"null"}};z.parse=t;z.toString=function(){return this.description||""};z.version&&B.unshift(G);z.name&&B.unshift(C);E&&C&&(E!=
String(E).split(" ")[0]||E!=C.split(" ")[0]&&!Q)&&B.push(Q?"("+E+")":"on "+E);B.length&&(z.description=B.join(" "));return z}var r={"function":!0,object:!0},k=r[typeof window]&&window||this,u=r[typeof exports]&&exports;r=r[typeof module]&&module&&!module.nodeType&&module;var q=u&&r&&"object"==typeof global&&global;!q||q.global!==q&&q.window!==q&&q.self!==q||(k=q);var F=Math.pow(2,53)-1,x=/\bOpera/;q=Object.prototype;var H=q.hasOwnProperty,A=q.toString,J=t();"function"==typeof define&&"object"==typeof define.amd&&
define.amd?(k.platform=J,define(function(){return J})):u&&r?d(J,function(p,N){u[N]=p}):k.platform=J}).call(this);
function buildIOSMeta(){for(var a=[{name:"viewport",content:"width=device-width, height=device-height, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no"},{name:"apple-mobile-web-app-capable",content:"yes"},{name:"apple-mobile-web-app-status-bar-style",content:"black"}],b=0;b<a.length;b++){var c=document.createElement("meta");c.name=a[b].name;c.content=a[b].content;var d=window.document.head.querySelector('meta[name="'+c.name+'"]');d&&d.parentNode.removeChild(d);window.document.head.appendChild(c)}}
function hideIOSFullscreenPanel(){jQuery(".xxx-ios-fullscreen-message").css("display","none");jQuery(".xxx-ios-fullscreen-scroll").css("display","none");jQuery(".xxx-game-iframe-full").removeClass("xxx-game-iframe-iphone-se")}function buildIOSFullscreenPanel(){jQuery("body").append('<div class="xxx-ios-fullscreen-message"><div class="xxx-ios-fullscreen-swipe"></div></div><div class="xxx-ios-fullscreen-scroll"></div>')}
function showIOSFullscreenPanel(){jQuery(".xxx-ios-fullscreen-message").css("display","block");jQuery(".xxx-ios-fullscreen-scroll").css("display","block")}
function __iosResize(){window.scrollTo(0,0);console.log(window.devicePixelRatio);console.log(window.innerWidth);console.log(window.innerHeight);if("iPhone"===platform.product)switch(window.devicePixelRatio){case 2:switch(window.innerWidth){case 568:320!==window.innerHeight&&jQuery(".xxx-game-iframe-full").addClass("xxx-game-iframe-iphone-se");break;case 667:375===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;case 808:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();
break;default:hideIOSFullscreenPanel()}break;case 3:switch(window.innerWidth){case 736:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;case 724:375===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;case 808:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;default:hideIOSFullscreenPanel()}break;default:hideIOSFullscreenPanel()}}function iosResize(){__iosResize();setTimeout(function(){__iosResize()},500)}
function iosInIframe(){try{return window.self!==window.top}catch(a){return!0}}function isIOSLessThen13(){var a=platform.os,b=a.family.toLowerCase();a=parseFloat(a.version);return"ios"===b&&13>a?!0:!1}$(document).ready(function(){platform&&"iPhone"===platform.product&&"safari"===platform.name.toLowerCase()&&isIOSLessThen13()&&!iosInIframe()&&(buildIOSFullscreenPanel(),buildIOSMeta())});
jQuery(window).resize(function(){platform&&"iPhone"===platform.product&&"safari"===platform.name.toLowerCase()&&isIOSLessThen13()&&!iosInIframe()&&iosResize()});var s_iOffsetX,s_iOffsetY,s_iScaleFactor=1,s_bIsIphone=!1,s_bFocus=!0;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}
function getSize(a){var b=a.toLowerCase(),c=window.document,d=c.documentElement;if(void 0===window["inner"+a])a=d["client"+a];else if(window["inner"+a]!=d["client"+a]){var e=c.createElement("body");e.id="vpw-test-b";e.style.cssText="overflow:scroll";var f=c.createElement("div");f.id="vpw-test-d";f.style.cssText="position:absolute;top:-1000px";f.innerHTML="<style>@media("+b+":"+d["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+b+":7px!important}}</style>";e.appendChild(f);d.insertBefore(e,c.head);
a=7==f["offset"+a]?d["client"+a]:window["inner"+a];d.removeChild(e)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}
function isIpad(){var a=-1!==navigator.userAgent.toLowerCase().indexOf("ipad");return!a&&navigator.userAgent.match(/Mac/)&&navigator.maxTouchPoints&&2<navigator.maxTouchPoints?!0:a}function isMobile(){return isIpad()?!0:jQuery.browser.mobile}function isIOS(){var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");for(-1!==navigator.userAgent.toLowerCase().indexOf("iphone")&&(s_bIsIphone=!0);a.length;)if(navigator.platform===a.pop())return!0;return s_bIsIphone=!1}
function isChrome(){return/Chrome/.test(navigator.userAgent)&&/Google Inc/.test(navigator.vendor)}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a=null!==platform.name&&"safari"===platform.name.toLowerCase()?getIOSWindowHeight():getSize("Height");var b=getSize("Width");s_bFocus&&_checkOrientation(b,a);var c=Math.min(a/CANVAS_HEIGHT,b/CANVAS_WIDTH),d=Math.round(CANVAS_WIDTH*c);c=Math.round(CANVAS_HEIGHT*c);if(c<a){var e=a-c;c+=e;d+=CANVAS_WIDTH/CANVAS_HEIGHT*e}else d<b&&(e=b-d,d+=e,c+=CANVAS_HEIGHT/CANVAS_WIDTH*e);e=a/2-c/2;var f=b/2-d/2,m=CANVAS_WIDTH/d;if(f*m<-EDGEBOARD_X||
e*m<-EDGEBOARD_Y)c=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),b/(CANVAS_WIDTH-2*EDGEBOARD_X)),d=Math.round(CANVAS_WIDTH*c),c=Math.round(CANVAS_HEIGHT*c),e=(a-c)/2,f=(b-d)/2,m=CANVAS_WIDTH/d;s_iOffsetX=-1*f*m;s_iOffsetY=-1*e*m;0<=e&&(s_iOffsetY=0);0<=f&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_bIsIphone?(canvas=document.getElementById("canvas"),s_oStage.canvas.width=2*d,s_oStage.canvas.height=
2*c,canvas.style.width=d+"px",canvas.style.height=c+"px",b=Math.min(d/CANVAS_WIDTH,c/CANVAS_HEIGHT),s_iScaleFactor=2*b,s_oStage.scaleX=s_oStage.scaleY=2*b):s_bMobile||isChrome()?($("#canvas").css("width",d+"px"),$("#canvas").css("height",c+"px")):(s_oStage.canvas.width=d,s_oStage.canvas.height=c,s_iScaleFactor=Math.min(d/CANVAS_WIDTH,c/CANVAS_HEIGHT),s_oStage.scaleX=s_oStage.scaleY=s_iScaleFactor);0>e||(e=(a-c)/2);$("#canvas").css("top",e+"px");$("#canvas").css("left",f+"px");fullscreenHandler()}}
function _checkOrientation(a,b){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(a>b?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),
s_oMain.stopUpdate()))}function createBitmap(a,b,c){var d=new createjs.Bitmap(a),e=new createjs.Shape;b&&c?e.graphics.beginFill("#fff").drawRect(0,0,b,c):e.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);d.hitArea=e;return d}function createSprite(a,b,c,d,e,f){a=null!==b?new createjs.Sprite(a,b):new createjs.Sprite(a);b=new createjs.Shape;b.graphics.beginFill("#000000").drawRect(-c,-d,e,f);a.hitArea=b;return a}
function randomFloatBetween(a,b,c){"undefined"===typeof c&&(c=2);return parseFloat(Math.min(a+Math.random()*(b-a),b).toFixed(c))}function shuffle(a){for(var b=a.length,c,d;0!==b;)d=Math.floor(Math.random()*b),--b,c=a[b],a[b]=a[d],a[d]=c;return a}function formatTime(a){a/=1E3;var b=Math.floor(a/60);a=parseFloat(a-60*b).toFixed(1);var c="";c=10>b?c+("0"+b+":"):c+(b+":");return 10>a?c+("0"+a):c+a}function formatValue(a){return TEXT_CURRENCY+a.toFixed(2).replace(/(\d)(?=(\d{3})+(?!\d))/g,"$1,")}
Array.prototype.sortOn=function(){var a=this.slice();if(!arguments.length)return a.sort();var b=Array.prototype.slice.call(arguments);return a.sort(function(c,d){for(var e=b.slice(),f=e.shift();c[f]==d[f]&&e.length;)f=e.shift();return c[f]==d[f]?0:c[f]>d[f]?1:-1})};function roundDecimal(a,b){var c=Math.pow(10,b);return Math.round(c*a)/c}function tweenVectors(a,b,c,d){d.set(a.getX()+c*(b.getX()-a.getX()),a.getY()+c*(b.getY()-a.getY()));return d}
function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3===a.nodeType&&(a=a.parentNode);var b=document.createEvent("MouseEvents");b.initEvent("click",!0,!0);a.dispatchEvent(b)}}};
(function(){function a(c){var d={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};c=c||window.event;c.type in d?document.body.className=d[c.type]:(document.body.className=this[b]?"hidden":"visible","hidden"===document.body.className?(s_oMain.stopUpdate(),s_bFocus=!1):(s_oMain.startUpdate(),s_bFocus=!0))}var b="hidden";b in document?document.addEventListener("visibilitychange",a):(b="mozHidden")in document?document.addEventListener("mozvisibilitychange",
a):(b="webkitHidden")in document?document.addEventListener("webkitvisibilitychange",a):(b="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();function playSound(a,b,c){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(s_aSounds[a].play(),s_aSounds[a].volume(b),s_aSounds[a].loop(c),s_aSounds[a]):null}
function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].stop()}function setVolume(a,b){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].volume(b)}function setMute(a,b){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].mute(b)}function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(a){for(var b=window.location.search.substring(1).split("&"),c=0;c<b.length;c++){var d=b[c].split("=");if(d[0]==a)return d[1]}}function fullscreenHandler(){ENABLE_FULLSCREEN&&screenfull.isEnabled&&(s_bFullscreen=screenfull.isFullscreen,null!==s_oInterface&&s_oInterface.resetFullscreenBut(),null!==s_oMenu&&s_oMenu.resetFullscreenBut())}
if(screenfull.isEnabled)screenfull.on("change",function(){s_bFullscreen=screenfull.isFullscreen;null!==s_oInterface&&s_oInterface.resetFullscreenBut();null!==s_oMenu&&s_oMenu.resetFullscreenBut()});
function CSpriteLibrary(){var a={},b,c,d,e,f,m;this.init=function(n,t,r){b={};d=c=0;e=n;f=t;m=r};this.addSprite=function(n,t){if(!a.hasOwnProperty(n)){var r=new Image;a[n]=b[n]={szPath:t,oSprite:r,bLoaded:!1};c++}};this.getSprite=function(n){return a.hasOwnProperty(n)?a[n].oSprite:null};this._onSpritesLoaded=function(){c=0;f.call(m)};this._onSpriteLoaded=function(){e.call(m);++d===c&&this._onSpritesLoaded()};this.loadSprites=function(){for(var n in b)b[n].oSprite.oSpriteLibrary=this,b[n].oSprite.szKey=
n,b[n].oSprite.onload=function(){this.oSpriteLibrary.setLoaded(this.szKey);this.oSpriteLibrary._onSpriteLoaded(this.szKey)},b[n].oSprite.onerror=function(t){var r=t.currentTarget;setTimeout(function(){b[r.szKey].oSprite.src=b[r.szKey].szPath},500)},b[n].oSprite.src=b[n].szPath};this.setLoaded=function(n){a[n].bLoaded=!0};this.isLoaded=function(n){return a[n].bLoaded};this.getNumSprites=function(){return c}}
var CANVAS_WIDTH=1700,CANVAS_HEIGHT=768,EDGEBOARD_X=250,EDGEBOARD_Y=0,FPS=30,FPS_TIME=1E3/FPS,DISABLE_SOUND_MOBILE=!1,FONT_GAME_1="arialbold",FONT_GAME_2="Digital-7",STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,STATE_GAME_WAITING_FOR_BET=0,STATE_GAME_DEALING=1,STATE_GAME_PLAYER_TURN=2,STATE_GAME_SPLIT_HAND=3,STATE_GAME_SHOWDOWN=4,STATE_GAME_DISTRIBUTE_FICHES=5,STATE_GAME_SHOW_WINNER=6,STATE_CARD_DEALING=0,STATE_CARD_WAIT_USER=1,STATE_CARD_SPLITTING=2,STATE_CARD_REMOVING=3,ON_MOUSE_DOWN=
0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,ASSIGN_FICHES="ASSIGN_FICHES",END_HAND="END_HAND",ON_CARD_SHOWN="ON_CARD_SHOWN",ON_CARD_ANIMATION_ENDING="ON_CARD_ANIMATION_ENDING",ON_CARD_TO_REMOVE="ON_CARD_TO_REMOVE",SPLIT_CARD_END_ANIM="SPLIT_CARD_END_ANIM",NUM_FICHES=6,CARD_WIDTH=66,CARD_HEIGHT=102,MIN_BET,MAX_BET,TOTAL_MONEY,FICHE_WIDTH,WIN_OCCURRENCE,BET_OCCURRENCE,COLOR_FICHES="#ff7706 #ffb600 #000 #06a800 #d50000 #444444".split(" "),CHIP_VALUES,TIME_FICHES_MOV=
600,TIME_CARD_DEALING=250,TIME_CARD_REMOVE=1E3,TIME_CARD_SPLIT=500,TIME_SHOW_FINAL_CARDS=4E3,TIME_END_HAND,BET_TIME=1E4,AD_SHOW_COUNTER,NUM_DECKS=4,PAYOUT_MULT,FIVE_ACES=0,ROYAL_FLUSH=1,STRAIGHT_FLUSH=2,FOUR_OF_A_KIND=3,FULL_HOUSE=4,FLUSH=5,STRAIGHT=6,THREE_OF_A_KIND=7,TWO_PAIR=8,ONE_PAIR=9,HIGH_CARD=10,NO_HAND=11,CARD_TWO=2,CARD_THREE=3,CARD_FOUR=4,CARD_FIVE=5,CARD_SIX=6,CARD_SEVEN=7,CARD_EIGHT=8,CARD_NINE=9,CARD_TEN=10,CARD_JACK=11,CARD_QUEEN=12,CARD_KING=13,CARD_ACE=14,CARD_JOKER=15,POS_BET,MULTIPLIERS=
[],ENABLE_FULLSCREEN,ENABLE_CHECK_ORIENTATION,SHOW_CREDITS,TEXT_DEAL="發牌",TEXT_MIN_BET="最小注",TEXT_MAX_BET="最大注",TEXT_RECHARGE="儲值",TEXT_EXIT="退出",TEXT_MONEY="籌碼",TEXT_CURRENCY="$",TEXT_FOLD="蓋牌",TEXT_HIGH_HAND="高牌",TEXT_LOW_HAND="低牌",TEXT_HOUSE_WAY="系統安排",TEXT_CREDITS_DEVELOPED="DEVELOPED BY",TEXT_PRELOADER_CONTINUE="開始",TEXT_DISPLAY_MSG_WAITING_BET="等候您的下注",TEXT_DISPLAY_MSG_PLAYER_LOSE="玩家輸去本局!",TEXT_DISPLAY_MSG_STANDOFF="平手",
TEXT_DISPLAY_MSG_PLAYER_WIN="玩家贏了",TEXT_DISPLAY_MSG_USER_TURN="選擇5張牌來組成高牌或由系統自動安排!",TEXT_DISPLAY_MSG_SHOWDOWN="關閉!",TEXT_DISPLAY_MSG_DEALING="發牌中...",TEXT_NO_MONEY="您沒有足夠的籌碼!!!",TEXT_HAND_WON_PLAYER="玩家贏得此局",TEXT_HAND_WON_DEALER="莊家贏得此局",TEXT_ERROR_MIN_BET="您的押注低於最小注!!",TEXT_ERROR_MAX_BET="您的押注高於最大注!!",TEXT_ERROR_BIGGER_LOW_HAND="不允許的安排。你的低牌不可以比你的高牌好!!",
TEXT_EVALUATOR="5張A;同花大順;同花順;鐵支;葫蘆;同花;順;三條;兩對;一對;高牌;無牌".split(";"),TEXT_SHARE_IMAGE="200x200.jpg",TEXT_SHARE_TITLE="恭喜!",TEXT_SHARE_MSG1="您獲得 <strong>",TEXT_SHARE_MSG2=" 分</strong>!<br><br>與您的好友分享獲得的分數!",TEXT_SHARE_SHARE1="我的分數是 ",TEXT_SHARE_SHARE2=" 分! 您能獲得更好的分數嗎?";
function CPreloader(){var a,b,c,d,e,f,m,n,t,r;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.addSprite("200x200","./sprites/200x200.jpg");s_oSpriteLibrary.addSprite("but_start","./sprites/but_start.png");s_oSpriteLibrary.loadSprites();r=new createjs.Container;s_oStage.addChild(r)};this.unload=function(){r.removeAllChildren();t.unload()};this._onImagesLoaded=function(){};
this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var k=new createjs.Shape;k.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);r.addChild(k);k=s_oSpriteLibrary.getSprite("200x200");m=createBitmap(k);m.regX=.5*k.width;m.regY=.5*k.height;m.x=CANVAS_WIDTH/2;m.y=CANVAS_HEIGHT/2-180;r.addChild(m);n=new createjs.Shape;n.graphics.beginFill("rgba(0,0,0,0.01)").drawRoundRect(m.x-100,m.y-100,200,200,10);r.addChild(n);m.mask=n;
k=s_oSpriteLibrary.getSprite("progress_bar");d=createBitmap(k);d.x=CANVAS_WIDTH/2-k.width/2;d.y=CANVAS_HEIGHT/2+50;r.addChild(d);a=k.width;b=k.height;e=new createjs.Shape;e.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(d.x,d.y,1,b);r.addChild(e);d.mask=e;c=new createjs.Text("","40px "+FONT_GAME_1,"#fff");c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT/2+110;c.textBaseline="alphabetic";c.textAlign="center";r.addChild(c);k=s_oSpriteLibrary.getSprite("but_start");t=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/
2,k,TEXT_PRELOADER_CONTINUE,"Arial","#000","bold 50",r);t.addEventListener(ON_MOUSE_UP,this._onButStartRelease,this);t.setVisible(!1);f=new createjs.Shape;f.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);r.addChild(f);createjs.Tween.get(f).to({alpha:0},500).call(function(){createjs.Tween.removeTweens(f);r.removeChild(f)})};this._onButStartRelease=function(){s_oMain._onRemovePreloader()};this.refreshLoader=function(k){c.text=k+"%";100===k&&(s_oMain._onRemovePreloader(),c.visible=
!1,d.visible=!1);e.graphics.clear();k=Math.floor(k*a/100);e.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(d.x,d.y,k,b)};this._init()}
function CMain(a){var b,c=0,d=0,e=STATE_LOADING,f,m;this.initContainer=function(){var t=document.getElementById("canvas");s_oStage=new createjs.Stage(t);createjs.Touch.enable(s_oStage,!0);s_bMobile=isMobile();!1===s_bMobile&&s_oStage.enableMouseOver(20);s_iPrevTime=(new Date).getTime();createjs.Ticker.framerate=FPS;createjs.Ticker.addEventListener("tick",this._update);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;seekAndDestroy()?f=new CPreloader:
window.location.href="http://www.codethislab.com/contact-us.html";s_oGameSettings=new CGameSettings;b=!0};this.preloaderReady=function(){this._loadImages();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds()};this.soundLoaded=function(){c++;f.refreshLoader(Math.floor(c/d*100))};this._initSounds=function(){Howler.mute(!s_bAudioActive);s_aSoundsInfo=[];s_aSoundsInfo.push({path:"./sounds/",filename:"card",loop:!1,volume:1,ingamename:"card"});s_aSoundsInfo.push({path:"./sounds/",filename:"press_but",
loop:!1,volume:1,ingamename:"press_but"});s_aSoundsInfo.push({path:"./sounds/",filename:"chip",loop:!1,volume:1,ingamename:"chip"});s_aSoundsInfo.push({path:"./sounds/",filename:"fiche_collect",loop:!1,volume:1,ingamename:"fiche_collect"});s_aSoundsInfo.push({path:"./sounds/",filename:"win",loop:!1,volume:1,ingamename:"win"});s_aSoundsInfo.push({path:"./sounds/",filename:"lose",loop:!1,volume:1,ingamename:"lose"});d+=s_aSoundsInfo.length;s_aSounds=[];for(var t=0;t<s_aSoundsInfo.length;t++)this.tryToLoadSound(s_aSoundsInfo[t],
!1)};this.tryToLoadSound=function(t,r){setTimeout(function(){s_aSounds[t.ingamename]=new Howl({src:[t.path+t.filename+".mp3"],autoplay:!1,preload:!0,loop:t.loop,volume:t.volume,onload:s_oMain.soundLoaded,onloaderror:function(k,u){for(var q=0;q<s_aSoundsInfo.length;q++)if(k===s_aSounds[s_aSoundsInfo[q].ingamename]._sounds[0]._id){s_oMain.tryToLoadSound(s_aSoundsInfo[q],!0);break}},onplayerror:function(k){for(var u=0;u<s_aSoundsInfo.length;u++)if(k===s_aSounds[s_aSoundsInfo[u].ingamename]._sounds[0]._id){s_aSounds[s_aSoundsInfo[u].ingamename].once("unlock",
function(){s_aSounds[s_aSoundsInfo[u].ingamename].play()});break}}})},r?200:0)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_menu_bg","./sprites/but_menu_bg.png");s_oSpriteLibrary.addSprite("but_game_bg","./sprites/but_game_bg.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");
s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("card_spritesheet","./sprites/card_spritesheet.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("display_bg","./sprites/display_bg.png");s_oSpriteLibrary.addSprite("fiche_highlight","./sprites/fiche_highlight.png");s_oSpriteLibrary.addSprite("win_bg","./sprites/win_bg.png");s_oSpriteLibrary.addSprite("but_clear","./sprites/but_clear.png");s_oSpriteLibrary.addSprite("but_generic",
"./sprites/but_generic.png");s_oSpriteLibrary.addSprite("but_rebet","./sprites/but_rebet.png");s_oSpriteLibrary.addSprite("gui_bg","./sprites/gui_bg.png");s_oSpriteLibrary.addSprite("bet_ante","./sprites/bet_ante.png");s_oSpriteLibrary.addSprite("help_cursor","./sprites/help_cursor.png");s_oSpriteLibrary.addSprite("but_split","./sprites/but_split.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");s_oSpriteLibrary.addSprite("but_credits","./sprites/but_credits.png");
s_oSpriteLibrary.addSprite("logo_ctl","./sprites/logo_ctl.png");for(var t=0;t<NUM_FICHES;t++)s_oSpriteLibrary.addSprite("fiche_"+t,"./sprites/fiche_"+t+".png");d+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){c++;f.refreshLoader(Math.floor(c/d*100))};this._onAllImagesLoaded=function(){};this._onRemovePreloader=function(){f.unload();this.gotoMenu()};this.gotoMenu=function(){new CMenu;e=STATE_MENU};this.gotoGame=function(){m=new CGame(n);e=STATE_GAME};
this.gotoHelp=function(){new CHelp;e=STATE_HELP};this.stopUpdate=function(){b=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||Howler.mute(!0)};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();b=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none");(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)&&s_bAudioActive&&Howler.mute(!1)};this._update=function(t){if(b){var r=(new Date).getTime();s_iTimeElaps=r-s_iPrevTime;
s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=r;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);e===STATE_GAME&&m.update();s_oStage.update(t)}};s_oMain=this;var n=a;ENABLE_CHECK_ORIENTATION=a.check_orientation;SHOW_CREDITS=n.show_credits;ENABLE_FULLSCREEN=a.fullscreen;s_bAudioActive=a.audio_enable_on_startup;this.initContainer()}
var s_bMobile,s_bAudioActive=!0,s_bFullscreen=!1,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oGameSettings,s_aSoundsInfo;
function CTextButton(a,b,c,d,e,f,m,n){var t,r,k,u,q,F,x,H,A,J,p,N;this._init=function(y,z,B,S,G,da,ba){t=!1;r=1;q=[];F=[];N=createBitmap(B);k=B.width;u=B.height;J=new createjs.Container;J.x=y;J.y=z;J.regX=B.width/2;J.regY=B.height/2;s_bMobile||(J.cursor="pointer");J.addChild(N,p);n.addChild(J);p=new CTLText(J,10,6,B.width-20,B.height-10,ba,"center",da,G,1,0,0,S,!0,!0,!1,!1);this._initListener()};this.unload=function(){J.off("mousedown",x);J.off("pressup",H);n.removeChild(J)};this.setVisible=function(y){J.visible=
y};this.setAlign=function(y){p.textAlign=y};this.setTextX=function(y){p.x=y};this.setScale=function(y){r=J.scaleX=J.scaleY=y};this.enable=function(){t=!1;J.filters=[];J.cache(0,0,k,u)};this.disable=function(){t=!0;try{var y=(new createjs.ColorMatrix).adjustSaturation(-100);J.filters=[new createjs.ColorMatrixFilter(y)];J.cache(0,0,k,u)}catch(z){}};this._initListener=function(){x=J.on("mousedown",this.buttonDown);H=J.on("pressup",this.buttonRelease)};this.addEventListener=function(y,z,B){q[y]=z;F[y]=
B};this.addEventListenerWithParams=function(y,z,B,S){q[y]=z;F[y]=B;A=S};this.buttonRelease=function(){t||(playSound("press_but",1,!1),J.scaleX=r,J.scaleY=r,q[ON_MOUSE_UP]&&q[ON_MOUSE_UP].call(F[ON_MOUSE_UP],A))};this.buttonDown=function(){t||(J.scaleX=.9*r,J.scaleY=.9*r,q[ON_MOUSE_DOWN]&&q[ON_MOUSE_DOWN].call(F[ON_MOUSE_DOWN]))};this.setPosition=function(y,z){J.x=y;J.y=z};this.tweenPosition=function(y,z,B,S,G,da,ba){createjs.Tween.get(J).wait(S).to({x:y,y:z},B,G).call(function(){void 0!==da&&da.call(ba)})};
this.changeText=function(y){p.refreshText(y)};this.setX=function(y){J.x=y};this.setY=function(y){J.y=y};this.getButtonImage=function(){return J};this.getX=function(){return J.x};this.getY=function(){return J.y};this.getSprite=function(){return J};this.getScale=function(){return J.scaleX};this._init(a,b,c,d,e,f,m)}
function CGfxButton(a,b,c,d){var e,f,m,n,t,r=[],k,u,q;this._init=function(x,H,A){e=!1;n=[];t=[];f=A.width;m=A.height;q=createBitmap(A);q.x=x;q.y=H;q.regX=A.width/2;q.regY=A.height/2;q.cursor="pointer";F.addChild(q);this._initListener()};this.unload=function(){q.off("mousedown",k);q.off("pressup",u);F.removeChild(q)};this.setVisible=function(x){q.visible=x};this._initListener=function(){k=q.on("mousedown",this.buttonDown);u=q.on("pressup",this.buttonRelease)};this.addEventListener=function(x,H,A){n[x]=
H;t[x]=A};this.addEventListenerWithParams=function(x,H,A,J){n[x]=H;t[x]=A;r=J};this.buttonRelease=function(){e||(playSound("press_but",1,!1),n[ON_MOUSE_UP]&&n[ON_MOUSE_UP].call(t[ON_MOUSE_UP],r))};this.buttonDown=function(){e||n[ON_MOUSE_DOWN]&&n[ON_MOUSE_DOWN].call(t[ON_MOUSE_DOWN],r)};this.setPosition=function(x,H){q.x=x;q.y=H};this.setX=function(x){q.x=x};this.setY=function(x){q.y=x};this.enable=function(){e=!1;q.filters=[];q.cache(0,0,f,m)};this.disable=function(){e=!0;try{var x=(new createjs.ColorMatrix).adjustSaturation(-100);
q.filters=[new createjs.ColorMatrixFilter(x)];q.cache(0,0,f,m)}catch(H){}};this.getButtonImage=function(){return q};this.getX=function(){return q.x};this.getY=function(){return q.y};var F=d;this._init(a,b,c);return this}
function CToggle(a,b,c,d,e){var f,m,n,t,r=[],k,u,q;this._init=function(F,x,H,A,J){n=[];t=[];var p=new createjs.SpriteSheet({images:[H],frames:{width:H.width/2,height:H.height,regX:H.width/2/2,regY:H.height/2},animations:{state_true:[0],state_false:[1]}});f=A;m=J;q=createSprite(p,"state_"+f,H.width/2/2,H.height/2,H.width/2,H.height);q.x=F;q.y=x;q.cursor="pointer";q.stop();s_oStage.addChild(q);this._initListener()};this.unload=function(){q.off("mousedown",k);q.off("pressup",u);s_oStage.removeChild(q)};
this._initListener=function(){k=q.on("mousedown",this.buttonDown);u=q.on("pressup",this.buttonRelease)};this.addEventListener=function(F,x,H){n[F]=x;t[F]=H};this.addEventListenerWithParams=function(F,x,H,A){n[F]=x;t[F]=H;r=A};this.setActive=function(F){f=F;q.gotoAndStop("state_"+f)};this.buttonRelease=function(){q.scaleX=1;q.scaleY=1;playSound("press_but",1,!1);m&&(f=!f,q.gotoAndStop("state_"+f));n[ON_MOUSE_UP]&&n[ON_MOUSE_UP].call(t[ON_MOUSE_UP],r)};this.buttonDown=function(){q.scaleX=.9;q.scaleY=
.9;n[ON_MOUSE_DOWN]&&n[ON_MOUSE_DOWN].call(t[ON_MOUSE_DOWN],r)};this.setPosition=function(F,x){q.x=F;q.y=x};this.setVisible=function(F){q.visible=F};this.getY=function(){return q.y};this._init(a,b,c,d,e)}
function CMenu(){var a,b,c,d,e,f,m,n,t,r,k,u,q=null,F=null;this._init=function(){m=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(m);var x=s_oSpriteLibrary.getSprite("but_menu_bg");n=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-164,x,s_oStage);n.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)x=s_oSpriteLibrary.getSprite("audio_icon"),e=CANVAS_WIDTH-x.width/4-10,f=x.height/2+10,r=new CToggle(e,f,x,s_bAudioActive,!0),r.addEventListener(ON_MOUSE_UP,
this._onAudioToggle,this);SHOW_CREDITS?(x=s_oSpriteLibrary.getSprite("but_credits"),a=x.height/2+10,b=x.height/2+10,t=new CGfxButton(a,b,x,s_oStage),t.addEventListener(ON_MOUSE_UP,this._onButCreditsRelease,this),c=a+x.width+10,d=b):(c=x.height/2+10,d=x.height/2+10);x=window.document;var H=x.documentElement;q=H.requestFullscreen||H.mozRequestFullScreen||H.webkitRequestFullScreen||H.msRequestFullscreen;F=x.exitFullscreen||x.mozCancelFullScreen||x.webkitExitFullscreen||x.msExitFullscreen;!1===ENABLE_FULLSCREEN&&
(q=!1);q&&screenfull.isEnabled&&(x=s_oSpriteLibrary.getSprite("but_fullscreen"),u=new CToggle(c,d,x,s_bFullscreen,!0),u.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));k=new createjs.Shape;k.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(k);createjs.Tween.get(k).to({alpha:0},400).call(function(){k.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(x,H){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||r.setPosition(e-
x,H+f);q&&screenfull.isEnabled&&u.setPosition(c+x,d+H);SHOW_CREDITS&&t.setPosition(a+x,b+H)};this.unload=function(){n.unload();n=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)r.unload(),r=null;SHOW_CREDITS&&t.unload();q&&screenfull.isEnabled&&u.unload();s_oStage.removeAllChildren();s_oMenu=null};this._onButPlayRelease=function(){this.unload();s_oMain.gotoGame();$(s_oMain).trigger("start_session")};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButCreditsRelease=
function(){new CCreditsPanel};this.resetFullscreenBut=function(){q&&screenfull.isEnabled&&u.setActive(s_bFullscreen)};this._onFullscreenRelease=function(){s_bFullscreen?F.call(window.document):q.call(window.document.documentElement);sizeHandler()};s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(a){var b=!1,c,d,e,f,m,n,t,r,k,u,q,F,x,H,A,J,p,N,y,z,B,S,G,da,ba,W,Z,O,L,Y,V,ea,ha,l,ca,ia,fa,R,C,Q,T,E,ka,K,D,P,X;this._init=function(){e=MAX_BET;f=-1;m=u=d=0;s_oTweenController=new CTweenController;ka=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(ka);K=new CInterface(TOTAL_MONEY);Q=new createjs.Container;s_oStage.addChild(Q);T=new CHandEvaluator;D=new CSeat;D.setCredit(TOTAL_MONEY);E=new CHelpCursor(620,390,s_oSpriteLibrary.getSprite("help_cursor"),s_oStage);
this.reset(!1);ha=new CVector2;ha.set(1214,228);l=new CVector2(CANVAS_WIDTH/2-115,250);R=new CVector2(l.getX()-65,l.getY());C=new CVector2(l.getX()+215,l.getY());ca=new CVector2;ca.set(418,820);ia=new CVector2;ia.set(0,-CANVAS_HEIGHT);fa=new CVector2(454,230);X=new CGameOver;D.getCredit()<s_oGameSettings.getFichesValueAt(0)?(this._gameOver(),this.changeState(-1)):b=!0;ea=new CVector2(ha.getX(),ha.getY());P=new CMsgBox;this.changeState(STATE_GAME_WAITING_FOR_BET)};this.unload=function(){b=!1;for(var h=
0;h<W.length;h++)W[h].unload();K.unload();X.unload();P.unload();s_oStage.removeAllChildren()};this.reset=function(h){k=t=m=d=0;D.reset();W=[];W.splice(0);Z=[];L=[];K.reset();K.enableBetFiches(h);this.shuffleCard()};this.shuffleCard=function(){O=[];O=s_oGameSettings.getShuffledCardDeck()};this.changeState=function(h){f=h;switch(h){case STATE_GAME_WAITING_FOR_BET:K.displayMsg(TEXT_DISPLAY_MSG_WAITING_BET,TEXT_MIN_BET+": "+formatValue(MIN_BET)+"\n"+TEXT_MAX_BET+": "+formatValue(MAX_BET));break;case STATE_GAME_DEALING:K.disableButtons();
K.displayMsg(TEXT_DISPLAY_MSG_DEALING," ");this._dealing();break;case STATE_GAME_SHOWDOWN:this._showHandEvaluation()}};this.setMoney=function(h){D.setCredit(h);K.refreshCredit(D.getCredit());X.hide()};this.cardFromDealerArrived=function(h,g,I){!1===g&&h.showCard();14>I&&s_oGame._dealing()};this._cardSplitted=function(h,g){12===g?(r=0,Z[0].showCard()):13===g&&s_oGame.changeState(STATE_GAME_SHOWDOWN)};this._showHandEvaluation=function(){K.refreshHandValueText(TEXT_EVALUATOR[q],TEXT_EVALUATOR[x],TEXT_EVALUATOR[F],
TEXT_EVALUATOR[J]);this._showWin()};this._showWin=function(){var h=0;"player"===p?(playSound("win",1,!1),c?(h=2*D.getBetAnte()-.05*D.getBetAnte(),this._playerWin(h)):(h=D.getBetAnte(),this._standOff(h))):"dealer"===p&&(playSound("lose",1,!1),c?(h=D.getBetAnte(),this._standOff(h)):this._playerLose());this.changeState(STATE_GAME_DISTRIBUTE_FICHES);K.refreshCredit(D.getCredit());setTimeout(function(){D.resetBet();s_oGame.changeState(STATE_GAME_WAITING_FOR_BET);K.enableBetFiches(!0)},3*TIME_CARD_REMOVE)};
this._playerWin=function(h){D.increaseCredit(h);aa-=h;K.displayMsg(TEXT_DISPLAY_MSG_SHOWDOWN,TEXT_DISPLAY_MSG_PLAYER_WIN+" "+formatValue(h));D.initMovement(0,ca.getX(),ca.getY());D.initMovement(1,ca.getX(),ca.getY());K.showResultText(TEXT_HAND_WON_PLAYER)};this._playerLose=function(){K.displayMsg(TEXT_DISPLAY_MSG_SHOWDOWN,TEXT_DISPLAY_MSG_PLAYER_LOSE);D.initMovement(0,ia.getX(),ia.getY());D.initMovement(1,ia.getX(),ia.getY());K.showResultText(TEXT_HAND_WON_DEALER)};this._standOff=function(h){D.increaseCredit(h);
aa-=h;K.displayMsg(TEXT_DISPLAY_MSG_SHOWDOWN,TEXT_DISPLAY_MSG_STANDOFF);D.initMovement(0,ca.getX(),ca.getY());D.initMovement(1,ca.getX(),ca.getY());K.showResultText(TEXT_DISPLAY_MSG_STANDOFF)};this._dealing=function(){if(14>t){var h=new CCard(ha.getX(),ha.getY(),Q);if(1===t%2){var g=new CVector2(l.getX()+CARD_WIDTH/4*t,l.getY());var I=V.splice(0,1),w=I[0].fotogram,v=I[0].rank;I=I[0].suit;h.setInfo(ea,g,w,v,I,!0,t);h.addEventListener(ON_CARD_SHOWN,this._onCardShown);Z.push(h)}else I=Y.splice(0,1),
w=I[0].fotogram,v=I[0].rank,I=I[0].suit,h.setInfo(ea,D.getAttachCardOffset(),w,v,I,!1,t),D.newCardDealed(),L.push(h);W.push(h);t++;h.addEventListener(ON_CARD_ANIMATION_ENDING,this.cardFromDealerArrived);h.addEventListener(SPLIT_CARD_END_ANIM,this._cardSplitted);playSound("card",1,!1)}else setTimeout(function(){s_oGame.changeState(STATE_GAME_PLAYER_TURN);K.displayMsg(TEXT_DISPLAY_MSG_USER_TURN," ");K.disableDeal(!0)},1E3)};this._onEndHand=function(){for(var h=new CVector2(fa.getX(),fa.getY()),g=0;g<
W.length;g++)W[g].initRemoving(h),W[g].hideCard();K.clearCardValueText();K.clearHandValueText();d=0;s_oGame.changeState(STATE_GAME_SHOW_WINNER);playSound("fiche_collect",1,!1);u++;u===AD_SHOW_COUNTER&&(u=0,$(s_oMain).trigger("show_interlevel_ad"));$(s_oMain).trigger("save_score",[D.getCredit()])};this._onCardShown=function(){if(7===r){for(var h=R.getX(),g=R.getY(),I=Z[0].getChildIndex(),w=0;w<S.length;w++)Z[S[w].index].initSplit(h,g,I),h+=CARD_WIDTH/2,I++;h=C.getX();g=C.getY();for(w=0;w<z.length;w++)Z[z[w].index].initSplit(h,
g,I),h+=CARD_WIDTH/2,I++;s_oGame.changeState(STATE_GAME_SPLIT_HAND)}else s_oGame._showNextDealerCard()};this.setBet=function(h){K.isResultPanelvisible()?(K.disableBetFiches(),D.clearBet(),ba=this.setBet,this._onEndHand()):(h=CHIP_VALUES[h],d=0,E.hide(),D.getBetAnte()+h>e?P.show(TEXT_ERROR_MAX_BET):h>D.getCredit()?K.displayMsg(TEXT_NO_MONEY," "):(D.decreaseCredit(h),aa+=h,D.betAnte(h),K.enable(!0,!1,!1),K.refreshCredit(D.getCredit())))};this.cardSelected=function(h){h?k++:k--;5===k?K.enableSplit(!0):
K.enableSplit(!1)};this._gameOver=function(){X.show()};this.onRebet=function(){K.isResultPanelvisible()&&(ba=this.rebet,this._onEndHand(),E.hide())};this.onDeal=function(){if(D.getBetAnte()<MIN_BET)P.show(TEXT_ERROR_MIN_BET),K.enableBetFiches(!1),K.enable(!1,!1,!1);else{$(s_oMain).trigger("bet_placed",D.getBetAnte());Q.removeAllChildren();n=2*D.getBetAnte();if((aa<n?WIN_OCCURRENCE+1:Math.floor(101*Math.random()))>WIN_OCCURRENCE){do this._generateRandomCards(),console.log("_iPlayerLowValue "+x),console.log("_iPlayerHighValue "+
q),console.log("_iPairValueLowHand "+H),console.log("_iPairValueHighHand "+A),console.log("_aPlayerLowHand"+JSON.stringify(y)),console.log("_aPlayerHighHand"+JSON.stringify(B));while("player"===p&&c||!this._checkIfHighHandBetterThanLow())}else{do this._generateRandomCards(),console.log("_iPlayerLowValue "+x),console.log("_iPlayerHighValue "+q),console.log("_iPairValueLowHand "+H),console.log("_iPairValueHighHand "+A),console.log("_aPlayerLowHand"+JSON.stringify(y)),console.log("_aPlayerHighHand"+
JSON.stringify(B));while("player"!==p||!c||!this._checkIfHighHandBetterThanLow())}D.setPrevBet();playSound("card",1,!1);this.changeState(STATE_GAME_DEALING)}};this._generateRandomCards=function(){A=H=-1;Y=this._generateRandCards();N=[];this._findHandCombinations(Y,5,0,[]);var h=this.getBestHand();B=h.hand;q=h.res;h=this._split7Hand(q,B,Y);y=h.low_hand;B=h.high_hand;V=this._generateRandCards();N=[];this._findHandCombinations(V,5,0,[]);h=this.getBestHand();S=h.hand;F=h.res;h=this._split7Hand(F,S,V);
z=h.low_hand;S=h.high_hand;c=this._compareLowHands();h=this.getWinnerComparingHands(B,S);p=h.res;q=h.player_value;F=h.dealer_value};this.getBestHand=function(){for(var h=NO_HAND,g=N[0],I=0;I<N.length;I++){var w=T.evaluate(N[I]);w.ret<h&&(h=w.ret,g=w.sort_hand)}return{res:h,hand:g}};this._findHandCombinations=function(h,g,I,w){if(0===g){h=[];for(g=0;g<w.length;g++)h[g]=w[g];N.push(h)}else for(;I<=h.length-g;I++)w[Math.abs(g-5)]=h[I],this._findHandCombinations(h,g-1,I+1,w)};this._compareLowHands=function(){y=
T.sortCards(y);z=T.sortCards(z);if(y[0].rank===y[1].rank||y[0].rank===CARD_JOKER||y[1].rank===CARD_JOKER){x=ONE_PAIR;H=y[0].rank;if(z[0].rank===z[1].rank||z[0].rank===CARD_JOKER||z[1].rank===CARD_JOKER)return J=ONE_PAIR,y[0].rank>z[0].rank?!0:!1;J=HIGH_CARD;return!0}x=HIGH_CARD;if(z[0].rank===z[1].rank||z[0].rank===CARD_JOKER||z[1].rank===CARD_JOKER)return J=ONE_PAIR,!1;J=HIGH_CARD;return y[1].rank===z[1].rank||y[1].rank===CARD_JOKER&&z[1].rank===CARD_ACE||y[1].rank===CARD_ACE&&z[1].rank===CARD_JOKER?
y[0].rank>z[0].rank?!0:!1:y[1].rank>z[1].rank?!0:!1};this._split7Hand=function(h,g,I){var w=[],v=[];switch(h){case ROYAL_FLUSH:case STRAIGHT_FLUSH:case STRAIGHT:case FLUSH:for(h=0;h<g.length;h++)w.push(g[h]);v=this._fillHandWithRemaining(I,w,v);w=v.high;v=v.low;break;case FOUR_OF_A_KIND:7>g[1].rank?(g[1].rank===g[0].rank?(w.push(g[0]),w.push(g[1]),w.push(g[2]),w.push(g[3])):(w.push(g[1]),w.push(g[2]),w.push(g[3]),w.push(g[4])),g=this.getRemainingCards(I,w,v),g=T.sortCards(g),v.push(g[g.length-1])):
(g[1].rank===g[0].rank?(w.push(g[0]),w.push(g[1]),v.push(g[2]),v.push(g[3])):(w.push(g[1]),w.push(g[2]),v.push(g[3]),v.push(g[4])),g=this.getRemainingCards(I,w,v),g=T.sortCards(g),w.push(g[g.length-1]));v=this._fillHandWithRemaining(I,w,v);w=v.high;v=v.low;break;case FULL_HOUSE:g[2].rank>g[1].rank?(w.push(g[2]),w.push(g[3]),w.push(g[4]),v.push(g[0]),v.push(g[1])):(w.push(g[0]),w.push(g[1]),w.push(g[2]),v.push(g[3]),v.push(g[4]));v=this._fillHandWithRemaining(I,w,v);w=v.high;v=v.low;break;case THREE_OF_A_KIND:h=
[];g[2].rank===g[1].rank&&g[0].rank===g[1].rank?(h.push(g[0]),h.push(g[1]),h.push(g[2])):g[2].rank===g[1].rank&&g[2].rank===g[3].rank?(h.push(g[1]),h.push(g[2]),h.push(g[3])):(h.push(g[2]),h.push(g[3]),h.push(g[4]));w.push(h[0]);w.push(h[1]);w.push(h[2]);g=this.getRemainingCards(I,w,v);g=T.sortCards(g);v.push(g[g.length-1]);v.push(g[g.length-2]);v=this._fillHandWithRemaining(I,w,v);w=v.high;v=v.low;break;case TWO_PAIR:h=0;var M=[],U=[];g[0].rank===g[1].rank?(M.push(g[0]),M.push(g[1])):g[1].rank===
g[2].rank&&(M.push(g[1]),M.push(g[2]));g[2].rank===g[3].rank?(h=g[2].rank,U.push(g[2]),U.push(g[3])):g[3].rank===g[4].rank&&(h=g[3].rank,U.push(g[3]),U.push(g[4]));g=this.getRemainingCards(I,w,v);g=T.sortCards(g);h>CARD_TEN?(v.push(M[0]),v.push(M[1]),w.push(U[0]),w.push(U[1])):h>CARD_SIX&&h<CARD_JACK?g[g.length-1].rank===CARD_ACE||g[g.length-1].rank===CARD_JOKER?(w.push(M[0]),w.push(M[1]),w.push(U[0]),w.push(U[1]),v.push(g[g.length-1])):(v.push(M[0]),v.push(M[1]),w.push(U[0]),w.push(U[1])):g[g.length-
1].rank>CARD_QUEEN?(w.push(M[0]),w.push(M[1]),w.push(U[0]),w.push(U[1]),v.push(g[g.length-1])):(v.push(M[0]),v.push(M[1]),w.push(U[0]),w.push(U[1]));v=this._fillHandWithRemaining(I,w,v);w=v.high;v=v.low;break;case ONE_PAIR:M=[];if(g[4].rank===CARD_JOKER&&g[3].rank===CARD_ACE)M.push(g[3]),M.push(g[4]);else for(h=0;h<g.length-1;h++)if(g[h].rank===g[h+1].rank){M.push(g[h]);M.push(g[h+1]);break}w.push(M[0]);w.push(M[1]);A=M[0].rank;g=this.getRemainingCards(I,w,v);g=T.sortCards(g);v.push(g[g.length-1]);
v.push(g[g.length-2]);v=this._fillHandWithRemaining(I,w,v);w=v.high;v=v.low;break;default:I=T.sortCards(I),v.push(I[I.length-2]),v.push(I[I.length-3]),v=this._fillHandWithRemaining(I,w,v),w=v.high,v=v.low}return{high_hand:w,low_hand:v}};this.getRemainingCards=function(h,g,I){for(var w=[],v=0;v<h.length;v++){for(var M=!1,U=h[v],ja=0;ja<g.length;ja++)if(g[ja].rank===U.rank&&g[ja].suit===U.suit){M=!0;break}for(ja=0;ja<I.length;ja++)if(I[ja].rank===U.rank&&I[ja].suit===U.suit){M=!0;break}M||w.push(U)}return w};
this._fillHandWithRemaining=function(h,g,I){h=this.getRemainingCards(h,g,I);for(var w=0;5>g.length;)g.push(h[w]),w++;for(;2>I.length;)I.push(h[w]),w++;return{high:g,low:I}};this.onHouseWay=function(){K.disableButtons();for(var h=D.getHighHandAttach().getX(),g=D.getHighHandAttach().getY(),I=L[0].getChildIndex(),w=0;w<B.length;w++)L[B[w].index].initSplit(h,g,I),h+=CARD_WIDTH/2,I++;h=D.getLowHandAttach().getX();g=D.getLowHandAttach().getY();for(w=0;w<y.length;w++)L[y[w].index].initSplit(h,g,I),h+=CARD_WIDTH/
2,I++;this.changeState(STATE_GAME_SPLIT_HAND)};this.onSplitHand=function(){G=B.slice();da=y.slice();B=[];y=[];for(var h=0;h<L.length;h++)L[h].isSelected()?B.push({rank:L[h].getValue(),suit:L[h].getSuit(),index:h}):y.push({rank:L[h].getValue(),suit:L[h].getSuit(),index:h});c=this._compareLowHands();B=T.sortCards(B);h=this.getWinnerComparingHands(B,S);p=h.res;q=h.player_value;F=h.dealer_value;if(this._checkIfHighHandBetterThanLow())this.onHouseWay();else P.show(TEXT_ERROR_BIGGER_LOW_HAND),B=G.slice(),
y=da.slice()};this._checkIfHighHandBetterThanLow=function(){return x<q?!1:q===x&&H>A?(console.log("FALSE"),!1):!0};this.getWinnerComparingHands=function(h,g){var I=T.evaluate(h).ret,w=T.evaluate(g).ret,v="dealer";if(I===w){switch(I){case STRAIGHT_FLUSH:v=h[3].rank<=g[3].rank?"dealer":"player";break;case FOUR_OF_A_KIND:v=h[1].rank>g[1].rank?"player":"dealer";break;case FULL_HOUSE:v=h[2].rank>g[2].rank?"player":"dealer";break;case FLUSH:v=h[3].rank<=g[3].rank?"dealer":"player";break;case STRAIGHT:v=
h[3].rank>g[3].rank?"player":"dealer";break;case THREE_OF_A_KIND:v=h[2].rank>g[2].rank?"player":"dealer";break;case TWO_PAIR:v=0;for(var M=h.length-1;1<M;M--)if(h[M].rank===h[M-1].rank){v=h[M].rank;break}var U=0;for(M=g.length-1;1<M;M--)if(g[M].rank===g[M-1].rank){U=g[M].rank;break}v=v>U?"player":"dealer";break;case ONE_PAIR:for(M=v=0;M<h.length-1;M++)if(h[M].rank===h[M+1].rank||h[M].rank===CARD_ACE&&h[M+1].rank===CARD_JOKER){v=h[M].rank;break}A=v;for(M=U=0;M<g.length-1;M++)if(g[M].rank===g[M+1].rank||
g[M].rank===CARD_ACE&&g[M+1].rank===CARD_JOKER){U=g[M].rank;break}v=v>U?"player":"dealer";break;case HIGH_CARD:if(v=g.length-1,g[v].rank===h[v].rank||g[v].rank===CARD_JOKER&&h[v].rank===CARD_ACE||g[v].rank===CARD_ACE&&h[v].rank===CARD_JOKER){do v--;while(g[v].rank===h[v].rank&&0<=v);v=g[v].rank<h[v].rank?"player":"dealer"}else v=g[g.length-1].rank>=h[h.length-1].rank?"dealer":"player"}return{res:v,player_value:I,dealer_value:w}}return{res:I>w?"dealer":"player",player_value:I,dealer_value:w}};this._showNextDealerCard=
function(){Z[r].showCard();r++};this._generateRandCards=function(){for(var h=[],g=0;7>g;g++)h.push({fotogram:O[m].fotogram,rank:O[m].rank,suit:O[m].suit,index:g}),m++,this._checkDeckLength();return h};this._checkDeckLength=function(){m>=O.length&&(O=s_oGameSettings.getShuffledCardDeck(),m=0)};this.clearBets=function(){if(f===STATE_GAME_WAITING_FOR_BET){K.enable(!1,!1,!1);var h=D.getStartingBet();0<h&&(D.clearBet(),D.increaseCredit(h),aa-=h,K.refreshCredit(D.getCredit()),h=D.checkIfRebetIsPossible(),
K.enableBetFiches(h))}};this.rebet=function(){this.clearBets();var h=D.rebet();aa-=h;K.enable(!0,!1,!1);K.refreshCredit(D.getCredit());d=BET_TIME};this.onExit=function(){this.unload();$(s_oMain).trigger("end_session");$(s_oMain).trigger("share_event",D.getCredit());s_oMain.gotoMenu()};this.getState=function(){return f};this._updateCards=function(){for(var h=0;h<W.length;h++)W[h].update()};this._updateFiches=function(){D.updateFichesController()};this._updateShowWinner=function(){for(var h=0;h<W.length;h++)W[h].update();
d+=s_iTimeElaps;d>TIME_END_HAND&&(d=0,h=D.checkIfRebetIsPossible(),this.reset(h),K.reset(),D.getCredit()<s_oGameSettings.getFichesValueAt(0)?(this._gameOver(),this.changeState(-1)):D.getCredit()<s_oGameSettings.getFichesValueAt(0)?(this._gameOver(),this.changeState(-1)):(this.changeState(STATE_GAME_WAITING_FOR_BET),ba.call(this,K.getFicheSelected())))};this.update=function(){if(!1!==b)switch(f){case STATE_GAME_WAITING_FOR_BET:d+=s_iTimeElaps;6E3<d&&(d=0,E.isVisible()||0!==D.getBetAnte()||E.show(1));
break;case STATE_GAME_DEALING:this._updateCards();break;case STATE_GAME_SPLIT_HAND:this._updateCards();break;case STATE_GAME_DISTRIBUTE_FICHES:this._updateFiches();break;case STATE_GAME_SHOW_WINNER:this._updateShowWinner()}};s_oGame=this;TOTAL_MONEY=a.money;MIN_BET=a.min_bet;MAX_BET=a.max_bet;CHIP_VALUES=a.chip_values;BET_TIME=a.bet_time;WIN_OCCURRENCE=a.win_occurrence;var aa=a.game_cash;TIME_END_HAND=a.time_show_hand;AD_SHOW_COUNTER=a.ad_show_counter;this._init()}var s_oGame,s_oTweenController;
function CInterface(a){var b,c,d,e,f,m,n,t,r,k,u,q,F,x,H,A,J,p,N,y,z,B,S,G,da,ba,W=null,Z=null;this._init=function(O){var L=s_oSpriteLibrary.getSprite("but_exit");d=CANVAS_WIDTH-L.width/2-10;e=L.height/2+10;r=new CGfxButton(d,e,L,s_oStage);r.addEventListener(ON_MOUSE_UP,this._onExit,this);var Y=s_oSpriteLibrary.getSprite("but_fullscreen");!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(f=r.getX()-L.width-10,m=L.height/2+10,A=new CToggle(f,m,s_oSpriteLibrary.getSprite("audio_icon"),s_bAudioActive,!0),A.addEventListener(ON_MOUSE_UP,
this._onAudioToggle,this),b=f-Y.width/2-10):b=d-Y.width/2-10;c=Y.height/2+10;L=window.document;var V=L.documentElement;W=V.requestFullscreen||V.mozRequestFullScreen||V.webkitRequestFullScreen||V.msRequestFullscreen;Z=L.exitFullscreen||L.mozCancelFullScreen||L.webkitExitFullscreen||L.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(W=!1);W&&screenfull.isEnabled&&(ba=new CToggle(b,c,Y,s_bFullscreen,!0),ba.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));L=createBitmap(s_oSpriteLibrary.getSprite("display_bg"));
L.x=290;L.y=6;s_oStage.addChild(L);L=s_oSpriteLibrary.getSprite("gui_bg");Y=createBitmap(L);Y.y=CANVAS_HEIGHT-L.height;s_oStage.addChild(Y);L=s_oSpriteLibrary.getSprite("but_clear");k=new CGfxButton(830,CANVAS_HEIGHT-L.height/2,L,s_oStage);k.addEventListener(ON_MOUSE_UP,this._onButClearRelease,this);L=s_oSpriteLibrary.getSprite("but_rebet");u=new CGfxButton(890,CANVAS_HEIGHT-L.height/2,L,s_oStage);u.disable();u.addEventListener(ON_MOUSE_UP,this._onButRebetRelease,this);L=s_oSpriteLibrary.getSprite("but_generic");
F=new CTextButton(1012,CANVAS_HEIGHT-L.height/2,L,TEXT_DEAL,FONT_GAME_1,"#ffffff",30,s_oStage);F.addEventListener(ON_MOUSE_UP,this._onButDealRelease,this);H=new CTextButton(1202,CANVAS_HEIGHT-L.height/2,L,TEXT_HOUSE_WAY,FONT_GAME_1,"#ffffff",27,s_oStage);H.addEventListener(ON_MOUSE_UP,this._onButHouseWayRelease,this);x=new CGfxButton(1060,570,s_oSpriteLibrary.getSprite("but_split"),s_oStage);x.setVisible(!1);x.addEventListener(ON_MOUSE_UP,this._onButSplitRelease,this);POS_BET={x:CANVAS_WIDTH/2,y:415};
q=new CGfxButton(POS_BET.x,POS_BET.y,s_oSpriteLibrary.getSprite("bet_ante"),s_oStage);q.addEventListener(ON_MOUSE_UP,this._onButAnteRelease,this);new CTLText(s_oStage,634,168,200,17,17,"center","#ffde00",FONT_GAME_1,1,0,0,TEXT_HIGH_HAND,!0,!0,!1,!1);new CTLText(s_oStage,868,168,200,17,17,"center","#ffde00",FONT_GAME_1,1,0,0,TEXT_LOW_HAND,!0,!0,!1,!1);new CTLText(s_oStage,634,638,200,17,17,"center","#ffde00",FONT_GAME_1,1,0,0,TEXT_HIGH_HAND,!0,!0,!1,!1);new CTLText(s_oStage,868,638,200,17,17,"center",
"#ffde00",FONT_GAME_1,1,0,0,TEXT_LOW_HAND,!0,!0,!1,!1);y=new createjs.Text("","17px "+FONT_GAME_1,"#fff");y.x=740;y.y=490;y.textAlign="center";s_oStage.addChild(y);z=new createjs.Text("","17px "+FONT_GAME_1,"#fff");z.x=970;z.y=490;z.textAlign="center";s_oStage.addChild(z);B=new createjs.Text("","17px "+FONT_GAME_1,"#fff");B.x=740;B.y=310;B.textAlign="center";s_oStage.addChild(B);S=new createjs.Text("","17px "+FONT_GAME_1,"#fff");S.x=970;S.y=310;S.textAlign="center";s_oStage.addChild(S);p=new CTLText(s_oStage,
405,18,190,40,24,"left","#ffde00",FONT_GAME_2,1,0,0," ",!0,!0,!0,!1);N=new CTLText(s_oStage,405,60,190,40,18,"left","#ffde00",FONT_GAME_2,1,0,0," ",!0,!0,!0,!1);new CTLText(s_oStage,300,CANVAS_HEIGHT-84,96,30,30,"left","#ffde00",FONT_GAME_2,1,0,0,TEXT_MONEY+":",!0,!0,!0,!1);J=new CTLText(s_oStage,400,CANVAS_HEIGHT-84,210,30,30,"left","#ffde00",FONT_GAME_2,1,0,0,formatValue(O),!0,!0,!0,!1);O=[{x:337,y:CANVAS_HEIGHT-24},{x:417,y:CANVAS_HEIGHT-24},{x:497,y:CANVAS_HEIGHT-24},{x:577,y:CANVAS_HEIGHT-24},
{x:657,y:CANVAS_HEIGHT-24},{x:737,y:CANVAS_HEIGHT-24}];t=[];Y=CHIP_VALUES;for(V=0;V<NUM_FICHES;V++)t[V]=new CFicheBut(V,O[V].x,O[V].y,1,s_oStage),t[V].addEventListenerWithParams(ON_MOUSE_UP,this._onFicheClicked,this,[Y[V],V]);O=s_oSpriteLibrary.getSprite("fiche_highlight");G=createBitmap(O);G.regX=O.width/2;G.regY=O.height/2;G.x=t[0].getX();G.y=t[0].getY();s_oStage.addChild(G);n=0;FICHE_WIDTH=L.width;da=new CAnimText(CANVAS_WIDTH,CANVAS_HEIGHT,s_oStage);this.disableButtons();this.refreshButtonPos(s_iOffsetX,
s_iOffsetY)};this.unload=function(){r.unload();r=null;!1===DISABLE_SOUND_MOBILE&&(A.unload(),A=null);W&&screenfull.isEnabled&&ba.unload();k.unload();F.unload();u.unload();s_oInterface=null};this.refreshButtonPos=function(O,L){r.setPosition(d-O,L+e);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||A.setPosition(f-O,L+m);W&&screenfull.isEnabled&&ba.setPosition(b-O,c+L)};this.reset=function(){this.disableButtons()};this.enableBetFiches=function(O){for(var L=0;L<NUM_FICHES;L++)t[L].enable();k.enable();q.enable();
O&&u.enable()};this.disableBetFiches=function(){for(var O=0;O<NUM_FICHES;O++)t[O].disable();k.disable();u.disable();q.disable()};this.disableButtons=function(){F.disable();H.disable();x.setVisible(!1)};this.disableDeal=function(O){O?(F.disable(),H.enable()):(F.enable(),H.disable())};this.enable=function(O){O?F.enable():F.disable()};this.enableSplit=function(O){x.setVisible(O)};this.refreshCredit=function(O){J.refreshText(formatValue(O))};this.refreshHandValueText=function(O,L,Y,V){y.text=O;z.text=
L;B.text=Y;S.text=V};this.clearHandValueText=function(){y.text="";z.text="";B.text="";S.text=""};this.displayMsg=function(O,L){p.refreshText(O);N.refreshText(L)};this.clearCardValueText=function(){da.hide()};this._onFicheClicked=function(O){G.x=t[O[1]].getX();G.y=t[O[1]].getY();n=O[1]};this.showResultText=function(O){da.show({x:-200,y:CANVAS_HEIGHT/2+140},{x:CANVAS_WIDTH/2-450,y:CANVAS_HEIGHT/2+140},O)};this._onButClearRelease=function(){s_oGame.clearBets()};this._onButRebetRelease=function(){u.disable();
s_oGame.onRebet()};this._onButAnteRelease=function(){s_oGame.setBet(n)};this._onButDealRelease=function(){this.disableBetFiches();this.disableDeal(!0);s_oGame.onDeal()};this._onButHouseWayRelease=function(){this.disableBetFiches();this.disableButtons();s_oGame.onHouseWay()};this._onButSplitRelease=function(){s_oGame.onSplitHand()};this._onExit=function(){s_oGame.onExit()};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this.resetFullscreenBut=function(){W&&
screenfull.isEnabled&&ba.setActive(s_bFullscreen)};this._onFullscreenRelease=function(){s_bFullscreen?Z.call(window.document):W.call(window.document.documentElement);sizeHandler()};this.getFicheSelected=function(){return n};this.isResultPanelvisible=function(){return da.isVisible()};s_oInterface=this;this._init(a);return this}var s_oInterface=null;
function CTweenController(){this.tweenValue=function(a,b,c){return a+c*(b-a)};this.easeLinear=function(a,b,c,d){return c*a/d+b};this.easeInCubic=function(a,b,c,d){d=(a/=d)*a*a;return b+c*d};this.easeBackInQuart=function(a,b,c,d){d=(a/=d)*a;return b+c*(2*d*d+2*d*a+-3*d)};this.easeInBack=function(a,b,c,d){return c*(a/=d)*a*(2.70158*a-1.70158)+b};this.easeOutCubic=function(a,b,c,d){return c*((a=a/d-1)*a*a+1)+b}}
function CSeat(){var a,b,c,d,e,f,m,n,t,r;this._init=function(){m=new createjs.Container;m.x=CANVAS_WIDTH/2-100;m.y=570;s_oStage.addChild(m);r=[];for(var k=0;2>k;k++)r[k]=new CFichesController;a=d=0;this.reset();n=new CVector2(m.x-80,m.y);t=new CVector2(m.x+200,m.y);f=new CVector2};this.unload=function(){s_oStage.removeChild(m)};this.addEventListener=function(k,u,q){};this.reset=function(){for(var k=c=0;k<r.length;k++)r[k].reset();e=[];for(k=0;3>k;k++)e[k]=[]};this.clearBet=function(){a=0;e=[];for(var k=
0;k<r.length;k++)r[k].reset(),e[k]=[]};this.resetBet=function(){a=0};this.setCredit=function(k){d=k};this.increaseCredit=function(k){d+=k};this.betAnte=function(k){a+=k;r[0].createFichesPile(a,POS_BET.x,POS_BET.y)};this.setPrevBet=function(){b=a};this.decreaseCredit=function(k){d-=k};this.refreshFiches=function(k,u,q,F,x){e[x].push({value:k,index:u});r[x].refreshFiches(e[x],q,F)};this.initMovement=function(k,u,q){r[k].initMovement(u,q)};this.newCardDealed=function(){c++};this.rebet=function(){a=b;
this.decreaseCredit(b);r[0].createFichesPile(b,POS_BET.x,POS_BET.y);return b};this.checkIfRebetIsPossible=function(){for(var k=0,u=0;u<r.length;u++){var q=parseFloat(r[u].getPrevBet().toFixed(2));k+=q}return k>d?!1:!0};this.updateFichesController=function(){for(var k=0;k<r.length;k++)r[k].update()};this.getAttachCardOffset=function(){f.set(m.x+CARD_WIDTH/2*c,m.y);return f};this.getHighHandAttach=function(){return n};this.getLowHandAttach=function(){return t};this.getBetAnte=function(){return a};this.getCredit=
function(){return d};this.getPotentialWin=function(k){return(void 0)[k]};this.getStartingBet=function(){for(var k=0,u=0;u<r.length;u++)k+=r[u].getValue();return k};this._init()}
function CFichesController(){var a,b,c,d,e,f,m,n,t,r;this._init=function(){n=new createjs.Container;s_oStage.addChild(n);e=new CVector2;e.set(n.x,n.y);t=new createjs.Container;s_oStage.addChild(t);r=new createjs.Text("","28px "+FONT_GAME_1,"#fff");r.textAlign="center";r.shadow=new createjs.Shadow("#000000",2,2,2);t.addChild(r);c=d=b=0;a=!1};this.addEventListener=function(k,u,q){};this.reset=function(){a=!1;c=0;n.removeAllChildren();n.x=e.getX();n.y=e.getY();r.text=""};this.setPrevValue=function(k){d=
k};this.refreshFiches=function(k,u,q){k=k.sortOn("value","index");for(var F=u,x=q+10,H=c=0,A=0;A<k.length;A++)(new CFicheBut(k[A].index,F,x,1,n)).disable(),x-=5,H++,9<H&&(H=0,F+=FICHE_WIDTH,x=q),c+=k[A].value;playSound("chip",1,!1);r.x=u;r.y=q+40;r.text=formatValue(c)};this.createFichesPile=function(k,u,q){this.reset();var F=CHIP_VALUES,x=[];do{for(var H=F[F.length-1],A=F.length-1;H>k;)A--,H=F[A];A=Math.floor(k/H);for(var J=0;J<A;J++)x.push({value:H,index:s_oGameSettings.getIndexForFiches(H)});k=
H=(k%H).toFixed(1)}while(0<H);this.refreshFiches(x,u,q)};this.initMovement=function(k,u){d=c;f=new CVector2(n.x,n.y);m=new CVector2(k,u);r.text="";a=!0};this.getValue=function(){return c};this.getPrevBet=function(){return d};this.update=function(){if(a)if(b+=s_iTimeElaps,b>TIME_FICHES_MOV)b=0,a=!1;else{var k=easeInOutCubic(b,0,1,TIME_FICHES_MOV),u=new CVector2;u=tweenVectors(f,m,k,u);n.x=u.getX();n.y=u.getY()}};this._init()}
function CVector2(a,b){var c,d;this._init=function(e,f){c=e;d=f};this.add=function(e,f){c+=e;d+=f};this.addV=function(e){c+=e.getX();d+=e.getY()};this.scalarDivision=function(e){c/=e;d/=e};this.subV=function(e){c-=e.getX();d-=e.getY()};this.scalarProduct=function(e){c*=e;d*=e};this.invert=function(){c*=-1;d*=-1};this.dotProduct=function(e){return c*e.getX()+d*e.getY()};this.set=function(e,f){c=e;d=f};this.setV=function(e){c=e.getX();d=e.getY()};this.length=function(){return Math.sqrt(c*c+d*d)};this.length2=
function(){return c*c+d*d};this.normalize=function(){var e=this.length();0<e&&(c/=e,d/=e)};this.getNormalize=function(e){this.length();e.set(c,d);e.normalize()};this.rot90CCW=function(){var e=c;c=-d;d=e};this.rot90CW=function(){var e=c;c=d;d=-e};this.getRotCCW=function(e){e.set(c,d);e.rot90CCW()};this.getRotCW=function(e){e.set(c,d);e.rot90CW()};this.ceil=function(){c=Math.ceil(c);d=Math.ceil(d)};this.round=function(){c=Math.round(c);d=Math.round(d)};this.toString=function(){return"Vector2: "+c+", "+
d};this.print=function(){trace("Vector2: "+c+", "+d)};this.getX=function(){return c};this.getY=function(){return d};this._init(a,b)}
function CGameSettings(){var a,b;this._init=function(){var c=-1;a=[];for(var d=0;52>d;d++){var e=(d+1)%13;1===e?(e=14,c++):0===e&&(e=13);a.push({fotogram:d,rank:e,suit:c})}a.push({fotogram:d,rank:15,suit:0})};this.getFichesValueAt=function(c){return CHIP_VALUES[c]};this.getIndexForFiches=function(c){for(var d=0,e=0;e<CHIP_VALUES.length;e++)CHIP_VALUES[e]===c&&(d=e);return d};this.generateFichesPile=function(c){var d=[],e=CHIP_VALUES.length-1,f=CHIP_VALUES[e];do{var m=c%f;m=CMath.roundDecimal(m,1);
c=Math.floor(c/f);for(var n=0;n<c;n++)d.push(f);e--;f=CHIP_VALUES[e];c=m}while(0<m&&-1<e);return d};this.timeToString=function(c){c=Math.round(c/1E3);var d=Math.floor(c/60);c-=60*d;var e="";e=10>d?e+("0"+d+":"):e+(d+":");return 10>c?e+("0"+c):e+c};this.getShuffledCardDeck=function(){for(var c=[],d=0;d<a.length;d++)c[d]=a[d];for(b=[];0<c.length;)b.push(c.splice(Math.round(Math.random()*(c.length-1)),1)[0]);return b};this.getCardDeck=function(){return a};this._init()}
var TYPE_LINEAR=0,TYPE_OUT_CUBIC=1,TYPE_IN_CUBIC=2,TYPE_OUT_BACK=3,TYPE_IN_BACK=4;function ease(a,b,c,d,e,f){switch(a){case TYPE_LINEAR:var m=easeLinear(b,c,d,e,f);break;case TYPE_IN_CUBIC:m=easeInCubic(b,c,d,e,f);break;case TYPE_OUT_CUBIC:m=easeOutCubic(b,c,d,e,f);break;case TYPE_IN_BACK:m=easeInBack(b,c,d,e,f);break;case TYPE_OUT_BACK:m=easeInBack(b,c,d,e,f)}return m}
function easeOutBounce(a,b,c,d){return(a/=d)<1/2.75?7.5625*c*a*a+b:a<2/2.75?c*(7.5625*(a-=1.5/2.75)*a+.75)+b:a<2.5/2.75?c*(7.5625*(a-=2.25/2.75)*a+.9375)+b:c*(7.5625*(a-=2.625/2.75)*a+.984375)+b}function easeInBounce(a,b,c,d){return c-easeOutBounce(d-a,0,c,d)+b}function easeInOutBounce(a,b,c,d){return a<d/2?.5*easeInBounce(2*a,0,c,d)+b:.5*easeOutBounce(2*a-d,0,c,d)+.5*c+b}function easeInCirc(a,b,c,d){return-c*(Math.sqrt(1-(a/=d)*a)-1)+b}
function easeOutCirc(a,b,c,d){return c*Math.sqrt(1-(a=a/d-1)*a)+b}function easeInOutCirc(a,b,c,d){return 1>(a/=d/2)?-c/2*(Math.sqrt(1-a*a)-1)+b:c/2*(Math.sqrt(1-(a-=2)*a)+1)+b}function easeInCubic(a,b,c,d,e){return c*(a/=d)*a*a+b}function easeOutCubic(a,b,c,d,e){return c*((a=a/d-1)*a*a+1)+b}function easeInOutCubic(a,b,c,d,e){return 1>(a/=d/2)?c/2*a*a*a+b:c/2*((a-=2)*a*a+2)+b}
function easeInElastic(a,b,c,d,e,f,m){if(0==a)return b;if(1==(a/=d))return b+c;m||(m=.3*d);!f||f<Math.abs(c)?(f=c,e=m/4):e=m/(2*Math.PI)*Math.asin(c/f);return-(f*Math.pow(2,10*--a)*Math.sin(2*(a*d-e)*Math.PI/m))+b}function easeOutElastic(a,b,c,d,e,f,m){if(0==a)return b;if(1==(a/=d))return b+c;m||(m=.3*d);!f||f<Math.abs(c)?(f=c,e=m/4):e=m/(2*Math.PI)*Math.asin(c/f);return f*Math.pow(2,-10*a)*Math.sin(2*(a*d-e)*Math.PI/m)+c+b}
function easeInOutElastic(a,b,c,d,e,f,m){if(0==a)return b;if(1==(a/=d))return b+c;m||(m=.3*d);!f||f<Math.abs(c)?(f=c,e=m/4):e=m/(2*Math.PI)*Math.asin(c/f);return 1>a?-.5*f*Math.pow(2,10*--a)*Math.sin(2*(a*d-e)*Math.PI/m)+b:f*Math.pow(2,-10*--a)*Math.sin(2*(a*d-e)*Math.PI/m)*.5+c+b}function easeInExpo(a,b,c,d){return 0==a?b:c*Math.pow(2,10*(a/d-1))+b}function easeOutExpo(a,b,c,d){return a==d?b+c:c*(-Math.pow(2,-10*a/d)+1)+b}
function easeInOutExpo(a,b,c,d){return 0==a?b:a==d?b+c:1>(a/=d/2)?c/2*Math.pow(2,10*(a-1))+b:c/2*(-Math.pow(2,-10*--a)+2)+b}function easeLinear(a,b,c,d){return c*a/d+b}function easeInQuad(a,b,c,d){return c*(a/=d)*a+b}function easeOutQuad(a,b,c,d){return-c*(a/=d)*(a-2)+b}function easeInOutQuad(a,b,c,d){return 1>(a/=d/2)?c/2*a*a+b:-c/2*(--a*(a-2)-1)+b}function easeInQuart(a,b,c,d){return c*(a/=d)*a*a*a+b}function easeOutQuart(a,b,c,d){return-c*((a=a/d-1)*a*a*a-1)+b}
function easeInOutQuart(a,b,c,d){return 1>(a/=d/2)?c/2*a*a*a*a+b:-c/2*((a-=2)*a*a*a-2)+b}function easeInQuint(a,b,c,d){return c*(a/=d)*a*a*a*a+b}function easeOutQuint(a,b,c,d){return c*((a=a/d-1)*a*a*a*a+1)+b}function easeInOutQuint(a,b,c,d){return 1>(a/=d/2)?c/2*a*a*a*a*a+b:c/2*((a-=2)*a*a*a*a+2)+b}function easeInSine(a,b,c,d){return-c*Math.cos(a/d*(Math.PI/2))+c+b}function easeOutSine(a,b,c,d){return c*Math.sin(a/d*(Math.PI/2))+b}
function easeInOutSine(a,b,c,d){return-c/2*(Math.cos(Math.PI*a/d)-1)+b}function easeInBack(a,b,c,d){return c*(a/=d)*a*(2.70158*a-1.70158)+b}function easeOutBack(a,b,c,d){return c*((a=a/d-1)*a*(2.70158*a+1.70158)+1)+b}
function CCard(a,b,c){var d,e,f,m=-1,n,t,r,k,u,q,F,x,H,A,J;this._init=function(p,N,y){f=!1;J=y;y={images:[s_oSpriteLibrary.getSprite("card_spritesheet")],frames:{width:CARD_WIDTH,height:CARD_HEIGHT,regX:CARD_WIDTH/2,regY:CARD_HEIGHT/2},animations:{card_1_1:[0],card_1_2:[1],card_1_3:[2],card_1_4:[3],card_1_5:[4],card_1_6:[5],card_1_7:[6],card_1_8:[7],card_1_9:[8],card_1_10:[9],card_1_J:[10],card_1_Q:[11],card_1_K:[12],card_2_1:[13],card_2_2:[14],card_2_3:[15],card_2_4:[16],card_2_5:[17],card_2_6:[18],
card_2_7:[19],card_2_8:[20],card_2_9:[21],card_2_10:[22],card_2_J:[23],card_2_Q:[24],card_2_K:[25],card_3_1:[26],card_3_2:[27],card_3_3:[28],card_3_4:[29],card_3_5:[30],card_3_6:[31],card_3_7:[32],card_3_8:[33],card_3_9:[34],card_3_10:[35],card_3_J:[36],card_3_Q:[37],card_3_K:[38],card_4_1:[39],card_4_2:[40],card_4_3:[41],card_4_4:[42],card_4_5:[43],card_4_6:[44],card_4_7:[45],card_4_8:[46],card_4_9:[47],card_4_10:[48],card_4_J:[49],card_4_Q:[50],card_4_K:[51],joker:[52],back:[53]}};y=new createjs.SpriteSheet(y);
A=createSprite(y,"back",CARD_WIDTH/2,CARD_HEIGHT/2,CARD_WIDTH,CARD_HEIGHT);A.x=p;A.y=N;A.rotation=120;A.stop();J.addChild(A);A.on("click",this._onCardRelease);x=[];H=[]};this.unload=function(){A.off("click",this._onCardRelease);F=q=null;J.removeChild(A)};this.addEventListener=function(p,N,y){x[p]=N;H[p]=y};this.setInfo=function(p,N,y,z,B,S,G){e=!1;u=0;n=y;t=z;r=B;q=p;F=N;k=G;d=S;d||(A.cursor="pointer");m=STATE_CARD_DEALING};this.initRemoving=function(p){q=new CVector2(A.x,A.y);F=p;u=0;m=STATE_CARD_REMOVING};
this.initSplit=function(p,N,y){c.setChildIndex(A,y);q=new CVector2(A.x,A.y);F=new CVector2(p,N);u=0;m=STATE_CARD_SPLITTING};this.setValue=function(){A.gotoAndStop(n);var p=this;createjs.Tween.get(A).to({scaleX:1},100).call(function(){p.cardShown()})};this.showCard=function(){var p=this;createjs.Tween.get(A).to({scaleX:.1},100).call(function(){p.setValue()})};this.hideCard=function(){var p=this;createjs.Tween.get(A).to({scaleX:.1},100).call(function(){p.setBack()})};this.setBack=function(){A.gotoAndStop("back");
var p=this;createjs.Tween.get(A).to({scaleX:1},100).call(function(){p.cardHidden()})};this.cardShown=function(){x[ON_CARD_SHOWN]&&x[ON_CARD_SHOWN].call(H[ON_CARD_SHOWN])};this.cardHidden=function(){e=!0};this._onCardRelease=function(){d||(m===STATE_CARD_WAIT_USER&&((f=!f)?createjs.Tween.get(A).to({y:A.y-20},300):createjs.Tween.get(A).to({y:A.y+20},300)),s_oGame.cardSelected(f))};this.getValue=function(){return t};this.getSuit=function(){return r};this.getChildIndex=function(){return J.getChildIndex(A)};
this.getFotogram=function(){return n};this.isSelected=function(){return f};this._updateDealing=function(){u+=s_iTimeElaps;if(u>TIME_CARD_DEALING)m=STATE_CARD_WAIT_USER,u=0,A.x=F.getX(),A.y=F.getY(),A.rotation=360,x[ON_CARD_ANIMATION_ENDING]&&x[ON_CARD_ANIMATION_ENDING].call(H[ON_CARD_ANIMATION_ENDING],this,d,k);else{this.visible=!0;var p=easeInOutCubic(u,0,1,TIME_CARD_DEALING),N=new CVector2;N=tweenVectors(q,F,p,N);A.x=N.getX();A.y=N.getY();A.rotation=120+24E3*p/100}};this._updateRemoving=function(){u+=
s_iTimeElaps;if(u>TIME_CARD_REMOVE)u=0,e=!1,m=-1,this.unload();else{var p=easeInOutCubic(u,0,1,TIME_CARD_REMOVE),N=new CVector2;N=tweenVectors(q,F,p,N);A.x=N.getX();A.y=N.getY();A.rotation=4500*p/100}};this._updateSplit=function(){u+=s_iTimeElaps;if(u>TIME_CARD_SPLIT)u=0,x[SPLIT_CARD_END_ANIM]&&x[SPLIT_CARD_END_ANIM].call(H[SPLIT_CARD_END_ANIM],this,k),m=-1;else{var p=easeInOutCubic(u,0,1,TIME_CARD_SPLIT),N=new CVector2;N=tweenVectors(q,F,p,N);A.x=N.getX();A.y=N.getY()}};this.update=function(){switch(m){case STATE_CARD_DEALING:this._updateDealing();
break;case STATE_CARD_SPLITTING:this._updateSplit();break;case STATE_CARD_REMOVING:!0===e&&this._updateRemoving()}};s_oCard=this;this._init(a,b,c)}var s_oCard;
function CGameOver(){var a,b,c,d;this._init=function(){d=new createjs.Container;s_oStage.addChild(d);d.on("click",function(){});var e=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));d.addChild(e);a=new CTLText(d,CANVAS_WIDTH/2-170,290,340,100,32,"center","#fff",FONT_GAME_1,1,0,0,TEXT_NO_MONEY,!0,!0,!0,!1);a.setShadow("#000000",2,2,2);b=new CTextButton(CANVAS_WIDTH/2-100,450,s_oSpriteLibrary.getSprite("but_game_bg"),TEXT_RECHARGE,FONT_GAME_1,"#fff",14,d);b.addEventListener(ON_MOUSE_UP,this._onRecharge,
this);c=new CTextButton(CANVAS_WIDTH/2+100,450,s_oSpriteLibrary.getSprite("but_game_bg"),TEXT_EXIT,FONT_GAME_1,"#fff",14,d);c.addEventListener(ON_MOUSE_UP,this._onExit,this);this.hide()};this.unload=function(){b.unload();c.unload();d.off("click",function(){})};this.show=function(){d.visible=!0;$(s_oMain).trigger("end_session")};this.hide=function(){d.visible=!1};this._onRecharge=function(){$(s_oMain).trigger("recharge")};this._onExit=function(){s_oGame.onExit()};this._init()}
function CMsgBox(){var a,b,c;this._init=function(){c=new createjs.Container;c.alpha=0;c.visible=!1;s_oStage.addChild(c);a=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));c.addChild(a);b=new CTLText(c,CANVAS_WIDTH/2-190,CANVAS_HEIGHT/2-50,380,100,50,"center","#fff",FONT_GAME_1,1,0,0," ",!0,!0,!0,!1);b.setShadow("#000",2,2,2)};this.unload=function(){c.off("mousedown",this._onExit)};this._initListener=function(){c.on("mousedown",this._onExit)};this.show=function(d){b.refreshText(d);c.visible=!0;
var e=this;createjs.Tween.get(c).to({alpha:1},500).call(function(){e._initListener()});setTimeout(function(){e._onExit()},3E3)};this._onExit=function(){c.visible&&(c.off("mousedown"),c.visible=!1)};this._init();return this}
function CHandEvaluator(){var a,b,c;this.evaluate=function(d){b=[];a=[];for(var e=0;e<d.length;e++)b[e]={rank:d[e].rank,suit:d[e].suit,index:d[e].index},a[e]={rank:d[e].rank,suit:d[e].suit,index:d[e].index};b.sort(this.compareRank);a.sort(this.compareRank);c=[0,1,2,3,4];return{ret:this.rankHand(),sort_hand:a}};this.rankHand=function(){return this._checkForFiveAces()?FIVE_ACES:this._checkForRoyalFlush()?ROYAL_FLUSH:this._checkForStraightFlush()?STRAIGHT_FLUSH:this._checkForFourOfAKind()?FOUR_OF_A_KIND:
this._checkForFullHouse()?FULL_HOUSE:this._checkForFlush()?FLUSH:this._checkForStraight()?STRAIGHT:this._checkForThreeOfAKind()?THREE_OF_A_KIND:this._checkForTwoPair()?TWO_PAIR:this._checkForOnePair()?ONE_PAIR:HIGH_CARD};this._checkForFiveAces=function(){return b[4].rank==CARD_JOKER&&b[0].rank==b[1].rank&&b[2].rank==b[3].rank&&b[0].rank==b[2].rank&&b[0].rank==CARD_ACE?!0:!1};this._checkForRoyalFlush=function(){return this._isRoyalStraight()&&this._isFlush()?!0:!1};this._checkForStraightFlush=function(){return this._isStraight()&&
this._isFlush()?!0:!1};this._checkForFourOfAKind=function(){return b[0].rank===b[3].rank?(b.splice(4,1),c.splice(4,1),!0):b[1].rank===b[4].rank||b[1].rank===CARD_ACE&&b[4].rank===CARD_JOKER?(b.splice(0,1),c.splice(0,1),!0):!1};this._checkForFullHouse=function(){if(this.isJokerInHand()){if(b[0].rank===b[1].rank&&b[2].rank===b[3].rank||b[0].rank===b[2].rank&&b[3].rank===CARD_ACE)return!0}else return b[0].rank===b[1].rank&&b[2].rank===b[4].rank||b[0].rank===b[2].rank&&b[3].rank===b[4].rank?!0:!1};this._checkForFlush=
function(){return this._isFlush()?!0:!1};this._checkForStraight=function(){return this._isStraight()?!0:!1};this._checkForThreeOfAKind=function(){return b[0].rank===b[1].rank&&b[0].rank===b[2].rank?(b.splice(3,1),b.splice(3,1),c.splice(3,1),c.splice(3,1),!0):b[1].rank===b[2].rank&&b[1].rank===b[3].rank?(b.splice(0,1),b.splice(3,1),c.splice(0,1),c.splice(3,1),!0):b[2].rank===b[3].rank&&b[2].rank===b[4].rank||b[4].rank===CARD_JOKER&&b[2].rank===CARD_ACE&&b[3].rank===CARD_ACE?(b.splice(0,1),b.splice(0,
1),c.splice(0,1),c.splice(0,1),!0):!1};this._checkForTwoPair=function(){return b[0].rank===b[1].rank&&b[2].rank===b[3].rank?(b.splice(4,1),c.splice(4,1),!0):b[1].rank===b[2].rank&&b[3].rank===b[4].rank?(b.splice(0,1),c.splice(0,1),!0):b[0].rank===b[1].rank&&b[3].rank===b[4].rank?(b.splice(2,1),c.splice(2,1),!0):!1};this._checkForOnePair=function(){if(b[4].rank===CARD_JOKER&&b[3].rank===CARD_ACE)return!0;for(var d=0;4>d;d++)if(b[d].rank===b[d+1].rank){var e=b[d],f=b[d+1];b=[];b.push(e);b.push(f);c=
[d,d+1];return!0}return!1};this._isFlush=function(){return b[3].suit===b[0].suit&&b[3].suit===b[1].suit&&b[3].suit===b[2].suit?b[4].rank===CARD_JOKER?!0:b[4].suit===b[3].suit?!0:!1:!1};this._isRoyalStraight=function(){return this.isJokerInHand()&&this._isStraight()&&(b[0].rank===CARD_TEN||b[3].rank===CARD_ACE)||b[0].rank===CARD_TEN&&b[1].rank===CARD_JACK&&b[2].rank===CARD_QUEEN&&b[3].rank===CARD_KING&&b[4].rank===CARD_ACE?!0:!1};this._isStraight=function(){for(var d=this.isJokerInHand()?1:0,e=0,f=
0;f<b.length-1-d;f++){var m=b[f+1].rank-(b[f].rank+1);if(0<m){if(e+=m,e>d)return!1}else if(0>m)return!1}return!0};this.isJokerInHand=function(){return b[4].rank===CARD_JOKER?!0:!1};this.compareRank=function(d,e){return d.rank<e.rank?-1:d.rank>e.rank?1:0};this.sortCards=function(d){for(var e=[],f=0;f<d.length;f++)e[f]=d[f];return e=e.sort(this.compareRank)}}
function CAnimText(a,b,c){var d,e,f;this._init=function(n,t){f=new createjs.Container;f.visible=!1;f.x=n;f.y=t;m.addChild(f);var r=s_oSpriteLibrary.getSprite("win_bg"),k=createBitmap(r);f.addChild(k);e=new CTLText(f,r.width/2-98,5,196,r.height-10,50,"center","#fff",FONT_GAME_1,1,0,0," ",!0,!0,!0,!1)};this.show=function(n,t,r){d=n;e.refreshText(r);f.x=n.x;f.y=n.y;f.visible=!0;createjs.Tween.get(f).to({x:t.x,y:t.y},1E3,createjs.Ease.elasticOut)};this.hide=function(){f.visible=!1;f.x=d.x;f.y=d.y};this.isVisible=
function(){return f.visible};var m=c;this._init(a,b)}
function CHelpCursor(a,b,c,d){var e,f;this._init=function(n,t,r){e=n;f=createBitmap(r);f.visible=!1;f.x=n;f.y=t;d.addChild(f)};this.show=function(n){0>n&&(f.scaleX*=-1);this._move(n,e+30*n,600);f.visible=!0};this.hide=function(){createjs.Tween.removeTweens(f);f.x=e;f.visible=!1};this._move=function(n,t,r){var k=0<n?createjs.Ease.cubicIn:createjs.Ease.cubicOut;createjs.Tween.get(f).to({x:t},r,k).call(function(){n*=-1;m._move(n,t+15*n,400)})};this.isVisible=function(){return f.visible};var m=this;this._init(a,
b,c)}
function CCreditsPanel(){var a,b,c,d,e,f,m,n,t,r,k;this._init=function(){k=new createjs.Container;k.alpha=0;s_oStage.addChild(k);var u=new createjs.Shape;u.graphics.beginFill("rgba(0,0,0,0.7)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);k.addChild(u);c=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));k.addChild(c);n=new createjs.Shape;n.graphics.beginFill("#0f0f0f").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);n.alpha=.01;b=n.on("click",this._onLogoButRelease);k.addChild(n);u=s_oSpriteLibrary.getSprite("but_exit");a=
CANVAS_WIDTH/2-235;e=new CGfxButton(a,270,u,k);e.addEventListener(ON_MOUSE_UP,this.unload,this);m=new createjs.Text(TEXT_CREDITS_DEVELOPED,"44px "+FONT_GAME_1,"#000");m.textAlign="center";m.textBaseline="alphabetic";m.x=CANVAS_WIDTH/2;m.y=320;m.outline=2;k.addChild(m);f=new createjs.Text(TEXT_CREDITS_DEVELOPED,"44px "+FONT_GAME_1,"#fff");f.textAlign="center";f.textBaseline="alphabetic";f.x=CANVAS_WIDTH/2;f.y=320;k.addChild(f);u=s_oSpriteLibrary.getSprite("logo_ctl");d=createBitmap(u);d.regX=u.width/
2;d.regY=u.height/2;d.x=CANVAS_WIDTH/2;d.y=CANVAS_HEIGHT/2;k.addChild(d);r=new createjs.Text("www.codethislab.com","40px "+FONT_GAME_1,"#000");r.textAlign="center";r.textBaseline="alphabetic";r.x=CANVAS_WIDTH/2;r.y=460;r.outline=2;k.addChild(r);t=new createjs.Text("www.codethislab.com","40px "+FONT_GAME_1,"#fff");t.textAlign="center";t.textBaseline="alphabetic";t.x=CANVAS_WIDTH/2;t.y=460;k.addChild(t);createjs.Tween.get(k).to({alpha:1},600,createjs.Ease.cubicOut);this.refreshButtonPos(s_iOffsetX,
s_iOffsetY)};this.refreshButtonPos=function(u,q){};this.unload=function(){n.off("click",b);e.unload();e=null;s_oStage.removeChild(k)};this._onLogoButRelease=function(){window.open("http://www.codethislab.com/index.php?&l=en","_blank")};this._init()}
function CFicheBut(a,b,c,d,e){var f,m,n,t=[],r,k;this._init=function(u,q){var F=s_oSpriteLibrary.getSprite("fiche_"+a);f=!1;k=new createjs.Container;k.x=u;k.y=q;k.regX=F.width/2;k.regY=F.height/2;k.cursor="pointer";k.scaleX=k.scaleY=d;e.addChild(k);m=[];n=[];r=createBitmap(F);k.addChild(r);new CTLText(k,F.width/2-10,F.height/2-11,18,20,20,"center",COLOR_FICHES[a],FONT_GAME_1,1,0,0,CHIP_VALUES[a],!0,!0,!1,!1);this._initListener()};this.unload=function(){k.off("mousedown",this.buttonDown);k.off("pressup",
this.buttonRelease);e.removeChild(k)};this.select=function(){};this.deselect=function(){};this.enable=function(){f=!1};this.disable=function(){f=!0};this.setVisible=function(u){k.visible=u};this._initListener=function(){k.on("mousedown",this.buttonDown);k.on("pressup",this.buttonRelease)};this.addEventListener=function(u,q,F){m[u]=q;n[u]=F};this.addEventListenerWithParams=function(u,q,F,x){m[u]=q;n[u]=F;t=x};this.buttonRelease=function(){f||(playSound("press_but",1,!1),k.scaleX=d,k.scaleY=d,m[ON_MOUSE_UP]&&
m[ON_MOUSE_UP].call(n[ON_MOUSE_UP],t))};this.buttonDown=function(){f||(k.scaleX=.9*d,k.scaleY=.9*d,m[ON_MOUSE_DOWN]&&m[ON_MOUSE_DOWN].call(n[ON_MOUSE_DOWN],t))};this.setPosition=function(u,q){k.x=u;k.y=q};this.setX=function(u){k.x=u};this.setY=function(u){k.y=u};this.getX=function(){return k.x};this.getY=function(){return k.y};this._init(b,c)}
CTLText.prototype={constructor:CTLText,__autofit:function(){if(this._bFitText){for(var a=this._iFontSize;(this._oText.getBounds().height>this._iHeight-2*this._iPaddingV||this._oText.getBounds().width>this._iWidth-2*this._iPaddingH)&&!(a--,this._oText.font=a+"px "+this._szFont,this._oText.lineHeight=Math.round(a*this._fLineHeightFactor),this.__updateY(),this.__verticalAlign(),8>a););this._iFontSize=a}},__verticalAlign:function(){if(this._bVerticalAlign){var a=this._oText.getBounds().height;this._oText.y-=
(a-this._iHeight)/2+this._iPaddingV}},__updateY:function(){this._oText.y=this._y+this._iPaddingV;switch(this._oText.textBaseline){case "middle":this._oText.y+=this._oText.lineHeight/2+(this._iFontSize*this._fLineHeightFactor-this._iFontSize)}},__createText:function(a){this._bDebug&&(this._oDebugShape=new createjs.Shape,this._oDebugShape.graphics.beginFill("rgba(255,0,0,0.5)").drawRect(this._x,this._y,this._iWidth,this._iHeight),this._oContainer.addChild(this._oDebugShape));this._oText=new createjs.Text(a,
this._iFontSize+"px "+this._szFont,this._szColor);this._oText.textBaseline="middle";this._oText.lineHeight=Math.round(this._iFontSize*this._fLineHeightFactor);this._oText.textAlign=this._szAlign;this._oText.lineWidth=this._bMultiline?this._iWidth-2*this._iPaddingH:null;switch(this._szAlign){case "center":this._oText.x=this._x+this._iWidth/2;break;case "left":this._oText.x=this._x+this._iPaddingH;break;case "right":this._oText.x=this._x+this._iWidth-this._iPaddingH}this._oContainer.addChild(this._oText);
this.refreshText(a)},setVerticalAlign:function(a){this._bVerticalAlign=a},setOutline:function(a){null!==this._oText&&(this._oText.outline=a)},setShadow:function(a,b,c,d){null!==this._oText&&(this._oText.shadow=new createjs.Shadow(a,b,c,d))},setColor:function(a){this._oText.color=a},setAlpha:function(a){this._oText.alpha=a},removeTweens:function(){createjs.Tween.removeTweens(this._oText)},setX:function(a){this._oText.x=a},getText:function(){return this._oText},getY:function(){return this._y},getFontSize:function(){return this._iFontSize},
refreshText:function(a){""===a&&(a=" ");null===this._oText&&this.__createText(a);this._oText.text=a;this._oText.font=this._iFontSize+"px "+this._szFont;this._oText.lineHeight=Math.round(this._iFontSize*this._fLineHeightFactor);this.__autofit();this.__updateY();this.__verticalAlign()}};
function CTLText(a,b,c,d,e,f,m,n,t,r,k,u,q,F,x,H,A){this._oContainer=a;this._x=b;this._y=c;this._iWidth=d;this._iHeight=e;this._bMultiline=H;this._iFontSize=f;this._szAlign=m;this._szColor=n;this._szFont=t;this._iPaddingH=k;this._iPaddingV=u;this._bVerticalAlign=x;this._bFitText=F;this._bDebug=A;this._oDebugShape=null;this._fLineHeightFactor=r;this._oText=null;q&&this.__createText(q)}
function extractHostname(a){a=-1<a.indexOf("://")?a.split("/")[2]:a.split("/")[0];a=a.split(":")[0];return a=a.split("?")[0]}function extractRootDomain(a){a=extractHostname(a);var b=a.split("."),c=b.length;2<c&&(a=b[c-2]+"."+b[c-1]);return a}
var getClosestTop=function(){var a=window,b=!1;try{for(;a.parent.document!==a.document;)if(a.parent.document)a=a.parent;else{b=!0;break}}catch(c){b=!0}return{topFrame:a,err:b}},getBestPageUrl=function(a){var b=a.topFrame,c="";if(a.err)try{try{c=window.top.location.href}catch(e){var d=window.location.ancestorOrigins;c=d[d.length-1]}}catch(e){c=b.document.referrer}else c=b.location.href;return c},TOPFRAMEOBJ=getClosestTop(),PAGE_URL=getBestPageUrl(TOPFRAMEOBJ);
function seekAndDestroy(){for(var a=extractRootDomain(PAGE_URL),b=[String.fromCharCode(99,111,100,101,116,104,105,115,108,97,98,46,99,111,109),String.fromCharCode(101,110,118,97,116,111,46,99,111,109),String.fromCharCode(99,111,100,101,99,97,110,121,111,110,46,99,111,109),String.fromCharCode(99,111,100,101,99,97,110,121,111,110,46,110,101,116)],c=0;c<b.length;c++)if(b[c]===a)return!0;return!0};