/*
 Platform.js <https://mths.be/platform>
 Copyright 2014-2018 Benjamin Tan <https://bnjmnt4n.now.sh/>
 Copyright 2011-2013 John-David Dalton
 Available under MIT license <https://mths.be/mit>
*/
(function(){function a(a){a=String(a);return a.charAt(0).toUpperCase()+a.slice(1)}function b(a,c){var b=-1,e=a?a.length:0;if("number"==typeof e&&-1<e&&e<=y)for(;++b<e;)c(a[b],b,a);else d(a,c)}function c(c){c=String(c).replace(/^ +| +$/g,"");return/^(?:webOS|i(?:OS|P))/.test(c)?c:a(c)}function d(a,c){for(var b in a)u.call(a,b)&&c(a[b],b,a)}function f(c){return null==c?a(c):w.call(c).slice(8,-1)}function k(a,c){var b=null!=a?typeof a[c]:"number";return!/^(?:boolean|number|string|undefined)$/.test(b)&&
("object"==b?!!a[c]:!0)}function e(a){return String(a).replace(/([ -])(?!$)/g,"$1?")}function m(a,c){var d=null;b(a,function(b,e){d=c(d,b,e,a)});return d}function p(a){function b(b){return m(b,function(b,d){var h=d.pattern||e(d);!b&&(b=RegExp("\\b"+h+" *\\d+[.\\w_]*","i").exec(a)||RegExp("\\b"+h+" *\\w+-[\\w]*","i").exec(a)||RegExp("\\b"+h+"(?:; *(?:[a-z]+[_-])?[a-z]+\\d+|[^ ();-]*)","i").exec(a))&&((b=String(d.label&&!RegExp(h,"i").test(d.label)?d.label:b).split("/"))[1]&&!/[\d.]+/.test(b[0])&&(b[0]+=
" "+b[1]),d=d.label||d,b=c(b[0].replace(RegExp(h,"i"),d).replace(RegExp("; *(?:"+d+"[_-])?","i")," ").replace(RegExp("("+d+")[-_.]?(\\w)","i"),"$1 $2")));return b})}function l(c){return m(c,function(c,b){return c||(RegExp(b+"(?:-[\\d.]+/|(?: for [\\w-]+)?[ /-])([\\d.]+[^ ();/_-]*)","i").exec(a)||0)[1]||null})}var n=h,q=a&&"object"==typeof a&&"String"!=f(a);q&&(n=a,a=null);var u=n.navigator||{},v=u.userAgent||"";a||(a=v);var y=q?!!u.likeChrome:/\bChrome\b/.test(a)&&!/internal|\n/i.test(w.toString()),
C=q?"Object":"ScriptBridgingProxyObject",x=q?"Object":"Environment",L=q&&n.java?"JavaPackage":f(n.java),V=q?"Object":"RuntimeObject";x=(L=/\bJava/.test(L)&&n.java)&&f(n.environment)==x;var W=L?"a":"\u03b1",X=L?"b":"\u03b2",Q=n.document||{},I=n.operamini||n.opera,N=z.test(N=q&&I?I["[[Class]]"]:f(I))?N:I=null,g,O=a;q=[];var P=null,J=a==v;v=J&&I&&"function"==typeof I.version&&I.version();var A=function(c){return m(c,function(c,b){return c||RegExp("\\b"+(b.pattern||e(b))+"\\b","i").exec(a)&&(b.label||
b)})}([{label:"EdgeHTML",pattern:"Edge"},"Trident",{label:"WebKit",pattern:"AppleWebKit"},"iCab","Presto","NetFront","Tasman","KHTML","Gecko"]),r=function(c){return m(c,function(c,b){return c||RegExp("\\b"+(b.pattern||e(b))+"\\b","i").exec(a)&&(b.label||b)})}(["Adobe AIR","Arora","Avant Browser","Breach","Camino","Electron","Epiphany","Fennec","Flock","Galeon","GreenBrowser","iCab","Iceweasel","K-Meleon","Konqueror","Lunascape","Maxthon",{label:"Microsoft Edge",pattern:"Edge"},"Midori","Nook Browser",
"PaleMoon","PhantomJS","Raven","Rekonq","RockMelt",{label:"Samsung Internet",pattern:"SamsungBrowser"},"SeaMonkey",{label:"Silk",pattern:"(?:Cloud9|Silk-Accelerated)"},"Sleipnir","SlimBrowser",{label:"SRWare Iron",pattern:"Iron"},"Sunrise","Swiftfox","Waterfox","WebPositive","Opera Mini",{label:"Opera Mini",pattern:"OPiOS"},"Opera",{label:"Opera",pattern:"OPR"},"Chrome",{label:"Chrome Mobile",pattern:"(?:CriOS|CrMo)"},{label:"Firefox",pattern:"(?:Firefox|Minefield)"},{label:"Firefox for iOS",pattern:"FxiOS"},
{label:"IE",pattern:"IEMobile"},{label:"IE",pattern:"MSIE"},"Safari"]),B=b([{label:"BlackBerry",pattern:"BB10"},"BlackBerry",{label:"Galaxy S",pattern:"GT-I9000"},{label:"Galaxy S2",pattern:"GT-I9100"},{label:"Galaxy S3",pattern:"GT-I9300"},{label:"Galaxy S4",pattern:"GT-I9500"},{label:"Galaxy S5",pattern:"SM-G900"},{label:"Galaxy S6",pattern:"SM-G920"},{label:"Galaxy S6 Edge",pattern:"SM-G925"},{label:"Galaxy S7",pattern:"SM-G930"},{label:"Galaxy S7 Edge",pattern:"SM-G935"},"Google TV","Lumia","iPad",
"iPod","iPhone","Kindle",{label:"Kindle Fire",pattern:"(?:Cloud9|Silk-Accelerated)"},"Nexus","Nook","PlayBook","PlayStation Vita","PlayStation","TouchPad","Transformer",{label:"Wii U",pattern:"WiiU"},"Wii","Xbox One",{label:"Xbox 360",pattern:"Xbox"},"Xoom"]),E=function(c){return m(c,function(c,b,d){return c||(b[B]||b[/^[a-z]+(?: +[a-z]+\b)*/i.exec(B)]||RegExp("\\b"+e(d)+"(?:\\b|\\w*\\d)","i").exec(a))&&d})}({Apple:{iPad:1,iPhone:1,iPod:1},Archos:{},Amazon:{Kindle:1,"Kindle Fire":1},Asus:{Transformer:1},
"Barnes & Noble":{Nook:1},BlackBerry:{PlayBook:1},Google:{"Google TV":1,Nexus:1},HP:{TouchPad:1},HTC:{},LG:{},Microsoft:{Xbox:1,"Xbox One":1},Motorola:{Xoom:1},Nintendo:{"Wii U":1,Wii:1},Nokia:{Lumia:1},Samsung:{"Galaxy S":1,"Galaxy S2":1,"Galaxy S3":1,"Galaxy S4":1},Sony:{PlayStation:1,"PlayStation Vita":1}}),t=function(b){return m(b,function(b,d){var h=d.pattern||e(d);if(!b&&(b=RegExp("\\b"+h+"(?:/[\\d.]+|[ \\w.]*)","i").exec(a))){var f=b,p=d.label||d,l={"10.0":"10","6.4":"10 Technical Preview",
"6.3":"8.1","6.2":"8","6.1":"Server 2008 R2 / 7","6.0":"Server 2008 / Vista","5.2":"Server 2003 / XP 64-bit","5.1":"XP","5.01":"2000 SP1","5.0":"2000","4.0":"NT","4.90":"ME"};h&&p&&/^Win/i.test(f)&&!/^Windows Phone /i.test(f)&&(l=l[/[\d.]+$/.exec(f)])&&(f="Windows "+l);f=String(f);h&&p&&(f=f.replace(RegExp(h,"i"),p));b=f=c(f.replace(/ ce$/i," CE").replace(/\bhpw/i,"web").replace(/\bMacintosh\b/,"Mac OS").replace(/_PowerPC\b/i," OS").replace(/\b(OS X) [^ \d]+/i,"$1").replace(/\bMac (OS X)\b/,"$1").replace(/\/(\d)/,
" $1").replace(/_/g,".").replace(/(?: BePC|[ .]*fc[ \d.]+)$/i,"").replace(/\bx86\.64\b/gi,"x86_64").replace(/\b(Windows Phone) OS\b/,"$1").replace(/\b(Chrome OS \w+) [\d.]+\b/,"$1").split(" on ")[0])}return b})}(["Windows Phone","Android","CentOS",{label:"Chrome OS",pattern:"CrOS"},"Debian","Fedora","FreeBSD","Gentoo","Haiku","Kubuntu","Linux Mint","OpenBSD","Red Hat","SuSE","Ubuntu","Xubuntu","Cygwin","Symbian OS","hpwOS","webOS ","webOS","Tablet OS","Tizen","Linux","Mac OS X","Macintosh","Mac",
"Windows 98;","Windows "]);A&&(A=[A]);E&&!B&&(B=b([E]));if(g=/\bGoogle TV\b/.exec(B))B=g[0];/\bSimulator\b/i.test(a)&&(B=(B?B+" ":"")+"Simulator");"Opera Mini"==r&&/\bOPiOS\b/.test(a)&&q.push("running in Turbo/Uncompressed mode");"IE"==r&&/\blike iPhone OS\b/.test(a)?(g=p(a.replace(/like iPhone OS/,"")),E=g.manufacturer,B=g.product):/^iP/.test(B)?(r||(r="Safari"),t="iOS"+((g=/ OS ([\d_]+)/i.exec(a))?" "+g[1].replace(/_/g,"."):"")):"Konqueror"!=r||/buntu/i.test(t)?E&&"Google"!=E&&(/Chrome/.test(r)&&
!/\bMobile Safari\b/i.test(a)||/\bVita\b/.test(B))||/\bAndroid\b/.test(t)&&/^Chrome/.test(r)&&/\bVersion\//i.test(a)?(r="Android Browser",t=/\bAndroid\b/.test(t)?t:"Android"):"Silk"==r?(/\bMobi/i.test(a)||(t="Android",q.unshift("desktop mode")),/Accelerated *= *true/i.test(a)&&q.unshift("accelerated")):"PaleMoon"==r&&(g=/\bFirefox\/([\d.]+)\b/.exec(a))?q.push("identifying as Firefox "+g[1]):"Firefox"==r&&(g=/\b(Mobile|Tablet|TV)\b/i.exec(a))?(t||(t="Firefox OS"),B||(B=g[1])):!r||(g=!/\bMinefield\b/i.test(a)&&
/\b(?:Firefox|Safari)\b/.exec(r))?(r&&!B&&/[\/,]|^[^(]+?\)/.test(a.slice(a.indexOf(g+"/")+8))&&(r=null),(g=B||E||t)&&(B||E||/\b(?:Android|Symbian OS|Tablet OS|webOS)\b/.test(t))&&(r=/[a-z]+(?: Hat)?/i.exec(/\bAndroid\b/.test(t)?t:g)+" Browser")):"Electron"==r&&(g=(/\bChrome\/([\d.]+)\b/.exec(a)||0)[1])&&q.push("Chromium "+g):t="Kubuntu";v||(v=l(["(?:Cloud9|CriOS|CrMo|Edge|FxiOS|IEMobile|Iron|Opera ?Mini|OPiOS|OPR|Raven|SamsungBrowser|Silk(?!/[\\d.]+$))","Version",e(r),"(?:Firefox|Minefield|NetFront)"]));
if(g="iCab"==A&&3<parseFloat(v)&&"WebKit"||/\bOpera\b/.test(r)&&(/\bOPR\b/.test(a)?"Blink":"Presto")||/\b(?:Midori|Nook|Safari)\b/i.test(a)&&!/^(?:Trident|EdgeHTML)$/.test(A)&&"WebKit"||!A&&/\bMSIE\b/i.test(a)&&("Mac OS"==t?"Tasman":"Trident")||"WebKit"==A&&/\bPlayStation\b(?! Vita\b)/i.test(r)&&"NetFront")A=[g];"IE"==r&&(g=(/; *(?:XBLWP|ZuneWP)(\d+)/i.exec(a)||0)[1])?(r+=" Mobile",t="Windows Phone "+(/\+$/.test(g)?g:g+".x"),q.unshift("desktop mode")):/\bWPDesktop\b/i.test(a)?(r="IE Mobile",t="Windows Phone 8.x",
q.unshift("desktop mode"),v||(v=(/\brv:([\d.]+)/.exec(a)||0)[1])):"IE"!=r&&"Trident"==A&&(g=/\brv:([\d.]+)/.exec(a))&&(r&&q.push("identifying as "+r+(v?" "+v:"")),r="IE",v=g[1]);if(J){if(k(n,"global"))if(L&&(g=L.lang.System,O=g.getProperty("os.arch"),t=t||g.getProperty("os.name")+" "+g.getProperty("os.version")),x){try{v=n.require("ringo/engine").version.join("."),r="RingoJS"}catch(U){(g=n.system)&&g.global.system==n.system&&(r="Narwhal",t||(t=g[0].os||null))}r||(r="Rhino")}else"object"==typeof n.process&&
!n.process.browser&&(g=n.process)&&("object"==typeof g.versions&&("string"==typeof g.versions.electron?(q.push("Node "+g.versions.node),r="Electron",v=g.versions.electron):"string"==typeof g.versions.nw&&(q.push("Chromium "+v,"Node "+g.versions.node),r="NW.js",v=g.versions.nw)),r||(r="Node.js",O=g.arch,t=g.platform,v=(v=/[\d.]+/.exec(g.version))?v[0]:null));else f(g=n.runtime)==C?(r="Adobe AIR",t=g.flash.system.Capabilities.os):f(g=n.phantom)==V?(r="PhantomJS",v=(g=g.version||null)&&g.major+"."+g.minor+
"."+g.patch):"number"==typeof Q.documentMode&&(g=/\bTrident\/(\d+)/i.exec(a))?(v=[v,Q.documentMode],(g=+g[1]+4)!=v[1]&&(q.push("IE "+v[1]+" mode"),A&&(A[1]=""),v[1]=g),v="IE"==r?String(v[1].toFixed(1)):v[0]):"number"==typeof Q.documentMode&&/^(?:Chrome|Firefox)\b/.test(r)&&(q.push("masking as "+r+" "+v),r="IE",v="11.0",A=["Trident"],t="Windows");t=t&&c(t)}v&&(g=/(?:[ab]|dp|pre|[ab]\d+pre)(?:\d+\+?)?$/i.exec(v)||/(?:alpha|beta)(?: ?\d)?/i.exec(a+";"+(J&&u.appMinorVersion))||/\bMinefield\b/i.test(a)&&
"a")&&(P=/b/i.test(g)?"beta":"alpha",v=v.replace(RegExp(g+"\\+?$"),"")+("beta"==P?X:W)+(/\d+\+?/.exec(g)||""));if("Fennec"==r||"Firefox"==r&&/\b(?:Android|Firefox OS)\b/.test(t))r="Firefox Mobile";else if("Maxthon"==r&&v)v=v.replace(/\.[\d.]+/,".x");else if(/\bXbox\b/i.test(B))"Xbox 360"==B&&(t=null),"Xbox 360"==B&&/\bIEMobile\b/.test(a)&&q.unshift("mobile mode");else if(!/^(?:Chrome|IE|Opera)$/.test(r)&&(!r||B||/Browser|Mobi/.test(r))||"Windows CE"!=t&&!/Mobi/i.test(a))if("IE"==r&&J)try{null===n.external&&
q.unshift("platform preview")}catch(U){q.unshift("embedded")}else(/\bBlackBerry\b/.test(B)||/\bBB10\b/.test(a))&&(g=(RegExp(B.replace(/ +/g," *")+"/([.\\d]+)","i").exec(a)||0)[1]||v)?(g=[g,/BB10/.test(a)],t=(g[1]?(B=null,E="BlackBerry"):"Device Software")+" "+g[0],v=null):this!=d&&"Wii"!=B&&(J&&I||/Opera/.test(r)&&/\b(?:MSIE|Firefox)\b/i.test(a)||"Firefox"==r&&/\bOS X (?:\d+\.){2,}/.test(t)||"IE"==r&&(t&&!/^Win/.test(t)&&5.5<v||/\bWindows XP\b/.test(t)&&8<v||8==v&&!/\bTrident\b/.test(a)))&&!z.test(g=
p.call(d,a.replace(z,"")+";"))&&g.name&&(g="ing as "+g.name+((g=g.version)?" "+g:""),z.test(r)?(/\bIE\b/.test(g)&&"Mac OS"==t&&(t=null),g="identify"+g):(g="mask"+g,r=N?c(N.replace(/([a-z])([A-Z])/g,"$1 $2")):"Opera",/\bIE\b/.test(g)&&(t=null),J||(v=null)),A=["Presto"],q.push(g));else r+=" Mobile";if(g=(/\bAppleWebKit\/([\d.]+\+?)/i.exec(a)||0)[1]){g=[parseFloat(g.replace(/\.(\d)$/,".0$1")),g];if("Safari"==r&&"+"==g[1].slice(-1))r="WebKit Nightly",P="alpha",v=g[1].slice(0,-1);else if(v==g[1]||v==(g[2]=
(/\bSafari\/([\d.]+\+?)/i.exec(a)||0)[1]))v=null;g[1]=(/\bChrome\/([\d.]+)/i.exec(a)||0)[1];537.36==g[0]&&537.36==g[2]&&28<=parseFloat(g[1])&&"WebKit"==A&&(A=["Blink"]);J&&(y||g[1])?(A&&(A[1]="like Chrome"),g=g[1]||(g=g[0],530>g?1:532>g?2:532.05>g?3:533>g?4:534.03>g?5:534.07>g?6:534.1>g?7:534.13>g?8:534.16>g?9:534.24>g?10:534.3>g?11:535.01>g?12:535.02>g?"13+":535.07>g?15:535.11>g?16:535.19>g?17:536.05>g?18:536.1>g?19:537.01>g?20:537.11>g?"21+":537.13>g?23:537.18>g?24:537.24>g?25:537.36>g?26:"Blink"!=
A?"27":"28")):(A&&(A[1]="like Safari"),g=(g=g[0],400>g?1:500>g?2:526>g?3:533>g?4:534>g?"4+":535>g?5:537>g?6:538>g?7:601>g?8:"8"));A&&(A[1]+=" "+(g+="number"==typeof g?".x":/[.+]/.test(g)?"":"+"));"Safari"==r&&(!v||45<parseInt(v))&&(v=g)}"Opera"==r&&(g=/\bzbov|zvav$/.exec(t))?(r+=" ",q.unshift("desktop mode"),"zvav"==g?(r+="Mini",v=null):r+="Mobile",t=t.replace(RegExp(" *"+g+"$"),"")):"Safari"==r&&/\bChrome\b/.exec(A&&A[1])&&(q.unshift("desktop mode"),r="Chrome Mobile",v=null,/\bOS X\b/.test(t)?(E=
"Apple",t="iOS 4.3+"):t=null);v&&0==v.indexOf(g=/[\d.]+$/.exec(t))&&-1<a.indexOf("/"+g+"-")&&(t=String(t.replace(g,"")).replace(/^ +| +$/g,""));A&&!/\b(?:Avant|Nook)\b/.test(r)&&(/Browser|Lunascape|Maxthon/.test(r)||"Safari"!=r&&/^iOS/.test(t)&&/\bSafari\b/.test(A[1])||/^(?:Adobe|Arora|Breach|Midori|Opera|Phantom|Rekonq|Rock|Samsung Internet|Sleipnir|Web)/.test(r)&&A[1])&&(g=A[A.length-1])&&q.push(g);q.length&&(q=["("+q.join("; ")+")"]);E&&B&&0>B.indexOf(E)&&q.push("on "+E);B&&q.push((/^on /.test(q[q.length-
1])?"":"on ")+B);if(t){var T=(g=/ ([\d.+]+)$/.exec(t))&&"/"==t.charAt(t.length-g[0].length-1);t={architecture:32,family:g&&!T?t.replace(g[0],""):t,version:g?g[1]:null,toString:function(){var a=this.version;return this.family+(a&&!T?" "+a:"")+(64==this.architecture?" 64-bit":"")}}}(g=/\b(?:AMD|IA|Win|WOW|x86_|x)64\b/i.exec(O))&&!/\bi686\b/i.test(O)?(t&&(t.architecture=64,t.family=t.family.replace(RegExp(" *"+g),"")),r&&(/\bWOW64\b/i.test(a)||J&&/\w(?:86|32)$/.test(u.cpuClass||u.platform)&&!/\bWin64; x64\b/i.test(a))&&
q.unshift("32-bit")):t&&/^OS X/.test(t.family)&&"Chrome"==r&&39<=parseFloat(v)&&(t.architecture=64);a||(a=null);n={};n.description=a;n.layout=A&&A[0];n.manufacturer=E;n.name=r;n.prerelease=P;n.product=B;n.ua=a;n.version=r&&v;n.os=t||{architecture:null,family:null,version:null,toString:function(){return"null"}};n.parse=p;n.toString=function(){return this.description||""};n.version&&q.unshift(v);n.name&&q.unshift(r);t&&r&&(t!=String(t).split(" ")[0]||t!=r.split(" ")[0]&&!B)&&q.push(B?"("+t+")":"on "+
t);q.length&&(n.description=q.join(" "));return n}var l={"function":!0,object:!0},h=l[typeof window]&&window||this,n=l[typeof exports]&&exports;l=l[typeof module]&&module&&!module.nodeType&&module;var q=n&&l&&"object"==typeof global&&global;!q||q.global!==q&&q.window!==q&&q.self!==q||(h=q);var y=Math.pow(2,53)-1,z=/\bOpera/;q=Object.prototype;var u=q.hasOwnProperty,w=q.toString,x=p();"function"==typeof define&&"object"==typeof define.amd&&define.amd?(h.platform=x,define(function(){return x})):n&&
l?d(x,function(a,c){n[c]=a}):h.platform=x}).call(this);
function buildIOSMeta(){for(var a=[{name:"viewport",content:"width=device-width, height=device-height, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no"},{name:"apple-mobile-web-app-capable",content:"yes"},{name:"apple-mobile-web-app-status-bar-style",content:"black"}],b=0;b<a.length;b++){var c=document.createElement("meta");c.name=a[b].name;c.content=a[b].content;var d=window.document.head.querySelector('meta[name="'+c.name+'"]');d&&d.parentNode.removeChild(d);window.document.head.appendChild(c)}}
function hideIOSFullscreenPanel(){jQuery(".xxx-ios-fullscreen-message").css("display","none");jQuery(".xxx-ios-fullscreen-scroll").css("display","none");jQuery(".xxx-game-iframe-full").removeClass("xxx-game-iframe-iphone-se")}function buildIOSFullscreenPanel(){jQuery("body").append('<div class="xxx-ios-fullscreen-message"><div class="xxx-ios-fullscreen-swipe"></div></div><div class="xxx-ios-fullscreen-scroll"></div>')}
function showIOSFullscreenPanel(){jQuery(".xxx-ios-fullscreen-message").css("display","block");jQuery(".xxx-ios-fullscreen-scroll").css("display","block")}
function __iosResize(){window.scrollTo(0,0);if("iPhone"===platform.product)switch(window.devicePixelRatio){case 2:switch(window.innerWidth){case 568:320!==window.innerHeight&&jQuery(".xxx-game-iframe-full").addClass("xxx-game-iframe-iphone-se");break;case 667:375===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;default:hideIOSFullscreenPanel()}break;case 3:switch(window.innerWidth){case 736:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;
case 724:375===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;default:hideIOSFullscreenPanel()}break;default:hideIOSFullscreenPanel()}}function iosResize(){__iosResize();setTimeout(function(){__iosResize()},500)}$(document).ready(function(){platform&&"iPhone"===platform.product&&"Safari"===platform.name&&(buildIOSFullscreenPanel(),buildIOSMeta())});jQuery(window).resize(function(){platform&&"iPhone"===platform.product&&"Safari"===platform.name&&iosResize()});
(function(){var a="undefined"!==typeof window&&"undefined"!==typeof window.document?window.document:{},b="undefined"!==typeof module&&module.exports,c="undefined"!==typeof Element&&"ALLOW_KEYBOARD_INPUT"in Element,d=function(){for(var c,b=["requestFullscreen exitFullscreen fullscreenElement fullscreenEnabled fullscreenchange fullscreenerror".split(" "),"webkitRequestFullscreen webkitExitFullscreen webkitFullscreenElement webkitFullscreenEnabled webkitfullscreenchange webkitfullscreenerror".split(" "),
"webkitRequestFullScreen webkitCancelFullScreen webkitCurrentFullScreenElement webkitCancelFullScreen webkitfullscreenchange webkitfullscreenerror".split(" "),"mozRequestFullScreen mozCancelFullScreen mozFullScreenElement mozFullScreenEnabled mozfullscreenchange mozfullscreenerror".split(" "),"msRequestFullscreen msExitFullscreen msFullscreenElement msFullscreenEnabled MSFullscreenChange MSFullscreenError".split(" ")],d=0,f=b.length,h={};d<f;d++)if((c=b[d])&&c[1]in a){for(d=0;d<c.length;d++)h[b[0][d]]=
c[d];return h}return!1}(),f={change:d.fullscreenchange,error:d.fullscreenerror},k={request:function(b){var e=d.requestFullscreen;b=b||a.documentElement;if(/5\.1[.\d]* Safari/.test(navigator.userAgent))b[e]();else b[e](c&&Element.ALLOW_KEYBOARD_INPUT)},exit:function(){a[d.exitFullscreen]()},toggle:function(a){this.isFullscreen?this.exit():this.request(a)},onchange:function(a){this.on("change",a)},onerror:function(a){this.on("error",a)},on:function(c,b){var d=f[c];d&&a.addEventListener(d,b,!1)},off:function(c,
b){var d=f[c];d&&a.removeEventListener(d,b,!1)},raw:d};d?(Object.defineProperties(k,{isFullscreen:{get:function(){return!!a[d.fullscreenElement]}},element:{enumerable:!0,get:function(){return a[d.fullscreenElement]}},enabled:{enumerable:!0,get:function(){return!!a[d.fullscreenEnabled]}}}),b?module.exports=k:window.screenfull=k):b?module.exports=!1:window.screenfull=!1})();var s_iOffsetX=0,s_iOffsetY=0,s_fInverseScaling=0,s_bIsIphone=!1;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);function trace(a){console.log(a)}function isChrome(){return/Chrome/.test(navigator.userAgent)&&/Google Inc/.test(navigator.vendor)}function isIOS(){var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");for(-1!==navigator.userAgent.toLowerCase().indexOf("iphone")&&(s_bIsIphone=!0);a.length;)if(navigator.platform===a.pop())return!0;return s_bIsIphone=!1}$(window).resize(function(){sizeHandler()});
function getSize(a){var b=a.toLowerCase(),c=window.document,d=c.documentElement;if(void 0===window["inner"+a])a=d["client"+a];else if(window["inner"+a]!=d["client"+a]){var f=c.createElement("body");f.id="vpw-test-b";f.style.cssText="overflow:scroll";var k=c.createElement("div");k.id="vpw-test-d";k.style.cssText="position:absolute;top:-1000px";k.innerHTML="<style>@media("+b+":"+d["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+b+":7px!important}}</style>";f.appendChild(k);d.insertBefore(f,c.head);
a=7==k["offset"+a]?d["client"+a]:window["inner"+a];d.removeChild(f)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var b=getSize("Width");_checkOrientation(b,a);var c=Math.min(a/CANVAS_HEIGHT,b/CANVAS_WIDTH),d=CANVAS_WIDTH*c;c*=CANVAS_HEIGHT;if(c<a){var f=a-c;c+=f;d+=CANVAS_WIDTH/CANVAS_HEIGHT*f}else d<b&&(f=b-d,d+=f,c+=CANVAS_HEIGHT/CANVAS_WIDTH*f);f=a/2-c/2;var k=b/2-d/2,e=CANVAS_WIDTH/d;if(k*e<-EDGEBOARD_X||f*e<-EDGEBOARD_Y)c=Math.min(a/(CANVAS_HEIGHT-2*
EDGEBOARD_Y),b/(CANVAS_WIDTH-2*EDGEBOARD_X)),d=CANVAS_WIDTH*c,c*=CANVAS_HEIGHT,f=(a-c)/2,k=(b-d)/2,e=CANVAS_WIDTH/d;s_iOffsetX=-1*k*e;s_iOffsetY=-1*f*e;0<=f&&(s_iOffsetY=0);0<=k&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_bIsIphone?(canvas=document.getElementById("canvas"),s_oStage.canvas.width=2*d,s_oStage.canvas.height=2*c,canvas.style.width=d+"px",canvas.style.height=c+"px",s_oStage.scaleX=
s_oStage.scaleY=2*Math.min(d/CANVAS_WIDTH,c/CANVAS_HEIGHT)):s_bMobile||isChrome()?($("#canvas").css("width",d+"px"),$("#canvas").css("height",c+"px")):(s_oStage.canvas.width=d,s_oStage.canvas.height=c,s_iScaleFactor=Math.min(d/CANVAS_WIDTH,c/CANVAS_HEIGHT),s_oStage.scaleX=s_oStage.scaleY=s_iScaleFactor);0>f||(f=(a-c)/2);$("#canvas").css("top",f+"px");$("#canvas").css("left",k+"px");fullscreenHandler()}}
function _checkOrientation(a,b){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(a>b?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),
s_oMain.stopUpdate()))}function createBitmap(a,b,c){var d=new createjs.Bitmap(a),f=new createjs.Shape;b&&c?f.graphics.beginFill("#fff").drawRect(0,0,b,c):f.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);d.hitArea=f;return d}function createSprite(a,b,c,d,f,k){a=null!==b?new createjs.Sprite(a,b):new createjs.Sprite(a);b=new createjs.Shape;b.graphics.beginFill("#000000").drawRect(-c,-d,f,k);a.hitArea=b;return a}
function randomFloatBetween(a,b,c){"undefined"===typeof c&&(c=2);return parseFloat(Math.min(a+Math.random()*(b-a),b).toFixed(c))}function rotateVector2D(a,b){var c=b.getX()*Math.cos(a)+b.getY()*Math.sin(a),d=b.getX()*-Math.sin(a)+b.getY()*Math.cos(a);b.set(c,d)}function tweenVectorsOnX(a,b,c){return a+c*(b-a)}function shuffle(a){for(var b=a.length,c,d;0!==b;)d=Math.floor(Math.random()*b),--b,c=a[b],a[b]=a[d],a[d]=c;return a}
function bubbleSort(a){do{var b=!1;for(var c=0;c<a.length-1;c++)a[c]>a[c+1]&&(b=a[c],a[c]=a[c+1],a[c+1]=b,b=!0)}while(b)}function compare(a,b){return a.index>b.index?-1:a.index<b.index?1:0}function easeLinear(a,b,c,d){return c*a/d+b}function easeInQuad(a,b,c,d){return c*(a/=d)*a+b}function easeInSine(a,b,c,d){return-c*Math.cos(a/d*(Math.PI/2))+c+b}function easeInCubic(a,b,c,d){return c*(a/=d)*a*a+b}
function getTrajectoryPoint(a,b){var c=new createjs.Point,d=(1-a)*(1-a),f=a*a;c.x=d*b.start.x+2*(1-a)*a*b.traj.x+f*b.end.x;c.y=d*b.start.y+2*(1-a)*a*b.traj.y+f*b.end.y;return c}function formatTime(a){a/=1E3;var b=Math.floor(a/60);a=Math.floor(a-60*b);var c="";c=10>b?c+("0"+b+":"):c+(b+":");return 10>a?c+("0"+a):c+a}function degreesToRadians(a){return a*Math.PI/180}function checkRectCollision(a,b){var c=getBounds(a,.9);var d=getBounds(b,.98);return calculateIntersection(c,d)}
function calculateIntersection(a,b){var c,d,f,k;var e=a.x+(c=a.width/2);var m=a.y+(d=a.height/2);var p=b.x+(f=b.width/2);var l=b.y+(k=b.height/2);e=Math.abs(e-p)-(c+f);m=Math.abs(m-l)-(d+k);return 0>e&&0>m?(e=Math.min(Math.min(a.width,b.width),-e),m=Math.min(Math.min(a.height,b.height),-m),{x:Math.max(a.x,b.x),y:Math.max(a.y,b.y),width:e,height:m,rect1:a,rect2:b}):null}
function getBounds(a,b){var c={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){c.x2=-Infinity;c.y2=-Infinity;var d=a.children,f=d.length,k;for(k=0;k<f;k++){var e=getBounds(d[k],1);e.x<c.x&&(c.x=e.x);e.y<c.y&&(c.y=e.y);e.x+e.width>c.x2&&(c.x2=e.x+e.width);e.y+e.height>c.y2&&(c.y2=e.y+e.height)}Infinity==c.x&&(c.x=0);Infinity==c.y&&(c.y=0);Infinity==c.x2&&(c.x2=0);Infinity==c.y2&&(c.y2=0);c.width=c.x2-c.x;c.height=c.y2-c.y;delete c.x2;delete c.y2}else{if(a instanceof createjs.Bitmap){f=
a.sourceRect||a.image;k=f.width*b;var m=f.height*b}else if(a instanceof createjs.Sprite)if(a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image){f=a.spriteSheet.getFrame(a.currentFrame);k=f.rect.width;m=f.rect.height;d=f.regX;var p=f.regY}else c.x=a.x||0,c.y=a.y||0;else c.x=a.x||0,c.y=a.y||0;d=d||0;k=k||0;p=p||0;m=m||0;c.regX=d;c.regY=p;f=a.localToGlobal(0-d,0-p);e=a.localToGlobal(k-d,m-p);k=a.localToGlobal(k-d,0-p);d=a.localToGlobal(0-d,m-p);c.x=
Math.min(Math.min(Math.min(f.x,e.x),k.x),d.x);c.y=Math.min(Math.min(Math.min(f.y,e.y),k.y),d.y);c.width=Math.max(Math.max(Math.max(f.x,e.x),k.x),d.x)-c.x;c.height=Math.max(Math.max(Math.max(f.y,e.y),k.y),d.y)-c.y}return c}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(a){for(var b=a.length,c,d;0<b;)d=Math.floor(Math.random()*b),b--,c=a[b],a[b]=a[d],a[d]=c;return a}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var b=document.createEvent("MouseEvents");b.initEvent("click",!0,!0);a.dispatchEvent(b)}}};
(function(){function a(a){var c={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in c?document.body.className=c[a.type]:(document.body.className=this[b]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var b="hidden";b in document?document.addEventListener("visibilitychange",a):(b="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(b="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(b="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(a){for(var b=window.location.search.substring(1).split("&"),c=0;c<b.length;c++){var d=b[c].split("=");if(d[0]==a)return d[1]}}function playSound(a,b,c){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(s_aSounds[a].play(),s_aSounds[a].volume(b),s_aSounds[a].loop(c),s_aSounds[a]):null}function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].stop()}function setVolume(a,b){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].volume(b)}
function setMute(a,b){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].mute(b)}function fullscreenHandler(){ENABLE_FULLSCREEN&&!1!==screenfull.enabled&&(s_bFullscreen=screen.height<window.innerHeight+3&&screen.height>window.innerHeight-3?!0:!1,null!==s_oInterface&&s_oInterface.resetFullscreenBut(),null!==s_oMenu&&s_oMenu.resetFullscreenBut())}
if(screenfull.enabled)screenfull.on("change",function(){s_bFullscreen=screenfull.isFullscreen;null!==s_oInterface&&s_oInterface.resetFullscreenBut();null!==s_oMenu&&s_oMenu.resetFullscreenBut()});
function CSpriteLibrary(){var a,b,c,d,f,k;this.init=function(e,m,p){c=b=0;d=e;f=m;k=p;a={}};this.addSprite=function(c,d){a.hasOwnProperty(c)||(a[c]={szPath:d,oSprite:new Image},b++)};this.getSprite=function(c){return a.hasOwnProperty(c)?a[c].oSprite:null};this._onSpritesLoaded=function(){f.call(k)};this._onSpriteLoaded=function(){d.call(k);++c==b&&this._onSpritesLoaded()};this.loadSprites=function(){for(var c in a)a[c].oSprite.oSpriteLibrary=this,a[c].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[c].oSprite.onerror=function(c){var b=c.currentTarget;setTimeout(function(){a[b.szKey].oSprite.src=a[b.szKey].szPath},500)},a[c].oSprite.src=a[c].szPath};this.getNumSprites=function(){return b};this.loadSpriteGroup=function(c,d,f,l){for(var h=0;h<c.length;h++)a[c[h].key]={szPath:c[h].path,oSprite:new Image},b++;this._loadInStreamingSprite(c,d,f,l)};this._loadInStreamingSprite=function(c,b,d,f){var h=c.splice(0,1)[0].key;a[h].oSprite.oSpriteLibrary=this;a[h].oSprite.onload=function(){this.oSpriteLibrary._onElementOfSpriteGroupLoaded(c,
b,d,f)};a[h].oSprite.onerror=function(c){setTimeout(function(){a[h].oSprite.src=a[h].szPath},500)};a[h].oSprite.src=a[h].szPath};this._onElementOfSpriteGroupLoaded=function(a,c,b,d){0===a.length?b&&b.call(c,d):s_oSpriteLibrary._loadInStreamingSprite(a,c,b,d)}}
var CANVAS_WIDTH=790,CANVAS_HEIGHT=960,FONT="pixel_lcd7regular",FONT2="SportsJersey-Regular",EDGEBOARD_X=150,EDGEBOARD_Y=0,FPS_TIME=1E3/24,DISABLE_SOUND_MOBILE=!1,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,BATTER_X=CANVAS_WIDTH/2-225,BATTER_Y=CANVAS_HEIGHT-550,PITCHER_X=CANVAS_WIDTH/2-105,PITCHER_Y=CANVAS_HEIGHT/2-433,BALL_X=CANVAS_WIDTH/2-50,BALL_Y=CANVAS_HEIGHT/2-400,BALL_TO_THROW,STEP_SPEED_BALL_HITTED=1.3,STEP_SPEED_STADIUM,AREA_VALUE=[],OFFSET_FOR_HIT,OFFSET_FOR_PERFECT_HIT,PERFECT_HIT_X=
BALL_X+50,PERFECT_HIT_Y=BALL_Y+470,ALMOST_MINUS,ALMOST_PLUS,END_POINT_X=PERFECT_HIT_X,END_POINT_Y=CANVAS_HEIGHT,END_POINT_X_ALMOST_MINUS_LEFT=CANVAS_WIDTH/2-200,END_POINT_X_ALMOST_MINUS_RIGHT=CANVAS_WIDTH/2+200,END_POINT_Y_ALMOST_MINUS=0,END_POINT_X_ALMOST_PLUS_LEFT=CANVAS_WIDTH/2-300,END_POINT_X_ALMOST_PLUS_RIGHT=CANVAS_WIDTH/2+300,END_POINT_Y_ALMOST_PLUS=0,END_POINT_X_PERFECT_LEFT=CANVAS_WIDTH/2-100,END_POINT_X_PERFECT_RIGHT=CANVAS_WIDTH/2+100,END_POINT_Y_PERFECT=0,START_POINT_STADIUM_X=CANVAS_WIDTH/
2,START_POINT_STADIUM_Y=CANVAS_HEIGHT/2+250,NUM_SPRITE_PLAYERS=26,NUM_SPRITE_BATTING=18,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,ENABLE_FULLSCREEN,ENABLE_CHECK_ORIENTATION;TEXT_GAMEOVER="您的球已經打完.";TEXT_SCORE="您的最後積分是:\n\n";TEXT_PANEL="恭喜! 您獲得";TEXT_PANEL_POINT=" 分";SCORE_TEXT="分數: ";TEXT_CREDITS_DEVELOPED="DEVELOPED BY";var TEXT_PRELOADER_CONTINUE="開始";TEXT_SHARE_IMAGE="200x200.jpg";
TEXT_SHARE_TITLE="恭喜!";TEXT_SHARE_MSG1="您獲得 <strong>";TEXT_SHARE_MSG2=" 分</strong>!<br><br>與您的好友分享獲得的分數!";TEXT_SHARE_SHARE1="我的分數是 ";TEXT_SHARE_SHARE2=" 分! 您能獲得更好的分數嗎?";
function CPreloader(){var a,b,c,d,f,k,e,m,p,l;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.addSprite("200x200","./sprites/200x200.jpg");s_oSpriteLibrary.addSprite("but_start","./sprites/but_start.png");s_oSpriteLibrary.loadSprites();l=new createjs.Container;s_oStage.addChild(l)};this.unload=function(){p.unload();l.removeAllChildren()};this._onImagesLoaded=function(){};
this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var h=new createjs.Shape;h.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);l.addChild(h);h=s_oSpriteLibrary.getSprite("200x200");e=createBitmap(h);e.regX=.5*h.width;e.regY=.5*h.height;e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT/2-80;l.addChild(e);m=new createjs.Shape;m.graphics.beginFill("rgba(0,0,0,0.01)").drawRoundRect(e.x-100,e.y-100,200,200,10);l.addChild(m);e.mask=m;h=
s_oSpriteLibrary.getSprite("progress_bar");d=createBitmap(h);d.x=CANVAS_WIDTH/2-h.width/2;d.y=CANVAS_HEIGHT/2+70;l.addChild(d);a=h.width;b=h.height;f=new createjs.Shape;f.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(d.x,d.y,1,b);l.addChild(f);d.mask=f;c=new createjs.Text("","30px "+FONT2,"#fff");c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT/2+120;c.textBaseline="alphabetic";c.textAlign="center";l.addChild(c);h=s_oSpriteLibrary.getSprite("but_start");p=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2+100,
h,TEXT_PRELOADER_CONTINUE,"Arial","#000",36,l);p.addEventListener(ON_MOUSE_UP,this._onButStartRelease,this);p.setVisible(!1);k=new createjs.Shape;k.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);l.addChild(k);createjs.Tween.get(k).to({alpha:0},500).call(function(){createjs.Tween.removeTweens(k);l.removeChild(k)})};this._onButStartRelease=function(){s_oMain._allResourcesLoaded()};this.refreshLoader=function(h){c.text=h+"%";100===h&&(p.setVisible(!0),c.visible=!1,d.visible=!1);
f.graphics.clear();h=Math.floor(h*a/100);f.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(d.x,d.y,h,b)};this._init()}
function CMain(a){var b,c=0,d=0,f=STATE_LOADING,k,e;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.framerate=30;navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=
!0);s_oSpriteLibrary=new CSpriteLibrary;seekAndDestroy()?k=new CPreloader:window.location.href="http://www.codethislab.com/contact-us.html"};this.preloaderReady=function(){this._loadImages();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();b=!0};this.soundLoaded=function(){c++;k.refreshLoader(Math.floor(c/d*100))};this._initSounds=function(){var a=[];a.push({path:"./sounds/",filename:"baseball_buzzer",loop:!1,volume:1,ingamename:"baseball_buzzer"});a.push({path:"./sounds/",filename:"baseball_countdown_1",
loop:!1,volume:1,ingamename:"baseball_countdown_1"});a.push({path:"./sounds/",filename:"baseball_countdown_2",loop:!1,volume:1,ingamename:"baseball_countdown_2"});a.push({path:"./sounds/",filename:"baseball_crowd_homerun",loop:!1,volume:1,ingamename:"baseball_crowd_homerun"});a.push({path:"./sounds/",filename:"baseball_crowd_strike",loop:!1,volume:1,ingamename:"baseball_crowd_strike"});a.push({path:"./sounds/",filename:"baseball_drop_bounce_grass",loop:!1,volume:1,ingamename:"baseball_drop_bounce_grass"});
a.push({path:"./sounds/",filename:"baseball_hit_ball",loop:!1,volume:1,ingamename:"baseball_hit_ball"});a.push({path:"./sounds/",filename:"crowd_cheering",loop:!0,volume:1,ingamename:"crowd_cheering"});a.push({path:"./sounds/",filename:"baseball_applauses",loop:!1,volume:1,ingamename:"baseball_applauses"});a.push({path:"./sounds/",filename:"crowd_ohhh",loop:!1,volume:1,ingamename:"crowd_ohhh"});a.push({path:"./sounds/",filename:"soundtrack",loop:!0,volume:1,ingamename:"soundtrack"});d+=a.length;s_aSounds=
[];for(var c=0;c<a.length;c++)s_aSounds[a[c].ingamename]=new Howl({src:[a[c].path+a[c].filename+".mp3"],autoplay:!1,preload:!0,loop:a[c].loop,volume:a[c].volume,onload:s_oMain.soundLoaded})};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("but_exit",
"./sprites/but_exit.png");s_oSpriteLibrary.addSprite("logo_menu","./sprites/logo_menu.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("score_panel","./sprites/score_panel.png");s_oSpriteLibrary.addSprite("air_view","./sprites/air_view.jpg");s_oSpriteLibrary.addSprite("ball","./sprites/ball.png");s_oSpriteLibrary.addSprite("ball_shadow","./sprites/ball_shadow.png");s_oSpriteLibrary.addSprite("area_bottom",
"./sprites/area_bottom.png");s_oSpriteLibrary.addSprite("area_top","./sprites/area_top.png");s_oSpriteLibrary.addSprite("crowd_left","./sprites/crowd_left.png");s_oSpriteLibrary.addSprite("crowd_right","./sprites/crowd_right.png");s_oSpriteLibrary.addSprite("1","./sprites/1.png");s_oSpriteLibrary.addSprite("2","./sprites/2.png");s_oSpriteLibrary.addSprite("3","./sprites/3.png");s_oSpriteLibrary.addSprite("start_msg","./sprites/start_msg.png");s_oSpriteLibrary.addSprite("strike_msg","./sprites/strike_msg.png");
s_oSpriteLibrary.addSprite("but_credits","./sprites/but_credits.png");s_oSpriteLibrary.addSprite("logo_credits","./sprites/logo_credits.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");for(var a=0;a<NUM_SPRITE_BATTING;a++)s_oSpriteLibrary.addSprite("batter_batting_"+a,"./sprites/batter_hit/batter_batting_"+a+".png");for(a=0;a<NUM_SPRITE_PLAYERS;a++)s_oSpriteLibrary.addSprite("batter_idle_"+a,"./sprites/batter_idle/batter_idle_"+a+".png");for(a=0;a<NUM_SPRITE_PLAYERS;a++)s_oSpriteLibrary.addSprite("pitcher_"+
a,"./sprites/pitcher/pitcher_"+a+".png");d+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){c++;k.refreshLoader(Math.floor(c/d*100))};this._onAllImagesLoaded=function(){};this._allResourcesLoaded=function(){k.unload();s_oSoundTrack=playSound("soundtrack",1,!0);s_oMain.gotoMenu()};this.gotoMenu=function(){new CMenu;f=STATE_MENU};this.gotoGame=function(){e=new CGame(m);f=STATE_GAME};this.gotoHelp=function(){new CHelp;f=STATE_HELP};this.stopUpdate=function(){b=
!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||Howler.mute(!0)};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();b=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none");(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)&&s_bAudioActive&&Howler.mute(!1)};this._update=function(a){if(!1!==b){var c=(new Date).getTime();s_iTimeElaps=c-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=c;1E3<=s_iCntTime&&(s_iCurFps=
s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);f===STATE_GAME&&e.update();s_oStage.update(a)}};s_oMain=this;var m=a;ENABLE_FULLSCREEN=a.fullscreen;ENABLE_CHECK_ORIENTATION=a.check_orientation;this.initContainer()}var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_bBounce=!0,s_oDrawLayer,s_oStage,s_oMain,s_oStadium,s_oBall,s_oSpriteLibrary,s_oSoundTrack=null,s_oCanvas,s_aSounds;
function CTextButton(a,b,c,d,f,k,e,m){var p,l,h,n,q,y,z,u,w,x,C;this._init=function(a,c,b,d,f,e,k,m){p=!1;n=[];q=[];C=createBitmap(b);l=b.width;h=b.height;x=new createjs.Text(d,k+"px "+f,e);x.textAlign="center";x.textBaseline="alphabetic";x.lineWidth=.9*l;x.x=b.width/2;x.y=Math.floor(b.height/2)+15;w=new createjs.Container;w.x=a;w.y=c;w.regX=b.width/2;w.regY=b.height/2;s_bMobile||(w.cursor="pointer");w.addChild(C,x);!1!==m&&s_oStage.addChild(w);this._initListener()};this.unload=function(){w.off("mousedown",
y);w.off("pressup",z);s_oStage.removeChild(w)};this.setVisible=function(a){w.visible=a};this.setAlign=function(a){x.textAlign=a};this.enable=function(){p=!1;C.filters=[];C.cache(0,0,l,h)};this.disable=function(){p=!0;var a=(new createjs.ColorMatrix).adjustSaturation(-100).adjustBrightness(40);C.filters=[new createjs.ColorMatrixFilter(a)];C.cache(0,0,l,h)};this._initListener=function(){y=w.on("mousedown",this.buttonDown);z=w.on("pressup",this.buttonRelease)};this.addEventListener=function(a,c,b){n[a]=
c;q[a]=b};this.addEventListenerWithParams=function(a,c,b,d){n[a]=c;q[a]=b;u=d};this.buttonRelease=function(){p||(w.scaleX=1,w.scaleY=1,n[ON_MOUSE_UP]&&n[ON_MOUSE_UP].call(q[ON_MOUSE_UP],u))};this.buttonDown=function(){p||(w.scaleX=.9,w.scaleY=.9,n[ON_MOUSE_DOWN]&&n[ON_MOUSE_DOWN].call(q[ON_MOUSE_DOWN]))};this.setPosition=function(a,c){w.x=a;w.y=c};this.changeText=function(a){x.text=a};this.setX=function(a){w.x=a};this.setY=function(a){w.y=a};this.getButtonImage=function(){return w};this.getX=function(){return w.x};
this.getY=function(){return w.y};this.getSprite=function(){return w};this._init(a,b,c,d,f,k,e,m);return this}
function CToggle(a,b,c,d,f){var k,e,m,p=[],l,h,n;this._init=function(a,c,b,d){e=[];m=[];var h=new createjs.SpriteSheet({images:[b],frames:{width:b.width/2,height:b.height,regX:b.width/2/2,regY:b.height/2},animations:{state_true:[0],state_false:[1]}});k=d;n=createSprite(h,"state_"+k,b.width/2/2,b.height/2,b.width/2,b.height);n.x=a;n.y=c;n.cursor="pointer";n.stop();q.addChild(n);this._initListener()};this.unload=function(){n.off("mousedown",l);n.off("pressup",h);q.removeChild(n)};this._initListener=
function(){l=n.on("mousedown",this.buttonDown);h=n.on("pressup",this.buttonRelease)};this.addEventListener=function(a,c,b){e[a]=c;m[a]=b};this.addEventListenerWithParams=function(a,c,b,d){e[a]=c;m[a]=b;p=d};this.setActive=function(a){k=a;n.gotoAndStop("state_"+k)};this.buttonRelease=function(){n.scaleX=1;n.scaleY=1;k=!k;n.gotoAndStop("state_"+k);e[ON_MOUSE_UP]&&e[ON_MOUSE_UP].call(m[ON_MOUSE_UP],p)};this.buttonDown=function(){n.scaleX=.9;n.scaleY=.9;e[ON_MOUSE_DOWN]&&e[ON_MOUSE_DOWN].call(m[ON_MOUSE_DOWN],
p)};this.setPosition=function(a,c){n.x=a;n.y=c};this.setVisible=function(a){n.visible=a};var q=f;this._init(a,b,c,d)}
function CGfxButton(a,b,c){var d,f,k,e=[],m,p,l;this._init=function(a,c,b){d=1;f=[];k=[];l=createBitmap(b);l.x=a;l.y=c;l.regX=b.width/2;l.regY=b.height/2;l.cursor="pointer";s_oStage.addChild(l);this._initListener()};this.unload=function(){l.off("mousedown",m);l.off("pressup",p);s_oStage.removeChild(l)};this.setVisible=function(a){l.visible=a};this._initListener=function(){m=l.on("mousedown",this.buttonDown);p=l.on("pressup",this.buttonRelease)};this.addEventListener=function(a,c,b){f[a]=c;k[a]=b};
this.addEventListenerWithParams=function(a,c,b,d){f[a]=c;k[a]=b;e=d};this.buttonRelease=function(){l.scaleX=d;l.scaleY=d;f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(k[ON_MOUSE_UP],e)};this.buttonDown=function(){l.scaleX=.9*d;l.scaleY=.9*d;f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN],e)};this.setScale=function(a){d=a;l.scaleX=a;l.scaleY=a};this.setPosition=function(a,c){l.x=a;l.y=c};this.setX=function(a){l.x=a};this.setY=function(a){l.y=a};this.getButtonImage=function(){return l};this.getX=function(){return l.x};
this.getY=function(){return l.y};this._init(a,b,c);return this}
function CMenu(){var a,b,c,d,f,k,e,m,p,l,h,n,q,y=null,z=null;this._init=function(){setVolume("soundtrack",1);e=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(e);m=createBitmap(s_oSpriteLibrary.getSprite("logo_menu"));m.x=140;m.y=20;s_oStage.addChild(m);var u=s_oSpriteLibrary.getSprite("but_play");p=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-225,u);p.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)u=s_oSpriteLibrary.getSprite("audio_icon"),
f=CANVAS_WIDTH-u.height/2-10,k=u.height/2+10,h=new CToggle(f,k,u,s_bAudioActive,s_oStage),h.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);u=s_oSpriteLibrary.getSprite("but_credits");c=u.height/2+10;d=u.height/2+10;n=new CGfxButton(c,d,u,s_oStage);n.addEventListener(ON_MOUSE_UP,this._onCredits,this);u=window.document;var w=u.documentElement;y=w.requestFullscreen||w.mozRequestFullScreen||w.webkitRequestFullScreen||w.msRequestFullscreen;z=u.exitFullscreen||u.mozCancelFullScreen||u.webkitExitFullscreen||
u.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(y=!1);y&&screenfull.enabled&&(u=s_oSpriteLibrary.getSprite("but_fullscreen"),a=c+u.width/2+10,b=d,q=new CToggle(a,b,u,s_bFullscreen,s_oStage),q.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));l=new createjs.Shape;l.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(l);createjs.Tween.get(l).to({alpha:0},1E3).call(function(){l.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){p.unload();
p=null;l.visible=!1;n.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)h.unload(),h=null;y&&screenfull.enabled&&q.unload();s_oStage.removeAllChildren();s_oMenu=null};this.refreshButtonPos=function(e,l){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||h.setPosition(f-e,l+k);y&&screenfull.enabled&&q.setPosition(a+e,b+l);n.setPosition(c+e,l+d)};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};/*this._onCredits=function(){new CCreditsPanel};*/this._onButPlayRelease=
function(){this.unload();$(s_oMain).trigger("start_session");s_oMain.gotoGame()};this.resetFullscreenBut=function(){y&&screenfull.enabled&&q.setActive(s_bFullscreen)};this._onFullscreenRelease=function(){s_bFullscreen?z.call(window.document):y.call(window.document.documentElement);sizeHandler()};s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(a){var b=0,c=0,d=0,f=0,k=0,e,m=!1,p=!1,l=!1,h=!1,n=!1,q,y=null,z,u,w,x;this._init=function(){$(s_oMain).trigger("start_level",1);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)setVolume("soundtrack",.2),playSound("crowd_cheering",1,!0);var a=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(a);z=new createjs.Container;s_oStage.addChild(z);a=new createjs.Container;s_oStage.addChild(a);s_oStadium=new CStadium(a);q=new CInterface;w=new CPitcher(z);s_oBall=new CBall(z);
u=new CBatter(z);x=new createjs.Shape;x.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(0,75,CANVAS_WIDTH,CANVAS_HEIGHT+75);z.addChild(x);x.on("mousedown",s_oGame._strike,this,!1);n=!1;a=createBitmap(s_oSpriteLibrary.getSprite("3"));a.x=CANVAS_WIDTH/2;a.y=CANVAS_HEIGHT/2;a.regX=40;a.regY=84;s_oStage.addChild(a);playSound("baseball_countdown_1",1,!1);this.launchCountdown(a)};this.launchCountdown=function(a){createjs.Tween.get(a).to({scaleX:1.3,scaleY:1.3},500,createjs.Ease.cubicOut).wait(500).call(function(){this.visible=
!1;var a=createBitmap(s_oSpriteLibrary.getSprite("2"));a.x=CANVAS_WIDTH/2;a.y=CANVAS_HEIGHT/2;a.regX=40;a.regY=84;a.scaleX=.7;a.scaleY=.7;s_oStage.addChild(a);playSound("baseball_countdown_1",1,!1);createjs.Tween.get(a).to({scaleX:1.3,scaleY:1.3},500,createjs.Ease.cubicOut).wait(500).call(function(){this.visible=!1;var a=createBitmap(s_oSpriteLibrary.getSprite("1"));a.x=CANVAS_WIDTH/2;a.y=CANVAS_HEIGHT/2;a.regX=40;a.regY=84;a.scaleX=.7;a.scaleY=.7;s_oStage.addChild(a);playSound("baseball_countdown_1",
1,!1);createjs.Tween.get(a).to({scaleX:1.3,scaleY:1.3},500,createjs.Ease.cubicOut).wait(500).call(function(){this.visible=!1;var a=createBitmap(s_oSpriteLibrary.getSprite("start_msg"));a.x=CANVAS_WIDTH/2;a.y=CANVAS_HEIGHT/2;a.regX=202.5;a.regY=135;a.scaleX=.7;a.scaleY=.7;s_oStage.addChild(a);playSound("baseball_countdown_2",1,!1);createjs.Tween.get(a).to({scaleX:1.3,scaleY:1.3},500,createjs.Ease.cubicOut).wait(500).call(function(){this.visible=!1;n=e=!0})})})})};this._strike=function(){!0===n&&(m?
(u.hideBatter(c,m),c=0):(u.hideBatter(b,m),b=0),x.visible=!x.visible,m=!m)};this._ballMissed=function(){e=!1;l=!0;playSound("baseball_crowd_strike",1,!1);n=!1;var a=createBitmap(s_oSpriteLibrary.getSprite("strike_msg"));a.x=CANVAS_WIDTH/2;a.y=CANVAS_HEIGHT/2;a.regX=223.5;a.regY=148.5;a.scaleX=.7;a.scaleY=.7;s_oStage.addChild(a);createjs.Tween.get(a).to({scaleX:1,scaleY:1},500,createjs.Ease.cubicOut).wait(800).call(function(){u.hideBatter(b,m);b=0;m&&s_oGame._strike();this.visible=!1;n=e=!0})};this._setScore=
function(a){f+=a;q.viewScore(f)};this.unload=function(){x.off("mousedown",s_oGame._strike,this,!1);stopSound("crowd_cheering");q.unload();null!==y&&y.unload();createjs.Tween.removeAllTweens();s_oStage.removeAllChildren()};this.onExit=function(){this.unload();s_oMain.gotoMenu();$(s_oMain).trigger("end_level",1);$(s_oMain).trigger("show_interlevel_ad");$(s_oMain).trigger("end_session")};this.gameOver=function(){e=!1;y=CEndPanel(s_oSpriteLibrary.getSprite("msg_box"));y.show(f)};this._viewStadium=function(a,
c){s_oStadium.setVisible();s_oStadium.viewAndGetScore(a,c);h=!0};this._restart=function(){k>=BALL_TO_THROW?this.gameOver():(s_oBall.reset(),s_bBounce=!0,h=l=p=!1,s_oStadium.setInvisible(),this._strike())};this.update=function(){if(e){m?(u.hideBatter(c,m),c+1<NUM_SPRITE_BATTING?(u.viewBatter(c+1,m),c++):u.viewBatter(c,m),4===c&&(s_oBall.hittedControl(),s_oBall.getValue())):(u.hideBatter(b,m),b+1<NUM_SPRITE_PLAYERS?(u.viewBatter(b+1,m),b++):(b=0,u.viewBatter(b,m)));!0===l&&(k>=BALL_TO_THROW?this.gameOver():
(s_oBall.reset(),p=!1,0<c&&this._strike(),l=!1,n=!0));if(!p||d+1<NUM_SPRITE_PLAYERS)w.hidePitcher(d),d+1<NUM_SPRITE_PLAYERS?(w.viewPitcher(d+1),d++):d=0,16===d&&(k++,q.viewBallLeft(k),s_oBall.viewBall(),p=!0);p&&s_oBall.update();h&&s_oStadium.update()}};s_oGame=this;BALL_TO_THROW=a.ball_to_throw;OFFSET_FOR_HIT=a.offset_hit;OFFSET_FOR_PERFECT_HIT=a.offset_perfect_hit;STEP_SPEED_STADIUM=a.step_spd_stadium;AREA_VALUE=[a.score_area1,a.score_area2,a.score_area3];ALMOST_MINUS=PERFECT_HIT_Y-OFFSET_FOR_HIT;
ALMOST_PLUS=PERFECT_HIT_Y+OFFSET_FOR_HIT;this._init()}var s_oGame;
function CInterface(){var a,b,c,d,f,k,e,m,p,l,h,n,q,y,z,u,w,x,C,F,G,M,K=null,R=null,v,S;this._init=function(){var H,D=s_oSpriteLibrary.getSprite("but_exit");c=CANVAS_WIDTH-D.height/2-10;d=D.height/2+10;z=new CGfxButton(c,d,D,s_oStage);z.addEventListener(ON_MOUSE_UP,this._onExit,this);a=H=CANVAS_WIDTH-D.width/2-90;b=D.height/2+10;!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(D=s_oSpriteLibrary.getSprite("audio_icon"),y=new CToggle(a,b,D,s_bAudioActive,s_oStage),y.addEventListener(ON_MOUSE_UP,this._onAudioToggle,
this),D=s_oSpriteLibrary.getSprite("but_fullscreen"),f=a-D.width/2-10,k=b):(f=H,k=D.height/2+10);H=window.document;D=H.documentElement;K=D.requestFullscreen||D.mozRequestFullScreen||D.webkitRequestFullScreen||D.msRequestFullscreen;R=H.exitFullscreen||H.mozCancelFullScreen||H.webkitExitFullscreen||H.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(K=!1);K&&screenfull.enabled&&(D=s_oSpriteLibrary.getSprite("but_fullscreen"),M=new CToggle(f,k,D,s_bFullscreen,s_oStage),M.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,
this));u=s_oSpriteLibrary.getSprite("score_panel");n=CANVAS_WIDTH/2-260;q=35;v=new CGfxButton(n,q,u,s_oStage);p=CANVAS_WIDTH/2-315;x=new createjs.Text(SCORE_TEXT,"30px "+FONT,"#ff0000");x.x=p;x.y=47;x.textAlign="center";x.textBaseline="alphabetic";s_oStage.addChild(x);m=CANVAS_WIDTH/2-150;C=new createjs.Text("0","30px "+FONT,"#ff0000");C.x=m;C.y=47;C.textAlign="right";C.textBaseline="alphabetic";s_oStage.addChild(C);w=s_oSpriteLibrary.getSprite("ball");l=CANVAS_WIDTH/2-370;h=80;S=new CGfxButton(l,
h,w,s_oStage);e=CANVAS_WIDTH/2-350;F=new createjs.Text("x "+BALL_TO_THROW,"30px "+FONT2,"#ffffff");F.x=e;F.y=88;F.textAlign="left";F.textBaseline="alphabetic";F.outline=5;s_oStage.addChild(F);G=new createjs.Text("x "+BALL_TO_THROW,"30px "+FONT2,"#ff0000");G.x=e;G.y=88;G.textAlign="left";G.textBaseline="alphabetic";s_oStage.addChild(G);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)y.unload(),y=null;K&&screenfull.enabled&&M.unload();
z.unload();s_oInterface=null};this.refreshButtonPos=function(u,w){z.setPosition(c-u,w+d);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||y.setPosition(a-u,w+b);K&&screenfull.enabled&&M.setPosition(f-u,k+w);v.setPosition(n+u,w+q);S.setPosition(l+u,w+h);x.x=p+u;C.x=m+u;F.x=e+u;G.x=e+u};this.viewScore=function(a){C.text=a};this.viewBallLeft=function(a){F.text="x "+(BALL_TO_THROW-a);G.text="x "+(BALL_TO_THROW-a)};this._onButHelpRelease=function(){_oHelpPanel=new CHelpPanel};this._onButRestartRelease=function(){s_oGame.restartGame()};
this.onExitFromHelp=function(){_oHelpPanel.unload()};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){s_oGame.onExit()};this.resetFullscreenBut=function(){K&&screenfull.enabled&&M.setActive(s_bFullscreen)};this._onFullscreenRelease=function(){s_bFullscreen?R.call(window.document):K.call(window.document.documentElement);sizeHandler()};s_oInterface=this;this._init();return this}var s_oInterface=null;
function CEndPanel(a){var b,c,d,f,k,e;this._init=function(a){playSound("baseball_buzzer",1,!1);b=createBitmap(a);b.x=0;b.y=0;d=new createjs.Text(""," 60px "+FONT2,"#ffffff");d.x=CANVAS_WIDTH/2;d.y=CANVAS_HEIGHT/2-150;d.textAlign="center";d.textBaseline="alphabetic";d.lineWidth=500;d.lineHeight=60;d.outline=5;f=new createjs.Text(""," 60px "+FONT2,"#ff0000");f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT/2-150;f.textAlign="center";f.textBaseline="alphabetic";f.lineHeight=60;f.lineWidth=500;k=new createjs.Text("",
" 60px "+FONT2,"#ffffff");k.x=CANVAS_WIDTH/2;k.y=CANVAS_HEIGHT/2+40;k.textAlign="center";k.textBaseline="alphabetic";k.lineWidth=500;k.outline=5;e=new createjs.Text(""," 60px "+FONT2,"#ff0000");e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT/2+40;e.textAlign="center";e.textBaseline="alphabetic";e.lineWidth=500;c=new createjs.Container;c.alpha=0;c.visible=!1;c.addChild(b,k,e,d,f);s_oStage.addChild(c)};this.unload=function(){c.off("mousedown",this._onExit)};this._initListener=function(){c.on("mousedown",this._onExit)};
this.show=function(a){d.text=TEXT_GAMEOVER;f.text=TEXT_GAMEOVER;k.text=TEXT_SCORE+a;e.text=TEXT_SCORE+a;c.visible=!0;var b=this;createjs.Tween.get(c).to({alpha:1},500).call(function(){b._initListener()});$(s_oMain).trigger("share_event",a);$(s_oMain).trigger("save_score",a)};this._onExit=function(){c.off("mousedown",this._onExit);s_oStage.removeChild(c);s_oGame.onExit()};this._init(a);return this}
function CBatter(a){var b=[],c=[];this._init=function(a){for(var d=0;d<NUM_SPRITE_BATTING;d++)b.push(createBitmap(s_oSpriteLibrary.getSprite("batter_batting_"+d))),b[d].x=BATTER_X-180,b[d].y=BATTER_Y-45,b[d].rotation=0,b[d].visible=!1,a.addChild(b[d]);for(d=0;d<NUM_SPRITE_PLAYERS;d++)c.push(createBitmap(s_oSpriteLibrary.getSprite("batter_idle_"+d))),c[d].x=BATTER_X,c[d].y=BATTER_Y,c[d].rotation=0,c[d].visible=!1,a.addChild(c[d]);c[0].visible=!0};this.viewBatter=function(a,f){f?b[a].visible=!0:c[a].visible=
!0};this.hideBatter=function(a,f){f?b[a].visible=!1:c[a].visible=!1};this.getValue=function(){return _bCellOccupied};this.unload=function(a){};s_oBatter=this;this._init(a)}s_oBatter=null;
function CPitcher(a){var b=[];this._init=function(a){for(var c=0;c<NUM_SPRITE_PLAYERS;c++)b.push(createBitmap(s_oSpriteLibrary.getSprite("pitcher_"+c))),b[c].x=PITCHER_X,b[c].y=PITCHER_Y,b[c].rotation=0,b[c].visible=!1,a.addChild(b[c]);b[0].visible=!0};this.viewPitcher=function(a){b[a].visible=!0};this.hidePitcher=function(a){b[a].visible=!1};this.getValue=function(){return _bCellOccupied};this.unload=function(a){};s_oPticher=this;this._init(a)}s_oPticher=null;
function CBall(a){var b=0,c,d,f,k,e,m,p={x:0,y:0},l={x:0,y:0},h;this._init=function(a){var b=s_oSpriteLibrary.getSprite("ball");c=b.width;d=b.height;e=createBitmap(b);this.reset(b);a.addChild(e)};this.reset=function(){e.x=BALL_X;e.y=BALL_Y;e.regX=c/2;e.regY=d/2;e.scaleX=.4;e.scaleY=.4;e.rotation=0;e.visible=!1;p.x=e.x;p.y=e.y;l.x=END_POINT_X;l.y=END_POINT_Y;STEP_SPEED_BALL_HITTED=1.3;k=!1};this.viewBall=function(){e.visible=!0;this._calculateMid(p,l);f=!0};this.hideBall=function(){e.visible=!1};this._calculateMid=
function(a,c){var b=Math.floor(50*Math.random())+1;b=!0===k?c.x<CANVAS_WIDTH/2?c.y>CANVAS_HEIGHT/2?new createjs.Point(Math.floor(CANVAS_WIDTH/2*Math.random())+100,CANVAS_HEIGHT/2-200-b):new createjs.Point(Math.floor(CANVAS_WIDTH/2*Math.random())+100,CANVAS_HEIGHT/2-200+b):c.x>CANVAS_WIDTH/2?c.y>CANVAS_HEIGHT/2?new createjs.Point(Math.floor(CANVAS_WIDTH/2*Math.random())+300,CANVAS_HEIGHT/2-200-b):new createjs.Point(Math.floor(CANVAS_WIDTH/2*Math.random())+300,CANVAS_HEIGHT/2-200+b):c.x>CANVAS_WIDTH/
2?new createjs.Point(CANVAS_WIDTH/2-50,Math.floor(CANVAS_HEIGHT/2*Math.random()-100)+100):new createjs.Point(CANVAS_WIDTH/2+50,Math.floor(CANVAS_HEIGHT/2*Math.random()-100)+100):.5>Math.random()?new createjs.Point(CANVAS_WIDTH/2-50,Math.floor(CANVAS_HEIGHT/2*Math.random()-100)+100):new createjs.Point(CANVAS_WIDTH/2+50,Math.floor(CANVAS_HEIGHT/2*Math.random()-100)+100);h={start:a,end:c,traj:b}};this._updateBall=function(){b+=STEP_SPEED_BALL_HITTED;40<b&&(b=0,f=e.visible=!1,!0===k?s_oGame._viewStadium(m,
l):s_oGame._ballMissed());var a=easeLinear(b,0,1,40);a=getTrajectoryPoint(a,h);e.x=a.x;e.y=a.y;!0===k?0<=e.scaleX?(e.scaleX-=.03,e.scaleY-=.03):STEP_SPEED_BALL_HITTED-=.2:1>e.scaleX?(e.scaleX+=.03,e.scaleY+=.03):STEP_SPEED_BALL_HITTED+=.2};this.getValue=function(){return e};this.hittedControl=function(){STEP_SPEED_BALL_HITTED=2;e.y>=PERFECT_HIT_Y-OFFSET_FOR_PERFECT_HIT&&e.y<=PERFECT_HIT_Y+OFFSET_FOR_PERFECT_HIT?(playSound("baseball_hit_ball",1,!1),h.traj.x<CANVAS_WIDTH/2?(b=0,p.x=PERFECT_HIT_X,p.y=
PERFECT_HIT_Y,l.x=END_POINT_X_PERFECT_LEFT):(b=0,p.x=PERFECT_HIT_X,p.y=PERFECT_HIT_Y,l.x=END_POINT_X_PERFECT_RIGHT),l.y=END_POINT_Y_PERFECT,m=e.y-PERFECT_HIT_Y,0>m&&(m*=-1),k=!0,h={start:p,end:l,traj:l}):e.y>=ALMOST_MINUS&&e.y<=PERFECT_HIT_Y?(playSound("baseball_hit_ball",1,!1),h.traj.x<CANVAS_WIDTH/2?(b=0,p.x=PERFECT_HIT_X,p.y=PERFECT_HIT_Y,l.x=END_POINT_X_ALMOST_MINUS_RIGHT):(b=0,p.x=PERFECT_HIT_X,p.y=PERFECT_HIT_Y,l.x=END_POINT_X_ALMOST_MINUS_LEFT),l.y=END_POINT_Y_ALMOST_MINUS,m=e.y-PERFECT_HIT_Y,
0>m&&(m*=-1),k=!0,h={start:p,end:l,traj:l}):e.y<=ALMOST_PLUS&&e.y>=PERFECT_HIT_Y&&(playSound("baseball_hit_ball",1,!1),h.traj.x<CANVAS_WIDTH/2?(b=0,p.x=PERFECT_HIT_X,p.y=PERFECT_HIT_Y,l.x=END_POINT_X_ALMOST_PLUS_RIGHT):(b=0,p.x=PERFECT_HIT_X,p.y=PERFECT_HIT_Y,l.x=END_POINT_X_ALMOST_PLUS_LEFT),l.y=END_POINT_Y_ALMOST_PLUS,m=e.y-PERFECT_HIT_Y,0>m&&(m*=-1),k=!0,h={start:p,end:l,traj:l});f=!0};this.unload=function(){};this.update=function(){f&&this._updateBall()};this._init(a)}
function CStadium(a){var b,c,d,f,k,e,m,p;this._init=function(){var b=createBitmap(s_oSpriteLibrary.getSprite("air_view"));a.addChild(b);f=createBitmap(s_oSpriteLibrary.getSprite("area_bottom"));f.y=CANVAS_HEIGHT/2;f.alpha=.5;a.addChild(f);k=createBitmap(s_oSpriteLibrary.getSprite("area_top"));k.y=CANVAS_HEIGHT/2-55;k.alpha=.5;a.addChild(k);e=createBitmap(s_oSpriteLibrary.getSprite("crowd_left"));e.x=CANVAS_WIDTH/2+56;e.y=CANVAS_HEIGHT/2-150;e.alpha=.5;a.addChild(e);m=createBitmap(s_oSpriteLibrary.getSprite("crowd_right"));
m.y=CANVAS_HEIGHT/2-150;m.alpha=.5;a.addChild(m);c=a.visible=!1};this.viewAndGetScore=function(a,b){var h={x:0,y:0},l={x:START_POINT_STADIUM_X,y:START_POINT_STADIUM_Y};switch(b.x){case END_POINT_X_ALMOST_MINUS_LEFT:a<OFFSET_FOR_HIT/2?(d=1,b.y=k.y+30,h.x=b.x-10,h.y=b.y-10):a<OFFSET_FOR_HIT&&a>=OFFSET_FOR_HIT/2&&(d=0,b.y=f.y+30,h.x=b.x-10,h.y=b.y-10);break;case END_POINT_X_ALMOST_MINUS_RIGHT:a<OFFSET_FOR_HIT/2?(d=1,b.y=k.y+30,h.x=b.x+10,h.y=b.y-10):a<OFFSET_FOR_HIT&&a>=OFFSET_FOR_HIT/2&&(d=0,b.y=f.y+
30,h.x=b.x+10,h.y=b.y-10);break;case END_POINT_X_ALMOST_PLUS_LEFT:a<OFFSET_FOR_HIT/2?(d=1,b.y=k.y+30,h.x=b.x-10,h.y=b.y-10):a<OFFSET_FOR_HIT&&a>=OFFSET_FOR_HIT/2&&(d=0,b.y=f.y+40,h.x=b.x-10,h.y=b.y-10);break;case END_POINT_X_ALMOST_PLUS_RIGHT:a<OFFSET_FOR_HIT/2?(d=1,b.y=k.y+30,h.x=b.x+10,h.y=b.y-10):a<OFFSET_FOR_HIT&&a>=OFFSET_FOR_HIT/2&&(d=0,b.y=f.y+50,h.x=b.x+10,h.y=b.y-10);break;case END_POINT_X_PERFECT_LEFT:d=3;s_bBounce=!1;b.x-=30;b.y=e.y+30;break;case END_POINT_X_PERFECT_RIGHT:d=2,s_bBounce=
!1,b.y=m.y+30}var y=new createjs.Container;s_oStage.addChild(y);p=new CStadiumBall(l,b,h,y,d,a);c=!0};this.update=function(){c&&p.update()};this.viewAreaEffect=function(a,b){switch(a){case 0:createjs.Tween.get(f).to({alpha:1},300).call(function(){createjs.Tween.get(f).to({alpha:.5},300).call(function(){createjs.Tween.get(f).to({alpha:1},300).call(function(){createjs.Tween.get(f).to({alpha:.5},300).call(function(){new CPanel(b);s_oGame._setScore(b)})})})});break;case 1:createjs.Tween.get(k).to({alpha:1},
300).call(function(){createjs.Tween.get(k).to({alpha:.5},300).call(function(){createjs.Tween.get(k).to({alpha:1},300).call(function(){createjs.Tween.get(k).to({alpha:.5},300).call(function(){new CPanel(b);s_oGame._setScore(b)})})})});break;case 2:createjs.Tween.get(e).to({alpha:1},300).call(function(){createjs.Tween.get(e).to({alpha:.5},300).call(function(){createjs.Tween.get(e).to({alpha:1},300).call(function(){createjs.Tween.get(e).to({alpha:.5},300).call(function(){new CPanel(b);s_oGame._setScore(b)})})})});
break;case 3:createjs.Tween.get(m).to({alpha:1},300).call(function(){createjs.Tween.get(m).to({alpha:.5},300).call(function(){createjs.Tween.get(m).to({alpha:1},300).call(function(){createjs.Tween.get(m).to({alpha:.5},300).call(function(){new CPanel(b);s_oGame._setScore(b)})})})})}};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)b.unload(),b=null;a.removeAllChildren();s_oStadium=null};this.setVisible=function(){a.visible=!0};this.setInvisible=function(){a.visible=!1;p.unload()};
s_oStadium=this;this._init();return this}s_oStadium=null;
function CStadiumBall(a,b,c,d,f,k){var e=0,m=40,p,l,h,n,q={x:0,y:0},y={x:0,y:0},z={x:0,y:0},u={x:0,y:0},w,x,C=!1;this._init=function(a,b,c,d,e){p=e;n=createBitmap(s_oSpriteLibrary.getSprite("ball_shadow"));n.x=a.x;n.y=a.y;n.regX=n.width/2;n.regY=n.height/2;n.scaleX=.2;n.scaleY=.2;n.alpha=.5;n.rotation=0;d.addChild(n);h=createBitmap(s_oSpriteLibrary.getSprite("ball"));h.x=a.x;h.y=a.y;h.regX=h.width/2;h.regY=h.height/2;h.scaleX=.3;h.scaleY=.3;h.rotation=0;d.addChild(h);y.x=n.x;y.y=n.y;q.x=h.x;q.y=h.y;
z.x=b.x;z.y=b.y;u.x=c.x;u.y=c.y;l=!0;this._calculateMid(q,z)};this.viewBall=function(){h.visible=!0;l=n.visible=!0};this.hideBall=function(){h.visible=!1;n.visible=!1};this._calculateMid=function(a,b){var c=!1===C?new createjs.Point(CANVAS_WIDTH/2,Math.floor(CANVAS_HEIGHT/2*Math.random()-100)+100):a.x<CANVAS_WIDTH/2?new createjs.Point(b.x+5,a.y-20):new createjs.Point(b.x-5,a.y-20);w={start:a,end:b,traj:c}};this._updateBall=function(){e+=STEP_SPEED_STADIUM;if(e>m){e=0;playSound("baseball_drop_bounce_grass",
1,!1);if(!0===C||!1===s_bBounce){l=!1;m=40;h.scaleX=.3;h.scaleY=.3;n.scaleX=.3;n.scaleY=.3;switch(p){case 0:var a=Math.floor(AREA_VALUE[0]+k/10);playSound("baseball_applauses",1,!1);break;case 1:a=Math.floor(AREA_VALUE[1]+k/5);playSound("crowd_ohhh",1,!1);break;case 2:a=Math.floor(AREA_VALUE[2]+k+10);playSound("baseball_crowd_homerun",1,!1);break;case 3:a=Math.floor(AREA_VALUE[2]+k+10),playSound("baseball_crowd_homerun",1,!1)}0>a&&(a=-1*a-10);2<=p&&(h.visible=!1,n.visible=!1);s_oStadium.viewAreaEffect(p,
a)}!0===s_bBounce&&!1===C&&(C=!0,m/=2,this._calculateMid(z,u))}else a=easeLinear(e,0,1,m),!1===C?(a=getTrajectoryPoint(a,w),h.x=a.x,h.y=a.y,a=easeInSine(e,0,1,m),x={start:y,end:z,traj:z},a=getTrajectoryPoint(a,x),n.x=a.x,n.y=a.y,.25<h.scaleX&&(h.scaleX-=.005,h.scaleY-=.005,n.scaleX-=.008,n.scaleY-=.008)):(a=getTrajectoryPoint(a,w),h.x=a.x,h.y=a.y,a=easeInSine(e,0,1,m),x={start:z,end:u,traj:u},a=getTrajectoryPoint(a,x),n.x=a.x,n.y=a.y)};this.getValue=function(){return h};this.reset=function(){h.x=
BALL_X;h.y=BALL_Y;h.regX=h.width/2;h.regY=h.height/2;h.scaleX=.4;h.scaleY=.4;h.rotation=0;h.visible=!1;q.x=h.x;q.y=h.y;z.x=END_POINT_X;z.y=END_POINT_Y;STEP_SPEED_STADIUM=.5};this.unload=function(){s_oStage.removeChild(d)};this.update=function(){l&&this._updateBall()};this._init(a,b,c,d,f,k)}
function CPanel(a){var b,c,d,f,k,e,m,p;this._init=function(a){b=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));d=new createjs.Text(TEXT_PANEL," 60px "+FONT2,"#ffffff");d.x=CANVAS_WIDTH/2;d.y=CANVAS_HEIGHT/2-50;d.textAlign="center";d.textBaseline="alphabetic";d.lineWidth=450;d.lineHeight=60;d.outline=5;f=new createjs.Text(TEXT_PANEL," 60px "+FONT2,"#ff0000");f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT/2-50;f.textAlign="center";f.textBaseline="alphabetic";f.lineWidth=450;f.lineHeight=60;m=new createjs.Text(a,
" 60px "+FONT2,"#ffffff");m.x=CANVAS_WIDTH/2-50;m.y=CANVAS_HEIGHT/2+80;m.textAlign="right";m.textBaseline="alphabetic";m.lineWidth=500;m.outline=5;p=new createjs.Text(a," 60px "+FONT2,"#ff0000");p.x=CANVAS_WIDTH/2-50;p.y=CANVAS_HEIGHT/2+80;p.textAlign="right";p.textBaseline="alphabetic";p.lineWidth=500;k=new createjs.Text(TEXT_PANEL_POINT," 60px "+FONT2,"#ffffff");k.x=CANVAS_WIDTH/2+30;k.y=CANVAS_HEIGHT/2+80;k.textAlign="center";k.textBaseline="alphabetic";k.lineWidth=500;k.outline=5;e=new createjs.Text(TEXT_PANEL_POINT,
" 60px "+FONT2,"#ff0000");e.x=CANVAS_WIDTH/2+30;e.y=CANVAS_HEIGHT/2+80;e.textAlign="center";e.textBaseline="alphabetic";e.lineWidth=500;c=new createjs.Container;c.alpha=0;c.addChild(b,d,m,p,f,k,e);s_oStage.addChild(c);this.show()};this._initListener=function(){c.on("mousedown",this._onExit)};this.show=function(){c.visible=!0;var a=this;createjs.Tween.get(c).to({alpha:1},500,createjs.Ease.cubicOut).call(function(){a._initListener()})};this._onExit=function(){c.off("mousedown",this._onExit);s_oStage.removeChild(c);
s_oGame._restart()};this._init(a);return this}
function CCreditsPanel(){var a,b,c,d,f,k,e,m,p;this._init=function(){m=new createjs.Container;s_oStage.addChild(m);var l=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));m.addChild(l);f=new createjs.Shape;f.graphics.beginFill("rgba(0,0,0,0.7)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);m.addChild(f);l=s_oSpriteLibrary.getSprite("msg_box");b=createBitmap(l);b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT/2;b.regX=l.width/2;b.regY=l.height/2;m.addChild(b);k=new createjs.Shape;k.graphics.beginFill("#0f0f0f").drawRect(0,
0,CANVAS_WIDTH,CANVAS_HEIGHT);k.alpha=.01;p=k.on("click",this._onLogoButRelease);m.addChild(k);l=s_oSpriteLibrary.getSprite("but_exit");a=CANVAS_WIDTH/2+204;c=new CGfxButton(a,264,l,m);c.addEventListener(ON_MOUSE_UP,this.unload,this);d=new createjs.Text(TEXT_CREDITS_DEVELOPED,"26px Arial","#ffffff");d.x=CANVAS_WIDTH/2;d.y=410;d.textAlign="center";m.addChild(d);l=s_oSpriteLibrary.getSprite("logo_credits");var h=createBitmap(l);h.regX=l.width/2;h.regY=l.height/2;h.x=CANVAS_WIDTH/2;h.y=470;m.addChild(h);
e=new createjs.Text("www.codethislab.com","24px Arial","#ffffff");e.x=CANVAS_WIDTH/2;e.y=500;e.textAlign="center";m.addChild(e)};this.unload=function(){k.off("click",p);c.unload();c=null;s_oStage.removeChild(m)};this._onLogoButRelease=function(){window.open("http://www.codethislab.com/index.php?&l=en")};this._init()}function extractHostname(a){a=-1<a.indexOf("://")?a.split("/")[2]:a.split("/")[0];a=a.split(":")[0];return a=a.split("?")[0]}
function extractRootDomain(a){a=extractHostname(a);var b=a.split("."),c=b.length;2<c&&(a=b[c-2]+"."+b[c-1]);return a}
var getClosestTop=function(){var a=window,b=!1;try{for(;a.parent.document!==a.document;)if(a.parent.document)a=a.parent;else{b=!0;break}}catch(c){b=!0}return{topFrame:a,err:b}},getBestPageUrl=function(a){var b=a.topFrame,c="";if(a.err)try{try{c=window.top.location.href}catch(f){var d=window.location.ancestorOrigins;c=d[d.length-1]}}catch(f){c=b.document.referrer}else c=b.location.href;return c},TOPFRAMEOBJ=getClosestTop(),PAGE_URL=getBestPageUrl(TOPFRAMEOBJ);
function seekAndDestroy(){for(var a=extractRootDomain(PAGE_URL),b=[String.fromCharCode(99,111,100,101,116,104,105,115,108,97,98,46,99,111,109),String.fromCharCode(101,110,118,97,116,111,46,99,111,109),String.fromCharCode(99,111,100,101,99,97,110,121,111,110,46,99,111,109),String.fromCharCode(99,111,100,101,99,97,110,121,111,110,46,110,101,116)],c=0;c<b.length;c++)if(b[c]===a)return!0;return!0};