/*
 screenfull
 v5.0.0 - 2019-09-09
 (c) Sindre Sorhus; MIT License
 Platform.js <https://mths.be/platform>
 Copyright 2014-2018 Benjamin Tan <https://bnjmnt4n.now.sh/>
 Copyright 2011-2013 John-David Dalton
 Available under MIT license <https://mths.be/mit>
*/
(function(){var a="undefined"!==typeof window&&"undefined"!==typeof window.document?window.document:{},g="undefined"!==typeof module&&module.exports,b=function(){for(var b,f=["requestFullscreen exitFullscreen fullscreenElement fullscreenEnabled fullscreenchange fullscreenerror".split(" "),"webkitRequestFullscreen webkitExitFullscreen webkitFullscreenElement webkitFullscreenEnabled webkitfullscreenchange webkitfullscreenerror".split(" "),"webkitRequestFullScreen webkitCancelFullScreen webkitCurrentFullScreenElement webkitCancelFullScreen webkitfullscreenchange webkitfullscreenerror".split(" "),
"mozRequestFullScreen mozCancelFullScreen mozFullScreenElement mozFullScreenEnabled mozfullscreenchange mozfullscreenerror".split(" "),"msRequestFullscreen msExitFullscreen msFullscreenElement msFullscreenEnabled MSFullscreenChange MSFullscreenError".split(" ")],d=0,e=f.length,c={};d<e;d++)if((b=f[d])&&b[1]in a){for(d=0;d<b.length;d++)c[f[0][d]]=b[d];return c}return!1}(),e={change:b.fullscreenchange,error:b.fullscreenerror},d={request:function(d){return new Promise(function(f,h){var e=function(){this.off("change",
e);f()}.bind(this);this.on("change",e);d=d||a.documentElement;Promise.resolve(d[b.requestFullscreen]())["catch"](h)}.bind(this))},exit:function(){return new Promise(function(d,f){if(this.isFullscreen){var h=function(){this.off("change",h);d()}.bind(this);this.on("change",h);Promise.resolve(a[b.exitFullscreen]())["catch"](f)}else d()}.bind(this))},toggle:function(a){return this.isFullscreen?this.exit():this.request(a)},onchange:function(a){this.on("change",a)},onerror:function(a){this.on("error",a)},
on:function(b,d){var f=e[b];f&&a.addEventListener(f,d,!1)},off:function(b,d){var f=e[b];f&&a.removeEventListener(f,d,!1)},raw:b};b?(Object.defineProperties(d,{isFullscreen:{get:function(){return!!a[b.fullscreenElement]}},element:{enumerable:!0,get:function(){return a[b.fullscreenElement]}},isEnabled:{enumerable:!0,get:function(){return!!a[b.fullscreenEnabled]}}}),g?module.exports=d:window.screenfull=d):g?module.exports={isEnabled:!1}:window.screenfull={isEnabled:!1}})();
var s_iScaleFactor=1,s_bIsIphone=!1,s_iOffsetX,s_iOffsetY;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}function isChrome(){return/Chrome/.test(navigator.userAgent)&&/Google Inc/.test(navigator.vendor)}function isIOS(){var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");for(-1!==navigator.userAgent.toLowerCase().indexOf("iphone")&&(s_bIsIphone=!0);a.length;)if(navigator.platform===a.pop())return!0;return s_bIsIphone=!1}
function getSize(a){var g=a.toLowerCase(),b=window.document,e=b.documentElement;if(void 0===window["inner"+a])a=e["client"+a];else if(window["inner"+a]!=e["client"+a]){var d=b.createElement("body");d.id="vpw-test-b";d.style.cssText="overflow:scroll";var h=b.createElement("div");h.id="vpw-test-d";h.style.cssText="position:absolute;top:-1000px";h.innerHTML="<style>@media("+g+":"+e["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+g+":7px!important}}</style>";d.appendChild(h);e.insertBefore(d,b.head);
a=7==h["offset"+a]?e["client"+a]:window["inner"+a];e.removeChild(d)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a="safari"===platform.name.toLowerCase()?getIOSWindowHeight():getSize("Height");var g=getSize("Width");_checkOrientation(g,a);var b=Math.min(a/CANVAS_HEIGHT,g/CANVAS_WIDTH),e=Math.round(CANVAS_WIDTH*b);b=Math.round(CANVAS_HEIGHT*b);if(b<a){var d=a-b;b+=d;e+=CANVAS_WIDTH/CANVAS_HEIGHT*d}else e<g&&(d=g-e,e+=d,b+=CANVAS_HEIGHT/CANVAS_WIDTH*d);d=a/2-b/2;var h=g/2-e/2,f=CANVAS_WIDTH/e;if(h*f<-EDGEBOARD_X||d*f<-EDGEBOARD_Y)b=Math.min(a/(CANVAS_HEIGHT-
2*EDGEBOARD_Y),g/(CANVAS_WIDTH-2*EDGEBOARD_X)),e=Math.round(CANVAS_WIDTH*b),b=Math.round(CANVAS_HEIGHT*b),d=(a-b)/2,h=(g-e)/2,f=CANVAS_WIDTH/e;s_iOffsetX=-1*h*f;s_iOffsetY=-1*d*f;0<=d&&(s_iOffsetY=0);0<=h&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos();null!==s_oMenu&&s_oMenu.refreshButtonPos();s_bIsIphone?(canvas=document.getElementById("canvas"),s_oStage.canvas.width=2*e,s_oStage.canvas.height=2*b,canvas.style.width=e+"px",canvas.style.height=b+"px",s_oStage.scaleX=s_oStage.scaleY=
2*Math.min(e/CANVAS_WIDTH,b/CANVAS_HEIGHT)):s_bMobile||isChrome()?($("#canvas").css("width",e+"px"),$("#canvas").css("height",b+"px")):(s_oStage.canvas.width=e,s_oStage.canvas.height=b,s_iScaleFactor=Math.min(e/CANVAS_WIDTH,b/CANVAS_HEIGHT),s_oStage.scaleX=s_oStage.scaleY=s_iScaleFactor);0>d||(d=(a-b)/2);$("#canvas").css("top",d+"px");$("#canvas").css("left",h+"px");fullscreenHandler()}}
function createBitmap(a,g,b){var e=new createjs.Bitmap(a),d=new createjs.Shape;g&&b?d.graphics.beginFill("#fff").drawRect(0,0,g,b):d.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);e.hitArea=d;return e}function createSprite(a,g,b,e,d,h){a=null!==g?new createjs.Sprite(a,g):new createjs.Sprite(a);g=new createjs.Shape;g.graphics.beginFill("#000000").drawRect(-b,-e,d,h);a.hitArea=g;return a}
function randomFloatBetween(a,g,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(a+Math.random()*(g-a),g).toFixed(b))}function formatTime(a){a/=1E3;var g=Math.floor(a/60);a=Math.floor(a-60*g);var b="";b=10>g?b+("0"+g+":"):b+(g+":");return 10>a?b+("0"+a):b+a}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(a){for(var g=a.length,b,e;0<g;)e=Math.floor(Math.random()*g),g--,b=a[g],a[g]=a[e],a[e]=b;return a}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var g=document.createEvent("MouseEvents");g.initEvent("click",!0,!0);a.dispatchEvent(g)}}};function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(a){for(var g=window.location.search.substring(1).split("&"),b=0;b<g.length;b++){var e=g[b].split("=");if(e[0]==a)return e[1]}}function playSound(a,g,b){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(s_aSounds[a].play(),s_aSounds[a].volume(g),s_aSounds[a].loop(b),s_aSounds[a]):null}function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].stop()}function setVolume(a,g){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].volume(g)}
function setMute(a,g){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].mute(g)}
function _checkOrientation(a,g){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(a>g?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),
s_oMain.stopUpdate()))}function easeLinear(a,g,b,e){return b*a/e+g}function collisionWithCircle(a,g,b){var e=a.getX()-g.getX(),d=a.getY()-g.getY();return Math.sqrt(e*e+d*d)<a.getCollision()*b+g.getCollision()*b?!0:!1}function fullscreenHandler(){ENABLE_FULLSCREEN&&!1!==screenfull.isEnabled&&(s_bFullscreen=screenfull.isFullscreen,null!==s_oInterface&&s_oInterface.resetFullscreenBut(),null!==s_oMenu&&s_oMenu.resetFullscreenBut())}
if(screenfull.isEnabled)screenfull.on("change",function(){s_bFullscreen=screenfull.isFullscreen;null!==s_oInterface&&s_oInterface.resetFullscreenBut();null!==s_oMenu&&s_oMenu.resetFullscreenBut()});
function CSpriteLibrary(){var a={},g,b,e,d,h,f;this.init=function(a,k,c){g={};e=b=0;d=a;h=k;f=c};this.addSprite=function(d,f){if(!a.hasOwnProperty(d)){var c=new Image;a[d]=g[d]={szPath:f,oSprite:c,bLoaded:!1};b++}};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){b=0;h.call(f)};this._onSpriteLoaded=function(){d.call(f);++e===b&&this._onSpritesLoaded()};this.loadSprites=function(){for(var a in g)g[a].oSprite.oSpriteLibrary=this,g[a].oSprite.szKey=
a,g[a].oSprite.onload=function(){this.oSpriteLibrary.setLoaded(this.szKey);this.oSpriteLibrary._onSpriteLoaded(this.szKey)},g[a].oSprite.onerror=function(a){var c=a.currentTarget;setTimeout(function(){g[c.szKey].oSprite.src=g[c.szKey].szPath},500)},g[a].oSprite.src=g[a].szPath};this.setLoaded=function(b){a[b].bLoaded=!0};this.isLoaded=function(b){return a[b].bLoaded};this.getNumSprites=function(){return b}}
var CANVAS_WIDTH=960,CANVAS_HEIGHT=1440,CANVAS_WIDTH_HALF=.5*CANVAS_WIDTH,CANVAS_HEIGHT_HALF=.5*CANVAS_HEIGHT,EDGEBOARD_X=50,EDGEBOARD_Y=130,FPS=30,FPS_TIME=1/FPS,DISABLE_SOUND_MOBILE=!1,PRIMARY_FONT="SHMUP in the zone",OUTLINE_TEXT=4,CELL_OFFSET={x:-9,y:-9},STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,CONFIRMATION_EXIT=0,CONFIRMATION_RESET=1,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,ON_TWEEN_ENDED=6,ON_BUT_NO_DOWN=7,ON_BUT_YES_DOWN=8,BLOCK_TIME_SPAWN_RANGE=
{min:500,max:1E4},LEFT=0,RIGHT=1,UP=2,DOWN=3,GRID_Y=20,GRID_X=10,SHOW_CELL=!1,TIME_REFRESH_DIRECTION=.2,CELL_DESTROY_MS=15,DELAY_CELL_DESTROY_MS=20,DELAY_LINE_DOWN=10,LINE_DOWN_TIME=40,SHOW_FPS=!1,TIME_REFRESH_GAME=1,TIME_REFRESH_GAME_KEY_DOWN,GRID_X_HALF=Math.floor(.5*GRID_X),CELL_SIZE=50,START_GRID_X=CANVAS_WIDTH_HALF-CELL_SIZE*GRID_X_HALF-2.35*EDGEBOARD_X,START_GRID_Y=CANVAS_HEIGHT_HALF-GRID_Y*GRID_Y,BLOCKS_TYPE=[[[0,1,0],[1,1,1]],[[0,0,1],[1,1,1]],[[1,0,0],[1,1,1]],[[0,1,1],[1,1,0]],[[1,1,0],
[0,1,1]],[[1],[1],[1],[1]],[[1,1],[1,1]]],ENABLE_FULLSCREEN,ENABLE_CHECK_ORIENTATION,SOUNDTRACK_VOLUME_IN_GAME=.4;
(function(){function a(a){a=String(a);return a.charAt(0).toUpperCase()+a.slice(1)}function g(a,c){var b=-1,d=a?a.length:0;if("number"==typeof d&&-1<d&&d<=w)for(;++b<d;)c(a[b],b,a);else e(a,c)}function b(c){c=String(c).replace(/^ +| +$/g,"");return/^(?:webOS|i(?:OS|P))/.test(c)?c:a(c)}function e(a,c){for(var b in a)v.call(a,b)&&c(a[b],b,a)}function d(c){return null==c?a(c):B.call(c).slice(8,-1)}function h(a,c){var b=null!=a?typeof a[c]:"number";return!/^(?:boolean|number|string|undefined)$/.test(b)&&
("object"==b?!!a[c]:!0)}function f(a){return String(a).replace(/([ -])(?!$)/g,"$1?")}function m(a,c){var b=null;g(a,function(d,f){b=c(b,d,f,a)});return b}function k(a){function c(c){return m(c,function(c,d){var e=d.pattern||f(d);!c&&(c=RegExp("\\b"+e+" *\\d+[.\\w_]*","i").exec(a)||RegExp("\\b"+e+" *\\w+-[\\w]*","i").exec(a)||RegExp("\\b"+e+"(?:; *(?:[a-z]+[_-])?[a-z]+\\d+|[^ ();-]*)","i").exec(a))&&((c=String(d.label&&!RegExp(e,"i").test(d.label)?d.label:c).split("/"))[1]&&!/[\d.]+/.test(c[0])&&(c[0]+=
" "+c[1]),d=d.label||d,c=b(c[0].replace(RegExp(e,"i"),d).replace(RegExp("; *(?:"+d+"[_-])?","i")," ").replace(RegExp("("+d+")[-_.]?(\\w)","i"),"$1 $2")));return c})}function g(c){return m(c,function(c,b){return c||(RegExp(b+"(?:-[\\d.]+/|(?: for [\\w-]+)?[ /-])([\\d.]+[^ ();/_-]*)","i").exec(a)||0)[1]||null})}var p=q,n=a&&"object"==typeof a&&"String"!=d(a);n&&(p=a,a=null);var w=p.navigator||{},u=w.userAgent||"";a||(a=u);var v=n?!!w.likeChrome:/\bChrome\b/.test(a)&&!/internal|\n/i.test(B.toString()),
A=n?"Object":"ScriptBridgingProxyObject",E=n?"Object":"Environment",M=n&&p.java?"JavaPackage":d(p.java),C=n?"Object":"RuntimeObject";E=(M=/\bJava/.test(M)&&p.java)&&d(p.environment)==E;var V=M?"a":"\u03b1",W=M?"b":"\u03b2",S=p.document||{},K=p.operamini||p.opera,P=x.test(P=n&&K?K["[[Class]]"]:d(K))?P:K=null,l,Q=a;n=[];var R=null,L=a==u;u=L&&K&&"function"==typeof K.version&&K.version();var y=function(c){return m(c,function(c,b){return c||RegExp("\\b"+(b.pattern||f(b))+"\\b","i").exec(a)&&(b.label||
b)})}([{label:"EdgeHTML",pattern:"Edge"},"Trident",{label:"WebKit",pattern:"AppleWebKit"},"iCab","Presto","NetFront","Tasman","KHTML","Gecko"]),r=function(c){return m(c,function(c,b){return c||RegExp("\\b"+(b.pattern||f(b))+"\\b","i").exec(a)&&(b.label||b)})}(["Adobe AIR","Arora","Avant Browser","Breach","Camino","Electron","Epiphany","Fennec","Flock","Galeon","GreenBrowser","iCab","Iceweasel","K-Meleon","Konqueror","Lunascape","Maxthon",{label:"Microsoft Edge",pattern:"Edge"},"Midori","Nook Browser",
"PaleMoon","PhantomJS","Raven","Rekonq","RockMelt",{label:"Samsung Internet",pattern:"SamsungBrowser"},"SeaMonkey",{label:"Silk",pattern:"(?:Cloud9|Silk-Accelerated)"},"Sleipnir","SlimBrowser",{label:"SRWare Iron",pattern:"Iron"},"Sunrise","Swiftfox","Waterfox","WebPositive","Opera Mini",{label:"Opera Mini",pattern:"OPiOS"},"Opera",{label:"Opera",pattern:"OPR"},"Chrome",{label:"Chrome Mobile",pattern:"(?:CriOS|CrMo)"},{label:"Firefox",pattern:"(?:Firefox|Minefield)"},{label:"Firefox for iOS",pattern:"FxiOS"},
{label:"IE",pattern:"IEMobile"},{label:"IE",pattern:"MSIE"},"Safari"]),z=c([{label:"BlackBerry",pattern:"BB10"},"BlackBerry",{label:"Galaxy S",pattern:"GT-I9000"},{label:"Galaxy S2",pattern:"GT-I9100"},{label:"Galaxy S3",pattern:"GT-I9300"},{label:"Galaxy S4",pattern:"GT-I9500"},{label:"Galaxy S5",pattern:"SM-G900"},{label:"Galaxy S6",pattern:"SM-G920"},{label:"Galaxy S6 Edge",pattern:"SM-G925"},{label:"Galaxy S7",pattern:"SM-G930"},{label:"Galaxy S7 Edge",pattern:"SM-G935"},"Google TV","Lumia","iPad",
"iPod","iPhone","Kindle",{label:"Kindle Fire",pattern:"(?:Cloud9|Silk-Accelerated)"},"Nexus","Nook","PlayBook","PlayStation Vita","PlayStation","TouchPad","Transformer",{label:"Wii U",pattern:"WiiU"},"Wii","Xbox One",{label:"Xbox 360",pattern:"Xbox"},"Xoom"]),H=function(c){return m(c,function(c,b,d){return c||(b[z]||b[/^[a-z]+(?: +[a-z]+\b)*/i.exec(z)]||RegExp("\\b"+f(d)+"(?:\\b|\\w*\\d)","i").exec(a))&&d})}({Apple:{iPad:1,iPhone:1,iPod:1},Archos:{},Amazon:{Kindle:1,"Kindle Fire":1},Asus:{Transformer:1},
"Barnes & Noble":{Nook:1},BlackBerry:{PlayBook:1},Google:{"Google TV":1,Nexus:1},HP:{TouchPad:1},HTC:{},LG:{},Microsoft:{Xbox:1,"Xbox One":1},Motorola:{Xoom:1},Nintendo:{"Wii U":1,Wii:1},Nokia:{Lumia:1},Samsung:{"Galaxy S":1,"Galaxy S2":1,"Galaxy S3":1,"Galaxy S4":1},Sony:{PlayStation:1,"PlayStation Vita":1}}),t=function(c){return m(c,function(c,d){var e=d.pattern||f(d);if(!c&&(c=RegExp("\\b"+e+"(?:/[\\d.]+|[ \\w.]*)","i").exec(a))){var h=c,p=d.label||d,k={"10.0":"10","6.4":"10 Technical Preview",
"6.3":"8.1","6.2":"8","6.1":"Server 2008 R2 / 7","6.0":"Server 2008 / Vista","5.2":"Server 2003 / XP 64-bit","5.1":"XP","5.01":"2000 SP1","5.0":"2000","4.0":"NT","4.90":"ME"};e&&p&&/^Win/i.test(h)&&!/^Windows Phone /i.test(h)&&(k=k[/[\d.]+$/.exec(h)])&&(h="Windows "+k);h=String(h);e&&p&&(h=h.replace(RegExp(e,"i"),p));c=h=b(h.replace(/ ce$/i," CE").replace(/\bhpw/i,"web").replace(/\bMacintosh\b/,"Mac OS").replace(/_PowerPC\b/i," OS").replace(/\b(OS X) [^ \d]+/i,"$1").replace(/\bMac (OS X)\b/,"$1").replace(/\/(\d)/,
" $1").replace(/_/g,".").replace(/(?: BePC|[ .]*fc[ \d.]+)$/i,"").replace(/\bx86\.64\b/gi,"x86_64").replace(/\b(Windows Phone) OS\b/,"$1").replace(/\b(Chrome OS \w+) [\d.]+\b/,"$1").split(" on ")[0])}return c})}(["Windows Phone","Android","CentOS",{label:"Chrome OS",pattern:"CrOS"},"Debian","Fedora","FreeBSD","Gentoo","Haiku","Kubuntu","Linux Mint","OpenBSD","Red Hat","SuSE","Ubuntu","Xubuntu","Cygwin","Symbian OS","hpwOS","webOS ","webOS","Tablet OS","Tizen","Linux","Mac OS X","Macintosh","Mac",
"Windows 98;","Windows "]);y&&(y=[y]);H&&!z&&(z=c([H]));if(l=/\bGoogle TV\b/.exec(z))z=l[0];/\bSimulator\b/i.test(a)&&(z=(z?z+" ":"")+"Simulator");"Opera Mini"==r&&/\bOPiOS\b/.test(a)&&n.push("running in Turbo/Uncompressed mode");"IE"==r&&/\blike iPhone OS\b/.test(a)?(l=k(a.replace(/like iPhone OS/,"")),H=l.manufacturer,z=l.product):/^iP/.test(z)?(r||(r="Safari"),t="iOS"+((l=/ OS ([\d_]+)/i.exec(a))?" "+l[1].replace(/_/g,"."):"")):"Konqueror"!=r||/buntu/i.test(t)?H&&"Google"!=H&&(/Chrome/.test(r)&&
!/\bMobile Safari\b/i.test(a)||/\bVita\b/.test(z))||/\bAndroid\b/.test(t)&&/^Chrome/.test(r)&&/\bVersion\//i.test(a)?(r="Android Browser",t=/\bAndroid\b/.test(t)?t:"Android"):"Silk"==r?(/\bMobi/i.test(a)||(t="Android",n.unshift("desktop mode")),/Accelerated *= *true/i.test(a)&&n.unshift("accelerated")):"PaleMoon"==r&&(l=/\bFirefox\/([\d.]+)\b/.exec(a))?n.push("identifying as Firefox "+l[1]):"Firefox"==r&&(l=/\b(Mobile|Tablet|TV)\b/i.exec(a))?(t||(t="Firefox OS"),z||(z=l[1])):!r||(l=!/\bMinefield\b/i.test(a)&&
/\b(?:Firefox|Safari)\b/.exec(r))?(r&&!z&&/[\/,]|^[^(]+?\)/.test(a.slice(a.indexOf(l+"/")+8))&&(r=null),(l=z||H||t)&&(z||H||/\b(?:Android|Symbian OS|Tablet OS|webOS)\b/.test(t))&&(r=/[a-z]+(?: Hat)?/i.exec(/\bAndroid\b/.test(t)?t:l)+" Browser")):"Electron"==r&&(l=(/\bChrome\/([\d.]+)\b/.exec(a)||0)[1])&&n.push("Chromium "+l):t="Kubuntu";u||(u=g(["(?:Cloud9|CriOS|CrMo|Edge|FxiOS|IEMobile|Iron|Opera ?Mini|OPiOS|OPR|Raven|SamsungBrowser|Silk(?!/[\\d.]+$))","Version",f(r),"(?:Firefox|Minefield|NetFront)"]));
if(l="iCab"==y&&3<parseFloat(u)&&"WebKit"||/\bOpera\b/.test(r)&&(/\bOPR\b/.test(a)?"Blink":"Presto")||/\b(?:Midori|Nook|Safari)\b/i.test(a)&&!/^(?:Trident|EdgeHTML)$/.test(y)&&"WebKit"||!y&&/\bMSIE\b/i.test(a)&&("Mac OS"==t?"Tasman":"Trident")||"WebKit"==y&&/\bPlayStation\b(?! Vita\b)/i.test(r)&&"NetFront")y=[l];"IE"==r&&(l=(/; *(?:XBLWP|ZuneWP)(\d+)/i.exec(a)||0)[1])?(r+=" Mobile",t="Windows Phone "+(/\+$/.test(l)?l:l+".x"),n.unshift("desktop mode")):/\bWPDesktop\b/i.test(a)?(r="IE Mobile",t="Windows Phone 8.x",
n.unshift("desktop mode"),u||(u=(/\brv:([\d.]+)/.exec(a)||0)[1])):"IE"!=r&&"Trident"==y&&(l=/\brv:([\d.]+)/.exec(a))&&(r&&n.push("identifying as "+r+(u?" "+u:"")),r="IE",u=l[1]);if(L){if(h(p,"global"))if(M&&(l=M.lang.System,Q=l.getProperty("os.arch"),t=t||l.getProperty("os.name")+" "+l.getProperty("os.version")),E){try{u=p.require("ringo/engine").version.join("."),r="RingoJS"}catch(U){(l=p.system)&&l.global.system==p.system&&(r="Narwhal",t||(t=l[0].os||null))}r||(r="Rhino")}else"object"==typeof p.process&&
!p.process.browser&&(l=p.process)&&("object"==typeof l.versions&&("string"==typeof l.versions.electron?(n.push("Node "+l.versions.node),r="Electron",u=l.versions.electron):"string"==typeof l.versions.nw&&(n.push("Chromium "+u,"Node "+l.versions.node),r="NW.js",u=l.versions.nw)),r||(r="Node.js",Q=l.arch,t=l.platform,u=(u=/[\d.]+/.exec(l.version))?u[0]:null));else d(l=p.runtime)==A?(r="Adobe AIR",t=l.flash.system.Capabilities.os):d(l=p.phantom)==C?(r="PhantomJS",u=(l=l.version||null)&&l.major+"."+l.minor+
"."+l.patch):"number"==typeof S.documentMode&&(l=/\bTrident\/(\d+)/i.exec(a))?(u=[u,S.documentMode],(l=+l[1]+4)!=u[1]&&(n.push("IE "+u[1]+" mode"),y&&(y[1]=""),u[1]=l),u="IE"==r?String(u[1].toFixed(1)):u[0]):"number"==typeof S.documentMode&&/^(?:Chrome|Firefox)\b/.test(r)&&(n.push("masking as "+r+" "+u),r="IE",u="11.0",y=["Trident"],t="Windows");t=t&&b(t)}u&&(l=/(?:[ab]|dp|pre|[ab]\d+pre)(?:\d+\+?)?$/i.exec(u)||/(?:alpha|beta)(?: ?\d)?/i.exec(a+";"+(L&&w.appMinorVersion))||/\bMinefield\b/i.test(a)&&
"a")&&(R=/b/i.test(l)?"beta":"alpha",u=u.replace(RegExp(l+"\\+?$"),"")+("beta"==R?W:V)+(/\d+\+?/.exec(l)||""));if("Fennec"==r||"Firefox"==r&&/\b(?:Android|Firefox OS)\b/.test(t))r="Firefox Mobile";else if("Maxthon"==r&&u)u=u.replace(/\.[\d.]+/,".x");else if(/\bXbox\b/i.test(z))"Xbox 360"==z&&(t=null),"Xbox 360"==z&&/\bIEMobile\b/.test(a)&&n.unshift("mobile mode");else if(!/^(?:Chrome|IE|Opera)$/.test(r)&&(!r||z||/Browser|Mobi/.test(r))||"Windows CE"!=t&&!/Mobi/i.test(a))if("IE"==r&&L)try{null===p.external&&
n.unshift("platform preview")}catch(U){n.unshift("embedded")}else(/\bBlackBerry\b/.test(z)||/\bBB10\b/.test(a))&&(l=(RegExp(z.replace(/ +/g," *")+"/([.\\d]+)","i").exec(a)||0)[1]||u)?(l=[l,/BB10/.test(a)],t=(l[1]?(z=null,H="BlackBerry"):"Device Software")+" "+l[0],u=null):this!=e&&"Wii"!=z&&(L&&K||/Opera/.test(r)&&/\b(?:MSIE|Firefox)\b/i.test(a)||"Firefox"==r&&/\bOS X (?:\d+\.){2,}/.test(t)||"IE"==r&&(t&&!/^Win/.test(t)&&5.5<u||/\bWindows XP\b/.test(t)&&8<u||8==u&&!/\bTrident\b/.test(a)))&&!x.test(l=
k.call(e,a.replace(x,"")+";"))&&l.name&&(l="ing as "+l.name+((l=l.version)?" "+l:""),x.test(r)?(/\bIE\b/.test(l)&&"Mac OS"==t&&(t=null),l="identify"+l):(l="mask"+l,r=P?b(P.replace(/([a-z])([A-Z])/g,"$1 $2")):"Opera",/\bIE\b/.test(l)&&(t=null),L||(u=null)),y=["Presto"],n.push(l));else r+=" Mobile";if(l=(/\bAppleWebKit\/([\d.]+\+?)/i.exec(a)||0)[1]){l=[parseFloat(l.replace(/\.(\d)$/,".0$1")),l];if("Safari"==r&&"+"==l[1].slice(-1))r="WebKit Nightly",R="alpha",u=l[1].slice(0,-1);else if(u==l[1]||u==(l[2]=
(/\bSafari\/([\d.]+\+?)/i.exec(a)||0)[1]))u=null;l[1]=(/\bChrome\/([\d.]+)/i.exec(a)||0)[1];537.36==l[0]&&537.36==l[2]&&28<=parseFloat(l[1])&&"WebKit"==y&&(y=["Blink"]);L&&(v||l[1])?(y&&(y[1]="like Chrome"),l=l[1]||(l=l[0],530>l?1:532>l?2:532.05>l?3:533>l?4:534.03>l?5:534.07>l?6:534.1>l?7:534.13>l?8:534.16>l?9:534.24>l?10:534.3>l?11:535.01>l?12:535.02>l?"13+":535.07>l?15:535.11>l?16:535.19>l?17:536.05>l?18:536.1>l?19:537.01>l?20:537.11>l?"21+":537.13>l?23:537.18>l?24:537.24>l?25:537.36>l?26:"Blink"!=
y?"27":"28")):(y&&(y[1]="like Safari"),l=(l=l[0],400>l?1:500>l?2:526>l?3:533>l?4:534>l?"4+":535>l?5:537>l?6:538>l?7:601>l?8:"8"));y&&(y[1]+=" "+(l+="number"==typeof l?".x":/[.+]/.test(l)?"":"+"));"Safari"==r&&(!u||45<parseInt(u))&&(u=l)}"Opera"==r&&(l=/\bzbov|zvav$/.exec(t))?(r+=" ",n.unshift("desktop mode"),"zvav"==l?(r+="Mini",u=null):r+="Mobile",t=t.replace(RegExp(" *"+l+"$"),"")):"Safari"==r&&/\bChrome\b/.exec(y&&y[1])&&(n.unshift("desktop mode"),r="Chrome Mobile",u=null,/\bOS X\b/.test(t)?(H=
"Apple",t="iOS 4.3+"):t=null);u&&0==u.indexOf(l=/[\d.]+$/.exec(t))&&-1<a.indexOf("/"+l+"-")&&(t=String(t.replace(l,"")).replace(/^ +| +$/g,""));y&&!/\b(?:Avant|Nook)\b/.test(r)&&(/Browser|Lunascape|Maxthon/.test(r)||"Safari"!=r&&/^iOS/.test(t)&&/\bSafari\b/.test(y[1])||/^(?:Adobe|Arora|Breach|Midori|Opera|Phantom|Rekonq|Rock|Samsung Internet|Sleipnir|Web)/.test(r)&&y[1])&&(l=y[y.length-1])&&n.push(l);n.length&&(n=["("+n.join("; ")+")"]);H&&z&&0>z.indexOf(H)&&n.push("on "+H);z&&n.push((/^on /.test(n[n.length-
1])?"":"on ")+z);if(t){var T=(l=/ ([\d.+]+)$/.exec(t))&&"/"==t.charAt(t.length-l[0].length-1);t={architecture:32,family:l&&!T?t.replace(l[0],""):t,version:l?l[1]:null,toString:function(){var a=this.version;return this.family+(a&&!T?" "+a:"")+(64==this.architecture?" 64-bit":"")}}}(l=/\b(?:AMD|IA|Win|WOW|x86_|x)64\b/i.exec(Q))&&!/\bi686\b/i.test(Q)?(t&&(t.architecture=64,t.family=t.family.replace(RegExp(" *"+l),"")),r&&(/\bWOW64\b/i.test(a)||L&&/\w(?:86|32)$/.test(w.cpuClass||w.platform)&&!/\bWin64; x64\b/i.test(a))&&
n.unshift("32-bit")):t&&/^OS X/.test(t.family)&&"Chrome"==r&&39<=parseFloat(u)&&(t.architecture=64);a||(a=null);p={};p.description=a;p.layout=y&&y[0];p.manufacturer=H;p.name=r;p.prerelease=R;p.product=z;p.ua=a;p.version=r&&u;p.os=t||{architecture:null,family:null,version:null,toString:function(){return"null"}};p.parse=k;p.toString=function(){return this.description||""};p.version&&n.unshift(u);p.name&&n.unshift(r);t&&r&&(t!=String(t).split(" ")[0]||t!=r.split(" ")[0]&&!z)&&n.push(z?"("+t+")":"on "+
t);n.length&&(p.description=n.join(" "));return p}var c={"function":!0,object:!0},q=c[typeof window]&&window||this,n=c[typeof exports]&&exports;c=c[typeof module]&&module&&!module.nodeType&&module;var p=n&&c&&"object"==typeof global&&global;!p||p.global!==p&&p.window!==p&&p.self!==p||(q=p);var w=Math.pow(2,53)-1,x=/\bOpera/;p=Object.prototype;var v=p.hasOwnProperty,B=p.toString,A=k();"function"==typeof define&&"object"==typeof define.amd&&define.amd?(q.platform=A,define(function(){return A})):n&&
c?e(A,function(a,c){n[c]=a}):q.platform=A}).call(this);TEXT_SCORE="SCORE";TEXT_SCORE_CASE="Score";TEXT_SCORE_GAMEOVER="TOTAL SCORE";TEXT_LEVEL_UPPERCASE=TEXT_LEVEL="LEVEL";TEXT_GAMEOVER="GAME OVER";TEXT_GAME_COMPLETED="GAME COMPLETED";TEXT_HOW_TO_PLAY="HOW TO PLAY";TEXT_HELP_ENEMY="Escape from him";TEXT_SELECT_A_LEVEL="SELECT A LEVEL";TEXT_PAUSE="Pause";TEXT_HELP_TNT="Touch this to trigger an explosion";TEXT_FINAL_SCORE="FINAL SCORE";TEXT_ARE_SURE="ARE YOU SURE?";TEXT_CREDITS_DEVELOPED="DEVELOPED BY";
TEXT_LINK1="WWW.CODETHISLAB.COM";TEXT_RESET="ARE YOU SURE? ALL YOUR PREVIOUS SCORES WILL BE DELETED!";TEXT_NEXT="NEXT";TEXT_LINES="LINES";var TEXT_PRELOADER_CONTINUE="START";TEXT_SHARE_IMAGE="200x200.jpg";TEXT_SHARE_TITLE="Congratulations!";TEXT_SHARE_MSG1="You collected <strong>";TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";TEXT_SHARE_SHARE1="My score is ";TEXT_SHARE_SHARE2=" points! Can you do better";
function CPreloader(){var a,g,b,e,d,h,f,m,k,c;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.addSprite("200x200","./sprites/200x200.jpg");s_oSpriteLibrary.addSprite("but_start","./sprites/but_start.png");s_oSpriteLibrary.loadSprites();c=new createjs.Container;s_oStage.addChild(c)};this.unload=function(){c.removeAllChildren()};this._onImagesLoaded=function(){};this._onAllImagesLoaded=
function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var q=new createjs.Shape;q.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);c.addChild(q);q=s_oSpriteLibrary.getSprite("200x200");f=createBitmap(q);f.regX=.5*q.width;f.regY=.5*q.height;f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT/2-80;c.addChild(f);m=new createjs.Shape;m.graphics.beginFill("rgba(0,0,0,0.01)").drawRoundRect(f.x-100,f.y-100,200,200,10);c.addChild(m);f.mask=m;q=s_oSpriteLibrary.getSprite("progress_bar");
e=createBitmap(q);e.x=CANVAS_WIDTH/2-q.width/2;e.y=CANVAS_HEIGHT/2+70;c.addChild(e);a=q.width;g=q.height;d=new createjs.Shape;d.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(e.x,e.y,1,g);c.addChild(d);e.mask=d;b=new createjs.Text("","30px "+PRIMARY_FONT,"#fff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT/2+120;b.textBaseline="alphabetic";b.textAlign="center";c.addChild(b);q=s_oSpriteLibrary.getSprite("but_start");k=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2+100,q,TEXT_PRELOADER_CONTINUE,"Arial","#000",
36,c);k.addEventListener(ON_MOUSE_UP,this._onButStartRelease,this);k.setVisible(!1);h=new createjs.Shape;h.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);c.addChild(h);createjs.Tween.get(h).to({alpha:0},500).call(function(){createjs.Tween.removeTweens(h);c.removeChild(h)})};this._onButStartRelease=function(){s_oMain._onRemovePreloader()};this.refreshLoader=function(c){b.text=c+"%";100===c&&(s_oMain._onRemovePreloader(),b.visible=!1,e.visible=!1);d.graphics.clear();c=Math.floor(c*
a/100);d.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(e.x,e.y,c,g)};this._init()}
function CMain(a){var g,b=0,e=0,d=STATE_LOADING,h,f;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);s_oStage.preventSelection=!1;createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(30);navigator.userAgent.match(/Windows Phone/i)&&
(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;seekAndDestroy()?h=new CPreloader:window.location.href="http://www.codethislab.com/contact-us.html"};this.preloaderReady=function(){this._loadImages();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();g=!0};this.soundLoaded=function(){b++;h.refreshLoader(Math.floor(b/e*100))};this._initSounds=function(){Howler.mute(!s_bAudioActive);s_aSoundsInfo=[];s_aSoundsInfo.push({path:"./sounds/",filename:"delete_lines",loop:!1,volume:1,
ingamename:"delete_lines"});s_aSoundsInfo.push({path:"./sounds/",filename:"click",loop:!1,volume:1,ingamename:"click"});s_aSoundsInfo.push({path:"./sounds/",filename:"game_over",loop:!1,volume:1,ingamename:"game_over"});s_aSoundsInfo.push({path:"./sounds/",filename:"shift_piece",loop:!1,volume:1,ingamename:"shift_piece"});s_aSoundsInfo.push({path:"./sounds/",filename:"soundtrack",loop:!0,volume:1,ingamename:"soundtrack"});e+=s_aSoundsInfo.length;s_aSounds=[];for(var a=0;a<s_aSoundsInfo.length;a++)this.tryToLoadSound(s_aSoundsInfo[a],
!1)};this.tryToLoadSound=function(a,c){setTimeout(function(){s_aSounds[a.ingamename]=new Howl({src:[a.path+a.filename+".mp3"],autoplay:!1,preload:!0,loop:a.loop,volume:a.volume,onload:s_oMain.soundLoaded,onloaderror:function(a,c){for(var b=0;b<s_aSoundsInfo.length;b++)if(a===s_aSounds[s_aSoundsInfo[b].ingamename]._sounds[0]._id){s_oMain.tryToLoadSound(s_aSoundsInfo[b],!0);break}},onplayerror:function(a){for(var c=0;c<s_aSoundsInfo.length;c++)if(a===s_aSounds[s_aSoundsInfo[c].ingamename]._sounds[0]._id){s_aSounds[s_aSoundsInfo[c].ingamename].once("unlock",
function(){s_aSounds[s_aSoundsInfo[c].ingamename].play();"soundtrack"===s_aSoundsInfo[c].ingamename&&null!==s_oGame&&setVolume("soundtrack",SOUNDTRACK_VOLUME_IN_GAME)});break}}})},c?200:0)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("but_pause",
"./sprites/but_pause.png");s_oSpriteLibrary.addSprite("icon_audio","./sprites/icon_audio.png");s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("but_restart","./sprites/but_restart.png");s_oSpriteLibrary.addSprite("but_continue","./sprites/but_continue.png");s_oSpriteLibrary.addSprite("but_home","./sprites/but_home.png");s_oSpriteLibrary.addSprite("but_not","./sprites/but_not.png");s_oSpriteLibrary.addSprite("but_rotation","./sprites/but_rotation.png");s_oSpriteLibrary.addSprite("small_logo",
"./sprites/small_logo.png");s_oSpriteLibrary.addSprite("block_blur","./sprites/block_blur.png");s_oSpriteLibrary.addSprite("block_rotation","./sprites/block_rotation.png");s_oSpriteLibrary.addSprite("block_down","./sprites/block_down.png");s_oSpriteLibrary.addSprite("logo_ctl","./sprites/logo_ctl.png");s_oSpriteLibrary.addSprite("pause_text","./sprites/pause_text.png");s_oSpriteLibrary.addSprite("cell","./sprites/cell.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("but_yes",
"./sprites/but_yes.png");s_oSpriteLibrary.addSprite("but_info","./sprites/but_info.png");s_oSpriteLibrary.addSprite("arrow","./sprites/arrow.png");s_oSpriteLibrary.addSprite("next_board","./sprites/next_board.png");s_oSpriteLibrary.addSprite("info_board","./sprites/info_board.png");s_oSpriteLibrary.addSprite("score_board","./sprites/score_board.png");s_oSpriteLibrary.addSprite("frame_top","./sprites/frame_top.png");s_oSpriteLibrary.addSprite("frame_bottom","./sprites/frame_bottom.png");s_oSpriteLibrary.addSprite("key_down",
"./sprites/key_down.png");s_oSpriteLibrary.addSprite("key_up","./sprites/key_up.png");s_oSpriteLibrary.addSprite("key_right","./sprites/key_right.png");s_oSpriteLibrary.addSprite("key_left","./sprites/key_left.png");s_oSpriteLibrary.addSprite("logo_menu","./sprites/logo_menu.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");for(var a=0;a<BLOCKS_TYPE.length;a++)s_oSpriteLibrary.addSprite("cell_"+a,"./sprites/cell_"+a+".png");e+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};
this._onImagesLoaded=function(){b++;h.refreshLoader(Math.floor(b/e*100))};this._onAllImagesLoaded=function(){};this._onRemovePreloader=function(){h.unload();s_oSoundTrack=playSound("soundtrack",1,!0);s_oMain.gotoMenu()};this.gotoMenu=function(){new CMenu;d=STATE_MENU};this.gotoGame=function(){f=new CGame(m);d=STATE_GAME;$(s_oMain).trigger("start_session")};this.stopUpdate=function(){g=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||Howler.mute(!0)};
this.startUpdate=function(){s_iPrevTime=(new Date).getTime();g=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none");(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)&&s_bAudioActive&&Howler.mute(!1)};this._update=function(a){if(!1!==g){var c=(new Date).getTime();s_iTimeElaps=c-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=c;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);d===STATE_GAME&&f.update();s_oStage.update(a)}};s_oMain=this;var m=a;ENABLE_FULLSCREEN=
a.fullscreen;ENABLE_CHECK_ORIENTATION=a.check_orientation;s_bAudioActive=a.audio_enable_on_startup;this.initContainer()}var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_iAdsLevel=1,s_iLevelReached=1,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundTrack=null,s_oCanvas,s_aSounds,s_bFullscreen=!1,s_aSoundsInfo;
function CTextButton(a,g,b,e,d,h,f){var m,k,c,q,n;this._init=function(a,b,d,f,e,h,g){m=[];k=[];e=createBitmap(d);var p=Math.ceil(g/20);n=new createjs.Text(f,g+"px "+PRIMARY_FONT,"#fff");n.textAlign="center";n.textBaseline="alphabetic";var w=n.getBounds();n.x=d.width/2+p;n.y=Math.floor(d.height/2)+w.height/3+p;q=new createjs.Text(f,g+"px "+PRIMARY_FONT,h);q.textAlign="center";q.textBaseline="alphabetic";w=q.getBounds();q.x=d.width/2;q.y=Math.floor(d.height/2)+w.height/3;c=new createjs.Container;c.x=
a;c.y=b;c.regX=d.width/2;c.regY=d.height/2;c.addChild(e,n,q);s_oStage.addChild(c);s_bMobile||(c.cursor="pointer");this._initListener()};this.unload=function(){c.off("mousedown");c.off("pressup");s_oStage.removeChild(c)};this.setVisible=function(a){c.visible=a};this._initListener=function(){oParent=this;c.on("mousedown",this.buttonDown);c.on("pressup",this.buttonRelease)};this.addEventListener=function(a,c,b){m[a]=c;k[a]=b};this.buttonRelease=function(){c.scaleX=1;c.scaleY=1;playSound("click",1,!1);
m[ON_MOUSE_UP]&&m[ON_MOUSE_UP].call(k[ON_MOUSE_UP])};this.buttonDown=function(){c.scaleX=.9;c.scaleY=.9;m[ON_MOUSE_DOWN]&&m[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN])};this.setTextPosition=function(a){q.y=a;n.y=a+2};this.setPosition=function(a,b){c.x=a;c.y=b};this.setX=function(a){c.x=a};this.setY=function(a){c.y=a};this.getButtonImage=function(){return c};this.getX=function(){return c.x};this.getY=function(){return c.y};this._init(a,g,b,e,d,h,f);return this}
function CToggle(a,g,b,e,d){var h,f,m,k=[],c;this._init=function(a,b,d,e){f=[];m=[];var g=new createjs.SpriteSheet({images:[d],frames:{width:d.width/2,height:d.height,regX:d.width/2/2,regY:d.height/2},animations:{state_true:[0],state_false:[1]}});h=e;c=createSprite(g,"state_"+h,d.width/2/2,d.height/2,d.width/2,d.height);c.mouseEnabled=!0;c.x=a;c.y=b;c.stop();s_bMobile||(c.cursor="pointer");q.addChild(c);this._initListener()};this.unload=function(){c.off("mousedown",this.buttonDown);c.off("pressup",
this.buttonRelease);c.mouseEnabled=!1;q.removeChild(c)};this._initListener=function(){c.on("mousedown",this.buttonDown);c.on("pressup",this.buttonRelease)};this.addEventListener=function(a,c,b){f[a]=c;m[a]=b};this.addEventListenerWithParams=function(a,c,b,d){f[a]=c;m[a]=b;k=d};this.setActive=function(a){h=a;c.gotoAndStop("state_"+h)};this.buttonRelease=function(){c.scaleX=1;c.scaleY=1;playSound("click",1,!1);h=!h;c.gotoAndStop("state_"+h);f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(m[ON_MOUSE_UP],k)};this.buttonDown=
function(){c.scaleX=.9;c.scaleY=.9;f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(m[ON_MOUSE_DOWN],k)};this.setPosition=function(a,b){c.x=a;c.y=b};this.setVisible=function(a){c.visible=a};var q=d;this._init(a,g,b,e)}
function CNumToggle(a,g,b,e){var d,h,f,m,k,c,q,n=[];this._init=function(a,b,e,g){h=!1;f=[];m=[];k=new createjs.Container;k.x=a;k.y=b;g.addChild(k);a=s_oSpriteLibrary.getSprite("num_button");b={images:[a],framerate:5,frames:{width:a.width/2,height:a.height,regX:a.width/2/2,regY:a.height/2},animations:{state_true:[0],state_false:[1]}};b=new createjs.SpriteSheet(b);d=!1;c=createSprite(b,"state_"+d,a.width/2/2,a.height/2,a.width/2,a.height);c.stop();a=s_oSpriteLibrary.getSprite("ball");b={images:[a],
frames:{width:a.width/NUM_DIFFERENT_BALLS,height:a.height,regX:a.width/NUM_DIFFERENT_BALLS/2,regY:a.height/2},animations:{red:[0],green:[1],cyan:[0],violet:[1],blue:[1]}};b=new createjs.SpriteSheet(b);q=createSprite(b,"red",a.width/NUM_DIFFERENT_BALLS/2,a.height/2,a.width/NUM_DIFFERENT_BALLS,a.height);q.gotoAndStop(0);q.visible=!1;k.addChild(c,q);this._initListener()};this.unload=function(){k.off("mousedown",this.buttonDown);k.off("pressup",this.buttonRelease);e.removeChild(k)};this._initListener=
function(){k.on("mousedown",this.buttonDown);k.on("pressup",this.buttonRelease)};this.addEventListener=function(a,c,b){f[a]=c;m[a]=b};this.addEventListenerWithParams=function(a,c,b,d){f[a]=c;m[a]=b;n=d};this.setActive=function(a){d=a;c.gotoAndStop("state_"+d)};this.buttonRelease=function(){h||(playSound("click",1,!1),d=!d,c.gotoAndStop("state_"+d),f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(m[ON_MOUSE_UP],n))};this.buttonDown=function(){h||f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(m[ON_MOUSE_DOWN],n)};this.setPosition=
function(a,c){k.x=a;k.y=c};this.getGlobalPosition=function(){return{x:k.localToGlobal(0,0).x,y:k.localToGlobal(0,0).y}};this.block=function(a){h=a};this.setExtracted=function(a,c){q.visible=a;q.gotoAndStop(c)};this.highlight=function(){c.gotoAndPlay(0)};this.stopHighlight=function(){c.gotoAndStop(1)};this._init(a,g,b,e)}
function CGfxButton(a,g,b,e){var d,h,f,m,k=[],c,q;this._init=function(a,b,e,g){d=h=1;f=[];m=[];c=createBitmap(e);c.x=a;c.y=b;c.regX=e.width/2;c.regY=e.height/2;s_bMobile||(c.cursor="pointer");n?n.addChild(c):s_oStage.addChild(c);q=!1;this._initListener()};this.unload=function(){c.off("mousedown",this.buttonDown);c.off("pressup",this.buttonRelease);n?n.removeChild(c):s_oStage.removeChild(c)};this.setVisible=function(a){c.visible=a};this._initListener=function(){c.on("mousedown",this.buttonDown);c.on("pressup",
this.buttonRelease)};this.addEventListener=function(a,c,b){f[a]=c;m[a]=b};this.addEventListenerWithParams=function(a,c,b,d){f[a]=c;m[a]=b;k=d};this.buttonRelease=function(){q||(c.scaleX=h,c.scaleY=d,playSound("click",1,!1),f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(m[ON_MOUSE_UP],k))};this.buttonDown=function(){q||(c.scaleX=.9*h,c.scaleY=.9*d,f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(m[ON_MOUSE_DOWN],k))};this.setScale=function(a){d=h=a;c.scaleX=a;c.scaleY=a};this.setScaleX=function(a){h=a;c.scaleX=a};this.setPosition=
function(a,b){c.x=a;c.y=b};this.setX=function(a){c.x=a};this.setY=function(a){c.y=a};this.getButtonImage=function(){return c};this.getX=function(){return c.x};this.getY=function(){return c.y};this.block=function(a){q=a};this.rotation=function(a){c.rotation=a};this.pulseAnimation=function(){createjs.Tween.get(c).to({scaleX:.9*h,scaleY:.9*d},850,createjs.Ease.quadOut).to({scaleX:h,scaleY:d},650,createjs.Ease.quadIn).call(function(){p.pulseAnimation()})};this.trebleAnimation=function(){createjs.Tween.get(c).to({rotation:5},
75,createjs.Ease.quadOut).to({rotation:-5},140,createjs.Ease.quadIn).to({rotation:0},75,createjs.Ease.quadIn).wait(750).call(function(){p.trebleAnimation()})};var n=e;var p=this;this._init(a,g,b,e);return this}
function CMenu(){var a,g,b,e,d,h,f,m,k,c,q,n,p,w,x=null,v=null;this._init=function(){f=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(f);var k=s_oSpriteLibrary.getSprite("logo_menu");p=createBitmap(k);p.x=CANVAS_WIDTH_HALF;p.y=.5*-k.width;p.regX=.5*k.width;p.regY=.5*k.height;p.rotation=-15;s_oStage.addChild(p);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)k=s_oSpriteLibrary.getSprite("icon_audio"),d=CANVAS_WIDTH-k.width/2+15,h=k.height/2+30,n=new CToggle(d,h,k,s_bAudioActive,
s_oStage),n.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);k=s_oSpriteLibrary.getSprite("but_play");m=new CGfxButton(CANVAS_WIDTH/2,1100,k);m.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);m.pulseAnimation();k=s_oSpriteLibrary.getSprite("but_info");b=k.width/2+30;e=k.height/2+30;c=new CGfxButton(b,e,k);c.addEventListener(ON_MOUSE_UP,this._onCredits,this);k=window.document;var A=k.documentElement;x=A.requestFullscreen||A.mozRequestFullScreen||A.webkitRequestFullScreen||A.msRequestFullscreen;
v=k.exitFullscreen||k.mozCancelFullScreen||k.webkitExitFullscreen||k.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(x=!1);x&&screenfull.isEnabled&&(k=s_oSpriteLibrary.getSprite("but_fullscreen"),a=b+k.width/2+10,g=e,w=new CToggle(a,g,k,s_bFullscreen,s_oStage),w.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));q=new createjs.Shape;q.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(q);createjs.Tween.get(p).wait(300).to({rotation:0},1E3,createjs.Ease.cubicOut);
createjs.Tween.get(p).wait(300).to({y:CANVAS_HEIGHT_HALF-100},1E3,createjs.Ease.bounceOut);createjs.Tween.get(q).to({alpha:0},1E3).call(function(){s_oStage.removeChild(q)});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){m.unload();m=null;c.unload();c=null;k&&(k.unload(),k=null);x&&screenfull.isEnabled&&w.unload();s_oStage.removeChild(f);f=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)n.unload(),n=null;s_oStage.removeAllChildren();s_oMenu=null};this.exitFromCredits=function(){};
this.refreshButtonPos=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||n.setPosition(d-s_iOffsetX,h+s_iOffsetY);x&&screenfull.isEnabled&&w.setPosition(a+s_iOffsetX,g+s_iOffsetY);c.setPosition(b+s_iOffsetX,e+s_iOffsetY)};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this.resetFullscreenBut=function(){x&&screenfull.isEnabled&&w.setActive(s_bFullscreen)};this._onFullscreenRelease=function(){s_bFullscreen?v.call(window.document):x.call(window.document.documentElement);
sizeHandler()};/*this._onCredits=function(){new CCreditsPanel};*/this._onButPlayRelease=function(){this.unload();s_oMain.gotoGame()};s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(a){function g(a){v||B||s_oGameField.isAnimFullLines()||(37===a.keyCode?(s_oGame.onLeft(),v=!0):39===a.keyCode?(s_oGame.onRight(),v=!0):38===a.keyCode&&(s_oGame.onUp(),v=!0));if(40===a.keyCode&&!1===A&&!B)s_oGame.onDown();a.preventDefault();return!1}function b(a){!v||B||s_oGameField.isAnimFullLines()||(37===a.keyCode?(v=!1,s_oGame.dirKeyUp()):39===a.keyCode?(v=!1,s_oGame.dirKeyUp()):38===a.keyCode?v=!1:80===a.keyCode?v=!1:32===a.keyCode&&(v=!1));if(40===a.keyCode&&!0===A)s_oGame.onDownKeyUp();
a.preventDefault();return!1}var e,d,h,f,m,k,c,q,n,p,w,x,v,B,A=!1,C=!1,I,D,J,F;this._init=function(){setVolume("soundtrack",SOUNDTRACK_VOLUME_IN_GAME);this.setPause(!0);e=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(e);c=new CEdges;this.createGameContainer();v=!1;h=new CGameField;x=w=p=q=0;I=D=TIME_REFRESH_GAME;F=[];for(var a=0;a<BLOCKS_TYPE.length;a++)for(;0<BLOCKS_OCCURENCE[a];a++)F.push(a);this.createBlock(F[Math.floor(Math.random()*F.length)]);this.nextType();d=new CInterface(n);
d.refreshLevel(p+1);this.canInput(!0);c.createIEdge();$(s_oMain).trigger("start_level",1);d.showHelpPanel();s_bMobile||(document.onkeydown=g,document.onkeyup=b)};this.createGameContainer=function(){m=new createjs.Container;s_oStage.addChild(m)};this.nextType=function(){n=F[Math.floor(Math.random()*F.length)]};this.setPause=function(a){B=a};this._onExitHelpPanel=function(){this.setPause(!1);d.unloadHelp()};this.onExit=function(){setVolume("soundtrack",1);s_oGame.unload();s_oMain.gotoMenu();$(s_oMain).trigger("end_level",
1);$(s_oMain).trigger("end_session");$(s_oMain).trigger("show_interlevel_ad")};this.restartGame=function(){h.unload();h=null;m.removeAllChildren();f=null;C=!1;this.nextType();d.refreshNextBlock(n);h=new CGameField;this.createBlock(F[Math.floor(Math.random()*F.length)]);D=TIME_REFRESH_GAME;x=w=p=q=0;d.refreshLevel(p+1);d.refreshLines(w);d.refreshScore(q);B=!1};this.unload=function(){s_bMobile||(document.onkeydown=null,document.onkeyup=null);h.unload();h=null;d.unload();createjs.Tween.removeAllTweens();
s_oStage.removeAllChildren()};this.onLeft=function(){f.getReplace()||(k=s_oGame.onLeft,C=!0,J=TIME_REFRESH_DIRECTION,0<f.getCol()&&!h.checkDirection(f,LEFT)&&(f.setCol(f.getCol()-1),f.refreshCellPosition()))};this.onRight=function(){f.getReplace()||(k=s_oGame.onRight,C=!0,J=TIME_REFRESH_DIRECTION,f.getCol()<GRID_X-f.getWidth()&&!h.checkDirection(f,RIGHT)&&(f.setCol(f.getCol()+1),f.refreshCellPosition()))};this.onUp=function(){playSound("shift_piece",1,!1);f.setOrientation(f.getOrientation()+90);f.refreshCellPosition()};
this.onDown=function(){A=!0;f.getReplace()||f.down();I=TIME_REFRESH_GAME_KEY_DOWN};this.calculateScore=function(a){this.addScore(SCORE_LINE[a-1]*(p+1))};this.checkForNewLevel=function(a){w+=a;x+=a;d.refreshLines(w);x>=LEVEL_UP_LINES&&(p++,x-=LEVEL_UP_LINES,d.refreshLevel(p+1),a=D-STEP_DECREASE,a>=MIN_REFRESH_GAME&&(D=a),STEP_DECREASE-=.05,.05>STEP_DECREASE&&(STEP_DECREASE=.05))};this.canInput=function(a){};this.addScore=function(a){q+=a;d.refreshScore(q)};this.dirKeyUp=function(){C=!1};this.onDownKeyUp=
function(){A=!1;I=D};this.createBlock=function(a){var c=s_oSpriteLibrary.getSprite("cell_"+a);f=new CBlock(a,c,m)};this.getContainerGame=function(){return m};this.gameOver=function(){this.setPause(!0);s_aSounds.game_over.on("end",function(){setVolume("soundtrack",SOUNDTRACK_VOLUME_IN_GAME)});playSound("game_over",1,!1);setVolume("soundtrack",0);$(s_oMain).trigger("end_level",1);d.gameOver(q,p+1,w)};this.keysDirectionPress=function(){C&&k()};this.update=function(){if(!1===B&&!s_oGameField.isAnimFullLines()){if(!0===
f.getReplace()&&(f=null,this.createBlock(n),this.nextType(),d.refreshNextBlock(n),s_oGameField.checkDirection(f))){this.gameOver();return}0>I?(f.down(),I=A?TIME_REFRESH_GAME_KEY_DOWN:1E3*D):I-=s_iTimeElaps;0>J?(J=TIME_REFRESH_DIRECTION,this.keysDirectionPress()):C&&(J-=FPS_TIME)}};s_oGame=this;LEVEL_UP_LINES=a.level_up_lines;MIN_REFRESH_GAME=a.min_refresh_game;SCORE_LINE=a.score_line;TIME_REFRESH_GAME=a.start_refresh_game;STEP_DECREASE=a.step_decrease_refresh_game;BLOCKS_OCCURENCE=a.blocks_occurence;
NUM_LEVEL_FOR_ADS=a.num_levels_for_ads;TIME_REFRESH_GAME_KEY_DOWN=MIN_REFRESH_GAME;this._init()}var s_oGame,s_oScrollStage;
function CInterface(a){var g,b,e,d,h,f,m,k,c,q=null,n=null,p,w,x,v,B,A,C,I,D,J,F,O,u,G=null,N;this._init=function(a){var E=s_oSpriteLibrary.getSprite("but_exit");e=CANVAS_WIDTH-E.width/2-30;d=E.height/2+30;x=new CGfxButton(e,d,E);x.addEventListener(ON_MOUSE_UP,this._onExit,this);var v=s_oSpriteLibrary.getSprite("but_pause");m=CANVAS_WIDTH-v.width/2-E.width-30-15;k=v.height/2+30;w=new CGfxButton(m,k,v);w.addEventListener(ON_MOUSE_UP,this.onButPauseRelease,this);var C=s_oSpriteLibrary.getSprite("but_fullscreen");
if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile){var D=s_oSpriteLibrary.getSprite("icon_audio");h=CANVAS_WIDTH-D.width/2-v.width-E.width/2-30-30;f=D.height/2+30;p=new CToggle(h,f,D,s_bAudioActive,s_oStage);p.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);g=h-C.width/2-10;b=f}else g=CANVAS_WIDTH-C.width/2-v.width-E.width/2-30-30,b=C.height/2+30;E=window.document;v=E.documentElement;q=v.requestFullscreen||v.mozRequestFullScreen||v.webkitRequestFullScreen||v.msRequestFullscreen;n=E.exitFullscreen||
E.mozCancelFullScreen||E.webkitExitFullscreen||E.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(q=!1);q&&screenfull.isEnabled&&(N=new CToggle(g,b,C,s_bFullscreen,s_oStage),N.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));C=s_oSpriteLibrary.getSprite("next_board");J=new CNextBlockBoard(800,417,C,a,s_oStage);a=s_oSpriteLibrary.getSprite("info_board");F=new CInfoBoard(800,757,a,s_oStage);a=s_oSpriteLibrary.getSprite("score_board");O=new CScoreBoard(800,1051,a,s_oStage);a=s_oSpriteLibrary.getSprite("small_logo");
c={x:.5*a.width+30,y:.5*a.height+30};u=createBitmap(a);u.x=c;u.y=c;u.regX=.5*a.width;u.regY=.5*a.height;s_oStage.addChild(u);!0===SHOW_FPS&&(B=new createjs.Text("","normal 60px "+PRIMARY_FONT,"#ffd800"),B.textAlign="center",B.textBaseline="alphabetic",B.x=.5*CANVAS_WIDTH+-330,B.y=.5*CANVAS_HEIGHT+550,A=new createjs.Text("","normal 60px "+PRIMARY_FONT,"#025cce"),A.textAlign="center",A.textBaseline="alphabetic",A.x=.5*CANVAS_WIDTH+-328,A.y=.5*CANVAS_HEIGHT+552,s_oStage.addChild(A,B));s_bMobile&&(G=
new CController);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||p.setPosition(h-s_iOffsetX,f+s_iOffsetY);q&&screenfull.isEnabled&&N.setPosition(g-s_iOffsetX,b+s_iOffsetY);w.setPosition(m-s_iOffsetX,k+s_iOffsetY);x.setPosition(e-s_iOffsetX,d+s_iOffsetY);var a=J.getStartPos();J.setPosition(a.x-s_iOffsetX,a.y);a=F.getStartPos();F.setPosition(a.x-s_iOffsetX,a.y);a=O.getStartPos();O.setPosition(a.x-s_iOffsetX,a.y);u.x=c.x+s_iOffsetX;
u.y=c.y+s_iOffsetY;null!==G&&(a=G.getStartPositionControlLeft(),G.setPositionControlLeft(a.x+s_iOffsetX,a.y-s_iOffsetY),a=G.getStartPositionControlRight(),G.setPositionControlRight(a.x+s_iOffsetX,a.y-s_iOffsetY),a=G.getStartPositionControlUp(),G.setPositionControlUp(a.x-s_iOffsetX,a.y-s_iOffsetY),a=G.getStartPositionControlDown(),G.setPositionControlDown(a.x+s_iOffsetX,a.y-s_iOffsetY))};this.finishGame=function(a){var c=s_oSpriteLibrary.getSprite("msg_box");I=new CCongratulations(c,a)};this._onButNextLevelRelease=
function(){setVolume("soundtrack",SOUNDTRACK_VOLUME_IN_GAME);C=null;s_oGame.nextLevel()};this._onButSpaceBarRelease=function(){C&&C._onContinue()};this._onButMenuRelease=function(){I&&(I.unload(),I=null);s_oGame.onExit()};this.refreshScore=function(a){O.refreshScore(a)};this.refreshLevel=function(a){F.refreshLevel(a)};this.refreshLines=function(a){F.refreshLines(a)};this.unloadPause=function(){D.unload();D=null};this.onButPauseRelease=function(){D=new CPause};this.onContinuePauseRelease=function(){D&&
D._onLeavePause()};this.showHelpPanel=function(){var a=s_oSpriteLibrary.getSprite("msg_box");v=new CHelpPanel(0,0,a)};this.gameOver=function(a,c,b){var d=s_oSpriteLibrary.getSprite("msg_box");new CGameOver(d,a,c,b)};this.unloadHelp=function(){v.unload();v=null};this._onButRestartLevelRelease=function(){s_oGame.restartLevelFromGameOver();x.block(!1)};this.unload=function(){x.unload();x=null;w.unload();w=null;null!==G&&(G.unload(),G=null);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)p.unload(),p=null;
q&&screenfull.isEnabled&&N.unload();s_oInterface=null};this.refreshNextBlock=function(a){J.refreshBlock(a)};this.refreshFPS=function(){var a=Math.ceil(createjs.Ticker.getMeasuredFPS());B.text="FPS:"+a;A.text="FPS:"+a};this._onExit=function(){(new CAreYouSurePanel(s_oStage)).show()};this._onButRestartLevelRelease=function(){s_oGame.restartGame()};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this.resetFullscreenBut=function(){q&&screenfull.isEnabled&&N.setActive(s_bFullscreen)};
this._onFullscreenRelease=function(){s_bFullscreen?n.call(window.document):q.call(window.document.documentElement);sizeHandler()};s_oInterface=this;this._init(a);return this}var s_oInterface=null;
function CHelpPanel(a,g,b){var e,d,h,f,m,k=!1;this._init=function(a,b,k){f=new createjs.Container;f.x=a;f.y=b;s_oStage.addChild(f);h=new createjs.Shape;h.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);h.alpha=.7;f.addChild(h);d=createBitmap(k);d.x=CANVAS_WIDTH_HALF;d.y=CANVAS_HEIGHT_HALF;d.regX=.5*k.width;d.regY=.5*k.height;f.addChild(d);e=new CTLText(f,CANVAS_WIDTH/2-300,.5*CANVAS_HEIGHT-230,600,50,50,"center","#0025c2",PRIMARY_FONT,1,0,0,TEXT_HOW_TO_PLAY,!0,!0,!1,!1);e.setOutline(4);
new CTLText(f,CANVAS_WIDTH/2-300,.5*CANVAS_HEIGHT-230,600,50,50,"center","#ffd800",PRIMARY_FONT,1,0,0,TEXT_HOW_TO_PLAY,!0,!0,!1,!1);m=new createjs.Container;if(s_bMobile){var c=s_oSpriteLibrary.getSprite("arrow");var g=s_oSpriteLibrary.getSprite("arrow");var n=s_oSpriteLibrary.getSprite("arrow");var q=s_oSpriteLibrary.getSprite("but_rotation")}else c=s_oSpriteLibrary.getSprite("key_left"),g=s_oSpriteLibrary.getSprite("key_up"),n=s_oSpriteLibrary.getSprite("key_right"),q=s_oSpriteLibrary.getSprite("key_down");
a=this.createKey(CANVAS_WIDTH_HALF,CANVAS_HEIGHT_HALF-100,s_oSpriteLibrary.getSprite("block_blur"));b=this.createKey(CANVAS_WIDTH_HALF-125,CANVAS_HEIGHT_HALF+30,s_oSpriteLibrary.getSprite("block_down"));k=this.createKey(CANVAS_WIDTH_HALF+125,CANVAS_HEIGHT_HALF+30,s_oSpriteLibrary.getSprite("block_rotation"));c=this.createKey(CANVAS_WIDTH_HALF-135,CANVAS_HEIGHT_HALF-90,c);g=this.createKey(CANVAS_WIDTH_HALF+125,CANVAS_HEIGHT_HALF+170,g);n=this.createKey(CANVAS_WIDTH_HALF+135,CANVAS_HEIGHT_HALF-90,n);
q=this.createKey(CANVAS_WIDTH_HALF-125,CANVAS_HEIGHT_HALF+170,q);s_bMobile&&(c.scaleX=-1,g.rotation=270);m.addChild(c,g,n,q,a,b,k);f.addChild(m);s_bMobile||(f.cursor="pointer");var B=this;f.on("pressup",function(){B._onExitHelp()})};this.createKey=function(a,b,d){var c=createBitmap(d);c.x=a;c.y=b;c.regX=.5*d.width;c.regY=.5*d.height;return c};this.unload=function(){createjs.Tween.removeAllTweens();createjs.Tween.get(f).to({alpha:0},500,createjs.Ease.cubicIn).call(function(){s_oStage.removeChild(f)});
var a=this;f.off("pressup",function(){a._onExitHelp()})};this._onExitHelp=function(){k||(k=!0,this.unload(),s_oGame._onExitHelpPanel())};this._init(a,g,b);return this}
function CGameOver(a,g,b,e){var d,h,f,m,k,c;this._init=function(a,b,e,g){s_oGame.setPause(!0);d=new createjs.Container;h=new createjs.Container;h.y=-CANVAS_WIDTH_HALF-.5*a.width;f=createBitmap(a);f.x=.5*CANVAS_WIDTH;f.y=.5*CANVAS_HEIGHT;f.regX=.5*a.width;f.regY=.5*a.height;h.addChild(f);m=new createjs.Shape;m.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);m.alpha=0;m.on("click",function(){});d.addChild(m);a=.5*CANVAS_WIDTH;var n=.5*CANVAS_HEIGHT-75;(new CTLText(h,a-300,n-150,
600,60,60,"center","#0025c2",PRIMARY_FONT,1,0,0,TEXT_GAMEOVER,!0,!0,!1,!1)).setOutline(OUTLINE_TEXT);new CTLText(h,a-300,n-150,600,60,60,"center","#ffd800",PRIMARY_FONT,1,0,0,TEXT_GAMEOVER,!0,!0,!1,!1);(new CTLText(h,a-300,n-25,250,80,40,"center","#025cce",PRIMARY_FONT,1,0,0,TEXT_LEVEL+"\n"+e,!0,!0,!0,!1)).setOutline(OUTLINE_TEXT);new CTLText(h,a-300,n-25,250,80,40,"center","#ffd800",PRIMARY_FONT,1,0,0,TEXT_LEVEL+"\n"+e,!0,!0,!0,!1);(new CTLText(h,a+50,n-25,250,80,40,"center","#025cce",PRIMARY_FONT,
1,0,0,TEXT_LINES+"\n"+g,!0,!0,!0,!1)).setOutline(OUTLINE_TEXT);new CTLText(h,a+50,n-25,250,80,40,"center","#ffd800",PRIMARY_FONT,1,0,0,TEXT_LINES+"\n"+g,!0,!0,!0,!1);(new CTLText(h,a-150,n+100,300,120,40,"center","#025cce",PRIMARY_FONT,1,0,0,TEXT_SCORE_GAMEOVER+"\n\n"+b,!0,!0,!0,!1)).setOutline(4);new CTLText(h,a-150,n+100,300,120,40,"center","#ffd800",PRIMARY_FONT,1,0,0,TEXT_SCORE_GAMEOVER+"\n\n"+b,!0,!0,!0,!1);d.addChild(h);s_oStage.addChild(d);e=s_oSpriteLibrary.getSprite("but_restart");g=s_oSpriteLibrary.getSprite("but_home");
k=new CGfxButton(CANVAS_WIDTH/2-250,CANVAS_HEIGHT/2+150,g,h);k.addEventListener(ON_MOUSE_UP,this._onMenu,this);c=new CGfxButton(CANVAS_WIDTH/2+250,CANVAS_HEIGHT/2+150,e,h);c.addEventListener(ON_MOUSE_UP,this._onRestart,this);c.pulseAnimation();createjs.Tween.get(m).to({alpha:.5},750,createjs.Ease.cubicOut);createjs.Tween.get(h).to({y:0},1500,createjs.Ease.bounceOut).call(function(){s_iAdsLevel===NUM_LEVEL_FOR_ADS?($(s_oMain).trigger("show_interlevel_ad"),s_iAdsLevel=1):s_iAdsLevel++});$(s_oMain).trigger("save_score",
b);$(s_oMain).trigger("share_event",b)};this.unload=function(){m.off("click",function(){});k&&(k.unload(),k=null);s_oStage.removeChild(d)};this._onMenu=function(){this.unload();s_oInterface._onButMenuRelease()};this._onRestart=function(){this.unload();s_oInterface._onButRestartLevelRelease()};this._init(a,g,b,e);return this}
function CPause(){var a,g,b;this._init=function(){a=new createjs.Container;a.alpha=0;g=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));g.alpha=1;g.on("click",function(){});a.addChild(g);var e=s_oSpriteLibrary.getSprite("pause_text");b=createBitmap(e);b.x=CANVAS_WIDTH_HALF;b.y=CANVAS_HEIGHT_HALF-200;b.regX=.5*e.width;b.regY=.5*e.height;a.addChild(b);e=s_oSpriteLibrary.getSprite("but_continue");(new CGfxButton(.5*CANVAS_WIDTH,.5*CANVAS_HEIGHT+100,e,a)).addEventListener(ON_MOUSE_UP,this._onLeavePause,
this);s_oStage.addChild(a);this.onPause(!0);createjs.Tween.get(a).to({alpha:1},300,createjs.quartOut).call(function(){createjs.Ticker.paused=!0})};this.onPause=function(a){s_oGame.setPause(a);s_oGame.canInput(!a)};this.unload=function(){g.off("click",function(){});s_oStage.removeChild(a)};this._onLeavePause=function(){createjs.Ticker.paused=!1;createjs.Tween.removeTweens(a);var b=this;createjs.Tween.get(a).to({alpha:0},300,createjs.quartIn).call(function(){b.onPause(!1);s_oInterface.unloadPause()})};
this._init();return this}
function CAreYouSurePanel(a){var g,b,e,d,h,f;this._init=function(){h=new createjs.Container;h.visible=!1;m.addChild(h);f=new createjs.Shape;f.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);f.alpha=.7;f.on("click",function(){});h.addChild(f);var a=s_oSpriteLibrary.getSprite("msg_box");d=createBitmap(a);d.x=CANVAS_WIDTH_HALF;d.y=CANVAS_HEIGHT_HALF;d.regX=.5*a.width;d.regY=.5*a.height;h.addChild(d);d.on("click",function(){});g=new CTLText(h,CANVAS_WIDTH/2-300,.5*CANVAS_HEIGHT-150,
600,150,70,"center","#0025c2",PRIMARY_FONT,1,0,0,TEXT_ARE_SURE,!0,!0,!0,!1);g.setOutline(5);new CTLText(h,CANVAS_WIDTH/2-300,.5*CANVAS_HEIGHT-150,600,150,70,"center","#ffd800",PRIMARY_FONT,1,0,0,TEXT_ARE_SURE,!0,!0,!0,!1);b=new CGfxButton(CANVAS_WIDTH/2+170,.5*CANVAS_HEIGHT+150,s_oSpriteLibrary.getSprite("but_yes"),h);b.addEventListener(ON_MOUSE_UP,this._onButYes,this);e=new CGfxButton(CANVAS_WIDTH/2-170,.5*CANVAS_HEIGHT+150,s_oSpriteLibrary.getSprite("but_not"),h);e.addEventListener(ON_MOUSE_UP,
this._onButNo,this)};this.onPause=function(a){s_oGame.setPause(a);createjs.Ticker.paused=a;!0===a?s_oGame.canInput(!1):s_oGame.canInput(!0)};this.show=function(){this.onPause(!0);h.visible=!0};this.unload=function(){e.unload();b.unload();f.off("click",function(){})};this._onButYes=function(){this.unload();this.onPause(!1);s_oGame.onExit()};this._onButNo=function(){this.unload();this.onPause(!1);h.visible=!1};var m=a;this._init()}
function CCreditsPanel(){var a,g,b,e,d,h,f,m,k;this._init=function(){k=new createjs.Container;k.y=-130;s_oStage.addChild(k);var c=new createjs.Shape;c.graphics.beginFill("black").drawRect(0,130,CANVAS_WIDTH,CANVAS_HEIGHT);c.alpha=.7;k.addChild(c);c=s_oSpriteLibrary.getSprite("msg_box");a=createBitmap(c);k.addChild(a);a.x=.5*CANVAS_WIDTH;a.y=.5*CANVAS_HEIGHT+130;a.regX=.5*c.width;a.regY=.5*c.height;h=new createjs.Shape;h.graphics.beginFill("#0f0f0f").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);h.alpha=
.01;h.on("click",this._onLogoButRelease);s_bMobile||(h.cursor="pointer");k.addChild(h);c=s_oSpriteLibrary.getSprite("but_exit");b=new CGfxButton(800,640,c,k);b.addEventListener(ON_MOUSE_UP,this.unload,this);d=new createjs.Text(TEXT_CREDITS_DEVELOPED,"40px "+PRIMARY_FONT,"#025cce");d.textAlign="center";d.textBaseline="alphabetic";d.x=CANVAS_WIDTH/2;d.y=770;d.outline=OUTLINE_TEXT;k.addChild(d);e=new createjs.Text(TEXT_CREDITS_DEVELOPED,"40px "+PRIMARY_FONT,"#ffd800");e.textAlign="center";e.textBaseline=
"alphabetic";e.x=CANVAS_WIDTH/2;e.y=d.y;k.addChild(e);c=s_oSpriteLibrary.getSprite("logo_ctl");g=createBitmap(c);g.regX=c.width/2;g.regY=c.height/2;g.x=CANVAS_WIDTH/2;g.y=850;k.addChild(g);m=new createjs.Text(TEXT_LINK1,"40px "+PRIMARY_FONT,"#025cce");m.textAlign="center";m.textBaseline="alphabetic";m.x=CANVAS_WIDTH/2;m.y=980;m.outline=OUTLINE_TEXT;k.addChild(m);f=new createjs.Text(TEXT_LINK1,"40px "+PRIMARY_FONT,"#ffd800");f.textAlign="center";f.textBaseline="alphabetic";f.x=CANVAS_WIDTH/2;f.y=m.y;
k.addChild(f);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(a,b){};this.unload=function(){h.off("click",this._onLogoButRelease);b.unload();b=null;s_oStage.removeChild(k);s_oMenu.exitFromCredits()};this._onLogoButRelease=function(){window.open("http://www.codethislab.com/index.php?&l=en","_blank")};this._init()}
function CBlock(a,g,b){var e=0,d,h,f=!1,m,k=BLOCKS_TYPE[a];this._init=function(a){h=Math.floor(GRID_X_HALF-this.getWidth()/2);d=0;m=this.createSpriteBlock(a);this.refreshCellPosition();this.orderCellsChildIndex()};this.getHeight=function(){return k.length};this.getWidth=function(){return k[0].length};this.createSpriteBlock=function(a){for(var c=[],b=h,f=d,e=s_oGameField.getXByCol(b),g=s_oGameField.getYByRow(f),m=k.length*k[0].length,B=0,A=0;A<k.length;A++){for(var C=0;C<k[A].length;C++)1===k[A][C]&&
(c[B]=this.createCell(e,g,a,f,b,0),B++),b++,e=s_oGameField.getXByCol(b),m--;f++;b=h;g=s_oGameField.getYByRow(f);e=s_oGameField.getXByCol(b)}return c};this.createCell=function(a,d,f,e,h,g){a=new CCell(a,d,g,f,b);a.setRow(e);a.setCol(h);return a};this.orderCellsChildIndex=function(){for(var a=b.numChildren-1,d=0;d<m.length;d++)m[d].setChildIndex(a),a--};this.updateRenderOffsets=function(a){a.x++;a.x>=this.getWidth()&&(a.y++,a.x=0);return a};this.pieceFilled=function(a){a=this.stepToCooordinates(a);
return!!k[a.y][a.x]};this.stepToCooordinates=function(a){var c={x:0,y:0};c.x=a%this.getWidth();c.y=Math.floor(a/this.getWidth());return c};this.down=function(){s_oGameField.checkHitBottom(this,DOWN);!0!==f&&(d+=1,this.refreshCellPosition())};this.refreshCellPosition=function(){for(var a=h,b=d,f=0,e=s_oGameField.getXByCol(a),g=s_oGameField.getYByRow(b),x=0;x<k.length;x++){for(var v=0;v<k[x].length;v++)1===k[x][v]&&(m[f].setPosition(e,g),m[f].setRow(b),m[f].setCol(a),m[f].setChildIndex(s_oGameField.getChildID(b,
a)),f++),a++,a<GRID_X&&(e=s_oGameField.getXByCol(a));if(b+1>GRID_Y-1)break;b++;a=h;g=s_oGameField.getYByRow(b);e=s_oGameField.getXByCol(a)}};this.setReplace=function(a){f=a};this.getReplace=function(){return f};this.getCol=function(){return h};this.getRow=function(){return d};this.getBlock=function(){return m};this.setRow=function(a){d=a};this.setCol=function(a){h=a};this.__rotateBlock=function(a){for(var b=[],c=a[0].length-1;-1<c;c--){for(var d=[],f=0;f<a.length;f++)d.push(a[f][c]);b.push(d)}return b};
this.getOrientation=function(){return e};this.setOrientation=function(a){360===a&&(a=0);var b=this.__rotateBlock(k),c=s_oGameField.badRotation(b,this);1!==c&&(0===c?(e=a,k=b):2===c&&this.setOrientation(a))};this.unload=function(){for(var a=0;a<m.length;a++)m[a].unload();m=null};this._init(g);return this}
function CGameField(){var a=[],g=!1;this._init=function(){s_bMobile&&(START_GRID_Y=CANVAS_HEIGHT_HALF-GRID_Y*GRID_Y);for(var b=START_GRID_X,e=START_GRID_Y,d=0;d<GRID_Y;d++){a[d]=[];for(var h=0;h<GRID_X;h++)a[d][h]={x:b,y:e,occupied:!1,cell:null,childID:null},this.createCellTest(b,e),b+=CELL_SIZE+CELL_OFFSET.x;e+=CELL_SIZE+CELL_OFFSET.y;b=START_GRID_X}this.setID()};this.createCellTest=function(a,e){if(SHOW_CELL){var b=s_oSpriteLibrary.getSprite("cell");var h=createBitmap(b);h.x=a;h.y=e;h.regX=.5*b.width;
h.regY=.5*b.height;s_oStage.addChild(h);s_oStage.setChildIndex(h,1)}};this.setID=function(){for(var b=s_oSpriteLibrary.getSprite("cell_0"),e=GRID_Y-1;-1<e;e--)for(var d=GRID_X-1;-1<d;d--)a[e][d].childID=new CCell(a[e][d].x,a[e][d].y,0,b,s_oGame.getContainerGame()),a[e][d].childID.setVisible(!1)};this.getMiddleGridX=function(){return a[0][GRID_X_HALF].x};this.getStartGridY=function(){return a[0][0].y};this.getXByCol=function(b){return a[0][b].x};this.getYByRow=function(b){return a[b][0].y};this.setCellState=
function(b,e,d){a[b][e].occupied=d};this.getCellState=function(b,e){return a[b][e].occupied};this.checkDirection=function(b,e){for(var d=!1,h={x:0,y:0},f,g,k=0;k<b.getWidth()*b.getHeight();k++){f=b.getCol()+h.x;g=b.getRow()+h.y;switch(e){case UP:g--;break;case RIGHT:f++;break;case DOWN:g++;break;case LEFT:f--}if(g>GRID_Y-1)return!0;if(a[g][f].occupied&&(f=b.pieceFilled(k))){d=!0;break}h=b.updateRenderOffsets(h)}return d};this.getChildID=function(b,e){return a[b][e].childID.getChildIndex()};this.checkHitBottom=
function(b){var e=this.checkDirection(b,DOWN);b.getRow()+b.getHeight()>=a.length&&(e=!0);if(e){b.setReplace(!0);b=b.getBlock();for(e=0;e<b.length;e++)a[b[e].getRow()][b[e].getCol()].occupied=!0,a[b[e].getRow()][b[e].getCol()].cell=b[e];this.checkForFullLines()}};this.badRotation=function(b,e){for(var d=0,h=0,f=0,g,k,c=0;c<b[0].length*b.length;c++){g=e.getCol()+h;k=e.getRow()+f;if(k>GRID_Y-1)return 1;if(g>GRID_X-1)return e.setCol(e.getCol()-e.getWidth()+1),2;if(a[k][g].occupied){d=1;break}h++;h>=b[0].length&&
(f++,h=0)}return d};this.isAnimFullLines=function(){return g};this.checkForFullLines=function(){for(var b=0,e,d=[],h=0,f=0;f<a.length;f++){for(var m=e=0;m<a[0].length;m++)a[f][m].occupied&&e++;if(e===a[0].length){b++;d[h]=f;h++;var k=DELAY_CELL_DESTROY_MS;for(m=0;m<a[0].length;m++)a[f][m].occupied=!1,this.animCellDestroy(a[f][m],k),k+=DELAY_CELL_DESTROY_MS}}0<b&&(g=!0,playSound("delete_lines",1,!1),k+=2*CELL_DESTROY_MS,createjs.Tween.get(this).wait(k).call(function(){s_oGame.calculateScore(b);s_oGame.checkForNewLevel(b);
this.checkEmptyRowForFall(d);g=!1}))};this.animCellDestroy=function(a,e){a.cell.changeState(1);createjs.Tween.get(a.cell.getSprite()).wait(e).to({scaleX:0,scaleY:0},CELL_DESTROY_MS,createjs.Ease.cubicOut).call(function(){!0===a.occupied&&a.cell.unload()})};this.checkEmptyRowForFall=function(b){for(var e=0,d=0;d<b.length;d++)for(var h=0;h<a[d].length;h++)for(var f=b[d]-1;-1<f;f--)!0===a[f][h].occupied&&(a[f][h].occupied=!1,a[f+1][h].cell=a[f][h].cell,a[f][h].cell=null,a[f+1][h].occupied=!0);for(f=
a[d].length-1;-1<f;f--)for(d=a.length-1;-1<d;d--)!0===a[d][f].occupied&&(a[d][f].cell.setChildIndex(this.getChildID(d,f)),this.animateLineDown(a[d][f].cell.getSprite(),a[d][f].y,e),e+=DELAY_LINE_DOWN)};this.animateLineDown=function(a,e,d){createjs.Tween.get(a).wait(d).to({y:e},LINE_DOWN_TIME,createjs.Ease.cubicOut)};this.unload=function(){for(var b=0;b<a.length;b++)for(var e=0;e<a[0].length;e++)a[b][e].occupied&&a[b][e].cell.unload();s_oGameField=a=null};this._init();s_oGameField=this;return this}
var s_oGameField;
function CCell(a,g,b,e,d){var h,f,m;this._init=function(a,b,f,e){h=createBitmap(e);h.x=a;h.y=b;a=new createjs.SpriteSheet({images:[e],frames:{width:e.width/2,height:e.height,regX:e.width/2/2,regY:e.height/2+f},animations:{normal:[0],complete:[1]}});h=createSprite(a,"normal",e.width/2/2,e.height/2+f,e.width/2,e.height);h.stop();d.addChild(h)};this.setPosition=function(a,b){h.x=a;h.y=b};this.getY=function(){return h.y};this.getX=function(){return h.x};this.setRow=function(a){f=a};this.setCol=function(a){m=
a};this.getRow=function(){return f};this.getCol=function(){return m};this.setRegY=function(a){h.regY=a};this.changeState=function(a){h.gotoAndStop(a)};this.getSprite=function(){return h};this.getRegY=function(){return h.regY};this.setVisible=function(a){h.visible=a};this.getChildIndex=function(){return d.getChildIndex(h)};this.setChildIndex=function(a){d.setChildIndex(h,a)};this.unload=function(){d.removeChild(h)};this._init(a,g,b,e);return this}
function CNextBlockBoard(a,g,b,e,d){var h,f,m,k,c,q,n,p;this._init=function(a,b,c,d){p={x:a,y:b};m=new createjs.Container;m.x=a;m.y=b;w.addChild(m);f=createBitmap(d);f.regX=.5*d.width;f.regY=.5*d.height;m.addChild(f);h=new CTLText(m,-90,-f.regY+36,180,33,33,"center","#025cce",PRIMARY_FONT,1,0,0,TEXT_NEXT,!0,!0,!1,!1);h.setOutline(5);new CTLText(m,-90,-f.regY+36,180,33,33,"center","#ffd800",PRIMARY_FONT,1,0,0,TEXT_NEXT,!0,!0,!1,!1);k=new createjs.Container;q=.15*f.regX;n=.25*f.regY+16;m.addChild(k);
this.createNextBlock(c)};this.createNextBlock=function(a){c=new CNextBlock(BLOCKS_TYPE[a],s_oSpriteLibrary.getSprite("cell_"+a),k);k.x=q-c.getOffsetX();k.y=n-c.getOffsetY()};this.refreshBlock=function(a){c.unload();this.createNextBlock(a)};this.getStartPos=function(){return p};this.setPosition=function(a,b){m.x=a;m.y=b};var w=d;this._init(a,g,e,b);return this}
function CNextBlock(a,g,b){var e,d,h;this._init=function(a,b){d=0;e=this.createSpriteBlock(a,b);this.orderCellsChildIndex()};this.createSpriteBlock=function(a,b){for(var e=[],c=0,f=0,g=0;g<a.length;g++){for(var m=0;m<a[g].length;m++)1===a[g][m]&&e.push(this.createCell(c,f,b,0)),c+=CELL_SIZE+CELL_OFFSET.x;f+=CELL_SIZE+CELL_OFFSET.y;c=0}d=.5*(CELL_SIZE+CELL_OFFSET.y)*a[0].length;h=.5*(CELL_SIZE+CELL_OFFSET.x)*a.length;return e};this.createCell=function(a,d,e,c){e=new CCell(a,d,c,e,b);e.setPosition(a,
d);return e};this.orderCellsChildIndex=function(){for(var a=b.numChildren-1,d=0;d<e.length;d++)e[d].setChildIndex(a),a--};this.getOffsetX=function(){return d};this.getOffsetY=function(){return h};this.unload=function(){for(var a=0;a<e.length;a++)e[a].unload();e=null};this._init(a,g);return this}
function CInfoBoard(a,g,b,e){var d,h,f,m,k,c,q;this._init=function(a,b,g){q={x:a,y:b};c=new createjs.Container;c.x=a;c.y=b;e.addChild(c);d=createBitmap(g);d.regX=.5*g.width;d.regY=.5*g.height;c.addChild(d);(new CTLText(c,-90,.5*-d.regY-24,180,33,33,"center","#025cce",PRIMARY_FONT,1,0,0,TEXT_LEVEL,!0,!0,!1,!1)).setOutline(4);new CTLText(c,-90,.5*-d.regY-24,180,33,33,"center","#ffd800",PRIMARY_FONT,1,0,0,TEXT_LEVEL,!0,!0,!1,!1);f=new CTLText(c,-45,.5*-d.regY+25,100,33,33,"center","#025cce",PRIMARY_FONT,
1,0,0,"1",!0,!0,!1,!1);f.setOutline(4);h=new CTLText(c,-45,.5*-d.regY+25,100,33,33,"center","#ffd800",PRIMARY_FONT,1,0,0,"1",!0,!0,!1,!1);(new CTLText(c,-90,.5*-d.regY+74,180,33,33,"center","#025cce",PRIMARY_FONT,1,0,0,TEXT_LINES,!0,!0,!1,!1)).setOutline(4);new CTLText(c,-90,.5*-d.regY+74,180,33,33,"center","#ffd800",PRIMARY_FONT,1,0,0,TEXT_LINES,!0,!0,!1,!1);k=new CTLText(c,-45,.5*-d.regY+124,100,33,33,"center","#025cce",PRIMARY_FONT,1,0,0,"1",!0,!0,!1,!1);k.setOutline(4);m=new CTLText(c,-45,.5*
-d.regY+124,100,33,33,"center","#ffd800",PRIMARY_FONT,1,0,0,"1",!0,!0,!1,!1)};this.refreshLevel=function(a){h.refreshText(a);f.refreshText(a)};this.refreshLines=function(a){k.refreshText(a);m.refreshText(a)};this.getStartPos=function(){return q};this.setPosition=function(a,b){c.x=a;c.y=b};this._init(a,g,b);return this}
function CScoreBoard(a,g,b,e){var d,h,f,m,k;this._init=function(a,b,g){k={x:a,y:b};m=new createjs.Container;m.x=a;m.y=b;e.addChild(m);d=createBitmap(g);d.regX=.5*g.width;d.regY=.5*g.height;m.addChild(d);(new CTLText(m,-90,-45,180,36,36,"center","#025cce",PRIMARY_FONT,1,0,0,TEXT_SCORE,!0,!0,!1,!1)).setOutline(4);new CTLText(m,-90,-45,180,36,36,"center","#ffd800",PRIMARY_FONT,1,0,0,TEXT_SCORE,!0,!0,!1,!1);f=new CTLText(m,-80,6,170,36,36,"center","#025cce",PRIMARY_FONT,1,0,0,"0",!0,!0,!1,!1);f.setOutline(4);
h=new CTLText(m,-80,6,170,36,36,"center","#ffd800",PRIMARY_FONT,1,0,0,"0",!0,!0,!1,!1)};this.refreshScore=function(a){h.refreshText(a);f.refreshText(a)};this.getStartPos=function(){return k};this.setPosition=function(a,b){m.x=a;m.y=b};this._init(a,g,b);return this}
function CController(){var a,g,b,e,d,h,f,m;this._init=function(){a={x:.5*CANVAS_WIDTH-210,y:CANVAS_HEIGHT-80};g={x:.5*CANVAS_WIDTH-380,y:CANVAS_HEIGHT-80};b={x:.5*CANVAS_WIDTH+380,y:CANVAS_HEIGHT-80};e={x:.5*CANVAS_WIDTH-60,y:CANVAS_HEIGHT-80};var k=s_oSpriteLibrary.getSprite("arrow"),c=s_oSpriteLibrary.getSprite("but_rotation");d=new CGfxButton(g.x,g.y,k,s_oStage);d.addEventListener(ON_MOUSE_DOWN,s_oGame.onLeft,this);d.addEventListener(ON_MOUSE_UP,s_oGame.dirKeyUp,this);d.setScaleX(-1);h=new CGfxButton(a.x,
a.y,k,s_oStage);h.addEventListener(ON_MOUSE_DOWN,s_oGame.onRight,this);h.addEventListener(ON_MOUSE_UP,s_oGame.dirKeyUp,this);f=new CGfxButton(b.x,b.y,c,s_oStage);f.addEventListener(ON_MOUSE_DOWN,s_oGame.onUp,this);m=new CGfxButton(e.x,e.y,k,s_oStage);m.addEventListener(ON_MOUSE_DOWN,s_oGame.onDown,this);m.addEventListener(ON_MOUSE_UP,s_oGame.onDownKeyUp,this);m.rotation(90)};this.getStartPositionControlRight=function(){return a};this.getStartPositionControlLeft=function(){return g};this.getStartPositionControlUp=
function(){return b};this.getStartPositionControlDown=function(){return e};this.setPositionControlRight=function(a,b){h.setPosition(a,b)};this.setPositionControlLeft=function(a,b){d.setPosition(a,b)};this.setPositionControlUp=function(a,b){f.setPosition(a,b)};this.setPositionControlDown=function(a,b){m.setPosition(a,b)};this.unload=function(){d.unload();d=null;h.unload();h=null;f.unload();f=null;m.unload();m=null};this._init();return this}
function CEdges(){var a,g;this._init=function(){var b=s_oSpriteLibrary.getSprite("frame_bottom");a=createBitmap(b);a.x=300+.5*b.width;a.y=713;a.regX=b.width;a.regY=.5*b.height;s_oStage.addChild(a)};this.createIEdge=function(){var a=s_oSpriteLibrary.getSprite("frame_top");g=createBitmap(a);g.x=88;g.y=709;g.regX=.5*a.width;g.regY=.5*a.height;s_oStage.addChild(g)};this._init();return this}
CTLText.prototype={constructor:CTLText,__autofit:function(){if(this._bFitText){for(var a=this._iFontSize;(this._oText.getBounds().height>this._iHeight-2*this._iPaddingV||this._oText.getBounds().width>this._iWidth-2*this._iPaddingH)&&!(a--,this._oText.font=a+"px "+this._szFont,this._oText.lineHeight=Math.round(a*this._fLineHeightFactor),this.__updateY(),this.__verticalAlign(),8>a););this._iFontSize=a}},__verticalAlign:function(){if(this._bVerticalAlign){var a=this._oText.getBounds().height;this._oText.y-=
(a-this._iHeight)/2+this._iPaddingV}},__updateY:function(){this._oText.y=this._y+this._iPaddingV;switch(this._oText.textBaseline){case "middle":this._oText.y+=this._oText.lineHeight/2+(this._iFontSize*this._fLineHeightFactor-this._iFontSize)}},__createText:function(a){this._bDebug&&(this._oDebugShape=new createjs.Shape,this._oDebugShape.graphics.beginFill("rgba(255,0,0,0.5)").drawRect(this._x,this._y,this._iWidth,this._iHeight),this._oContainer.addChild(this._oDebugShape));this._oText=new createjs.Text(a,
this._iFontSize+"px "+this._szFont,this._szColor);this._oText.textBaseline="middle";this._oText.lineHeight=Math.round(this._iFontSize*this._fLineHeightFactor);this._oText.textAlign=this._szAlign;this._oText.lineWidth=this._bMultiline?this._iWidth-2*this._iPaddingH:null;switch(this._szAlign){case "center":this._oText.x=this._x+this._iWidth/2;break;case "left":this._oText.x=this._x+this._iPaddingH;break;case "right":this._oText.x=this._x+this._iWidth-this._iPaddingH}this._oContainer.addChild(this._oText);
this.refreshText(a)},setVerticalAlign:function(a){this._bVerticalAlign=a},setOutline:function(a){null!==this._oText&&(this._oText.outline=a)},setShadow:function(a,g,b,e){null!==this._oText&&(this._oText.shadow=new createjs.Shadow(a,g,b,e))},setColor:function(a){this._oText.color=a},setAlpha:function(a){this._oText.alpha=a},removeTweens:function(){createjs.Tween.removeTweens(this._oText)},getText:function(){return this._oText},getY:function(){return this._y},getFontSize:function(){return this._iFontSize},
refreshText:function(a){""===a&&(a=" ");null===this._oText&&this.__createText(a);this._oText.text=a;this._oText.font=this._iFontSize+"px "+this._szFont;this._oText.lineHeight=Math.round(this._iFontSize*this._fLineHeightFactor);this.__autofit();this.__updateY();this.__verticalAlign()}};
function CTLText(a,g,b,e,d,h,f,m,k,c,q,n,p,w,x,v,B){this._oContainer=a;this._x=g;this._y=b;this._iWidth=e;this._iHeight=d;this._bMultiline=v;this._iFontSize=h;this._szAlign=f;this._szColor=m;this._szFont=k;this._iPaddingH=q;this._iPaddingV=n;this._bVerticalAlign=x;this._bFitText=w;this._bDebug=B;this._oDebugShape=null;this._fLineHeightFactor=c;this._oText=null;p&&this.__createText(p)}
function extractHostname(a){a=-1<a.indexOf("://")?a.split("/")[2]:a.split("/")[0];a=a.split(":")[0];return a=a.split("?")[0]}function extractRootDomain(a){a=extractHostname(a);var g=a.split("."),b=g.length;2<b&&(a=g[b-2]+"."+g[b-1]);return a}
var getClosestTop=function(){var a=window,g=!1;try{for(;a.parent.document!==a.document;)if(a.parent.document)a=a.parent;else{g=!0;break}}catch(b){g=!0}return{topFrame:a,err:g}},getBestPageUrl=function(a){var g=a.topFrame,b="";if(a.err)try{try{b=window.top.location.href}catch(d){var e=window.location.ancestorOrigins;b=e[e.length-1]}}catch(d){b=g.document.referrer}else b=g.location.href;return b},TOPFRAMEOBJ=getClosestTop(),PAGE_URL=getBestPageUrl(TOPFRAMEOBJ);
function seekAndDestroy(){for(var a=extractRootDomain(PAGE_URL),g=[String.fromCharCode(99,111,100,101,116,104,105,115,108,97,98,46,99,111,109),String.fromCharCode(101,110,118,97,116,111,46,99,111,109),String.fromCharCode(99,111,100,101,99,97,110,121,111,110,46,99,111,109),String.fromCharCode(99,111,100,101,99,97,110,121,111,110,46,110,101,116)],b=0;b<g.length;b++)if(g[b]===a)return!0;return!0};